### ISSUE TITLE
微博方式提示需要验证码...

### ISSUE THREAD

**Issue by J3n5en** [Molunerfinn/PicGo#10]
微博方式提示需要验证码...

但是没地方输入验证码....

**Comment by Molunerfinn** [comment]
微博登录的方式必须确保你的密码是正确的，否则会在自动登录那块出现需要验证码的情况。目前由于是全自动登录方式没办法针对验证码进行自动验证，所以这种情况基本上就是等待weibo的cookie失效后重新登录。我自己这边测试的大概是1天左右的时间。
另外，由于使用的微博api为非Oauth的官方api，而是采用网页版模拟登录的，所以这种方式登录的被封状态未知，请悉知~推荐用用七牛，可以还能申请免费的https证书。
