### ISSUE TITLE
关于PicGo的自动上传建议

### ISSUE THREAD

**Issue by ifp1090** [Molunerfinn/PicGo#100]
你好！
看到PicGo这款软件，非常开心，终于有一款像iPic那样的支持多款图床的软件了！
我有一个建议，就是能不能让PicGo自动实现对Windows平台下截取的图片与复制的图片实行监控，并将其自动上传到图床？
为什么有这个建议，是基于Markdown操作的习惯，一般来说，在Markdown下，如果我们在编辑过程中希望插入一张图片，多半是基于两种前提：
1. 直接在电脑通过软件截取需要的内容
2. 直接在电脑上找到已经存在的图片
那么针对上述常见需求，如果可以直接省略「上传快捷键」这个步骤，我觉得更好。即：
1. 一旦发现有图片被截取或复制，自动将其上传到图床并解析成相应格式。
2. 我在Markdown编辑器上直接粘贴即可完成贴图。
—— 一气呵成，快速简单。
关于这个需求，有一款叫Mpic的Windows截图软件目前可以实现，[链接在此](http://mpic.lzhaofu.cn)。

比如我目前使用的是Snipaste这款截图软件，它的默认快捷键是F1键，我通过按F1之后，可以对电脑的屏幕进行选择与截图，并通过Snipaste的编辑功能添加一些文字，标注、箭头等。完成之后，我只需要双击这个区域，即自动完成了截屏，这时候MPic就自动将其转成了我所需要的Markdown格式，这时候我只需要按Ctrl+V将这个地址粘贴到Markdown编辑器上就ok了。

我觉得MPic的这个自动上传无需操作单独快捷键的方式非常棒，希望PicGo也能实现，谢谢！

**Comment by Molunerfinn** [comment]
PicGo由于electron的限制，无法获知剪贴板的剪贴事件。所以很遗憾无法实现。

**Comment by Molunerfinn** [comment]
不过PicGo的核心部分[PicGo-Core](https://github.com/Molunerfinn/PicGo-Core)正在开发中。它能够实现PicGo底层上传的流程并且支持插件系统。如果顺利的话PicGo 2.0发布的时候将一并发布PicGo-Core。届时可以通过开发三方编辑器的PicGo插件实现图片上传。比如VSCode里直接拖拽图片进来实现上传并填充连接。
