### ISSUE TITLE
[Bug]: macos突然提示pigco易损坏，无法打开。

### ISSUE THREAD

**Issue by nonozone** [Molunerfinn/PicGo#1001]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [X] [Issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)

### PicGo的版本 | PicGo Version

v2.3.1beta8

### 系统信息 | System Information

Mac(arm64)

### 问题重现 | Bug reproduce

其实我前几天更新完之后，应该是正常用过的，但是今天打开typora，插入图片的时候提示
<img width="260" alt="image" src="https://user-images.githubusercontent.com/1277444/198882144-93033d76-905e-42c0-96f0-edc9fa36a98b.png">

不知道什么原因，重新下载安装也不行，是不是配置文件丢了？

**Comment by Molunerfinn** [comment]
faq最后一条。
