### ISSUE TITLE
[Bug]: 网址后缀不应该是必填项

### ISSUE THREAD

**Issue by you-hengh** [Molunerfinn/PicGo#1002]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [X] [Issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)

### PicGo的版本 | PicGo Version

2.3.1-beta8

### 系统信息 | System Information

Mac(arm64)

### 问题重现 | Bug reproduce

<img width="1158" alt="image" src="https://user-images.githubusercontent.com/34816426/199666866-8206ad3c-4eeb-4ef2-8c57-86d98da7c5e7.png">

又拍云有这一项功能 可以节省网站流量

但是picgo 里又拍云设定网址后缀是必填项 填写这个 图片就无法转成 webp 网站请求的还是原来的图片格式 取消后缀(!)后 网站请求的就是 webp 格式了  

目前 picgo 上传图片返回的地址 都是结尾带后缀(!)的 , 无法让网站请求 webp 格式的图片

希望这个后缀可以改成选填项而不是必填项 这样就可以使用 webp 格式的图片来节省流量了 谢谢

<img width="800" alt="image" src="https://user-images.githubusercontent.com/34816426/199667493-ad348b67-32d1-4c33-908f-d60760e527ee.png">

**Comment by Molunerfinn** [comment]
你好，这个确实是个bug，会在2.3.1正式版里更新，感谢反馈

**Comment by Molunerfinn** [comment]
你可以在界面里随便输入一个后缀点击确定。然后关闭PicGo，手动修改PicGo配置文件，upyun的配置里的options项，改成""即可。
