### ISSUE TITLE
[Bug]: 七牛云+PicGo 链接多了‘/’

### ISSUE THREAD

**Issue by autjuly** [Molunerfinn/PicGo#1004]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [X] [Issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)

### PicGo的版本 | PicGo Version

v2.3.1-beta8

### 系统信息 | System Information

Windows

### 问题重现 | Bug reproduce

七牛云图片上传成功后picgo返回的链接为：http://cdn.kitel.top//img/202211041345377.png
可以看到img前面多个斜杠，这是什么问题？我如果直接在网页中引用，会引发问题，图片不会正常显示。

**Comment by Molunerfinn** [comment]
你自己的访问网址配置里最后一个字符不要加 `/`

**Comment by Molunerfinn** [comment]
![image](https://user-images.githubusercontent.com/12621342/199904249-17dbc271-9c95-4586-9a3e-558285ac59b1.png)
按格式来，自己看

**Comment by autjuly** [comment]
> ![image](https://user-images.githubusercontent.com/12621342/199904249-17dbc271-9c95-4586-9a3e-558285ac59b1.png) 按格式来，自己看

谢谢大大，是我太粗心了。
