### ISSUE TITLE
[Bug]: Mac系统，双击图标没有反应，但是活动监视器有程序

### ISSUE THREAD

**Issue by terrywang1109** [Molunerfinn/PicGo#1007]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [X] [Issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)

### PicGo的版本 | PicGo Version

2.3.1-beta.8

### 系统信息 | System Information

Mac

### 问题重现 | Bug reproduce

大家好，我是mac系统，下载了dmg安装包，然后打不开（最新beta版本和稳定版本都试过）。具体情况是把应用拖进Application文件夹后，双击图标没有反应，是一点反应都没有，但是活动监视器可以看到 Picgo，最上面菜单栏找不到，但bartender里面可以找到，拖到那个位置，就是不显示。
有人遇到了类似情况吗，网上也搜不到这种情况，非常感谢！

**Comment by Molunerfinn** [comment]
请看faq最后一条。

**Comment by terrywang1109** [comment]
多谢多谢，重启，加卸载重装，加输入命令，终于出来了
