### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by glqzk** [Molunerfinn/PicGo#1008]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [X] [Issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)

### PicGo的版本 | PicGo Version

2.3.0

### 系统信息 | System Information

Mac

### 问题重现 | Bug reproduce

![image](https://user-images.githubusercontent.com/30902475/200999783-e7ebea4f-e2ca-4606-bbc0-49c3f7908e72.png)
上传都是正常的，但是没办法显示图片
![image](https://user-images.githubusercontent.com/30902475/200999874-ae28069d-0566-453f-ad84-b48aea1e8558.png)

**Comment by Molunerfinn** [comment]
github图片显示与否跟你的网络环境有关。picgo的相册只是辅助作用。上传是正常的。

**Comment by glqzk** [comment]
已经试过切换多个网络，但是通过picgo上传的图片，均无法在github上正常显示

**Comment by Molunerfinn** [comment]
<img width="1392" alt="image" src="https://user-images.githubusercontent.com/12621342/201004756-02752d18-f5f4-4c0f-9762-b5bee582ccb2.png">
为啥我可以看到你传的图片呢？我说了这是网络问题，你自己检查吧。
