### ISSUE TITLE
增加存储库类型

### ISSUE THREAD

**Issue by ityc** [Molunerfinn/PicGo#101]
## 问题类型

Feature Request

## 功能请求

希望能添加亚马逊S3的接口 很多产品都是兼容亚马逊的接口标准

不知道后期的插件是不是意味着 可以 自己定义存储空间.

如果同时能集成压缩功能,那就更棒了.

---

-EOF-

**Comment by Molunerfinn** [comment]
![image](https://user-images.githubusercontent.com/12621342/44696013-527dbd80-aaa8-11e8-955c-6d9542bd49eb.png)

**Comment by Molunerfinn** [comment]
2.0插件说明可以查看我的知乎回答：

你最近在造什么有趣的前端(node)轮子？ - 皮蛋的回答 - 知乎
https://www.zhihu.com/question/288119376/answer/460462428
