### ISSUE TITLE
[Feature]: 支持存储路径使用变量

### ISSUE THREAD

**Issue by serfend** [Molunerfinn/PicGo#1010]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [X] [Issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)

### PicGo的版本 | PicGo Version

v2.3.1

### 系统信息 | System Information

Windows

### 功能请求 | Feature request

```json
{
    "github": {
      "repo": "serfend/res.image.reference",
      "branch": "main",
      "token": "ghp_jsuLZDY3MTdjOGRkNThhZDdhYTJ",
      "path": "img{year}{month}/{day}",
      "customUrl": ""
    }
}
```
path 支持填入变量

**Comment by Molunerfinn** [comment]
本体不考虑，已有插件支持。

**Comment by serfend** [comment]
本体或可在配置文件提供统一路径配置，以支持各插件读取
