### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by zxclovetotti** [Molunerfinn/PicGo#1012]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [X] [Issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)

### PicGo的版本 | PicGo Version

v2.3.1

### 系统信息 | System Information

Mac(arm64)

### 问题重现 | Bug reproduce

macOS 13.0.1 (22A400) 升级安装PicGo 2.3.1正式版后无法打开

报错提示如下：
<img width="677" alt="image" src="https://user-images.githubusercontent.com/9988834/201841707-aba22b9c-ff28-475b-85f0-7245ed7e2d60.png">

**Comment by Molunerfinn** [comment]
![image](https://user-images.githubusercontent.com/12621342/201843717-2e214c3b-719b-40e3-b405-f0a732400f1a.png)
![image](https://user-images.githubusercontent.com/12621342/201843774-f0b487b8-db55-486d-baee-5361e23a3199.png)

**Comment by zxclovetotti** [comment]
问题已解决。谢谢回复
