### ISSUE TITLE
[Bug]: ubuntu20.0.4上上传不了图片

### ISSUE THREAD

**Issue by liuxiaohui1221** [Molunerfinn/PicGo#1013]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [X] [Issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)

### PicGo的版本 | PicGo Version

V2.3.1

### 系统信息 | System Information

Linux

### 问题重现 | Bug reproduce

在ubuntu20.0.4系统下安装AppImage版本，选择本地图片上传均失败，提示：请检查你的配置项以及网络

### 相关日志 | Logs

下面是报错信息：
(base) kemove@kemove-MS-7D25:~/software$ ./PicGo-2.3.1.AppImage -appimage-extract
on ready

startup true
[PicGo INFO]: [PicGo Server] is listening at 36677
[PicGo INFO]: Before transform
[PicGo INFO]: Transforming... Current transformer is [path]
[PicGo INFO]: Before upload
[PicGo INFO]: beforeUploadPlugins: renameFn running
[PicGo INFO]: Uploading... Current uploader is [github]
[PicGo WARN]: failed
[PicGo ERROR]: {
  method: 'PUT',
  url: 'https://api.github.com/repos/liuxiaohui1221/Repo_PicGo/contents/img/2019819904.jpg',
  statusCode: 404,
  message: 'Request failed with status code 404',
  stack: {},
  response: {
    status: 404,
    statusCode: 404,
    body: {
      message: 'Branch master not found',
      documentation_url: 'https://docs.github.com/rest/reference/repos#create-or-update-file-contents'
    }
  }
}
[PicGo ERROR]: {
  method: 'PUT',
  url: 'https://api.github.com/repos/liuxiaohui1221/Repo_PicGo/contents/img/2019819904.jpg',
  statusCode: 404,
  message: 'Request failed with status code 404',
  stack: {},
  response: {
    status: 404,
    statusCode: 404,
    body: {
      message: 'Branch master not found',
      documentation_url: 'https://docs.github.com/rest/reference/repos#create-or-update-file-contents'
    }
  }
}

**Comment by liuxiaohui1221** [comment]
![图片](https://user-images.githubusercontent.com/23338827/201990756-fad3ee90-38ee-4b76-ae68-266143d1fc2f.png)

**Comment by liuxiaohui1221** [comment]
Github换成Gitee后可以上传了

**Comment by balalalawjx** [comment]
github还是不行吗？我用github一直报404

**Comment by liuxiaohui1221** [comment]
嗯，所以才换成了gitee



xiao_辉
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Molunerfinn/PicGo"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年12月2日(星期五) 凌晨1:07
***@***.***&gt;;
***@***.***&gt;;"State ***@***.***&gt;;
主题:&nbsp;Re: [Molunerfinn/PicGo] [Bug]: ubuntu20.0.4上上传不了图片 (Issue #1013)





 
github还是不行吗？我用github一直报404
