### ISSUE TITLE
[bug]: 

### ISSUE THREAD

**Issue by Ivan-MuTang** [Molunerfinn/PicGo#1017]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [X] [Issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)

### PicGo的版本 | PicGo Version

V2.3.1

### 系统信息 | System Information

Windows

### 问题重现 | Bug reproduce

[疑问]: 自建简单图床 - EasyImage，通知自动定WEB插件设置上传，实侧可以上传，通过网页后台可以看到图片，但是在PICGO相册里没有任何显示。

**Comment by Molunerfinn** [comment]
请联系插件方适配新版picgo。
