### ISSUE TITLE
[Bug]: 2.3.1正式版安装后上传报错

### ISSUE THREAD

**Issue by wjie0309** [Molunerfinn/PicGo#1018]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [X] [Issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)

### PicGo的版本 | PicGo Version

v2.3.1

### 系统信息 | System Information

Windows

### 问题重现 | Bug reproduce

我使用笔记软件 obsidian 以及其插件 'Image auto upload plugin' 来在写笔记的时候可以直接在软件中粘贴上传图片.

图床使用的是 vika.

在更新完2.3.1后发现会报下图中的错误.

![image](https://user-images.githubusercontent.com/90775300/202759042-8956d73d-99a8-4448-86e3-9db01190caef.png)

为了控制变量我也尝试了直接在 picgo 上传图片, 从本地, 微信截图, 以及网站上右键复制图片都试过了, 报了一样的错.

### 相关日志 | Logs

2022-11-19 01:45:22 [PicGo INFO] [PicGo Server] upload result:  
2022-11-19 01:45:22 [PicGo WARN] [PicGo Server] upload failed, see picgo.log for more detail ↑ 
2022-11-19 01:45:39 [PicGo INFO] [PicGo Server] shutdown 
2022-11-19 01:45:45 [PicGo INFO] [PicGo Server] is listening at 36677 
2022-11-19 01:45:49 [PicGo INFO] [PicGo Server] get the request  
2022-11-19 01:45:49 [PicGo INFO] [PicGo Server] upload clipboard file 
2022-11-19 01:45:50 [PicGo INFO] Before transform 
2022-11-19 01:45:50 [PicGo INFO] beforeTransformPlugins: vika running 
2022-11-19 01:45:50 [PicGo INFO] Transforming... Current transformer is [path] 
2022-11-19 01:45:50 [PicGo INFO] Before upload 
2022-11-19 01:45:50 [PicGo INFO] beforeUploadPlugins: vika running 
2022-11-19 01:45:50 [PicGo INFO] beforeUploadPlugins: renameFn running 
2022-11-19 01:45:50 [PicGo INFO] Uploading... Current uploader is [vika] 
2022-11-19 01:45:50 [PicGo WARN] failed 
2022-11-19 01:45:50 [PicGo ERROR] {
  "method": "POST",
  "url": "",
  "statusCode": 0,
  "message": "Cannot read properties of null (reading 'replace')",
  "stack": "Error: Cannot read properties of null (reading 'replace')\n    at dispatchHttpRequest (D:\\ProgramData\\picgo\\resources\\app.asar\\node_modules\\picgo\\node_modules\\axios\\lib\\adapters\\http.js:161:23)\n    at new Promise (<anonymous>)\n    at httpAdapter (D:\\ProgramData\\picgo\\resources\\app.asar\\node_modules\\picgo\\node_modules\\axios\\lib\\adapters\\http.js:49:10)\n    at dispatchRequest (D:\\ProgramData\\picgo\\resources\\app.asar\\node_modules\\picgo\\node_modules\\axios\\lib\\core\\dispatchRequest.js:58:10)\n    at async Uploader.uploadAttachmentsToEachRecord (C:\\Users\\wjie\\AppData\\Roaming\\picgo\\node_modules\\picgo-plugin-vikadata\\dist\\uploader.js:47:38)\n    at async Uploader.handle (C:\\Users\\wjie\\AppData\\Roaming\\picgo\\node_modules\\picgo-plugin-vikadata\\dist\\uploader.js:138:13)\n    at async Object.handle (C:\\Users\\wjie\\AppData\\Roaming\\picgo\\node_modules\\picgo-plugin-vikadata\\dist\\index.js:59:17)\n    at async $e.doUpload (D:\\ProgramData\\picgo\\resources\\app.asar\\node_modules\\picgo\\dist\\index.cjs.js:1:17198)\n    at async $e.start (D:\\ProgramData\\picgo\\resources\\app.asar\\node_modules\\picgo\\dist\\index.cjs.js:1:15969)\n    at async Tt.upload (D:\\ProgramData\\picgo\\resources\\app.asar\\node_modules\\picgo\\dist\\index.cjs.js:1:71624)",
  "response": {
    "status": 0,
    "statusCode": 0,
    "body": ""
  }
} 
2022-11-19 01:45:50 [PicGo ERROR] {
  "method": "POST",
  "url": "",
  "statusCode": 0,
  "message": "Cannot read properties of null (reading 'replace')",
  "stack": "Error: Cannot read properties of null (reading 'replace')\n    at dispatchHttpRequest (D:\\ProgramData\\picgo\\resources\\app.asar\\node_modules\\picgo\\node_modules\\axios\\lib\\adapters\\http.js:161:23)\n    at new Promise (<anonymous>)\n    at httpAdapter (D:\\ProgramData\\picgo\\resources\\app.asar\\node_modules\\picgo\\node_modules\\axios\\lib\\adapters\\http.js:49:10)\n    at dispatchRequest (D:\\ProgramData\\picgo\\resources\\app.asar\\node_modules\\picgo\\node_modules\\axios\\lib\\core\\dispatchRequest.js:58:10)\n    at async Uploader.uploadAttachmentsToEachRecord (C:\\Users\\wjie\\AppData\\Roaming\\picgo\\node_modules\\picgo-plugin-vikadata\\dist\\uploader.js:47:38)\n    at async Uploader.handle (C:\\Users\\wjie\\AppData\\Roaming\\picgo\\node_modules\\picgo-plugin-vikadata\\dist\\uploader.js:138:13)\n    at async Object.handle (C:\\Users\\wjie\\AppData\\Roaming\\picgo\\node_modules\\picgo-plugin-vikadata\\dist\\index.js:59:17)\n    at async $e.doUpload (D:\\ProgramData\\picgo\\resources\\app.asar\\node_modules\\picgo\\dist\\index.cjs.js:1:17198)\n    at async $e.start (D:\\ProgramData\\picgo\\resources\\app.asar\\node_modules\\picgo\\dist\\index.cjs.js:1:15969)\n    at async Tt.upload (D:\\ProgramData\\picgo\\resources\\app.asar\\node_modules\\picgo\\dist\\index.cjs.js:1:71624)",
  "response": {
    "status": 0,
    "statusCode": 0,
    "body": ""
  }
} 
2022-11-19 01:45:50 [PicGo INFO] [PicGo Server] upload result:  
2022-11-19 01:45:50 [PicGo WARN] [PicGo Server] upload failed, see picgo.log for more detail ↑ 
2022-11-19 01:46:27 [PicGo INFO] [PicGo Server] get the request  
2022-11-19 01:46:27 [PicGo INFO] [PicGo Server] upload clipboard file 
2022-11-19 01:46:28 [PicGo INFO] Before transform 
2022-11-19 01:46:28 [PicGo INFO] beforeTransformPlugins: vika running 
2022-11-19 01:46:28 [PicGo INFO] Transforming... Current transformer is [path] 
2022-11-19 01:46:28 [PicGo INFO] Before upload 
2022-11-19 01:46:28 [PicGo INFO] beforeUploadPlugins: vika running 
2022-11-19 01:46:28 [PicGo INFO] beforeUploadPlugins: renameFn running 
2022-11-19 01:46:28 [PicGo INFO] Uploading... Current uploader is [vika] 
2022-11-19 01:46:28 [PicGo WARN] failed 
2022-11-19 01:46:28 [PicGo ERROR] {
  "method": "POST",
  "url": "",
  "statusCode": 0,
  "message": "Cannot read properties of null (reading 'replace')",
  "stack": "Error: Cannot read properties of null (reading 'replace')\n    at dispatchHttpRequest (D:\\ProgramData\\picgo\\resources\\app.asar\\node_modules\\picgo\\node_modules\\axios\\lib\\adapters\\http.js:161:23)\n    at new Promise (<anonymous>)\n    at httpAdapter (D:\\ProgramData\\picgo\\resources\\app.asar\\node_modules\\picgo\\node_modules\\axios\\lib\\adapters\\http.js:49:10)\n    at dispatchRequest (D:\\ProgramData\\picgo\\resources\\app.asar\\node_modules\\picgo\\node_modules\\axios\\lib\\core\\dispatchRequest.js:58:10)\n    at async Uploader.uploadAttachmentsToEachRecord (C:\\Users\\wjie\\AppData\\Roaming\\picgo\\node_modules\\picgo-plugin-vikadata\\dist\\uploader.js:47:38)\n    at async Uploader.handle (C:\\Users\\wjie\\AppData\\Roaming\\picgo\\node_modules\\picgo-plugin-vikadata\\dist\\uploader.js:138:13)\n    at async Object.handle (C:\\Users\\wjie\\AppData\\Roaming\\picgo\\node_modules\\picgo-plugin-vikadata\\dist\\index.js:59:17)\n    at async $e.doUpload (D:\\ProgramData\\picgo\\resources\\app.asar\\node_modules\\picgo\\dist\\index.cjs.js:1:17198)\n    at async $e.start (D:\\ProgramData\\picgo\\resources\\app.asar\\node_modules\\picgo\\dist\\index.cjs.js:1:15969)\n    at async Tt.upload (D:\\ProgramData\\picgo\\resources\\app.asar\\node_modules\\picgo\\dist\\index.cjs.js:1:71624)",
  "response": {
    "status": 0,
    "statusCode": 0,
    "body": ""
  }
} 
2022-11-19 01:46:28 [PicGo ERROR] {
  "method": "POST",
  "url": "",
  "statusCode": 0,
  "message": "Cannot read properties of null (reading 'replace')",
  "stack": "Error: Cannot read properties of null (reading 'replace')\n    at dispatchHttpRequest (D:\\ProgramData\\picgo\\resources\\app.asar\\node_modules\\picgo\\node_modules\\axios\\lib\\adapters\\http.js:161:23)\n    at new Promise (<anonymous>)\n    at httpAdapter (D:\\ProgramData\\picgo\\resources\\app.asar\\node_modules\\picgo\\node_modules\\axios\\lib\\adapters\\http.js:49:10)\n    at dispatchRequest (D:\\ProgramData\\picgo\\resources\\app.asar\\node_modules\\picgo\\node_modules\\axios\\lib\\core\\dispatchRequest.js:58:10)\n    at async Uploader.uploadAttachmentsToEachRecord (C:\\Users\\wjie\\AppData\\Roaming\\picgo\\node_modules\\picgo-plugin-vikadata\\dist\\uploader.js:47:38)\n    at async Uploader.handle (C:\\Users\\wjie\\AppData\\Roaming\\picgo\\node_modules\\picgo-plugin-vikadata\\dist\\uploader.js:138:13)\n    at async Object.handle (C:\\Users\\wjie\\AppData\\Roaming\\picgo\\node_modules\\picgo-plugin-vikadata\\dist\\index.js:59:17)\n    at async $e.doUpload (D:\\ProgramData\\picgo\\resources\\app.asar\\node_modules\\picgo\\dist\\index.cjs.js:1:17198)\n    at async $e.start (D:\\ProgramData\\picgo\\resources\\app.asar\\node_modules\\picgo\\dist\\index.cjs.js:1:15969)\n    at async Tt.upload (D:\\ProgramData\\picgo\\resources\\app.asar\\node_modules\\picgo\\dist\\index.cjs.js:1:71624)",
  "response": {
    "status": 0,
    "statusCode": 0,
    "body": ""
  }
} 
2022-11-19 01:46:28 [PicGo INFO] [PicGo Server] upload result:  
2022-11-19 01:46:28 [PicGo WARN] [PicGo Server] upload failed, see picgo.log for more detail ↑ 
2022-11-19 01:48:39 [PicGo INFO] Before transform 
2022-11-19 01:48:39 [PicGo INFO] beforeTransformPlugins: vika running 
2022-11-19 01:48:39 [PicGo INFO] Transforming... Current transformer is [path] 
2022-11-19 01:48:39 [PicGo INFO] Before upload 
2022-11-19 01:48:39 [PicGo INFO] beforeUploadPlugins: vika running 
2022-11-19 01:48:39 [PicGo INFO] beforeUploadPlugins: renameFn running 
2022-11-19 01:48:39 [PicGo INFO] Uploading... Current uploader is [vika] 
2022-11-19 01:48:39 [PicGo WARN] failed 
2022-11-19 01:48:39 [PicGo ERROR] {
  "method": "POST",
  "url": "",
  "statusCode": 0,
  "message": "Cannot read properties of null (reading 'replace')",
  "stack": "Error: Cannot read properties of null (reading 'replace')\n    at dispatchHttpRequest (D:\\ProgramData\\picgo\\resources\\app.asar\\node_modules\\picgo\\node_modules\\axios\\lib\\adapters\\http.js:161:23)\n    at new Promise (<anonymous>)\n    at httpAdapter (D:\\ProgramData\\picgo\\resources\\app.asar\\node_modules\\picgo\\node_modules\\axios\\lib\\adapters\\http.js:49:10)\n    at dispatchRequest (D:\\ProgramData\\picgo\\resources\\app.asar\\node_modules\\picgo\\node_modules\\axios\\lib\\core\\dispatchRequest.js:58:10)\n    at async Uploader.uploadAttachmentsToEachRecord (C:\\Users\\wjie\\AppData\\Roaming\\picgo\\node_modules\\picgo-plugin-vikadata\\dist\\uploader.js:47:38)\n    at async Uploader.handle (C:\\Users\\wjie\\AppData\\Roaming\\picgo\\node_modules\\picgo-plugin-vikadata\\dist\\uploader.js:138:13)\n    at async Object.handle (C:\\Users\\wjie\\AppData\\Roaming\\picgo\\node_modules\\picgo-plugin-vikadata\\dist\\index.js:59:17)\n    at async $e.doUpload (D:\\ProgramData\\picgo\\resources\\app.asar\\node_modules\\picgo\\dist\\index.cjs.js:1:17198)\n    at async $e.start (D:\\ProgramData\\picgo\\resources\\app.asar\\node_modules\\picgo\\dist\\index.cjs.js:1:15969)\n    at async Tt.upload (D:\\ProgramData\\picgo\\resources\\app.asar\\node_modules\\picgo\\dist\\index.cjs.js:1:71270)",
  "response": {
    "status": 0,
    "statusCode": 0,
    "body": ""
  }
} 
2022-11-19 01:48:39 [PicGo ERROR] {
  "method": "POST",
  "url": "",
  "statusCode": 0,
  "message": "Cannot read properties of null (reading 'replace')",
  "stack": "Error: Cannot read properties of null (reading 'replace')\n    at dispatchHttpRequest (D:\\ProgramData\\picgo\\resources\\app.asar\\node_modules\\picgo\\node_modules\\axios\\lib\\adapters\\http.js:161:23)\n    at new Promise (<anonymous>)\n    at httpAdapter (D:\\ProgramData\\picgo\\resources\\app.asar\\node_modules\\picgo\\node_modules\\axios\\lib\\adapters\\http.js:49:10)\n    at dispatchRequest (D:\\ProgramData\\picgo\\resources\\app.asar\\node_modules\\picgo\\node_modules\\axios\\lib\\core\\dispatchRequest.js:58:10)\n    at async Uploader.uploadAttachmentsToEachRecord (C:\\Users\\wjie\\AppData\\Roaming\\picgo\\node_modules\\picgo-plugin-vikadata\\dist\\uploader.js:47:38)\n    at async Uploader.handle (C:\\Users\\wjie\\AppData\\Roaming\\picgo\\node_modules\\picgo-plugin-vikadata\\dist\\uploader.js:138:13)\n    at async Object.handle (C:\\Users\\wjie\\AppData\\Roaming\\picgo\\node_modules\\picgo-plugin-vikadata\\dist\\index.js:59:17)\n    at async $e.doUpload (D:\\ProgramData\\picgo\\resources\\app.asar\\node_modules\\picgo\\dist\\index.cjs.js:1:17198)\n    at async $e.start (D:\\ProgramData\\picgo\\resources\\app.asar\\node_modules\\picgo\\dist\\index.cjs.js:1:15969)\n    at async Tt.upload (D:\\ProgramData\\picgo\\resources\\app.asar\\node_modules\\picgo\\dist\\index.cjs.js:1:71270)",
  "response": {
    "status": 0,
    "statusCode": 0,
    "body": ""
  }
} 
2022-11-19 01:51:33 [PicGo INFO] [PicGo Server] is listening at 36677 
2022-11-19 01:51:52 [PicGo INFO] [PicGo Server] get the request  
2022-11-19 01:51:52 [PicGo INFO] [PicGo Server] upload clipboard file 
2022-11-19 01:51:53 [PicGo INFO] Before transform 
2022-11-19 01:51:53 [PicGo INFO] beforeTransformPlugins: vika running 
2022-11-19 01:51:53 [PicGo INFO] Transforming... Current transformer is [path] 
2022-11-19 01:51:53 [PicGo INFO] Before upload 
2022-11-19 01:51:53 [PicGo INFO] beforeUploadPlugins: vika running 
2022-11-19 01:51:53 [PicGo INFO] beforeUploadPlugins: renameFn running 
2022-11-19 01:51:53 [PicGo INFO] Uploading... Current uploader is [vika] 
2022-11-19 01:51:56 [PicGo INFO] afterUploadPlugins: vika running 
2022-11-19 01:51:56 [PicGo SUCCESS] 
https://s1.vika.cn/space/2022/11/19/c3659bf4153048f9882e6d2170af1343

**Comment by Molunerfinn** [comment]
请去vika插件仓库反馈

**Comment by Molunerfinn** [comment]
vika 插件旧版本没有适配新版本的 picgo， 更新vika插件到最新版本即可。插件的问题，建议直接去插件仓库提问。
