### ISSUE TITLE
[Feature]: Picgo 2.3.1 默认安装后右键菜单没有了吗？

### ISSUE THREAD

**Issue by LarryKHite** [Molunerfinn/PicGo#1019]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [X] [Issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)

### PicGo的版本 | PicGo Version

2.3.1

### 系统信息 | System Information

Windows

### 功能请求 | Feature request

之前老版本都有右键菜单的，现在没有了很不习惯，不会是我电脑问题吧？

**Comment by Molunerfinn** [comment]
应该是更新了electron-builder之后，默认的安装脚本没有装上导致的。下个版本会修复。

**Comment by Molunerfinn** [comment]
https://github.com/Molunerfinn/PicGo/blob/dev/build/installer.nsh

**Comment by Molunerfinn** [comment]
另外，右键菜单只会在文件上右键才能出现。

**Comment by Molunerfinn** [comment]
![image](https://user-images.githubusercontent.com/12621342/202853900-685b2374-1c34-4f90-bedd-400b9b9f53f2.png)
