### ISSUE TITLE
[Bug]: github配置正确但是无法上传，出现statusCode=405错误

### ISSUE THREAD

**Issue by csxueyue** [Molunerfinn/PicGo#1023]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [X] [Issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)

### PicGo的版本 | PicGo Version

v2.3.1

### 系统信息 | System Information

Windows

### 问题重现 | Bug reproduce

具体描述如下：
图床为 github
具体可能原因已经排除：

1. token 没有失效
2. 在仓库直接 add file 是成功的
3. 重装了一次 picgo 也不行
4. 配置检查了很多遍还是一样的

### 相关日志 | Logs

2022-11-23 19:31:52 [PicGo ERROR] {
  "method": "PUT",
  "url": "https://api.github.com/repos/csxueyue/ImageBed/contents/black.png",
  "statusCode": 0,
  "message": "tunneling socket could not be established, statusCode=405",
  "stack": "Error: tunneling socket could not be established, statusCode=405\n    at ClientRequest.onConnect (D:\\AZ\\PicGo\\resources\\app.asar\\node_modules\\tunnel\\lib\\tunnel.js:154:19)\n    at Object.onceWrapper (node:events:514:26)\n    at ClientRequest.emit (node:events:394:28)\n    at Socket.socketOnData (node:_http_client:525:11)\n    at Socket.emit (node:events:394:28)\n    at addChunk (node:internal/streams/readable:315:12)\n    at readableAddChunk (node:internal/streams/readable:289:9)\n    at Socket.Readable.push (node:internal/streams/readable:228:10)\n    at TCP.onStreamRead (node:internal/stream_base_commons:199:23)",
  "response": {
    "status": 0,
    "statusCode": 0,
    "body": ""
  }
}

**Comment by Molunerfinn** [comment]
网络问题请按FAQ自行解决。

**Comment by Molunerfinn** [comment]
github作为图床的情况，建议配置 PicGo 的上传代理再使用，国内的环境对于 github 接口非常不友好。
