### ISSUE TITLE
[Bug]: arm版本下载后损坏

### ISSUE THREAD

**Issue by VegeBun-csj** [Molunerfinn/PicGo#1024]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [X] [Issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)

### PicGo的版本 | PicGo Version

2.3.1 arm

### 系统信息 | System Information

Mac(arm64)

### 问题重现 | Bug reproduce

下载后安装，然后打开就直接出现这个问题
<img width="249" alt="image" src="https://user-images.githubusercontent.com/39252213/203675903-22c22c78-7d29-4401-aacd-df95fdaec7b8.png">

**Comment by Molunerfinn** [comment]
看FAQ最后一条，都不看为啥要勾呢？
![image](https://user-images.githubusercontent.com/12621342/203676451-4797e79a-ace1-4292-9509-4fa42fc94e87.png)

**Comment by scypurple** [comment]
> 看FAQ最后一条，都不看为啥要勾呢？ ![image](https://user-images.githubusercontent.com/12621342/203676451-4797e79a-ace1-4292-9509-4fa42fc94e87.png)
和提问者一样的配置， 我按照faq的做了以后，顶部栏也没图标，无法打开主页面。但typora上传图片会跳出来上传失败的通知

**Comment by Molunerfinn** [comment]
> > 看FAQ最后一条，都不看为啥要勾呢？ ![image](https://user-images.githubusercontent.com/12621342/203676451-4797e79a-ace1-4292-9509-4fa42fc94e87.png)
> > 和提问者一样的配置， 我按照faq的做了以后，顶部栏也没图标，无法打开主页面。但typora上传图片会跳出来上传失败的通知

![image](https://user-images.githubusercontent.com/12621342/203750107-08c88018-9909-45fc-be83-9c9598dd0742.png)

**Comment by scypurple** [comment]
> > > 看FAQ最后一条，都不看为啥要勾呢？ ![image](https://user-images.githubusercontent.com/12621342/203676451-4797e79a-ace1-4292-9509-4fa42fc94e87.png)
> 
> > > 和提问者一样的配置， 我按照faq的做了以后，顶部栏也没图标，无法打开主页面。但typora上传图片会跳出来上传失败的通知
> 
> 
> 
> ![image](https://user-images.githubusercontent.com/12621342/203750107-08c88018-9909-45fc-be83-9c9598dd0742.png)
> 
> 

重启过了
