### ISSUE TITLE
[Bug]: “PicGo” is damaged and can’t be opened. You should move it to the Trash.

### ISSUE THREAD

**Issue by ZhizhouTian** [Molunerfinn/PicGo#1025]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [X] [Issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)

### PicGo的版本 | PicGo Version

lastest

### 系统信息 | System Information

Mac

### 问题重现 | Bug reproduce

```bash
# brew install picgo --cask
==> Downloading https://github.com/Molunerfinn/PicGo/releases/download/v2.3.1/PicGo-2.3.1-arm64.dmg
Already downloaded: /Users/tianzz/Library/Caches/Homebrew/downloads/a0082319ba8f80fa74e8222157709a9581ac300715777fe600397ab2ce4b8785--PicGo-2.3.1-arm64.dmg
==> Installing Cask picgo
==> Moving App 'PicGo.app' to '/Applications/PicGo.app'
🍺  picgo was successfully installed!


# ./PicGo
```
<img width="260" alt="image" src="https://user-images.githubusercontent.com/13183390/203952327-84a3aad9-3f06-46c0-8c42-37e0ceaab0c1.png">

**Comment by Molunerfinn** [comment]
![image](https://user-images.githubusercontent.com/12621342/203962044-361fe300-16ea-4029-9491-44ce9866009c.png)
FAQ最后一条。

**Comment by whitewatercn** [comment]
[解决macos应用打不开，报错“XXX.app” is damaged and can’t be opened. You should move it to the Trash - 🛠工具与编程 - 始徒Beginner](https://forum.beginner.center/t/topic/2689): https://forum.beginner.center/t/topic/2689

**Comment by Molunerfinn** [comment]
picgo mac 版本目前已经有签名，可以直接下载安装

**Comment by whitewatercn** [comment]
> picgo mac 版本目前已经有签名，可以直接下载安装

测试了一下，近期通过brew安装的mac  2.5.2版本依然会报错

<img width="260" height="250" alt="Image" src="https://github.com/user-attachments/assets/8fee1ca8-e19d-4e46-bdb8-bc25f57ed20e" />

brew应该是从github直接拉的release
https://github.com/Homebrew/homebrew-cask/blob/HEAD/Casks/p/picgo.rb

**Comment by Molunerfinn** [comment]
> > picgo mac 版本目前已经有签名，可以直接下载安装
> 
> 测试了一下，近期通过brew安装的mac 2.5.2版本依然会报错
> 
> <img alt="Image" width="260" height="250" src="https://private-user-images.githubusercontent.com/58654928/561998674-8fee1ca8-e19d-4e46-bdb8-bc25f57ed20e.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NzMyODkyODEsIm5iZiI6MTc3MzI4ODk4MSwicGF0aCI6Ii81ODY1NDkyOC81NjE5OTg2NzQtOGZlZTFjYTgtZTE5ZC00ZTQ2LWJkYjgtYmMyNWY1N2VkMjBlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNjAzMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjYwMzEyVDA0MTYyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgwYWUwOWFlMTkzMWE5MTkyOGQxYzA4OTk4NTkyNjEwNGM1M2FiNjJkNGY5OGJjNGY3MDdmNzYwMDVkNzU0MTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.6vMLuLfPRFQ8eQMKAhUYYPIqaFMd58KStL21oFs3MyU">
> brew应该是从github直接拉的release [Homebrew/homebrew-cask@`HEAD`/Casks/p/picgo.rb](https://github.com/Homebrew/homebrew-cask/blob/HEAD/Casks/p/picgo.rb?rgh-link-date=2026-03-12T03%3A53%3A34.000Z)

那就不知道了，你直接通过 github release 下载应该是正常的，我刚刚还试了下 2.5.3 是正常的

<img width="260" height="260" alt="Image" src="https://github.com/user-attachments/assets/ed90d06d-68c7-4b95-a970-5b1ce31f62ab" />

**Comment by whitewatercn** [comment]
> > > picgo mac 版本目前已经有签名，可以直接下载安装
> > 
> > 
> > 测试了一下，近期通过brew安装的mac 2.5.2版本依然会报错
> > <img alt="Image" width="260" height="250" src="https://private-user-images.githubusercontent.com/58654928/561998674-8fee1ca8-e19d-4e46-bdb8-bc25f57ed20e.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NzMyODkyODEsIm5iZiI6MTc3MzI4ODk4MSwicGF0aCI6Ii81ODY1NDkyOC81NjE5OTg2NzQtOGZlZTFjYTgtZTE5ZC00ZTQ2LWJkYjgtYmMyNWY1N2VkMjBlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNjAzMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjYwMzEyVDA0MTYyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgwYWUwOWFlMTkzMWE5MTkyOGQxYzA4OTk4NTkyNjEwNGM1M2FiNjJkNGY5OGJjNGY3MDdmNzYwMDVkNzU0MTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.6vMLuLfPRFQ8eQMKAhUYYPIqaFMd58KStL21oFs3MyU">
> > brew应该是从github直接拉的release [Homebrew/homebrew-cask@`HEAD`/Casks/p/picgo.rb](https://github.com/Homebrew/homebrew-cask/blob/HEAD/Casks/p/picgo.rb?rgh-link-date=2026-03-12T03%3A53%3A34.000Z)
> 
> 那就不知道了，你直接通过 github release 下载应该是正常的，我刚刚还试了下 2.5.3 是正常的
> 
> <img alt="Image" width="260" height="260" src="https://private-user-images.githubusercontent.com/12621342/562005765-ed90d06d-68c7-4b95-a970-5b1ce31f62ab.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NzMyOTQzMzgsIm5iZiI6MTc3MzI5NDAzOCwicGF0aCI6Ii8xMjYyMTM0Mi81NjIwMDU3NjUtZWQ5MGQwNmQtNjhjNy00Yjk1LWE5NzAtNWIxY2UzMWY2MmFiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNjAzMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjYwMzEyVDA1NDAzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgzYTg4YTk1NGY3MTMzNTVhYzFmNzIxNTZkYTkxYWIzMzhjN2ZiZGZhNGE5MWE2NjJmNDM3MWNlZWFiNTc3MjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.A-f5unUtOqw-qZQhUFFlxo2TweDPULtqnIX-tZ9TI7s">

那很奇怪了，不知道为什么，但是没关系我brew用惯了，执行一下就行
```
xattr -cr /Applications/PicGo.app/
```
