### ISSUE TITLE
[Bug]: Github上传成功，PicGo无法自动复制链接且提示失败：socket hang up

### ISSUE THREAD

**Issue by 7more0** [Molunerfinn/PicGo#1026]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [X] [Issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)

### PicGo的版本 | PicGo Version

v2.3.1

### 系统信息 | System Information

Windows

### 问题重现 | Bug reproduce

+ 上传剪贴板图像到Github可在仓库找到上传文件，本地提示上传失败且无法复制链接
![image](https://user-images.githubusercontent.com/61447970/203992192-606785f6-bd47-42a4-a62d-ac72c7c54f9c.png)

### 相关日志 | Logs

2022-11-25 20:57:05 [PicGo INFO] Before transform 
2022-11-25 20:57:05 [PicGo INFO] Transforming... Current transformer is [path] 
2022-11-25 20:57:05 [PicGo INFO] Before upload 
2022-11-25 20:57:05 [PicGo INFO] beforeUploadPlugins: renameFn running 
2022-11-25 20:57:05 [PicGo INFO] Uploading... Current uploader is [github] 
2022-11-25 20:57:06 [PicGo WARN] failed 
2022-11-25 20:57:06 [PicGo ERROR] {
  "method": "PUT",
  "url": "https://api.github.com/repos/***********/contents/imgs_2022/202211252057948.png",
  "statusCode": 0,
  "message": "socket hang up",
  "stack": "Error: socket hang up\n    at connResetException (node:internal/errors:691:14)\n    at TLSSocket.socketOnEnd (node:_http_client:471:23)\n    at TLSSocket.emit (node:events:406:35)\n    at endReadableNT (node:internal/streams/readable:1343:12)\n    at processTicksAndRejections (node:internal/process/task_queues:83:21)",
  "response": {
    "status": 0,
    "statusCode": 0,
    "body": ""
  }
} 
2022-11-25 20:57:06 [PicGo ERROR] {
  "method": "PUT",
  "url": "https://api.github.com/repos/********/contents/imgs_2022/202211252057948.png",
  "statusCode": 0,
  "message": "socket hang up",
  "stack": "Error: socket hang up\n    at connResetException (node:internal/errors:691:14)\n    at TLSSocket.socketOnEnd (node:_http_client:471:23)\n    at TLSSocket.emit (node:events:406:35)\n    at endReadableNT (node:internal/streams/readable:1343:12)\n    at processTicksAndRejections (node:internal/process/task_queues:83:21)",
  "response": {
    "status": 0,
    "statusCode": 0,
    "body": ""
  }
}

**Comment by Molunerfinn** [comment]
这是你的网络问题 我无法帮你解决。建议配置picgo代理再使用github图床 或者使用国内图床。
