### ISSUE TITLE
[Bug]: 空格url字符被转成了空格，在一些平台中无法显示

### ISSUE THREAD

**Issue by chrisyy2003** [Molunerfinn/PicGo#1027]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [X] [Issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)

### PicGo的版本 | PicGo Version

2.3

### 系统信息 | System Information

Mac

### 问题重现 | Bug reproduce

图片地址中含有空格，在typora中文件是能够显示，但是在hexo和其他其他平台无法显示

我的本地typora
<img width="571" alt="image" src="https://user-images.githubusercontent.com/63803385/204072261-6191d194-eccc-40ba-a908-338ed773d32c.png">
其他平台
<img width="970" alt="image" src="https://user-images.githubusercontent.com/63803385/204072274-65c5e3cf-c5f5-47f1-a20a-da4887223188.png">

此外从picgo中复制地址是没有url编码的，但是在我的oss中地址是url编码过的

oss中的信息
<img width="626" alt="image" src="https://user-images.githubusercontent.com/63803385/204072305-5e77719d-23e2-494f-af77-e6c564099ee8.png">

**Comment by Molunerfinn** [comment]
请更新2.3.1。
