### ISSUE TITLE
[Bug]: 开机多个 PicGo 启动项

### ISSUE THREAD

**Issue by MYXXTS** [Molunerfinn/PicGo#1028]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [X] [Issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)

### PicGo的版本 | PicGo Version

PicGo - 2.3.1 - beta.8

### 系统信息 | System Information

Windows

### 问题重现 | Bug reproduce

设置软件开机自启之后，短时间内，开机启动项只有一个，后续电脑重新启动之后启动项就变成了两个，如图：
![image](https://user-images.githubusercontent.com/51087760/204165754-622aeb5d-823b-4577-9b1d-b7934334f3d5.png)
后续通过工具查看，发现两个启动项名称不同外，其余的描述、签名、包括路径均指向同一个内容，如图：
![image](https://user-images.githubusercontent.com/51087760/204165817-bd28ab7a-85c3-438b-ab8a-ec44beeb6411.png)

**Comment by MYXXTS** [comment]
补充：
应用内选项开机自启控制的是名为 com.molunerfinn.picgo	PicGo	(Not Verified) GitHub, Inc.
而另外出现的是 electron.app.PicGo	PicGo	(Not Verified) GitHub, Inc.

**Comment by Molunerfinn** [comment]
感谢反馈。后续有空再看看
