### ISSUE TITLE
Feature Request: 上传后保留完整HTTP响应报文

### ISSUE THREAD

**Issue by zombie110year** [Molunerfinn/PicGo#103]
# Feature Request

## PicGo的相关信息

PicGo Version 1.6.2
System: Windows10

## 功能请求

作者您好, 请问 PicGo 在上传图片后能保存完整的 HTTP 响应报文吗? 目前的 PicGo 只保留了图片的链接地址, 要删除图片也只能在本地删除. 而一些图床(例如 [SM.MS](https://sm.ms/doc/) ) 在响应报文中提供了用于删除图片的连接.

希望 PicGo 能够将图片与对应的报文一起保存起来. 谢谢!

---

如果您不准备在此版本中实现该功能的话, 期待能为您的 PicGo-Core 开发插件🙂.

**Comment by Molunerfinn** [comment]
这个需求太过小众。不会在本体里实现。欢迎通过插件实现
