### ISSUE TITLE
[Feature]: 访问云端文件

### ISSUE THREAD

**Issue by 233Xie** [Molunerfinn/PicGo#1033]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [X] [Issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)

### PicGo的版本 | PicGo Version

v2.3.1

### 系统信息 | System Information

Windows

### 功能请求 | Feature request

希望可以在PicGo里面直接访问、编辑云端文件，比如我用阿里云，一个bucket里面有不同设备上传的图片，但是通过阿里云网页访问有点麻烦了，通过微信传链接还不如通过阿里云网页访问

**Comment by Molunerfinn** [comment]
感谢反馈 但是picgo本身不是为了做云盘控制台。后续会开放更多能力让插件去实现。
