### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by zsp-1080** [Molunerfinn/PicGo#1034]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [X] [Issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)

### PicGo的版本 | PicGo Version

v2.3.1

### 系统信息 | System Information

Mac

### 问题重现 | Bug reproduce

使用阿里oss，windows已经可以正常使用，使用mac时反复确认过填入的设置信息，还是出现了错误。

### 相关日志 | Logs

2022-12-04 20:20:15 [PicGo ERROR] {
  "stack": "Error: read ECONNRESET\n    at TLSWrap.onStreamRead (node:internal/stream_base_commons:220:20)",
2022-12-04 20:20:15 [PicGo ERROR] 
------Error Stack Begin------
Error: [object Object]
-------Error Stack End------- 
2022-12-04 20:20:15 [PicGo ERROR] 
------Error Stack Begin------
Error: [object Object]
-------Error Stack End-------

**Comment by Molunerfinn** [comment]
报错信息提示了这是你的网络问题。通常是代理设置不当导致的。建议如果开启全局代理的情况 需要给picgo单独设置上传代理。
