### ISSUE TITLE
[Bug]: picgo上传图片url可以打开，但是放到网页里面图片就打不开了

### ISSUE THREAD

**Issue by zhang1446802857** [Molunerfinn/PicGo#1036]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [X] [Issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)

### PicGo的版本 | PicGo Version

2.3.1 beta.8

### 系统信息 | System Information

Windows

### 问题重现 | Bug reproduce

![image](https://user-images.githubusercontent.com/87363443/205559702-963f55d9-52e7-4da5-a210-bed65fef3c38.png)

上传都是没问题，就是没法放到网站里用，GitHub可能是和网络有关系，但是gitee也是不行

**Comment by Molunerfinn** [comment]
这跟picgo有什么关系？

**Comment by zhang1446802857** [comment]
外链从picgo生成的啊

**Comment by zhang1446802857** [comment]
不支持放在网页吗？

**Comment by zhang1446802857** [comment]
只能自己点链接看吗
？

**Comment by Molunerfinn** [comment]
支持放网页啊，但是图片访问不了是你的网络问题啊，跟picgo有什么关系呢？你可以搜一下访问不了的报错信息是啥意思
![image](https://user-images.githubusercontent.com/12621342/205580111-ee0f92df-44a4-4287-a13c-799884972e6b.png)
picgo负责图片上传，把URL给到你，但是并不是说picgo上传的图片URL你一定能访问到，这个跟你实际的网络环境有关系。
就github而言，国内基本已经墙了github的静态资源链接，你如果还要继续用github做图床，请自行配置代理
