### ISSUE TITLE
[Bug]: Windows系统软件安装出错

### ISSUE THREAD

**Issue by huawuque404** [Molunerfinn/PicGo#1038]
### 前置阅读 | Pre-reading

- [x] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [X] [Issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)

### PicGo的版本 | PicGo Version

v2.3.1 Latest

### 系统信息 | System Information

Windows

### 问题重现 | Bug reproduce

安装过程中出错，Windows10系统

安装过程中出现以下
![R9T6}TKR$XMFXX$W 5F%O}H](https://user-images.githubusercontent.com/109327586/206392899-032291c8-4e34-45df-b94d-533df4b0d243.png)

点击重试出现以下
![}X_ 54 OYV{GT4U5DIYX@_S](https://user-images.githubusercontent.com/109327586/206393013-62c7ee1f-8fc3-4d3c-952a-445991baaad1.png)

点击中止之后，系统本地没有在指定路径新建程序文件夹

**Comment by huawuque404** [comment]
有了新的进展，当选择为所有用户安装时，可以成功，如果选择本机用户安装，就会出错

**Comment by Molunerfinn** [comment]
安装picgo的时候请关闭再安装。

**Comment by huawuque404** [comment]
不好意思，没太理解您的意思，请问您说的关闭是关闭什么呢？

**Comment by Molunerfinn** [comment]
> 不好意思，没太理解您的意思，请问您说的关闭是关闭什么呢？

请退出picgo之后再运行安装程序

**Comment by chinesehuazhou** [comment]
遇到了同样的问题，出问题后，想要卸载，在应用中能看到它占用了392M，但是卸载失败。在本地目录中看不到任何安装内容。
安装时，也是选了只为当前用户安装
