### ISSUE TITLE
[Bug]: 图片无法上传

### ISSUE THREAD

**Issue by zhengyongtao** [Molunerfinn/PicGo#1039]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [X] [Issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)

### PicGo的版本 | PicGo Version

2.3.1

### 系统信息 | System Information

Mac

### 问题重现 | Bug reproduce

图片上传失败，不论是否勾选`使用内置剪贴板上传`都是相同的结果。
日志显示
```
------Error Stack Begin------
Error: ENOENT: no such file or directory, open '/Users/username/Library/Application Support/picgo/picgo-clipboard-images/202212121745646.png.2363083632'
-------Error Stack End------- 
```
回退到2.3.0版本可以正常使用，怀疑是2.3.1引入的bug。

### 相关日志 | Logs

2022-12-10 09:37:53 [PicGo ERROR] startup error
------Error Stack Begin------
Error: unexpected end of file
    at Zlib.zlibOnError [as onerror] (zlib.js:168:17)
-------Error Stack End-------
2022-12-10 09:38:48 [PicGo INFO] [PicGo Server] is listening at 36677 
2022-12-10 09:38:48 [PicGo ERROR] startup error
------Error Stack Begin------
Error: unexpected end of file
    at Zlib.zlibOnError [as onerror] (zlib.js:168:17)
-------Error Stack End-------
2022-12-10 09:39:35 [PicGo INFO] [PicGo Server] shutdown 
2022-12-10 09:40:07 [PicGo INFO] [PicGo Server] is listening at 36677 
2022-12-12 17:45:53 [PicGo ERROR] 
------Error Stack Begin------
Error: ENOENT: no such file or directory, open '/Users/zhengyongtao/Library/Application Support/picgo/picgo-clipboard-images/202212121745888.png.617039141'
-------Error Stack End------- 
2022-12-12 17:45:56 [PicGo ERROR] 
------Error Stack Begin------
Error: ENOENT: no such file or directory, open '/Users/zhengyongtao/Library/Application Support/picgo/picgo-clipboard-images/202212121745450.png.1802205871'
-------Error Stack End------- 
2022-12-12 17:45:56 [PicGo ERROR] 
------Error Stack Begin------
Error: ENOENT: no such file or directory, open '/Users/zhengyongtao/Library/Application Support/picgo/picgo-clipboard-images/202212121745646.png.2363083632'
-------Error Stack End-------

**Comment by zhengyongtao** [comment]
![image](https://user-images.githubusercontent.com/23188362/207042007-f866eab4-1e4c-4b47-a3e5-69be3a707a65.png)
![image](https://user-images.githubusercontent.com/23188362/207042049-a5ee56c0-39c7-4feb-a6af-83674b195605.png)
没有安装插件

**Comment by HasonHuang** [comment]
+1

**Comment by Molunerfinn** [comment]
> 

报错也是同样的找不到 `picgo-clipboard-images` 目录下的 `${times}.png.xxxxx`  这样的文件么？

**Comment by zhengyongtao** [comment]
> > 
> 
> 报错也是同样的找不到 `picgo-clipboard-images` 目录下的 `${times}.png.xxxxx` 这样的文件么？

是这样的，@HasonHuang 提供的解决方法对我适用，在 `/Users/xxx/Library/Application Support/picgo/` 下创建 `picgo-clipboard-images` 就可以正常使用了。

**Comment by juhuan** [comment]
> +1 我是这样解决：进入目录 `YOUR_APP_HOME/picgo/` 手动创建目录 `picgo-clipboard-images`。 之后就可以上传。

太牛逼了，困扰我很久的问题

**Comment by Molunerfinn** [comment]
2.4.0-beta.1 新增 PicGo 修复工具箱，能检查出这种情况，可以更新试试。
