### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by cloudycloudzhang** [Molunerfinn/PicGo#1040]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [X] [Issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)

### PicGo的版本 | PicGo Version

PicGo-2.3.1-arm64

### 系统信息 | System Information

Mac(arm64)

### 问题重现 | Bug reproduce

安装后不显示picgo 的图标，顶部栏也没有。 很苦恼。 mac pro M1 。 已经自行查找问题，始终找不到原因。用的其他图床软件，也都不显示图标，导致无法设置。

**Comment by Molunerfinn** [comment]
faq最后一条。

**Comment by cloudycloudzhang** [comment]
- macOS 安装好之后，PicGo 是不会弹出主窗口的，因为 PicGo 在 macOS 系统里设计是个顶部栏应用。注意看你顶部栏的图标，如果有 PicGo 的图标，说明安装成功了，点击图标即可打开顶部栏窗口。

已经 检查，顶部栏没有该图标。。。
---
- 如果你是 M1 的系统，此前装过 PicGo 的 x64 版本，但是后来更新了 arm64 的版本发现打开后没反应，请重启电脑即可。

已经重新电脑没有反应。另外，尝试了试用其他的图床软件，顶部栏也都没有图标。。。

**Comment by cloudycloudzhang** [comment]
macOS 安装好之后，PicGo 是不会弹出主窗口的，因为 PicGo 在 macOS 系统里设计是个顶部栏应用。注意看你顶部栏的图标，如果有 PicGo 的图标，说明安装成功了，点击图标即可打开顶部栏窗口。
- 已经 检查，顶部栏没有该图标。。。
如果你是 M1 的系统，此前装过 PicGo 的 x64 版本，但是后来更新了 arm64 的版本发现打开后没反应，请重启电脑即可。
- 已经重新电脑没有反应。另外，尝试了试用其他的图床软件，顶部栏也都没有图标。。。

**Comment by Molunerfinn** [comment]
那你应该检查你电脑的问题了。。。

**Comment by cloudycloudzhang** [comment]
> 



> 那你应该检查你电脑的问题了。。。

bug已经解决。最后确认为 顶部的图标太多，无法显示picgo图标。最终解决办法为：安装了一个顶部栏管理工具，成功将图标拉了出来。供大家参考。
