### ISSUE TITLE
[Bug]: typora上传图片上传成功但是不显示，picgo相册里面也没有显示，图片url没有问题

### ISSUE THREAD

**Issue by LiKunBiao** [Molunerfinn/PicGo#1041]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [X] [Issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)

### PicGo的版本 | PicGo Version

PicGo-Setup-2.3.0-x64

### 系统信息 | System Information

Windows

### 问题重现 | Bug reproduce

![image](https://user-images.githubusercontent.com/102348109/207625809-95fc627a-7ce1-4a00-8539-bdfcce10fea4.png)
图片url可以在浏览器访问

**Comment by Molunerfinn** [comment]
请更新版本
