### ISSUE TITLE
[Bug]: 更新版本之后 app 打不开

### ISSUE THREAD

**Issue by Carina957** [Molunerfinn/PicGo#1042]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [X] [Issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)

### PicGo的版本 | PicGo Version

v2.3.1

### 系统信息 | System Information

Mac(arm64)

### 问题重现 | Bug reproduce

<img width="805" alt="image" src="https://user-images.githubusercontent.com/56385216/208005058-a9f4cb87-6231-4fa9-8087-56e890e22ad6.png">

正常从 homebrew 上按照最新版本之后，打开之后是这样的：

<img width="260" alt="image" src="https://user-images.githubusercontent.com/56385216/208005288-fc33ca03-b61e-4276-a1ce-042e3b650f58.png">

我的电脑系统版本目前是 Macos 13.1 (22C65)

**Comment by Molunerfinn** [comment]
请问你看过faq最后一条吗？
