### ISSUE TITLE
[Bug]: 2.3.1下载无法安装?

### ISSUE THREAD

**Issue by jianfengye** [Molunerfinn/PicGo#1043]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [X] [Issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)

### PicGo的版本 | PicGo Version

2.3.1

### 系统信息 | System Information

Mac(arm64)

### 问题重现 | Bug reproduce

从github或者腾讯云下载mac arm64的版本，2.3.1，下载后打开出现问题
<img width="260" alt="image" src="https://user-images.githubusercontent.com/1316468/208278781-c25e757d-0576-427e-b01a-468feecfad2c.png">

**Comment by jianfengye** [comment]
忽略，按照https://zhuanlan.zhihu.com/p/135948430 解决了

**Comment by Molunerfinn** [comment]
我很好奇，为啥这个问题 FAQ 里写得清清楚楚，还是不断有人发重复的issue。以及为何你没看 FAQ 就勾上呢？

![image](https://user-images.githubusercontent.com/12621342/208280318-08c255cc-5e73-4176-984a-a344890333ae.png)

**Comment by Molunerfinn** [comment]
![image](https://user-images.githubusercontent.com/12621342/208280357-6739e051-6af9-45fa-a4a1-9b5d834149f7.png)
真的都是眼瞎么
