### ISSUE TITLE
[Feature]: 提供一个配置项，隐藏菜单栏图标

### ISSUE THREAD

**Issue by yeshiqing** [Molunerfinn/PicGo#1045]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [X] [Issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)

### PicGo的版本 | PicGo Version

v2.3.1

### 系统信息 | System Information

Mac

### 功能请求 | Feature request

能否像 Alfred 一样，给提供一个配置项，隐藏菜单栏图标？我不想引入顶部栏管理应用。
![image](https://user-images.githubusercontent.com/11813936/208900926-ac8d4be5-af7a-4e3c-b605-9f93308ab45c.png)

菜单栏的 icon 一旦隐藏，不方便再次重现。Alfred 的做法是在应用内增设一个 Alfred Preference 应用，这个应用是 Dock 应用，而非菜单栏应用。在这里面设置 icon 是否在菜单栏显示。

可以参考Alfred troubleshooting：https://www.alfredapp.com/help/troubleshooting/hidden-menubar-icon/

**Comment by Molunerfinn** [comment]
可以考虑实现

**Comment by feiquan666** [comment]
附议

**Comment by Molunerfinn** [comment]
先行提供 dock 显示功能，顶部栏隐藏功能目前可以通过一些第三方软件实现。
