### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by xunEin10** [Molunerfinn/PicGo#1046]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [X] [Issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)

### PicGo的版本 | PicGo Version

2.3.1

### 系统信息 | System Information

Mac(arm64)

### 问题重现 | Bug reproduce

安装PicGo并按照FAQ最后一条成功启动之后，顶部栏无法找到picgo图标，使用cmd+shift+p只会报错上传失败，没有任何办法打开主界面，activity monitor中可以看到picgo进程信息。

### 相关日志 | Logs

主界面打不开无法找到log，，，

**Comment by xunEin10** [comment]
问题已解决，macOS的顶部栏显示bug问题，与picgo无关

**Comment by Molunerfinn** [comment]
> 问题已解决，macOS的顶部栏显示bug问题，与picgo无关

如何解决的也欢迎issue里说明，方便后续相同问题用户解决~
