### ISSUE TITLE
[Feature]: 让应用程序可以在底部程序栏显示

### ISSUE THREAD

**Issue by feiquan666** [Molunerfinn/PicGo#1049]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [X] [Issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)

### PicGo的版本 | PicGo Version

2.3.1

### 系统信息 | System Information

Mac(arm64)

### 功能请求 | Feature request

因为 mac 刘海屏的原因，顶部栏空间严重不足，在有些情况下，程序在顶部栏无法显示。必须要关闭其他顶部栏程序才可以。

**Comment by Molunerfinn** [comment]
跟 #1045 重复，在 #1045 里处理。

**Comment by mouyong** [comment]
mac 刘海屏真实了。。。虽然可以用 hidden bar.但是需要展开的时候还是不方便。我是把它常驻了。
<img width="1025" alt="image" src="https://user-images.githubusercontent.com/10336437/210220864-b438c9f6-9985-46ca-a011-86da056e4fea.png">
