### ISSUE TITLE
【功能建议】加入启动最小化到托盘选项

### ISSUE THREAD

**Issue by cooper1x** [Molunerfinn/PicGo#105]
## 问题类型
Feature Request

## PicGo的相关信息
系统：Windows10 1803 x64
软件版本：PicGo v1.6.2

## 功能请求
建议加入【启动时缩小到右下角托盘图标】的功能，这个配合开机启动就不会出现开机弹出窗口了。

**Comment by Molunerfinn** [comment]
右下角图标只有windows有。不适合其他平台。所以可能可以考虑开机启动的时候启动迷你窗口。

**Comment by cooper1x** [comment]
@Molunerfinn 这样也是可以的，另外这个悬浮球最好能加一个置顶的选项，有时候别的窗口最大化了就看不见了。

**Comment by Molunerfinn** [comment]
嗯，迷你窗口置顶功能之后会提供。

**Comment by cooper1x** [comment]
@Molunerfinn 另外希望支持网页图片拖拽可以上传到图床的功能，这样就免去下载再上传这一个繁琐的步骤。刚刚我试着把我的github头像图片拖拽进去，显示正在上传后消失就没有了。

**Comment by Molunerfinn** [comment]
这个功能涉及的点比较多，需要考量。
另外这个其实不需要下载的。你直接右键复制图片，然后快捷键上传即可。

**Comment by Molunerfinn** [comment]
已在此[commit](https://github.com/Molunerfinn/PicGo/commit/f309d18aed0990c7abe4d7969d61e1a25489371e)更新，会与2.0版本一起发布。
