### ISSUE TITLE
[Feature]: 相册是否支持显示文件名呢？

### ISSUE THREAD

**Issue by mouyong** [Molunerfinn/PicGo#1050]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [X] [Issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)

### PicGo的版本 | PicGo Version

v2.3.1

### 系统信息 | System Information

Mac(arm64)

### 功能请求 | Feature request

期望相册支持显示文件名，以及上传的不是可预览的图片时，能有默认的 placeholder 图片。

<img width="779" alt="image" src="https://user-images.githubusercontent.com/10336437/209790217-871b7cc8-efe9-4267-a856-3df7f5403ff1.png">

**Comment by Molunerfinn** [comment]
会考虑实现，感谢反馈

**Comment by mouyong** [comment]
pr 提交了，可以参考一下。下面是预览图

<img width="796" alt="image" src="https://user-images.githubusercontent.com/10336437/209804256-0bafc4b0-5416-4876-a23d-15966863eaf5.png">

<img width="190" alt="image" src="https://user-images.githubusercontent.com/10336437/209804212-26e16f21-85a2-45cd-93bc-d7693c03be48.png">

**Comment by mouyong** [comment]
<img width="797" alt="image" src="https://user-images.githubusercontent.com/10336437/209805643-18bba873-50e9-4925-9048-1ec95c01d1df.png">

不行。还得大佬修复。我无法完成复制。第一个文件上传后，点击不到复制按钮。

**Comment by mouyong** [comment]
<img width="800" alt="image" src="https://user-images.githubusercontent.com/10336437/209805997-e29e3644-fd28-4a3e-8e25-0f539800a7b1.png">

点击复制的按钮之后很久才提示复制成功。不知道为啥。

**Comment by Molunerfinn** [comment]
回头我处理一下

**Comment by Molunerfinn** [comment]
我才你这里上传的并非图片格式的文件，这样会导致图片标签加载不符合预期，同时notification里因为要加载图片会加载成如你图示里的视频文件，会导致下载时间过长。

这里不是简单显示文件名能处理的。图片无法显示是符合预期的情况

**Comment by mouyong** [comment]
没关系的，需要的功能其实只是显示出上传过这个文件。以及文件的名字。

对了，上传完成能支持通知 webhook 地址不？

还有个问题。1G以上的大文件上传和下载有比较好的方案吗。

因为是内网线上线下组网的，大文件上传会有点慢，下载也有点慢。

目前是做了一套转码程序，大视频上传到内网后，转码程序转成m3u8进行点播，然后在线web后台设置视频的资讯信息，就可以在小程序加载了。

**Comment by Molunerfinn** [comment]
picgo初衷不是用来做大文件上传下载的，这方面有更专业的工具，你可以尝试搜索。

上传完成后的功能，你可以自行开发插件实现。https://picgo.github.io/PicGo-Core-Doc/zh/dev-guide/cli.html#afteruploadplugins

**Comment by mouyong** [comment]
有地方可以查看 picgo 的 node 版本吗，我想确定下是不是因为版本高了导致无法进行 dev 预览开发。

我的 node 默认版本是 v16.14.0, nvm 版本是 0.39.1, yarn 版本是 1.22.19

**Comment by Molunerfinn** [comment]
node 16就行。dev开发时，需要把安装版退出

**Comment by mouyong** [comment]
https://github.com/zjsxdyw/file-chunk-upload 大文件上传下载的方案有了。参考借鉴这个。

**Comment by mouyong** [comment]
有退出呢，启动yarn dev后，mac 的程序坞有个 electron 软件。但是没有开启任何程序。菜单没东西。

今天运行，直接提示报错。不知道咋解决，前几天还可以写代码后 build。但是效率很低。

<img width="1515" alt="image" src="https://user-images.githubusercontent.com/10336437/210048927-8c4bf2a5-81fd-4a5e-bc05-bb986d850716.png">

**Comment by mouyong** [comment]
移除项目目录下的 main 后，执行效果如下图

<img width="1283" alt="image" src="https://user-images.githubusercontent.com/10336437/210049096-1d5bf1be-c84a-43c0-8840-833a9e4d36f7.png">

**Comment by mouyong** [comment]
噢，没退出导致的。

退出后，运行了，看不到界面。只有个图标在下方

<img width="1709" alt="image" src="https://user-images.githubusercontent.com/10336437/210049262-dcdf0021-1a80-4ab8-a049-41682bafe497.png">

**Comment by mouyong** [comment]
有了。估计是之前菜单栏图标太多了，然后被摄像头挡住了，所以看不到

<img width="1209" alt="image" src="https://user-images.githubusercontent.com/10336437/210049420-627039d5-175c-4dc3-8b5f-1b90632be496.png">

**Comment by mouyong** [comment]
显示文件名这个太重要了，用在区分文件方面很方便。其他类型的文件，期望可以有个默认的占位图。

**Comment by mouyong** [comment]
期望能在上传的时候切换同一个插件下的其他配置。这样方便将不同的文件上传到不同的地方。然后 menu icon 也能支持切换操作，这样不用打开主窗口，使用会更方便。

<img width="1013" alt="image" src="https://user-images.githubusercontent.com/10336437/210049647-03c4d433-7e80-465f-bfcb-7e3893661eb6.png">

<img width="844" alt="image" src="https://user-images.githubusercontent.com/10336437/210049664-abf1ccc3-edb6-4633-9387-357bde623683.png">

**Comment by mouyong** [comment]
menu 的上传等待区。粘贴板的图片预览操作。如果图片过大，会加载好一会。建议放按钮，粘贴板图片，点击后触发上传就可以了。

**Comment by mouyong** [comment]
https://file.keking.cn/

通过集成这个kkfileview，可以达到预览绝大多数文件的目的。不知道相册的位置能通过插件增加按钮吗

**Comment by Molunerfinn** [comment]
> https://file.keking.cn/
> 
> 
> 
> 通过集成这个kkfileview，可以达到预览绝大多数文件的目的。不知道相册的位置能通过插件增加按钮吗。
> 
> 
> 
> 示例：
> 
> https://file.keking.cn/onlinePreview?url=aHR0cDovL2ZpbGVzLmhlY3MuaXdud2ViLmNvbS9vdXRzaXRlX2xpbmsvMjAyMjEyMzEwMDExODUzLnBuZw%3D%3D

不考虑。后续会开放插件接入webview，插件自行可以绘制界面。本体相册不做复杂逻辑。

**Comment by Molunerfinn** [comment]
> menu 的上传等待区。粘贴板的图片预览操作。如果图片过大，会加载好一会。建议放按钮，粘贴板图片，点击后触发上传就可以了。

放图片是为了二次确认，图片过大会导致主进程和渲染进程传输数据大，这个无法避免。如果你已经很确定要上传的图片，可以直接使用快捷键上传。
