### ISSUE TITLE
[Feature]: 菜单栏的预览能否支持显示名字呢

### ISSUE THREAD

**Issue by mouyong** [Molunerfinn/PicGo#1054]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [X] [Issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)

### PicGo的版本 | PicGo Version

dev

### 系统信息 | System Information

Mac(arm64)

### 功能请求 | Feature request

菜单栏的预览能否支持显示名字呢，当多个文件上传后，会连续显示几个默认图的文件，看不到文件名。

<img width="196" alt="image" src="https://user-images.githubusercontent.com/10336437/210170025-85151894-43ca-4549-a41f-64119275b388.png">

**Comment by Molunerfinn** [comment]
后续会补充文件名

**Comment by mouyong** [comment]
大佬霸气

**Comment by mouyong** [comment]
哇，刚发现快捷切换图床配置的功能支持了，好棒，这个太赞了。大佬方便加个联系方式交流嘛。

<img width="384" alt="image" src="https://user-images.githubusercontent.com/10336437/210214455-9cdda2e5-3d8c-4e6b-b619-b41e6aaf76ca.png">

<img width="904" alt="image" src="https://user-images.githubusercontent.com/10336437/210214472-8ffe2f7b-846c-4a1f-984d-db4ef6f5826b.png">

**Comment by mouyong** [comment]
大佬，要不要考虑用 vitepress 更新下文档站点。我来自荐了：http://mouyong.github.io/vitepress-doc-website/

**Comment by Molunerfinn** [comment]
> 大佬，要不要考虑用 vitepress 更新下文档站点。我来自荐了：[http://mouyong.github.io/vitepress-doc-website](http://mouyong.github.io/vitepress-doc-website/)

暂时没必要换，文档站点目前用的 vuepress 没啥问题。

**Comment by mouyong** [comment]
哈哈哈，好滴
