### ISSUE TITLE
[Bug]: arm64文件已损坏

### ISSUE THREAD

**Issue by Jesslynwong** [Molunerfinn/PicGo#1055]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [X] [Issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)

### PicGo的版本 | PicGo Version

2.3.1

### 系统信息 | System Information

Mac(arm64)

### 问题重现 | Bug reproduce

arm64文件已损坏

**Comment by p1Kk** [comment]
我也出现了这样的错误，请问您是如何解决的？（我是MacOS 13.1）

**Comment by songtianlun** [comment]
发现这样可以解决

```bash
sudo xattr -d com.apple.quarantine "/Applications/PicGo.app"
```

参考：https://github.com/1zilc/fishing-funds/issues/149#issuecomment-928044197

**Comment by HLTangbinbin** [comment]
> ```shell
> sudo xattr -d com.apple.quarantine "/Applications/PicGo.app"
> ```

这个方法可以解决应用已损坏的提示
