### ISSUE TITLE
[Feature]: 可以在菜单增加一个上传文件吗

### ISSUE THREAD

**Issue by mouyong** [Molunerfinn/PicGo#1056]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [X] [Issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)

### PicGo的版本 | PicGo Version

dev

### 系统信息 | System Information

Windows

### 功能请求 | Feature request

[Feature]: 可以在菜单增加一个上传文件吗，这样就不用点开主窗口，这样就不用记忆快捷键。快捷键好像只能上传文件。上传区没有这个限制。

<img width="202" alt="image" src="https://user-images.githubusercontent.com/10336437/210251762-f19843b8-f1c4-4617-97f4-f6186cbc9693.png">

**Comment by mouyong** [comment]
这样就不用点开主窗口，这样就不用记忆快捷键。快捷键好像只能上传文件。上传区没有这个限制

**Comment by Molunerfinn** [comment]
不考虑。picgo是图片上传工具。

**Comment by Molunerfinn** [comment]
另外，顶部菜单栏图标是可以拖拽上传的。

**Comment by mouyong** [comment]
拖拽上传和选择上传有点点不一样。
选择上传是打开文件选择器，再找文件。

拖拽上传要先选文件，再去拖拽。

**Comment by mouyong** [comment]
@Molunerfinn 大佬，这个交互的不同是暂时不考虑增加嘛，确定的话我再看看怎能处理这个使用便捷性问题。

**Comment by Molunerfinn** [comment]
对 不考虑

**Comment by mouyong** [comment]
好的👌

**Comment by mouyong** [comment]
用触控板和用鼠标，在这两种交互的体验下，会有比较大的差别

**Comment by mouyong** [comment]
@Molunerfinn 那这个算是主体的功能不：

快捷上传到指定图床，目的是省去切换配置的操作，能快速完成上传并获取到对应的图片域名。

有点类似和设置图床的交互。

不同的图传到对应的图传下。拖拽必须先改默认图床，再去选文件上传。

<img width="398" alt="image" src="https://user-images.githubusercontent.com/10336437/210292667-e7687fe7-7eba-42a8-90c0-3613306a2fe8.png">

**Comment by Molunerfinn** [comment]
> 好的👌，那如果 PR 呢？

不接受，这个不符合预期。

**Comment by Molunerfinn** [comment]
你可以自行fork自行构建

**Comment by mouyong** [comment]
> @Molunerfinn 那这个算是主体的功能不：
> 
> 快捷上传到指定图床，目的是省去切换配置的操作，能快速完成上传，获取到对应的图片访问域名。
> 
> 有点类似和设置图床的交互。
> 
> 不同的图传到对应的图床下。拖拽必须先改默认图床，再去选文件上传。
> 
> ```
> 快捷上传
>     - 直接上传(当前图床：GitHub)
>     - 选择图床
>         - 七牛云
>             - 账号 A
>             - 账号 B
>         - SFTP
>             - 配置 A
>             - 配置 B
>         - GitHub
>             - 仓库 A
>             - 仓库 B
> ```
> 
> <img alt="image" width="398" src="https://user-images.githubusercontent.com/10336437/210292667-e7687fe7-7eba-42a8-90c0-3613306a2fe8.png">

@Molunerfinn 这个你看看是否也是自行处理，不做合并的需求呢？

**Comment by mouyong** [comment]
是的话我找个时间按照你说的方式处理下。

**Comment by Molunerfinn** [comment]
picgo的架构目前是单图床多配置，但是每次上传只能使用一份配置，配置需要先确认再使用。这里加一个菜单，后续很多涉及到快捷上传的部分都需要改交互。

这里不是短期实现目标，2.4.0版本的 PicGo 不考虑。

**Comment by Molunerfinn** [comment]
还是那句话，如果你有自己的独立需求，如果我觉得也OK，我会考虑自己实现或者采纳你的PR。如果我觉得不合理，也欢迎你自行fork自行处理

**Comment by mouyong** [comment]
那会官方支持嘛，不在 2.4.0 的话我可以等等。不计划支持的话我就想办法处理。代码质量可能差点，勉强满足使用也可以

**Comment by mouyong** [comment]
其实就是确认下这个是否属于会合并的需求。或者是否属于某个计划范围内的需求。

**Comment by mouyong** [comment]
2种方式决定了处理结果：
属于计划内的，分为短期计划，长期计划。这种类型可以考虑等待官方或者fork后pr。
属于计划外的，只能考虑 fork 后自行构建，不做 pr。

**Comment by mouyong** [comment]
https://github.com/Molunerfinn/PicGo/projects/9 这里是目前的 2.4.0 的计划。只是不确定这个需求是否可能归属于未来计划的一部分。

**Comment by Molunerfinn** [comment]
这里涉及到的一个点是，远期 PicGo 的目标是支持多配置同时上传

因此对于快捷上传这里会考虑的更多，暂时不会按照本issue规范进行处理

不过短期内的一个可以实现的是通过快捷键快速切换配置，这里会扩展快捷键系统，补充诸如

- 打开主窗口
- 打开顶部栏窗口
- 切换配置

等可自定义快捷键

**Comment by mouyong** [comment]
要不要开启一个讨论区。github 的 discussions 功能。这样目前我们的讨论人家也可以看得到。能了解到计划，相关讨论之类的。
https://github.com/Molunerfinn/PicGo/discussions

**Comment by mouyong** [comment]
好的。这个不错

**Comment by mouyong** [comment]
快捷键打开配置选择框，完成配置切换，快捷键选择上传。这两个都是快捷键的话也是能满足这种文件要上传到不同地方，获取对应域名的需求。

**Comment by Molunerfinn** [comment]
> 要不要开启一个讨论区。github 的 discussions 功能。这样目前我们的讨论人家也可以看得到。能了解到计划，相关讨论之类的。 [Molunerfinn/PicGo/discussions](https://github.com/Molunerfinn/PicGo/discussions)

以前开过，后来关了。主要是因为很多人发issue发现要模板，就不发了，直接转去discussions，导致discussions变成了随意发帖的issue区，不好管理。

**Comment by mouyong** [comment]
还有这样的人啊！

**Comment by mouyong** [comment]
那 mini 窗口增加一个点击上传，这个是否可以呀。

这样拖拽交互和选择交互都有了。

打开主窗口虽然是打开了上传区，但是增加了操作路径。还需要主动关闭窗口。

**Comment by Molunerfinn** [comment]
mini窗口本身就可以点击上传

**Comment by mouyong** [comment]
是粘贴板的图片加载后，在 mini 预览，然后点击待上传区的图片，进行上传吗，如果想上传的图片不是粘贴板的，希望选择其他图，是不是目前只能考虑上传区的点击，或者将图片拖拽到icon上呢。

**Comment by Molunerfinn** [comment]
你说的mini窗口跟我说的不一样。我说的是windows和linux上才有的mini窗口。

mac的这个窗口是顶部栏窗口。顶部栏窗口的点击上传确实是有缺失，后续看看往哪里塞个按钮进去。

**Comment by mouyong** [comment]
哦哦，原来那个叫做顶部栏窗口

**Comment by mouyong** [comment]
可以往菜单塞一个，或者往预览页塞一个。这两个位置都算是方便的交互。

一个是左键点击，一个是右键点击，操作路径长度相同。

**Comment by mouyong** [comment]
如果后期有计划增加快捷上传的菜单。那这个会推荐增加在预览页进行上传。

**Comment by mouyong** [comment]
相当于一个是上传到了默认的图床，

一个是上传到了切换的图床。

**Comment by Molunerfinn** [comment]
> 可以往菜单塞一个，或者往预览页塞一个。这两个位置都算是方便的交互。
> 
> 一个是左键点击，一个是右键点击，操作路径长度相同。

只会在顶部栏窗口里加一个点击上传，是为了和windows和linux的mini窗口功能对齐，而且也只会上传到默认图床

**Comment by mouyong** [comment]
嗯嗯。这样足够了。已经变得特别便捷了。
