### ISSUE TITLE
[Bug]: 快捷键方式上传失败

### ISSUE THREAD

**Issue by sxk10812139** [Molunerfinn/PicGo#1057]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [X] [Issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)

### PicGo的版本 | PicGo Version

v2.3.1 通过快捷键上传失败

### 系统信息 | System Information

Mac(arm64)

### 问题重现 | Bug reproduce

mac v2.3.1在剪贴图片后，尝试使用快捷键上传图片，发现失败概率很大(>50%)，而且发现个灵异现象，只要我将鼠标移动到顶栏picgo图标上，就立即触发了上传，具体表现如图所示

tail -f picgo.log
![](http://pic.aipp.vip/202301031614179.png)

当鼠标移动到顶栏图标处时，上传触发
![](http://pic.aipp.vip/202301031617220.png)

**Comment by Molunerfinn** [comment]
和 #1031 重复，先关闭，在那个issue里统一处理
