### ISSUE TITLE
[Bug]: 从2.3.1-beta5升级至2.3.1正式版后，使用自定义web图床无法正常上传图片。

### ISSUE THREAD

**Issue by SrSh-notme** [Molunerfinn/PicGo#1058]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [X] [Issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)

### PicGo的版本 | PicGo Version

2.3.1正式版

### 系统信息 | System Information

Windows

### 问题重现 | Bug reproduce

桌面系统为win 11

使用2.3.1-beta5 自定义web图床能正常上传，使用2.3.1正式版，包括beta6有的版本都不能正常上传。显示下图的错误信息

**Comment by Molunerfinn** [comment]
请联系插件作者更新适配。

**Comment by SrSh-notme** [comment]
> 请联系插件作者更新适配。

这个插件感觉N年没有维护过了。
Picgo有没有可能增加自带自定义web图床的功能？感谢~

**Comment by Molunerfinn** [comment]
> > 请联系插件作者更新适配。
> 
> 这个插件感觉N年没有维护过了。 Picgo有没有可能增加自带自定义web图床的功能？感谢~

暂时不考虑，这个功能插件即可实现

**Comment by SrSh-notme** [comment]
> > > 请联系插件作者更新适配。
> > 
> > 
> > 这个插件感觉N年没有维护过了。 Picgo有没有可能增加自带自定义web图床的功能？感谢~
> 
> 暂时不考虑，这个功能插件即可实现

这个插件现在感觉有问题，作者的github感觉也不在维护插件，每个版本一个个尝试了，win11 下面超过beta5版本就用不了了。以后版本再升级也用不了了。

**Comment by Mydong** [comment]
哎 是的  我测试了好几个版本  确实只有2.3.1 beta5  可以使用那个插件
但是插件的作者已经n久不更新了
