### ISSUE TITLE
【功能建议】加入 Arch 的 AUR  源

### ISSUE THREAD

**Issue by mupenyu** [Molunerfinn/PicGo#106]
## 问题类型
Feature Request

## PicGo的相关信息
Arch Linux

## 功能请求

[AUR](https://wiki.archlinux.org/index.php/Arch_User_Repository_(%E7%AE%80%E4%BD%93%E4%B8%AD%E6%96%87)) 是是为用户而建、由用户主导的Arch软件仓库，更新方便，能让您的软件得到更多的关注。

**Comment by Molunerfinn** [comment]
我对此不太熟悉，不过很欢迎你们帮PicGo加进去~


 :octocat: [From gitme iOS](http://flutterchina.club/app/gm.html)

**Comment by houbaron** [comment]
@Molunerfinn 已经发布了 [picgo-appimage](https://aur.archlinux.org/packages/picgo-appimage/)

Arch 类 Linux 可以执行 `aurman -S picgo-appimage` 来安装。

**Comment by Molunerfinn** [comment]
@houbaron 非常感谢！稍后会把该项安装放至README首页~

**Comment by Molunerfinn** [comment]
@houbaron 已经更新，再次感谢贡献！

**Comment by houbaron** [comment]
以后每次 release 还请在此 issue 里面 AT 我，以便我去更新。

**Comment by Molunerfinn** [comment]
好的，非常感谢:smile:

**Comment by Molunerfinn** [comment]
@houbaron 2.2.0已经更新，有空的话可以更新一下AUR源，欢迎订阅release更新哈~这样就不用手动提醒啦
![image](https://user-images.githubusercontent.com/12621342/71948814-4bbe9900-320c-11ea-981b-101ab9fb52b4.png)

**Comment by heyizhang** [comment]
@houbaron picgo 更新了哈，大佬，帮忙更新到 aur 里面呗
