### ISSUE TITLE
[Bug]: 图片上传进行时

### ISSUE THREAD

**Issue by ChaseYangGithub** [Molunerfinn/PicGo#1060]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [X] [Issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)

### PicGo的版本 | PicGo Version

PicGo2.4.0 beta 0

### 系统信息 | System Information

Windows

### 问题重现 | Bug reproduce

当前最新版本beta，在PicGo主程序已经运行的情况下，上传图片后台出现多个主程序
且正常上传无法停止。
在清除后台重新运行上传之后恢复正常
win11
Typora 0.9.98
PicGo2.4.0 beta 0

### 相关日志 | Logs

2023-01-09 01:10:23 [PicGo INFO] [PicGo Server] upload files in list 
2023-01-09 01:10:23 [PicGo INFO] Before transform 
2023-01-09 01:10:23 [PicGo INFO] Transforming... Current transformer is [path] 
2023-01-09 01:10:23 [PicGo INFO] Before upload 
2023-01-09 01:10:23 [PicGo INFO] beforeUploadPlugins: renameFn running 
2023-01-09 01:10:23 [PicGo INFO] Uploading... Current uploader is [github] 
//这里我关闭了后台，但是有两个程序所以关了两次
2023-01-09 01:11:45 [PicGo INFO] [PicGo Server] shutdown 
2023-01-09 01:11:46 [PicGo INFO] [PicGo Server] is listening at 36677 
2023-01-09 01:11:49 [PicGo INFO] [PicGo Server] shutdown

**Comment by Molunerfinn** [comment]
typora是调用picgo的http server进行上传的 按理说不应该会启动第二个实例才对。2.3.1正式版会出现这个问题吗？

**Comment by Molunerfinn** [comment]
这里看着是关了一个程序后又启动了然后再关闭，而不是同时存在两个。

**Comment by ChaseYangGithub** [comment]
> 这里看着是关了一个程序后又启动了然后再关闭，而不是同时存在两个。

是同时存在的，如果后台已经运行程序了，上传图片任务管理器里有两个主程序。软件变得很卡
如果后台没有运行程序，topora调用程序运行正常

**Comment by ChaseYangGithub** [comment]
> typora是调用picgo的http server进行上传的 按理说不应该会启动第二个实例才对。2.3.1正式版会出现这个问题吗？

我没使用正式版本尝试

**Comment by ChaseYangGithub** [comment]
> > typora是调用picgo的http server进行上传的 按理说不应该会启动第二个实例才对。2.3.1正式版会出现这个问题吗？
> 
> 我没使用正式版本尝试

试了下2.3.1没问题

**Comment by Molunerfinn** [comment]
好的 回头看看

**Comment by Molunerfinn** [comment]
我用mac的typora试了一下并没有这个问题。

检查了一下代码，关于底层双实例的代码从 2.3.1 到 2.4.0 中间并没有做改动，2.4.0的代码基本仅更新了页面而已。

我看你的typora已经有点旧了，更新一下typora试试呢？另外这个问题属于第三方应用调用picgo的问题，其实如果有问题应该去typora官方提。毕竟picgo本身上传功能应该是正常的。

**Comment by Molunerfinn** [comment]
请问你typora设置picgo上传的部分是怎么设置的？是直接指定 PicGo.exe 还是指定了命令行上传？

**Comment by ChaseYangGithub** [comment]
> 请问你typora设置picgo上传的部分是怎么设置的？是直接指定 PicGo.exe 还是指定了命令行上传？ <img alt="image" width="543" src="https://user-images.githubusercontent.com/12621342/211233242-851b389b-ded3-4e74-b095-fab5cda0b04c.png">
直接指定exe

既然底层代码没有改变，可能是typora版本问题吧

**Comment by musnows** [comment]
### 问题
出现了相同问题，当typora上传图片的时候，有时候会卡在上传阶段；
**任务管理器内会出现多个picgo的进程**，其中有一个进程占用最高10%，且此时picgo在windows状态栏中的页面无法正常打开（打开来是黑屏的）

### 解决办法
在任务管理器中终止picgo占用量最高的那个进程，此时typora会自动启动一个picgo，才能正常上传图片；
* 已试过重新安装picgo，甚至在github重新下过一遍安装包安装
* v2.3.0-beta8无此问题
* 但是 v2.3.0-beta8 无法正常运行lsky插件（同样试过重新安装picgo，无效）

### 版本
typora版本：0.9.98
pcigo版本：2.3.1正式版

**Comment by Molunerfinn** [comment]
请不要使用0.9.98版本typora，是有问题的。请使用最新的typora，验证正常。

**Comment by Molunerfinn** [comment]
1. 这里的问题我本地无法复现
2. picgo本身上传功能是否正常？我这里看起来是不存在多进程的问题的。typora上传处于uploading的情况下，picgo有什么日志么？
3. 如果只是 typora 调用 picgo 有问题（picgo独立上传没问题的话）请去typora的仓库里询问

**Comment by Molunerfinn** [comment]
> 1. 这里的问题我本地无法复现
> 2. picgo本身上传功能是否正常？我这里看起来是不存在多进程的问题的。typora上传处于uploading的情况下，picgo有什么日志么？
> 3. 如果只是 typora 调用 picgo 有问题（picgo独立上传没问题的话）请去typora的仓库里询问

另外我看了一下，如果是一开始没有打开picgo，就用typora执行上传的话，typora会用自己的方式唤起picgo，这中间的过程我不知道他做了什么，我会看到六个子进程，不过影响不是很大，我这里上传依然是正常的。

![image](https://user-images.githubusercontent.com/12621342/220109564-6062aeca-3406-4b93-a3e8-7e8de89745d9.png)

如果你们对进程数很在意，我建议你们先自行开启picgo再使用typora上传。

**Comment by musnows** [comment]
> 1. 这里的问题我本地无法复现
> 2. picgo本身上传功能是否正常？我这里看起来是不存在多进程的问题的。typora上传处于uploading的情况下，picgo有什么日志么？
> 3. 如果只是 typora 调用 picgo 有问题（picgo独立上传没问题的话）请去typora的仓库里询问

出现卡上传的情况时，右下角的picgo主页面无法打开，右键图标也没有反应；等我后续再次发现此问题的时候，看看日志吧！

**Comment by musnows** [comment]
> > 1. 这里的问题我本地无法复现
> > 2. picgo本身上传功能是否正常？我这里看起来是不存在多进程的问题的。typora上传处于uploading的情况下，picgo有什么日志么？
> > 3. 如果只是 typora 调用 picgo 有问题（picgo独立上传没问题的话）请去typora的仓库里询问
> 
> 另外我看了一下，如果是一开始没有打开picgo，就用typora执行上传的话，typora会用自己的方式唤起picgo，这中间的过程我不知道他做了什么，我会看到六个子进程，不过影响不是很大，我这里上传依然是正常的。
> 
> ![image](https://user-images.githubusercontent.com/12621342/220109564-6062aeca-3406-4b93-a3e8-7e8de89745d9.png)
> 
> 如果你们对进程数很在意，我建议你们先自行开启picgo再使用typora上传。

更新2.4.0beta版本和最新版本typora后，无此问题

**Comment by musnows** [comment]
> 1. 这里的问题我本地无法复现
> 2. picgo本身上传功能是否正常？我这里看起来是不存在多进程的问题的。typora上传处于uploading的情况下，picgo有什么日志么？
> 3. 如果只是 typora 调用 picgo 有问题（picgo独立上传没问题的话）请去typora的仓库里询问

我大概发现出现此问题的情况了，只要typora在运行之后关闭过，而picgo依旧在后台运行。下次启动typora，那就有极大概率出现卡上传的情况。此时picgo主进程无法打开（页面全黑），必须要进任务管理器中结束picgo进程，才能上传成功。

typora最新版本+picgo2.4.0 beta0 依旧会出现这个问题
