### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by zh-wen** [Molunerfinn/PicGo#1061]
### PicGo的版本 | PicGo Version

2.4.0-beta.0

### 系统信息 | System Information

Windows

### 问题重现 | Bug reproduce

2.4.0-beta.0版本存在读取本机文件
进程全路径：c:\users\xxxx\appdata\local\programs\picgo\picgo.exe
进程md5：C4F98CEEB5FD7813D7FDA16558BAA388
通信域名：
进程上下文信息：
MD5：C4F98CEEB5FD7813D7FDA16558BAA388

读取本地文件 密码.xls

下载路径：
https://picgo-1251750343.cos.ap-chengdu.myqcloud.com/2.4.0-beta.0/PicGo-Setup-2.4.0-beta.0-x64.exe

**Comment by Molunerfinn** [comment]
呃，代码全开源的 你不放心可以自行构建。picgo不存在随意读取用户文件的情况，请你检查一下是否有装什么三方插件等。

**Comment by zh-wen** [comment]
这是公司扫描到的，我下载v2.3.1版本没有问题。就这个版本有问题，可以排查一下

**Comment by Molunerfinn** [comment]
2.3.1 到 2.4.0 的依赖只有vue的一个子依赖发生了变更，代码变更记录在这里，都不会主动去读取你的文件。

https://github.com/Molunerfinn/PicGo/compare/v2.3.1...v2.4.0-beta.0#files_bucket

唯一有可能的点是，你这个文件复制到了剪贴板里，然后又调用了picgo的上传，picgo会尝试读取剪贴板文件的时候才会去获取这个文件的路径而已。

**Comment by zh-wen** [comment]
问题原因应该就是这样，感谢
