### ISSUE TITLE
[Feature]: 图传图片分类功能

### ISSUE THREAD

**Issue by fenston** [Molunerfinn/PicGo#1062]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [X] [Issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)

### PicGo的版本 | PicGo Version

v2.3.1

### 系统信息 | System Information

Windows

### 功能请求 | Feature request

1.上传区，图床下建不同文件夹，支持通过PicGo上传图片到不同文件夹
2.相册，可以映射某一图床下不同文件夹，显示多个相册
3.支持加载图床现有的图片并根据文件夹显示为多个相册

**Comment by Molunerfinn** [comment]
PicGo的本意不是用来做一个完备的云端存储管理软件。

这里之前的issue里说过了，后续会开放webview给到插件自行绘制页面，届时一些比较复杂的业务逻辑可以由插件实现
