### ISSUE TITLE
[Feature]: 同一个图，上传多次，名字不一样，hash问题？

### ISSUE THREAD

**Issue by qbmiller** [Molunerfinn/PicGo#1066]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [X] [Issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)

### PicGo的版本 | PicGo Version

2.3.1

### 系统信息 | System Information

Mac

#### 同一张图，上传多次，名字不一样
想要一样的url
hash取名时候，根据base64是不是就是一样的了？ 后者覆盖前边。

----------------
用简悦收藏文章时候，用的插件（应该是调用picgo的picgo-server模式），我试了几次 ，每次都一样url

简悦插件地址  https://github.com/Kenshin/simpread/issues/4307

**Comment by Molunerfinn** [comment]
你同一张图是用剪贴板上传还是用文件路径上传？

如果是剪贴板图片上传，名字会默认用时间戳命名。每次上传时间戳是不一样的

**Comment by qbmiller** [comment]
> 你同一张图是用剪贴板上传还是用文件路径上传？
> 
> 如果是剪贴板图片上传，名字会默认用时间戳命名。每次上传时间戳是不一样的

好吧重复上传，按理说 图片基于base64的话，每次一样最好。毕竟内容都是一样的，不管是剪贴板还是本地 ，网络url

**Comment by Molunerfinn** [comment]
picgo并不知道你服务器上已经传的同内容的图片是什么。picgo只负责上传，不负责去重。

**Comment by qbmiller** [comment]
> picgo并不知道你服务器上已经传的同内容的图片是什么。picgo只负责上传，不负责去重。

我意思是 上传时候 基于图片内容(图片转base64).md5或者什么， 上传时候 就每次同一个名字了（每次hash都是一样的）

**Comment by Molunerfinn** [comment]
有些插件有做类似的事可以自行搜索使用
