### ISSUE TITLE
[Bug]: 根据 FAQ 文档操作 M1 Mac 无法正常运行 Picgo

### ISSUE THREAD

**Issue by QuincySx** [Molunerfinn/PicGo#1067]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [X] [Issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)

### PicGo的版本 | PicGo Version

2.3.1

### 系统信息 | System Information

Mac

### 问题重现 | Bug reproduce
根据 FAQ 文档的操作。

#### xattr -cr /Applications/PicGo.app
会打印输出 option -r not recognized

#### xattr -c /Applications/PicGo.app/*
正常也不会报错，但是 picgo 打开还是会报错应用损坏，重启电脑也无效。

> 使用 sudo 运行也无效

#### sudo xattr -d com.apple.quarantine /Applications/PicGo.app/
使用该方式可以正常运行。

希望补充到 FAQ

**Comment by Molunerfinn** [comment]
感谢反馈，欢迎你提个PR

**Comment by ffy** [comment]
Same problem and you can solve it simply by using the x64 version
