### ISSUE TITLE
[Bug]: Ubuntu下 snap 安装的pcigo2.3.1无法打开

### ISSUE THREAD

**Issue by kdt2014** [Molunerfinn/PicGo#1073]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [X] [Issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)

### PicGo的版本 | PicGo Version

2.3.1

### 系统信息 | System Information

Linux

### 问题重现 | Bug reproduce

下载snap版本的软件
执行： sudo snap install --dangerous picgo_2.3.1_amd64.snap 命令安装软件
在所有应用的界面，点击picgo用于图标，桌面闪烁以下，但是应用没有启动。
在终端输入 picgo -v, 输出 1.5.0

plus:
下载APPimage版本应用，双击可打开，缺点就是没法固定在收藏栏。

### 相关日志 | Logs

软件打不开，无法按照这个指引上传日志

**Comment by Molunerfinn** [comment]
linux版本的picgo我这边没法测试，我对linux也不熟悉，只是在构建的时候多添加了linux平台的构建信息而已。

这里只能建议你优先使用appimage格式的picgo了。社区上应该有一些文章可以参考

**Comment by kdt2014** [comment]
谢谢 Appimage使用正常，已经使用https://bella722.github.io/post/3c4ff36.html 链接里的方式，添加图标并放在收藏栏了。多谢回复！
