### ISSUE TITLE
[Feature]: 可以增加静默上传吗？

### ISSUE THREAD

**Issue by imsandox** [Molunerfinn/PicGo#1074]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [X] [Issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)

### PicGo的版本 | PicGo Version

2.3.1

### 系统信息 | System Information

Windows

### 功能请求 | Feature request

![image](https://user-images.githubusercontent.com/89513202/218238287-214795f8-b741-405d-9f4d-6cae406af75d.png)

已经设置了使用时间戳重命名，但每次都要点一下确定，有时窗口还在后台，所以有些麻烦。

会考虑像Mac版本那样的静默上传吗？

**Comment by Molunerfinn** [comment]
开启时间戳重命名 然后关掉上传前重命名 即可。

**Comment by imsandox** [comment]
感谢开发者
