### ISSUE TITLE
[Bug]: typora 选择picgo时，显示文件损坏

### ISSUE THREAD

**Issue by smallbaiprogrammer** [Molunerfinn/PicGo#1076]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [X] [Issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)

### PicGo的版本 | PicGo Version

v2.3.1-arm64

### 系统信息 | System Information

Mac

### 问题重现 | Bug reproduce

下载完毕之后，无法按照，显示文件损坏
![image](https://user-images.githubusercontent.com/67349524/219408039-4544cf30-efa6-42a1-a9f7-44d4cdfa552f.png)

**Comment by Molunerfinn** [comment]
请你看faq最后一条，谢谢。
