### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by youngledo** [Molunerfinn/PicGo#1078]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [X] [Issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)

### PicGo的版本 | PicGo Version

v2.3.1和最新版本

### 系统信息 | System Information

Mac(arm64)

### 问题重现 | Bug reproduce

设置阿里云OSS之后，点击上传失败，查看日志如下：
<img width="1232" alt="image" src="https://user-images.githubusercontent.com/68590897/222080017-0a5889c4-d4fd-4470-aa8b-9ea2bc8a148e.png">

### 相关日志 | Logs

2023-03-01 16:04:10 [PicGo INFO] Before transform 
2023-03-01 16:04:10 [PicGo INFO] Transforming... Current transformer is [path] 
2023-03-01 16:04:10 [PicGo INFO] Before upload 
2023-03-01 16:04:10 [PicGo INFO] beforeUploadPlugins: renameFn running 
2023-03-01 16:04:10 [PicGo INFO] Uploading... Current uploader is [aliyun] 
2023-03-01 16:04:10 [PicGo WARN] failed 
2023-03-01 16:04:10 [PicGo ERROR] {
  "method": "",
  "url": "",
  "statusCode": 0,
  "message": "Invalid character in header content [\"Host\"]",
  "stack": "TypeError [ERR_INVALID_CHAR]: Invalid character in header content [\"Host\"]\n    at ClientRequest.setHeader (node:_http_outgoing:576:3)\n    at new ClientRequest (node:_http_client:256:14)\n    at Object.request (node:https:353:10)\n    at RedirectableRequest._performRequest (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/picgo/node_modules/follow-redirects/index.js:279:24)\n    at new RedirectableRequest (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/picgo/node_modules/follow-redirects/index.js:61:8)\n    at Object.request (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/picgo/node_modules/follow-redirects/index.js:511:14)\n    at dispatchHttpRequest (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/picgo/node_modules/axios/lib/adapters/http.js:262:25)\n    at new Promise (<anonymous>)\n    at httpAdapter (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/picgo/node_modules/axios/lib/adapters/http.js:49:10)\n    at dispatchRequest (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/picgo/node_modules/axios/lib/core/dispatchRequest.js:58:10)",
  "response": {
    "status": 0,
    "statusCode": 0,
    "body": ""
  }
} 
2023-03-01 16:04:10 [PicGo ERROR] {
  "method": "",
  "url": "",
  "statusCode": 0,
  "message": "Invalid character in header content [\"Host\"]",
  "stack": "TypeError [ERR_INVALID_CHAR]: Invalid character in header content [\"Host\"]\n    at ClientRequest.setHeader (node:_http_outgoing:576:3)\n    at new ClientRequest (node:_http_client:256:14)\n    at Object.request (node:https:353:10)\n    at RedirectableRequest._performRequest (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/picgo/node_modules/follow-redirects/index.js:279:24)\n    at new RedirectableRequest (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/picgo/node_modules/follow-redirects/index.js:61:8)\n    at Object.request (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/picgo/node_modules/follow-redirects/index.js:511:14)\n    at dispatchHttpRequest (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/picgo/node_modules/axios/lib/adapters/http.js:262:25)\n    at new Promise (<anonymous>)\n    at httpAdapter (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/picgo/node_modules/axios/lib/adapters/http.js:49:10)\n    at dispatchRequest (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/picgo/node_modules/axios/lib/core/dispatchRequest.js:58:10)",
  "response": {
    "status": 0,
    "statusCode": 0,
    "body": ""
  }
}

**Comment by Molunerfinn** [comment]
检查你的配置，有非法字符
