### ISSUE TITLE
新浪微博要输验证码

### ISSUE THREAD

**Issue by xcsweb** [Molunerfinn/PicGo#108]
## PicGo的相关信息

windows版本
登录的时候，提示信息是请输入验证码，我试了下新浪微博官网登录也是要输入验证码的，
如果你加一个验证码的话输入的话，或许可以解决这个问题

**Comment by Molunerfinn** [comment]
新浪微博用账号密码登录是调用的API，无法获取网页上的验证码。所以如果遇到需要输入验证码的情况，还请使用cookie模式。这点WIKI里已经说明了。
