### ISSUE TITLE
[Feature]: 支持jihu 图床

### ISSUE THREAD

**Issue by jinfagang** [Molunerfinn/PicGo#1081]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [X] [Issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)

### PicGo的版本 | PicGo Version

v2.4.0

### 系统信息 | System Information

Windows

### 功能请求 | Feature request

支持 jihulab.com 的图床，

因为

1. 国内服务器
2. 单个仓库容量2GB

**Comment by Molunerfinn** [comment]
readme里说得很清楚 有需要别的图床支持请自行开发插件。
