### ISSUE TITLE
[Bug]: tsconfig.json needs to fix typeRoots for the project

### ISSUE THREAD

**Issue by sheetalkamat** [Molunerfinn/PicGo#1082]
### 前置阅读 | Pre-reading

- [ ] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [ ] [Issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [ ] [FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)

### PicGo的版本 | PicGo Version

Current

### 系统信息 | System Information

Windows

### 问题重现 | Bug reproduce

Project will report error when compiled with typescript nightly and needs to fix its typeRoots to include root node_modules and @types:

> ### [tsconfig.json](https://github.com/Molunerfinn/PicGo/blob/4f392f36282d79231258ebb5a00fb0f8732d021a/tsconfig.json)
> * `error TS2688: Cannot find type definition file for 'element-plus/global'.`
>   
>   * Project Scope
> * `error TS2688: Cannot find type definition file for 'vue3-photo-preview'.`
>   
>   * Project Scope
> * `error TS2688: Cannot find type definition file for 'webpack-env'.`
>   
>   * Project Scope

This needs change to tsconfig.json typeRoots as:
![image](https://user-images.githubusercontent.com/8052792/223550974-1aef586b-23d7-4047-b5d0-ed5131b50d45.png)

https://github.com/microsoft/TypeScript/issues/53122#issuecomment-1458865645

**Comment by Molunerfinn** [comment]
OK, let me check
