### ISSUE TITLE
[Feature]: 关于mac状态栏显示不全

### ISSUE THREAD

**Issue by chencicici** [Molunerfinn/PicGo#1083]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [X] [Issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)

### PicGo的版本 | PicGo Version

v2.3.1

### 系统信息 | System Information

Mac(arm64)

### 功能请求 | Feature request

mac上只能点击顶部状态栏才能显示出主窗口，但是有时候状态栏被占满看不到picgo的图标，就会陷入打不开主窗口的尴尬.能否增加一个点击下方大图标也能打开主窗口
<img width="579" alt="image" src="https://user-images.githubusercontent.com/74459394/223631244-f4173891-79dd-43d5-8ca1-8fb69b19768e.png">

**Comment by Molunerfinn** [comment]
跟 #1045 重复
