### ISSUE TITLE
[Feature]: 

### ISSUE THREAD

**Issue by pengfeichencpf** [Molunerfinn/PicGo#1085]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [X] [Issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)

### PicGo的版本 | PicGo Version

2.3.2

### 系统信息 | System Information

Mac(arm64)

### 功能请求 | Feature request

1.请问一下，后续会考虑在APP Store平台上架吗？APP Store平台管理应用 升级 卸载 迁移更为方便

2.会考虑做一个在docker栏有图标的功能吗？只有状态栏，有时候还是不是特别方便。

**Comment by Molunerfinn** [comment]
1. 暂不考虑，这个项目是我个人兴趣开发，后续如果有更多 macOS 或者 iOS 生态的东西需要发布届时再考虑
2. 会有的，会在 #1045 中实现

**Comment by pengfeichencpf** [comment]
收到

**Comment by Molunerfinn** [comment]
这块做起来会比较复杂，不过未来会希望实现这个目标。

不过如果实现的话，更新包也会放到 GitHub 上，这样的话需要用户自行解决 GitHub release 资源下载速度慢的问题。

PicGo 现在能免费就是因为使用的基础设施都是基于开源社区的。所以如果要让 PicGo 提供快速下载、无打扰更新等工作，这些需要成本的功能，我本质上的意见是这部分成本能省则省，用户只要能用上即可。如果一定要提供更好的服务，那么势必会需要用户付费使用 PicGo。如果用户付费意愿强烈，我可以考虑做。

**Comment by pengfeichencpf** [comment]
首先，感谢您的回复。
作为用户，使用Picgo有着非常好的用户体验。如果是Picgo提供快速下载或者是在APP Store上架，提供了这些需要额外增加成本的功能，是可以接受付费的，当然也要听取大部分用户的声音。

另外想问一下，Picgo在Mac上更新下载最新版的话，是直接下载安装包，重新安装即可了吗？不需要卸载之前已经安装的版本？

另，在之前的安装过程中，会出现一个 **信任开发者** 的操作，后续会考虑一次性解决这个问题吗？

谢谢！

**Comment by Molunerfinn** [comment]
不需要卸载直接覆盖安装即可。

信任开发者本质上是没有签名导致的，签名是需要开通苹果开发者账号获取的，这部分是有成本的，所以也暂时不做。

**Comment by pengfeichencpf** [comment]
明白 谢谢！
