### ISSUE TITLE
希望能提供一个上传到百度云的插件

### ISSUE THREAD

**Issue by SongZX0106** [Molunerfinn/PicGo#1087]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [X] [Issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)

### PicGo的版本 | PicGo Version

2.3.1

### 系统信息 | System Information

Windows

### 功能请求 | Feature request

能否支持百度云上传

**Comment by Molunerfinn** [comment]
请你仔细阅读 FAQ
