### ISSUE TITLE
[Bug]: 上传mp4文件后mime被识别为"application/octet-stream"，希望能识别为"video/mp4"，否则浏览器无法在线播放

### ISSUE THREAD

**Issue by zhengguoxin** [Molunerfinn/PicGo#1088]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [X] [Issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)

### PicGo的版本 | PicGo Version

2.3.1

### 系统信息 | System Information

Mac(arm64)

### 问题重现 | Bug reproduce

如题，在配置文件中增加 "mimeTypes": ["image/jpeg", "image/png", "image/gif", "video/mp4"] 后也无法识别，希望作者能改进，谢谢

**Comment by Molunerfinn** [comment]
你用的是什么图床？

**Comment by zhengguoxin** [comment]
> 

我使用了minio图床，不知道是不是在minio插件中设置？但是找不到设置的地方，这个问题很困扰
<img width="641" alt="image" src="https://user-images.githubusercontent.com/24664658/225805777-89486b20-ec39-45e5-a35b-03b310603999.png">

**Comment by Molunerfinn** [comment]
这个请你联系 minio 图床插件作者。

**Comment by zhengguoxin** [comment]
> 

好的，谢谢，这个mime并不是picgo处理的，而是各个插件自己处理的吧

**Comment by Molunerfinn** [comment]
是的
