### ISSUE TITLE
CTRL + C 复制图片后用快捷键上传失败

### ISSUE THREAD

**Issue by bgrc** [Molunerfinn/PicGo#109]
## 问题类型

Bug Report

## PicGo的相关信息

picGo: 1.6.2
Win10: 1803

## 问题重现

问题复现率 100%，当使用 `CTRL + C` 将图片复制到剪贴板，然后用快捷键上传的时候会提示剪贴板最新的内容不是图片。用微信截图时，点完成然后再用快捷键上传就正常，另外拖拽上传也是正常的。

![2018-09-13_15-34-38](https://user-images.githubusercontent.com/38936252/45473907-eae39580-b76a-11e8-8ebc-78c90d8b00d1.gif)

**Comment by Molunerfinn** [comment]
Windows不支持直接复制图片文件。必须打开图片之后，在图片上右键复制才可以。Windows在系统下右键复制图片复制的是图片文件而不是图片内容。

**Comment by bgrc** [comment]
好的，打扰了

**Comment by bgrc** [comment]
@Molunerfinn 好的，打扰了
