### ISSUE TITLE
[Bug]: Typora上传图片至阿里云OSS时出现TLSWrap.onStreamRead报错且无法上传

### ISSUE THREAD

**Issue by Chutj** [Molunerfinn/PicGo#1090]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [X] [Issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)

### PicGo的版本 | PicGo Version

v2.3.1

### 系统信息 | System Information

Windows

### 问题重现 | Bug reproduce

您好~
在用**Typora**时，粘贴本地或网络图片后，原本应当顺利上传至阿里云的OSS中；但从今天下午开始，这一操作就会报错，具体报错日志如下所示。
已经参考了相关文档，排除了是网络、代理的问题；并且同样的环境、条件下，同一张图片是可以用同样的方式上传至**GitHub**图床的。
此外，还有一点发现，就是在**Typora**的“图像”设置中，通过“验证图片上传选项”，虽然会显示上传错误（如下图所示），但是OSS的文件列表中是可以看到此时**Typora**自动上传的这一张示例图片的（但是也不会自动复制该图片的URL）；但是在**Typora**中自行上传图片，会报错且OSS中也没有上传对应文件。谢谢~
![image](https://user-images.githubusercontent.com/76252620/225937152-da7fe9f1-5f94-4422-8190-56f0f6822f43.png)

### 相关日志 | Logs

2023-03-17 22:31:45 [PicGo ERROR] {
  "method": "PUT",
  "url": "https://picturesali.oss-cn-beijing.aliyuncs.com/202303172231596.png",
  "statusCode": 0,
  "message": "read ECONNRESET",
  "stack": "Error: read ECONNRESET\n    at TLSWrap.onStreamRead (node:internal/stream_base_commons:220:20)",
  "response": {
    "status": 0,
    "statusCode": 0,
    "body": ""
  }
}

**Comment by Molunerfinn** [comment]
这是你网络问题。
