### ISSUE TITLE
[Feature]: 您好，请问是否考虑新增自动生成目录功能？

### ISSUE THREAD

**Issue by KezHub** [Molunerfinn/PicGo#1091]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [X] [Issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)

### PicGo的版本 | PicGo Version

v2.3.1

### 系统信息 | System Information

Windows

### 功能请求 | Feature request

现在使用GitHub作为图床，上传路径通过手动设置日期来进行创建，是否可以有自动日期的功能选择呢？
例如：今天2023年3月18日，那么此时上传的路径自动显示为images/uploads/2023/03/18/。
文件会上传到2023目录下的03目录中的18文件夹内，对于博客来讲这样较为容易根据文章发布日期来找到图片位置。

**Comment by Molunerfinn** [comment]
已有相关插件请自行安装，前面的iisue也有提及请仔细阅谢谢
