### ISSUE TITLE
[Bug]: 证书认证失败

### ISSUE THREAD

**Issue by Yukii2333** [Molunerfinn/PicGo#1093]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [X] [Issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)

### PicGo的版本 | PicGo Version

v2.4.0-beta.0

### 系统信息 | System Information

Windows

### 问题重现 | Bug reproduce

就正常配置后在打算用github作为图床，但是改了不少地方都没有效果，而且貌似没看见类似的问题？
![image](https://user-images.githubusercontent.com/116934686/228281869-8c4f33bb-5b41-4073-9d04-06b916505095.png)

### 相关日志 | Logs

2023-03-28 23:04:01 [PicGo ERROR] {
  "method": "PUT",
  "url": "https://api.github.com/repos/Yukii2333/Images/contents/202303282304212.jpg",
  "statusCode": 0,
  "message": "unable to verify the first certificate",
  "stack": "Error: unable to verify the first certificate\n    at TLSSocket.onConnectSecure (node:_tls_wrap:1530:34)\n    at TLSSocket.emit (node:events:394:28)\n    at TLSSocket._finishInit (node:_tls_wrap:944:8)\n    at TLSWrap.ssl.onhandshakedone (node:_tls_wrap:725:12)",
  "response": {
    "status": 0,
    "statusCode": 0,
    "body": ""
  }
}

**Comment by Molunerfinn** [comment]
这是你的网络问题。一般这种情况都是代理问题，请尽量不使用全局代理。可以尝试配置 picgo 的代理等。

**Comment by Yukii2333** [comment]
配置picgo代理解决了，感谢

**Comment by Eadela** [comment]
gitee图传也出现。同样问题了，网络没有配置代理呐

**Comment by sanri1993** [comment]
> 配置picgo代理解决了，感谢

请问是怎么配置代理的啊, 我没找着门路, 开了 fastgithub 就传不了图, 传得了图就使用不了 fastgithub

**Comment by phantasy36** [comment]
> > 配置picgo代理解决了，感谢
> 
> 请问是怎么配置代理的啊, 我没找着门路, 开了 fastgithub 就传不了图, 传得了图就使用不了 fastgithub

同问。
