### ISSUE TITLE
[Feature]: 希望加上重复上传图片检测功能

### ISSUE THREAD

**Issue by i-NMB** [Molunerfinn/PicGo#1094]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [X] [Issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)

### PicGo的版本 | PicGo Version

v2.4.0-beta.0

### 系统信息 | System Information

Windows

### 功能请求 | Feature request

希望开发者大大能够在新的版本中添加一个相同图片上传检测功能。

遇到的问题：如果将同一个MD5值（或哈希值）的图片由于种种因素（比如配合Typora）不小心又多上传了一遍，这部分重复资源将会占用图库空间、浪费云空间与金钱资源。

希望能添加相同图片上传的检测功能。
**建议**
鄙人的拙见是在本地计算需上传图片的MD5（或哈希值），并在本地建立一个比较库，上传图片时将需上传图片的MD5（或哈希值）与比较库相比较，没有与比较库相同的MD5值（或哈希值），则上传图片，并记录图片地址；如果有与比较库相同的MD5（或哈希值）时则直接返回记录的图片链接地址。
**优势**
鄙人觉得这样可以节省一定的图库（或对象储存）的空间
**优化**
1.不过要注意的是，有些人可能不喜欢这个功能，那么可以将它作为可选项。
2.并且随着上传图片的时间和数量推移，MD5（或哈希值）的数量可能会增多、上传同一图片的可能性减少。由此我们可以手动或定时的删除比较库以及对应的图片链接。

以上是鄙人的一些小建议，这个功能也不一定需要按照本人的建议实现。（因为大佬可能会有实现更高效率的想法）
不过还是很希望能有相同图片上传检测的功能

如果开发者大大能够看到或回复将感激不尽！希望PicGo越来越好

**Comment by Molunerfinn** [comment]
这个可以通过插件实现。以及后续会提供以 md5 命名文件的变量，能够避免相同文件的问题。

**Comment by Mingzefei** [comment]
有人实现了这个功能吗？没有我抽空写一个。
