### ISSUE TITLE
[Bug]: Error: ENOENT: no such file or directory, open '/Users/haisen/Library/Application Support/picgo/picgo-clipboard-images/202303292217898.png.1514657680'

### ISSUE THREAD

**Issue by lhsaq2009** [Molunerfinn/PicGo#1095]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [X] [Issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)

### PicGo的版本 | PicGo Version

Version: 2.3.1

### 系统信息 | System Information

Mac

### 问题重现 | Bug reproduce

不知道为啥，重启 APP 也没用

### 相关日志 | Logs

-------Error Stack End------- 
2023-03-29 22:17:06 [PicGo ERROR] 
------Error Stack Begin------
Error: ENOENT: no such file or directory, open '/Users/haisen/Library/Application Support/picgo/picgo-clipboard-images/202303292217045.png.4031940941'
-------Error Stack End------- 
2023-03-29 22:17:31 [PicGo ERROR] 
------Error Stack Begin------
Error: ENOENT: no such file or directory, open '/Users/haisen/Library/Application Support/picgo/picgo-clipboard-images/202303292217821.png.4005317414'
-------Error Stack End------- 
2023-03-29 22:17:36 [PicGo ERROR] 
------Error Stack Begin------
Error: ENOENT: no such file or directory, open '/Users/haisen/Library/Application Support/picgo/picgo-clipboard-images/202303292217274.png.3740321505'
-------Error Stack End------- 
2023-03-29 22:17:36 [PicGo ERROR] 
------Error Stack Begin------
Error: ENOENT: no such file or directory, open '/Users/haisen/Library/Application Support/picgo/picgo-clipboard-images/202303292217493.png.1015249976'
-------Error Stack End------- 
2023-03-29 22:17:36 [PicGo ERROR] 
------Error Stack Begin------
Error: ENOENT: no such file or directory, open '/Users/haisen/Library/Application Support/picgo/picgo-clipboard-images/202303292217898.png.1514657680'
-------Error Stack End-------

**Comment by Molunerfinn** [comment]
之前的issue有提到了，请自行查看。
