### ISSUE TITLE
[Feature]: 使用腾讯云COS时，支持开启图片默认压缩

### ISSUE THREAD

**Issue by carsonxu** [Molunerfinn/PicGo#1097]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [X] [Issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)

### PicGo的版本 | PicGo Version

latest

### 系统信息 | System Information

All

### 功能请求 | Feature request

腾讯云上线了“极智压缩”，如果开启了，桶的图片访问链接，加载的时候就会是压缩后的图。
希望 PicGo 能用这个功能提供一个“图片压缩”开关，提示的文字和文档链接。

**Comment by Molunerfinn** [comment]
这个功能是网页端手动开启就行？

**Comment by carsonxu** [comment]
对，网页控制台可以开启，但如果在 picgo 有个开关，就更方便一些，有 API 可以开启。

**Comment by carsonxu** [comment]
查询：
curl -X GET "https://bj-1251902136.pic.ap-beijing.myqcloud.com/?image-slim"

开启：
curl -X PUT "https://bj-1251902136.pic.ap-beijing.myqcloud.com/?image-slim" -H "x-stgw-time: 1680179186.179" -H "Content-Type: application/xml" -d '<?xml version="1.0" encoding="UTF-8" standalone="yes"?><ImageSlim><Status>on</Status></ImageSlim>'

关闭：
curl -X DELETE "https://bj-1251902136.pic.ap-beijing.myqcloud.com/?image-slim"

**Comment by Molunerfinn** [comment]
这个就不考虑了 插件完全可以实现 可以考虑插件实现
