### ISSUE TITLE
[Feature]: 希望增加上传至imgur账户的功能，匿名上传难以管理

### ISSUE THREAD

**Issue by chung1912** [Molunerfinn/PicGo#1099]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [X] [Issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)

### PicGo的版本 | PicGo Version

v2.3.0

### 系统信息 | System Information

Windows

### 功能请求 | Feature request

目前imgur只支持clientID匿名上传，当本地删除时，无法服务器端删除；希望增加上传至imgur账户的功能，这样方便线上管理

**Comment by Molunerfinn** [comment]
本体不再做改动，有可以考虑插件实现
