### ISSUE TITLE
已上传缩略图无法显示，相册图片无法显示

### ISSUE THREAD

**Issue by icehen** [Molunerfinn/PicGo#110]
## 问题类型

bug

## PicGo的相关信息

 版本1.6.2 所在平台 MAC

## 问题重现

![image](https://user-images.githubusercontent.com/18263251/45663792-dfadb280-bb3a-11e8-84eb-66896e566a09.png)

#
![image](https://user-images.githubusercontent.com/18263251/45663799-f05e2880-bb3a-11e8-9dd3-6875f1a77755.png)
# 功能请求

希望修复
---

**Comment by Molunerfinn** [comment]
什么图床？


 :octocat: [From gitme iOS](http://flutterchina.club/app/gm.html)

**Comment by Molunerfinn** [comment]
如果是七牛图床，请你仔细看Wiki，网址需要加http://或者https://并且之前已经有人发过同样的issue了


 :octocat: [From gitme iOS](http://flutterchina.club/app/gm.html)

**Comment by icehen** [comment]
感谢你的回答，抱歉github没有用熟练没有看仔细。

**Comment by ZonuyCode** [comment]
我的也是一样的问题，但是在GitHub上面，不知道怎么解决

**Comment by ZonuyCode** [comment]
> 感谢你的回答，抱歉github没有用熟练没有看仔细。

想问一下是怎么解决的？

**Comment by wmxzrs** [comment]
我也是，github图床。梯子都不管用😂

**Comment by wmxzrs** [comment]
大佬，移动端上传后无法和桌面端同步嘛
