### ISSUE TITLE
[Feature]: 希望增加上传图片时转换图片格式的功能

### ISSUE THREAD

**Issue by zui-lang** [Molunerfinn/PicGo#1104]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [X] [Issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)

### PicGo的版本 | PicGo Version

v2.3.1

### 系统信息 | System Information

Windows

### 功能请求 | Feature request

# 希望增加上传图片时转换图片格式的功能
例如更改图片格式为webp，将所有上传的png，jpg等其他格式改为webp后上传，webp格式可以大幅度提高网页加载图片的速度，提高个人博客流畅度

**Comment by Molunerfinn** [comment]
有类似插件已实现。

**Comment by zui-lang** [comment]
请问插件名叫什么

**Comment by Molunerfinn** [comment]
请擅于使用搜索引擎
https://github.com/mrgeneralgoo/picgo-plugin-compress-webp-lossless

**Comment by Molunerfinn** [comment]
另外就算没有已有的插件实现，这个功能也不会内置在本体里，也是依赖插件实现

**Comment by zui-lang** [comment]
好的，感谢大佬
