### ISSUE TITLE
[Feature]: 跳过同名文件

### ISSUE THREAD

**Issue by yamsfeer** [Molunerfinn/PicGo#1105]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [X] [Issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)

### PicGo的版本 | PicGo Version

v2.3.1

### 系统信息 | System Information

Windows

### 功能请求 | Feature request

批量上传图片到github时，如果github已有同名文件，则该文件之后的所有上传都不成功
希望能跳过同名文件，继续上传其图片

**Comment by Molunerfinn** [comment]
你可以用时间戳重命名避免同名文件问题

**Comment by Molunerfinn** [comment]
后续 github 图床会做一下处理

**Comment by Molunerfinn** [comment]
PicGo 下个 beta 版本将更新可以支持同名文件上传不报错
