### ISSUE TITLE
[Bug]: mac m2下用2.3.1-arm64.dmg包打开没有任何反应

### ISSUE THREAD

**Issue by caoyingde** [Molunerfinn/PicGo#1106]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [X] [Issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)

### PicGo的版本 | PicGo Version

2.3.1-arm64.dmg

### 系统信息 | System Information

Mac(arm64)

### 问题重现 | Bug reproduce

[Bug]: mac m2下用2.3.1-arm64.dmg包打开没有任何反应

### 相关日志 | Logs

[Bug]: mac m2下用2.3.1-arm64.dmg包打开没有任何反应

**Comment by Molunerfinn** [comment]
在顶部栏。

**Comment by caoyingde** [comment]
> 在顶部栏。

没有看到

<img width="1679" alt="image" src="https://user-images.githubusercontent.com/10750404/230882019-a49c82c3-8e2b-4b0a-b132-3cf5d76fa2a1.png">

**Comment by caoyingde** [comment]
解决了 brew

**Comment by ShaoLongFei** [comment]
@caoyingde 怎么解决的?，我和你相同的问题

**Comment by zkeq** [comment]
> @caoyingde 怎么解决的?，我和你相同的问题

```sh
brew install picgo
```
