### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by iefc** [Molunerfinn/PicGo#1108]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [X] [Issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)

### PicGo的版本 | PicGo Version

v2.3.1

### 系统信息 | System Information

Mac(arm64)

### 问题重现 | Bug reproduce

电脑：macbook pro m2
问题描述：一开始安装后无法打开应用，按照FAQ操作后，不再提示错误，但打开后没有任何反应，顶部状态栏没有图标，按照FAQ进行重启电脑，重启后再次打开后，顶部状态栏会出现图标，关闭应用后，顶部状态栏便消失，无论如何打开应用，顶部状态栏都不会出现应用了。

**Comment by Molunerfinn** [comment]
检查你顶部栏是否图标过多被隐藏了。过往issue里有很多用户有类似的情况。

后续会新增配置让picgo能出现在dock栏 就不会有这些问题了。你的问题你再自己检查下吧 我也是M2的电脑我用的很正常。
