### ISSUE TITLE
可以关闭提示音吗？

### ISSUE THREAD

**Issue by Chigogo** [Molunerfinn/PicGo#111]
## 问题类型

Feature Request
## PicGo的相关信息

Windows
## 功能请求

上传图片完成会有声音提示，可以关闭声音吗？
---

**Comment by Molunerfinn** [comment]
不可以。electron的Notification模块不支持这个设置。

**Comment by Chigogo** [comment]
@Molunerfinn That's weird. 我打算自己写一个了。
