### ISSUE TITLE
[Bug]: 无法打开 app

### ISSUE THREAD

**Issue by ShaoLongFei** [Molunerfinn/PicGo#1111]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [X] [Issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)

### PicGo的版本 | PicGo Version

v2.3.1

### 系统信息 | System Information

Mac(arm64)

### 问题重现 | Bug reproduce

mac 系统版本 v13.3
下载 https://github.com/Molunerfinn/PicGo/releases/download/v2.3.1/PicGo-2.3.1-arm64.dmg
安装后显示文件已损坏，请移到废纸篓，使用 sudo xattr -rd com.apple.quarantine xxx 命令解决后软件无法打开
打开监视器可以看到进程的运行但是没有任何界面弹出，程序坞也不会显示软件图标，顶部状态栏也不会显示软件图标
从监视器结束进程后依然无法打开
与 https://github.com/Molunerfinn/PicGo/issues/1106 相同的问题，但是没有说是怎么解决的

### 相关日志 | Logs

打不开软件，在程序包内也未找到日志相关文件

**Comment by Molunerfinn** [comment]
如果之前安装过x86版本的picgo，请重启电脑再打开才行。

**Comment by Molunerfinn** [comment]
picgo在mac上最初设计是个顶部栏应用 所以不会在程序坞有图标。请检查顶部栏图标是否空间不够被隐藏等，此前遇到多例。

后续会放开程序坞图标的权限。

**Comment by imagpiecc** [comment]
兄弟解决了吗

**Comment by imagpiecc** [comment]
@ShaoLongFei 兄弟解决了吗

**Comment by ShaoLongFei** [comment]
> @ShaoLongFei 兄弟解决了吗

我用的是 m1 pro 的 mac ，我感觉是图标是卡在电脑屏幕里的刘海里了，开关一下电脑就好了
