### ISSUE TITLE
[Feature]: 建议注册一个PicGo.org官方域名

### ISSUE THREAD

**Issue by AkarinLiu** [Molunerfinn/PicGo#1114]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [X] [Issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)

### PicGo的版本 | PicGo Version

v2.3.1

### 系统信息 | System Information

All

### 功能请求 | Feature request

如果官网能够有域名那就更好了

**Comment by Molunerfinn** [comment]
感谢建议。后续如果做到一定规模了会考虑的
