### ISSUE TITLE
[Bug]: 重新安装+重新配置原服务器后无法看到之前上传的图片

### ISSUE THREAD

**Issue by Kodp** [Molunerfinn/PicGo#1115]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [X] [Issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)

### PicGo的版本 | PicGo Version

v2.3.0

### 系统信息 | System Information

Windows

### 问题重现 | Bug reproduce

新版本重新安装咋不同文件夹+重新配置腾讯云cos服务器，无法看到之前上传的图片，可以新上传图片。

**Comment by Molunerfinn** [comment]
本来就只是本地存储上传记录 没有跟远程同步。
