### ISSUE TITLE
[Bug]: 使用v2.3.0 和v2.3.1版本 上传图片到七牛云报错

### ISSUE THREAD

**Issue by Hiwoniu** [Molunerfinn/PicGo#1118]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [X] [Issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)

### PicGo的版本 | PicGo Version

v2.3.0 和v2.3.1

### 系统信息 | System Information

Windows

### 问题重现 | Bug reproduce

一个输入bug  如果要是再配置页面重新输入秘钥 **要把原来输入的内容清理干净再复制** 不然会报错，会提交不了。大坑 

### 相关日志 | Logs

无

**Comment by Molunerfinn** [comment]
这个可能是你带有前后空格导致的。配置完不确定可以打开配置文件检查是否配置正确。
