### ISSUE TITLE
[Feature]: 

### ISSUE THREAD

**Issue by yao1818** [Molunerfinn/PicGo#1119]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [X] [Issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)

### PicGo的版本 | PicGo Version

最新版本

### 系统信息 | System Information

Linux

### 功能请求 | Feature request

能否增加一个截图功能，当截图后可以选择保存本地，保存剪切板，及 将截图自动上传到图床，然后返回地址到剪切板的功能，这样能更加快捷

**Comment by Molunerfinn** [comment]
截图功能非常复杂，PicGo本身不会做的。

可以通过插件接入其他截图软件来实现你说的功能。参考：https://github.com/PicGo/picgo-plugin-quick-capture
