### ISSUE TITLE
关于PicGo的启动界面

### ISSUE THREAD

**Issue by ifp1090** [Molunerfinn/PicGo#112]
## 功能请求

---

**Comment by Molunerfinn** [comment]
？？？


 :octocat: [From gitme iOS](http://flutterchina.club/app/gm.html)

**Comment by ifp1090** [comment]
你好！我发现Windows平台下，每次开机的时候，PicGo 都会自动弹出来它的界面：
http://prntscr.com/kwv965

每次都要手动点击叉叉来将这个界面关闭掉。

我觉得一款好的软件应该做到自动启动但并不显示出来，每次都要手动关闭这个界面会增加使用者的繁琐性。

所以，能不能将这个自动弹出方式去掉？

**Comment by Molunerfinn** [comment]
@ifp1090    2.0版本将会改成用mini窗口启动，届时将不会占用桌面空间。


 :octocat: [From gitme iOS](http://flutterchina.club/app/gm.html)

**Comment by ifp1090** [comment]
感谢！

**Comment by ifp1090** [comment]
2.0版本什么时候会出来？

**Comment by Molunerfinn** [comment]
正在开发时间未定


 :octocat: [From gitme iOS](http://flutterchina.club/app/gm.html)

**Comment by ifp1090** [comment]
好的，期待！
