### ISSUE TITLE
[Bug]: 如果文件名包含#号,上传后返回的链接中#号没有转义为%23导致无法访问

### ISSUE THREAD

**Issue by iamqiz** [Molunerfinn/PicGo#1121]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [X] [Issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)

### PicGo的版本 | PicGo Version

2.3.1

### 系统信息 | System Information

Windows

### 问题重现 | Bug reproduce

将图片改名,使其含有#号
上传图片
返回的的url无法访问, 需要把#号改成%23才能访问

**Comment by Molunerfinn** [comment]
#号在 URL 是作为一个合法的 hash 标识符，前端通过 `encodeURI` 是不会转义这个字符的。建议不要取名带有 # 号标识。

因为有些云服务商是通过 ?xxx 或者 #xxx 来对图片做一些额外处理，这个时候是不能转义这些 URL 里合法标识的。

**Comment by Molunerfinn** [comment]
参考 #996 ，无法做所有的字符转义也是有原因的

**Comment by iamqiz** [comment]
picgo上传之后,腾讯云返回的链接就是没有编码#的链接?  我在腾讯云控制台复制的链接是转义过的,不存在#号

**Comment by iamqiz** [comment]
我刚才试了腾讯云的nodejs api上传文件,成功之后返回的url是编码过#号的,
比如
key 设置为  objKey='美国/#ss.jpeg'
返回的url 结尾为   
```
myqcloud.com/%E7%BE%8E%E5%9B%BD/%23ss.jpeg',
```

**Comment by Molunerfinn** [comment]
应该是它对文件名做了encodeURIComponent操作，这个跟encodeURI不一样。

我看看后续版本里做一下处理吧

**Comment by Molunerfinn** [comment]
下个 beta 版本将更新支持文件名中带有 # 号。 参考提交：https://github.com/PicGo/PicGo-Core/commit/c22492b4feee0d7cbb640f05369d73fd605dc4e9
