### ISSUE TITLE
[Bug]: mac m1pro 13.3 更新到正式版打开直接报已损坏

### ISSUE THREAD

**Issue by Dzsom** [Molunerfinn/PicGo#1122]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [X] [Issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)

### PicGo的版本 | PicGo Version

V2.3.1

### 系统信息 | System Information

Mac(arm64)

### 问题重现 | Bug reproduce

<img width="260" alt="image" src="https://user-images.githubusercontent.com/22705562/236418355-9ae93275-2cf5-474f-9ef3-4ab9c3a7263a.png">
系统是最新的13.3版本，本来旧的beta可以用，我升级了一下直接打不开了。

**Comment by FantasyWind2016** [comment]
+1

**Comment by StinsonZhao** [comment]
+1

**Comment by real-jiakai** [comment]
同样遇到这个问题。🥲🥲🥲
