### ISSUE TITLE
在typora上传图片时候 picgo会自动打开窗口 怎么样让它不打开窗口呢

### ISSUE THREAD

**Issue by lone0x0** [Molunerfinn/PicGo#1123]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [X] [Issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)

### PicGo的版本 | PicGo Version

v2.4.0 beta1

### 系统信息 | System Information

Mac

### 问题重现 | Bug reproduce

https://user-images.githubusercontent.com/78702504/236976470-8701e235-495b-47f8-940a-76a067f2eb4a.mov

**Comment by cola99year** [comment]
你好，请问怎么解决，现在有解决的办法吗

**Comment by lone0x0** [comment]
换个版本看看 我有点忘记了
cola99year ***@***.***> 于2024年12月23日周一 21:48写道：
