### ISSUE TITLE
[Bug]: 上传失败

### ISSUE THREAD

**Issue by twguang** [Molunerfinn/PicGo#1128]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [X] [Issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)

### PicGo的版本 | PicGo Version

2.31

### 系统信息 | System Information

Windows

### 问题重现 | Bug reproduce

安装软件设置smms token，上传就失败，不太懂什么意思，科学上网也试过
![image](https://github.com/Molunerfinn/PicGo/assets/72485375/554ba515-7454-45da-a4fa-28c3b7d274c6)

### 相关日志 | Logs

![image](https://github.com/Molunerfinn/PicGo/assets/72485375/8dc4fdc1-a090-4ce9-bc43-bc8b73c219f8)

**Comment by Molunerfinn** [comment]
请设置smms的备用域名为smms.app。查看之前的issue谢谢。
