### ISSUE TITLE
[Bug]: 启动picgo无反应，任务栏也没有看到图标，只是任务管理器有进程在跑

### ISSUE THREAD

**Issue by sirius-tzq** [Molunerfinn/PicGo#1129]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [X] [Issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)

### PicGo的版本 | PicGo Version

2.3.0

### 系统信息 | System Information

Windows

### 问题重现 | Bug reproduce

双击picgo.exe（2.3.0和2.4.0都一样，再往前的版本没有试过）后没有任何响应，查看任务栏未发现图标
![image](https://github.com/Molunerfinn/PicGo/assets/55345484/42f1208d-d4e7-4372-8cb4-b061c02e4864)
node版本为16.16.0
![image](https://github.com/Molunerfinn/PicGo/assets/55345484/b17d4f84-1382-4199-894c-05bca9ae9eb1)
因为打不开主页面，只能提供日志内容。

### 相关日志 | Logs

2023-05-18 19:02:52 [PicGo ERROR] 
------Error Stack Begin------
Error: EISDIR: illegal operation on a directory, read
    at Object.readSync (fs.js:513:3)
    at tryReadSync (fs.js:338:20)
    at Object.readFileSync (fs.js:375:19)
    at Object.fs.readFileSync (electron/js2c/asar.js:580:40)
    at Object.fs.readFileSync (electron/js2c/asar.js:580:40)
    at x (E:\PicGO\resources\app.asar\background.js:36:20110)
    at _ (E:\PicGO\resources\app.asar\background.js:36:20477)
    at Module.<anonymous> (E:\PicGO\resources\app.asar\background.js:36:20677)
    at r (E:\PicGO\resources\app.asar\background.js:1:110)
    at Object.<anonymous> (E:\PicGO\resources\app.asar\background.js:15:19041)
-------Error Stack End-------

**Comment by Molunerfinn** [comment]
启动报错了，读取配置文件的时候有问题。可以检查一下配置文件路径是否正常和存在。配置文件路径可以在文档中找到。

**Comment by sirius-tzq** [comment]
感谢回复。
文档中没有找到配置文件的路径，只有通过主界面定位的方式
![image](https://github.com/Molunerfinn/PicGo/assets/55345484/c996fe22-d8f2-4bd2-89e2-36eda44ee8c9)
找到AppData/Roaming/picgo，不知道是我缺少了那个配置文件？
![image](https://github.com/Molunerfinn/PicGo/assets/55345484/0c2a70f8-caa2-440f-8704-8ac650772d8f)

**Comment by Molunerfinn** [comment]
<img width="1119" alt="image" src="https://github.com/Molunerfinn/PicGo/assets/12621342/e4fffdfd-931e-4279-9851-f37381c75e5f">

文档里是有的，叫做 data.json。

我看你的目录是没有这个文件的，可以看看 data.bak.json 文件是否是合法的 json 文件，如果是可以拷贝一份改名为 data.json 再重启 picgo 试试。

**Comment by sirius-tzq** [comment]
已解决！

**Comment by dracula-cn** [comment]
遇到同样问题，所有版本打不开，启动不了。请问如何解决的？

**Comment by sirius-tzq** [comment]
这个issue下的答主的办法无法解决你的问题吗？
我是修改了启动配置文件的文件名解决的



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年6月29日(周四) 中午1:05
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;"State ***@***.***&gt;;
主题: Re: [Molunerfinn/PicGo] [Bug]: 启动picgo无反应，任务栏也没有看到图标，只是任务管理器有进程在跑 (Issue #1129)




 
遇到同样问题，所有版本打不开，启动不了。请问如何解决的？

**Comment by dracula-cn** [comment]
![image](https://github.com/Molunerfinn/PicGo/assets/35946872/2cd36f4f-73f5-4cf0-84b1-13e1ea00bfd6)，我配置文件里有两个文件，一个data.bak.json，一个data.json。

**Comment by sirius-tzq** [comment]
启动配置文件是data.json。
建议检查data.json格式或者查看下picgo.log查看报错信息。可能我的问题和你不一样



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年6月29日(周四) 中午1:16
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;"State ***@***.***&gt;;
主题: Re: [Molunerfinn/PicGo] [Bug]: 启动picgo无反应，任务栏也没有看到图标，只是任务管理器有进程在跑 (Issue #1129)




 
，我配置文件里有两个文件，一个data.bak.json，一个data.json。

**Comment by dracula-cn** [comment]
解决了。谢谢
