### ISSUE TITLE
自定义图片url的失效

### ISSUE THREAD

**Issue by hu9msbedu** [Molunerfinn/PicGo#113]
得到URL地址之后，在自定义url链接修改为 
`$url?xx`
xx为七牛云处理图片水印借口。
只能得到url地址，无法添加？xx后面的地址

**Comment by Molunerfinn** [comment]
你这个问题有两种解决办法。

1. 自定义url链接之后，你需要选择一下复制链接的格式为`Custom`，否则你复制的时候将不生效：

![image](https://user-images.githubusercontent.com/12621342/45915861-182cf380-be8f-11e8-94b3-4233f208326a.png)

自定义url的方式只有在复制链接的时候才会生效。也就是说相册里的链接依然是原始的URL。

2. 七牛云设置里自带后缀的设置，你为何还需要使用自定义URL呢？

![image](https://user-images.githubusercontent.com/12621342/45915868-50cccd00-be8f-11e8-95ba-4d14d579bc84.png)

3. 请发issue的时候按照模板发，否则将会被直接关闭。谢谢。
