### ISSUE TITLE
配置文件里面为什么看不到我上传的图片的配置呢

### ISSUE THREAD

**Issue by ChenKun1997** [Molunerfinn/PicGo#1132]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [X] [Issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)

### PicGo的版本 | PicGo Version

v2.3.1

### 系统信息 | System Information

Windows

### 问题重现 | Bug reproduce

为什么看不到上传的图片呢
![image](https://github.com/Molunerfinn/PicGo/assets/24249578/b84ac74f-3c84-40e7-8fba-53a731e2ce06)
而我相册区是有图片的，配置文件中却看不到已上传的图片
![image](https://github.com/Molunerfinn/PicGo/assets/24249578/7cba1a03-43d1-4498-97d2-fb4338d0ec4c)

![image](https://github.com/Molunerfinn/PicGo/assets/24249578/bfe57759-a74d-4c70-a907-006cc8c27fe9)

**Comment by ChenKun1997** [comment]
感觉可以把discussion模块打开，有的并不是issue也不是feature，不好在issue模块提 😢

**Comment by Molunerfinn** [comment]
这里是文档没更新。新版本会将上传的文件列表写入配置文件目录下的 picgo.db 文件中 暂时没法直接查看。如果要查看也可以将这个文件用gzip解压缩之后就是json格式。

discussion以前有开过但是太多人把它当作不提供有效信息的issue来发帖非常浪费我的精力，就给关闭了。
