### ISSUE TITLE
[Bug]: obsidian无法上传图片

### ISSUE THREAD

**Issue by DORcas-Zheng** [Molunerfinn/PicGo#1135]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [X] [Issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)

### PicGo的版本 | PicGo Version

v2.3.1 arm64

### 系统信息 | System Information

Mac

### 问题重现 | Bug reproduce

在obsidian无法从剪切板创建图片，我已经检查过“Application Support/picgo/”，里面有picgo-clipboard-images文件夹，picgo软件可以正常上传图片。

### 相关日志 | Logs

obsidian issue：
<img width="550" alt="image" src="https://github.com/Molunerfinn/PicGo/assets/89367598/c625a88d-4b36-40d0-90aa-bc00fb8940e8">
picgo settings：
<img width="598" alt="image" src="https://github.com/Molunerfinn/PicGo/assets/89367598/28cdb692-0d19-414e-8ea4-d9ca5906a473">
使用的obsidian插件为：
<img width="990" alt="image" src="https://github.com/Molunerfinn/PicGo/assets/89367598/b81de0ec-e8e0-4b7b-8c01-538534c1ee92">

**Comment by Molunerfinn** [comment]
obsidian 无法上传图片， picgo 可以上传图片，你为什么不去 obsidian 的插件仓库里反馈？
