### ISSUE TITLE
[Feature]: 是否能够支持webdav

### ISSUE THREAD

**Issue by FinderBGG** [Molunerfinn/PicGo#1139]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [X] [Issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)

### PicGo的版本 | PicGo Version

2.3.0

### 系统信息 | System Information

Windows

### 功能请求 | Feature request

是否能够支持webdav 一个能填写主机ip 端口用户名和密码的插件

**Comment by Molunerfinn** [comment]
印象中有插件支持，或者可以看看 piclist。
