### ISSUE TITLE
[Bug]:  电脑长时间不关机，picgo无法正常使用

### ISSUE THREAD

**Issue by Romic77** [Molunerfinn/PicGo#1140]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [X] [Issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)

### PicGo的版本 | PicGo Version

2.3.1

### 系统信息 | System Information

Windows

### 问题重现 | Bug reproduce

![image](https://github.com/Molunerfinn/PicGo/assets/14304457/fb189e59-d0fb-465a-9c1d-f48d4d6543fd)
电脑不关机，第二天使用markdown的时候，无法正常使用picgo上传图片。
问题1：
软件打开像幻灯片操作，巨卡 类似无响应又只有微弱的响应卡卡卡

问题2：
无法正常上传图片(这个可以查看日志)

### 相关日志 | Logs

2023-06-18 14:50:49 [PicGo ERROR] {
  "method": "PUT",
  "url": "https://api.github.com/repos/Romic77/image/contents/image/image-20230618144518080.png",
  "statusCode": 0,
  "message": "Client network socket disconnected before secure TLS connection was established",
  "stack": "Error: Client network socket disconnected before secure TLS connection was established\n    at connResetException (node:internal/errors:691:14)\n    at TLSSocket.onConnectEnd (node:_tls_wrap:1585:19)\n    at TLSSocket.emit (node:events:406:35)\n    at endReadableNT (node:internal/streams/readable:1343:12)\n    at processTicksAndRejections (node:internal/process/task_queues:83:21)",
  "response": {
    "status": 0,
    "statusCode": 0,
    "body": ""
  }
} 
2023-06-18 14:50:49 [PicGo ERROR] {
  "method": "PUT",
  "url": "https://api.github.com/repos/Romic77/image/contents/image/image-20230618144518080.png",
  "statusCode": 0,
  "message": "Client network socket disconnected before secure TLS connection was established",
  "stack": "Error: Client network socket disconnected before secure TLS connection was established\n    at connResetException (node:internal/errors:691:14)\n    at TLSSocket.onConnectEnd (node:_tls_wrap:1585:19)\n    at TLSSocket.emit (node:events:406:35)\n    at endReadableNT (node:internal/streams/readable:1343:12)\n    at processTicksAndRejections (node:internal/process/task_queues:83:21)",
  "response": {
    "status": 0,
    "statusCode": 0,
    "body": ""
  }
}

**Comment by Molunerfinn** [comment]
新的beta版应该已经修复了。
