### ISSUE TITLE
[Bug]: 使用2.31版本以上的Picgo，在重新安装操作系统之后。剪切板上传，变得非常的慢。无论是2.31还是2.40，2.41，都不能快速的通过剪切板上传文件，之前是没有这个问题的，现在使用2.30版本目前是正常的，但是比较简陋。我是苹果电脑2016款，英特尔处理器。

### ISSUE THREAD

**Issue by shixueaaa811001** [Molunerfinn/PicGo#1142]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [X] [Issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)

### PicGo的版本 | PicGo Version

2.3.1正式版

### 系统信息 | System Information

Mac

### 问题重现 | Bug reproduce

[Bug]: 使用2.31版本以上的Picgo，在重新安装操作系统之后。剪切板上传，变得非常的慢。无论是2.31还是2.40，2.41，都不能快速的通过剪切板上传文件，之前是没有这个问题的，现在使用2.30版本目前是正常的，但是比较简陋。

### 相关日志 | Logs

[Bug]: 使用2.31版本以上的Picgo，在重新安装操作系统之后。剪切板上传，变得非常的慢。无论是2.31还是2.40，2.41，都不能快速的通过剪切板上传文件，之前是没有这个问题的，现在使用2.30版本目前是正常的，但是比较简陋。

**Comment by Molunerfinn** [comment]
2.4 beta 版本有一些新的日志可以参考，建议更新到最新的版本再提供相关日志。你的快速通过剪贴板上传是点击还是快捷键的方式？

同时可以尝试开启 「使用内置剪贴板上传」

<img width="615" alt="image" src="https://github.com/Molunerfinn/PicGo/assets/12621342/014ca2b5-f34d-43b1-9711-7df46864e3ff">

**Comment by shixueaaa811001** [comment]
我是点击点不动的感觉。

**Comment by shixueaaa811001** [comment]
我这些版本都试过了，就是2.3版本可以，我不知道怎么把日志给你，作者。不知道怎么联系一下。给你呢？或者帮我看看也好，我就是重新安装了一下操作系统，之前2.3.1版本其实是没问题的，就是重做系统后产生了这个问题。

**Comment by shixueaaa811001** [comment]
刚刚再次升级到最新版本，竟然都能用了。。。感谢作者提示。
