### ISSUE TITLE
[Bug]: 图片上传问题

### ISSUE THREAD

**Issue by Yafine** [Molunerfinn/PicGo#1143]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [X] [Issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)

### PicGo的版本 | PicGo Version

v2.4.1-beta版本

### 系统信息 | System Information

Windows

### 问题重现 | Bug reproduce

无法拖拽上传图片，是因为新版本的原因吗？

**Comment by Molunerfinn** [comment]
不是，请提供相关上传日志才能分析。2.4.0-beta.1 拖拽上传是正常的。

**Comment by Yafine** [comment]
> 不是，请提供相关上传日志才能分析。2.4.0-beta.1 拖拽上传是正常的。

这个提供不了，因为我都无法拖拽上传，所以它无法产生日志。
![image](https://github.com/Molunerfinn/PicGo/assets/31881437/0a7abfa2-a717-436b-ab70-d39cca8c5cea)
直接显示禁用的标志

**Comment by Kuingsmile** [comment]
> ### 前置阅读 | Pre-reading
> * [x]  [文档/Doc](https://picgo.github.io/PicGo-Doc/)
> * [x]  [Issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
> * [x]  [FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)
> 
> ### PicGo的版本 | PicGo Version
> v2.4.1-beta版本
> 
> ### 系统信息 | System Information
> Windows
> 
> ### 问题重现 | Bug reproduce
> 无法拖拽上传图片，是因为新版本的原因吗？
> 
> ### 相关日志 | Logs
> _No response_

@Yafine 你肯定是用管理员权限打开PicGo了，这是electron的限制，管理员模式运行的时候不能拖放文件

重新用普通用户权限打开就可以

https://blog.csdn.net/mulianju/article/details/130987530
