### ISSUE TITLE
[Bug]: imgur的图片上传全部失败了

### ISSUE THREAD

**Issue by justincnn** [Molunerfinn/PicGo#1146]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [X] [Issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)

### PicGo的版本 | PicGo Version

Version: 2.4.0-beta.1

### 系统信息 | System Information

Mac(arm64)

### 问题重现 | Bug reproduce

所有上传的图片都是如下：

![](https://s2.loli.net/2023/07/04/YJGfbSFgCuOB6jE.png)

更新Clientld也是一样

### 相关日志 | Logs

所有上传的图片都是如下：

![](https://s2.loli.net/2023/07/04/YJGfbSFgCuOB6jE.png)

更新Clientld也是一样

**Comment by Molunerfinn** [comment]
picgo的代理只是上传代理 imgur图片国内无法访问需要挂代理才能访问。
