### ISSUE TITLE
使用阿里云OSS配置出现：getaddrinfo ENOTFOUND

### ISSUE THREAD

**Issue by Jason-Qian993** [Molunerfinn/PicGo#1152]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [X] [Issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)

### PicGo的版本 | PicGo Version

2.3.1

### 系统信息 | System Information

Windows

### 问题重现 | Bug reproduce

之前一直没有出现这种情况，今天突然发现上传不了，报了以下错误（相关日志中）
然后我将PicGo中的阿里云OSS设置全部设置了一遍，上传了一张图片，可以上传，再上传一张，又报了相同的错误。
我设置了好几遍都是同样的情况。

### 相关日志 | Logs

```
2023-07-12 22:43:57 [PicGo ERROR] {
  "method": "PUT",
  "url": "https://jasonqianpic.oss-cn-chengdu.aliyuncs.com/img/202307122243762.jpg",
  "statusCode": 0,
  "message": "getaddrinfo ENOTFOUND jasonqianpic.oss-cn-chengdu.aliyuncs.com",
  "stack": "Error: getaddrinfo ENOTFOUND jasonqianpic.oss-cn-chengdu.aliyuncs.com\n    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:71:26)",
  "response": {
    "status": 0,
    "statusCode": 0,
    "body": ""
  }
} 
```

**Comment by Molunerfinn** [comment]
你的网络问题 dns 解析不到你的地址。

**Comment by hanlindaodao** [comment]
不要直接在阿里云里复制地域节点，在这个链接里找“阿里云通用Region ID”
https://help.aliyun.com/zh/oss/user-guide/regions-and-endpoints?spm=a2c4g.11174283.0.0.74077368LpmsAu
我也是同样的问题，已解决
