### ISSUE TITLE
[Bug]: Error: connect ETIMEDOUT 221.178.72.149:80     at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1146:16)

### ISSUE THREAD

**Issue by ghost** [Molunerfinn/PicGo#1153]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [X] [Issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)

### PicGo的版本 | PicGo Version

v2.3.1

### 系统信息 | System Information

Windows

### 问题重现 | Bug reproduce

上传图片
直接在腾讯云上传文件没事 但是使用picgo就会错误i

### 相关日志 | Logs

2023-07-13 23:29:32 [PicGo INFO] beforeUploadPlugins: renameFn running 
2023-07-13 23:29:32 [PicGo INFO] Uploading... Current uploader is [tcyun] 
2023-07-13 23:29:53 [PicGo WARN] failed 
2023-07-13 23:29:53 [PicGo ERROR] {
  "method": "PUT",
  "url": "http://cscgblog-1301638685.cos.ap-chengdu.myqcloud.com/note%2Ftypora-icon2.png",
  "statusCode": 0,
  "message": "connect ETIMEDOUT 221.178.72.149:80",
  "stack": "Error: connect ETIMEDOUT 221.178.72.149:80\n    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1146:16)",
  "response": {
    "status": 0,
    "statusCode": 0,
    "body": ""
  }
} 
2023-07-13 23:29:53 [PicGo ERROR] {
  "method": "PUT",
  "url": "http://cscgblog-1301638685.cos.ap-chengdu.myqcloud.com/note%2Ftypora-icon2.png",
  "statusCode": 0,
  "message": "connect ETIMEDOUT 221.178.72.149:80",
  "stack": "Error: connect ETIMEDOUT 221.178.72.149:80\n    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1146:16)",
  "response": {
    "status": 0,
    "statusCode": 0,
    "body": ""
  }
}

**Comment by Molunerfinn** [comment]
你这是网络超时。
