### ISSUE TITLE
[Feature]: 建议增加支持一下华为云

### ISSUE THREAD

**Issue by zplan7** [Molunerfinn/PicGo#1154]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [X] [Issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)

### PicGo的版本 | PicGo Version

2.3.1

### 系统信息 | System Information

Windows

### 功能请求 | Feature request

建议支持一下华为云，华为云的对象存储好像也是9元40G哈哈哈

**Comment by Molunerfinn** [comment]
本体不做支持，请自行搜索插件。

**Comment by hsh778205** [comment]
@zplan7 找到了一个插件 https://github.com/YunfengGao/picgo-plugin-huawei-uploader
