### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by fmelon2** [Molunerfinn/PicGo#1155]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [X] [Issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)

### PicGo的版本 | PicGo Version

v2.3.1-arm64

### 系统信息 | System Information

Mac(arm64)

### 问题重现 | Bug reproduce

<img width="523" alt="截屏2023-07-17 15 45 15" src="https://github.com/Molunerfinn/PicGo/assets/80674603/04a0c1d7-5b03-44ba-a9bd-67c975eeadb4">
安装了直接使用不了：

### 相关日志 | Logs

日志如上截图

**Comment by Molunerfinn** [comment]
你真的看过这两个么
![image](https://github.com/Molunerfinn/PicGo/assets/12621342/3c79204b-2e41-4603-9675-f60d483bba28)
