### ISSUE TITLE
[Bug]: 安装插件时一直提示请安装nodejs，实际已安装

### ISSUE THREAD

**Issue by leon0625** [Molunerfinn/PicGo#1158]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [X] [Issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)

### PicGo的版本 | PicGo Version

2.3.1

### 系统信息 | System Information

Linux

### 问题重现 | Bug reproduce

我是ubuntu系统，安装插件时提示未安装nodejs。
我使用apt install nodejs安装后
重启软件
还是提示未安装nodejs

打开日志看，是npm没装
apt install npm安装npm后正常

应该提示安装nodejs和npm

### 相关日志 | Logs

无

**Comment by Molunerfinn** [comment]
因为正常情况下安装nodejs会自带npm，这里文档里有说明了。
