### ISSUE TITLE
[Feature]: 能否支持关闭重命名确认窗口呢

### ISSUE THREAD

**Issue by spidu-lee** [Molunerfinn/PicGo#1159]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [X] [Issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)

### PicGo的版本 | PicGo Version

v2.3.1

### 系统信息 | System Information

Windows

### 功能请求 | Feature request

我用时间戳就够了，每一次都要自己点确认，希望增加一个重命名确认窗口的开关

**Comment by Molunerfinn** [comment]
你只要开启时间戳重命名 然后关闭上传前重命名 选项就行。

**Comment by spidu-lee** [comment]
好家伙，是我想多了，我还以为俩个都要开
