### ISSUE TITLE
[Feature]: 主界面唤醒时机

### ISSUE THREAD

**Issue by huifer** [Molunerfinn/PicGo#1160]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [X] [Issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)

### PicGo的版本 | PicGo Version

2.4.0-beta.3

### 系统信息 | System Information

Mac

### 功能请求 | Feature request

是否可以支持后台上传，不要在上传成功后弹出主界面。或者在上传期间弹出这个界面

**Comment by Molunerfinn** [comment]
不知道你说的是什么界面。 PicGo 一直是支持后台上传的。
你是否开启了「上传前重命名」选项，如果想重命名，又不想手动重命名，就关掉这个选项，开启时间戳重命名即可。

**Comment by huifer** [comment]
![image](https://github.com/Molunerfinn/PicGo/assets/26766909/733155a3-22b1-43a4-972b-f31612b9aa5a)
这个界面  @Molunerfinn

**Comment by huifer** [comment]
配置：
![image](https://github.com/Molunerfinn/PicGo/assets/26766909/ff2fc9a1-d815-4050-9ff0-9d659c613042)


在typora中使用
![image](https://github.com/Molunerfinn/PicGo/assets/26766909/4c3cb61b-aa8e-4be8-8032-47f8012e619d)

**Comment by Molunerfinn** [comment]
左上角的红叉关了就行了，你如果一开始没有启动 PicGo，typora 会先启动 PicGo 再上传图片。

**Comment by huifer** [comment]
我是每次都会弹出来这个内容，只要上传。我一开始启动了的

**Comment by Lishuoyy** [comment]
我遇到了相同的问题。我的系统也是 mac，每次在 typora 中粘贴图片时，会自动打开啊 picgo 的主界面。

**Comment by Lishuoyy** [comment]
> 我遇到了相同的问题。我的系统也是 mac，每次在 typora 中粘贴图片时，会自动打开啊 picgo 的主界面。

<img width="545" alt="image" src="https://github.com/Molunerfinn/PicGo/assets/66720796/86b4ceb4-0118-416b-b551-61df0d97c505">

已解决，把这个关掉就好了😆

**Comment by MyMonsterCat** [comment]
> > 我遇到了相同的问题。我的系统也是 mac，每次在 typora 中粘贴图片时，会自动打开啊 picgo 的主界面。
> 
> <img alt="image" width="545" src="https://private-user-images.githubusercontent.com/66720796/260226127-86b4ceb4-0118-416b-b551-61df0d97c505.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU4MzE5MzQsIm5iZiI6MTcxNTgzMTYzNCwicGF0aCI6Ii82NjcyMDc5Ni8yNjAyMjYxMjctODZiNGNlYjQtMDExOC00MTZiLWI1NTEtNjFkZjBkOTdjNTA1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE2VDAzNTM1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJhYTA1M2IzNmY5YmMyNzk2NWZlZTM4YzkyMjZmNjY2YTRiOTg3YjZlZmMyNzYxYTRjM2FiMWRiYjUxNDIxZDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ygW9MzGrl44pIhLhRl5Rdl0oGuHj_vaGOzhCbvyMAfU">
> 已解决，把这个关掉就好了😆

感谢，用了半小时太折磨了，一直弹出，已解决
