### ISSUE TITLE
[Feature]: 期待如果能有图片拉取的功能就好了，指定一个文件夹从图床拉取，比如需要更换图床的服务器，拉取下来，再上传到别处。

### ISSUE THREAD

**Issue by MR-liao-955** [Molunerfinn/PicGo#1161]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [X] [Issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)

### PicGo的版本 | PicGo Version

v2.4.0-beta.1

### 系统信息 | System Information

Windows

### 功能请求 | Feature request

首先，感谢开发者们的无私奉献！
        原因：我的笔记写在本地，通过picgo 和 Typora 上传图片到图床，这样我的笔记就能同时通过git 放在github 和个人网站了，但是万一图床服务器到期或者个人原因需要迁移，那么手动复制图片就显得异常困难。
        期待：如果picgo 能拉取图床文件到本地的文件夹，我的本地文件再次上传到 新图床，那么就不用特别费事。。如果能有这个功能那该多好。
        如果有机会我也想加入picgo 的维护，但是奈何对js 和vue 等语言的不熟悉。十分感谢开发者的奉献！！！

**Comment by ellya00** [comment]
目前obsidian的插件可以实现你的需求，一个是插件local image plus，有一个可以把全部md文件内的图片下载到本地的命令。还有image auto upload结合picgo可以实现单个文件内的图片的上传和下载。你可以把typora写的md文件放进ob下载，到本地附件文件夹就可以找到批量下载下来的图片了。

**Comment by Molunerfinn** [comment]
[picgo-plugin-pic-migrater](https://github.com/PicGo/picgo-plugin-pic-migrater) 能满足你的需求

**Comment by MR-liao-955** [comment]
感谢回复，看来这类大众化的需求开发者们早已想到！
