### ISSUE TITLE
[Bug]: “打开配置文件” 设置项的按钮点击后实际打开的是日志文件

### ISSUE THREAD

**Issue by zhongdongy** [Molunerfinn/PicGo#1163]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [X] [Issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)

### PicGo的版本 | PicGo Version

v2.4.0-beta.3

### 系统信息 | System Information

Windows

### 问题重现 | Bug reproduce

点击“PicGo设置” -> “（打开配置文件）点击打开”，编辑器（如记事本）会打开 PicGo 的日志

疑似[这部分代码有问题](https://github.com/Molunerfinn/PicGo/blob/894d0a243e4c0f38568d818b8f996eef5dc76e41/src/renderer/pages/components/settings/buttonArea/ButtonAreaSettings.vue#L2)

### 相关日志 | Logs

无需日志

**Comment by Molunerfinn** [comment]
感谢反馈，这个会在下个版本修复

**Comment by Molunerfinn** [comment]
2.4.0-beta4 已修复
