### ISSUE TITLE
[Bug]: Mac环境下toolbar小窗图片显示损坏

### ISSUE THREAD

**Issue by Aerdax** [Molunerfinn/PicGo#1164]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [X] [Issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)

### PicGo的版本 | PicGo Version

v2.3.1

### 系统信息 | System Information

Mac

### 问题重现 | Bug reproduce

使用SM.MS图床，上传图片后，toolbar图标展示预览图片是损坏的
![image](https://github.com/Molunerfinn/PicGo/assets/48790522/9ae7ea82-b6d5-4227-a189-25776562e95e)

**Comment by MkMarko** [comment]
图片链接可以访问 但是无法加载预览图

**Comment by MkMarko** [comment]
我也遇到这个问题了

**Comment by MkMarko** [comment]
我是七牛云的 把域名改为https带证书的就解决了 估计是没有处理http的问题
