### ISSUE TITLE
突然开始显示无法连接到github，试过重新下载软件、配置图床都没有用，希望大佬能指点指点。[Bug]: 

### ISSUE THREAD

**Issue by Bihuaa** [Molunerfinn/PicGo#1166]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [X] [Issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)

### PicGo的版本 | PicGo Version

v2.4.0-beta.3

### 系统信息 | System Information

Windows

### 问题重现 | Bug reproduce

![图床](https://github.com/Molunerfinn/PicGo/assets/102508773/5b109d03-cba3-4c7e-b49c-2087c588bd67)

### 相关日志 | Logs

------Error Stack Begin------
Error: Can't find github config
    at Object.tt [as handle] (D:\PicGo\resources\app.asar\node_modules\picgo\dist\index.cjs.js:1:27152)
    at je.doUpload (D:\PicGo\resources\app.asar\node_modules\picgo\dist\index.cjs.js:1:19658)
    at je.start (D:\PicGo\resources\app.asar\node_modules\picgo\dist\index.cjs.js:1:18417)
    at async $t.upload (D:\PicGo\resources\app.asar\node_modules\picgo\dist\index.cjs.js:1:72078)
    at async Object.upload (D:\PicGo\resources\app.asar\index.js:2:693580)
    at async fr (D:\PicGo\resources\app.asar\index.js:2:696313)
    at async D:\PicGo\resources\app.asar\index.js:2:697392
-------Error Stack End-------

**Comment by Molunerfinn** [comment]
你的配置文件内容截个图看看，关键的配置token啥的可以打个码。你这个报错不是连接不到 而是没找到对应的配置

**Comment by jiechen257** [comment]
> 你的配置文件内容截个图看看，关键的配置token啥的可以打个码。你这个报错不是连接不到 而是没找到对应的配置

大佬麻烦看下
<img width="1228" alt="image" src="https://github.com/Molunerfinn/PicGo/assets/73946940/9cee2631-720c-49cd-a19e-3c90899923d2">

**Comment by hyyxiaoluo** [comment]
我跟你一样，之前一直没事。只两天用了突然这样了。
------Error Stack Begin------
HttpError: request to https://api.github.com/repos/hyyxiaoluo/picgo/contents/img%2F2023%2F08%2F21%2F20230821042303.png failed, reason: connect ETIMEDOUT 20.205.243.168:443
    at D:\Environment\node-v16.16.0-win-x64\node_global\node_modules\picgo-plugin-github-plus\node_modules\@octokit\request\dist-node\index.js:108:11
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Octo.upload (D:\Environment\node-v16.16.0-win-x64\node_global\node_modules\picgo-plugin-github-plus\dist\lib\octokit.js:114:19)
    at async Object.handle (D:\Environment\node-v16.16.0-win-x64\node_global\node_modules\picgo-plugin-github-plus\dist\index.js:143:5)
    at async $e.doUpload (D:\software\PicGo\resources\app.asar\node_modules\picgo\dist\index.cjs.js:1:17198)
    at async $e.start (D:\software\PicGo\resources\app.asar\node_modules\picgo\dist\index.cjs.js:1:15969)
    at async Tt.upload (D:\software\PicGo\resources\app.asar\node_modules\picgo\dist\index.cjs.js:1:71270)
    at async Object.upload (D:\software\PicGo\resources\app.asar\background.js:2:661590)
    at async zn (D:\software\PicGo\resources\app.asar\background.js:2:664240)
-------Error Stack End-------

**Comment by jiechen257** [comment]
> 我跟你一样，之前一直没事。只两天用了突然这样了。找不到配置我也不太能理解啊，之前都可以 ------Error Stack Begin------ HttpError: request to https://api.github.com/repos/hyyxiaoluo/picgo/contents/img%2F2023%2F08%2F21%2F20230821042303.png failed, reason: connect ETIMEDOUT 20.205.243.168:443 at D:\Environment\node-v16.16.0-win-x64\node_global\node_modules\picgo-plugin-github-plus\node_modules@octokit\request\dist-node\index.js:108:11 at processTicksAndRejections (node:internal/process/task_queues:96:5) at async Octo.upload (D:\Environment\node-v16.16.0-win-x64\node_global\node_modules\picgo-plugin-github-plus\dist\lib\octokit.js:114:19) at async Object.handle (D:\Environment\node-v16.16.0-win-x64\node_global\node_modules\picgo-plugin-github-plus\dist\index.js:143:5) at async $e.doUpload (D:\software\PicGo\resources\app.asar\node_modules\picgo\dist\index.cjs.js:1:17198) at async $e.start (D:\software\PicGo\resources\app.asar\node_modules\picgo\dist\index.cjs.js:1:15969) at async Tt.upload (D:\software\PicGo\resources\app.asar\node_modules\picgo\dist\index.cjs.js:1:71270) at async Object.upload (D:\software\PicGo\resources\app.asar\background.js:2:661590) at async zn (D:\software\PicGo\resources\app.asar\background.js:2:664240) -------Error Stack End------- 2023-08-21 04:23:25 [PicGo SUCCESS]
> 
> 2023-08-21 04:25:10 [PicGo INFO] Before transform 2023-08-21 04:25:10 [PicGo INFO] Transforming... Current transformer is [path] 2023-08-21 04:25:10 [PicGo INFO] Before upload 2023-08-21 04:25:10 [PicGo INFO] beforeUploadPlugins: super-prefix running 2023-08-21 04:25:10 [PicGo INFO] beforeUploadPlugins: renameFn running 2023-08-21 04:25:10 [PicGo INFO] Uploading... Current uploader is [github] 2023-08-21 04:25:31 [PicGo WARN] failed 2023-08-21 04:25:31 [PicGo ERROR] { "method": "PUT", "url": "https://api.github.com/repos/hyyxiaoluo/picgo/contents/img/2023/08/21/20230821042510.png", "statusCode": 0, "message": "connect ETIMEDOUT 20.205.243.168:443", "stack": "Error: connect ETIMEDOUT 20.205.243.168:443\n at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1146:16)", "response": { "status": 0, "statusCode": 0, "body": "" } } ![image](https://user-images.githubusercontent.com/102205671/261875494-32375e86-e59d-4cc6-8b55-99725b823dc5.png)

我在我那个 issues 回复你了

**Comment by Bihuaa** [comment]
> 
部分配置信息如下
![日志](https://github.com/Molunerfinn/PicGo/assets/102508773/590a56f9-813c-400e-8ac0-a65e70cc1ef0)

**Comment by Molunerfinn** [comment]
> > 
> 
> 部分配置信息如下 ![日志](https://user-images.githubusercontent.com/102508773/261901040-590a56f9-813c-400e-8ac0-a65e70cc1ef0.jpg)

这个是日志不是配置信息。2.4.0-beta.3 有个bug，打开配置文件打开的是日志文件。请手动打开配置目录下的 data.json 看看 配置信息

**Comment by Bihuaa** [comment]
> 
好的，不好意思
![11](https://github.com/Molunerfinn/PicGo/assets/102508773/ca7403e1-1b94-404b-89e6-9e9c3803c527)

**Comment by Molunerfinn** [comment]
我看了一下，你的报错日志是 2023-05-31 的时候找不到配置文件；但是现在这份配置文件是对的，说明报错不是这个问题。

<img width="444" alt="image" src="https://github.com/Molunerfinn/PicGo/assets/12621342/fb930271-123f-4a82-9bc4-61051f95bd3a">

翻到最新的报错日志，我估计跟这个 issue 是一样的，参考他的处理或者配置一下 picgo 的代理

https://github.com/Molunerfinn/PicGo/issues/1167

**Comment by Bihuaa** [comment]
> 我看了一下，你的报错日志是 2023-05-31 的时候找不到配置文件；但是现在这份配置文件是对的，说明报错不是这个问题。
> 
> <img alt="image" width="444" src="https://user-images.githubusercontent.com/12621342/262012877-fb930271-123f-4a82-9bc4-61051f95bd3a.png">
> 翻到最新的报错日志，我估计跟这个 [issue](https://github.com/Molunerfinn/PicGo/issues/1167) 是一样的，参考他的处理或者配置一下 picgo 的[上传代理](https://picgo.github.io/PicGo-Doc/zh/guide/config.html#%E4%BB%A3%E7%90%86%E8%AE%BE%E7%BD%AE)（比如常见的 ss 的 http 代理是 [http://127.0.0.1:1080）](http://127.0.0.1:1080%EF%BC%89)
> 
> #1167

在PicGo内部配置了代理，已解决！超级感谢！又可以愉快使用Typopra了😊

**Comment by hyyxiaoluo** [comment]
我好想知道自己错在哪了，一是没加代理，二是之前branch选项我用的master不是main，换成main正常了。现在master 不能用了么，之前我填的master没事可以正常使用

**Comment by Molunerfinn** [comment]
从之前某个时间开始 gothub 创建的默认分支名已经改成了 main
