### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by karmagabx** [Molunerfinn/PicGo#1168]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [X] [Issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)

### PicGo的版本 | PicGo Version

1,4,7

### 系统信息 | System Information

Windows

### 问题重现 | Bug reproduce

./picgo u OIP.jpg
[PicGo INFO]: Before transform
[PicGo INFO]: Transforming...
[PicGo INFO]: Before upload
[PicGo INFO]: Uploading...
[PicGo INFO]: [信息]{version:3,uploadPath:阿里云盘\MDpic,fileName:OIP.jpg}
[PicGo INFO]: [信息]已经写入文件C:\Users\shello\AppData\Local\Temp\OIP.jpg
[PicGo ERROR]: Error: [上传操作]异常：ctx.request is not a function
[PicGo SUCCESS]:
undefined

**Comment by Molunerfinn** [comment]
你的 picgo 版本太低了更新一下吧。同时你用的是插件上传？那么请去插件仓库提问
