### ISSUE TITLE
[Bug]: 无法安装提示picgo已损坏

### ISSUE THREAD

**Issue by midsmr** [Molunerfinn/PicGo#1169]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [X] [Issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)

### PicGo的版本 | PicGo Version

2.3.1

### 系统信息 | System Information

Mac(arm64)

### 问题重现 | Bug reproduce

<img width="1002" alt="截屏2023-08-22 23 04 23" src="https://github.com/Molunerfinn/PicGo/assets/61633355/01ba1e92-2f24-4a24-8dd8-8d73b88c54b2">
<img width="372" alt="截屏2023-08-22 23 06 32" src="https://github.com/Molunerfinn/PicGo/assets/61633355/33ac068c-5465-4a99-91b7-98f6ae9ab6a0">

### 相关日志 | Logs

无logs

**Comment by midsmr** [comment]
GitHub Release下载的dmg安装包，也是一样

**Comment by Molunerfinn** [comment]
请问你看过 FAQ 么？
![Uploading image.png…]()
