### ISSUE TITLE
图片上传 bug

### ISSUE THREAD

**Issue by giraffe-tree** [Molunerfinn/PicGo#117]
## 问题类型

Bug Report

## PicGo的相关信息

picGo 1.6.2
win 10 
使用的是阿里云 OSS 

## 问题重现

一下子上传 4 张 12 M左右的图片, 卡住一会儿后,  只有一张上传成功, , 图册中却显示 4 张一模一样的图片

![bug](https://data-chen.oss-cn-hangzhou.aliyuncs.com/photo/1537972959%281%29.png?x-oss-process=style/default)

**Comment by Molunerfinn** [comment]
嗯这是个bug，而且只会出现在阿里云里。因为一个循环里的i写成了0。目前的解决方案是你可以先设定一下自定义域名：（你可以直接设置成阿里云给你的域名也没关系）
![image](https://user-images.githubusercontent.com/12621342/46089514-45f0a000-c1e1-11e8-998a-99e6f5e49d4c.png)
这样就不会出现这个问题了。2.0版本里将会修复这个bug。

**Comment by Molunerfinn** [comment]
另外「卡住」只是因为上传需要时间尤其是你的图片很大...所以实际上多张图片都是上传成功的，你可以在你阿里云后台看到。建议不要上传太大的图片，一个是等待时间太长，另外一个是这么大的图片的url也不推荐用来使用。
