### ISSUE TITLE
[Feature]: 希望 Picgo Server 可以识别更多的参数，或开放更多的端口

### ISSUE THREAD

**Issue by uuanqin** [Molunerfinn/PicGo#1170]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [X] [Issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)

### PicGo的版本 | PicGo Version

v2.4.0 beta0

### 系统信息 | System Information

Windows

### 功能请求 | Feature request

目前使用知识库软件记笔记（Obsidian），拖拽图片时第三方插件向Picgo Server发送HTTP请求，并请求使用默认配置上传至图床。我的需求是，不同知识库的图片上传到不同的图床中，即每张需要上传的图片可以自主选择使用不同的图床配置。Picgo server可否通过开放更多监听端口或识别HTTP参数实现这一功能？

如果选择开发Picgo插件以实现相关功能的话是否可行？

**Comment by Molunerfinn** [comment]
不需要改端口 picgo现在支持同一图床多分配置 你只需要上传前切换不同的配置就行。用插件可以实现切换配置

**Comment by uuanqin** [comment]
意思是每次上传前都需要手动切换配置吗？因为平时经常在几个Obsidian知识库进行切换，可能会比较麻烦。我目前的想法是开发Picgo插件，识别url参数以选择不同的图床配置上传图片，如`http://127.0.0.1:36677/upload/config1`，`http://127.0.0.1:36677/upload?config=1`这种

**Comment by Molunerfinn** [comment]
哦我说的是可以通过插件实现切换配置，但是切换的规则可以你自己定。目前 server 还没开放插件接口，可能需要别的方式处理
