### ISSUE TITLE
[Bug]: 双击打开无反应

### ISSUE THREAD

**Issue by SynMarc** [Molunerfinn/PicGo#1172]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [X] [Issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)

### PicGo的版本 | PicGo Version

2.3.0及以上版本

### 系统信息 | System Information

Windows

### 问题重现 | Bug reproduce

将安装路径改到D盘，安装结束双击打开，任务管理器中虽然显示程序在后台运行，但是无界面。使用默认路径则无上述问题。

**Comment by Molunerfinn** [comment]
在右下角任务栏

**Comment by SynMarc** [comment]
右下角没有picgo的图标。不知道是win11系统问题还是amd处理器问题或者二者结合的问题。之前在win10+intel的机器上是没问题的。

**Comment by SynMarc** [comment]
> 在右下角任务栏


右下角没有picgo的图标。不知道是win11系统问题还是amd处理器问题或者二者结合的问题。之前在win10+intel的机器上是没问题的。

**Comment by Molunerfinn** [comment]
有点奇怪 不过我手头没有 win11的机器 还不是很好解决。后续会开放一些配置 比如让窗口默认打开

**Comment by Molunerfinn** [comment]
我是amd+win10 目前是正常的

**Comment by SynMarc** [comment]
> 应该是我这边机器的问题。我的个别其它软件，如steam等也遇到了这个问题
