### ISSUE TITLE
[Bug]: 删除后重新安装配置完GitHub

### ISSUE THREAD

**Issue by NAILIANGCHI** [Molunerfinn/PicGo#1174]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [X] [Issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)

### PicGo的版本 | PicGo Version

v2.3.1

### 系统信息 | System Information

Windows

### 问题重现 | Bug reproduce

更换设备或者卸载重新安装后配置完GitHub图床后，之前的图片不会在应用的相册里显示了，请问时我配置有问题还是不支持读取GitHub上面的图片？

**Comment by Molunerfinn** [comment]
不支持。

**Comment by NAILIANGCHI** [comment]
您好！您的邮件我已经收到。阅读后尽快给您回复！

**Comment by NAILIANGCHI** [comment]
> 不支持。

好的了解了😉
