### ISSUE TITLE
[Feature]: 能补充一下upload接口描述吗

### ISSUE THREAD

**Issue by m986883511** [Molunerfinn/PicGo#1176]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [X] [Issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)

### PicGo的版本 | PicGo Version

2.4.0 beta1

### 系统信息 | System Information

Windows

### 功能请求 | Feature request

我通常是用obsidian里面的图传插件，结合picgo的upload接口使用的。

我想自行开发纯后台的图传上传服务，我不太懂js，比较熟练python，我的图床是github，我可以自己实现socket5代理上传github。纯python的命令行上传github已经找到开源实现了。

但是没找到upload上传请求是怎么描述的，我找了https://picgo.github.io/PicGo-Core-Doc/zh/api/#upload-input 这个说明，但描述的不是很清晰，没有写返回是什么样的。

能像podman那种，提供下upload的接口描述吗

**Comment by Molunerfinn** [comment]
https://picgo.github.io/PicGo-Doc/zh/guide/advance.html#picgo-server%E7%9A%84%E4%BD%BF%E7%94%A8
