### ISSUE TITLE
[Bug]: mac arm 中，右击面板的workflow 无法复制到 /Library/Service 中，导致右击菜单中缺少 picgo 选项

### ISSUE THREAD

**Issue by muwoo** [Molunerfinn/PicGo#1179]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [X] [Issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)

### PicGo的版本 | PicGo Version

v2.3.1

### 系统信息 | System Information

Mac(arm64)

### 问题重现 | Bug reproduce

必现的

### 相关日志 | Logs

这个问题是 electron 的bug，这里有相关的issue说明：
https://github.com/electron/electron/issues/14320

后面他们修复了，我给你提个pr吧

**Comment by Molunerfinn** [comment]
感谢反馈
