### ISSUE TITLE
[Bug]: 同类图床（此处为GitHub）添加新的图床位置会覆盖先前的图床而不是新建

### ISSUE THREAD

**Issue by Yukii2333** [Molunerfinn/PicGo#1184]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [X] [Issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)

### PicGo的版本 | PicGo Version

v2.4.0-beta.4

### 系统信息 | System Information

Windows

### 问题重现 | Bug reproduce

![image](https://github.com/Molunerfinn/PicGo/assets/116934686/5a4619a9-f291-4d5d-adfc-47444bea9dda)
此处新建与编辑同效果了，前面版本还没问题的

**Comment by Yukii2333** [comment]
是beta5

**Comment by Molunerfinn** [comment]
感谢反馈 近期会看看原因

**Comment by Molunerfinn** [comment]
已经修复，会在下个 beta 版本带出去；再次感谢反馈！
