### ISSUE TITLE
[Bug]: 腾讯云对象存储在picgo上传失败，但是在腾讯云控制台可以正常上传

### ISSUE THREAD

**Issue by LaPhilosophie** [Molunerfinn/PicGo#1186]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [X] [Issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)

### PicGo的版本 | PicGo Version

v2.3.1

### 系统信息 | System Information

Windows

### 问题重现 | Bug reproduce

感谢开发者做出怎么好用的picgo，我出现了一些问题，希望解答。之前一直是用相同的腾讯云存储配置，上传腾讯云对象存储正常使用，这次忽然就上传失败了。

有如下尝试：
1.换了picgo软件版本，依旧报错
2.使用相同腾讯云对象存储配置在Windows和MacBook两个测试，都无法上传
3.腾讯云管理控制台的上传页面，可以上传通过，也可以正常访问图片
4.使用GitHub在picgo可以正常上传
5.我使用抓包软件也没分析出什么结果
6.多次确认腾讯云存储配置无误

### 相关日志 | Logs

2023-10-13 12:18:39 [PicGo ERROR] {
  "method": "PUT",
  "url": "http://picgo-1305151344.cos.ap-nanjing.myqcloud.com/img%2F202310131218920.png",
  "statusCode": 0,
  "message": "read ECONNRESET",
  "stack": "Error: read ECONNRESET\n    at TCP.onStreamRead (node:internal/stream_base_commons:220:20)",
  "response": {
    "status": 0,
    "statusCode": 0,
    "body": ""
  }
}

**Comment by Molunerfinn** [comment]
这是网络报错 检查你是否配置了全局代理或者给picgo配置了代理之类的。腾讯云cos的接口代理下有可能失败

**Comment by Zyoohi** [comment]
全局代理已经关了，picgo也没配置了代理，还是报这个错是什么原因？
