### ISSUE TITLE
[Bug]: 不能给单一图床添加额外的配置

### ISSUE THREAD

**Issue by Sincejunly** [Molunerfinn/PicGo#1196]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [X] [Issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)

### PicGo的版本 | PicGo Version

PicGo-Setup-2.4.0-beta.5-x64.exe

### 系统信息 | System Information

Windows

### 问题重现 | Bug reproduce

点击加号不能设置新的配置，不能给单一图床添加额外的配置
![image](https://github.com/Molunerfinn/PicGo/assets/96775034/3c9a2544-902f-4f3f-8354-c0294e072e39)

**Comment by Molunerfinn** [comment]
已知问题，已经修复还没发版；可以先用 beta4
