### ISSUE TITLE
[Bug]: 图床无法增加配置

### ISSUE THREAD

**Issue by AriaLyy** [Molunerfinn/PicGo#1198]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [X] [Issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)

### PicGo的版本 | PicGo Version

2.4.0-beta5

### 系统信息 | System Information

Mac

### 问题重现 | Bug reproduce

发现一个问题，无法对图床新增配置，复现步骤：
1、我用的是七牛云，我原来的版本是2.3.1，然后升级到了2.4.0-beta5版本
2、然后我打开图床的七牛云配置，点击 `+`新增配置
3、填写完成点击确认后，发现并没有新增配置，而是修改了我原来的配置
![input_soft](https://github.com/Molunerfinn/PicGo/assets/10437293/87127bed-bc0f-42a0-bfad-04fdb46a6c93)

**Comment by AriaLyy** [comment]
我重新下载安装2.4.0-beta.0版本就正常了，在2.4.0-beta.5版本是有问题，点加号变成了修改原配置而不是新增配置

**Comment by Molunerfinn** [comment]
是的，已知问题已经修复，还没发版，下个 beta 版本会修复

https://github.com/Molunerfinn/PicGo/issues/1196
