### ISSUE TITLE
[Feature]: 能否增加配置备份功能

### ISSUE THREAD

**Issue by AriaLyy** [Molunerfinn/PicGo#1199]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [X] [Issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)

### PicGo的版本 | PicGo Version

v2.4.0.beta.0

### 系统信息 | System Information

All

### 功能请求 | Feature request

我电脑比较多，公司两台、家里两台，每次修改picogo的图床的配置，都需要修改4次，能否提供一个备份和恢复的功能，比如可以备份到坚果云，然后其它设备可以从坚果云拉取备份。
类似[pot-app](https://github.com/pot-app/pot-desktop)的这个webdav备份

![image](https://github.com/Molunerfinn/PicGo/assets/10437293/0d71660e-517a-4ec6-b74b-cef6df306c6b)

**Comment by Molunerfinn** [comment]
打开配置文件，可以通过 `configPath` 这个属性指定配置文件路径，可以指定到额外的路径，比如你坚果云同步本地的一个目录。前提是这个文件同样需要以 json 结尾。

你可以把你的配置文件复制一份到指定路径，比如 `/Users/xxxx/xxx/data.json`，然后在 picgo 的默认配置里添加 `configPath` 属性如下：

示例：

```json
{
  "configPath": "/Users/xxxx/xxx/data.json"
  "picBed": {
    "current": "tcyun",
    "uploader": "tcyun",
    ....,
}
```


后续会通过 github 做一个官方的同步配置插件

**Comment by AriaLyy** [comment]
老哥，这个方法不行，我这边用的是坚果云，这样配置后，会出现大量的链接，导致被坚果云临时封禁。是不是picgo读取配置时会大量写配置文件夹的文件呢？

**Comment by Molunerfinn** [comment]
安装插件 上传文件等才会又写操作。正常一般是读操作
