### ISSUE TITLE
外接显示器下点开下拉窗口的适配问题。

### ISSUE THREAD

**Issue by StudentWan** [Molunerfinn/PicGo#12]
我在外接显示器（1920 * 1080）下点开下拉窗口的时候位置比较奇怪

发上来看看，并不影响使用

![显示问题](http://p20zi8dae.bkt.clouddn.com/2018-1-7-下午5:05:46.png)

**Comment by Molunerfinn** [comment]
噫，真是个奇怪的bug。顺便问一句主窗口打开的时候位置也是往下偏移的么？回头我定位一下这个问题。下个版本修复一下。

**Comment by StudentWan** [comment]
@Molunerfinn 主窗口没有诶

**Comment by Molunerfinn** [comment]
![image](https://user-images.githubusercontent.com/12621342/34710940-39348378-f558-11e7-9736-bd046a467578.png)
奇怪的是我也接上1920分辨率的外接显示器，然而无法复现问题。
![image](https://user-images.githubusercontent.com/12621342/34710974-5fc1251e-f558-11e7-8f6a-71fc5ee9f37f.png)
不知道是不是个个例。

**Comment by Molunerfinn** [comment]
v1.2.1版本更新了，考虑更新一下。若无其他跟进问题，issue先关了~
