### ISSUE TITLE
[Feature]: 可以加一下大佬微信嘛？有信息反馈

### ISSUE THREAD

**Issue by muwoo** [Molunerfinn/PicGo#1201]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [X] [Issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)

### PicGo的版本 | PicGo Version

v2.3.1

### 系统信息 | System Information

Windows

### 功能请求 | Feature request

可以加一下大佬微信嘛？有信息反馈

**Comment by Molunerfinn** [comment]
发我邮件吧
