### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by minixiaoxin** [Molunerfinn/PicGo#1207]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [X] [Issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)

### PicGo的版本 | PicGo Version

v2.3.1

### 系统信息 | System Information

Windows

### 问题重现 | Bug reproduce

【系统】
Windows 11 23H2
【步骤】
1、进入PicGo相册页面，上传超过12张图片检查页面左侧留白和底部留白。同官方文档比对
【预期】
1、间隔应该要一致
【实际】
2、留白空间变大，或多出不必要留白空间

对比了一下文档中的相册页面的距离，好像是这个版本软件距离变大了，看着怪怪的，溜了很大一片空白：
![image](https://github.com/Molunerfinn/PicGo/assets/45511100/184bf1ef-3394-4a0c-bb3f-a513d94000fe)
期望修复，感谢！

**Comment by Molunerfinn** [comment]
picgo的窗体尺寸是写死的 按理说不会有这么大的间隔。我用win10 打开也是正常的

**Comment by minixiaoxin** [comment]
我发现，这个现象是在经历在不同屏幕之间拖动之后才出现。我这边外接1个屏幕，从2560 × 1600分辨率拖动到2560 × 1440才会出现。如果不拖动这个现实的是好的。。

**Comment by minixiaoxin** [comment]
![image](https://github.com/Molunerfinn/PicGo/assets/45511100/4caf6d1a-89da-4fcd-b105-8d68ca6f2183)

**Comment by Molunerfinn** [comment]
可能确实跟分辨率有点关系。这块优先级稍微低一些，回头会看看如何做高分屏适配

**Comment by Molunerfinn** [comment]
暂时关闭，后续看看升级 electron 有没有效果
