### ISSUE TITLE
[Feature]: 自定义链接无效，请求修复

### ISSUE THREAD

**Issue by GrantKnoche** [Molunerfinn/PicGo#1208]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [X] [Issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)

### PicGo的版本 | PicGo Version

2.3.0

### 系统信息 | System Information

Windows

### 功能请求 | Feature request

`<img src="($url)" width="500">`  是我想设置的格式，但无法实现，还是和默认的一样以`![]($url)`的形式存在

**Comment by Molunerfinn** [comment]
你设置了之后请选择custom格式再进行复制
