### ISSUE TITLE
[Bug]: 删除了github图床仓库，为什么上传的url还能访问图片？

### ISSUE THREAD

**Issue by collidegit** [Molunerfinn/PicGo#1209]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [X] [Issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)

### PicGo的版本 | PicGo Version

PicGo-2.4.0-beta.6

### 系统信息 | System Information

Windows

### 问题重现 | Bug reproduce

我已经手动删除了github图床仓库，picgo相册也删除了，为什么之前上传的图片的https的url还能访问图片？

**Comment by Molunerfinn** [comment]
请你去问github
