### ISSUE TITLE
[Bug]: 点击复制之前的项目，实际复制失败

### ISSUE THREAD

**Issue by oooo0oooo0** [Molunerfinn/PicGo#1210]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [X] [Issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)

### PicGo的版本 | PicGo Version

v2.4.0-beta.6

### 系统信息 | System Information

Mac(arm64)

### 问题重现 | Bug reproduce

从状态栏点开应用，点击任意一个元素复制其 url，通知提示复制成功，但是实际剪贴板没有

### 相关日志 | Logs

日志中没有相关内容，最后一条日志是说成功上传了一个文件

**Comment by oooo0oooo0** [comment]
对了，打开主窗口，通过相册文件点击复制就可以正常使用

**Comment by Molunerfinn** [comment]
回头看下咋回事

**Comment by qq937728** [comment]
这个问题已经提出1年多了，怎么还不给解决，微信上也和作者说了，作者说上github提，也提了。

**Comment by Molunerfinn** [comment]
已修复，跟下个 beta 版本

**Comment by Molunerfinn** [comment]
https://github.com/Molunerfinn/PicGo/releases/tag/v2.4.0-beta.9
已发布，欢迎更新体验
