### ISSUE TITLE
[Bug]: 又拍云服务上传失败

### ISSUE THREAD

**Issue by 90zm** [Molunerfinn/PicGo#1214]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [X] [Issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)

### PicGo的版本 | PicGo Version

v2.3.1

### 系统信息 | System Information

Windows

### 问题重现 | Bug reproduce

有一次上传一张图片成功，之后第二张照片就没有办法上传了。
读FAQ看401是配置问题，配置检查了很多遍，没有问题。请问大佬们这会是什么问题。

### 相关日志 | Logs

2024-01-29 22:36:22 [PicGo INFO] Before transform 
2024-01-29 22:36:22 [PicGo INFO] Transforming... Current transformer is [path] 
2024-01-29 22:36:22 [PicGo INFO] Before upload 
2024-01-29 22:36:22 [PicGo INFO] beforeUploadPlugins: renameFn running 
2024-01-29 22:36:22 [PicGo INFO] Uploading... Current uploader is [upyun] 
2024-01-29 22:36:23 [PicGo WARN] failed 
2024-01-29 22:36:23 [PicGo ERROR] {
  "method": "PUT",
  "url": "https://v0.api.upyun.com/typorazm/202401292236304.jpg",
  "statusCode": 401,
  "message": "Request failed with status code 401",
  "stack": {},
  "response": {
    "status": 401,
    "statusCode": 401,
    "body": {
      "msg": "signature error",
      "code": 40100005,
      "id": "5486020283e12a92abf034129bf0d4be"
    }
  }
} 
2024-01-29 22:36:23 [PicGo ERROR] {
  "method": "PUT",
  "url": "https://v0.api.upyun.com/typorazm/202401292236304.jpg",
  "statusCode": 401,
  "message": "Request failed with status code 401",
  "stack": {},
  "response": {
    "status": 401,
    "statusCode": 401,
    "body": {
      "msg": "signature error",
      "code": 40100005,
      "id": "5486020283e12a92abf034129bf0d4be"
    }
  }
}

**Comment by 90zm** [comment]
查了一下又拍云的api错误码




<html>
<body>

401 | 40100005 | signature error | 请求签名错误
-- | -- | -- | --



</body>
</html>

**Comment by Molunerfinn** [comment]
这个就是你自己的配置问题，配置出错了就会导致又拍云认为你的签名有问题。可以打开配置文件直接仔细确认下配置各项是否正确。这个是个人配置问题 不是 picgo的问题。

**Comment by 90zm** [comment]
> 这个就是你自己的配置问题，配置出错了就会导致又拍云认为你的签名有问题。可以打开配置文件直接仔细确认下配置各项是否正确。这个是个人配置问题 不是 picgo的问题。

好的，谢谢大佬，我再检查一下！

**Comment by 90zm** [comment]
> 这个就是你自己的配置问题，配置出错了就会导致又拍云认为你的签名有问题。可以打开配置文件直接仔细确认下配置各项是否正确。这个是个人配置问题 不是 picgo的问题。

感谢大佬，我重新检查了一下，中间更新版本重新填写配置信息的时候将**S3 访问凭证**当成了**授权账户设定操作员密码**。
![image](https://github.com/Molunerfinn/PicGo/assets/44014367/45e2f05f-c495-431d-b525-dadea66237d8)
![image](https://github.com/Molunerfinn/PicGo/assets/44014367/a15406cf-0925-47b4-b321-b55e55854e11)

**Comment by Molunerfinn** [comment]
嗯嗯 解决了就好
