### ISSUE TITLE
[Bug]: 无法更新配置文件

### ISSUE THREAD

**Issue by homuraLan** [Molunerfinn/PicGo#1215]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [X] [Issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)

### PicGo的版本 | PicGo Version

目前最新的版本

### 系统信息 | System Information

Windows

### 问题重现 | Bug reproduce

经过测试UI还是core都有该问题，在插件更新之后其配置项无法更新，有着自己的缓存，不论更新几次都一样
![image](https://github.com/Molunerfinn/PicGo/assets/96775034/4abb678e-dd3c-4790-8399-5c0e3a45fcb7)

**Comment by Molunerfinn** [comment]
插件更新成功后 需要重启picgo才能生效
