### ISSUE TITLE
[Bug]: 安装后打开报文件已损坏

### ISSUE THREAD

**Issue by francisLee777** [Molunerfinn/PicGo#1216]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [X] [Issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)

### PicGo的版本 | PicGo Version

2.4.0-beta.6

### 系统信息 | System Information

Mac(arm64)

### 问题重现 | Bug reproduce

MacOS 14.3 M系列打不开，不兼容，并在2.3.0版本中也是一样。
![image](https://github.com/Molunerfinn/PicGo/assets/30818378/df11a60a-f5dd-4e42-a700-4f894bdb10b5)

**Comment by Molunerfinn** [comment]
请问你阅读过 FAQ 么？没有阅读为什么打勾呢
![image](https://github.com/Molunerfinn/PicGo/assets/12621342/a4fb5374-b336-4ba2-979c-cbddfea053b6)
