### ISSUE TITLE
[Bug]: 右击窗口不显示，一闪而过

### ISSUE THREAD

**Issue by QThans** [Molunerfinn/PicGo#1217]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [X] [Issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)

### PicGo的版本 | PicGo Version

v2.4.0-beta.6

### 系统信息 | System Information

Mac(arm64)

### 问题重现 | Bug reproduce

https://github.com/Molunerfinn/PicGo/assets/18275400/0137d559-839f-460d-a63b-5d5f27e8217e

**Comment by Molunerfinn** [comment]
没法复现，不过可以试试按住 cmd 键拖拽 picgo 图标到右边一些，可能在最左边处于隐藏状态了

**Comment by QThans** [comment]
> 没法复现，不过可以试试按住 cmd 键拖拽 picgo 图标到右边一些，可能在最左边处于隐藏状态了

尝试了还是不行，我clone下代码看看

**Comment by QThans** [comment]
https://github.com/Molunerfinn/PicGo/assets/18275400/45528d12-577b-4a62-a8df-d1f9de2a3438

加上timeout以后就可以了,我对electron不太熟,不知道具体原因.debug中无意发现.

**Comment by QThans** [comment]
测试了会儿，看了会儿文档，觉得可能还是electron的问题。
我的Mac，2023 Mac mini M2 16G
OS：14.3.1 (23D60)

**Comment by QThans** [comment]
@Molunerfinn 可以按照这样修复吗？

**Comment by Molunerfinn** [comment]
可以的，我回头试一下。这个一定要200ms么，setTimeout 0 可以么

**Comment by QThans** [comment]
setTimeout以后就可以

**Comment by Molunerfinn** [comment]
好的，我处理一波
