### ISSUE TITLE
支援Github同帳號多個repo切換

### ISSUE THREAD

**Issue by flawlessprime** [Molunerfinn/PicGo#122]
## 问题类型

Feature Request

## PicGo的相关信息

Mac(主要使用) & Windows

## 功能请求

目前Github好像只有提供連結一個repo作上傳
但每個repo好像有容量限制1G左右，因此希望未來能夠支援多個repo作上傳，
例如設置過ＡＢＣ三個repo後，
上傳時能在選擇默認圖床的清單中，能從ＡＢＣ三個repo擇一設置為默認，再做上傳。

謝謝您！

---

**Comment by Molunerfinn** [comment]
本体不打算支持做任何切换帐号的操作。你可以自行修改配置文件。


 :octocat: [From gitme iOS](http://flutterchina.club/app/gm.html)
