### ISSUE TITLE
[Feature]: 是否有国产统信UOS linux系统ARM64位的安装包。

### ISSUE THREAD

**Issue by KUHE0000** [Molunerfinn/PicGo#1223]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [X] [Issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)

### PicGo的版本 | PicGo Version

PicGo-2.4.0-beta.6.AppImage

### 系统信息 | System Information

Linux

### 功能请求 | Feature request

您好，作者，我的系统是国产统信UOS linux系统，架构是ARM64的，运行PicGo-2.4.0-beta.6.AppImage，提示：
![image](https://github.com/Molunerfinn/PicGo/assets/136438172/52e623a8-35f6-4ffb-9b0a-038718ec69e1)
目前有ARM64位的包吗？

**Comment by Molunerfinn** [comment]
暂时没有。这里可能需要手动构建一下。
