### ISSUE TITLE
[Bug]: 上传图片后，在相册中的链接中自动在我文件名前加入“undefined”

### ISSUE THREAD

**Issue by FeatherWaves666** [Molunerfinn/PicGo#1225]
### 前置阅读 | Pre-reading

- [x] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [X] [Issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)

### PicGo的版本 | PicGo Version

2.4.0-beta.6

### 系统信息 | System Information

Windows

### 问题重现 | Bug reproduce

![image](https://github.com/Molunerfinn/PicGo/assets/77005595/a3f50350-db31-42c4-b586-9411c404d6df)

**Comment by Molunerfinn** [comment]
你的图床是什么 配置是啥样的？ 日志呢

**Comment by FeatherWaves666** [comment]
> 你的图床是什么 配置是啥样的？ 日志呢

**图床：**

GitHub

**日志文件：**

2024-03-11 12:01:57 [PicGo INFO] [PicGo Server] get the request {"list":["C:\\Users\\Waves\\AppData\\Roaming\\Typora\\typora-user-images\\image-20240311120157366.png"]} 
2024-03-11 12:01:57 [PicGo INFO] [PicGo Server] upload files in list 
2024-03-11 12:01:57 [PicGo INFO] Before transform 
2024-03-11 12:01:57 [PicGo INFO] Transforming... Current transformer is [path] 
2024-03-11 12:01:57 [PicGo INFO] Before upload 
2024-03-11 12:01:57 [PicGo INFO] beforeUploadPlugins: renameFn running 
2024-03-11 12:01:57 [PicGo INFO] Uploading... Current uploader is [github] 
2024-03-11 12:01:58 [PicGo SUCCESS] 
https://cdn.jsdelivr.net/gh/Waves/blogImage@main/undefinedimage-20240311120157366.png 
2024-03-11 12:01:58 [PicGo INFO] [PicGo Server] upload result https://cdn.jsdelivr.net/gh/Waves/blogImage@main/undefinedimage-20240311120157366.png 

**配置：**

{
  "picBed": {
    "current": "github",
    "uploader": "github",
    "smms": {
      "token": ""
    },
    "qiniu": {
      "_configName": "Default",
      "_id": "caa072a2-0f3e-4abd-b2c1-c32e7e81fd21",
      "_createdAt": 1709182142528,
      "_updatedAt": 1709182142528
    },
    "github": {
      "_configName": "blogImage",
      "repo": "Waves/blogImage",
      "branch": "main",
      "token": "ghp_id5F6kr6hH14nae6haKL1Oi0UYOJbo0",
      "customUrl": "https://cdn.jsdelivr.net/gh/Waves/blogImage@main",
      "_id": "efb22efb-0bbc-40a2-8036-d4827efe27cd",
      "_createdAt": 1709182283906,
      "_updatedAt": 1709182283906
    },
    "proxy": ""
  },
  "settings": {
    "shortKey": {
      "picgo:upload": {
        "enable": true,
        "key": "CommandOrControl+Shift+P",
        "name": "upload",
        "label": "QUICK_UPLOAD"
      }
    },
    "showUpdateTip": true,
    "server": {
      "port": 36677,
      "host": "127.0.0.1",
      "enable": true
    },
    "privacyEnsure": true,
    "pasteStyle": "URL",
    "npmProxy": "",
    "npmRegistry": "",
    "autoStart": true
  },
  "needReload": false,
  "picgoPlugins": {},
  "debug": true,
  "PICGO_ENV": "GUI",
  "uploader": {
    "qiniu": {
      "configList": [
        {
          "_configName": "Default",
          "_id": "caa072a2-0f3e-4abd-b2c1-c32e7e81fd21",
          "_createdAt": 1709182142528,
          "_updatedAt": 1709182142528
        }
      ],
      "defaultId": "caa072a2-0f3e-4abd-b2c1-c32e7e81fd21"
    },
    "github": {
      "configList": [
        {
          "_configName": "Default",
          "_id": "3326c6d9-50ac-4edc-b8d5-3c21673047b5",
          "_createdAt": 1709182148260,
          "_updatedAt": 1709182148260
        },
        {
          "_configName": "blogImage",
          "repo": "Waves/blogImage",
          "branch": "main",
          "token": "ghp_id5F6kr6hH14nae6haKL1Oi0UYOJbo0",
          "customUrl": "https://cdn.jsdelivr.net/gh/Waves/blogImage@main",
          "_id": "efb22efb-0bbc-40a2-8036-d4827efe27cd",
          "_createdAt": 1709182283906,
          "_updatedAt": 1709182283906
        }
      ],
      "defaultId": "efb22efb-0bbc-40a2-8036-d4827efe27cd"
    }
  }
}

**Comment by Molunerfinn** [comment]
你的配置里，少了 path 这一项，导致获取的时候拿到的 undefined，如果你的 path 是 空的，可以手动处理成 ""。 不要直接修改配置文件，请在 picgo 配置界面里设定存储路径，可以先随便输入一个，点保存，然后再清空，点保存即可。
<img width="152" alt="image" src="https://github.com/Molunerfinn/PicGo/assets/12621342/acd97ce5-ac77-482b-b994-5b65a94499ee">
<img width="484" alt="image" src="https://github.com/Molunerfinn/PicGo/assets/12621342/f3ef52f9-e297-4e8c-b7a2-80c911fc2ea9">


<img width="537" alt="image" src="https://github.com/Molunerfinn/PicGo/assets/12621342/05121a5d-521a-4b56-8d0f-0eaffeef77e8">

**Comment by FeatherWaves666** [comment]
> 你的配置里，少了 path 这一项，导致获取的时候拿到的 undefined，如果你的 path 是 空的，可以手动处理成 ""。 不要直接修改配置文件，请在 picgo 配置界面里设定存储路径，可以先随便输入一个，点保存，然后再清空，点保存即可。 <img alt="image" width="152" src="https://private-user-images.githubusercontent.com/12621342/313480640-acd97ce5-ac77-482b-b994-5b65a94499ee.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA2ODY4NzcsIm5iZiI6MTcxMDY4NjU3NywicGF0aCI6Ii8xMjYyMTM0Mi8zMTM0ODA2NDAtYWNkOTdjZTUtYWM3Ny00ODJiLWI5OTQtNWI2NWE5NDQ5OWVlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE3VDE0NDI1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkyODhiOTY0YmE5N2FlMTllNmVjZjZkMTk1NDc2NmVhZThlZjhmOWZlNzQ1NDA3NDY2ZWUzMGRhNTdiMTVkNzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.IZRwxv-c2zBKQk_6hPaj8c-41cRKP6zsB69EEeLJjls"> <img alt="image" width="484" src="https://private-user-images.githubusercontent.com/12621342/313480745-f3ef52f9-e297-4e8c-b7a2-80c911fc2ea9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA2ODY4NzcsIm5iZiI6MTcxMDY4NjU3NywicGF0aCI6Ii8xMjYyMTM0Mi8zMTM0ODA3NDUtZjNlZjUyZjktZTI5Ny00ZThjLWI3YTItODBjOTExZmMyZWE5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE3VDE0NDI1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdiNTRmNjUzYjIwNDMzZTE2ZDVlYjkzNTE2ZTgzMDA3Y2VhZmQyNWViN2MyN2MyY2MwNzMxYjRiNjNlZGI4YzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.i-OW_nE6U--Ak20ZU1XeTVyeZvPXyivGIy6PRB1h4bc">
> 
> <img alt="image" width="537" src="https://private-user-images.githubusercontent.com/12621342/313480539-05121a5d-521a-4b56-8d0f-0eaffeef77e8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA2ODY4NzcsIm5iZiI6MTcxMDY4NjU3NywicGF0aCI6Ii8xMjYyMTM0Mi8zMTM0ODA1MzktMDUxMjFhNWQtNTIxYS00YjU2LThkMGYtMGVhZmZlZWY3N2U4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE3VDE0NDI1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU4MTJkYjk1NDIzOWYzNmI0NGFmZjUyYzkwYjhjYTk0YmRiZmJlOTBmZjY1MGVhMmI1ZDk1NTFlMjlmZWQzOWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.CiTxkQMRvfQm8g5RZh4qAnwJy26ULxlKoNR7G9YOmBo">

非常感谢，已解决👍
