### ISSUE TITLE
希望可以提供便携版

### ISSUE THREAD

**Issue by hausen1012** [Molunerfinn/PicGo#1226]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [X] [Issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)

### PicGo的版本 | PicGo Version

v2.3.1

### 系统信息 | System Information

Windows

### 功能请求 | Feature request

希望有便携版，便于多终端使用，这样的话不需要每台电脑都安装，只需要通过 onedrive 同步即可

**Comment by Molunerfinn** [comment]
暂不考虑，你可以自行打包
