### ISSUE TITLE
[Bug]: 上传了图片返回地址错误

### ISSUE THREAD

**Issue by LCG0214** [Molunerfinn/PicGo#1228]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [X] [Issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)

### PicGo的版本 | PicGo Version

2.3.1

### 系统信息 | System Information

Windows

### 问题重现 | Bug reproduce

使用插件 设置了多级的文件路径 返回的url地址错误：
![image](https://github.com/Molunerfinn/PicGo/assets/71062757/2372528c-83b6-4a8f-8f9b-b7b0d215375a)

这个设置了
![image](https://github.com/Molunerfinn/PicGo/assets/71062757/421f1f5b-def5-4a35-957f-fbc9399f8048)
z这样的路径 ，返回的路径不对 导致相册也是空的

**Comment by LCG0214** [comment]
![image](https://github.com/Molunerfinn/PicGo/assets/71062757/528ea0ee-f48d-4d53-aa6f-494fc95bd35f)

**Comment by LCG0214** [comment]
![image](https://github.com/Molunerfinn/PicGo/assets/71062757/3393f0d3-6ce6-4618-b20a-1949abb8433d)
使用的这个插件

**Comment by Molunerfinn** [comment]
请去这个插件的仓库反馈
