### ISSUE TITLE
[Bug Report] svg图片格式不支持剪贴板快捷键上传吗

### ISSUE THREAD

**Issue by liuchuo** [Molunerfinn/PicGo#123]
## 问题类型

您好，感谢您开发这么好用的图床工具，我主要用来上传.svg格式的图片，直接拖动到菜单栏是可以上传的，但是如果是拷贝图片到剪贴板然后cmd+shift+P快捷键上传就会被提示“剪贴板的最新一条记录不是图片”，不知是我操作不对还是什么原因～

## PicGo的相关信息
v1.6.2
Mac平台

## 功能请求

---

**Comment by Molunerfinn** [comment]
@liuchuo 剪贴板图片只支持png格式上传——如果是jpg、png、gif等非矢量图都会被转换成png格式上传。如果是svg这种矢量图将无能为力，这是electron和操作系统的限制，很抱歉~

所以如果要上传svg请使用拖拽上传。剪贴板上传只是用来快速上传位图的。
