### ISSUE TITLE
[Bug]: mac M2 使用dmg或者brew安装后，打不开，提示文件损坏

### ISSUE THREAD

**Issue by wuwenrui** [Molunerfinn/PicGo#1230]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [X] [Issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)

### PicGo的版本 | PicGo Version

2.3.1

### 系统信息 | System Information

Mac

### 问题重现 | Bug reproduce

mac安装后打开报错：
<img width="260" alt="image" src="https://github.com/Molunerfinn/PicGo/assets/20716568/d3becb59-bfe4-4417-8280-ec502814fedb">

**Comment by Molunerfinn** [comment]
<img width="521" alt="image" src="https://github.com/Molunerfinn/PicGo/assets/12621342/f749569a-f27c-4c8e-907d-caf0c4192e43">
看过 FAQ 么
