### ISSUE TITLE
[Feature]: 希望增加一个删除图片后，自动删除远程图床的图片功能

### ISSUE THREAD

**Issue by wuwenrui** [Molunerfinn/PicGo#1231]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [X] [Issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)

### PicGo的版本 | PicGo Version

2.3.1

### 系统信息 | System Information

Mac(arm64)

### 功能请求 | Feature request

图床使用阿里云oss，可否增加一个配置，删除图片时，自动删除远程存储空间图片的功能

**Comment by Molunerfinn** [comment]
看 faq。如果有需求可以搜索 piclist
