### ISSUE TITLE
[Bug]: smms和imgur的图上传之后，无法显示

### ISSUE THREAD

**Issue by justincnn** [Molunerfinn/PicGo#1233]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [X] [Issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)

### PicGo的版本 | PicGo Version

Version: 2.4.0-beta.6

### 系统信息 | System Information

Mac(arm64)

### 问题重现 | Bug reproduce

github搭建的临时图床没有问题，

但是smms和imgur的不行，

![](https://cdn.jsdelivr.net/gh/justincnn/pictures/img/202404050849247.png)

**Comment by Molunerfinn** [comment]
无法显示不是picgo的问题是你网络的问题。
