### ISSUE TITLE
[Bug]: 插件安装均失败

### ISSUE THREAD

**Issue by justincnn** [Molunerfinn/PicGo#1234]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [X] [Issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)

### PicGo的版本 | PicGo Version

2.4.0-beta.6

### 系统信息 | System Information

Windows

### 问题重现 | Bug reproduce

所有库里的插件安装均提示如下的错误：

![](https://s2.loli.net/2024/04/05/DrO3x7yzUYApaBR.png)

**Comment by Molunerfinn** [comment]
看起来是权限不够没法创建文件夹。可以尝试手动到插件目录用命令行手动安装插件试试呢
