### ISSUE TITLE
[Bug]: 同一图床多个配置时，GUI 界面无法下滑

### ISSUE THREAD

**Issue by TinySnow** [Molunerfinn/PicGo#1237]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [X] [Issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)

### PicGo的版本 | PicGo Version

v2.4.0-beta6

### 系统信息 | System Information

Windows

### 问题重现 | Bug reproduce

为一个图床创建多个配置时（8 个以上）会出现图床设置无法下滑的情况。
无法下滑创建新的配置，同时无法点击本应在最底部的“设为默认图床”按钮。
详情如图。
![PixPin_2024-04-18_22-00-09](https://github.com/Molunerfinn/PicGo/assets/56748295/a496f73a-6d93-4fc2-99be-71457cbb99b6)

### 相关日志 | Logs

GUI 问题，无 Log。

**Comment by Molunerfinn** [comment]
感谢反馈 这里会尽快修复

**Comment by Molunerfinn** [comment]
已修复，这两天会发个新的 beta 版本

**Comment by Molunerfinn** [comment]
已发布 
beta.7
