### ISSUE TITLE
[Bug]: nsis写入注册表右键菜单问题

### ISSUE THREAD

**Issue by linavaos** [Molunerfinn/PicGo#1240]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [X] [Issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)

### PicGo的版本 | PicGo Version

v2.3

### 系统信息 | System Information

Windows

### 问题重现 | Bug reproduce

非常不好意思啊，最近在学习electron，看到您之前写过写过相关教程，windows系统级别的菜单，这里遇到一个问题就是用electron-builder 指定nsis脚本位置写入注册表。在windows中安装必须以管理员身份安装才能显示菜单（写入注册表）。非管理员方式不可以安装。

### 相关日志 | Logs

无

**Comment by Molunerfinn** [comment]
这个我也无法解答，我也要谷歌才知道，请自行搜索相关答案或者去 electron builder 仓库提问
