### ISSUE TITLE
[Feature]: 添加自动同步配置

### ISSUE THREAD

**Issue by findwei** [Molunerfinn/PicGo#1241]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [X] [Issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)

### PicGo的版本 | PicGo Version

v2.4.0-beta.7

### 系统信息 | System Information

Windows

### 功能请求 | Feature request

当前使用疼点：
配置了多个平台的图床相关配置，更换客户端后需要重新配置或者在更换之前导出具体某一个平台的配置（二维码形式）

希望大佬们你们考虑加入下面的功能：自动同步配置
在软件设置里面配置一个平台图床，当修改图床设置里面的配置，自动将当前配置过的图床配置生成二维码上传到之前在软件设置里面设置的图床平台上。当我使用其他客户端或者更换客户端的时候只需要安装软件后，在软件设置里面配置一下之前生成二维码配置平台的图床链接，实现自动同步当前的配置。

感谢大佬们提供这么好用的工具

**Comment by Molunerfinn** [comment]
配置同步这个功能，会以插件的形式提供
