### ISSUE TITLE
[Feature]: 上传前确认是否上传的功能或插件

### ISSUE THREAD

**Issue by lxiiiixi** [Molunerfinn/PicGo#1242]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [X] [Issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)

### PicGo的版本 | PicGo Version

v2.3.1

### 系统信息 | System Information

Mac(arm64)

### 功能请求 | Feature request

我希望在添加一个功能或插件，在每次图片上传之前，能够弹出一个确认对话框，询问是否确认上传该图片。

当前我使用的场景是，使用 PicGo 作为图片上传的服务器，并在 markdown 编辑器中设置了粘贴自动上传，但有的时候会手误粘贴了原本不打算上传的图片。希望可以在每次上传前都能有一个确认步骤。

希望能够找到一个合适的插件或在 PicGo 中直接集成这一功能，谢谢！

**Comment by Molunerfinn** [comment]
这个功能插件即可实现，后续有时间我可以实现一个
