### ISSUE TITLE
更换电脑后，重新配置picgo 历史图片找不到了[Bug]: 

### ISSUE THREAD

**Issue by 6YoungHome** [Molunerfinn/PicGo#1244]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [X] [Issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)

### PicGo的版本 | PicGo Version

v2.4.0-beta.6

### 系统信息 | System Information

Windows

### 问题重现 | Bug reproduce

反正就是更换电脑后，重新配置picgo 历史图片找不到了，但是历史链接可以访问，在picgo中的相册看不到图片

### 相关日志 | Logs

反正就是更换电脑后，重新配置picgo 历史图片找不到了，但是历史链接可以访问，在picgo中的相册看不到图片

**Comment by Molunerfinn** [comment]
picgo没有同步的功能 所有的相册记录都是本地存储记录，如果需要看到相册需要把你之前电脑的picgo的相册文件复制一份过来。相册文件是什么请看文档。

**Comment by 6YoungHome** [comment]
检查发现配置也有些问题，日志信息如下：
![image](https://github.com/Molunerfinn/PicGo/assets/76726577/c8dcde5d-8746-47e0-84bc-e0369b4715b5)
然后我访问里面的链接：
https://api.github.com/repos/https://github.com/6YoungHome/cdn2/contents/%E5%B1%8F%E5%B9%95%E6%88%AA%E5%9B%BE%202024-05-27%20161933.png

链接返回：
{
    "message": "API rate limit exceeded for 38.207.137.254. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)",
    "documentation_url": "https://docs.github.com/rest/overview/resources-in-the-rest-api#rate-limiting"
}

求问！！！！

**Comment by Molunerfinn** [comment]
这个报错信息你自己搜一下啊 这个是 github 服务端返回的 说明你请求次数超过它的频率限制了 跟 picgo 没关系
