### ISSUE TITLE
[Bug]: 安装插件一直失败，下载的包导入也失败，用管理员权限安装也失败

### ISSUE THREAD

**Issue by 543128533** [Molunerfinn/PicGo#1245]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [X] [Issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)

### PicGo的版本 | PicGo Version

v2.4.0

### 系统信息 | System Information

Windows

### 问题重现 | Bug reproduce

安装或导入都是直接报错乱码，日志信息就是一行乱码。下载了源码看了也没有找到具体位置。希望能解决一下谢谢
![1717118957507](https://github.com/Molunerfinn/PicGo/assets/65695008/87df35e8-ef46-4ae4-839b-94b530931064)

### 相关日志 | Logs

[picgo.log](https://github.com/user-attachments/files/15507367/picgo.log)

**Comment by Molunerfinn** [comment]
https://langjialing.com/archives/npminstallbao-cuo-npmerrcode1jie-jue

你可以进入picgo日志所在目录，然后在目录里，手动通过命令行比如 `npm install picgo-plugin-gitee` 安装插件，然后看看命令行报的具体错误是啥

这个通常跟你的 node 环境有关系，并不是 picgo 能控制的
