### ISSUE TITLE
[Feature]: 

### ISSUE THREAD

**Issue by kangyouwei111** [Molunerfinn/PicGo#1246]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [X] [Issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)

### PicGo的版本 | PicGo Version

v2.4.0-beta 7

### 系统信息 | System Information

Windows

### 功能请求 | Feature request

希望可以在picGo的相册内增加删除并同步到远程（即也可以将远端仓库的图片一并删除）功能。
![image](https://github.com/Molunerfinn/PicGo/assets/62366387/3a119f23-2cd1-4c6e-abcb-c796e0831e75)

**Comment by Molunerfinn** [comment]
插件可实现 本体不做
