### ISSUE TITLE
[Bug]: Mac OS下载后提示

### ISSUE THREAD

**Issue by YassinYin** [Molunerfinn/PicGo#1247]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [X] [Issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)

### PicGo的版本 | PicGo Version

2.4.0-beta.7

### 系统信息 | System Information

Mac(arm64)

### 问题重现 | Bug reproduce

下载PicGo-2.4.0-beta.7-arm64.dmg包进行安装之后，提示包损坏，无法打开
<img width="577" alt="image" src="https://github.com/Molunerfinn/PicGo/assets/152459711/e4cfdbbd-a968-4f6b-9ede-c47d1c3913d3">

**Comment by Molunerfinn** [comment]
请问你真的看过这个么
<img width="756" alt="image" src="https://github.com/Molunerfinn/PicGo/assets/12621342/331d3cec-f405-4977-bbba-b9c8d16c3378">
