### ISSUE TITLE
[Feature]: 自定义储存路径

### ISSUE THREAD

**Issue by alpha-baby** [Molunerfinn/PicGo#1249]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [X] [Issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)

### PicGo的版本 | PicGo Version

v2.4.0-beta7

### 系统信息 | System Information

Mac(arm64)

### 功能请求 | Feature request

支持类似 uPic 这种自定义路径的功能吗？
![image](https://github.com/Molunerfinn/PicGo/assets/47237632/4e9e6067-4afb-4848-8a88-9ae84ed66a55)

**Comment by Molunerfinn** [comment]
支持 如果需要变量的路径 可以找已有的插件 已经支持。
