### ISSUE TITLE
[Bug]: 无法上传至阿里云oss，已按教程一步步配置

### ISSUE THREAD

**Issue by Shuis004** [Molunerfinn/PicGo#1250]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [X] [Issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)

### PicGo的版本 | PicGo Version

v2.3.1

### 系统信息 | System Information

Windows

### 问题重现 | Bug reproduce

感觉我这个问题应该有很多人出现过，我也看了很多错误示范反复检查，但就是无法正常运行，很抱歉打扰到作者，烦请作者帮我看看问题出现在哪里🥹。
按照步骤一步步设置，但就是无法成功上传图片。阿里云oss配置如下
![Screenshot 2024-06-06 233112](https://github.com/Molunerfinn/PicGo/assets/119423302/61261893-792b-4a24-b9ad-d4473cd404cb)
日志显示403，但我反复检查了KeyId和KeySecret，我是从阿里云oss下载的用户信息csv文件中直接复制粘贴的，应该不会出错的呀。甚至我从obsidian中已经成功运行的remotely-save插件里复制了同样的id和secret，也还是无法上传。
![image](https://github.com/Molunerfinn/PicGo/assets/119423302/b7df0913-6c7e-49f7-acae-2687ffe1950c)

### 相关日志 | Logs

2024-06-06 23:45:33 [PicGo ERROR] {
  "method": "PUT",
  "url": "https://lidddpic.oss-cn-shenzhen.aliyuncs.com/Screenshot%202023-11-05%20105620.png",
  "statusCode": 403,
  "message": "Request failed with status code 403",
  "stack": {},
  "response": {
    "status": 403,
    "statusCode": 403,
    "body": "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Error>\n  <Code>AccessDenied</Code>\n  <Message>You have no right to access this object because of bucket acl.</Message>\n  <RequestId>6661D99C9935E338390F6F6B</RequestId>\n  <HostId>lidddpic.oss-cn-shenzhen.aliyuncs.com</HostId>\n  <EC>0003-00000001</EC>\n  <RecommendDoc>https://api.aliyun.com/troubleshoot?q=0003-00000001</RecommendDoc>\n</Error>\n"
  }
}

**Comment by Molunerfinn** [comment]
应该是你的上传的文件名里含有转义字符 尝试勾选时间戳重命名再上传试试

**Comment by Shuis004** [comment]
> 应该是你的上传的文件名里含有转义字符 尝试勾选时间戳重命名再上传试试

你好，我勾选了，但还是无法上传呀？怎么回事呢，而且还是403错误
2024-06-07 08:52:02 [PicGo ERROR] {
  "method": "PUT",
  "url": "https://lidddpic.oss-cn-shenzhen.aliyuncs.com/202406070852293.png",
  "statusCode": 403,
  "message": "Request failed with status code 403",
  "stack": {},
  "response": {
    "status": 403,
    "statusCode": 403,
    "body": "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Error>\n  <Code>AccessDenied</Code>\n  <Message>You have no right to access this object because of bucket acl.</Message>\n  <RequestId>666259B2E144DC3038037541</RequestId>\n  <HostId>lidddpic.oss-cn-shenzhen.aliyuncs.com</HostId>\n  <EC>0003-00000001</EC>\n  <RecommendDoc>https://api.aliyun.com/troubleshoot?q=0003-00000001</RecommendDoc>\n</Error>\n"
  }
}

**Comment by Molunerfinn** [comment]
那就是你的配置项有问题，导致签名校验不过。可以打开配置文件 看看key 或者 secrect 有没有多个空格之类的

**Comment by Shuis004** [comment]
我已经检查了超级多遍了🥹。重复地复制粘贴，就是不行。

**Comment by zxuexingzhijie** [comment]
我也跟你一样的问题,老哥,我快痛苦死了,昨天还可以用,今天一上午发现就不行了,我也没改任何东西

**Comment by zxuexingzhijie** [comment]
> 我已经检查了超级多遍了🥹。重复地复制粘贴，就是不行。

现在老哥你解决了吗

**Comment by maojiaoyu** [comment]
这个问题是因为阿里云的OSS地址最后面还有“-lr”字段，如果按正常的（如"oss-cn-wuhan"）填写是无法成功上传的，必须填oss-cn-wuhan-lr
