### ISSUE TITLE
我应该如何更新PicGo版本

### ISSUE THREAD

**Issue by zhang-zhonggui** [Molunerfinn/PicGo#1252]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [X] [Issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)

### PicGo的版本 | PicGo Version

PicGo-Setup-2.4.0-beta.7 

### 系统信息 | System Information

Windows

### 问题重现 | Bug reproduce

当前版本PicGo-Setup-2.4.0-beta.6我想更新到PicGo-Setup-2.4.0-beta.7下载完毕,双击无反应,已管理员运行依旧不行,
我应该怎么样更新新的版本呢?
系统是win11 23H2 , node:16.20.2
![image](https://github.com/Molunerfinn/PicGo/assets/89518224/8ddaa900-8d2d-4f0e-8c55-5f06241aaa4a)

### 相关日志 | Logs

无

**Comment by Molunerfinn** [comment]
没有特殊限制，点击打不开可能要注意看下是不是被系统安全拦截了，因为 picgo 安装包没有签名。可以留意下系统安全软件或者通知

**Comment by zhang-zhonggui** [comment]
> 没有特殊限制，点击不开 注意看是不是被系统安全拦截了，因为picgo安装包没有签名。可以关注下系统安全软件或者通知

目前win11是强签名制,哪怕我关闭了火绒或者win11安全都不会出现提示,win也不会出现通知
目前我的解决办法就是打开一个md文件,然后配置上传服务,这样可以调用win的安装服务完成,安装或者更新.
![image](https://github.com/Molunerfinn/PicGo/assets/89518224/0a2e7024-8b45-4b3c-b055-b1cc38cb1d9b)
