### ISSUE TITLE
[Bug]: 设置上传前重命名，不进行上传，点x关闭后会提示上传成功

### ISSUE THREAD

**Issue by sharebravery** [Molunerfinn/PicGo#1253]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [X] [Issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)

### PicGo的版本 | PicGo Version

v2.4.0-beta.7

### 系统信息 | System Information

Windows

### 问题重现 | Bug reproduce

设置上传前重命名，不进行上传，点x关闭后会提示上传成功，这是错误的行为。

**Comment by Molunerfinn** [comment]
不好意思 picgo 没有中断上传的逻辑 点叉不是不上传而是不重命名
