### ISSUE TITLE
[Feature]: 调整picgo icons

### ISSUE THREAD

**Issue by Emtier** [Molunerfinn/PicGo#1256]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [X] [Issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)

### PicGo的版本 | PicGo Version

v2.4.0 b7

### 系统信息 | System Information

Mac(arm64)

### 功能请求 | Feature request

现在icons没有圆角矩形，不雅观，可以修改icons 
icons地址 https://cdn.jsdelivr.net/gh/Emtier/img@link/to/202406232319043.icns
已有版本可以直接在访达里找到picgo 右键 显示简介
直接把icons图标拉到简介的左上角原有图标位置即可
<img width="572" alt="1" src="https://github.com/Molunerfinn/PicGo/assets/166900875/27acde64-03a6-43ae-bda7-61d7270369da">
<img width="820" alt="2" src="https://github.com/Molunerfinn/PicGo/assets/166900875/9a16a537-ee39-4fea-967c-b57f6b76e188">

**Comment by Molunerfinn** [comment]
感谢，这个可以自定义
