### ISSUE TITLE
[Bug]: 上传失败，日志显示png url 有转义

### ISSUE THREAD

**Issue by qbmiller** [Molunerfinn/PicGo#1259]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [X] [Issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)

### PicGo的版本 | PicGo Version

v2.4.0-beta.7

### 系统信息 | System Information

Mac(arm64)

### 问题重现 | Bug reproduce

![image](https://github.com/Molunerfinn/PicGo/assets/7335567/e31904a6-de15-4a0c-817e-26fda67ae89a)
<img width="551" alt="image" src="https://github.com/Molunerfinn/PicGo/assets/7335567/de9785ed-49ce-431c-8d4b-13794099c793">
<img width="541" alt="image" src="https://github.com/Molunerfinn/PicGo/assets/7335567/c40b6dd4-ad52-41d2-90b9-7d93715a95d4">

macos 
一开始老版本2.3.1 也不行。好久没用，再用这样。报错后，更到最新也这错

### 相关日志 | Logs

2024-07-05 12:58:14 [PicGo INFO] Uploading... Current uploader is [tcyun] 
2024-07-05 12:58:45 [PicGo WARN] failed 
2024-07-05 12:58:45 [PicGo ERROR] {
  "method": "PUT",
  "url": "http://xxxx-xxxxxx.cos.ap-beijing.myqcloud.com/blog%2F2024%2F07c956c9c0eda692863279669625bf47df.png",
  "statusCode": 0,
  "message": "read ETIMEDOUT",
  "stack": "Error: read ETIMEDOUT\n    at TCP.onStreamRead (node:internal/stream_base_commons:220:20)",
  "response": {
    "status": 0,
    "statusCode": 0,
    "body": ""
  }
} 
2024-07-05 12:58:45 [PicGo ERROR] {
  "method": "PUT",
  "url": "http://xxxxx-xxxx.cos.ap-beijing.myqcloud.com/blog%2F2024%2F07c956c9c0eda692863279669625bf47df.png",
  "statusCode": 0,
  "message": "read ETIMEDOUT",
  "stack": "Error: read ETIMEDOUT\n    at TCP.onStreamRead (node:internal/stream_base_commons:220:20)",
  "response": {
    "status": 0,
    "statusCode": 0,
    "body": ""
  }
}

**Comment by Molunerfinn** [comment]
这个转义不是 picgo 做的，是你的插件做的

**Comment by qbmiller** [comment]
> 这个转义不是 picgo 做的，是你的插件做的

自动用picgo就用这个插件。 原先一直是{hash} .改成hash也会转移。 
picgo配置成blog +插件配置{hash}也不管用。这插件可是4-5年没更新了。 https://github.com/liuwave/picgo-plugin-rename-file

**Comment by Molunerfinn** [comment]
picgo有更新 插件没更新的话有些是无法适配的 请去插件仓库反馈

**Comment by qbmiller** [comment]
> picgo有更新 插件没更新的话有些是无法适配的 请去插件仓库反馈

感谢，辛苦作者！
