### ISSUE TITLE
功能请求请求添加更多图床

### ISSUE THREAD

**Issue by lan542662** [Molunerfinn/PicGo#126]
## 功能请求

* 首先是windows有黑屏的情况.
* imgur的clientid官方不可用.
* 期待添加postimage(没有被墙,速度还是不错的),国外有这个和imgur基本足够了.

---

**Comment by Molunerfinn** [comment]
![image](https://user-images.githubusercontent.com/12621342/47126304-84e2b480-d2ba-11e8-97a7-377e8ce15990.png)
clientid不可用是因为imgur墙了国内ip，你需要设置proxy。

**Comment by lan542662** [comment]
> ![image](https://user-images.githubusercontent.com/12621342/47126304-84e2b480-d2ba-11e8-97a7-377e8ce15990.png)
> clientid不可用是因为imgur墙了国内ip，你需要设置proxy。

好了.果然是这样.不让上传的但能看.
