### ISSUE TITLE
[Bug]: 2.4.0beta7的arm64.dmg版本每次上传图片的时候都会弹出pigGo的整个界面

### ISSUE THREAD

**Issue by sxs123-m** [Molunerfinn/PicGo#1260]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [X] [Issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)

### PicGo的版本 | PicGo Version

v2.4.0-beta7

### 系统信息 | System Information

Mac(arm64)

### 问题重现 | Bug reproduce

每次上传图片的时候都会弹出pigGo的整个界面，如果mac是全屏，则会被挤掉，只能切屏，这是bug还是就这样设置的？

**Comment by Molunerfinn** [comment]
<img width="604" alt="image" src="https://github.com/Molunerfinn/PicGo/assets/12621342/a47eb1c8-9e57-4ceb-b68a-765b0767d2b1">
如果不想弹出请关闭 `显示 Dock 栏图标` 这个设置
