### ISSUE TITLE
[Bug]: 点击剪切板上传没有反应

### ISSUE THREAD

**Issue by Veng0923** [Molunerfinn/PicGo#1261]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [X] [Issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)

### PicGo的版本 | PicGo Version

V2.3.1

### 系统信息 | System Information

Linux

### 问题重现 | Bug reproduce

我的系统是ubuntu22.04, 用的是 wayland显示，点击粘贴板上传是无效的，但是切换到xorg显示就没有问题

### 相关日志 | Logs

点击后没有新增日志, 问题是必现的

**Comment by Molunerfinn** [comment]
没有linux系统 没法排查 可以看看picgo的剪贴板脚本

**Comment by lvxianchao** [comment]
Inter 版本 Mac 也一样

**Comment by lvxianchao** [comment]
> Inter 版本 Mac 也一样

我查看了日志发现这一段：

```
------Error Stack Begin------
Error: ENOENT: no such file or directory, open '/Users/lvxc/Library/Application Support/picgo/picgo-clipboard-images/202407221346211.png.1503464999'
-------Error Stack End------- 
```

然后我去到 `/Users/lvxc/Library/Application Support/picgo` 这个路径下，发现 `picgo-clipboard-images` 这个文件夹不存在，于是我创建了一个，It works!

**Comment by JARVNM** [comment]
Ubuntu22下最新版就好了。Download this latest version.

**Comment by happy-game** [comment]
> 没有linux系统 没法排查 可以看看picgo的剪贴板脚本

问题出在[上传脚本](https://github.com/Molunerfinn/PicGo/blob/dacb926f177f6ad3ad09b10841b7cc055e25144d/public/linux.sh#L21)
```bash
filePath=`wl-copy -o 2>/dev/null | grep ^file:// | cut -c8-`
```
在`wayland`中一般使用 `wl-clipboard`来管理剪切版, 它包含 `wl-copy`和`wl-paste`两个命令行工具, 它的`Manual`部分如下:
> DESCRIPTION
>       wl-copy copies the given text to the Wayland clipboard.  If no text is given, wl-copy copies data from its standard input.
>       wl-paste pastes data from the Wayland clipboard to its standard output.

在原脚本中 `wl-copy`实际在等待标准输出的内容, 所以在这里卡住了, 导致点击剪切版上传没有反应.
正确的做法应该是使用`wl-paste`.

**Comment by ishuangdigan** [comment]
> > Inter 版本 Mac 也一样
> 
> 我查看了日志发现这一段：
> 
> ```
> ------Error Stack Begin------
> Error: ENOENT: no such file or directory, open '/Users/lvxc/Library/Application Support/picgo/picgo-clipboard-images/202407221346211.png.1503464999'
> -------Error Stack End------- 
> ```
> 
> 然后我去到 `/Users/lvxc/Library/Application Support/picgo` 这个路径下，发现 `picgo-clipboard-images` 这个文件夹不存在，于是我创建了一个，It works!

我是mac系统，也按照你的方法解决了这个问题！
