### ISSUE TITLE
[Bug]: 插件在线安装完成之后，显示已安装，但是没办法使用

### ISSUE THREAD

**Issue by jackcheng321321** [Molunerfinn/PicGo#1262]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [X] [Issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)

### PicGo的版本 | PicGo Version

2.4.0-beat。7

### 系统信息 | System Information

Windows

### 问题重现 | Bug reproduce

![image](https://github.com/Molunerfinn/PicGo/assets/122415449/1b40dc86-136f-44ea-a032-905e8ea4d9fd)
S3插件安装之后，显示已安装，但是没办法使用，日志中也提示安装成功

**Comment by Molunerfinn** [comment]
怎么个没法使用？ 已安装后的插件有问题请去插件仓库反馈

**Comment by WooAooW** [comment]
我也遇到这个了，请问解决了吗？
