### ISSUE TITLE
[Bug]: can't upload via clipboard because picgo-clipboard-images dir missing

### ISSUE THREAD

**Issue by huahuayu** [Molunerfinn/PicGo#1263]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [X] [Issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)

### PicGo的版本 | PicGo Version

v2.3.1

### 系统信息 | System Information

Mac(arm64)

### 问题重现 | Bug reproduce

1. Download & install version 2.3.1
2. Setup AWS S3 storage
3. Can't upload via clipboard
4. Check the log, it is said can't find the dir `picgo-clipboard-images`
5. After manual create `picgo-clipboard-images` in `~/Library/Application Support/picgo/` it works.

### 相关日志 | Logs

```
------Error Stack Begin------
Error: ENOENT: no such file or directory, open '~/Library/Application Support/picgo/picgo-clipboard-images/202407140033594.png.3272010221'
-------Error Stack End------- 
```

**Comment by Molunerfinn** [comment]
You can use picgo toolbox to check and fix
<img width="273" alt="image" src="https://github.com/user-attachments/assets/7341e303-97a5-4865-8d92-fa20011dfdbb">
<img width="778" alt="image" src="https://github.com/user-attachments/assets/f6ecd626-aa3a-4bcc-8410-ac76826d6c9b">
