### ISSUE TITLE
[Feature]: 有个多个账号的配置,目前只能填一个,不方便切换

### ISSUE THREAD

**Issue by qq471754603** [Molunerfinn/PicGo#1268]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [X] [Issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)

### PicGo的版本 | PicGo Version

2.3.1

### 系统信息 | System Information

Mac

### 功能请求 | Feature request

[Feature]: 有个多个账号的配置,目前只能填一个,不方便切换

**Comment by qq471754603** [comment]
有个多个账号的配置,目前只能填一个,不方便切换,每次都要填一遍遍

**Comment by Molunerfinn** [comment]
beta 版本早已能支持多配置切换
