### ISSUE TITLE
不能看到上传区的照片

### ISSUE THREAD

**Issue by lan542662** [Molunerfinn/PicGo#127]
## 问题重现
看上传得照片是这个样子的.没有缩略预览,点进去也看不到.
![不能看到图片](https://img.vim-cn.com/91/da0de4040b92e8471857a15672b753700f572a.png "不能看到图片")
![点击也不能预览](https://img.vim-cn.com/0d/c0b49f8670a89c3f45d0d0fed657927e73f9a9.png "点击也不能预览")
*感谢,很方便*

---

**Comment by Molunerfinn** [comment]
请问你用的是哪个图床...信息全一点也好帮你解决问题啊

**Comment by lan542662** [comment]
> 请问你用的是哪个图床...信息全一点也好帮你解决问题啊
[^^]:
抱歉抱歉,我以为都是这样的.是7牛图床

**Comment by Molunerfinn** [comment]
那请你好好看看FAQ，发issue前就有提示了吧？
![image](https://user-images.githubusercontent.com/12621342/47126681-346c5680-d2bc-11e8-8f93-80970e810e6c.png)
![image](https://user-images.githubusercontent.com/12621342/47126689-3a623780-d2bc-11e8-9f51-425adb46a90b.png)

**Comment by lan542662** [comment]
好的,谢谢.我是加了的.重启后来的可以,.

**Comment by Molunerfinn** [comment]
@lan542662 之前未显示的你可以通过编辑，把前缀加回去：
![image](https://user-images.githubusercontent.com/12621342/47126793-cf653080-d2bc-11e8-905f-22f69baeb255.png)

**Comment by lan542662** [comment]
> @lan542662 之前未显示的你可以通过编辑，把前缀加回去：
> ![image](https://user-images.githubusercontent.com/12621342/47126793-cf653080-d2bc-11e8-905f-22f69baeb255.png)

好的,非常感谢.另外有个小问题,imgur我上传了.在自己的账户里看不到上传了的图片.

**Comment by Molunerfinn** [comment]
对，imgur那个是类似微博图床一样的匿名上传。

**Comment by lan542662** [comment]
> 对，imgur那个是类似微博图床一样的匿名上传。

好的,期待有个不匿名的国外,比如postimage.很棒,我这里没有墙.^^

**Comment by Molunerfinn** [comment]
其他的图床就靠2.0出来后，有其他人写图床的插件支持了~

**Comment by lan542662** [comment]
> 其他的图床就靠2.0出来后，有其他人写图床的插件支持了~

great.谢谢开发如此好的软件.方便极了,期待2.0.^_^

**Comment by bluestarpin** [comment]
我使用的github图床也出现这个问题，picgo客户端相册显示不了，然后复制makedown链接也无法显示，之前我的github仓库是私有的，现在改为公开之后，也无法显示，但是我去github上复制图片的链接，就可以正常显示。不知道原因出在哪了，之前的issues-79是七牛云的，现在我的是github的，这个应当怎么解决呢？

**Comment by yhx1001** [comment]
> 我使用的github图床也出现这个问题，picgo客户端相册显示不了，然后复制makedown链接也无法显示，之前我的github仓库是私有的，现在替换公开之后，也无法显示，但是我去github上复制图片的链接，就可以正常显示。不知道原因出在哪了，之前的问题-79是七牛云的，现在我的是github的，这个可行怎么解决呢？

我的也一样，咋解决

**Comment by yhx1001** [comment]
> > 我使用的github图床也出现这个问题，picgo客户端相册显示不了，然后复制makedown链接也无法显示，之前我的github仓库是私有的，现在替换公开之后，也无法显示，但是我去github上复制图片的链接，就可以正常显示。不知道原因出在哪了，之前的问题-79是七牛云的，现在我的是github的，这个可行怎么解决呢？
> 
> 我的也一样，咋解决

你的解决了吗

**Comment by kktt007** [comment]
> 
> 
> > 我使用的github图床也出现这个问题，picgo客户端相册显示不了，然后复制makedown链接也无法显示，之前我的github仓库是私有的，现在替换公开之后，也无法显示，但是我去github上复制图片的链接，就可以正常显示。不知道原因出在哪了，之前的问题-79是七牛云的，现在我的是github的，这个可行怎么解决呢？
> 
> 我的也一样，咋解决

用别的图床，测试下看看呢，我就是加了http:// 然后就好了，一定要加前缀
