### ISSUE TITLE
[Feature]: 如果想Github图床能够支持自定义域名，我应该怎么做？

### ISSUE THREAD

**Issue by Carvin-Yu** [Molunerfinn/PicGo#1271]
### 前置阅读 | Pre-reading

- [x] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [X] [Issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)

### PicGo的版本 | PicGo Version

v2.3.0

### 系统信息 | System Information

Windows

### 功能请求 | Feature request

> 背景：
> 1 - 通过已知Issues，我了解到了PigGo-Electron已经完全支持`自定义域名`功能
> 2 - 通过PicGo-Core源码，我发现了这个功能在上传结束后替换URL: https://github.com/PicGo/PicGo-Core/blob/dev/src/plugins/uploader/github.ts#L42
>
> 3 - 我们公司花巨资买下了**Enterprise-Github**并部署在自己内网，所以有自己的域名，也就是我们默认的域名不是https://github.com/，而是https://xxx-github.company.com/

我想尝试把PicGo-Electron引入到我们公司里面来，然而很迷茫的事情是：

如何我想实现这个**域名的自定义**？(现在看了日志报错，因为默认连上去的是api.github.com，并非我们公司的api.xxx-github.company.com，预期使用后者才能上传图片到某个仓库的指定分支的目录)

有没有比较简单的方式，使得我们能够容易地引入PicGo？源码重新编译？还是有地方可以放开配置？。。。

**Comment by Molunerfinn** [comment]
写一个自定义插件即可。

**Comment by Carvin-Yu** [comment]
我通过看文档并修改好了：https://github.com/PicGo/PicGo-Core/blob/dev/src/plugins/uploader/github.ts#L42

如果想编译成一个windows可用的二进制文件的话，有没有推荐的打包方式？

![图片](https://github.com/user-attachments/assets/ab4146ff-8ef8-4d95-8716-1a88cf643b37)
