### ISSUE TITLE
[Feature]: picgo-server或许可以独立出来

### ISSUE THREAD

**Issue by yqs112358** [Molunerfinn/PicGo#1272]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [X] [Issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)

### PicGo的版本 | PicGo Version

v2.3.1

### 系统信息 | System Information

Linux

### 功能请求 | Feature request

类似picgo-server这种通过API上传图片获取URL的场景有相当大的需求，比如各种笔记软件、网页剪裁软件等都需要通过HTTP API上传图片到图床中。对于笔记软件来说，不同图床平台需要单独适配，而picgo正好有易于适配多种图床的优势。

目前server是整合在客户端中的，但是如果可以将server独立成单独的项目（可以视为一种“无头客户端”，把JS API封装成HTTP API），提供一些类似docker部署服务的方法，应该会非常受欢迎

有一些类似 #1170 之类的向server增加功能的请求，个人理解如果能将server单独抽出来成一个项目，可能更便于维护和完善功能

或者其实也可以把server功能整合到picgo-core cli工具中

**Comment by Molunerfinn** [comment]
这个用 nodejs 加上 picgo-core 就能实现，社区应该有一些类似的实现 不需要装 picgo 这么重的客户端

**Comment by yqs112358** [comment]
确实server这个功能是不太需要依赖整个客户端的，所以我感觉可以移到core里面，改成类似`picgo-core server`之类，可以简单部署运行的

**Comment by Molunerfinn** [comment]
core 里不会包含这个的。 不过是可以写个单独的 picgo server
