### ISSUE TITLE
[Bug]: macOS sonoma 提示已损坏

### ISSUE THREAD

**Issue by evlic** [Molunerfinn/PicGo#1273]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [X] [Issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)

### PicGo的版本 | PicGo Version

v2.4.0-beta-8

### 系统信息 | System Information

Mac

### 问题重现 | Bug reproduce

直接安装可复现

系统 14.2

fix: `sudo xattr -rd com.apple.quarantine /Applications/PicGo.app/`

**Comment by Molunerfinn** [comment]
重复issue faq 里已经说明了
