### ISSUE TITLE
[Bug]: 2.4.0-beta.8 阿里云上传了1000张图片之后软件反应很慢，这种是啥情况啊大佬，切换上传区，相册，picgo设置都反应很慢

### ISSUE THREAD

**Issue by wwwwwwsprite** [Molunerfinn/PicGo#1275]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [X] [Issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)

### PicGo的版本 | PicGo Version

2.4.0-beta.8

### 系统信息 | System Information

Windows

### 问题重现 | Bug reproduce

也不算是故障吧，就是软件上多了图片变慢了，望大佬能优化一下

**Comment by Molunerfinn** [comment]
内存占用问题；未来会考虑优化一下的，短期内如果你只用于上传不用怎么查看的话，直接删掉配置目录下 picgo.db，然后重启 picgo 即可

**Comment by wwwwwwsprite** [comment]
好的，谢谢大佬
