### ISSUE TITLE
[Bug]: MacOS VSCode 快捷键冲突

### ISSUE THREAD

**Issue by evlic** [Molunerfinn/PicGo#1276]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [X] [Issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)

### PicGo的版本 | PicGo Version

v2.4.0-beta-8

### 系统信息 | System Information

Mac(arm64)

### 问题重现 | Bug reproduce

platform: m2pro macOS Sonoma 14.7

自从某个时候开始 CMD shift + P 就不能在 VScode 中使用，直到使用全局快捷键注册检查工具

picgo 客户端注册的默认的快捷方式和 vscode 快捷面板冲突，且是默认行为，在有较多插件的情况下很难找到冲突，建议默认关闭全局键盘快捷方式

**Comment by julyfun** [comment]
几天前遇到 vscode 命令面板打不开的问题，同样定位到 PicGO 全局快捷键的问题。由于 Cmd / ctrl + shift + P 实在是太常用了，建议关闭全局快捷键或者修改键位

**Comment by Molunerfinn** [comment]
自行修改快捷键绑定或者禁用对应快捷键即可。 picgo 设置里有快捷键设置

**Comment by uniquejava** [comment]
终于找到元凶了.

**Comment by Molunerfinn** [comment]
新版已经修改默认快捷键为 cmd+shift+u
