### ISSUE TITLE
[Feature]: 

### ISSUE THREAD

**Issue by 1109008002** [Molunerfinn/PicGo#1279]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [X] [Issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)

### PicGo的版本 | PicGo Version

v2.3.0

### 系统信息 | System Information

Windows

### 功能请求 | Feature request

我有多个设备，共用一个r2存储桶，但是每个设备都只能显示本设备上传的图片，希望可以在picgo里面显示存储桶内的所有图片，感谢您

**Comment by Molunerfinn** [comment]
本体暂不考虑。相册同步未来会用插件支持
