### ISSUE TITLE
[Bug]: 点击图片不能复制图片链接

### ISSUE THREAD

**Issue by qq937728** [Molunerfinn/PicGo#1280]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [X] [Issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)

### PicGo的版本 | PicGo Version

2.4.0beta8

### 系统信息 | System Information

Mac

### 问题重现 | Bug reproduce

<img width="196" alt="image" src="https://github.com/user-attachments/assets/e6834ed5-b59b-475c-ad28-4df75722701a">
点击不能复制url

### 相关日志 | Logs

日志里没有错误

**Comment by Molunerfinn** [comment]
已修复，跟下个 beta 版本

**Comment by Molunerfinn** [comment]
https://github.com/Molunerfinn/PicGo/releases/tag/v2.4.0-beta.9
已发布，欢迎更新体验
