### ISSUE TITLE
[Bug]:使用腾讯云进行存储，无法读取存入相片

### ISSUE THREAD

**Issue by zyh778** [Molunerfinn/PicGo#1283]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [X] [Issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)

### PicGo的版本 | PicGo Version

v2.4.1 beta8

### 系统信息 | System Information

Windows

### 问题重现 | Bug reproduce

![image](https://github.com/user-attachments/assets/1268f93b-68dd-44d3-832c-f62f1e8e1e45)
如图，当上传图片后，无法读取已上传图片，使用的腾讯云子账户，相关读写权限已经打开
![image](https://github.com/user-attachments/assets/b38e40d7-e1d4-4739-9dd9-255d18d07da8)

**Comment by Molunerfinn** [comment]
这个请找腾讯云，picgo只负责上传

**Comment by zyh778** [comment]
好的谢谢
