### ISSUE TITLE
[Feature]: 希望增加多仓库的支持

### ISSUE THREAD

**Issue by fscarmen** [Molunerfinn/PicGo#1287]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [X] [Issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)

### PicGo的版本 | PicGo Version

PicGo -2.4.0-beta.8

### 系统信息 | System Information

Mac

### 功能请求 | Feature request

希望同一个github库的配置里能设置多个仓库，图片能随机上传到其中一个或者上传到所有的库，他们用逗号分隔开，共用同一个token、路径、用户名，如下图所示。
<img width="800" alt="image" src="https://github.com/user-attachments/assets/ff26ff5f-c46b-4ab3-a534-88d4dd6f8eb5">

**Comment by Molunerfinn** [comment]
picgo 支持同个图床多份配置。随机上传只需插件支持即可，实现很简单 上传前随机切换配置即可

**Comment by fscarmen** [comment]
> picgo 支持同个图床多份配置。随机上传只需插件支持即可，实现很简单 上传前随机切换配置即

感谢大佬的及时回复，我希望的效果是，设置好n个图床，上传时随机给我上传即可，不需要我手动切换配置的。请问现在有现成的插件吗？

**Comment by Molunerfinn** [comment]
这个暂时没有。不过插件可以实现，所以这个本体不会考虑。

一次性上传多个图床，这个本体会考虑开发
