### ISSUE TITLE
[Bug]: 插件设置页无法搜索到插件

### ISSUE THREAD

**Issue by owenleexiaoyu** [Molunerfinn/PicGo#1297]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [X] [Issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)

### PicGo的版本 | PicGo Version

v2.4.0-beta8

### 系统信息 | System Information

Mac

### 问题重现 | Bug reproduce

安装 picgo 后，在插件设置页，搜索插件，输入任何字符，都搜索不到插件

<img width="836" alt="image" src="https://github.com/user-attachments/assets/dba30e09-793e-4289-8f89-67de67133cf3">

![iShot_2024-12-02_10 38 21](https://github.com/user-attachments/assets/b5a7a304-4873-4813-a47e-65ba207d0fa4)

### 相关日志 | Logs

2024-12-02 10:27:22 [PicGo INFO] [PicGo Server] is listening at 36677 
2024-12-02 10:31:11 [PicGo INFO] [PicGo Server] shutdown 
2024-12-02 10:31:51 [PicGo INFO] [PicGo Server] is listening at 36677 
2024-12-02 10:31:51 [PicGo INFO] register builtin shortKey command: [picgo:upload] - [CommandOrControl+Shift+P] 
2024-12-02 10:31:51 [PicGo INFO] register builtin shortKey command: [picgo:upload] - [CommandOrControl+Shift+P] successfully 
2024-12-02 10:33:00 [PicGo INFO] [PicGo Server] is listening at 36677 
2024-12-02 10:33:00 [PicGo INFO] register builtin shortKey command: [picgo:upload] - [CommandOrControl+Shift+P] 
2024-12-02 10:33:00 [PicGo INFO] register builtin shortKey command: [picgo:upload] - [CommandOrControl+Shift+P] successfully

**Comment by ChenSino** [comment]
+1，使用梯子也搜不到

**Comment by marlonfan** [comment]
+1

**Comment by TFTree** [comment]
2.3.1稳定版也搜索不到插件

**Comment by Molunerfinn** [comment]
![image](https://github.com/user-attachments/assets/974d7dd6-bf53-47eb-9ba8-c35592b8eb9d)
npm 的接口看起来挂了

**Comment by Molunerfinn** [comment]
手动安装不受影响，可以先手动安装插件

**Comment by ChenSino** [comment]
> 手动安装不受影响，可以先手动安装插件
我可以访问接口也无法下载插件
![image](https://github.com/user-attachments/assets/a6ca6610-5455-453e-b69e-aeceaded32cb)
![image](https://github.com/user-attachments/assets/cdf00d99-b970-4885-9930-8c09c2d8f2d8)

**Comment by Molunerfinn** [comment]
看到了，npm 这个接口返回体的结构改了，导致无法正确获取数据。

我会尽快处理下
![image](https://github.com/user-attachments/assets/90fcf1f1-da61-48f5-b781-5e05aacd5a7b)

**Comment by Molunerfinn** [comment]
https://github.com/Molunerfinn/PicGo/releases/tag/v2.4.0-beta.9
已发布，欢迎更新体验

**Comment by NKU-ZiXuan** [comment]
> 手动安装不受影响，可以先手动安装插件
怎么手动安装，nmp install 手动安装也报错

**Comment by dayunnas** [comment]
> https://github.com/Molunerfinn/PicGo/releases/tag/v2.4.0-beta.9 已发布，欢迎更新体验

大佬，已升级2.4.0-beta9还是无法搜索到插件

**Comment by NKU-ZiXuan** [comment]
> > https://github.com/Molunerfinn/PicGo/releases/tag/v2.4.0-beta.9 已发布，欢迎更新体验
> 
> 大佬，已升级2.4.0-beta9还是无法搜索到插件

安装node.js 然后手动安装插件，我成功了

**Comment by kkl-1998** [comment]
> > https://github.com/Molunerfinn/PicGo/releases/tag/v2.4.0-beta.9 已发布，欢迎更新体验
> 
> 大佬，已升级2.4.0-beta9还是无法搜索到插件
+1，我的新版本也不行
npm手动安装插件包，然后这里本地导入
![image](https://github.com/user-attachments/assets/c0f5403c-0fd8-4e8a-a2f3-8127b87304a4)

**Comment by sundaying0** [comment]
> > > https://github.com/Molunerfinn/PicGo/releases/tag/v2.4.0-beta.9 已发布，欢迎更新体验https://github.com/Molunerfinn/PicGo/releases/tag/v2.4.0-beta.9
> > 
> > 
> > 大佬，已升级2.4.0-beta9还是无法搜索到插件
> > +1，我的新版本也不行
> > npm手动安装插件包，然后这里本地导入
> > ![image](https://private-user-images.githubusercontent.com/67861822/399159260-c0f5403c-0fd8-4e8a-a2f3-8127b87304a4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzYzODk1OTcsIm5iZiI6MTczNjM4OTI5NywicGF0aCI6Ii82Nzg2MTgyMi8zOTkxNTkyNjAtYzBmNTQwM2MtMGZkOC00ZThhLWEyZjMtODEyN2I4NzMwNGE0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAxMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMTA5VDAyMjEzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFlNjI5MWJkNDI2MmU2ZWQzZTkzN2IzMGU4NTYwYzFkNTMxZWZlNjAxOGEzZTlmNjBjNTMxYWVmYjlhNjE0OWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.bCCIg_A4UGNxsUJrD-iKYppWpWL5U4lugk6N8lzHF8M)

您好，能否指导下npm手动安装插件包具体怎么操作的，我导入好像不成功。。。

**Comment by guozhenyi** [comment]
> https://github.com/Molunerfinn/PicGo/releases/tag/v2.4.0-beta.9 已发布，欢迎更新体验

大佬，能发布一个 v2.3.2 正式版，去修复插件不能安装的问题么。v2.4 的正式版迟迟不出来，还不如先把 v2.3 修复一下。

**Comment by niaodian** [comment]
beta.9可以搜索到插件，但是安装失败，设备CPU是M4 Max

<img width="818" alt="Image" src="https://github.com/user-attachments/assets/e628cd90-9ea4-4c4f-a0fb-e915264682cf" />

**Comment by niaodian** [comment]
> beta.9可以搜索到插件，但是安装失败，设备CPU是M4 Max
> 
> <img alt="Image" width="818" src="https://private-user-images.githubusercontent.com/91940665/433014271-e628cd90-9ea4-4c4f-a0fb-e915264682cf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDQ0MzkwNTYsIm5iZiI6MTc0NDQzODc1NiwicGF0aCI6Ii85MTk0MDY2NS80MzMwMTQyNzEtZTYyOGNkOTAtOWVhNC00YzRmLWEwZmItZTkxNTI2NDY4MmNmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTA0MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwNDEyVDA2MTkxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTExNWY2ZTNjM2U2MGMxZDI1Zjc3MGI4MDEyMTNlMjUzNzE0YTNkNzBkNWI0NmFmZTA1MTNhZGMxMTg4N2Q4MmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.kVuRPoyJ8yho6RN1tt6b8CR0SBEZ3qsPd-XC0-rTrNQ">

日志：
```
2025-04-12 14:16:07 [PicGo ERROR] 
------Error Stack Begin------
Error: Cannot find module '/Users/xxx/Library/Application Support/picgo/node_modules/picgo-plugin-s3/dist/index.js'. Please verify that the package.json has a valid "main" entry
    at tryPackage (node:internal/modules/cjs/loader:360:19)
    at Function.Module._findPath (node:internal/modules/cjs/loader:573:18)
    at Module._resolveFilename (node:internal/modules/cjs/loader:926:27)
    at Function.n._resolveFilename (node:electron/js2c/browser_init:249:1128)
    at Module._load (node:internal/modules/cjs/loader:785:27)
    at Function.c._load (node:electron/js2c/asar_bundle:5:13331)
    at Module.require (node:internal/modules/cjs/loader:1012:19)
    at require (node:internal/modules/cjs/helpers:94:18)
    at Nt.getPlugin (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/picgo/dist/index.cjs.js:1:43922)
    at Nt.registerPlugin (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/picgo/dist/index.cjs.js:1:43045)
-------Error Stack End------- 
2025-04-12 14:16:07 [PicGo SUCCESS] 插件安装成功 
```

**Comment by niaodian** [comment]
> > beta.9可以搜索到插件，但是安装失败，设备CPU是M4 Max
> > <img alt="Image" width="818" src="https://private-user-images.githubusercontent.com/91940665/433014271-e628cd90-9ea4-4c4f-a0fb-e915264682cf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDQ0MzkwNTYsIm5iZiI6MTc0NDQzODc1NiwicGF0aCI6Ii85MTk0MDY2NS80MzMwMTQyNzEtZTYyOGNkOTAtOWVhNC00YzRmLWEwZmItZTkxNTI2NDY4MmNmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTA0MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwNDEyVDA2MTkxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTExNWY2ZTNjM2U2MGMxZDI1Zjc3MGI4MDEyMTNlMjUzNzE0YTNkNzBkNWI0NmFmZTA1MTNhZGMxMTg4N2Q4MmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.kVuRPoyJ8yho6RN1tt6b8CR0SBEZ3qsPd-XC0-rTrNQ">
> 
> 日志：
> 
> ```
> 2025-04-12 14:16:07 [PicGo ERROR] 
> ------Error Stack Begin------
> Error: Cannot find module '/Users/xxx/Library/Application Support/picgo/node_modules/picgo-plugin-s3/dist/index.js'. Please verify that the package.json has a valid "main" entry
>     at tryPackage (node:internal/modules/cjs/loader:360:19)
>     at Function.Module._findPath (node:internal/modules/cjs/loader:573:18)
>     at Module._resolveFilename (node:internal/modules/cjs/loader:926:27)
>     at Function.n._resolveFilename (node:electron/js2c/browser_init:249:1128)
>     at Module._load (node:internal/modules/cjs/loader:785:27)
>     at Function.c._load (node:electron/js2c/asar_bundle:5:13331)
>     at Module.require (node:internal/modules/cjs/loader:1012:19)
>     at require (node:internal/modules/cjs/helpers:94:18)
>     at Nt.getPlugin (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/picgo/dist/index.cjs.js:1:43922)
>     at Nt.registerPlugin (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/picgo/dist/index.cjs.js:1:43045)
> -------Error Stack End------- 
> 2025-04-12 14:16:07 [PicGo SUCCESS] 插件安装成功 
> ```

咨询Gemini Pro 2.5以后解决了：

## 重置 PicGo (作为最后手段):
- 备份你的 PicGo 配置文件 data.json (位于 /Users/xxx/Library/Application Support/picgo/)。这个文件包含了你的图床配置等信息。
- 完全退出 PicGo 应用 (Cmd + Q)。
- 删除整个 /Users/xxx/Library/Application Support/picgo/ 文件夹。
- 重新启动 PicGo，它会像首次安装一样运行。
- 尝试重新安装插件。
- 如果插件安装成功，可以尝试将备份的 data.json 文件放回原处（覆盖新生成的），但需注意这可能带回旧配置的问题。

**Comment by twiify** [comment]
更新beta9后还是没法搜索到插件，找到了一个picgo的可以试试，兼容大部分picgo插件。

[https://github.com/Kuingsmile/PicList/blob/dev/README_cn.md](https://github.com/Kuingsmile/PicList/blob/dev/README_cn.md)
