### ISSUE TITLE
[功能请求]: MAC arm64 系统 在PicGo设置打开提示上传功能

### ISSUE THREAD

**Issue by small-howe** [Molunerfinn/PicGo#1299]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [X] [Issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)

### PicGo的版本 | PicGo Version

2.4.0-beta.9

### 系统信息 | System Information

MAC ARM64

### 功能请求 | Feature request

![sp20241204_125511_008](https://github.com/user-attachments/assets/a96cae33-95a2-42ba-9490-d0e3429655da)
目前复制是有提示的，但是上传成功没有提示（Mac arm64）使用快捷键上传后 每次都需要点开小图标才知道上传成功，能否做个上传成功提示，目前设置里面的提示打开的，但是一直没提示，

**Comment by Molunerfinn** [comment]
你这个复制提示不是 picgo 的吧

**Comment by Molunerfinn** [comment]
![image](https://github.com/user-attachments/assets/69cad875-c48e-4ad4-982e-137cc85e9f0d)
上传成功提示一直是有的，如下图，我也是快捷键上传（macOS ARM64）。请自行检查是否没给 picgo 开放通知权限。
![PixPin_2024-12-04_14-53-37](https://github.com/user-attachments/assets/a580e3ce-6c76-422b-9b11-5195151cdaeb)

**Comment by small-howe** [comment]
好的 谢谢
