### ISSUE TITLE
上传图片带中文会导致上次失败

### ISSUE THREAD

**Issue by qsy1122** [Molunerfinn/PicGo#13]
上传到七牛云时出现这个问题，修改文件名后正常，其他平台未测试
平时会使用系统屏幕截图功能，默认文件名会有屏幕快照字样

**Comment by Molunerfinn** [comment]
1. 感谢发现的问题，之后我看看是不是七牛的限制
2. 截图到剪贴板里，这个时候是个图片但是并没有文件名。上传的话必须要有一个文件名，所以我就取了日期+时间作为默认文件名。这个不是bug，是个feature。

**Comment by Molunerfinn** [comment]
v1.2.1版本已经修复，欢迎下载体验~
