### ISSUE TITLE
Mac下打不开应用

### ISSUE THREAD

**Issue by cn-xufei** [Molunerfinn/PicGo#130]
## 问题类型
mac下dev或者build，应用的窗体都无法显示，dev下程序坞上有electron的图标。。。
这是环境问题？

## PicGo的相关信息

Mac Mojave
## 问题重现
![image](https://user-images.githubusercontent.com/14144811/47207162-1c303080-d3bd-11e8-9bf8-1cc29b95301a.png)

## 功能请求

---

**Comment by Molunerfinn** [comment]
mac下的主窗体是在顶部menubar右键->打开详细窗口。。
![image](https://user-images.githubusercontent.com/12621342/47207306-8052f480-d3bd-11e8-8f2e-33e3cb105e33.png)

**Comment by cn-xufei** [comment]
尴尬了，不好意思
