### ISSUE TITLE
[Bug]: 插件安装

### ISSUE THREAD

**Issue by Mathinas** [Molunerfinn/PicGo#1303]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [X] [Issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)

### PicGo的版本 | PicGo Version

2.4.0 beta9

### 系统信息 | System Information

Windows

### 问题重现 | Bug reproduce

真的很纳闷，老版本一个一个下了安装，搜不到插件，非得最新beta9才能搜达插件，但新版本搜到了又安装不上，一
<img width="453" alt="Snipaste_2024-12-12_11-34-11" src="https://github.com/user-attachments/assets/cd2a2979-92ba-4d68-b9a3-22659b425472" />
直安装中

### 相关日志 | Logs

-------Error Stack End------- 
2024-12-12 11:11:27 [PicGo ERROR] NPM is not installed 
2024-12-12 11:11:27 [PicGo ERROR] 插件安装失败，失败码为1，错误日志为 
 'npm' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���
���������ļ���

**Comment by Molunerfinn** [comment]
说明你系统里没有装node环境

**Comment by Mathinas** [comment]
装了node.js

**Comment by buzhidaojiaoshenm** [comment]
我也遇到了同样的问题，已经安装了node.js，还是安装不了sftp的插件，直接显示load error

**Comment by 7peanuts** [comment]
官方图床插件 1.0.0 是不是坏了啊，安装下到本地了，然后报错 load error，无法显示在插件列表里，安装了其它几个插件都没有问题。

**Comment by zhulir** [comment]
我也遇到了同样的问题，装了node,但是PicGo搜索不到插件，你们则ui后都解决了吗

**Comment by zhulir** [comment]
已经解决了，下载了beta9,更改nodejs中cache和global文件的权限就可以了
