### ISSUE TITLE
[Bug]: 下载完成后没有插件文件夹，插件设置搜索为空

### ISSUE THREAD

**Issue by Cuitongxue30** [Molunerfinn/PicGo#1304]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [X] [Issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)

### PicGo的版本 | PicGo Version

v2.3.0,v2.3.1

### 系统信息 | System Information

Windows

### 问题重现 | Bug reproduce

![image](https://github.com/user-attachments/assets/59054dae-ff27-4f0c-9c83-32794f0bfe5a)
![image](https://github.com/user-attachments/assets/d3e9dba2-6137-4754-a7e6-fdcb2316eb0b)
下载完软件之后，没有插件文件夹，软件内插件搜索不到

**Comment by Molunerfinn** [comment]
插件无法搜索的问题在2.4.0最新 beta 版本修复了
