### ISSUE TITLE
[求助]: 自定义输出 URL 模板里面的变量不知道怎么设置了. (┬＿┬)

### ISSUE THREAD

**Issue by immustard** [Molunerfinn/PicGo#1305]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [X] [Issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)

### PicGo的版本 | PicGo Version

v2.4.0-beta.9

### 系统信息 | System Information

Mac(arm64)

### 问题重现 | Bug reproduce

之前用的 v2.3.1, 自定义输出模板只填 host 就行了. 这个是 v2.4.0 新加的不.. 

上传文件路径: {year}/{month}/{md5}.{extName}
自定义输出 url 模板: 设置{md5}的话, 不会替换.. 应该怎么设置

**Comment by Molunerfinn** [comment]
picgo 默认的只有这几个
![image](https://github.com/user-attachments/assets/7e9080d6-b038-4544-9f52-45e41e81edcf)

你说的这些应该是某个插件提供的，请去插件仓库提问。

**Comment by immustard** [comment]
您好，您的邮件已经收到。

**Comment by immustard** [comment]
哦哦. 明白啦~ 情况是之前 `自定义输出模板` 只设置一个地址就行了. 后面会自动拼上文件的具体路径. 比如说, 之前只配置一个 www.baidu.com 就行了, 上传完之后会直接得到 www.baidu.com/1/2/image.png 地址.. 
具体的我去插件的地方问问.
