### ISSUE TITLE
[Bug]: mac下使用快捷键上传不行，使用快捷键后必须在点击一下软件才会开始上传，要不就是有延迟，延迟还挺严重

### ISSUE THREAD

**Issue by nuo010** [Molunerfinn/PicGo#1307]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [X] [Issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)

### PicGo的版本 | PicGo Version

2.3.1

### 系统信息 | System Information

Mac

### 问题重现 | Bug reproduce

<img width="800" alt="Snipaste_2024-12-27_10-02-25" src="https://github.com/user-attachments/assets/9de27d0e-9aaa-42ba-8f6d-384d1dcfc798" />

**Comment by Molunerfinn** [comment]
https://github.com/Molunerfinn/PicGo/issues/1031
更新 2.4.0 的 beta 版本，此前已经修复了

**Comment by nuo010** [comment]
可以了，谢谢，作者，我想知道上为啥，因为什么原因导致的
