### ISSUE TITLE
[Bug]: 上传后无法显示图片，打开浏览器访问报如下错误

### ISSUE THREAD

**Issue by bytelife7676** [Molunerfinn/PicGo#1308]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [X] [Issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)

### PicGo的版本 | PicGo Version

v2.4.0

### 系统信息 | System Information

Windows

### 问题重现 | Bug reproduce

This XML file does not appear to have any style information associated with it. The document tree is shown below.
  <Error> <Code>AccessDenied</Code> <Message>Access Denied.</Message> <Resource>/test/pexels-photo-29487999.jpeg</Resource> <RequestId>Njc2ZjdmYjFfMTJiMDI0MDlfZThiNF9hZDA5MTky</RequestId> <TraceId>OGVmYzZiMmQzYjA2OWNhODk0NTRkMTBiOWVmMDAxODc0OWRkZjk0ZDM1NmI1M2E2MTRlY2MzZDhmNmI5MWI1OWVjYTU1YTQxYjIzY2EyNTc2ZmY2NzFlOWU4NzBkOTFlMTNlY2NhMjg1YmYyMjU0YWVkZTE4M2Y5ZmExMTYzM2M=</TraceId> </Error>

**Comment by Molunerfinn** [comment]
什么图床？不能访问的图片链接是什么？

这里通常是你把图床权限设为私有 导致无法公开访问

**Comment by bytelife7676** [comment]
> 什么图床？无法访问的图片链接是什么？
> 
> 这里是你把图床权限设置为通常导致无法公开访问

确实是这个原因，由于我的cos设置为私有读写所以失效了，感谢大佬的解答
