### ISSUE TITLE
[Bug]: 我上传图片并不能成功，突然这样的。

### ISSUE THREAD

**Issue by 1060404996** [Molunerfinn/PicGo#1309]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [X] [Issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)

### PicGo的版本 | PicGo Version

2.40

### 系统信息 | System Information

Windows

### 问题重现 | Bug reproduce

拖拽上传图片过一会就没反应了，进度条到最后就红色一下就没有了。希望有大佬帮忙看下哪里问题？

### 相关日志 | Logs

2024-12-29 21:19:40 [PicGo ERROR] {
  "method": "PUT",
  "url": "https://api.github.com/repos/1060404996/my-pic/contents/img/logo_20231211_uugai.com_1702260845713.png",
  "statusCode": 0,
  "message": "connect ETIMEDOUT 20.205.243.168:443",
  "stack": "Error: connect ETIMEDOUT 20.205.243.168:443\n    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1146:16)",
  "response": {
    "status": 0,
    "statusCode": 0,
    "body": ""

**Comment by JasonDev324** [comment]
我的也是这样
