### ISSUE TITLE
七牛云无法上传

### ISSUE THREAD

**Issue by MyLeoLan** [Molunerfinn/PicGo#131]
## 问题类型
Bug
七牛云无法上传，用自己的域名也不行。

## PicGo的相关信息
Mac 1.6.2

## 问题重现
![12345](https://user-images.githubusercontent.com/18298528/47281064-dd43ea00-d60b-11e8-9654-1ac2f416d845.png)

**Comment by Molunerfinn** [comment]
这个跟域名没关系，域名设置只是用来最后url里显示的。请你看看你的secretKey等关键的密钥信息是不是填写正确，以及确认一下这些信息前后是不是有多一个空格之类的，很多人是复制粘贴的时候头或者尾多了一个空格。
我这边七牛上传是没问题的。

**Comment by ktjg** [comment]
同上问题  七牛云无法上传 确定As，Ks，正确
Gtk-Message: 00:30:17.725: GtkDialog mapped without a transient parent. This is discouraged.
[PicGo INFO]: Before transform
[PicGo INFO]: Transforming...
[PicGo INFO]: Before upload
[PicGo INFO]: Uploading...
failed
[PicGo ERROR]: TypeError: Cannot read property 'body' of undefined
(node:594) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'body' of undefined
    at Object.handle (/tmp/.mount_picgo-Xnr8si/resources/app.asar/node_modules/picgo/dist/plugins/uploader/qiniu.js:65:51)
(node:594) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:594) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by ktjg** [comment]
版本 2.04 
操作系统deepin

**Comment by Molunerfinn** [comment]
@ktjg  AS KS正确也不一定就没问题。你的bucket的名字也有可能错。
所以可以打开配置文件看看你的配置项是否都正确，有没有多一个空格或者少一个空格，有没有字母打错。我这边七牛上传是没问题的。

![image](https://user-images.githubusercontent.com/12621342/56082669-1425ea80-5e4e-11e9-8cd7-69ec1673afba.png)

**Comment by ktjg** [comment]
{
  "uploaded": [],
  "picBed": {
    "current": "qiniu",
    "qiniu": {
      "accessKey": "WySSwSENTA7YPkwFrrz0tZ2_w_8MVE6gmpm4PL42",
      "secretKey": "biqgf0MTP3OY260JGL_qtQEmKXny2P5rjXM6Hc-1",
      "bucket": "xysycx",
      "url": "http://xysycx.cn.qiniudns.com",
      "area": "z2",
      "options": "",
      "path": ""
    },
我还是无法上传 你可以测试一下我的配置信息有没有错

**Comment by Molunerfinn** [comment]
![image](https://user-images.githubusercontent.com/12621342/56087802-d99b6c80-5ea4-11e9-9845-611e3773957f.png)

**Comment by Molunerfinn** [comment]
你是截图上传的还是使用文件上传的？

**Comment by ktjg** [comment]
文件上传

**Comment by Molunerfinn** [comment]
这就很奇怪了，我这边上传是没问题的，你也看到了我用你的配置上传是OK的。看看是不是有什么代理的问题吧。

**Comment by ktjg** [comment]
我开了ssr 的问题么

**Comment by Molunerfinn** [comment]
可能是吧，我也不清楚具体的，这个跟你的网络环境有关系了。跟PicGo本身没关系了已经。配置是没问题的

**Comment by ktjg** [comment]
那不好意思 打扰了 应该是我自己的问题

**Comment by Molunerfinn** [comment]
嗯嗯，你得记得把你的这对密钥删掉，重新申请一对

**Comment by ktjg** [comment]
无法上传的原因是我之前改动了我localhost地址 127.0.0.1 改成了 127.0.0.0 改回来就行了

![](http://xysycx.cn/20190415221825.png)

**Comment by ktjg** [comment]
上图是正确配置
