### ISSUE TITLE
Linux 下 PicGo 的菜单栏图标显示

### ISSUE THREAD

**Issue by spencerwooo** [Molunerfinn/PicGo#133]
## 问题类型

Feature Request

## PicGo的相关信息

1.6.2 for Arch Linux，从 AUR 上面下载的 PicGo 版本。

## 功能请求

Linux 也有如 macOS 的菜单栏，希望也可以在菜单栏让 PicGo 有一席之地～这样我让 PicGo 常住后台，就可以实现拖拽上传了！:tada::tada::tada:

![image](https://user-images.githubusercontent.com/32114380/48062375-c81aae00-e1fc-11e8-8f39-c5d51cef726a.png)

**Comment by Molunerfinn** [comment]
@spencerwooo PicGo由于不同的发行版的行为不一致（比如Ubuntu的菜单栏能显示，但是并不能拖拽上传，因为electron官方对于Linux平台的Tray没有drag事件。而其他发行版有些则直接无法显示。）为了统一的操作习惯考虑，则改用了`迷你视窗`也就是`mini-window`的设定。

![image](https://user-images.githubusercontent.com/12621342/48062656-a0781580-e1fd-11e8-8207-cfb1a51a9f4a.png)

这样的好处是在Windows和Linux下都能有一个小窗口来替代macOS的菜单栏的icon，实现简易的拖拽上传区域，并且不挤占桌面空间。

PS：PicGo一开始只做了macOS版本，为了兼容Windows而做了主窗口；后来加了Linux版本，为了兼容Linux菜单栏不统一的问题而加入迷你视窗~

**Comment by spencerwooo** [comment]
原来如此...可惜了
