### ISSUE TITLE
[Feature Request] 关于上传图片前加上水印

### ISSUE THREAD

**Issue by Quorafind** [Molunerfinn/PicGo#134]
## 问题类型

Feature Request

## PicGo的相关信息

Pic v1.6.2、Mac

## 功能请求

想要给图片打上水印，这样写博客的时候会更为轻松。
预想的方式，是在图片中央或者左下角/右下角打上一个半透明的自主设定的文字或者logo

---

**Comment by Molunerfinn** [comment]
这个将交给插件去做。

**Comment by wqh8522** [comment]
> @wqh8522 目前还没人写，有兴趣可以用node-images写一个插件。

好吧，不会node

**Comment by Dec-F** [comment]
需要这个功能，有人着手实现了吗？没有的话，我可以试试 @Molunerfinn

**Comment by Molunerfinn** [comment]
> 需要这个功能，有人着手实现了吗？没有的话，我可以试试 @Molunerfinn

目前没有人做，可以试试！
