### ISSUE TITLE
[Bug Report]mac上下载了最新版的picGo，但是打不开

### ISSUE THREAD

**Issue by Kerminate** [Molunerfinn/PicGo#135]
## 功能请求

---

**Comment by Molunerfinn** [comment]
检查你的顶部栏。
![image](https://user-images.githubusercontent.com/12621342/48697886-b2f04700-ec20-11e8-9729-8bf5641bb86a.png)
使用前请看看文档。https://github.com/Molunerfinn/PicGo/wiki

**Comment by Kerminate** [comment]
看到了 尴尬

**Comment by tang1107** [comment]
我点击顶部蓝的小图标，没有任何反应啊

**Comment by Jimmylxue** [comment]
打不开 官网书用 homebrew 下载 好了以后打不开

**Comment by Jimmylxue** [comment]
无法打开“PicGo”，因为无法验证开发者。

**Comment by Jimmylxue** [comment]
macOS无法验证此App不包含恶意软件。
