### ISSUE TITLE
[Bug Report]  开启时间戳重命名，拖拽上传多张相同后缀图片，弹出的名称一样，希望优化。

### ISSUE THREAD

**Issue by jingyulong** [Molunerfinn/PicGo#136]
## 问题类型
Feature Request

## PicGo的相关信息
PicGo 版本：1.6.2
所在平台：Windows 10

## 问题重现
直接拖拽两个相同后缀的图片上传，文件名是一样的。
![](http://pij0ar5gi.bkt.clouddn.com/image/20181121161037.gif)

## 功能请求
希望自动优化成不同名称。还有可以希望自定义前缀或者后缀。

---

**Comment by jingyulong** [comment]
谢谢啦。另外问下哈，2.0的版本可以添加根据图床的不同，添加同步删除的操作的插件吗?

**Comment by Molunerfinn** [comment]
@jingyulong 目前插件系统里还没有加入删除的回调，适当的时候会开放。2.0以后插件系统会逐步更新开放功能，届时应该能通过第三方插件实现同步删除。

**Comment by jingyulong** [comment]
还发现了一个问题，拖拽上传后，弹出图片命名的窗口，如果我点击取消，图片还是会上传。这个取消的按钮，在我看来是取消上传，而不是取消重命名。

**Comment by Molunerfinn** [comment]
@jingyulong 不是的，那个只是重命名的窗口，而不是阻止图片上传的窗口。

**Comment by jingyulong** [comment]
@Molunerfinn 明白啦，谢谢答疑。

**Comment by jingyulong** [comment]
@Molunerfinn 右下角的通知也需要优化下，如果我多点击几次复制链接的按钮，通知会出现阻塞，等当前通知结束后，才会进行下次提示。我觉得正常的行为是及时反馈。

**Comment by Molunerfinn** [comment]
@jingyulong 那个是windows的通知栏问题，同一时间只能显示一个并且只能等一个结束后下一个才能再来- -暂时无解。

**Comment by jingyulong** [comment]
@Molunerfinn 好的，谢谢啦。
