### ISSUE TITLE
相册里可以设置Referer就好了

### ISSUE THREAD

**Issue by billy74** [Molunerfinn/PicGo#138]
## 功能请求

希望在相册里加个Referer的设置，这样就可以开启防盗链了，不用允许空Referer来在相册中预览。
现在想在软件的相册中预览就必须允许空Referer

说实话加那么多的存储类型其实只是为了满足更多人群使用，但是单个使用人中，还是使用某一个存储的比较多吧

**Comment by Molunerfinn** [comment]
相册页面无法设置refer。因为是直接通过<img src=""></img>请求的。

**Comment by ASC8384** [comment]
> 相册页面无法设置refer。因为是直接通过`<img src=""></img>`请求的。

4 年了，请问有实现的方法了吗？
