### ISSUE TITLE
Bug Report:拖拽图片到相册界面或者设置界面，会打开软件内置图片浏览器，并没有关闭按钮，只能关掉整个软件

### ISSUE THREAD

**Issue by jingyulong** [Molunerfinn/PicGo#140]
## 问题类型
Bug Report

## PicGo的相关信息
PicGo 版本：1.6.2
所在平台：Windows 10

## 问题重现
![](http://pij0ar5gi.bkt.clouddn.com/image/20181125213540.gif)
图片显示不完全，请点击链接：http://pij0ar5gi.bkt.clouddn.com/image/20181125213540.gif

## 功能请求
内置的图片浏览器右上角的关闭按钮和软件的按钮**有重叠，容易误点**，建议打开图片时背景做一些处理。

---

**Comment by Molunerfinn** [comment]
收到bug，会在2.0版本里修复。
