### ISSUE TITLE
Feature Request：希望增加配置文件，方便多个平台同步自定义的配置

### ISSUE THREAD

**Issue by jingyulong** [Molunerfinn/PicGo#144]
## 问题类型

Feature Request
## PicGo的相关信息
Mac|Windows 
PicGo 1.6.2

## 功能请求
- 多个平台，所有配置都要重新输入，用一个账号同步来讲可能会有点远，不过可以用添加自定义配置文件解决。
- 建议增加图床抓取指定路径图片，显示在相册的功能

---

**Comment by Molunerfinn** [comment]
picgo一直使用着本地的一个叫做`data.json`的配置文件。
![image](https://user-images.githubusercontent.com/12621342/49442614-fa6ff900-f804-11e8-8366-5be5b6bd0f10.png)
通过URL上传考虑是通过插件实现。不过入口还在考虑。
