### ISSUE TITLE
Feature Request：建议重命名上传文件弹出的窗口在软件界面的中央，而不是屏幕中央。

### ISSUE THREAD

**Issue by jingyulong** [Molunerfinn/PicGo#145]
## 问题类型
Feature Request

## PicGo的相关信息
Mac|Windows
PicGo 1 .6.2

## 功能请求
如果把软件主界面移动，上传图片的时候，如果开启上传图片重命名图片功能，重命名的弹出框会出现在屏幕中央，对于我们平时操作不是太方便。

---

**Comment by Molunerfinn** [comment]
嗯，这个可以考虑优化一下
