### ISSUE TITLE
Feature Request：建议增加上传队列显示

### ISSUE THREAD

**Issue by jingyulong** [Molunerfinn/PicGo#146]
## 问题类型
Feature Request

## PicGo的相关信息
Mac|Windows
PicGO 1.6.2

## 功能请求
今天用阿里云的OSS，上传了多张图片，本地显示多张（还有重复），但是OSS上只成功了两张。还没时间测。
但是想到，如果批量上传图片的时候，可以拖入，显示上传队列，可以上传所有，也可以重命名完了之后点击上传，这样交互应该体验会更好。而且如果上传不成功，可以点击重新上传。

---

**Comment by Molunerfinn** [comment]
OSS多图片上传至上传一张那个是个bug。已经在未发布的版本里修复。
目前的流程里每张图片上传的过程是独立的，所以重命名也是在单独的上传过程里的。流程暂时改不了。

**Comment by jingyulong** [comment]
明白了，可以方便本地加一个上传日志吗？上传n张，成功n张，失败n张。

**Comment by Molunerfinn** [comment]
日志的部分应该会在2.1版本里做，目前的功能排期可以查看project：
https://github.com/Molunerfinn/PicGo/projects/5

最近论文在开题，所以开发进度受到影响。等开完题应该能继续开发。

**Comment by jingyulong** [comment]
@Molunerfinn 好的，幸苦啦。再问个小问题哈，如果开启了Https，上传图片会比Http的慢吗？

**Comment by Molunerfinn** [comment]
https的认证过程需要一些运算。但是就单张图片上传来说基本可以忽略不计。

**Comment by jingyulong** [comment]
@Molunerfinn 如果有影响的话，建议加一个OSS的http地址用来上传，然后Https的地址就用来访问了。
