### ISSUE TITLE
上传至imgur的图片无法在imgur账户内找到

### ISSUE THREAD

**Issue by colorblank** [Molunerfinn/PicGo#147]
## 问题类型
Bug Report

## PicGo的相关信息
1.6.2 Mac

## 问题重现
将图片上传至imgur后，是上传至imgur账户内的吗？如果是，我无法在imgur账户找到成功上传的图片。如果不是，是上传到公共还是什么地方？

## 功能请求

---

**Comment by Molunerfinn** [comment]
imgur通过clientId上传的是类似微博图床一样的匿名上传，不会传到自己的imgur账户内。

**Comment by 7peanuts** [comment]
> 

imgur能设置上传到账户内吗？
