### ISSUE TITLE
图片上传没有提示框出现

### ISSUE THREAD

**Issue by mixerdev** [Molunerfinn/PicGo#149]
## 问题类型
Bug Report

## PicGo的相关信息
Mac 1.6.2

## 问题重现
dmg文件安装后配置了阿里云图床，用快捷键comman + shift + p上传，可以上传，但是**没有提示框弹出，完全是静默上传**。点击在状态栏上的picgo小图标可以看到图片已经在已上传列表中，也能直接访问。

同事和我同样的版本mac 1.6.2，但是他上传图片有提示（同样是阿里云）

**Comment by Molunerfinn** [comment]
![image](https://user-images.githubusercontent.com/12621342/50068599-815ba300-0201-11e9-89cc-aae3a22426de.png)

**Comment by huahuayu** [comment]
@Molunerfinn 你好，上传提示是开启的，这真的是一个bug，我安装后从没有出过一次提示，虽然上传提示是开启的。

**Comment by Molunerfinn** [comment]
@huahuayu 你是什么版本的什操作系统的？
![image](https://user-images.githubusercontent.com/12621342/50413714-f8b9b400-084b-11e9-974b-c27a45ad7aff.png)
我这边是没有任何问题的，你要注意一下是否系统级别的开启了免打扰之类的设置

**Comment by huahuayu** [comment]
@Molunerfinn 是mac
谢谢提醒，我发现是我在这里把通知关了，我不知道你这个应用依赖于右边的通知栏做通知
![image](https://user-images.githubusercontent.com/1725060/50435350-e27b2900-091b-11e9-8317-1ae52f0a32b3.png)

**Comment by Molunerfinn** [comment]
@huahuayu 嗯，electron的通知调用的是系统级别的。
