### ISSUE TITLE
希望能支持图片瘦身

### ISSUE THREAD

**Issue by Mofisto** [Molunerfinn/PicGo#150]
## 问题类型
功能需求

## PicGo的相关信息

Picgo 1.6.2 Windows 7 七牛云图床
## 功能请求
1. 希望未来能开发出支持图片瘦身（有损压缩）的功能。
2. 图片瘦身后文件名不变
能支持所有图床最好啦
不知道大家有没有这样的烦恼，
作为图床加载的时候，本地图片过大，比如我自己图片经常2--3M,导致图片加载慢。
我用过Mpic,自己主要用七牛云，但是这个软件有一个功能特性，就是上传的图片会自动重命名，再去看源文件的时候就会很奇怪，所以希望瘦身之后仍然是用户本地的文件名。
最后感谢开发者，带来这么好用的小工具

---

**Comment by Molunerfinn** [comment]
七牛云本身支持图片压缩处理，请自己查阅文档。本体不会提供压缩图片功能，应该交给插件做。


 :octocat: [From gitme iOS](http://flutterchina.club/app/gm.html)

**Comment by Mofisto** [comment]
非常感谢作者提示。感谢作者。
