### ISSUE TITLE
无法正常运行

### ISSUE THREAD

**Issue by yhysir** [Molunerfinn/PicGo#151]
## 问题类型

Bug Report

## PicGo的相关信息

win7 64位系统

## 问题重现

git cnpm install 后npm run dev无法正常运行起来，报错
events.js:167
      throw er; // Unhandled 'error' event
![image](https://user-images.githubusercontent.com/26732157/50197023-6a8f8a80-0380-11e9-88f7-fcb13f2bf2ce.png)

## 功能请求

---

**Comment by Molunerfinn** [comment]
另外建议用yarn来安装依赖。如果嫌速度慢可以用yarn然后配上淘宝源。用cnpm装的有的时候依赖会有问题。

**Comment by yhysir** [comment]
感谢，萌新提问，已经解决了。
