### ISSUE TITLE
[Feature Request] 使用命令行上传

### ISSUE THREAD

**Issue by CaiJingLong** [Molunerfinn/PicGo#152]
## 问题类型

Feature Request

## PicGo的相关信息

提供命令行调用软件接口的方案

## 功能请求

希望可以有通过命令行的方式来调用上传图片,就是可以在命令行中通过类似于`picgo upload -p ~/image.png`来达到快捷上传的功能
![image](https://user-images.githubusercontent.com/14145407/50384575-70c79300-0701-11e9-9a8a-bb4a2c50ee5f.png)

或者就是说能不能抽取出一部分功能来使用node构建一个本地服务

---

**Comment by Molunerfinn** [comment]
我猜你在说这个：[PicGo-Core](https://github.com/PicGo/PicGo-Core)，这个是PicGo2.0的底层核心，可以在命令行以及node环境下使用。
