### ISSUE TITLE
觉得还是很需要一个账户系统

### ISSUE THREAD

**Issue by l-souljourney** [Molunerfinn/PicGo#153]
因为有时候会频繁在不同电脑上安装picgo，然后每次都要重新配置一遍比如图床信息，能否开发一个账户系统，登陆之后可以同步图床和软件配置。这样会方便很多的。

**Comment by Molunerfinn** [comment]
配置文件是开放的，你可以复制到其他的地方去。
![image](https://user-images.githubusercontent.com/12621342/50503836-ac1ce580-0aa4-11e9-8a4c-0c9330275a03.png)
