### ISSUE TITLE
CPU usage is exploding.

### ISSUE THREAD

**Issue by seungmun** [Molunerfinn/PicGo#154]
When I run `npm run dev`, my cpu usage rate is getting 100%.

Especially, if I modify the file in src/main directory while running dev watch, the usage seems to increase.
(This is not accurate.)

How about you? And is there a solution?

----

Windows 10
Node v10.14.2

**Comment by Molunerfinn** [comment]
No, It seems no problem for me...
While I use Node v8.13, my Mac & Win10 are both normal.

**Comment by Molunerfinn** [comment]
You can create a new electron-vue project by using [electron-vue](https://github.com/SimulatedGREG/electron-vue), and then see how the results

**Comment by Molunerfinn** [comment]
![image](https://user-images.githubusercontent.com/12621342/50508031-09239600-0abb-11e9-97b7-3ffa1025c0b5.png)

**Comment by Molunerfinn** [comment]
No..., maybe you can reset to this [commit](https://github.com/Molunerfinn/PicGo/commit/60ccd10e1aff0d94c1337c61325d34d2e8083251), and then reinstall node modules to see what will happen. The commit was the last commit before I updated electron version & webpack version to 4.

**Comment by seungmun** [comment]
No, It never gets 100% usage of CPU at that commit.

`electron-vue` default project is never getting 100% because it included electron 1.x version. maybe.

WHAT THE PROBLEM! SHOULD I DOWNGRADE MY NODE VERSION?!

**Comment by Molunerfinn** [comment]
:joy: maybe you can use nvm to change the version of node

**Comment by seungmun** [comment]
Okay, I will try it and tell you about the result!

Hold on my dude!

**Comment by seungmun** [comment]
Never works well :-( I am so sad.

**Comment by Molunerfinn** [comment]
:-( sorry... I have no idea about this...

**Comment by seungmun** [comment]
I am still stressed by the problem.

Can you tell me your version of Windows build?

Type it `winver` in cmd.

**Comment by demon1q** [comment]
你好，为什么我开启了上传成功提醒，却没有任何反应![img](https://demon-1258469613.cos.ap-shanghai.myqcloud.com/img/20190108215315.png)

**Comment by Molunerfinn** [comment]
@demon1q 你好，请你先查查已有的issue: https://github.com/Molunerfinn/PicGo/issues/149

**Comment by demon1q** [comment]
> @demon1q 你好，请你先查查已有的issue: #149

嗯嗯 解决了 谢谢 是我自己的通知关闭了

**Comment by demon1q** [comment]
还有一个问题 就是win10上小窗口不能置顶 还有任务栏关闭就直接退出了而不是隐藏在后台

**Comment by Molunerfinn** [comment]
@demon1q 2.0版本里将会增加小窗口置顶的选项。任务栏关闭是在后台的- -，你自己注意一下你的任务栏小窗口：
![image](https://user-images.githubusercontent.com/12621342/51075138-adfcc080-16c2-11e9-8f26-42ed5500ae59.png)
另外有其他问题请你再开issue，不要继续在这个issue下回复了。

**Comment by demon1q** [comment]
好的，多谢




| |
张强
|
|
邮箱：18112358325@163.com
|

签名由 网易邮箱大师 定制

On 01/12/2019 23:35, PiEgg wrote:

@demon1q 2.0版本里将会增加小窗口置顶的选项。任务栏关闭是在后台的- -，你自己注意一下你的任务栏小窗口：

另外有其他问题请你再开issue，不要继续在这个issue下回复了。

**Comment by Molunerfinn** [comment]
2.2 use a different framework, now it will be OK
