### ISSUE TITLE
请问Github上传能不能支持类似Gitlab和Coding这样的网站？

### ISSUE THREAD

**Issue by PhoenixGS** [Molunerfinn/PicGo#155]
## 问题类型

Feature Request

## 功能请求

Github上的照片访问有些慢，所以请问能不能支持其他Git的网站？谢谢啦，支持

**Comment by Molunerfinn** [comment]
README阅读一下。本体不再支持其他图床。想要支持其他图床等2.0出来后自行开发插件支持。

**Comment by PhoenixGS** [comment]
> README阅读一下。本体不再支持其他图床。想要支持其他图床等2.0出来后自行开发插件支持。

请问2.0什么时候出来呢？QAQ

**Comment by Molunerfinn** [comment]
估计下个月吧
