### ISSUE TITLE
为什么多张图片一起上传的时候相册里显示的是一样的

### ISSUE THREAD

**Issue by PhoenixGS** [Molunerfinn/PicGo#157]
## 问题类型

Bug Report

## PicGo的相关信息

Mac

## 问题重现

RT，图片的名字也是一样的

有截图
![image](https://user-images.githubusercontent.com/19629579/50533966-ca9be300-0b6f-11e9-9f73-34047550ddb8.png)
![image](https://user-images.githubusercontent.com/19629579/50533968-d091c400-0b6f-11e9-9a83-c12cf93a26a7.png)

**Comment by Molunerfinn** [comment]
你用的是阿里云OSS么？

**Comment by PhoenixGS** [comment]
腾讯云

**Comment by Molunerfinn** [comment]
你说的多张图片上传是怎么上传的，拖动进去还是啥

**Comment by PhoenixGS** [comment]
拖进去的
![image](https://user-images.githubusercontent.com/19629579/50534010-cfad6200-0b70-11e9-9bbf-7a2ae8723916.png)
这个窗口

**Comment by Molunerfinn** [comment]
那可能是开启了时间重命名的时候，两个名字是一样的，后面的那张就覆盖了前面的那张。你看看你的文件名，是一样的。这个bug在2.0里修复了，多张图片上传的时候如果开启时间重命名会有自增。1.6版本里你需要手动注意一下时间戳命名的文件名。

**Comment by PhoenixGS** [comment]
谢谢，作者辛苦了
