### ISSUE TITLE
复制失效问题

### ISSUE THREAD

**Issue by StudentWan** [Molunerfinn/PicGo#16]
在剪贴板已经有东西的时候，复制链接会失败。
使用的版本是1.2.0。
图床是七牛云。

另外在github上更新似乎有点太慢了，不知道能否提供别的下载地址？
谢谢。

**Comment by Molunerfinn** [comment]
没有其他下载地址。。没时间维护这么多，请谅解。你可以使用[freedownloadmanager](https://www.freedownloadmanager.org/zh/)来下载github的release文件，速度会很快。
剪贴板复制的bug已经收到，下个版本会更新~

**Comment by StudentWan** [comment]
好滴 谢谢啦 过几天有空了争取提一些PR

**Comment by Molunerfinn** [comment]
@StudentWan 我这边需要一下你的复制失效问题的复现说明。我这边测试的情况是可以的。由于剪贴板是入栈的操作，所以最后的文本复制会放在最上面。你那边的失效是指你剪贴板里原本就有文本还是图片？复制是点击了menubar窗口的图片复制的还是点击了主窗口的相册功能里的复制按钮出的问题？麻烦给一下复现操作我这边定位一下问题，谢谢啦
