### ISSUE TITLE
mac下使用github图床时，配置完必填项，提示请输入用户名，这一步在哪设置呢

### ISSUE THREAD

**Issue by we11cheng** [Molunerfinn/PicGo#160]
## 功能请求

---

**Comment by Molunerfinn** [comment]
把你的配置截图发上来？

**Comment by Molunerfinn** [comment]
目测你是仓库名前面没有加自己的用户名进去：
![image](https://user-images.githubusercontent.com/12621342/51069725-b11a9100-166f-11e9-9be0-aee2c2df9456.png)

**Comment by Molunerfinn** [comment]
![image](https://user-images.githubusercontent.com/12621342/51069733-bd9ee980-166f-11e9-8cb5-200751006be1.png)

**Comment by we11cheng** [comment]
没有设置为默认图床，设置之后好了，感谢
