### ISSUE TITLE
WIN 10&PicGO 1.6.2上传没有提示

### ISSUE THREAD

**Issue by xmzzyo** [Molunerfinn/PicGo#161]
## 问题类型

Bug Report

## PicGo的相关信息

WIN 10&PicGO 1.6.2

## 问题重现

上传没有提示

**Comment by Molunerfinn** [comment]
请发issue前多找找之前的issue：
https://github.com/Molunerfinn/PicGo/issues/149
![image](https://user-images.githubusercontent.com/12621342/51081770-a07f1f00-1732-11e9-99ca-aa45fe7e2258.png)

**Comment by xmzzyo** [comment]
谢谢回复！是因为开启了win 10的优先通知，PicGo的通知被拦截了。
