### ISSUE TITLE
安装本地GUI插件报错

### ISSUE THREAD

**Issue by zWingz** [Molunerfinn/PicGo#162]
## 问题类型

Bug

## PicGo的相关信息

v2.0.0 mac

## 问题重现

开发插件遇到此问题

![image](https://user-images.githubusercontent.com/13031838/51100424-02ae5180-1811-11e9-83b8-a45c61527795.png)

## 插件代码

为[demo](https://picgo.github.io/PicGo-Core-Doc/zh/dev-guide/gui.html#guimenu) 中的代码
![image](https://user-images.githubusercontent.com/13031838/51100438-178ae500-1811-11e9-9f1e-efa6104d461c.png)

**Comment by Molunerfinn** [comment]
下个小版本应该会加一个`重启`的按钮方便调试吧:joy:

**Comment by zWingz** [comment]
我一直都有重启.
后面直接用`plugin-template`, 然后我发现`plugin-template` ts版本编译后的入口有问题. 
按模板来说, 入口应该是`src/index.js`.

**Comment by Molunerfinn** [comment]
@zWingz 啊那应该是我在模板里写错了。你现在入口改完之后还有这个问题么？

**Comment by zWingz** [comment]
改完后现在没问题.可以正常开发

**Comment by Molunerfinn** [comment]
@zWingz OK~我立马去修改一下template :joy: 速度好快啊，已经在写插件了

**Comment by Molunerfinn** [comment]
@zWingz template已经修改好了，如果你用新的template来build的话，应该还是`dist/index.js`，之前是我tsconfig配置写错了

**Comment by zWingz** [comment]
ok
