### ISSUE TITLE
希望增加插件的全局快捷键调用

### ISSUE THREAD

**Issue by J3n5en** [Molunerfinn/PicGo#163]
做了个截图自动上传的插件，在cli上可以通过自定义cmd实现，但是还是觉得不方便。

希望增加GUI插件的全局快捷键调用方法，这样的话插件的可玩性就多很多了。

**Comment by Molunerfinn** [comment]
嗯，快捷键模块会考虑一下的，目前已经预留配置了

**Comment by Molunerfinn** [comment]
写好的插件欢迎开源出来给大家用呀，回头我会建一个仓库给PicGo的插件们的~

**Comment by Molunerfinn** [comment]
2.2版本会支持，我会尽快更新一下文档

**Comment by Molunerfinn** [comment]
已更新
