### ISSUE TITLE
Windows 下2.0版本上传总是失败

### ISSUE THREAD

**Issue by Lucio0O** [Molunerfinn/PicGo#164]
## PicGo的相关信息
版本：2.0
平台：Windows x64

## 问题重现
配置了腾讯云 COS V5 和微博，都是上传进度条到一半之后，提示错误
图床应该是都按照教程配置好了

![image](https://user-images.githubusercontent.com/37397080/51156852-6b043e00-18b8-11e9-8cef-6b4a32dede09.png)

---

**Comment by Molunerfinn** [comment]
你可以用用SMMS图床，看看是否还出现问题，SMMS图床是不用配置的，如果还出现问题请看看你上传的图片是不是有问题。Windows下如果你想要复制图片上传请打开图片后右键复制图片才行，单纯复制图片文件是不行的

**Comment by Lucio0O** [comment]
> 请问你是用什么方式上传的？剪贴板图片还是直接拖拽上传的？

剪贴板和拖拽上传都会遇到一样的问题

**Comment by Molunerfinn** [comment]
那可能是你的配置项配置有问题，注意是否配置项前后多了空格。然后你可以先用用SMMS图床，那个不需要配置项，所以可以直接看看能否使用。

**Comment by Lucio0O** [comment]
SMMS图床刚跟试了也是提示：请检查配置和上传的文件是否符合要求

**Comment by Molunerfinn** [comment]
请问你上传的文件格式是什么，发上来看看？

**Comment by Lucio0O** [comment]
https://user-images.githubusercontent.com/12621342/34974486-482c0caa-fac8-11e7-963b-8e0ee5418828.png

**Comment by Molunerfinn** [comment]
文件名是啥？可能文件名里有特殊字符什么的？

**Comment by Molunerfinn** [comment]
![image](https://user-images.githubusercontent.com/12621342/51161901-2c2db280-18cf-11e9-9f90-60516dd67650.png)
我这边依然是复现不了

**Comment by Lucio0O** [comment]
那就奇怪了，我卸载重装试一下

**Comment by Molunerfinn** [comment]
调试的办法：
1. 打开你PicGo的安装目录（有一个PicGo.exe的）：
![image](https://user-images.githubusercontent.com/12621342/51161968-6bf49a00-18cf-11e9-898a-96fa85a4a09b.png)
2. 用CMD或者PowerShell在安装目录下打开，然后输入`.\PicGo.exe`
![image](https://user-images.githubusercontent.com/12621342/51162013-a3fbdd00-18cf-11e9-8b12-44bea4c0c472.png)
3. 拖拽上传一张图片，然后把PowerShell或者CMD的截图发上来看看：
![image](https://user-images.githubusercontent.com/12621342/51162046-bf66e800-18cf-11e9-927c-a8cedcd273b1.png)

**Comment by Molunerfinn** [comment]
直接截图然后ctrl+v到github的输入框里就能上传图片了

**Comment by Lucio0O** [comment]
解决了，切换了个网络。应该是公司办公网络做了限制。
多谢多谢

**Comment by Molunerfinn** [comment]
OK :smile:

**Comment by Molunerfinn** [comment]
@Lucio0O 喜欢的话欢迎点个star！

**Comment by supbadboy** [comment]
![](https://raw.githubusercontent.com/supbadboy/image/master/20190610175241.png)

这个是什么原因

**Comment by Molunerfinn** [comment]
https://github.com/Molunerfinn/PicGo/issues/279

**Comment by LeoSue** [comment]
> 直接截图然后ctrl+v到github的输入框里就能上传图片了

但是我想用那个剪切板图片上传按钮怎么办呀？可以私聊吗？他老时报这个错
![image](https://user-images.githubusercontent.com/48464107/63741896-6fbab700-c8c9-11e9-9c4c-7361434aef19.png)
我查了所有的issues 都不行

**Comment by supbadboy** [comment]
![](https://raw.githubusercontent.com/supbadboy/image/master/img/20190829092331.png)
这个问题有遇到过吗 ？  日志上这个错误，上传一直出现服务端出错，请重试

**Comment by Molunerfinn** [comment]
> ![](https://raw.githubusercontent.com/supbadboy/image/master/img/20190829092331.png)
> 这个问题有遇到过吗 ？ 日志上这个错误，上传一直出现服务端出错，请重试

你这个就是很明显没有认真看文档，去issue搜搜多少个跟你一样的....

**Comment by Molunerfinn** [comment]
> > 直接截图然后ctrl+v到github的输入框里就能上传图片了
> 
> 但是我想用那个剪切板图片上传按钮怎么办呀？可以私聊吗？他老时报这个错
> ![image](https://user-images.githubusercontent.com/48464107/63741896-6fbab700-c8c9-11e9-9c4c-7361434aef19.png)
> 我查了所有的issues 都不行

@LeoSue 所有的issue？请问你powershell的环境变量配对了吗

**Comment by supbadboy** [comment]
> 你这个就是很明显没有认真看文档，去issue搜搜多少个跟你一样的....好好看GitH

不啊  我两个电脑 安装的版本都是一样的  配置也是一样的啊 只是token不同  为啥一台行 另外一个不行呢  配置文件我对比的了的

**Comment by Moheli** [comment]
> 是否做了全局代理等配置？

你好，我也出现这个情况，但是换手机热点还是这样

**Comment by Molunerfinn** [comment]
> > 是否做了全局代理等配置？
> 
> 你好，我也出现这个情况，但是换手机热点还是这样

TIMEOUT是网络问题，跟PicGo无关
