### ISSUE TITLE
阿里云OSS图片上传无法显示

### ISSUE THREAD

**Issue by banpie** [Molunerfinn/PicGo#165]
## 问题类型

Bug Report

## PicGo的相关信息

Mac V2.2.0

## 问题重现

1. 使用的是阿里云的OSS，图片未上传前，可以看见；
2. 上传后，外链打开可以正常显示，但是在软件中图片无法显示：
![image](https://user-images.githubusercontent.com/9192763/51163174-cc85d600-18d3-11e9-92b7-0b3e26bfe572.png)
3. 相册也看不见
![image](https://user-images.githubusercontent.com/9192763/51163189-d90a2e80-18d3-11e9-9b0b-731a4ac1baf4.png)

## 尝试的步骤

1. 已经搜索过 https://github.com/Molunerfinn/PicGo/issues/86 ，目前：
  - 没有使用全局代理
  - OSS是公开可读的

2. 根据https://github.com/Molunerfinn/PicGo/issues/117 设定自定义域名，也已经设定过了

![image](https://user-images.githubusercontent.com/9192763/51163330-3ef6b600-18d4-11e9-9dbf-6378d0e15a1f.png)

3. [点击查看图片链接](http://cdn.bpteach.com/images/20190115143919.png)

**Comment by Molunerfinn** [comment]
自定义域名那里，没加前缀，`http://`或者`https://`。已经上传过的图片，你到相册区里点击图片下面的编辑按钮，加上前缀应该就可以了。

**Comment by banpie** [comment]
> 自定义域名那里，没加前缀，`http://`或者`https://`。已经上传过的图片，你到相册区里点击图片下面的编辑按钮，加上前缀应该就可以了。

感谢回复，的确可以了。
