### ISSUE TITLE
【官方】如果你也在为PicGo开发插件，或者在用PicGo-Core开发，可以看过来~

### ISSUE THREAD

**Issue by Molunerfinn** [Molunerfinn/PicGo#167]
欢迎提交一个PR给[Awesome-PicGo](https://github.com/PicGo/Awesome-PicGo)，把你的项目添加到Awesome-List里！提交前请注意看CONTRIBUTING的要求！

感谢各位开发者的贡献！有你们让PicGo更强大 :smile: :tada:

**Comment by ruanfumin** [comment]
真棒！~

**Comment by jearton** [comment]
正在学习electron开发

**Comment by jearton** [comment]
作者能不能提供Amazon S3的支持？

**Comment by Molunerfinn** [comment]
@jearton 不一定，有时间再说，最近在找实习。

**Comment by Molunerfinn** [comment]
移步 [插件讨论区](https://github.com/Molunerfinn/PicGo/issues/222）
