### ISSUE TITLE
关于remove操作想法

### ISSUE THREAD

**Issue by zWingz** [Molunerfinn/PicGo#169]
## 问题类型

Feature Request

## 功能请求

如今`remove`功能是通过事件传递, 插件在监听到`remove`事件时候, `db`已经把该条记录删掉, 所以在进行`remove`相关操作如果出错, 无法回滚

建议:

- `remove`操作可以监听插件的返回结果, 如果为`false`或者`Promise.reject`则不执行删除.
- `remove`监听跟`Uploader`进行绑定, 只有对应的`Uploader`能进行相关`remove`监听并操作

**Comment by Molunerfinn** [comment]
将 `remove` 作为事件是有原因的。

1. 不是所有的上传方都支持删除。比如微博图床、Imgur等都是匿名的。所以本体支持的图床一律没有做`remove`事件处理，都交给插件。
2. `remove`操作不在正常的上传流程里：

![image](https://user-images.githubusercontent.com/12621342/51364990-17445f80-1b19-11e9-97cd-9fd7d98f0732.png)

因此它没办法接入PicGo-Core底层的上传流程中，也就无法被你所说的`Uploader`捕获。

3. 接上一条`remove`操作是在GUI环境下的。在PicGo里，删除操作是有二次确认的：

![image](https://user-images.githubusercontent.com/12621342/51365023-4529a400-1b19-11e9-85b7-bd8c58dba4e8.png)

所以用户很明确自己需要删除这张图片，至于远端有没有成功删除，那是插件的事。你所说的回滚不应该直接体现在用户点击了删除，但是因为远端没删掉，本地也删不掉。相对的，你能拿到删除的图片具体是哪些，你的插件只需要关系自己对应的图片类型，对其进行远端删除即可。如果发生了错误，没有把远端的删掉，插件应该自己将没有删掉的部分存储下来，然后在插件面板给一个菜单或者其他方式，让用户二次操作把未在远端删除的图片删除。

所以大前提是不能影响用户在本地相册里的删除体验。至于远端是否删除成功、如果在失败后再有机会删除，这应该是插件自身应该思考的事。

**Comment by zWingz** [comment]
`picgo-core`是只是用来进行上传, 不用来进行图片管理.
但`GUI`上的确有图片管理这一块. 而其实`remove`, `rename`这类操作也是属于图片管理.
既然一个`plugin`可以完成`uploader`, `transform` 等5个上传的生命周期. 那后续的管理是否也可以开放出给插件管理.
目前的确可以把输入`remove`的缓存下来.如果失败了可以再次添加.
但那样是直接操作`picConfig.uploaded`这个数据. 不同插件也可能由于不谨慎而误删

**Comment by Molunerfinn** [comment]
插件不推荐直接写`uploaded`这个字段。当然如果插件自身要写也是没有办法避免的，毕竟只要赋予了fs权限，理论上你可以把整个PicGo从系统上抹掉。

`remove`如果作为管理项，那么将会造成如下问题：

- 用户批量删除的时候，如果渲染进程只向主进程发布一个事件。但是因为用户批量删除的时候图床可能不一样，导致渲染进程要监听多次主进程反馈的事件，如果一张图片一次回传未免性能上有损耗。如果一个图床回传一次，那么如果这个图床删除的多张图片里有一部分删除失败，那么返回的结果反而变得很复杂。
- 如果删除耗时，那么用户在点击删除后将不知道为何图片依然还在，可能会进行多次重复操作，加重上述的循环。

所以我依然觉得把删除作为一个事件发布而不是作为插件管理项走更为合理。

实际上插件如果要做`同步远端删除`的功能，除了监听`remove`事件的时候删除，还可以在自身的菜单项里多增加一个诸如 `同步本地删除至远端`的菜单，将`remove`事件里没删除成功的图片在插件菜单项里手动继续删除。
