### ISSUE TITLE
如何更改快捷键，与vscode的格式化按钮冲突了

### ISSUE THREAD

**Issue by SpontaLeo** [Molunerfinn/PicGo#17]
如题

**Comment by Molunerfinn** [comment]
暂不支持！不过已经在计划中。下一个minor版本应该会支持自定义快捷键，因为整个快捷键模块都还在设计中。
目前来说你需要切换到比如桌面的时候来使用快捷键。请谅解~

**Comment by coderbean** [comment]
@SpontaLeo 自己编译修改下吧，或者我把编译好的分享给你。快捷键变成了`cmd+shift+u`, [下载地址](	https://image-hosting-1251780645.cos.ap-beijing.myqcloud.com/PicGo-1.3.2.dmg)

**Comment by Molunerfinn** [comment]
v1.4.0版本已经支持自定义快捷键功能，可以查看[文档](https://github.com/Molunerfinn/PicGo/wiki/%E8%AF%A6%E7%BB%86%E7%AA%97%E5%8F%A3%E7%9A%84%E4%BD%BF%E7%94%A8#%E8%87%AA%E5%AE%9A%E4%B9%89%E5%BF%AB%E6%8D%B7%E9%94%AE)
v1.4.0版本正在构建，稍后可以在release页面下载
