### ISSUE TITLE
希望添加远端同步删除功能

### ISSUE THREAD

**Issue by rxliuli** [Molunerfinn/PicGo#170]
真心希望，picgo 有远端删除功能。毕竟，现在每次上传出现了问题想要更换都要去 github 上删除，实属麻烦 Ծ‸Ծ

> 附：吾辈可以转载更新的博文么？
 https://molunerfinn.com/picgo-v2.0-update/

**Comment by Molunerfinn** [comment]
远程删除功能本体不提供，已经有钩子可以让插件去实现了。文档：https://picgo.github.io/PicGo-Core-Doc/zh/dev-guide/gui.html#remove

可以转载

**Comment by Molunerfinn** [comment]
@zWingz https://github.com/zWingz/picgo-plugin-github-plus/blob/43270a4ae7c79a9e3109229da72f1190de1350dd/index.ts#L2
不需要用electron的Notification了，直接可以用`guiApi.showNotification`。你的electron是在`devDependencies`里，所以用户安装的时候是不会安装`electron`的，这样你的Notification在插件安装后是用不了的。
showNotification的使用文档：https://picgo.github.io/PicGo-Core-Doc/zh/dev-guide/gui.html#shownotificaiton-option

**Comment by zWingz** [comment]
会有这个问题的吗.原来项目依赖不是本来就有`electron`了吗

**Comment by Molunerfinn** [comment]
@zWingz 安装的时候你的插件是装在配置文件的所在文件夹下的。所以`require('electron')`的时候是去配置文件夹所在的`node_modules`里去找。而PicGo打包之后，依赖是内置在`asar`文件里，不对外暴露。所以调用的时候是不会把内部模块暴露出去的。

**Comment by Molunerfinn** [comment]
@zWingz 本地跑完发现确实可以...很奇怪。主要是项目本身和插件本身不是在同一个进程里跑起来的，所以感觉有点奇怪。回头我再看看为什么吧，不过目前来说应该是能运行的
