### ISSUE TITLE
guiMenu一个bug. 

### ISSUE THREAD

**Issue by zWingz** [Molunerfinn/PicGo#171]
## 问题类型
bug
## PicGo的相关信息
最新
## 问题重现

![image](https://user-images.githubusercontent.com/13031838/51421389-9a78ba80-1bd8-11e9-9bd1-5276024adf2d.png)

既然`guiMenu`是一个`function`, 那就不应该拿`guiMenu.length > 0`
因为`guiMenu.length`返回的是方法参数的个数.
```javascript
guiMenu = () => [{label: '', handle: () => {}}]
```
此时`guiMenu.length === 0`, 会导致无法执行`menu`
目前解决方法只能是
```javascript
guiMenu = (ctx) => [{label: '', handle: () => {}}]
```
还是说编写`guiMenu`参数一定要带`ctx`呢? 这不太合理.

**Comment by zWingz** [comment]
`guiMenu` 能否提供一个`confirm`操作. 有些操作无法回滚可能要二次确认.

**Comment by Molunerfinn** [comment]
guiApi以后会提供messagebox用于信息提醒或者二次确认，类似删除图片的时候弹出来的那个确认框

**Comment by zWingz** [comment]
不错不错

**Comment by Molunerfinn** [comment]
开发计划可以参考
https://github.com/Molunerfinn/PicGo/issues/171#issuecomment-455745767
