### ISSUE TITLE
小图标无法置顶

### ISSUE THREAD

**Issue by demon1q** [Molunerfinn/PicGo#172]
## 问题类型

Feature Request
## PicGo的相关信息

Windows 10 PicGo 2.0.1
## 功能请求

就是小图标无法置顶 不能像迅雷或者百度云那样
[http://pkfdxuz6o.bkt.clouddn.com//img/Gif录制_19121150856.gif](url)

---

**Comment by Molunerfinn** [comment]
收到反馈，这个是个小bug，下个小版本更新的时候会修复~

**Comment by Molunerfinn** [comment]
嗯？不是关闭了么

**Comment by demon1q** [comment]
不是这个意思 就是希望不要关闭 就像迅雷和百度云一样 任务栏关闭只是最小化而不是直接关掉了

**Comment by Molunerfinn** [comment]
不过对于electron来说如果你主动在任务栏关闭这个窗口那么它就会被销毁。我可以把mini窗口的时候在任务栏上的窗口显示取消掉。
