### ISSUE TITLE
希望自定义url模式可以增加更多参数

### ISSUE THREAD

**Issue by Y4er** [Molunerfinn/PicGo#173]
## 功能请求

希望自定义url模式可以增加更多参数
比如图片文件名

**Comment by Molunerfinn** [comment]
这个之后可能会详细做一次需求评估，目前暂无计划。

**Comment by 0772boy** [comment]
> 这个之后可能会详细做一次需求评估，目前暂无计划。

。。额，请问我留言的格式不对吗还咋了。。。请问能否将设置文件保存在程序目录下？便携化之类的？谢谢

**Comment by Molunerfinn** [comment]
@0772boy 说了不行了，这个涉及底层架构不会轻易改动的。https://github.com/Molunerfinn/PicGo/issues/178

**Comment by 0772boy** [comment]
> @0772boy 说了不行了，这个涉及底层架构不会轻易改动的。#178

。。。哦，好的，谢谢T_T，我看core有个-c的参数还以为这个也能呢

**Comment by upupming** [comment]
@0772boy 你可以用这个同步配置到github https://github.com/zWingz/picgo-plugin-github-plus

**Comment by feichaiyu** [comment]
请问,PicGo生成的markdown链接格式为什么是![](ppmjxze3u.bkt.clouddn.com/******)，怎么没有http/https？只能靠Custom自定义格式，但这样PicGo相册中又无法预览

**Comment by Molunerfinn** [comment]
下个版本将会支持 `$fileName`
