### ISSUE TITLE
【Feature Request】希望可以加入相册同步删除功能

### ISSUE THREAD

**Issue by cooper1x** [Molunerfinn/PicGo#174]
## 问题类型
Feature Request

## PicGo的相关信息
win10 1809 x64

## 功能请求
希望可以加入相册同步删除功能，就是在相册预览的图片点击删除后，服务器也对应删除。
我找了下API文档，不知道你这边能不能用，尤其是对于那种不是根目录有路径的，比方说img/a.png这种不知道能不能删。
https://cloud.tencent.com/document/product/436/7743

**Comment by Molunerfinn** [comment]
已有接口交给插件实现

**Comment by Molunerfinn** [comment]
文档：https://picgo.github.io/PicGo-Core-Doc/zh/dev-guide/gui.html#remove
相关issue：https://github.com/Molunerfinn/PicGo/issues/170
