### ISSUE TITLE
CPU占用，相册卡顿

### ISSUE THREAD

**Issue by glamourzc** [Molunerfinn/PicGo#175]
## 问题类型

Bug Report

## PicGo的相关信息

Win10，PicGo 2.0.2
## 问题重现

相册卡顿，滑动时同时cpu占用严重
![](https://raw.githubusercontent.com/glamourzc/iPic/master/images/20190123220055.png)

**Comment by Molunerfinn** [comment]
你是不是大图片或者GIF很多啊？以及你的图片总数有多少呢

**Comment by Molunerfinn** [comment]
相册页图片多，渲染起来因人而异，得看图片数量以及图片格式等，这个能优化的空间比较小，之后可能会加个virtual-list来提升性能，不过可能不会有太多提高

**Comment by glamourzc** [comment]
图片只有48张，但是每次打开相册都会重新加载缩略图。1.6.x中不存在这个问题，挺快的。

**Comment by Molunerfinn** [comment]
可能是加了动画效果的原因

**Comment by Molunerfinn** [comment]
我回头看看吧，如果有必要可以加一个禁止动画效果的选项。先看看是什么原因。

**Comment by Molunerfinn** [comment]
下次更新应该相册页的CPU占用会低了。不过是有条件的：

1. 初次打开的时候需要第一次加载图片和渲染，所以第一次可能会慢一点，加上有图片懒加载，所以往下滚动的时候第一次可能会有「卡」的感觉。这是正常的
2. 第一次打开之后，后续只要窗口不关闭，再次回到相册页也不会重新加载图片了，相册页第一次打开之后会缓存起来。这样的话效果会好很多。

**Comment by pictoken** [comment]
多图上传就会提示COOKIE失效 其实没有失效

**Comment by Molunerfinn** [comment]
@pictoken 我这边多图上传微博图床是没问题的。你要不要试试更新一下cookie？

**Comment by fantab01** [comment]
@Molunerfinn 啊......刚才一次性往阿里云oss上上传了五十张图片，现在相册页面超级无敌卡啊，重启也是超级无敌卡，我忍着卡顿从顶部滚动到底然后再滚动回顶，按理说已经渲染完毕了，但还是超级......无敌卡.......

**Comment by Molunerfinn** [comment]
之后更新的版本里会更新相册页的DOM结构，应该能减少不少卡顿的感觉，不过相册的图片的缩略图的处理逻辑也随之改变，有些图片可能会「失真」（比如被缩放、或者被压缩了），这是正常的，不影响点击后预览的效果。也是对提升性能后的一点妥协

**Comment by Molunerfinn** [comment]
2.1.1版本应该解决了这个问题了，可以更新看看。
