### ISSUE TITLE
小窗口无法点击上传图片。

### ISSUE THREAD

**Issue by ronething** [Molunerfinn/PicGo#176]
## 问题类型

Bug Report

## PicGo的相关信息

picgo 版本：2.0.2

平台：Mac

系统版本：Mojave 10.14.2 

## 问题重现

![image](https://user-images.githubusercontent.com/28869910/51734702-467e4200-20c0-11e9-94d3-cc72773729f0.png)

默认 github 图床

在这个小窗口点击上传无反应。（我点了好多次都没用。）不过快捷键和详细窗口是可以的。

## 功能请求

希望可以解决一下。(如果只是我的电脑问题就有点尴尬了。🎸)

---

**Comment by Molunerfinn** [comment]
收到，回头排查一下。

**Comment by Molunerfinn** [comment]
已经修复，静候下个小版本更新
