### ISSUE TITLE
需要取消全局快捷键的功能

### ISSUE THREAD

**Issue by wuwb** [Molunerfinn/PicGo#177]
默认快捷键和 vscode 的命令行快捷键冲突。

**Comment by Molunerfinn** [comment]
快捷键可以自定义的( っ'-')╮

**Comment by Molunerfinn** [comment]
怕你找不到：
![image](https://user-images.githubusercontent.com/12621342/51957642-6b3f3480-2487-11e9-965d-f9717b43ca28.png)

**Comment by Molunerfinn** [comment]
是的，能设置就行了未什么需要取消呢
