### ISSUE TITLE
请问如何将PicGo便携化？我想让它把data.json保存在程序安装目录下可以吗？

### ISSUE THREAD

**Issue by 0772boy** [Molunerfinn/PicGo#178]
PicGo的配置文件在不同系统里是不一样的。
Windows: %APPDATA%\picgo\data.json

请问如何将PicGo便携化？我想让它把data.json保存在程序安装目录下可以吗？

**Comment by Molunerfinn** [comment]
不行。不存在这个文件会自动创建。
