### ISSUE TITLE
请检查配置和上传的文件是否符合要求

### ISSUE THREAD

**Issue by ZeddYu** [Molunerfinn/PicGo#179]
## 问题类型

Bug Report

## PicGo的相关信息

MacOS 10.14.2
版本:2.0.3

## 问题重现

原来使用2.0版本无错，今晚更新到2.0.3之后，无论怎么上传图片（剪贴、选择、拖拽等方式），均提示请检查配置和上传的文件是否符合要求。上传之前传过的图片也是如此。

使用的是微博图床，网络没问题，是否关闭全局代理均尝试过。

---

**Comment by ZeddYu** [comment]
网络没问题，是否关闭全局代理均尝试过。

**Comment by Molunerfinn** [comment]
跟版本没关系，2.0.3没有做底层修改。你这个是Cookie过期了，重新复制一遍Cookie吧。我这边都是没问题的。

**Comment by ZeddYu** [comment]
> 跟版本没关系，2.0.3没有做底层修改。你这个是Cookie过期了，重新复制一遍Cookie吧。我这边都是没问题的。
> 不信的话你降回去也一样。

未使用Cookie模式诶...用的账号密码

**Comment by Molunerfinn** [comment]
帐号密码有的时候会遇到要输入验证码，但是PicGo不支持输入验证码，所以也会提示上传失败，推荐用Cookie模式。如果觉得麻烦可以用SM.MS图床不用配置
