### ISSUE TITLE
又拍云删除图片失败！

### ISSUE THREAD

**Issue by gee1k** [Molunerfinn/PicGo#18]
首先感谢一下大佬的工具，很好用。
但是我在使用的过程中发现好像又拍云删除图片提示成功，但是图床里面还在

**Comment by Molunerfinn** [comment]
我在说明里说过了，这个删除功能只针对本地删除：
![image](https://user-images.githubusercontent.com/12621342/35430528-95a78296-02b3-11e8-8d83-6c18dbcb34d9.png)
文档[地址](https://github.com/Molunerfinn/PicGo/wiki/%E8%AF%A6%E7%BB%86%E7%AA%97%E5%8F%A3%E7%9A%84%E4%BD%BF%E7%94%A8#%E7%9B%B8%E5%86%8C%E5%8C%BA)
