### ISSUE TITLE
自动上传剪切板的图片

### ISSUE THREAD

**Issue by PikachuHy** [Molunerfinn/PicGo#181]
## 功能请求
可否增加自动上传剪切板的图片的功能

详细描述：
当通过截图软件将图片保存到剪切板时，自动将图片上传到图床，然后把md图片链接写到剪切板
增加一个开关是否自动上传

使用场景：
当写文章的时候，某一个时间段内的截图肯定是都要上传到图床的，这个时候每次按快捷键反而不方便

**Comment by Molunerfinn** [comment]
electron没有提供剪贴板监听事件，所以暂时无法实现。
