### ISSUE TITLE
实用性建议: 先(预测)获取链接再上传

### ISSUE THREAD

**Issue by Zhangzijing** [Molunerfinn/PicGo#182]
## 问题类型
Feature Request

## 功能请求
对于腾讯COS(或类似云储存)其实可以直接先计算出图片URL, 再进行上传, 这样就不必等待上传完成才CTRL+V了. 
(我目前使用的是Snipast+PicGo, 上传图片流程: F1截图, CTRL+SHIFT+P上传, 等待上传, CTRL+V粘贴
多数时间花在等待上传这一步, 实际上可以简化到: F1截图, CTRL+SHIFT+P上传并提前自动粘贴图片URL. 于是瞬间操作完毕
).

**Comment by Molunerfinn** [comment]
这个可以用插件实现，本体就不会提供了。


 :octocat: [From gitme iOS](http://flutterchina.club/app/gm.html)
