### ISSUE TITLE
重命名是否可以隐藏提示呢？

### ISSUE THREAD

**Issue by rxliuli** [Molunerfinn/PicGo#183]
# 如题
目前每次重命名都会弹窗提示，即便吾辈已经选择了**【按照时间戳重命名】**，然而每次还是会有提示，真的很麻烦，可否添加个可配置项呢？

**Comment by rxliuli** [comment]
![image_2019-02-15_18-19-15](https://user-images.githubusercontent.com/24560368/52850644-ecb4e900-314e-11e9-86ca-a910bb7e0c28.png)

**Comment by Molunerfinn** [comment]
为什么不好好看看配置页呢


 :octocat: [From gitme iOS](http://flutterchina.club/app/gm.html)

**Comment by Molunerfinn** [comment]
![image](https://user-images.githubusercontent.com/12621342/52851095-34884000-3150-11e9-8c11-e0e05b32f16d.png)

**Comment by rxliuli** [comment]
吾辈已经找到了，之前不清楚上传前重命名是必须弹出窗口的（吾辈以为要和下面的时间戳重命名同时使用）┐(‘～`；)┌

PiEgg <notifications@github.com> 于2019年2月15日周五 下午6:33写道：

**Comment by Molunerfinn** [comment]
@rxliuli 建议如果配置项看不懂用来做啥，可以先看看文档：https://picgo.github.io/PicGo-Doc/zh/guide/config.html#%E4%B8%8A%E4%BC%A0%E5%89%8D%E9%87%8D%E5%91%BD%E5%90%8D
