### ISSUE TITLE
剪贴板上传不成功

### ISSUE THREAD

**Issue by zhangferry** [Molunerfinn/PicGo#184]
## 问题类型
Bug Report

## PicGo的相关信息

V2.0.3 Mac
## 问题重现

![image](https://user-images.githubusercontent.com/13702445/52953717-3ad22280-33c3-11e9-8144-32c2cfb0728e.png)

我截完图之后，点开PicGo，会显示我刚才的截图是等待上传状态。等了一段时间（5分钟）之后还一直显示等待上传。我点击该张图片，鼠标会出现一个灰色的禁止图标。

我用拖动的方式上传是没有问题的。

试过重启客户端，还是会出现这种问题。

**Comment by Molunerfinn** [comment]
emmmmPicGo不会自动上传的，都需要你手动点一下。
点击该图片出现一个灰色禁止图标是为了防止多次点击。你等一会就会发现图片上传成功了。

**Comment by Molunerfinn** [comment]
![image](https://user-images.githubusercontent.com/12621342/52954466-3d357c00-33c5-11e9-8bbc-266dd3d8ba1c.png)
文档里也说了

**Comment by zhangferry** [comment]
感谢回复，是我操作问题。已经star了😄

**Comment by Molunerfinn** [comment]
感谢支持😁
