### ISSUE TITLE
【Feature Request】希望增加服务端支持

### ISSUE THREAD

**Issue by yuki-xin** [Molunerfinn/PicGo#186]
## 问题类型

Feature Request

## PicGo的相关信息

Linux

## 功能请求

希望添加服务端部署功能，开放API

**Comment by Molunerfinn** [comment]
我猜你说的是这个：[PicGo-Core](https://github.com/PicGo/PicGo-Core)，相关文档：https://picgo.github.io/PicGo-Core-Doc/
