### ISSUE TITLE
【Feature Request】md文件本地图片地址批量转图床地址

### ISSUE THREAD

**Issue by cooper1x** [Molunerfinn/PicGo#187]
## 问题类型
Feature Request

## PicGo的相关信息
版本：PicGo 2.0.2
系统：Windows 10 x64 1809 教育版

## 功能请求

希望可以加入markdwon文件内所有本地图片链接转线上图床地址的功能，用拖拽或者选择md文件的方式操作。

这个场景适用于没网的时候写本地md文件，然后有网了读取文件里面的本地图片地址，然后上传图床，地址批量替换。

**Comment by Molunerfinn** [comment]
这个我已经用插件实现了。
https://github.com/PicGo/picgo-plugin-pic-migrater

**Comment by Molunerfinn** [comment]
本体只会提供图片上传功能，需要额外功能以后都交给三方开发者用插件实现。请悉知。

**Comment by cooper1x** [comment]
这个我刚刚试了下，发现除了文件名可以配置，无法选择图床。
我默认的是腾讯COS。
而且我测试了一下，提示转换成功，可是路径还是本地的没有变。

**Comment by Molunerfinn** [comment]
不会修改源文件的内容，只会在新文件里修改

**Comment by cooper1x** [comment]
新文件也没有改呢

**Comment by Molunerfinn** [comment]
@cooper1x 提示转换成功会提示转换成功了几张，失败了几张。

我这边测试了是没问题的。

转换前：

![image](https://user-images.githubusercontent.com/12621342/53221656-6005b000-36a5-11e9-9191-21bafe85f0a8.png)

转换后：

![image](https://user-images.githubusercontent.com/12621342/53221672-6eec6280-36a5-11e9-9712-c44c8a501685.png)

注意图片的格式必须是`![](xxxx)`这样才会被转换。

**Comment by Molunerfinn** [comment]
![image](https://user-images.githubusercontent.com/12621342/53221708-980cf300-36a5-11e9-9d9e-424ee68cb766.png)

**Comment by cooper1x** [comment]
![image](https://user-images.githubusercontent.com/9080789/53221896-7c561c80-36a6-11e9-998b-458366795269.png)
我的测试文档内容是这样的，是不是Windows路径不识别呢？
```
![emoji_7e01g15f3r](C:\Users\Cooper\Desktop\emoji_7e01g15f3r.gif)

![1550807033464](C:\Users\Cooper\AppData\Roaming\Typora\typora-user-images\1550807033464.png)
```

**Comment by Molunerfinn** [comment]
@cooper1x Windows绝对路径这个应该是个bug，我修复一下。上传成功了但是文件没写入。

**Comment by Molunerfinn** [comment]
@cooper1x 单`\`会引起转义的问题，在替换的时候就无法正确替换了。请使用`/`作为分隔符。

**Comment by Molunerfinn** [comment]
![image](https://user-images.githubusercontent.com/12621342/53223782-7283e780-36ad-11e9-89b6-cdd01dae5782.png)

**Comment by cooper1x** [comment]
可以了，谢谢。
我目前是在typora里面用`Ctrl+H`替换全部然后转换的。
如果有系统脚本可以实现转换成`\\`或者`/`后再用js获取就更好了，这个Windows路径的历史包袱也困扰了我很久。
