### ISSUE TITLE
Weibo cookie上传失败

### ISSUE THREAD

**Issue by itgoyo** [Molunerfinn/PicGo#188]
## 问题类型

Bug Report

## PicGo的相关信息

Windows

## 问题重现

登录https://weibo.com/minipublish
获取cookie然后填写 

![](https://raw.githubusercontent.com/itgoyo/PicGoRes/master/img/TIM%E6%88%AA%E5%9B%BE20190222121740.png)

右下角提示上传失败，服务器错误

**Comment by Molunerfinn** [comment]
你没把微博图床设为你的默认图床吧？右下角那个`设为默认图床`要点一下。
![image](https://user-images.githubusercontent.com/12621342/53221366-fe911180-36a3-11e9-8ece-1d6b910405cd.png)

**Comment by itgoyo** [comment]
额，确实没有设置成默认，谢谢回答
