### ISSUE TITLE
【Feature Request】希望可以在上传图片页可以快速切换图床

### ISSUE THREAD

**Issue by cooper1x** [Molunerfinn/PicGo#189]
## 问题类型
Feature Request

## 功能请求
有时候我是临时用一下图片，这时候就用sm.ms这样的公共图床，所以需要快速切换。
![image](https://user-images.githubusercontent.com/9080789/53231106-22178480-36c3-11e9-9619-a9801e1d320a.png)
希望可以考虑一下这个需求。

**Comment by Molunerfinn** [comment]
会考虑实现，不过需要看看如果安排布局和样式。

**Comment by cooper1x** [comment]
嗯嗯，我也觉得布局的调整是个问题，现在的按钮是比较满的。
可以考虑在这个字后面做个按钮，或者把图床名称整个做成一个按钮。

**Comment by CaiJingLong** [comment]
快速切换图床 
可以考虑添加一个快捷键
然后效果是直接在鼠标焦点处或右上角icon处弹出一个选择框,接受上下键/1~0键选择?

建议仅供参考 😃

**Comment by lefinite** [comment]
![image](https://user-images.githubusercontent.com/23370734/53460776-3b308480-3a79-11e9-93f4-5b14a80a73d0.png)
鼠标悬浮在这里时，弹出图床列表，点击直接切换图床。
这样就是最好的了。

**Comment by Molunerfinn** [comment]
![image](https://user-images.githubusercontent.com/12621342/53462918-623e8480-3a80-11e9-8ccb-5425a4a6881b.png)
![image](https://user-images.githubusercontent.com/12621342/53462927-69fe2900-3a80-11e9-98b4-a7ab799f78a2.png)

**Comment by cooper1x** [comment]
@lefinite hover还有一个问题就是，不容易被发现，而且等待时间略长，效率不是很高。
