### ISSUE TITLE
Mac上PicGo 2.0.3 版本安装不了pic-migrater插件

### ISSUE THREAD

**Issue by liaoyt** [Molunerfinn/PicGo#191]
## PicGo的相关信息

PicGo版本：2.0.3
Mac版本：Mojave 10.14.2 (18C54)
安装插件：pic-migrater 1.0

## 问题重现

搜索到插件后，点击安装，弹出错误提示框
![](https://raw.githubusercontent.com/liaoyt/img/master/image/20190301182032.png)
点击‘好’以后插件一直显示'安装中'，就不动了。
![](https://raw.githubusercontent.com/liaoyt/img/master/image/20190301182324.png)

---

**Comment by Molunerfinn** [comment]
安装插件需要有Nodejs环境，文档里已经说明了。你安装一下Nodejs环境然后重启应用就能安装插件课。

**Comment by liaoyt** [comment]
好的，请问nodejs有没有具体的版本要求。文档并没有说明需要安装😂😂

**Comment by Molunerfinn** [comment]
@liaoyt 安装最新的LTS版本吧。至少要>=8。
文档里是有说的：https://picgo.github.io/PicGo-Doc/zh/guide/config.html#安装
![image](https://user-images.githubusercontent.com/12621342/53634370-037e3400-3c55-11e9-9c47-4d3ad9646828.png)

**Comment by Molunerfinn** [comment]
不过之后我应该会加一个提示，如果没有npm的话就让用户去安装Node.js

**Comment by liaoyt** [comment]
好的，非常感谢
