### ISSUE TITLE
截图工具到剪贴板的图片无法上传

### ISSUE THREAD

**Issue by einvince** [Molunerfinn/PicGo#192]
公司 家里两台mac电脑用最新版都会出现
使用微信或系统的截图工具到剪贴板，上传时一直在等待
但是如果将截图保存到本地，再复制文件，上传，秒传

**Comment by Molunerfinn** [comment]
这个bug已经修复，下个版本就会更新

**Comment by chenyinchang** [comment]
> 这个bug已经修复，下个版本就会更新

Windows版本直接就没反应。微信截图，使用快捷键或者直接在UI界面点击剪切板上传都不行。
