### ISSUE TITLE
Mac上的腾讯云COS V5上传后相册没有显示

### ISSUE THREAD

**Issue by im-yuxuan** [Molunerfinn/PicGo#193]
## 问题类型

**Bug Report**

## PicGo的相关信息

**PicGo: 2.0.3     Mac: 10.14.3**

## 问题重现

- 没有设置防盗链

- 图片 URL 是https:开头

- 
![2019-03-08 2 05 19](https://user-images.githubusercontent.com/48344765/54011012-eba23500-41ab-11e9-8585-1a99df2afb6b.png)

- 
![2019-03-08 2 05 27](https://user-images.githubusercontent.com/48344765/54011024-f6f56080-41ab-11e9-8be4-5ae8154f11bf.png)

---

**Comment by Molunerfinn** [comment]
你的URL有问题啊

**Comment by Molunerfinn** [comment]
![image](https://user-images.githubusercontent.com/12621342/54011161-7f740100-41ac-11e9-8bf1-74db40a97320.png)

**Comment by Molunerfinn** [comment]
把你的COS的配置页截个图，可以把token那些打码，我就看看你customUrl或者path是怎么写的

**Comment by im-yuxuan** [comment]
![2019-03-08 2 20 10](https://user-images.githubusercontent.com/48344765/54011441-80f1f900-41ad-11e9-87de-ef0cbb6821db.png)
![2019-03-08 2 18 37](https://user-images.githubusercontent.com/48344765/54011446-82bbbc80-41ad-11e9-9b9d-a8d0137c51da.png)

**Comment by Molunerfinn** [comment]
你指定存储路径那边写错了，不是`\image/`，而是直接写`image/`：
![image](https://user-images.githubusercontent.com/12621342/54011514-c9111b80-41ad-11e9-93a6-e33ee639a6f8.png)
已经传过的图片你通过编辑把`\image/`前面的`\`去掉应该就能看到了

**Comment by im-yuxuan** [comment]
还是不行，依然显示不出来
![2019-03-08 2 28 41](https://user-images.githubusercontent.com/48344765/54011718-8a2f9580-41ae-11e9-8bd5-e3b8b753f39a.png)

**Comment by Molunerfinn** [comment]
你是用剪贴板上传的图片的话，Mac2.0.3版本是有个bug的，下个版本会更新。你现在已经是显示出实际图片了，只不过这个图片是由于剪贴板图片上传的bug引起的：
详细可以看：https://github.com/Molunerfinn/PicGo/issues/190
预计今天下午更新2.0.4就OK了。你可以试试通过拖拽上传图片，应该是没问题了

**Comment by im-yuxuan** [comment]
好的谢谢大佬！
