### ISSUE TITLE
【Bug Report】快捷键设置失败报错

### ISSUE THREAD

**Issue by cooper1x** [Molunerfinn/PicGo#194]
## 问题类型

Bug Report

## PicGo的相关信息
win10 x64 1809
PicGo 2.0.4

## 问题重现
我设置快捷键shift+``或者是`TAB+\`，都出现下面报错。
![image](https://user-images.githubusercontent.com/9080789/54018414-8ce8b580-41c3-11e9-86a5-c687f1e1442f.png)

**Comment by Molunerfinn** [comment]
组合键支持`ctrl`、`shift`和`alt`
也就是只有这几个键支持`+`其他键跟随的。所以`TAB`实际上是不支持`+`的。

然后你的`Shfit~`实际上可能是按键太快导致错误记录，实际上应该是Shift+`才是对的：
![image](https://user-images.githubusercontent.com/12621342/54018916-d554a300-41c4-11e9-95d5-1932a160b711.png)

**Comment by Molunerfinn** [comment]
PicGo支持的快捷键系统比较简单，所以最好使用一些常用组合来。

**Comment by cooper1x** [comment]
这个报错是我点击确定触发的。
由于我左手边的快捷键好按的都设置了别的软件，三个键不太方便，略显尴尬。
