### ISSUE TITLE
自定义的快捷键上传不起作用

### ISSUE THREAD

**Issue by strivebo** [Molunerfinn/PicGo#195]
## 问题类型

Bug Report
## PicGo的相关信息

picgo 2.0.2/2.0.3/2.0.4  平台：windows7 64-bit
## 问题重现
升级到了最新版 2.0.4 使用，自定义上传的快捷键方式不起作用（以前是可以的），更换快捷键也没成。于是软件换回到版本 2.0.3 和 2.0.2，但发现自定义的快捷键上传还是不起作用。

---

**Comment by Molunerfinn** [comment]
我这边是没问题的，不过我的机器是WIN10，我也没有WIN7的测试环境，按理说应该没啥区别。

目前你提供的信息太少还不足以判断问题出在什么地方。你可以先退出PicGo，然后到PicGo的安装所在目录：

![image](https://user-images.githubusercontent.com/12621342/54097254-298c9c80-43ea-11e9-9ef0-48b59f9cf9c7.png)
使用CMD或者POWERSHELL打开：
![image](https://user-images.githubusercontent.com/12621342/54097266-3c06d600-43ea-11e9-9926-3f77c32713a0.png)
然后你再复制一张图片，使用快捷键上传，看看CMD或者POWERSHELL输出是什么，截图上来看看：

![image](https://user-images.githubusercontent.com/12621342/54097332-96079b80-43ea-11e9-9f25-cfff1c4d1138.png)

我这边是没问题的。

**Comment by Molunerfinn** [comment]
我估计可能是POWERSHELL的脚本问题

**Comment by strivebo** [comment]
@Molunerfinn 好的。我目前版本 2.0.3，windows7 64bit，上传快捷键为 ctrl+e。
下图为我刚刚快捷键上传出现的：
![QQ截图20190311105225](https://user-images.githubusercontent.com/25930007/54097682-2d212300-43ec-11e9-94e8-191f62c79cc4.png)

**Comment by Molunerfinn** [comment]
果然应该是上次改进的PowerShell脚本不支持WIN7....

**Comment by strivebo** [comment]
@Molunerfinn 哈，算是后端问题吗？因为我记得我没升级到 2.0.4 之前我是有是有使用快捷键上传成功，后来看到提示更新，就立即更新到了 2.0.4，后面偶然需要上传图片，发现快捷键不起作用，于是换到低版本2.0.3/2.0.2 也是不行。

期待 bug 的修复~ 也非常感谢作者你开发的 picgo，自从知道该客户端，便一直在使用，非常方便~

**Comment by Molunerfinn** [comment]
@strivebo 嗯我现在只能使用降级方案了，如果发现不支持新版本的POWERSHELL脚本，就回退回以前的行为——不能复制图片文件上传了，只能复制图片内容上传（比如截图，比如网页里右键图片->复制）

**Comment by Molunerfinn** [comment]
就目前来说你可以这样来操作复原原本的功能，直到2.0.5我会更新一个修复的版本。
1. 卸载2.0.4版本的PicGo
2. 通过打开配置文件，你可以找到配置文件所在的目录：
![image](https://user-images.githubusercontent.com/12621342/54098783-eeda3280-43f0-11e9-9c46-1e02aa88b915.png)
3. 删掉图中所示三个文件：
![image](https://user-images.githubusercontent.com/12621342/54098796-00bbd580-43f1-11e9-91af-3cc359ae661c.png)
4. 降级回2.0.3就可以了

**Comment by Molunerfinn** [comment]
我目前已经在更新文档里提示了：
![image](https://user-images.githubusercontent.com/12621342/54098851-47113480-43f1-11e9-93f8-e9606719abdc.png)
感谢你的反馈！

**Comment by strivebo** [comment]
@Molunerfinn 刚按你的操作指示，已解决——可以快捷键上传。感谢！

另外有个关于软件的需求，不知道能否提下哈？——每次电脑开机， picgo 上传小图标也跟着在桌面显示，因为我设置了软件开机自启+快捷键上传，只需 picgo 在底部栏即可，每次我都会把 picgo 小图标关掉，这样多了点操作加了点麻烦。哈哈，不知可否在新版picgo中有个类似「电脑开机小图标桌面不显示」的设置

**Comment by Molunerfinn** [comment]
@strivebo 会考虑加上

**Comment by chenyinchang** [comment]
@Molunerfinn Win8.1也有这个问题

**Comment by Molunerfinn** [comment]
@chenyinchang 嗯那就是只有WIN10支持新版PowerShell的一些方法了。

**Comment by Molunerfinn** [comment]
@demon1q 你是截图之后+快捷键上传还是复制了图片+快捷键上传呢？如果你是复制了图片文件+截图上传的话，请留意一下你的图片文件名是否有中文？以及图片路径是否有中文？PowerShell获取的中文会是乱码，所以会导致上传路径错误，所以如果要复制图片文件上传的话，请把路径以及文件名都改成英文

**Comment by demon1q** [comment]
> @demon1q 你是截图之后+快捷键上传还是复制了图片+快捷键上传呢？如果你是复制了图片文件+快捷键上传的话，请留意一下你的图片文件名是否有中文？以及图片路径是否有中文？PowerShell获取的中文会是乱码，所以会导致上传路径错误，所以如果要复制图片文件上传的话，请把路径以及文件名都改成英文

是截图了直接上传 我看了一下 我截的图名字确实是带了中文

**Comment by Molunerfinn** [comment]
@demon1q 嗯，目前还不支持中文的图片，或者图片带有中文的路径。主要是由于编码问题，我看看能否解决吧，如果解决了会一并在2.0.5里更新

**Comment by Molunerfinn** [comment]
WIN10的问题解决了，今天会更新2.0.5

**Comment by hucstar** [comment]
我2.1.2怎么遇到了这个问题呀？

**Comment by 1015127214** [comment]
> 我估计可能是POWERSHELL的脚本问题

你好，我现在可以，我能进目录运行这个程序，但是快捷键上传有问题，没啥显示的
![image](https://user-images.githubusercontent.com/31812278/95564482-749ce480-0a51-11eb-8c0c-0e03c3c60fde.png)
