### ISSUE TITLE
是不是可以考虑加入gitee的图床支持呢？

### ISSUE THREAD

**Issue by gnehcgnaw** [Molunerfinn/PicGo#196]
## 问题类型
免费的存储方式GitHub图床是一个不错的选择， 但是国内响应很慢，是不是可以考虑加入gitee的图床支持呢？

**Comment by Molunerfinn** [comment]
![image](https://user-images.githubusercontent.com/12621342/54178133-b198a200-44cf-11e9-9428-61de67b73494.png)
已经有开发者开发了第三方图床插件了。比如青云。

**Comment by Molunerfinn** [comment]
有兴趣的话欢迎贡献插件~

**Comment by gnehcgnaw** [comment]
好的，我不是这方面的开发人员，我刚才以赞助的方式予以支持了。感谢你的共享。

**Comment by Molunerfinn** [comment]
@gnehcgnaw 感谢！
