### ISSUE TITLE
【Feature Request】建议移除或修改七牛的指定存储路径的选项

### ISSUE THREAD

**Issue by cooper1x** [Molunerfinn/PicGo#197]
## 问题类型

Feature Request

## PicGo的相关信息

win10 x64 1809
PicGo 2.0.4

## 功能请求
这个我跟官方确认过，并且自己测试过了，七牛的对象存储不支持自定义路径，也就是根目录下无法创建二级目录。
![image](https://user-images.githubusercontent.com/9080789/54178019-46e76680-44cf-11e9-8756-8346a2b1135f.png)
建议可以这样，当用户进入七牛配置界面时候，把这个框弄成灰色不可选，鼠标悬浮或者旁边有个小问号悬浮告诉用户这个设置七牛是无效的，或者移除这个项也可以。

**Comment by Molunerfinn** [comment]
是支持的，只不过七牛把这个当做文件名来处理了。
![image](https://user-images.githubusercontent.com/12621342/54178310-4bf8e580-44d0-11e9-9462-20f6e258802b.png)
