### ISSUE TITLE
2.0.5问题

### ISSUE THREAD

**Issue by Xiaohantx** [Molunerfinn/PicGo#199]
## 问题类型
Bug Report

## PicGo的相关信息
2.0.5 mac

## 问题重现
[![WX20190312-142023@2x.png](https://i.loli.net/2019/03/12/5c874ff6d10f6.png)](https://i.loli.net/2019/03/12/5c874ff6d10f6.png)
2.0.4版本mac仍然不能通过快捷键或者从剪切板上传按钮上传剪切板的图片，下载了2.0.5版本后，运行出现了该错误提示无法打开

---

**Comment by gnehcgnaw** [comment]
同样这个问题我也出现了。 @Molunerfinn

**Comment by Molunerfinn** [comment]
macOS版本的不必更新2.0.5，你降级回2.0.4。如果2.0.4版本的macOS不支持剪贴板上传，可以试试这个issue的办法：
![image](https://user-images.githubusercontent.com/12621342/54179368-929c0f00-44d3-11e9-8a06-d80d1b9c731d.png)

**Comment by Molunerfinn** [comment]
目前我已经撤下2.0.5的dmg版本地址。windows是正常的

**Comment by Xiaohantx** [comment]
我这边修改了系统语言为英文后仍然无法上传快捷键和按钮都不可以。。点了没反应

**Comment by Xiaohantx** [comment]
[![WX20190312-144114@2x.png](https://i.loli.net/2019/03/12/5c87549a29f63.png)](https://i.loli.net/2019/03/12/5c87549a29f63.png)

不行，这里能看见剪切板的图片，但是鼠标放上去这里是有个禁止的箭头加禁止的圆

**Comment by Xiaohantx** [comment]
手动选择文件是好的。。。剪切板方式都行不通好像

**Comment by gnehcgnaw** [comment]
Mac系统升级到Macos Mojave版本，系统对模拟按键增加了限制，我不太清除你这个粘贴板是如何实现的（我本人不是搞mac开发的），你是不是使用了模拟组合键的方式呢？ @Molunerfinn

**Comment by Molunerfinn** [comment]
@Xiaohantx 我这边2.0.4无法复现，可能需要你提供更详细的信息来定位问题：

1. 然后先把你的PicGo退出了。

2. 打开你的终端，然后输入：

```bash
cd /Applications/PicGo.app/Contents/MacOS
```
3. 输入：

```bash
./PicGo --debug
```

然后你复制一张图片，然后用快捷键上传也好，主界面点击上传也好，看看终端里报了什么错？

![image](https://user-images.githubusercontent.com/12621342/54180342-58803c80-44d6-11e9-87c3-9a8f27fe7123.png)

**Comment by Molunerfinn** [comment]
@gnehcgnaw 跟那个关系不大，因为除了快捷键上传之外，还可以通过点击按钮的方式来快捷上传图片。

**Comment by Xiaohantx** [comment]
[![WX20190312-145327@2x.png](https://i.loli.net/2019/03/12/5c87577645fc5.png)](https://i.loli.net/2019/03/12/5c87577645fc5.png)

**Comment by Xiaohantx** [comment]
以下报错信息
```
2019-03-12 14:52:49.564 PicGo[1435:37872] *** WARNING: Textured window <AtomNSWindow: 0x7fdd8e692510> is getting an implicitly transparent titlebar. This will break when linking against newer SDKs. Use NSWindow's -titlebarAppearsTransparent=YES instead.
[PicGo ERROR]: *** Error creating a JP2 color space: falling back to sRGB

(node:1435) UnhandledPromiseRejectionWarning: [object Uint8Array]
(node:1435) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:1435) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

```

**Comment by Molunerfinn** [comment]
OK，有报错信息就好定位问题了

**Comment by Molunerfinn** [comment]
你复制的图片不管什么格式都会有这个问题吗

**Comment by Xiaohantx** [comment]
主要是通过截图来剪切板上传，复制图片才试了下也都不行

**Comment by Molunerfinn** [comment]
https://github.com/Molunerfinn/PicGo/blob/dev/static/mac.applescript
这个文件是PicGo获取剪贴板图片的脚本，你可以下载到本地：

```bash
wget https://raw.githubusercontent.com/Molunerfinn/PicGo/dev/static/mac.applescript
```

然后你复制一张图片文件，在终端运行一下这个脚本：

```bash
osascript mac.applescript test
```
如图我的输出是这样的：
![image](https://user-images.githubusercontent.com/12621342/54181226-ccbbdf80-44d8-11e9-9160-11edb990e716.png)

我想看看你的输出是啥

**Comment by Xiaohantx** [comment]
我的不是这样
```
yinhandeMacBook-Pro:Docker xiaohantx$ osascript mac.applescript test
*** Error creating a JP2 color space: falling back to sRGB
*** Error creating a JP2 color space: falling back to sRGB
```

**Comment by Molunerfinn** [comment]
如果你复制了一张图片文件之后，再输入这串代码：

```bash
osascript -e "clipboard info"
```

![image](https://user-images.githubusercontent.com/12621342/54181626-19ec8100-44da-11e9-8711-7077733bf0c1.png)

看看输出是啥。很抱歉让你帮忙一起排查错误花费了不少时间！

**Comment by Xiaohantx** [comment]
没关系，日常划水中，软件很好用
以下为输出结果
```
*** Error creating a JP2 color space: falling back to sRGB
«class PNGf», 63581, «class 8BPS», 265044, GIF picture, 24551, «class jp2 », 68030, JPEG picture, 50697, TIFF picture, 1355634, «class BMP », 1354790, «class TPIC», 123721
```

**Comment by Xiaohantx** [comment]
```
*** Error creating a JP2 color space: falling back to sRGB
TIFF picture, 1090534, «class HTML», 147, «class 8BPS», 225944, GIF picture, 35216, «class jp2 », 72886, JPEG picture, 56264, «class PNGf», 104940, «class BMP », 1090046, «class TPIC», 226861
```

**Comment by Molunerfinn** [comment]
很奇怪，如果是图片文件被复制到剪贴板的话，按理说应该可以获取到`«class furl»`从而获取到你的图片文件本身。我现在有个猜想，可能是因为你的command line tool在升级系统版本后没有升级导致的？

试试看：

```bash
xcode-select --install
```

看看是否需要升级

**Comment by Xiaohantx** [comment]
```
xcode-select: error: command line tools are already installed, use "Software Update" to install updates
```

**Comment by Molunerfinn** [comment]
那么你打开Xcode呢，有没有提示要升级？或者你看看你的Xcode是否需要升级？

**Comment by angnuoli** [comment]
@Molunerfinn 我的输出是 "/test" 没有 User 之类的

![](https://i.loli.net/2019/03/12/5c87603b4a44c.jpg)

**Comment by Xiaohantx** [comment]
我没有xcode鸭....我不用xcode开发我只有vscode...

**Comment by Molunerfinn** [comment]
@angnuoli 你的picgo也不能复制图片上传么

**Comment by Molunerfinn** [comment]
@Xiaohantx 那就很奇怪了...使用系统自带的clipboard命令你都会出现报错的话就很神奇了

**Comment by Xiaohantx** [comment]
看了下
`Error creating a JP2 color space: falling back to sRGB`
然后猜测了下刚才尝试了下，找到了这句话问题所在....
设置里显示-颜色-色彩描述文件的问题我切换到普通rgb就没问题了，我之前用的display p3

**Comment by Xiaohantx** [comment]
这是mac问题吗，不是太懂mac开发，但是正常图片复制粘贴貌似也没问题呀。。

**Comment by Molunerfinn** [comment]
是呀就很奇怪...其实我也只是前端开发，并不是特别了解mac开发，脚本都是现学的。

如果你的问题解决了，欢迎把具体步骤说一下吧，造福后人~

**Comment by Xiaohantx** [comment]
就是更改了显示的描述文件，就可以了，别的都不用动..
其他描述文件没尝试，普通rgb下没问题，display p3下无法使用剪切板上传

**Comment by Molunerfinn** [comment]
好的，非常感谢！

**Comment by Alalalalaki** [comment]
同样问题。改成普通rgb可以。

**Comment by Molunerfinn** [comment]
PicGo下个版本将会更新剪贴板上传图片的错误处理，使得剪贴板上传图片将不再受 `屏幕色彩描述文件` 的影响。

**Comment by Billin9** [comment]
前两天系统更新了之后又出现这个问题了.

## 相关环境

- 操作系统: macOS Mojave 10.14.5 (18F132)
- PicGo: 2.1.2

## 问题现象

剪切板上传失败.

## 日志

2019-05-27 17:28:43 [PicGo ERROR] *** Error creating a JP2 color space: falling back to sRGB

------Error Stack Begin------
undefined
-------Error Stack End-------

**Comment by Molunerfinn** [comment]
@Billin9 先根据本issue里给出的解决办法改描述文件看看。下个版本会彻底修复这个问题将不用再改描述文件。


 :octocat: [From gitme iOS](http://flutterchina.club/app/gm.html)

**Comment by Billin9** [comment]
@Molunerfinn 好的, 描述文件改成 sRGB 后可以了. 不过我没有更新系统之前用的好好的, 也不用改色彩描述文件, 奇怪. 谢了, 这个软件很好用!

**Comment by najunuoyan** [comment]
同样遇到这个问题，期待解决

**Comment by liutf** [comment]
> 就是更改了显示的描述文件，就可以了，别的都不用动..
> 其他描述文件没尝试，普通rgb下没问题，display p3下无法使用剪切板上传

遇到同样问题。果然显示切换到普通rgb就可以了。眼泪掉下来。

**Comment by zionfuo** [comment]
mac打不开主窗口

**Comment by Molunerfinn** [comment]
@zionfuo 
![image](https://user-images.githubusercontent.com/12621342/63687820-2ec69200-c838-11e9-9cfd-6756c3594db4.png)
没有鼠标的话用双指点按PicGo顶部图标。

**Comment by zionfuo** [comment]
> @zionfuo
> ![image](https://user-images.githubusercontent.com/12621342/63687820-2ec69200-c838-11e9-9cfd-6756c3594db4.png)
> 没有鼠标的话用双指点按PicGo顶部图标。

谢谢大佬

**Comment by theo1201** [comment]
mac中无法上传
查看debug如下：
picgo nhandledPromiseRejectionWarning: StatusCodeError: 401 - "{\"error\":\"
不知道大佬知不知道是什么问题

**Comment by theo1201** [comment]
ps完整的debug内容：
 UnhandledPromiseRejectionWarning: StatusCodeError: 401 - "{\"error\":\"bad auth\"}"
    at new StatusCodeError (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/request-promise-core/lib/errors.js:32:15)
    at Request.plumbing.callback (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/request-promise-core/lib/plumbing.js:104:33)
    at Request.RP$callback [as _callback] (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at Request.self.callback (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/request/request.js:185:22)
    at Request.emit (events.js:182:13)
    at Request.<anonymous> (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/request/request.js:1161:10)
    at Request.emit (events.js:182:13)
    at IncomingMessage.<anonymous> (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:273:13)
    at IncomingMessage.emit (events.js:187:15)
(node:3589) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 5)

**Comment by Molunerfinn** [comment]
@theo1201 401是认证失败，说明你配置不对。

**Comment by SHERlocked93** [comment]
试了下更改 `屏幕色彩描述文件` 然后上传一次成功了，之后又失败了，版本 2.1.2，macOS 版本 10.15.1 😫

**Comment by Sailfishc** [comment]
Mac系统，PicGo 2.1.2，在连接显示器的情况下快捷键上传失败，不接显示器可以上传，手动上传几种情况都可以。
![image](https://user-images.githubusercontent.com/13750989/69207311-42a93800-0b8a-11ea-894c-a7f1b326bf46.png)

**Comment by Molunerfinn** [comment]
@Sailfishc 连接显示器后对应显示器的色彩描述文件也修改一下...

**Comment by BrambleXu** [comment]
@Molunerfinn 
我也出现连连接显示器无法上传的情况。请问该如何修改色彩描述文件

**Comment by shog86** [comment]
依旧遇到这个问题，接了外接显示器，用SMMS和Github的都显示配置不对或者检查图片文件。换了任何其他色彩配置文件也都不行。

另外，Github配置时最后一行的末尾要不要加/？还是说直接`master`就可以了？

**Comment by Molunerfinn** [comment]
> 依旧遇到这个问题，接了外接显示器，用SMMS和Github的都显示配置不对或者检查图片文件。换了任何其他色彩配置文件也都不行。
> 
> 另外，Github配置时最后一行的末尾要不要加/？还是说直接`master`就可以了？

没有打星号的配置项你不知道含义可以不用配置...打星号的配置已经在文档里给出来了。上传成不成功跟url配置无关系，只跟你的token、repo和branch有关系。

色彩文件需要修改你外接的显示器的色彩文件，而不仅仅是你mac本机的。

**Comment by shog86** [comment]
> > 依旧遇到这个问题，接了外接显示器，用SMMS和Github的都显示配置不对或者检查图片文件。换了任何其他色彩配置文件也都不行。
> > 另外，Github配置时最后一行的末尾要不要加/？还是说直接`master`就可以了？
> 
> 没有打星号的配置项你不知道含义可以不用配置...打星号的配置已经在文档里给出来了。上传成不成功跟url配置无关系，只跟你的token、repo和branch有关系。
> 
> 色彩文件需要修改你外接的显示器的色彩文件，而不仅仅是你mac本机的。

还是不行，两个显示器都改成color LCD，重启了应用，也还是不行。拖文件可以，剪贴板不行

**Comment by Molunerfinn** [comment]
@shog86 提供一下报错的日志

**Comment by shog86** [comment]
`2019-12-04 11:36:12.467 PicGo[11966:3242191] *** WARNING: Textured window <AtomNSWindow: 0x7f931a4ad600> is getting an implicitly transparent titlebar. This will break when linking against newer SDKs. Use NSWindow's -titlebarAppearsTransparent=YES instead.
UpdateRecents: about to call HIS_XPC_GetApplicationPolicyForURLs with seed 2141394250
UpdateRecents: received results from HIS_XPC_GetApplicationPolicyForURLs
UpdateRecents: ignoring results because menu isn't open
UpdateRecents: about to call HIS_XPC_GetApplicationPolicyForURLs with seed 2141394250
UpdateRecents: received results from HIS_XPC_GetApplicationPolicyForURLs
UpdateRecents: ignoring results because menu isn't open
UpdateRecents: about to call HIS_XPC_GetApplicationPolicyForURLs with seed 2141394250
UpdateRecents: received results from HIS_XPC_GetApplicationPolicyForURLs
UpdateRecents: ignoring results because menu isn't open
[PicGo ERROR]: osascript: OpenScripting.framework - scripting addition "/Library/ScriptingAdditions/QXPScriptingAdditions.osax" cannot be used with the current OS because it has no OSAXHandlers entry in its Info.plist.

(node:11966) UnhandledPromiseRejectionWarning: [object Uint8Array]
(node:11966) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:11966) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

`

**Comment by shog86** [comment]
> @shog86 提供一下报错的日志

2019-12-04 11:36:12.467 PicGo[11966:3242191] *** WARNING: Textured window <AtomNSWindow: 0x7f931a4ad600> is getting an implicitly transparent titlebar. This will break when linking against newer SDKs. Use NSWindow's -titlebarAppearsTransparent=YES instead.
UpdateRecents: about to call HIS_XPC_GetApplicationPolicyForURLs with seed 2141394250
UpdateRecents: received results from HIS_XPC_GetApplicationPolicyForURLs
UpdateRecents: ignoring results because menu isn't open
UpdateRecents: about to call HIS_XPC_GetApplicationPolicyForURLs with seed 2141394250
UpdateRecents: received results from HIS_XPC_GetApplicationPolicyForURLs
UpdateRecents: ignoring results because menu isn't open
UpdateRecents: about to call HIS_XPC_GetApplicationPolicyForURLs with seed 2141394250
UpdateRecents: received results from HIS_XPC_GetApplicationPolicyForURLs
UpdateRecents: ignoring results because menu isn't open
[PicGo ERROR]: osascript: OpenScripting.framework - scripting addition "/Library/ScriptingAdditions/QXPScriptingAdditions.osax" cannot be used with the current OS because it has no OSAXHandlers entry in its Info.plist.

(node:11966) UnhandledPromiseRejectionWarning: [object Uint8Array]
(node:11966) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:11966) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by Molunerfinn** [comment]
这个报错没见过，我自己也无法复现。。下个版本会修复显示器色彩描述文件导致的报错问题。不过你这个看来好像跟脚本运行还有关系

**Comment by shog86** [comment]
> 这个报错没见过，我自己也无法复现。。下个版本会修复显示器色彩描述文件导致的报错问题。不过你这个看来好像跟脚本运行还有关系。另外你的系统版本是多少？ @shog86

10.15.1，刚才找到那个脚本删掉，就好了！

下次再遇到问题我就自己跑跑debug看看，感谢~

**Comment by BreezeStark** [comment]
感谢楼上,我使用的是 mac10.12, picgo2.1.2,  更改屏幕描述文件后解决  ( bug: 剪切板和快捷键提示上传失败 )   ,  我的笔记本使用的是  linux 系统, 也出现了这个问题, 未尝试解决...

**Comment by jianhao** [comment]
补充下：修改显示器颜色后，剪贴板的图片只有第一次会上传成功，重新截图，再次上传新的图片也会成功。

**Comment by He2008** [comment]
在外接显示器上同样遇见这个问题，修改屏幕描述文件暂时可以用了

**Comment by MintLucas** [comment]
遇到同样的问题，解决办法是外接显示器颜色描述文件要和Mac一样，比如外接HD 709-A改为LCD，Mac一般也是LCD即可解决，或都改成RGB

**Comment by JasonX2140** [comment]
大家还有没有解决这个问题的吗？更改来mac和外接显示器的颜色配置文件之后，依然无法解决该问题？请支支招，谢谢！

**Comment by Molunerfinn** [comment]
> 大家还有没有解决这个问题的吗？更改来mac和外接显示器的颜色配置文件之后，依然无法解决该问题？请支支招，谢谢！

多看更新文档呀- -
![image](https://user-images.githubusercontent.com/12621342/204813460-5a9ddefb-8cd0-44cb-b6bd-d7dab995d2fb.png)

**Comment by JasonX2140** [comment]
> > 大家还有没有解决这个问题的吗？更改来mac和外接显示器的颜色配置文件之后，依然无法解决该问题？请支支招，谢谢！
> 
> 多看更新文档呀- - ![image](https://user-images.githubusercontent.com/12621342/204813460-5a9ddefb-8cd0-44cb-b6bd-d7dab995d2fb.png)

感谢及时回应，谢谢！按照文档的方式进行了操作，但是还是未能解决。执行的动作报告：开启`使用内置剪贴板上传`、重启应用、重新截图、picgo识别图片到待上传区、点击图片图片上依然出现禁止符号。

**Comment by Molunerfinn** [comment]
> > > 大家还有没有解决这个问题的吗？更改来mac和外接显示器的颜色配置文件之后，依然无法解决该问题？请支支招，谢谢！
> 
> > 
> 
> > 多看更新文档呀- - ![image](https://user-images.githubusercontent.com/12621342/204813460-5a9ddefb-8cd0-44cb-b6bd-d7dab995d2fb.png)
> 
> 
> 
> 感谢及时回应，谢谢！按照文档的方式进行了操作，但是还是未能解决。执行的动作报告：开启`使用内置剪贴板上传`、重启应用、重新截图、picgo识别图片到待上传区、点击图片图片上依然出现禁止符号。

点击了图片就会上传 显示禁止符号是为了防止你重复点击上传。。

**Comment by JasonX2140** [comment]
出现的报错信息，请帮看看

`------Error Stack Begin------
Error: [object Object]
    at Object.ve [as handle] (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/picgo/dist/index.cjs.js:1:18794)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async $e.doUpload (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/picgo/dist/index.cjs.js:1:17198)
    at async $e.start (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/picgo/dist/index.cjs.js:1:15969)
    at async Tt.upload (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/picgo/dist/index.cjs.js:1:71270)
    at async Object.upload (/Applications/PicGo.app/Contents/Resources/app.asar/background.js:2:653584)
    at async jn (/Applications/PicGo.app/Contents/Resources/app.asar/background.js:2:656251)
-------Error Stack End-------`

**Comment by JasonX2140** [comment]
> > > > 大家还有没有解决这个问题的吗？更改来mac和外接显示器的颜色配置文件之后，依然无法解决该问题？请支支招，谢谢！
> > 
> > 
> > > 
> > 
> > 
> > > 多看更新文档呀- - ![image](https://user-images.githubusercontent.com/12621342/204813460-5a9ddefb-8cd0-44cb-b6bd-d7dab995d2fb.png)
> > 
> > 
> > 感谢及时回应，谢谢！按照文档的方式进行了操作，但是还是未能解决。执行的动作报告：开启`使用内置剪贴板上传`、重启应用、重新截图、picgo识别图片到待上传区、点击图片图片上依然出现禁止符号。
> 
> 点击了图片就会上传 显示禁止符号是为了防止你重复点击上传。。

出现的报错信息，请帮看看：

`------Error Stack Begin------
Error: ENOENT: no such file or directory, open '/Users/name/Library/Application Support/picgo/picgo-clipboard-images/202212010838713.png.1748160031'
-------Error Stack End------- `

**Comment by JasonX2140** [comment]
> > 
> 
> 不知道你剪贴板图片后面的 `.1748160031` 是怎么来的，导致无法读到正确的图片路径上传，可能是某些插件导致的。
> 
> 剪贴板图片，会先转换到 picgo 配置文件目录下的 `picgo-clipboard-images` 临时文件夹里，然后上传后就会删除。我这边是正常的，请自行检查。

好的，谢谢反馈，我按这个思路再看看

**Comment by gaohongy** [comment]
遇到了相同的问题，使用剪贴板快捷上传失败，查看日志是png后面跟了一串数字导致的no such file or directory.

一种暂时的替代方案是采用quick-capture这个插件，利用插件提供的剪贴板上传功能。
插件的原有执行逻辑是通过快捷键执行插件，插件会执行截图命令，在截图完成后将剪贴板的图片上传。
如果将插件执行的命令修改为true或其他非截图命令，那么就相当于只利用插件的剪贴板图片上传功能，即可以处理截图也可以处理复制的图片

<img width="912" alt="image" src="https://github.com/Molunerfinn/PicGo/assets/56125657/390d44c3-8792-4455-b2e1-14813e5dd40b">

**Comment by real-jiakai** [comment]
在我的场景中，mac上一开始点击picgo中的剪贴板上传没反应，我关闭了使用内置剪贴板上传就可以上传了。目前用的版本是2.4.0-beta.1。
