### ISSUE TITLE
希望作者能支持upyun图床

### ISSUE THREAD

**Issue by nmchgx** [Molunerfinn/PicGo#2]

**Comment by Molunerfinn** [comment]
我看了下upyun的文档，应该可以考虑支持~

**Comment by Molunerfinn** [comment]
v1.2.0版本经支持又拍云了。
详细文档可以查看[wiki](https://github.com/Molunerfinn/PicGo/wiki/%E8%AF%A6%E7%BB%86%E7%AA%97%E5%8F%A3%E7%9A%84%E4%BD%BF%E7%94%A8#%E5%8F%88%E6%8B%8D%E4%BA%91)

**Comment by nmchgx** [comment]
@Molunerfinn 谢谢，有时间可以支持下Homebrew Cask，方便更新

**Comment by Molunerfinn** [comment]
@nmchgx 嗯，这个在考虑之中了
