### ISSUE TITLE
腾讯云COS无法使用

### ISSUE THREAD

**Issue by coderbean** [Molunerfinn/PicGo#20]
我看了下腾讯云COS的SDK文档，看是看懂了，可是我不会node呀，希望作者尽快修复下。

**Comment by Molunerfinn** [comment]
请详细说明你的问题。不能使用报错的错误码是多少？我会有提示的。我这边测试都是可以使用的。如果是`-47`的话，请你看看你的secretId和key值是不是结尾多了空格而你没发现？

**Comment by coderbean** [comment]
@Molunerfinn 什么反应没有，试了几次，没有成功也没有提示，请问这个存储空间名是否需要带APPID后缀，我这样设置是正确的吗。![](https://ws4.sinaimg.cn/large/006tNc79ly1fnwo9r14alj30ou03at90.jpg)

**Comment by coderbean** [comment]
我尝试调试了以下，得到了这个  `(node:22917) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): SyntaxError: Unexpected token Y in JSON at position 0`

**Comment by Molunerfinn** [comment]
存储空间名是你的bucket名
![image](https://user-images.githubusercontent.com/12621342/35483175-0a754c94-047a-11e8-9c7c-9017b262da4a.png)
比如我的就是mofin123
![image](https://user-images.githubusercontent.com/12621342/35483181-17e4620c-047a-11e8-8e5f-48ea986d2e5d.png)

**Comment by coderbean** [comment]
@Molunerfinn 我设置的就是这个![](https://ws2.sinaimg.cn/large/006tNc79ly1fnwoupc3euj30ec07qaae.jpg)

**Comment by Molunerfinn** [comment]
腾讯云这个有毛病。
PicGo支持的是这个：
![image](https://user-images.githubusercontent.com/12621342/35483306-5e7ed570-047b-11e8-95a9-d56a3b4d2ba9.png)
而不是这个：
![image](https://user-images.githubusercontent.com/12621342/35483310-6d4b275c-047b-11e8-8d75-e180f92515e1.png)

**Comment by coderbean** [comment]
@Molunerfinn 我没有找到你说的那个v4的什么，方便贴个URL上来吗？

**Comment by Molunerfinn** [comment]
@coderbean 嗯，这个：https://console.cloud.tencent.com/cos4/index

**Comment by coderbean** [comment]
@Molunerfinn 我点进去就直接跳转到 https://console.cloud.tencent.com/cos5 了，估计只有原来建过cos4存储的才能进，现在都是cos5了。😓

**Comment by Molunerfinn** [comment]
那就不知道新的api长什么样了...这个我也很尴尬，我开通不了新的就无法测。你试试用用七牛吧，我自己用的也是七牛，速度快而且省心。233。回头我要在文档里声明一下。。

**Comment by Molunerfinn** [comment]
我无法申请v5的COS权限，就无法测试了。等开放了我把v5的接入进来，如果你那边做完了也欢迎contribute~。问题搞清楚了，issue我先关了~

**Comment by MrNickLock** [comment]
同是V5，哭晕，不知有进展了吗

**Comment by Molunerfinn** [comment]
@MrNickLock 我已经申请到V5的权限。我将在V1.5版本里尽快更新支持。
目前V1.5版本的进度可以查看：https://github.com/Molunerfinn/PicGo/projects/1
感谢支持。

**Comment by Molunerfinn** [comment]
v1.5版本发布，更新v5版本支持，欢迎更新体验。
@pengzhendong @MrNickLock @coderbean

**Comment by MrNickLock** [comment]
感动感动，这就去试一波！

**Comment by hitck129** [comment]
大概率空格问题吧，我也是，一直上传不成功，弄了一个多小时，后来发现是名称前面多了个空格，因为是直接复制的，估计是复制的时候多了个空格。建议后来者多检查前面和后面有没有多余的空格

**Comment by lhalcyon** [comment]
wtf .. 真的是 @tsukiikekaoru 说的问题. 是复制的名称前面有个空格 = = !
