### ISSUE TITLE
【Bug Report】七牛云markdown格式链接有误

### ISSUE THREAD

**Issue by cooper1x** [Molunerfinn/PicGo#200]
## 问题类型
Bug Report

## PicGo的相关信息
PicGo 2.0.4
win10 x64 1809

## 问题重现
![image](https://user-images.githubusercontent.com/9080789/54336163-47fecc00-4666-11e9-9a2b-e73b7ad8bace.png)
七牛云图床，快捷键上传后，粘贴的格式如上图所示，没有加http://，地址前面有空格，导致typora里面的图加载不出来。

**Comment by Molunerfinn** [comment]
请问你这里有写好`http://`么
![image](https://user-images.githubusercontent.com/12621342/54336382-de32f200-4666-11e9-8485-82027936ec6a.png)

**Comment by Molunerfinn** [comment]
![image](https://user-images.githubusercontent.com/12621342/54336513-3b2ea800-4667-11e9-8626-edfd66f202fd.png)

**Comment by cooper1x** [comment]
好吧，七牛有这个问题，确实没注意。
还是腾讯COS好用。

**Comment by cooper1x** [comment]
另外那个空格是我复制粘贴的时候多了一个空格，如果能用trim()处理下，去掉收尾空格就更好了。
这里不容易看出来有没有空格。
![image](https://user-images.githubusercontent.com/9080789/54336775-fb1bf500-4667-11e9-8ee2-2ae4f6aed339.png)

**Comment by Molunerfinn** [comment]
嗯，这个优化会在之后的版本里加上
