### ISSUE TITLE
上传后TrayPage图片显示不正确, 相册正常

### ISSUE THREAD

**Issue by zWingz** [Molunerfinn/PicGo#202]
## 问题类型

bug

## PicGo的相关信息

mac
2.0.3

## 问题重现

上传后显示404, 在相册内查看正常, 重启后一切正常
![image](https://user-images.githubusercontent.com/13031838/54424716-79eb5d80-474e-11e9-9510-e7bfa9ef4a66.png)

使用的是[github-plus](https://github.com/zWingz/picgo-plugin-github-plus)上传, 已正确设置`imgUrl`. 

另外`trayPage`中的图片能否使用`object-fit`自适应

**Comment by Molunerfinn** [comment]
我用你的github-plus上传是没问题的，TrayPage里的图片显示正常。
不知道你的customUrl是否设置的时候没有写`https://`或者`http://`

trayPage里的图片是根据宽度来定的高度，不设计成固定宽高是为了不让图片失真。

**Comment by zWingz** [comment]
但是我打开相册以及重启都能正常显示.这个跟url没关系吧.
`object-fit`不是可以根据宽度自适应吗.

**Comment by Molunerfinn** [comment]
现在也是根据宽度100%来的。如果你不写http或者https头其实理论上会从file://去获取图片

**Comment by ZonuyCode** [comment]
![image](https://user-images.githubusercontent.com/57613482/97704491-722c2880-1aed-11eb-8552-6f78821de397.png)
我是用GitHub做的，也是图片显示不出来，是哪里出问题了？要怎么改？
