### ISSUE TITLE
上传成功但是显示图片裂掉

### ISSUE THREAD

**Issue by mrlizonglin** [Molunerfinn/PicGo#204]
Bug Report
## PicGo的相关信息

mac
## 问题重现
1.绑定完七牛云图床，并且添加了二级域名（域名可以正常使用）
2.上传图片显示成功，并且通过URL访问可以正常显示。
3.工具的预览显示失败，并且md格式的预览也显示裂图。
4.
![image](https://user-images.githubusercontent.com/22819077/54510718-768fe600-4989-11e9-8a86-876ed4244635.png)

**Comment by mrlizonglin** [comment]
已解决

**Comment by niusz** [comment]
@mrlizonglin 怎么解决的呢？

**Comment by Molunerfinn** [comment]
@niusz 为什么不看看 [FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md#1七牛图床上传图片成功后无法显示或图片无http前缀) 呢

**Comment by niusz** [comment]
@Molunerfinn 可能是防盗链了吧，可是我用另一款软件，同样的图片就可以上传。

**Comment by Molunerfinn** [comment]
@niusz 我也开了防盗链啊...七牛的防盗链可以设置空Referer的，PicGo支持显示空Referer的防盗链图片。

**Comment by niusz** [comment]
> @niusz 我也开了防盗链啊...七牛的防盗链可以设置空Referer的，PicGo支持显示空Referer的防盗链图片。
哦  我懂了 🙏
