### ISSUE TITLE
关于mac下多个桌面，PicGo小图标的显示问题

### ISSUE THREAD

**Issue by ykxkykx** [Molunerfinn/PicGo#205]
## 问题类型
Feature Report

## PicGo的相关信息
PicGo版本为2.0.4
系统为 MacOS Mojave 10.14

## 功能请求

我一共有4个桌面，分别用于不同的工作用途，在第三个界面打开了软件PicGo后，之后只要是在非第三个桌面的任一桌面，点击了顶部栏上的PicGo小图标，都会跳到第三个桌面去。

我希望能够在每一个桌面，点击了PicGO的小图标，就能直接在该桌面进行上传操作，而不是每一次都跳转到打开PicGo时候的那个桌面去。

---

**Comment by Molunerfinn** [comment]
这个是electron的默认行为，暂时无法修复。
