### ISSUE TITLE
安装插件时报错（2.0.5版本）

### ISSUE THREAD

**Issue by Moyf** [Molunerfinn/PicGo#206]
## 问题类型
BUG Report

## PicGo的相关信息
2.0.5 Windows

## 问题重现
![image](https://user-images.githubusercontent.com/4013062/54678084-5a35aa00-4b3f-11e9-9aa8-3b3086e9fef6.png)

---
安装任意一个插件时会弹出这个错误提示。

**Comment by Molunerfinn** [comment]
https://picgo.github.io/PicGo-Doc/zh/guide/config.html#安装
![image](https://user-images.githubusercontent.com/12621342/54678337-e34ce100-4b3f-11e9-98c4-97ea76408ed0.png)

**Comment by Moyf** [comment]
Oooops，抱歉没注意到这里……之前电脑重装了，Node.js 也没了。

那能不能加个 FR，在未安装 Node 时如果尝试安装插件，就 try catch 一下，然后弹出提示「请安装 Node.js」？
现在的报错对于业余人士来说无法获得明确的信息 _(:з」∠)_

PiEgg <notifications@github.com> 于2019年3月20日周三 下午6:42写道：

**Comment by Molunerfinn** [comment]
嗯之后会加上这个
