### ISSUE TITLE
七牛上传图片后在相册中无法看到图片

### ISSUE THREAD

**Issue by zxygithub** [Molunerfinn/PicGo#208]
## 问题类型

Bug Report
## PicGo的相关信息

2.0.4
macOS 10.14.3
七牛

## 问题重现
上传图片后在相册中无法看到图片

<img width="343" alt="屏幕快照 2019-03-22 下午2 29 11" src="https://user-images.githubusercontent.com/1762949/54804678-532da980-4caf-11e9-808e-2868b5fdadd6.png">
<img width="792" alt="屏幕快照 2019-03-22 下午2 29 36" src="https://user-images.githubusercontent.com/1762949/54804679-53c64000-4caf-11e9-9fc4-aea620073f7a.png">
<img width="792" alt="屏幕快照 2019-03-22 下午2 29 28" src="https://user-images.githubusercontent.com/1762949/54804680-53c64000-4caf-11e9-879a-a58da9717abd.png">

## 功能请求

---

**Comment by Molunerfinn** [comment]
发issue前请注意看文档和FAQ。
https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md#1七牛图床上传图片成功后无法显示或图片无http前缀
