### ISSUE TITLE
为什么Win10 防火墙报毒啊

### ISSUE THREAD

**Issue by NeverKnowsTomorrow** [Molunerfinn/PicGo#209]
## 问题类型

 Bug Report 

## PicGo的相关信息

 Version 2.0.5 on Windows 10

**Comment by Molunerfinn** [comment]
并不是报毒...只是因为软件没有签名而已。软件的构建是用CI构建的，没有签名，所以Windows可能不信任。如果觉得不安全可以自己下载代码自己构建。

**Comment by NeverKnowsTomorrow** [comment]
好的，谢谢啦
