### ISSUE TITLE
【已解决】Windows客户端-七牛-上传失败-！记得右键任务栏图标设置默认上传图床哦！

### ISSUE THREAD

**Issue by WilliamHHH** [Molunerfinn/PicGo#21]
您好，

我按照wiki设置完Windows客户端的七牛云存储之后，提示
> 上传失败，请检查图床配置！

而我使用同样的配置在我老的图床工具客户端是可以上传的。请问是否windows客户端出现了bug? 烦请您测试一下~

感谢！

**Comment by WilliamHHH** [comment]
啊啊啊！ 是我的问题，客户端没毛病！

才发现任务栏图标处需要**右键设置默认图床**，软件默认的是微博图床，改成七牛的就可以上传啦！

感谢感谢！

**Comment by Molunerfinn** [comment]
👍 问题解决了就好~

**Comment by Molunerfinn** [comment]
回头我在主页面加一个设为默认图床的按钮吧，比较方便。
