### ISSUE TITLE
A bug For Windows

### ISSUE THREAD

**Issue by ifp1090** [Molunerfinn/PicGo#210]
## PicGo的相关信息

版本：2.0.5
平台：Win10

## 问题重现

之前一直用PicGo都是正常的，没有任何问题，非常流畅。
我设置的快捷健如下：
F1： 通过截图软件截图
F3： 上传图片
而当我升级到最新版的2.0.5后，我发现截图成功后，按上传快捷健F3弹出错误对话框！尝试改成其他的上传快捷健，也弹出错误对话框。
提升错误如下图：

截图如下：
https://i.loli.net/2019/03/25/5c98a4ce92cc8.jpg

## 功能请求

---

![Snipaste_2019-03-25_17-51-57](https://user-images.githubusercontent.com/24539845/54910268-ede3ed80-4f26-11e9-9a95-cb6c7dbf162c.jpg)

**Comment by Molunerfinn** [comment]
这个问题很奇怪，我这边的WIN10 + 2.0.5 无法复现，不知你重启电脑后是否还是会报错？

**Comment by ifp1090** [comment]
我重启电脑/删除后重装2.0.5、重装2.0.2均出现相同状况！推断是电脑问题。有时间重装系统后再试试看，谢谢！

**Comment by Molunerfinn** [comment]
很抱歉给你带来的困扰。重装WIN10后最好更新到最新或者较新的发行版然后再试试，如果依然有问题欢迎继续在本issue下回复！

**Comment by Molunerfinn** [comment]
就目前而言你可以先通过这个方法降级回2.0.3，应该就能恢复以前的使用了：
https://github.com/Molunerfinn/PicGo/issues/195/#issuecomment-471392914

**Comment by ifp1090** [comment]
非常感谢！ 回去我试试看。但是这个问题是在win10下出现的，能通过官方版本升级解决麽？

**Comment by Molunerfinn** [comment]
@ifp1090 我自己的WIN10是没问题的，你可以试试升级你的WIN10版本看看？以及我安装PicGo的时候有个选项，安装给自己还是安装给所有用户，我选的是所有用户，你也可以试试

**Comment by ifp1090** [comment]
你好！我按照你的方法删除相关文件后安装2.0.3，依然出现相同的弹窗！
http://prntscr.com/n5ng1u
看来只能重装试试啦？

**Comment by Molunerfinn** [comment]
@ifp1090 非常奇怪，这个报错理论上是没有POWERSHELL的权限...，请问一下你的windows账户是否有管理员权限呢？我今天正好要重装一下我实验室的Windows机器

**Comment by ifp1090** [comment]
我默认就是管理员呢，刚刚我又重新右键以管理员身份运行后依然不能快捷健上传， 奇怪。

**Comment by Molunerfinn** [comment]
@ifp1090 我下午会重装一下电脑的Windows10，如果没啥问题的话，你可以考虑使用我装的Windows10的版本，应该是最新的版本。
![image](https://user-images.githubusercontent.com/12621342/55300729-80c2e180-546b-11e9-8249-a1b3134a4dcf.png)

**Comment by ifp1090** [comment]
好的，感谢!

**Comment by Molunerfinn** [comment]
我下午重装了WIN10 2019年3月的更新版，装了PicGo 2.0.5，截图上传没问题

**Comment by ifp1090** [comment]
好的感谢！我这周马上装一下，测试之后告诉你结果哈~！

**Comment by Molunerfinn** [comment]
@ifp1090 OK的

**Comment by ifp1090** [comment]
你好！  我重新安装了Win10的系统，再重装2.0.5版的PicGo，发现之前提到的始终无法上传图片的Bug得到解决！ 
但具体原因我目前尚未找到。

**Comment by Molunerfinn** [comment]
@ifp1090 具体原因我也不太清楚，主要是我无法复现。总之解决了就好！

**Comment by ifp1090** [comment]
谢谢！
