### ISSUE TITLE
能否被Mac的App Store认可一下？

### ISSUE THREAD

**Issue by jearton** [Molunerfinn/PicGo#211]
在Mac上安装后打开，会提示来自不明身份的软件，需要去“安全与隐私”设置里，点仍要打开才可以。

**Comment by Molunerfinn** [comment]
没钱申请Mac的开发者啊，一年99刀，所以就没做Mac的签名。这个软件目前还是免费的，我还是个学生没有收入来源，很抱歉

**Comment by jearton** [comment]
同情加理解，希望能一直更新下去，已赞助

**Comment by Molunerfinn** [comment]
@jearton 感谢！
