### ISSUE TITLE
Ubuntu 上应用菜单中快捷方式的位置

### ISSUE THREAD

**Issue by yurjane** [Molunerfinn/PicGo#214]
## 问题类型

Feature Request

## PicGo的相关信息

ubuntu 18.04.2

## 功能请求

我更换了 picgo 的位置，需要修改应用菜单下快捷方式的指向，这个文件在哪里？

---

**Comment by Molunerfinn** [comment]
这个需要你自己去查appimage软件如何指定快捷方式指向。我没有ubuntu环境。
