### ISSUE TITLE
希望增加自动生成子目录功能，按日期命名

### ISSUE THREAD

**Issue by sean1990** [Molunerfinn/PicGo#216]
## 问题类型

Feature Request
## PicGo的相关信息

macOS，又拍云
## 功能请求
希望能按照按照日期或者月份命名路径，例如：www.xxxx.com/resources/yyyy/mm/dd 这种。目前所有的图片都是上传到同一个路径下，担心文件多了之后会影响性能。

---

**Comment by Molunerfinn** [comment]
不考虑，有特殊需求会交给插件做。另外，同一路径这个不影响性能

**Comment by mafeifan** [comment]
主要是为了增量备份，和方便按日期分类查看

**Comment by tanteng** [comment]
也希望有这个功能，在路径设置里，支持年月日的变量

**Comment by awaken233** [comment]
有相关的插件实现了该功能吗？方便告知下插件的名称吗？谢谢😁
