### ISSUE TITLE
picgo-setup-2.0.5.exe无法下载

### ISSUE THREAD

**Issue by xiaolin6** [Molunerfinn/PicGo#217]
## 问题类型
Bug Report

## PicGo的相关信息
2.0.5 Windows
-- 版本、所在平台（Mac或者Windows） -->

## 问题重现
无法下载
![image](https://user-images.githubusercontent.com/29225400/55241147-70e1ac80-5275-11e9-980d-4dedd4a9e04b.png)

## 功能请求

---

**Comment by xiaolin6** [comment]
![image](https://user-images.githubusercontent.com/29225400/55241245-a8e8ef80-5275-11e9-8dd8-342df9a5ed8d.png)

尝试了好几个网络，不知道是不是我电脑的问题

**Comment by Molunerfinn** [comment]
下载不了的请挂代理，这个我无法帮你解决。
