### ISSUE TITLE
能否添加个从单个URL或多个URL列表上传图片的功能

### ISSUE THREAD

**Issue by liub1934** [Molunerfinn/PicGo#218]
## 问题类型
Feature Request

## PicGo的相关信息
Windows、Mac

## 功能请求
建议添加个从URL上传的功能，支持单个URL和多个URL列表图片上传，方便将之前网站的图片通过URL形式批量导入上传。

---

**Comment by Molunerfinn** [comment]
这个不会在本体做，会交给插件实现。
