### ISSUE TITLE
[feature request]  请求增加启动方式配置

### ISSUE THREAD

**Issue by HarveyTvT** [Molunerfinn/PicGo#219]
## 问题类型

Feature Request

## PicGo的相关信息

os: windows 10 1809

## 功能请求

windows启动picgo，默认会在屏幕中央展示picgo悬浮窗，需要手动点击”最小化窗口“才能隐藏。请问是否可以增加开关控制启动方式，启动方式可选项建议为：展示悬浮窗，最小化窗口，详细窗口三种方式。thanks~~~

**Comment by Molunerfinn** [comment]
后续应该会加上隐藏窗口的设置。
