### ISSUE TITLE
guiApi.showNotificaiton 不起作用

### ISSUE THREAD

**Issue by upupming** [Molunerfinn/PicGo#220]
## 问题重现

PicGo 2.0.6 开发 plugin 时发现在 `handle` 内执行：

```js
guiApi.showNotificaiton({
    title: 'vscode-migrator',
    body: text
  })
```

无用，必须使用这样的代码才行：https://github.com/zWingz/picgo-plugin-github-plus/blob/master/index.ts#L20

## 功能请求

---

**Comment by upupming** [comment]
另外文档中写道直接把项目复制到 C 盘，这样不便于开发，会产生权限问题，`npm i` 经常出错。

建议修改文档，不必复制项目到 C 盘，而是修改安装方式，例如：

```js
 npm i D:\github\picgo-plugin-vscode-migrator
```

**Comment by Molunerfinn** [comment]
@upupming 你api写错了呀，不是 `showNotificaiton` 而是 `showNotification` -> 不是 `iton` 而是 `tion`。

测试插件项目的安装方式你说的对，实际上我后来也是使用这个方式开发的。我会尽快更新文档。

**Comment by upupming** [comment]
不好意思哈！我是直接复制的文档
https://picgo.github.io/PicGo-Core-Doc/zh/dev-guide/gui.html#shownotificaiton-option

**Comment by Molunerfinn** [comment]
@upupming 哈我也有锅

**Comment by Molunerfinn** [comment]
文档已更新
