### ISSUE TITLE
任意格式文件上传有插件吗？

### ISSUE THREAD

**Issue by ma3252788** [Molunerfinn/PicGo#221]
## 问题类型
Feature Request

## PicGo的相关信息
windows:v2.0.5

## 功能请求
希望能增加任意格式的文件上传，查看了之前的issue，发现作者说可以通过插件，我查了优质插件，没有发现，不知道作者说的插件是哪个呢？谢谢~

---

**Comment by Molunerfinn** [comment]
目前这个插件还没有人开发，希望有三方开发者来实现，
