### ISSUE TITLE
插件 debug 支持

### ISSUE THREAD

**Issue by upupming** [Molunerfinn/PicGo#224]
## 问题类型

Feature Request

## PicGo的相关信息

Any

## 问题重现

None

## 功能请求

插件开发是否可以像 vscode 一样提供一个 DEBUG CONSOLE，这样能够更好地定位错误信息。

---

**Comment by Molunerfinn** [comment]
可以通过命令行运行PicGo.exe，然后查看console。另外下个版本的PicGo支持本地日志打印，也可以通过查看本地日志来查看。

参考：https://github.com/Molunerfinn/PicGo/issues/195#issuecomment-471386156

**Comment by upupming** [comment]
嗯！
