### ISSUE TITLE
more than guiApi

### ISSUE THREAD

**Issue by upupming** [Molunerfinn/PicGo#225]
## 问题类型

Feature Request

## PicGo的相关信息

All

## 问题重现

None

## 功能请求

请问如果要实现自主的界面，比如说 [picgo-plugin-vscode-migrator](https://github.com/upupming/picgo-plugin-vscode-migrator) 想要在点击 `import...` 之后打开一个新的界面，这样用户可以自行选择 `vs-picgo` 里的图片应该保留，哪些应该 import，然后在 import 过程中显示进度条（类似于PicGo 的【上传区】）等等，这样能否实现？

guiApi 会提供这样的 API 吗？还是插件开发者必须自己创建新的 UI 界面。

---

**Comment by Molunerfinn** [comment]
目前这个你可以通过自己创建一个Web页面来实现。

PicGo的UI界面支持度会放在一些内置组件里。比如之后可能会有 `进度条` 组件，`上传面板` 组件等。
以及下个版本会有的 `插件快捷键` 系统。目前来说，自定义UI一个是在实现上难度比较大，另一个是PicGo的插件本身更注重的部分不是用来做页面扩展，而是做功能扩展的，所以在UI界面支持度上会相对保守。
所以如果要完全写一个目前的guiApi实现不了的界面，可以考虑自己写一个页面，然后通过插件去打开这个页面来实现功能。

**Comment by upupming** [comment]
谢谢您的耐心解答，我有空再尝试～
PicGo is promising!
