### ISSUE TITLE
HEIC格式

### ISSUE THREAD

**Issue by Yaanco** [Molunerfinn/PicGo#226]
## 问题类型

1、您好，HEIC格式的图片在Github图床上可以上传吗？
2、有个问题，当复制了一张图片没有上传的时候（图片格式为HEIC），点击菜单栏的小logo图标，就会卡顿10秒左右才会出来界面，每次点击都一样，除非复制其他格式图片

## PicGo的相关信息

Mac10.14.4 ，2.0.4版本

**Comment by Molunerfinn** [comment]
HEIC不支持，因为这个格式目前并没有办法直接读取。

卡住的原因是electron将HEIC转成可读的图片格式需要很长的计算时间。

估计需要插件支持才行，目前不推荐使用HEIC来传输，还是推荐转成jpg。
