### ISSUE TITLE
上传图片成功后返回的图片url错误

### ISSUE THREAD

**Issue by soulseen** [Molunerfinn/PicGo#228]
## 问题类型

Bug Report

## PicGo的相关信息

PicGo版本：2.0.3 和 2.0.4
OS: MacOS 10.14.3

## 问题重现

使用青云 qingstor插件上传成功图片后，显示的url错误。
![image](https://user-images.githubusercontent.com/16031013/55850680-f293dd00-5b87-11e9-8237-4dbe20047509.png)
<img width="797" alt="WechatIMG77" src="https://user-images.githubusercontent.com/16031013/55850770-6504bd00-5b88-11e9-8077-faf58a9f3303.png">
需要手动修改路径中的undefined才能显示
![image](https://user-images.githubusercontent.com/16031013/55850787-7bab1400-5b88-11e9-88b2-deb89e6195cb.png)

**Comment by Molunerfinn** [comment]
这个不是PicGo的问题，是插件的问题，请你去插件仓库提交问题：
https://github.com/chengww5217/picgo-plugin-qingstor-uploader/issues
