### ISSUE TITLE
mac 2.04 截屏到剪贴板无法上传

### ISSUE THREAD

**Issue by Alalalalaki** [Molunerfinn/PicGo#229]
Bug Report

PicGo 2.04 Mac

系统直接截屏到剪贴板后一直在等待上传无法上传。点击剪贴板图片上传也没用。手动拖图可以上传。

**Comment by Molunerfinn** [comment]
请查看这个issue：
https://github.com/Molunerfinn/PicGo/issues/199，并在那个issue下反馈
