### ISSUE TITLE
生成的图片名格式不优雅

### ISSUE THREAD

**Issue by liutf** [Molunerfinn/PicGo#23]
> 首先感谢作者的贡献，用了下觉得各方面都不错。但是发现图片的名称不够优雅。希望能优化下。

* 目前
http://p2oheco53.bkt.clouddn.com/2018-2-23-16:27:21.png

* 期望
https://ws1.sinaimg.cn/large/006ctfxYgy1fo807om1naj30tw0l8tcy.jpg
或
http://p2oheco53.bkt.clouddn.com/201802071608_847.png

**Comment by Molunerfinn** [comment]
微博图床的URL是微博自动生成的，无法修改。
其他图床的默认文件名目前格式是`YYYY-MM-DD-HH:mm:ss`，确实不太好看。将考虑改成截图软件普遍的`YYYYMMDDHHmmss`格式。下一版应该会修改。

**Comment by oopp1800** [comment]
同样有该请求，这里提供一下我的使用场景，希望作者能稍稍提高下本需求的优先级 :)

我是在 Zotero 软件中使用以上传图片，该软件会根据粘贴的链接地址自动判断是否为图片并插入，但目前使用 PicGo 的新浪图床与七牛图床均无法成功插入图片。
经过多次实验结论如下：
- 新浪图床结尾不含 `.jpg`（手动添加 `.jpg` 并复制后可成功插入）
- 七牛图床格式为 `YYYY-MM-DD-HH:mm:ss`，可能因为格式问题（比如链接中包含 `:` 符号等）导致 Zotero 不解析，手动删除中间符号后验证可用

虽然这些问题都不是由 PicGo 引发的，也完全不是 PicGo 的 Bug，但既然看到了有这样一个 issue 不禁上来补一嘴，希望 PicGo 能更加完善 :smile:

**Comment by Molunerfinn** [comment]
@oopp1800 嗯你说的这两个问题下个版本已经明确会改进。目前的计划是未来的一至两周内更新下个小版本。

**Comment by Molunerfinn** [comment]
v1.4.2版本已经支持。

**Comment by liutf** [comment]
感谢作者更新，试了下，发现v1.4.2生成文件名里貌似有点小问题。`undefined` 
生成的如下：
* `![](http://p2oheco53.bkt.clouddn.com/undefined20180312102518.png)`
![](http://p2oheco53.bkt.clouddn.com/undefined20180312102518.png)

**Comment by Molunerfinn** [comment]
这个bug已经锁定了。在下次更新之前，你可以简单的：
![image](https://user-images.githubusercontent.com/12621342/37263708-567686cc-25e4-11e8-914c-4e42a226a50a.png)
点击一下七牛图床设置界面的确定，然后再上传文件就不会出现这个问题了。

**Comment by liutf** [comment]
ok, thx!
