### ISSUE TITLE
七牛云不支持东南亚的 bucket

### ISSUE THREAD

**Issue by imfht** [Molunerfinn/PicGo#230]
## 问题类型

Bug Report

## PicGo的相关信息

macOS  2.0.4

## 问题重现
![image](https://user-images.githubusercontent.com/15059493/55932315-ce093500-5c5b-11e9-8a82-f6c884c99444.png)

## 功能请求

目前从 Github 下载的最新版本的七牛云存储区域只有 华东、华北、华南、北美。
在七牛云的官方页面显示有东南亚区域 --> https://developer.qiniu.com/kodo/manual/1671/region-endpoint
![image](https://user-images.githubusercontent.com/15059493/55932353-e5e0b900-5c5b-11e9-8aaa-06cb3a1e1f75.png)
建议增加次区域的bucket 支持

**Comment by Molunerfinn** [comment]
之后会把七牛云的区域选择改成输入的形式，这样以后七牛云再增加区域也没事了。

目前而言你可以打开配置文件，然后把配置文件里七牛的区域那一项改成 `as0` 即可使用。
