### ISSUE TITLE
还在吗？release的下载链接在amazonaws.com的服务器上，国内下载速度很慢，几kb一秒

### ISSUE THREAD

**Issue by COCO5666** [Molunerfinn/PicGo#231]
还在吗？release的下载链接在amazonaws.com的服务器上，国内下载速度很慢，几kb一秒，你放了之后就没有自己下载测试吗？

**Comment by Molunerfinn** [comment]
抱歉，如果你觉得下载速度很慢你可以手动本地构建。另外我有代理下载速度很快。
