### ISSUE TITLE
PicGo 已经可以通过 Homebrew Cask 安装了

### ISSUE THREAD

**Issue by womeimingzi11** [Molunerfinn/PicGo#233]
## 问题类型
Feature Request

## PicGo的相关信息
Mac

## 功能请求
PicGo 已经提交至 Homebrew Cask 且已经并入 Master 主分支。

使用下列命令可以安装 PicGo

>brew cask install picgo

PS. 因为 Release 页面中仅 2.0.4 提供了 Mac 端的 zip 档，因此目前 Cask 版本为 2.0.4

---

**Comment by Molunerfinn** [comment]
@womeimingzi11 非常感谢！之后会在README里提及你的贡献！

**Comment by Molunerfinn** [comment]
如果今后有时间也希望能持续帮忙更新cask源哈哈~

**Comment by womeimingzi11** [comment]
更新源没有问题啦！

感谢开发了如此好用的应用！我只是做了力所能及的小工作！

PiEgg <notifications@github.com> 于2019年4月12日周五 上午10:49写道：

**Comment by Molunerfinn** [comment]
感谢！文档已更新~

**Comment by womeimingzi11** [comment]
非常荣幸！

PiEgg <notifications@github.com> 于2019年4月12日周五 上午10:59写道：
