### ISSUE TITLE
是否考虑,增加开启启动后自动隐藏悬浮球的设置?

### ISSUE THREAD

**Issue by y761350477** [Molunerfinn/PicGo#234]
PicGo设置自启后,会显示悬浮球,而这个我一般用不到,每次手动隐藏也挺麻烦的,希望作者在设置里面增加隐藏的功能,另外设置快捷键进行唤出,谢谢!

**Comment by Molunerfinn** [comment]
下个版本会默认隐藏

**Comment by MakerFace** [comment]
Linux 2.3.0启动后没有自动隐藏，是否有命令行参数可以在启动时隐藏呢？

启动方式：
./PicGo-2.3.0.AppImage
