### ISSUE TITLE
github 请检查配置和上传的文件是否符合要求

### ISSUE THREAD

**Issue by haroel** [Molunerfinn/PicGo#235]
## 问题类型

github配置了token和仓库，但是上传一直提示“请检查配置和上传的文件是否符合要求”

## PicGo的相关信息

macOS 10.14  v2.0.4版本
![AC6B764D-6E4D-479B-9887-D01B69BD7027](https://user-images.githubusercontent.com/2418222/56104760-bdaece00-5f6b-11e9-8dfd-40b687a8f42a.png)

## 问题重现

![image](https://user-images.githubusercontent.com/2418222/56104792-d4552500-5f6b-11e9-9393-fbe5bdcf99be.png)

## 功能请求

---

**Comment by Molunerfinn** [comment]
仓库名配错了。看看文档吧：
https://picgo.github.io/PicGo-Doc/zh/guide/config.html#github图床

**Comment by shiwenyuan** [comment]
@Molunerfinn 我今天也遇到了这个问题 ，基于github的图床，在mac自带显示屏的截图可以上传上去   外扩屏的接图上传不上去，上传不上去的就报错`请检查配置和上传的文件是否符合要求`， 是分辨率的问题吗，下图是我两个显示器的分辨率
![image](https://user-images.githubusercontent.com/29530604/69304791-e531eb80-0c5c-11ea-9cde-da60f2c920e9.png)
之前用的外扩屏就没有问题，之前的外扩屏分辨率是1960*1080的，上图外扩屏是最近新买的

**Comment by Molunerfinn** [comment]
@shiwenyuan 不是分辨率的问题
![image](https://user-images.githubusercontent.com/12621342/69306715-71dfa800-0c63-11ea-8c9e-29377d763472.png)

**Comment by PanfengChen** [comment]
我的也是因为外接显示器的问题导致的。
