### ISSUE TITLE
picgo 2.1.0 详细窗口无法上传图片

### ISSUE THREAD

**Issue by zeroskylian** [Molunerfinn/PicGo#236]
## 是不是bug

picgo 2.1.0 详细窗口无法上传图片

## PicGo的相关信息
mac OS 10.14.4

## 问题重现
![](http://qiniu.wretchant.com/picgo/picgo_bug.gif)

**Comment by Molunerfinn** [comment]
嗯这个问题2.1.1马上修复。过10分钟即可更新

**Comment by Molunerfinn** [comment]
很抱歉，这个bug是上线前的一个疏忽！现在2.1.1修复版本已经发布，可以更新了
