### ISSUE TITLE
设置界面无法显示

### ISSUE THREAD

**Issue by itodouble** [Molunerfinn/PicGo#237]
## PicGo的相关信息
win10  picgo2.1.1

## 问题重现

![image](https://user-images.githubusercontent.com/13508120/56253381-af3cef80-60ee-11e9-9f0f-97add80769e7.png)

**Comment by itodouble** [comment]
![image](https://user-images.githubusercontent.com/13508120/56253520-499d3300-60ef-11e9-9160-04cbd7b5c6b6.png)

**Comment by Molunerfinn** [comment]
退了重开还是这样么？我这边是可以的。
logs文件夹是空的，因为picgo的log是写在`picgo.log`里的

**Comment by Molunerfinn** [comment]
![image](https://user-images.githubusercontent.com/12621342/56253550-705b6980-60ef-11e9-873f-88a65e08e827.png)

**Comment by Molunerfinn** [comment]
界面相关的不会出现在log里，log里只会显示上传流程中的日志

**Comment by itodouble** [comment]
重开还是这样的 我是昨天遇到的 我本来是想修改 "设置日志文件"的 我点开后没有修改 点击的保存无法保存然后点击取消就成这样了

**Comment by Molunerfinn** [comment]
@itodouble 收到，我手动复现一下

**Comment by Molunerfinn** [comment]
@itodouble 复现不成功，你把你的配置文件截个图？
![image](https://user-images.githubusercontent.com/12621342/56253725-3343a700-60f0-11e9-99dd-79734baa9c90.png)

**Comment by Molunerfinn** [comment]
可以把一些关键的图床配置信息隐去，只保留本体的配置就行。如果是配置文件的问题你那边出问题我应该用同样的配置也会出问题

**Comment by itodouble** [comment]
![image](https://user-images.githubusercontent.com/13508120/56253917-19569400-60f1-11e9-9fa3-3f4e57bf7176.png)

**Comment by Molunerfinn** [comment]
OK，复现成功，你只需把`"logLevel": "all"`改成`"logLevel": ["all"]`即可

**Comment by Molunerfinn** [comment]
下个版本我会给这个地方做个判断避免再次出这个问题
