### ISSUE TITLE
升级到2.1.1后再次出现快捷键上传失效！

### ISSUE THREAD

**Issue by ifp1090** [Molunerfinn/PicGo#238]
Win10  

昨天使用2.1.0一切正常，今早弹出要升级到2.1.1，于是点击自动升级。
升级后再次出现之前我重装系统之前的问题，无法通过自定义快捷键上传！
![](https://i.loli.net/2019/04/17/5cb6972d36620.png)

卸载2.1.1后安装2.1.0版本还是不行，当我按下自定义快捷键时，依然弹出这个错误窗口！

**Comment by Molunerfinn** [comment]
这个真是很奇怪了...我是始终无法复现的。

2.1.1支持命令行来上传，你可以看看用命令行调用是否依然是这个报错：找到你PicGo安装的目录，然后截一张图，然后输入`.\PicGo.exe upload`

![image](https://user-images.githubusercontent.com/12621342/56258194-47dc6b00-6101-11e9-8be4-4f4415107b94.png)

**Comment by Molunerfinn** [comment]
![image](https://user-images.githubusercontent.com/12621342/56258274-8a05ac80-6101-11e9-9a43-8a9ee0978ca1.png)
找到一个解决办法，你需要在你系统的环境变量里加入`Powershell`的路径

**Comment by Molunerfinn** [comment]
![image](https://user-images.githubusercontent.com/12621342/56258311-b4f00080-6101-11e9-8cec-fb08598772fc.png)

**Comment by Molunerfinn** [comment]
参考：https://github.com/felixrieseberg/windows-build-tools/issues/20

**Comment by ifp1090** [comment]
通过命令行依然弹出错误。
![](https://i.loli.net/2019/04/17/5cb69b3684a9b.png)
另外我发现我本来就有这个路径？
![](https://i.loli.net/2019/04/17/5cb69c6d789af.png)
我尝试加入了引用中的路径：
![](https://i.loli.net/2019/04/17/5cb69cc17fdde.png)
但依然不行。

**Comment by Molunerfinn** [comment]
引入这个路径之后你点击确定。然后你打开cmd，然后输入`powershell`，看看会报错么

**Comment by Molunerfinn** [comment]
![image](https://user-images.githubusercontent.com/12621342/56258913-cdf9b100-6103-11e9-9494-92f2599e0cfd.png)

**Comment by Molunerfinn** [comment]
以及你进入上述目录，是否能看到`powershell.exe`呢？PicGo的截图上传调用了`powershell.exe`，如果它不存在自然就无法调用了。
![image](https://user-images.githubusercontent.com/12621342/56258944-f1246080-6103-11e9-9038-2c25cc171e06.png)

**Comment by ifp1090** [comment]
![image](https://user-images.githubusercontent.com/24539845/56259022-38125600-6104-11e9-9c28-df2ab9636cfb.png)

没有报错。

**Comment by ifp1090** [comment]
有这个文件呢
![image](https://user-images.githubusercontent.com/24539845/56259077-698b2180-6104-11e9-8812-aff58e6a6a59.png)

**Comment by Molunerfinn** [comment]
很奇怪，按理说正常的话不应该报这个错误，而且2.1.1和2.1.0仅变动了一行代码，跟powershell脚本无关。所以我还是很疑惑，这个报错理论上是node找不到powershell这个命令所以无法运行报的错。你重装系统前和这次重装后升级PicGo的前后有没有做一些同样的事导致了这个报错呢

**Comment by Molunerfinn** [comment]
重启之后依然这样么

**Comment by ifp1090** [comment]
没有呢，今早开机就弹出升级，我马上点击升级，于是出错，彻底卸载后安装上一版，也类似。我也觉得很奇怪！
重装试过，不行。

**Comment by Molunerfinn** [comment]
昨天使用的时候有做哪些操作么，比如装了某些软件之类的。这个报错的原因就是PicGo找不到powershell这个命令报的错，感觉有点无力。如果你自己平时使用的更多是截图上传倒是可以降回1.6.2，那个用的截图上传是electron自带的，不过限制相对大一点。不能复制图片文件然后上传。只能复制图片内容上传

**Comment by Molunerfinn** [comment]
我将考虑在2.2版本里加入一个配置选项开关，用于选择`使用Electron自带的api捕获截图`或者`使用PicGo内置的脚本进行截图捕获`。这样如果在使用PicGo脚本报错的情况下可以选择回退到以前的上传方式。

不过你的这个问题我依然无法复现，真的很奇怪。就目前而言你可以考虑先降级回1.6.2的版本，这个版本的截图上传是用的Electron自带的api实现的。很抱歉对你造成的困扰！

**Comment by ifp1090** [comment]
你好！经过测试回退到1.6.2版本使用正常！能够正常使用快捷键！谢谢！

**Comment by xwjahahahaha** [comment]
我现在使用2.3.0版本，也出现了同样的问题...
