### ISSUE TITLE
PicGo 设置日志等级后无法关闭 重启后就出现以下界面 无法进行设置

### ISSUE THREAD

**Issue by CoderTonyChan** [Molunerfinn/PicGo#240]
## 问题类型

Bug Report

## PicGo的相关信息

Mac

## 问题重现

PicGo 设置日志等级后无法关闭 重启后就出现以下界面 无法进行设置

![image](https://user-images.githubusercontent.com/16996753/56345194-b993e200-61f1-11e9-982a-5601dae00cab.png)

**Comment by Molunerfinn** [comment]
参考这个[issue](https://github.com/Molunerfinn/PicGo/issues/237)

`logLevel`字段必须是数组。这个bug下个版本会修复

**Comment by CoderTonyChan** [comment]
不习惯看closed中的issue 看了一下open的无相关issue就发了

另外问问 是否有导出 `~/Library/Application\ Support/picgo/data.json`中uploaded的数据 

Feature : 我觉得可以有一个功能备份到iCloud中

**Comment by Molunerfinn** [comment]
@CoderTonyChan 这个会交给插件来实现。目前的构想是可以通过GitHub私人仓库来同步。不过最近这段时间我没有时间开发插件，所以需要看看有没有人有兴趣来给PicGo写插件了。

**Comment by CoderTonyChan** [comment]
@Molunerfinn smms上传的图片 可以在uploaded中的数据加上delete字段: 例如 "https://sm.ms/api/delete/nLbCw63NheaiJp1"

**Comment by Molunerfinn** [comment]
图床之间的差异不会反应在这些字段上，相应的上传记录项应该是统一的。而且也只有SMMS有delete字段，其他图床没有这也不合适。如果想做同步删除，PicGo有暴露`remove`事件，自行开发插件监听并删除即可。
因为有些图床是无法删除图片的，比如微博图床。

**Comment by Molunerfinn** [comment]
这个插件就是一个例子：https://github.com/zWingz/picgo-plugin-github-plus
