### ISSUE TITLE
Mac上不能打开设置详情页面

### ISSUE THREAD

**Issue by CodeXey** [Molunerfinn/PicGo#241]
## 问题类型
Bug Report

## PicGo的相关信息
PicGo Version:2.1.1, MacOS Version:10.14.4

## 问题重现
不能打开设置详情页面，右键状态栏图标，只有打开小窗口。
<img width="192" alt="image" src="https://user-images.githubusercontent.com/12522976/56407926-9118f000-62a4-11e9-89f1-28921c56d45e.png">

---

**Comment by Molunerfinn** [comment]
你右键状态栏图标没反应？左键点击状态栏图标是打开小窗口，右键是菜单呀
![image](https://user-images.githubusercontent.com/12621342/56408204-dc7fce00-62a5-11e9-8d76-261889fdb12b.png)

**Comment by Molunerfinn** [comment]
这个现象我无法复现，请确认是否鼠标右键位有所更改？或者试试用触摸板双指单击（模拟右键）呢

**Comment by CodeXey** [comment]
> 你右键状态栏图标没反应？左键点击状态栏图标是打开小窗口，右键是菜单呀
> ![image](https://user-images.githubusercontent.com/12621342/56408204-dc7fce00-62a5-11e9-8d76-261889fdb12b.png)

是的，我目前没使用鼠标，Control加触控板是不会触发的，刚上网查了下，双指点按是可以的
