### ISSUE TITLE
vscode的2.0.3版本，从粘贴板上传图片一直显示Uploading...

### ISSUE THREAD

**Issue by CatcherX** [Molunerfinn/PicGo#242]
## 问题类型

Bug Report

## PicGo的相关信息

Version: 1.33.1 (user setup)
Commit: 51b0b28134d51361cf996d2f0a1c698247aeabd8
Date: 2019-04-11T08:27:14.102Z
Electron: 3.1.6
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 6.1.7601
PicGo插件版本：2.0.3
## 问题重现
按Ctrl + Alt + O，vscode提示：Uploading...
查看日志，没记录。
从窗口选择文件上传则是正常的。

## 功能请求

正常上传

**Comment by Molunerfinn** [comment]
请去vs-picgo的仓库反馈。
