### ISSUE TITLE
windows下剪贴板上传失败

### ISSUE THREAD

**Issue by gengdd** [Molunerfinn/PicGo#243]
## 问题类型

win10剪贴板上传失败。前几天还可以使用，昨天突然无法使用，更新到最新版本依然无法使用。不知道是否和我电脑的环境变量被清空有关。

## PicGo的相关信息

版本：2.1.2
平台：Win10
## 问题重现
只在issues看到mac的类似问题。
![](https://i.loli.net/2019/04/23/5cbe7e3f75421.png)

## 功能请求

---

**Comment by Molunerfinn** [comment]
有关，你加上powershell的环境变量即可。
![image](https://user-images.githubusercontent.com/12621342/56549863-8ae18700-65b6-11e9-92c1-8e0b48d54a60.png)

**Comment by Molunerfinn** [comment]
C:\Windows\System32\WindowsPowerShell\v1.0\

**Comment by Molunerfinn** [comment]
加上之后可能需要重启电脑以生效

**Comment by gengdd** [comment]
@Molunerfinn  问题已解决，多谢及时回复，万分感谢！！！

**Comment by zops** [comment]
非常感谢！已解决！
