### ISSUE TITLE
最新版在 Mac 上安装错误

### ISSUE THREAD

**Issue by jdhao** [Molunerfinn/PicGo#244]
## 问题类型

Bug Report

## PicGo的相关信息

+ 版本： 2.1.2
+ 平台： Mac Mojave

## 问题重现

下载最新版 picgo dmg 安装包，打开以后提示需要在系统的安全设置那里打开，在安全设置里面，选择「仍要打开」，
![image](https://user-images.githubusercontent.com/16662357/56605351-83fa5900-6636-11e9-821e-39051ff809b5.png)

然后出现错误

> 未能完成该操作，（OSStatus 错误 99999）

![image](https://user-images.githubusercontent.com/16662357/56605398-aa1ff900-6636-11e9-82cb-012b9f81cb64.png)

重新安装 2.0.3 版本，打开没有这个问题。

**Comment by jdhao** [comment]
按照[这里](https://github.com/KLayout/klayout/issues/137#issuecomment-400186371) 给出方法，运行下面的命令：

```
xattr -dr com.apple.quarantine /Applications/PicGo.app
```

可以打开最新版了，不知道具体哪里出了问题。

**Comment by Molunerfinn** [comment]
因为没钱买苹果开发者账号，所以应用没签名。
