### ISSUE TITLE
能否提供类似created的生命周期

### ISSUE THREAD

**Issue by zWingz** [Molunerfinn/PicGo#245]
## 问题类型

feature request

## 功能请求

希望提供`created`生命周期, 用以处理启动时候的初始化
比如

- `api`初始化
- 图片相关数据初始化(拉取远端数据)

**Comment by Molunerfinn** [comment]
这个还需要规划。因为这个其实已经跟生命周期仅在上传阶段生效的初衷有所背驰。所以之后还需要设计。目前还是需要让用户手动去触发相应的操作。

**Comment by zWingz** [comment]
如果能在启动时候执行一些操作, 就免去不少数据同步问题了.
