### ISSUE TITLE
macOS看不到顶部栏图标

### ISSUE THREAD

**Issue by billbillHao** [Molunerfinn/PicGo#247]
## 问题类型

mac 看不到状态栏图标..... 我确定已经开启
![image](https://user-images.githubusercontent.com/20323504/56729791-adc39500-6788-11e9-943e-260d17348354.png)

## 问题重现

![image](https://user-images.githubusercontent.com/20323504/56729798-b1efb280-6788-11e9-90c6-e337c586ded5.png)

## 功能请求

---

**Comment by Molunerfinn** [comment]
macOS没有状态栏图标，只有顶部栏图标。如果要打开详细窗口，请在顶部栏图标处右键，「打开详细窗口」
![image](https://user-images.githubusercontent.com/12621342/56731340-d483ca80-678c-11e9-8aa0-9a83fcf4c45c.png)

**Comment by yeshiqing** [comment]
@Molunerfinn 你好！
我喜欢精简 Mac 的顶部栏图标，结果按住 `command` 拖动鼠标，不小心把 PicGo 的顶部栏图标给弄丢了。即使重新打开应用，也没法出现图标，请问该怎么找回顶部栏图标？
（BTW，不想新开 Issue 了，所以在这里问，盼复！）

**Comment by Molunerfinn** [comment]
> @Molunerfinn 你好！ 我喜欢精简 Mac 的顶部栏图标，结果按住 `command` 拖动鼠标，不小心把 PicGo 的顶部栏图标给弄丢了。即使重新打开应用，也没法出现图标，请问该怎么找回顶部栏图标？ （BTW，不想新开 Issue 了，所以在这里问，盼复！）

尝试重启电脑后再打开应用。如果还不存在可以尝试使用一些顶部栏管理应用来处理。你这种情况应该不是只有picgo会出现，应该是个通用的操作

**Comment by yeshiqing** [comment]
谢谢，问题解决了。顶部栏管理应用：Dozer、Bartender 我都试了，它们对这类问题无效。

抱歉！实际上 PicGo 不会出现这个问题。我是 Clipy.app 出现图标消失的情况，最终通过 `defaults` 命令重现了图标。
```shell
defaults delete com.clipy-app.Clipy kCPYPrefShowStatusItemKey
```
