### ISSUE TITLE
同步删除的插件只对github图床有效果吗

### ISSUE THREAD

**Issue by Nisekoi5** [Molunerfinn/PicGo#248]
想同步删除上传的图片，于是翻了很久issue，发现似乎有插件可以实现，接着我就去安装了github-plus插件。但是好像不能同步删除阿里OSS上传的图片。 是我的操作方法有问题，还是插件不支持呢

---

**Comment by Molunerfinn** [comment]
是的，插件不支持。欢迎贡献插件


 :octocat: [From gitme iOS](http://flutterchina.club/app/gm.html)
