### ISSUE TITLE
我想问的是  macos 顶部看不到顶部栏图标

### ISSUE THREAD

**Issue by billbillHao** [Molunerfinn/PicGo#249]
## 问题类型

我想问的是  macos 顶部看不到顶部栏图标

## PicGo的相关信息
mac os 看不到顶部栏图标 我确定 picgo是开启的

## 问题重现

![image](https://user-images.githubusercontent.com/20323504/56777436-36cbe200-6804-11e9-97f8-a6e8d1e5887c.png)
![image](https://user-images.githubusercontent.com/20323504/56777446-3f241d00-6804-11e9-8c13-83cf7d35b09a.png)

## 功能请求

---

**Comment by Molunerfinn** [comment]
那可能是你顶部栏图标太多放不下了...试着退掉几个顶部栏应用再看看

**Comment by billbillHao** [comment]
关了好多也没出来

**Comment by Molunerfinn** [comment]
那就不知道了，我无法复现

**Comment by billbillHao** [comment]
辅助功能我都给他打开了- - 是我系统太高了么..

**Comment by billbillHao** [comment]
嗨呀好气- -

**Comment by Molunerfinn** [comment]
我的系统是10.14.4，应该也是最新的。你可以试试一些顶部栏图标整理的工具，没准能看到

**Comment by billbillHao** [comment]
我重启一下


发自我的iPhone

------------------ 原始邮件 ------------------
发件人: PiEgg <notifications@github.com>
发送时间: 2019年4月26日 09:53
收件人: Molunerfinn/PicGo <PicGo@noreply.github.com>
抄送: billbillHao <354250377@qq.com>, Author <author@noreply.github.com>
主题: 回复：[Molunerfinn/PicGo] 我想问的是  macos 顶部看不到顶部栏图标 (#249)




我的系统是10.14.4，应该也是最新的。你可以试试一些顶部栏图标整理的工具，没准能看到

**Comment by billbillHao** [comment]
哦了  重启一下就粗线了!!picGo 牛逼!!!!!!!!!!!

**Comment by Molunerfinn** [comment]
OK~
