### ISSUE TITLE
2.1.2 版本在 Mac 下无法上传剪切板图片

### ISSUE THREAD

**Issue by plokmju88** [Molunerfinn/PicGo#251]
用截图工具截图进剪切板，使用 PicGo 无法上传，将文件保存到本地，直接复制文件再上传，可以成功。

PicGo 版本：2.1.2
Mac OS：10.12.3

**Comment by Molunerfinn** [comment]
看看这个[issue](https://github.com/Molunerfinn/PicGo/issues/199)，并给出更详细的日志。你可以在PicGo的「PicGo设置」页面打开log文件：
![image](https://user-images.githubusercontent.com/12621342/56787132-23ce0780-682e-11e9-8fcb-5bc3e83a99b0.png)


![image](https://user-images.githubusercontent.com/12621342/56787128-1dd82680-682e-11e9-9445-1f8292c9b74d.png)

**Comment by plokmju88** [comment]
最新的剪切板错误日志如下：

------Error Stack Begin------
undefined
-------Error Stack End-------
2019-04-26 14:13:16 [PicGo ERROR] 
Error creating a JP2 color space from ICC profile.
Falling back to sRGB

------Error Stack Begin------
undefined
-------Error Stack End-------
2019-04-26 14:24:28 [PicGo ERROR] 
Error creating a JP2 color space from ICC profile.
Falling back to sRGB

------Error Stack Begin------
undefined
-------Error Stack End-------
2019-04-26 14:24:55 [PicGo ERROR] 
Error creating a JP2 color space from ICC profile.
Falling back to sRGB

------Error Stack Begin------
undefined
-------Error Stack End-------

**Comment by Molunerfinn** [comment]
嗯，那你就按照那个issue里的方法改一下描述文件应该就行了。
https://github.com/Molunerfinn/PicGo/issues/199#issuecomment-471890683
![image](https://user-images.githubusercontent.com/12621342/56787567-84117900-682f-11e9-85b9-b48d0843e571.png)

**Comment by plokmju88** [comment]
谢谢，按照这个方式是可以解决的。
