### ISSUE TITLE
新浪图床图片无法显示

### ISSUE THREAD

**Issue by HarborZeng** [Molunerfinn/PicGo#253]
## 问题类型

Bug Report

## PicGo的相关信息

全平台所有版本，话说这个问题和picgo软件没有什么关系

## 问题重现

![Screenshot_2019-04-26-22-45-55-983_com android chrome](https://user-images.githubusercontent.com/8568937/56845823-bb4c5c80-68f9-11e9-9f83-cb235b616b31.png)
![Screenshot_2019-04-27-14-36-39-729_com android chrome](https://user-images.githubusercontent.com/8568937/56845842-f058af00-68f9-11e9-8e6d-6a8b3fefbb2a.png)

您好，首先非常感谢您开发的这个非常好用的软件。我已经查阅了常见问题列表，现在的问题就是新浪图床的图片无法展示，看起来好像是加了防盗链的功能。但是此仓库的主页仍然显示着支持新浪图床，如果新浪图床不再被支持了，那么应该移除。

不知道您是否有其他支持多分辨率的图床推荐？

**Comment by Molunerfinn** [comment]
支持是支持的- -只是人家做了防盗链...我近期会在项目主页上声明一下。

多分辨率的图床我并不知道多少，你可以看看七牛，他家貌似有一些图片处理的接口可以实现裁剪或者质量压缩。
