### ISSUE TITLE
win10直接上传失败，说配置错误或文件错误

### ISSUE THREAD

**Issue by TheCryingGame** [Molunerfinn/PicGo#254]
## 问题类型
Feature Request

## PicGo的相关信息

Windows
## 问题重现

win10直接上传失败，说配置错误或文件错误
![](https://oss.imangie.com/superbed/2019/04/27/5cc42dd63a213b04171888eb.png)
## 功能请求
都是配置好了的，不知道什么情况

---

**Comment by Molunerfinn** [comment]
哪个图床？配置长啥样？给点具体信息…一般都是你自己配置错了…

**Comment by Molunerfinn** [comment]
可以在设置页面打开配置文件检查配置信息，是不是多了或者少了什么字符，比如多了空格

**Comment by TheCryingGame** [comment]
> 哪个图床？配置长啥样？给点具体信息…一般都是你自己配置错了…

![](https://oss.imangie.com/superbed/2019/04/27/5cc4308d3a213b041718b72f.png)

**Comment by TheCryingGame** [comment]
> 可以在设置页面打开配置文件检查配置信息，是不是多了或者少了什么字符，比如多了空格

![QQ图片20190427183541](https://user-images.githubusercontent.com/48227194/56848442-98cb3b00-691b-11e9-809c-b25fd277a4e1.png)

**Comment by TheCryingGame** [comment]
> 可以在设置页面打开配置文件检查配置信息，是不是多了或者少了什么字符，比如多了空格

![QQ图片20190427183919](https://user-images.githubusercontent.com/48227194/56848455-d3cd6e80-691b-11e9-93a9-6dd7d1ffa8ee.png)

**Comment by TheCryingGame** [comment]
> > 可以在设置页面打开配置文件检查配置信息，是不是多了或者少了什么字符，比如多了空格
> 
> ![QQ图片20190427183541](https://user-images.githubusercontent.com/48227194/56848442-98cb3b00-691b-11e9-809c-b25fd277a4e1.png)



> 可以在设置页面打开配置文件检查配置信息，是不是多了或者少了什么字符，比如多了空格

![QQ图片20190427184040](https://user-images.githubusercontent.com/48227194/56848463-04150d00-691c-11e9-9e36-212954d064c7.png)

**Comment by Molunerfinn** [comment]
存储区域错了吧…没有alioss.com

**Comment by TheCryingGame** [comment]
> 存储区域错了吧…没有aliyuncs.com
> 
> :octocat: [From gitme iOS](http://flutterchina.club/app/gm.html)

那存储区域应该填什么

**Comment by Molunerfinn** [comment]
空格这个之后会处理。其它没办法判断。得自行处理。你这个就是区域值配错了，好好看看文档吧

**Comment by TheCryingGame** [comment]
> 空格这个之后会处理。其它没办法判断。得自行处理。你这个就是区域值配错了，好好看看文档吧



> 空格这个之后会处理。其它没办法判断。得自行处理。你这个就是区域值配错了，好好看看文档吧

好的，我看错了，不应该填后面的，谢谢了。。
