### ISSUE TITLE
希望可以提供指定配置文件路径的功能

### ISSUE THREAD

**Issue by zt900403** [Molunerfinn/PicGo#255]
## 问题类型
Feature Request

2.1.2、Mac
## 功能请求
真的很需要多台设备之间的相册同步功能，而且例如很多图床没有相册管理功能。
有看到之前的issue，作者还是学生无法负担账号系统的服务器开销，能否将相册的配置信息分离出来，指定相册配置文件路径呢？
用户通过网盘例如onedrive或者dropbox同步管理相册配置文件，然后指定picgo读取特定路径的相册配置文件。
最后非常感谢作者的工作。

---

**Comment by Molunerfinn** [comment]
这里面涉及到比较复杂的问题，由于插件系统的存在，插件系统存放的插件是跟配置文件的目录绑定的，所以做外部配置文件可能会涉及到插件安装的问题。

目前有的想法，但是还没有时间做的部分是：

1. 用插件实现，方法是通过GitHub私人仓库来实现配置同步。这个应该不难实现。
2. 配置文件路径可自定义，但是这个会涉及到插件系统的问题，所以需要单独测试。

关于同步的插件，欢迎去 [插件讨论区](https://github.com/Molunerfinn/PicGo/issues/222) 发表你的意见。

**Comment by Molunerfinn** [comment]
另外之后的版本里，将会考虑将配置和相册分离。
配置依然使用JSON存储，但是相册将会单独剥离出来，用SQLite等更高效、性能更好的数据库来存储。

**Comment by zWingz** [comment]
直接用gist比较方便
不过gist的好像有墙

**Comment by Molunerfinn** [comment]
v2.3.0-beta.7 已支持自定义配置文件路径
