### ISSUE TITLE
mac安装包的区别

### ISSUE THREAD

**Issue by jearton** [Molunerfinn/PicGo#256]
请问mac下的安装包，zip和dmg有什么区别？

![image](https://user-images.githubusercontent.com/10370433/57213552-c26e1b80-7019-11e9-920e-ecc910ea8eee.png)

**Comment by Molunerfinn** [comment]
zip解压后是`picgo.app`文件，需要手动复制到`Application`文件夹里。
dmg双击之后会出现一个安装界面，能快速让你复制到`Application`文件夹里

**Comment by Molunerfinn** [comment]
zip解压后是`picgo.app`文件，需要手动复制到`Application`文件夹里。
dmg双击之后会出现一个安装界面，能快速让你复制到`Application`文件夹里
