### ISSUE TITLE
是否可以对接一下Typora，添加咱们的图床支持。

### ISSUE THREAD

**Issue by gnehcgnaw** [Molunerfinn/PicGo#258]
## 问题类型
是否可以对接一下Typora，添加咱们的图床支持。
## PicGo的相关信息
Mac 2.1.4
## 问题重现
[![2019-05-08_19-38-56.png](https://i.loli.net/2019/05/08/5cd2c1e874c8c.png)](https://i.loli.net/2019/05/08/5cd2c1e874c8c.png)
## 功能请求
1. 目前比较出名的，或者说是比较好用的markdown工具应该是Typora，我发现其中的图床插件只支持收费的那个图床工具，如果加上咱们的就好了。

**Comment by cooper1x** [comment]
要是能支持就好了，目前win用插件会有路径问题，mac应该是OK的。
我的PR拖延了好久，我在想是不是要去买台16寸的mac

**Comment by Molunerfinn** [comment]
Typora最新版已经支持PicGo
