### ISSUE TITLE
希望能支持 Github repo 做图床

### ISSUE THREAD

**Issue by ZetaoYang** [Molunerfinn/PicGo#26]
希望能支持 Github repo 做图床，再配合 [RawGit](https://rawgit.com)。

**Comment by Molunerfinn** [comment]
跟Github相关的部分在思考中，也许不一定要使用repo，也可以用Issue。如果更新应该是下个大版本。

**Comment by ZetaoYang** [comment]
@Molunerfinn 希望能把对各种图床的支持，做成 插件化 的管理。Core + Plugins 这样的做法是否可行？

**Comment by Molunerfinn** [comment]
@ZetaoYang 这个提议很好的，其实我一直在想能否提供一个公共接口，然后不同图床的内部上传api可以不一样，不过外部接收可以走PicGo提供的公共接口。其实也是有点类似于Core + Plugins的做法。
这样的问题就是代码结构和思路都要有所改进，估计要在PicGo的2.0版本来做了。👍

**Comment by Easzl** [comment]
V2EX 上有人询问 GitHub 官方，回复说不反对利用 GitHub Repo 或者 Issues 做图床。另外，目前口碑较好但价格较贵的 iPic 有个插件 iPic Mover，可以关注下，挺好的功能！

**Comment by Molunerfinn** [comment]
@Easzl 可以查看v1.5版本的计划。https://github.com/Molunerfinn/PicGo/projects/1
github图床的功能已经做完了。目前在做其他的部分。等计划都完成后会发布v1.5版本。
那个插件我觉得很不错。不过目前不在PicGo的v1.x的开发计划内。可能2.0开发插件系统后可以做。

**Comment by eluotao** [comment]
昨天在家里电脑下载了,频繁假死.怎么回事?
黑苹果.

公司使用正常.也是黑苹果

笔记本使用也是频繁bug.

我是直接在微信图片里面点开复制.然后上传.

上传的时候 点了没反应  或者出现多次上传   复制不到链接的情况.

**Comment by Molunerfinn** [comment]
@eluotao 没遇到过。

**Comment by skyel1u** [comment]
Github做图床，国内访问还是有点慢的。

**Comment by ZetaoYang** [comment]
@skyel1u 不在于慢，在于Free。

**Comment by Molunerfinn** [comment]
v1.5版本已发布，支持GitHub图床，欢迎更新下载。

**Comment by Molunerfinn** [comment]
PicGo2.0 发布，支持插件系统了，有兴趣的朋友可以为PicGo开发插件呀

**Comment by ZetaoYang** [comment]
@Molunerfinn Wonderful!
