### ISSUE TITLE
Version2.1.2 win10下无法上传GitHub && 插件下载反复弹出提示框

### ISSUE THREAD

**Issue by unclejimao** [Molunerfinn/PicGo#260]
## 问题类型

Bug Report

## PicGo的相关信息
PicGo Version:2.1.2

所在平台：Windows10 （1809）

## 问题重现
1. GitHub图床上传失败。

GitHub图床设置完全按照教程，public仓库

截图如下：

![](https://ws1.sinaimg.cn/large/8878a846ly1g2v4tge0v2j20rr0fo757.jpg)

![](https://ws1.sinaimg.cn/large/8878a846ly1g2v4tsfhk6j20rr0fo3zf.jpg)

2. github插件安装时反复提示安装Node.js

在安装GitHub插件时，提示安装Node.js，按照提示框安装完毕后，重新打开PicGo，安装插件仍然弹出该提示框。

截图如下：

![](https://ws1.sinaimg.cn/large/8878a846ly1g2v4ztx2a6j20rr0foaau.jpg)

PS.此issue提交截图的链接就是PicGo生成，只不过是上传到微博图床。

## 功能请求

---

**Comment by Molunerfinn** [comment]
你的截图不全啊？请给出完整截图
![image](https://user-images.githubusercontent.com/12621342/57438831-5d176600-7277-11e9-9af6-718bf626091b.png)

你可以在「PicGo设置」页面打开你的配置文件，看看你的配置是否正确。

如果安装了Node.js，还提示，可以重启一下电脑，并打开cmd，输入`npm`回车，看看`npm`这个命令是否可执行。
![image](https://user-images.githubusercontent.com/12621342/57438918-833d0600-7277-11e9-8e2a-9d564ae9cd67.png)
如果不可执行说明你的Node.js的npm路径没设置对，所以PicGo无法安装插件。

**Comment by Molunerfinn** [comment]
上传不成功一般都是你自己没设置对- -，比如设置项多了一些空格之类的。这个时候你可以直接打开配置文件检查。

**Comment by Molunerfinn** [comment]
「仓库名」这里应该是`unclejimao/pictureBed`
![image](https://user-images.githubusercontent.com/12621342/57439493-b8962380-7278-11e9-8ee4-92c618edf993.png)
然后检查一下你的token吧。可以打开配置文件看看你的token是否正确。如果依然有问题可以重新申请一个新的token。
上传不成功的基本上都是配置没配对...PicGo的GitHub用户很多，如果是PicGo本身的问题，那么issue早就炸锅了。

**Comment by unclejimao** [comment]
> 
> 
> 上传不成功一般都是你自己没设置对- -，比如设置项多了一些空格、配置项格式没有按照文档来之类的。这个时候你可以直接打开配置文件检查。

谢谢指点。打开配置文件后，确实发现repo那一行中多了一个空格，在PicGo界面下没有发现，是我疏忽了。删除空格保存配置文件后上传GitHub成功。

关于第二个问题：安装插件时反复弹出提示框

npm命令是可以执行的

![](https://raw.githubusercontent.com/unclejimao/picBed/master/Snipaste_2019-05-09_16-48-31.png?token=ALNAEY5DPWN3TCRO2DYIGTK42PVCS)

我这边显示截图是完整的，可能是微博图床加载慢的问题？

前面的截图重新上传GitHub试一下：

![](https://raw.githubusercontent.com/unclejimao/picBed/master/Snipaste_2019-05-09_15-53-03.png?token=ALNAEY73TBIX3EKGBOPLC7C42PVKI)

![](https://raw.githubusercontent.com/unclejimao/picBed/master/Snipaste_2019-05-09_15-54-36.png?token=ALNAEY2KKQ54DSHW7KYINR242PVKM)

![](https://raw.githubusercontent.com/unclejimao/picBed/master/Snipaste_2019-05-09_15-56-27.png?token=ALNAEY7LJLIO6PSS7YRBFUC42PVKC)

**Comment by Molunerfinn** [comment]
嗯如果刚安装完node.js重启一下电脑应该就不会再提示安装了
