### ISSUE TITLE
Mac 直接拖图片无法上传总是提示检查配置

### ISSUE THREAD

**Issue by howie6879** [Molunerfinn/PicGo#261]
## 问题类型
Bug Report

## PicGo的相关信息
目前使用2.1.1以及2.1.2都有相关问题，无法拖图片上传，如下：

![image](https://user-images.githubusercontent.com/17047388/57442068-c7cba000-727d-11e9-98df-9882cdcb3c46.png)

Mac
![image](https://user-images.githubusercontent.com/17047388/57441955-8d620300-727d-11e9-8f54-c7859b1d2ec7.png)

## 问题重现
![image](https://user-images.githubusercontent.com/17047388/57441925-82a76e00-727d-11e9-89ce-9c6c0af9dd18.png)

日志如下：
```txt
2019-05-09 17:13:49 [PicGo ERROR] *** Error creating a JP2 color space: falling back to sRGB

------Error Stack Begin------
undefined
-------Error Stack End-------
2019-05-09 17:13:53 [PicGo ERROR] *** Error creating a JP2 color space: falling back to sRGB

------Error Stack Begin------
undefined
-------Error Stack End------
```

## 功能请求

---

**Comment by Molunerfinn** [comment]
参照这个issue改一下屏幕描述文件应该就可以了：
https://github.com/Molunerfinn/PicGo/issues/199

**Comment by howie6879** [comment]
我改了依旧报错，为什么以前版本没报错呢，我就是用得好好的刚点了升级，老版本没问题

**Comment by Molunerfinn** [comment]
你升级前的版本是多少

**Comment by Molunerfinn** [comment]
2.0之后的版本没有对上传流程做修改，而且我自己也无法复现，并不知道是啥原因

**Comment by howie6879** [comment]
2.0.3左右吧

**Comment by Molunerfinn** [comment]
2.1和2.0的上传底层核心是一样的…如果目前影响使用了可以先降回去

**Comment by howie6879** [comment]
嗯嗯
