### ISSUE TITLE
希望增加便携版安装包

### ISSUE THREAD

**Issue by ZvonimirSun** [Molunerfinn/PicGo#262]
## 问题类型

Feature Request

## PicGo的相关信息

v2.1.2, Windows

## 功能请求

希望能够增加便携版的安装包，即解压即用无需安装的版本。顺便希望能通过scoop安装picgo，有便携版的安装包会比较容易写scoop的manifest。

---

**Comment by ZvonimirSun** [comment]
欸，看到不能弄便携化啊。。。

**Comment by helbing** [comment]
我寫了包，你可以試下

```powershell
scoop bucket add helbing https://github.com/helbing/scoop-bucket
scoop install picgo
```

**Comment by ZvonimirSun** [comment]
@helbing 谢谢
