### ISSUE TITLE
macOS 使用 QQ 或微信截图无法使用剪贴板图片上传

### ISSUE THREAD

**Issue by sxzz** [Molunerfinn/PicGo#264]
## 问题类型

Bug Report

## PicGo的相关信息

macOS 10.13.6
PicGo v2.1.2

## 问题重现

使用QQ或微信的截图，无法剪贴板图片上传，但是在等待上传可以正常显示预览图片
![](https://ws1.sinaimg.cn/large/8511ec6bgy1g2y1po0orqj209w024wee.jpg)

解决办法：可以在聊天框粘贴，然后再复制一遍图片

## 功能请求

---

**Comment by sxzz** [comment]
更换过其他图床，情况一样

**Comment by sxzz** [comment]
日志如下：
[PicGo ERROR]:
Error creating a JP2 color space from ICC profile.
Falling back to sRGB

(node:89153) UnhandledPromiseRejectionWarning: [object Uint8Array]
(node:89153) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:89153) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by Molunerfinn** [comment]
请查看置顶的[issue](https://github.com/Molunerfinn/PicGo/issues/199) 的解决办法是否可以解决你的问题。

**Comment by Molunerfinn** [comment]
![image](https://user-images.githubusercontent.com/12621342/57576601-0d62b580-7496-11e9-94bc-f747b4938b3b.png)
我自己用的 `彩色LCD` 和 `普通RGB描述文件` 都是可以的。你可以试试切换成这两个之一。

**Comment by Molunerfinn** [comment]
如果切换成这二者之后还不能使用，请再发issue。

**Comment by sxzz** [comment]
换描述文件可以解决；
我使用 dev 分支的代码重新编译可以解决，不用换描述文件

**Comment by Molunerfinn** [comment]
嗯，dev分支的代码更新了 picgo-core，解决了macOS剪贴板图片上传报错的问题

**Comment by jasony9982** [comment]
> 嗯，dev分支的代码更新了 picgo-core，解决了macOS剪贴板图片上传报错的问题
下载了最新的release  微信或者截图软件截图的直接上传还是不行,dev的分支有没有合并master?

**Comment by Molunerfinn** [comment]
@jasony9982 没合并，还没发布新版。你可以自己构建也可以改描述文件。
