### ISSUE TITLE
有些图片无法上传，一直出于等待上传状态

### ISSUE THREAD

**Issue by visonforcoding** [Molunerfinn/PicGo#266]
## 问题类型
Bug Report

## PicGo的相关信息
版本2.0.4
mac

## 问题重现

![image](https://user-images.githubusercontent.com/4387302/57596962-df59a000-757f-11e9-882e-bc0aec7e977f.png)

有些图片可以，有些不可以，不知道是大小原因还是其他原因！

**Comment by Molunerfinn** [comment]
等待上传区的图片是你剪贴板里的图片，需要点击一下才会上传

**Comment by visonforcoding** [comment]
不是，我点过了的。而且我还使用了快捷键，发现快捷键没反应，我又手动点了，还是不行。

**Comment by Molunerfinn** [comment]
更新到最新版，然后上传图片，然后提供一下新版里的上传日志，这样我才能定位是啥问题。有可能是图片太大

**Comment by Molunerfinn** [comment]
![image](https://user-images.githubusercontent.com/12621342/57616249-3a0af000-75b0-11e9-8a1e-c9727d792c89.png)
![image](https://user-images.githubusercontent.com/12621342/57616267-40996780-75b0-11e9-8807-c5f3a1039f52.png)

**Comment by visonforcoding** [comment]
好的，谢谢！等复现了再看日志

**Comment by qbmiller** [comment]
我刚遇到这个问题了，用的2.4.0-beta. 后来换成2.3.1也不行。
看了下显示日志 。 提示 /Users/xxx/Library/Application Support/picgo/picgo-clipboard-images/202302021106401.png.178768157 不存在，cant open .
然后我手动创建了 picgo-clipboard-images 这个文件夹 就OK了. 😄

**Comment by Molunerfinn** [comment]
> 我刚遇到这个问题了，用的2.4.0-beta. 后来换成2.3.1也不行。 看了下显示日志 。 提示 /Users/xxx/Library/Application Support/picgo/picgo-clipboard-images/202302021106401.png.178768157 不存在，cant open . 然后我手动创建了 picgo-clipboard-images 这个文件夹 就OK了. 😄

收到，这个问题后续会放到下个beta版本里做一个修复工具箱解决

**Comment by cornradio** [comment]
```
mkdir ～/Application Support/picgo/picgo-clipboard-images
```
