### ISSUE TITLE
mac拖拽上传时图标没了

### ISSUE THREAD

**Issue by ty850454** [Molunerfinn/PicGo#267]
## 问题类型
Bug Report

## PicGo的相关信息
版本: 2.1.2
所在平台: Mac

## 问题重现

拖拽到图标上前

![image](https://user-images.githubusercontent.com/18216589/57665490-a9bfc000-762e-11e9-9239-1ddb5c386974.png)

拖拽到图标上后

![image](https://user-images.githubusercontent.com/18216589/57665474-9c0a3a80-762e-11e9-8f52-23097e2111d1.png)

**Comment by Molunerfinn** [comment]
收到，下个版本会修复这个问题

**Comment by Molunerfinn** [comment]
目前只是图标不见了，不过不影响拖拽上传
