### ISSUE TITLE
是否可以增加一个启用/关闭快捷键的开关

### ISSUE THREAD

**Issue by leafney** [Molunerfinn/PicGo#268]
## 问题类型
Feature Request

## PicGo的相关信息
Mac v2.1.2

## 功能请求

首先，非常感谢作者开发出这么好用的工具，PicGo是我所使用的图片上传工具中最好用的一个。

在使用过程中一直有一个问题困扰着我，PicGo的快捷键功能是必须设置的。也就导致了这样会和我使用的其他软件的快捷键产生冲突的情况，貌似PicGo的快捷键优先级要高一些。

所以我就不得不将PicGo的快捷键更换成其他的组合键，然而又会导致和另一款软件的快捷键产生冲突。。。

因为我平时上传图片时很少使用快捷键的方式来上传，虽然快捷键非常方便。主要是为了确保图片的准确性，一般都是通过点击菜单栏的图标来上传。

希望可以增加一个是否启用快捷键的选项，类似于 `打开更新助手` `开机自启` 这样的形式，或者可以将快捷键选项置为空。感觉会更人性化一些。
Thanks!

---

**Comment by Molunerfinn** [comment]
会的，之后更新的2.2版本里将会重构底层的快捷键系统，可以实现禁用快捷键。并且可以实现插件也支持快捷键。

**Comment by Molunerfinn** [comment]
就目前而言你暂时无法禁用快捷键，所以可以设置成一个暂时用不到的组合键。感谢支持PicGo！

**Comment by leafney** [comment]
> 会的，之后更新的2.2版本里将会重构底层的快捷键系统，可以实现禁用快捷键。并且可以实现插件也支持添加自定义快捷键。

That't great.

**Comment by Molunerfinn** [comment]
2.2版本已更新
