### ISSUE TITLE
win7安装失败

### ISSUE THREAD

**Issue by CatcherX** [Molunerfinn/PicGo#269]
## 问题类型

Bug Report

## PicGo的相关信息
提示：    
问题签名:
  问题事件名称:	APPCRASH
  应用程序名:	picgo-setup-2.1.1.exe
  应用程序版本:	2.1.1.31
  应用程序时间戳:	5a6fed7c
  故障模块名称:	System.dll
  故障模块版本:	0.0.0.0
  故障模块时间戳:	5a6fed15
  异常代码:	c0000005
  异常偏移:	00001581
  OS 版本:	6.1.7601.2.1.0.256.1
  区域设置 ID:	2052
  其他信息 1:	0a9e
  其他信息 2:	0a9e372d3b4ad19135b953a78882e789
  其他信息 3:	0a9e
  其他信息 4:	0a9e372d3b4ad19135b953a78882e789

联机阅读隐私声明:
  http://go.microsoft.com/fwlink/?linkid=104288&clcid=0x0804

如果无法获取联机隐私声明，请脱机阅读我们的隐私声明:
  C:\Windows\system32\zh-CN\erofflps.txt
`

## 问题重现

点击exe文件安装就会出现

## 功能请求

正常安装

**Comment by CatcherX** [comment]
重试几次后，又可以安装了，原因不明

**Comment by Molunerfinn** [comment]
我手头没有Win7的机器，也不知道具体啥原因，很抱歉(._.)
