### ISSUE TITLE
七牛云可以支持存储路径，腾讯COS可以支持自定义域名吗？

### ISSUE THREAD

**Issue by c0427** [Molunerfinn/PicGo#27]
有点疑惑，不知道之后是否有开发计划，谢谢，
PicGo很好用，支持！

**Comment by Molunerfinn** [comment]
目前来说，支持两者的状态是这样：
1. 七牛因为支持了自定义域名，所以在路径上限制比较大，只能通过域名+上传文件来确定你的文件
2. COS因为不支持自定义域名，所以路径上限制小，返回的url是直接取的服务端返回的默认url。

不过就目前来看应该是能够解决的。下个版本应该会统一更新存储相关的问题。预计一到两周内吧。

**Comment by Molunerfinn** [comment]
v1.4.2版本已经支持。
