### ISSUE TITLE
是否能增加可选存储路径

### ISSUE THREAD

**Issue by cj466** [Molunerfinn/PicGo#270]
## 问题类型

Feature Request

## PicGo的相关信息

Windows 2.1.2

## 功能请求

希望在上传区或者图床设置里，指定存储路径能设置多个路径，因为有时候要上传到不同的文件夹，如果能在上传区手动选择设置的路径就很好啦！
Thanks

**Comment by Molunerfinn** [comment]
不是所有的图床都有可选路径。这个功能不会做在本体里。可以考虑用插件实现
