### ISSUE TITLE
腾讯云通过picgo上传成功后,在Markdown中粘贴好链接之后无法使用

### ISSUE THREAD

**Issue by weidongzhou1994** [Molunerfinn/PicGo#271]
同样是在picgo复制的链接，不知道为什么有的能用，有的不能用。

**Comment by Molunerfinn** [comment]
把链接发上来看看？

**Comment by weidongzhou1994** [comment]
这个能用，![](https://blog-1258437747.cos.ap-chengdu.myqcloud.com/20190103120002.png)
这个不能用，![](https://blog-1258437747.cos.ap-chengdu.myqcloud.com/20190520133747.png)

**Comment by Molunerfinn** [comment]
![image](https://user-images.githubusercontent.com/12621342/57998544-97e58d80-7b04-11e9-8e56-7dcf5ca55c52.png)
你直接用浏览器打开就知道了- -。这个不是PicGo的问题，而是你仓库设置的问题。既然你都用来写markdown了就不能把这个存储的bucket设成私有，而应该设成公开。

**Comment by Molunerfinn** [comment]
在我这边因为我没有权限，所以我两张图片都看不到。
![image](https://user-images.githubusercontent.com/12621342/57998598-ce230d00-7b04-11e9-96b4-e16c4f7e9698.png)

**Comment by weidongzhou1994** [comment]
我没动过啊，为什么以前的能用，现在就不能用。怎么改呢？

**Comment by weidongzhou1994** [comment]
我改了一下，您再试试

**Comment by Molunerfinn** [comment]
![image](https://user-images.githubusercontent.com/12621342/57998725-4558a100-7b05-11e9-93cd-a185222ce65c.png)

**Comment by weidongzhou1994** [comment]
为什么我将权限改了之后，还会存在前面的允许，后面的被拒绝呢？

**Comment by Molunerfinn** [comment]
我不知道你是否更新了什么配置。
我的COS权限配置是这样的：
![image](https://user-images.githubusercontent.com/12621342/57998802-96689500-7b05-11e9-9fe1-5a13e655fa28.png)

你自己也可以试试，打开Chrome的隐身窗口再打开你的图片地址，就知道能不能公开访问了。这个问题已经不是PicGo的问题了，如果改成公有读还不能公开访问，那是COS的问题，你应该去那里提工单。

**Comment by weidongzhou1994** [comment]
您好，同一个图片，上面的那个对象地址被拒绝，下面的那个签名链接可以访问，是因为防盗链还是什么吗？
![image](https://user-images.githubusercontent.com/40510496/57999253-530f2600-7b07-11e9-81ee-7464d562266e.png)

**Comment by weidongzhou1994** [comment]
上面的链接：https://blog-1258437747.cos.ap-chengdu.myqcloud.com/20190520113130.png
        下面的链接：https://blog-1258437747.cos.ap-chengdu.myqcloud.com/20190520113130.png?q-sign-algorithm=sha1&q-ak=AKIDnkIDbpjCKvJX7dFK0ZoTpKmrbv1yenDN&q-sign-time=1558331797;1558333597&q-key-time=1558331797;1558333597&q-header-list=&q-url-param-list=&q-signature=97cc751bebf9202be4c6d8ce61966d06f6b9b31d&x-cos-security-token=4e961a356348e15627fa4476045b8ec8a4cc467c10001

**Comment by Molunerfinn** [comment]
对，如果你开启了防盗链也会出现这个情况。如果你开了防盗链，那么只有从你指定的网站打开才能访问图片。

**Comment by Molunerfinn** [comment]
至于部分图片为何不行，有可能有些图片的权限依然没有改过来。

单独设置权限试试。
![image](https://user-images.githubusercontent.com/12621342/57999491-2c9dba80-7b08-11e9-81e8-9e8d72d83d8f.png)

另外再说一下，这个问题已经不属于PicGo的问题了，如果还有问题请你去COS提工单

**Comment by weidongzhou1994** [comment]
我又试了以下，发现picgo最近上传的几张图片会自动变更权限为继承权限，而不是公有读私有写权限，这是为什么呢？

**Comment by Molunerfinn** [comment]
一直都是继承权限，继承的是你bucket设置的权限
