### ISSUE TITLE
希望官方能支持gitee,coding.net图床

### ISSUE THREAD

**Issue by lizhuangs** [Molunerfinn/PicGo#273]
虽然现在支持的挺多的，但是已经有了github，感觉原生直接集成gitee和coding.net(现在好像是腾讯云开发者平台了)更简单一点。国内的速度实在太不稳定了。一般的博客也是放在git pages上，COS，OSS各种云的不太想弄。对electro和vue不熟，不好贡献插件，所以希望原生支持，谢谢~

**Comment by Molunerfinn** [comment]
没时间
