### ISSUE TITLE
剪贴板图片无法识别

### ISSUE THREAD

**Issue by lizhuangs** [Molunerfinn/PicGo#275]
## 问题类型
Bug Report

## PicGo的相关信息
picgo 2.1.2 & win8.1

## 问题重现
剪贴板图片无法识别
提示，请检查配置和图片是否符合要求

图片是使用windows自带的图片查看器复制的，当然我在图片文件夹里面直接复制图片也是一样的问题。

**Comment by Molunerfinn** [comment]
WIN8支持截图，网页图片右键复制。想要支持完整的体验请升级WIN10

**Comment by lizhuangs** [comment]
你好，请问下，win8支持截图指的是用什么截图？我用QQ截图测试不可以。网页右键复制可以。因为家用笔记本，win10太吃硬件资源，换过几次用回win8了。。

**Comment by Molunerfinn** [comment]
我没有WIN8的系统，不过在WIN10和WIN7上QQ截图测试是可以的。

剪贴板上传图片的原理是通过POWERSHELL获取剪贴板的图片内容（二进制）然后在系统里生成一张图片，上传成功后再把这张图片从磁盘上删掉。

**Comment by lizhuangs** [comment]
感谢回复，我测试了一下。复制功能是QQ五笔的问题，最新的QQ拼音和QQ自带的截图工具都可以使用。QQ五笔很多个没更新了。贴一下解决办法给后面可能遇到的人，QQ自带的是集成进去的，所以只能复制QQ拼音的截图工具QQPYSnapshot.exe和screencapture.cupf到QQ五笔目录，QQPYSnapshot.exe需要改名为SnapShot.exe。

**Comment by Molunerfinn** [comment]
感谢
