### ISSUE TITLE
自定义image格式

### ISSUE THREAD

**Issue by lizhuangs** [Molunerfinn/PicGo#276]
## 问题类型

Feature Request

## 功能请求

众所周知，markdown里面插图比较麻烦，感谢picgo的出现解决了这个问题。但是体验过程中发现一个问题，就是图片image格式不能自定义，比如`<img src="1.jpg" style="height:200px" />`。因为原生的markdown标签是不能控制大小的，只能使用html实现，而一般的博客配图，很少直接使用原图的，除非给这些配图都添加一个统一的css样式解决这个问题，但是不同的地方css可能不太一样。

我发现在vs-picgo这个插件里面是实现了这个功能的，而我目前的使用方法是修改了picgo的源码手动加了一下然后编译使用。。

**Comment by Molunerfinn** [comment]
PicGo支持custom链接格式。

https://picgo.github.io/PicGo-Doc/zh/guide/config.html#%E8%87%AA%E5%AE%9A%E4%B9%89%E9%93%BE%E6%8E%A5%E6%A0%BC%E5%BC%8F

**Comment by lizhuangs** [comment]
感谢回复，之前看文档以为是image的url的自定义格式，理解错了。
