### ISSUE TITLE
相册管理界面

### ISSUE THREAD

**Issue by lizhuangs** [Molunerfinn/PicGo#277]
## 问题类型

Feature Request

## 功能请求

相册管理界面目前删除不会同步到图床服务器，好在github-plus插件实现了这个功能，虽然还有点bug。每个图床都实现的话，工作量的确有点多。
相册管理目前选择需要一个一个选择，非常麻烦。考虑到图片过多的情况，全选也是个影响效率的问题。一个不错的想法是在每一行图片前加一个选择框。
另外就是图片如果太多不知道是否是懒加载或者分页的，因为我没有这么多图所以没测试这个。
然后我看到计划是将配置存到数据库，本来也想提的正好看见了。。
这是我使用过程中遇到的几个问题，所以分开提了。

**Comment by Molunerfinn** [comment]
图片目前已经是懒加载了。目前支持单选和多选，以及根据图床来筛选，没必要为某一行单独加入勾选。
