### ISSUE TITLE
可否增加一个自动复制链接到剪贴板的开关？

### ISSUE THREAD

**Issue by yorushika** [Molunerfinn/PicGo#278]
## 问题类型

Feature Request

## PicGo的相关信息

Mac 2.1.2

## 功能请求

有时上传仅仅是为了丰富图床内容而不需要获取图片URL，此时自动添加的URL会塞满我的Paste造成困扰。如果能做成开关就好了。

---

**Comment by Molunerfinn** [comment]
可以考虑在下个版本里加入这个开关

**Comment by yorushika** [comment]
赞！另外剪贴板文件上传也建议加一个开关，这些真的非常容易误操作。

**Comment by JoelynZhou** [comment]
+1 同样遇到这个问题，因为截图会自动保存到剪切板，然后被自动上传到 github，所以…

**Comment by jieshuq** [comment]
问一下为七牛云对象存储上传图片后相册区域为什么预览图显示错误 （防盗链和全局代理都是关闭状态）
![image](https://user-images.githubusercontent.com/47479745/59676415-1adc2f80-91fa-11e9-8533-20b108f7dc3e.png)

**Comment by Molunerfinn** [comment]
@jieshuq 提问之前请看看README说明里的FAQ好吗？

![image](https://user-images.githubusercontent.com/12621342/59684814-60562800-920d-11e9-8af2-0fce61e2f21b.png)

https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md#1七牛图床上传图片成功后无法显示或图片无http前缀

**Comment by Molunerfinn** [comment]
2.3.0版本将更新这个功能。
![image](https://user-images.githubusercontent.com/12621342/77070596-7788a700-6a25-11ea-9405-3a6485dfc17a.png)

**Comment by jinfagang** [comment]
我遇到问题恰恰相反，我从文件拖动上传它不会复制粘贴板。我从哪里去看上传后的历史URL、

**Comment by Molunerfinn** [comment]
> 我遇到问题恰恰相反，我从文件拖动上传它不会复制粘贴板。我从哪里去看上传后的历史URL、

有个功能叫相册 有个开关可以设置是否上传后复制到剪贴板

**Comment by jinfagang** [comment]
<img width="912" alt="image" src="https://user-images.githubusercontent.com/21303438/183279664-2618e030-bf4a-4637-aacf-8cfdbe0be0f9.png">
没有任何显示。

**Comment by Molunerfinn** [comment]
> <img alt="image" width="912" src="https://user-images.githubusercontent.com/21303438/183279664-2618e030-bf4a-4637-aacf-8cfdbe0be0f9.png">
> 
> 没有任何显示。

相册没有显示的问题之前的issue里也有说了，删掉配置文件目录下的picgo.db，重启picgo即可。另外建议升级最新的beta版本，能解决相册文件损坏的问题
