### ISSUE TITLE
win10已设置环境变量，从剪切板上传失败

### ISSUE THREAD

**Issue by Enriquejaja** [Molunerfinn/PicGo#279]
## 问题类型
Bug Report

## PicGo的相关信息
win10 1903 may 专业工作站版 

PicGo 2.1.2

## 问题重现
截图后，调用快捷键上传，出现对话框。

![不知名问题](https://user-images.githubusercontent.com/46493651/58448011-0647d280-8139-11e9-940c-f4ea01526623.gif)

![弹出对话框](https://raw.githubusercontent.com/Enriquejaja/Figurebed/master/img/未知问题.jpg)

## 对话框内容

![](https://raw.githubusercontent.com/Enriquejaja/Figurebed/master/img/{F234F247-9B46-49B7-AE38-5CF07F814397}.png.jpg)

> A JavaScript error occurred in the main process
>  Uncaught Exception 
> Error: spawn powershell ENOENT
>  at Process. Child Process. handle onexit(internal/child process. js: 232: 19) 
> at onErrorNT (internal/child process. js: 407: 16) 
> at process. tick Callback(internal/process/next tick js: 63: 19)

## 已参考Issues 设置环境变量

已参考[相关Issues ](https://github.com/Molunerfinn/PicGo/issues/243)设置环境变量后重启，但是仍然从剪切板上传失败。

![](https://raw.githubusercontent.com/Enriquejaja/Figurebed/master/img/已设置环境变量.jpg)

---

拖拽上传一张图片，但PowerShell并没有出现运行的情况

![image](https://user-images.githubusercontent.com/46493651/58450535-d9e48400-8141-11e9-9330-c4a69f514f0f.png)

**Comment by Molunerfinn** [comment]
把powershell的路径添加到环境变量的`Path`而不是环境变量的其他地方：
![image](https://user-images.githubusercontent.com/12621342/58452548-524f4300-814a-11e9-9296-f6b912cc3d2b.png)
![image](https://user-images.githubusercontent.com/12621342/58452559-59765100-814a-11e9-8f31-c83d64b5e53b.png)

> 拖拽上传一张图片，但PowerShell并没有出现运行的情况

你需要先退出PicGo，然后用PowerShell运行PicGo.exe才会在PowerShell里看到效果。

另外，如何鉴别你环境变量添加成功，你只需要在 `CMD`里输入 `powershell` 看看能否进入 powershell环境即可。 PicGo是通过Node来调用系统里 `powershell` 这个命令的，而这个命令必须是 `powershell.exe` 所在的目录在系统的 `Path` 的这个环境变量里。所以如果遇到写入 `Path` 还是无法调用，那很抱歉，我无法复现也没办法修复。
