### ISSUE TITLE
PicGo 在程序坞上时图标过大了

### ISSUE THREAD

**Issue by c0427** [Molunerfinn/PicGo#28]
如图所示，PicGo 固定在程序坞上时，比旁边的Photoshop大了一圈，希望能优化下，谢谢。

![](https://ws1.sinaimg.cn/large/006RUaFHgy1fp96v2dzroj30ru046gns.jpg)

**Comment by Molunerfinn** [comment]
- -这个尺寸每个应用都不一定一样把。百度云的尺寸还比PS小了一圈呢。

**Comment by c0427** [comment]
嗯嗯，是的。但是以系统图标尺寸为准，会显得更和谐些。

![](https://ws1.sinaimg.cn/large/006RUaFHgy1fp98a9iyt1j31f4056dl1.jpg)

**Comment by XIJINIAN** [comment]
确实感觉图标有点大，影响美观，不知道是什么情况，祝 PicGo 越来越完美：

![](https://i.loli.net/2018/09/04/5b8e2bd74d7e1.png)

**Comment by Molunerfinn** [comment]
@XIJINIAN  PicGo采用的是标准[ICNS尺寸](http://iconhandbook.co.uk/reference/chart/osx/)，因为是正方形没有倾斜没有变圆所以感觉会比较大。
