### ISSUE TITLE
希望添加log功能

### ISSUE THREAD

**Issue by zWingz** [Molunerfinn/PicGo#280]
## 问题类型

Feature Request

## 功能请求

希望提供`log`功能
可以查看`app`运行期间的`log`信息

**Comment by zWingz** [comment]
可以让插件写入一些错误信息..不然真不好debug.

**Comment by Molunerfinn** [comment]
插件可以通过调用ctx.log.xxx输出日志，会自动写入一个叫做picgo.log的文件。详情可以查看PicGo-Core以及PicGo2.1版本更新日志

**Comment by zWingz** [comment]
那可以做个界面把log信息显示出来?

**Comment by Molunerfinn** [comment]
![image](https://user-images.githubusercontent.com/12621342/58679451-16102280-8396-11e9-9d37-7b401dab96dc.png)

**Comment by zWingz** [comment]
`remove`事件好像没有`log`功能

**Comment by Molunerfinn** [comment]
是的，这个还没有，可以考虑加上

**Comment by zWingz** [comment]
阔以直接通过`this`来拿.. 或者通过`guiApi`里面的`picgo`实例来拿...
