### ISSUE TITLE
请求帮助，关于图床设置

### ISSUE THREAD

**Issue by ChaunceyDong** [Molunerfinn/PicGo#281]
我按照http://www.wzqj.top/2019/03/01/%E4%BD%BF%E7%94%A8%E4%B8%83%E7%89%9B%E4%BA%91%20+%20PicGo%E6%90%AD%E5%BB%BA%E5%9B%BE%E5%BA%8A%E5%B9%B6%E5%AE%9E%E7%8E%B0%E5%BF%AB%E9%80%9F%E4%B8%8A%E4%BC%A0/ 的设置，注册了七牛，下载了PicGo（感谢），但是一直设置错误，无法上传，请求帮助
![image](https://user-images.githubusercontent.com/33920326/58625522-3512a400-8305-11e9-99e1-abbc4c131614.png)
![image](https://user-images.githubusercontent.com/33920326/58625607-62f7e880-8305-11e9-9501-f1908774e26b.png)
![image](https://user-images.githubusercontent.com/33920326/58625619-6b502380-8305-11e9-8ef7-60c7cd296308.png)

**Comment by Molunerfinn** [comment]
打开配置文件看看是不是一些项输入错误，比如多了或者少了一位，或者是开头结尾多了空格。

**Comment by Molunerfinn** [comment]
另外存储区域不是填「华南」，而是填华南地区的代码，具体请认真看文档。

**Comment by g8up** [comment]
@Molunerfinn 遇到了相同的问题，请问这个`存储区域`的代码是在七牛文档还是 picgo 的文档？
我看有的界面是按钮形式的。

**Comment by g8up** [comment]
找到文档了，看这里：https://picgo.github.io/PicGo-Doc/zh/guide/config.html#%E4%B8%83%E7%89%9B%E5%9B%BE%E5%BA%8A
