### ISSUE TITLE
linux下剪切板上传问题

### ISSUE THREAD

**Issue by ycrao** [Molunerfinn/PicGo#285]
## 问题类型
Bug Report
## PicGo的相关信息
PicGo 2.1.2 - Ubuntu 16.04 LTS 
## 问题重现
已经安装过 `xclip` ，剪切板上传仍然提示 请先安装 `xclip`
![image](https://user-images.githubusercontent.com/3280204/58865240-cb214280-86e8-11e9-8bbb-5d3fcb067133.png)
![image](https://user-images.githubusercontent.com/3280204/58865264-d96f5e80-86e8-11e9-9de9-fa18cc4e577c.png)

## 功能请求
修复bug

**Comment by Molunerfinn** [comment]
我没有Linux的机器无法做测试和修复。不同系统的剪贴板图片上传使用的是不同的脚本，在Linux上用的是这个：

https://github.com/PicGo/PicGo-Core/blob/dev/src/utils/clipboard/linux.sh#L3

如果这句话跑不通才会提示没有xclip。

**Comment by Molunerfinn** [comment]
另外这个脚本在其他人的Linux发行版上测试是成功的。我对Linux系统不熟悉，所以可能无法帮忙修复。

**Comment by Molunerfinn** [comment]
另外你直接命令行里输入`xclip`会出现什么呢，也有可能第一次安装xclip后需要重启一下再试试。

**Comment by ycrao** [comment]
该发行版上直接执行 `xclip` 处于 `halt` 的状态，但是执行完整的 `shell` 命令导出图是可以的

![image](https://user-images.githubusercontent.com/3280204/58866610-80ed9080-86eb-11e9-8495-4af260605ad5.png)


```bash
xclip -selection clipboard -target image/png -o > 1.png
```

建议判断是否存在使用 `xclip -h` 命令，有回显帮助信息。

**Comment by Molunerfinn** [comment]
你如果输入`command -v xclip`呢

**Comment by ycrao** [comment]
返回它的路径了
```bash
command -v xclip
/usr/bin/xclip
```

**Comment by Molunerfinn** [comment]
所以既然正常返回了就不应该出现`{ echo >&1 "no xclip"; exit 1; }`，真是个奇怪的问题。你尝试重启一下系统看看呢

**Comment by ycrao** [comment]
安装之后，已经重启过。

**Comment by Molunerfinn** [comment]
你如果完整输入`command -v xclip >/dev/null 2>&1 || { echo >&1 "no xclip"; exit 1; }`，会返回`no xclip`么

**Comment by ycrao** [comment]
没有返回

![image](https://user-images.githubusercontent.com/3280204/58867712-88ae3480-86ed-11e9-961a-172001c0864d.png)

**Comment by ycrao** [comment]
我这边下载源码，使用开发 `npm run dev` 是可以上传的，怀疑是 `liunx` 二进制的 `snap` 安装包问题。

**Comment by Molunerfinn** [comment]
真是奇怪

**Comment by dwdcth** [comment]
> 我这边下载源码，使用开发 `npm run dev` 是可以上传的，怀疑是 `liunx` 二进制的 `snap` 安装包问题。

我用appimage包测试可以

**Comment by Molunerfinn** [comment]
暂时先关闭了哈，PicGo剪贴板上传在linux下是依赖xclip的
