### ISSUE TITLE
我在进行快捷键粘贴的时候发现了一个bug，可能是我自身的原因，但是我无法独立解决他

### ISSUE THREAD

**Issue by Zhoumi0729** [Molunerfinn/PicGo#286]
## 问题类型

Bug Report

## PicGo的相关信息

Windows

## 问题重现

![$% H)ZYJOU ZM0J)$@K@668](https://user-images.githubusercontent.com/51530701/59181181-51ca9980-8b99-11e9-8a8a-87563a4ce1a5.png)

## 功能请求

---

**Comment by Molunerfinn** [comment]
https://github.com/Molunerfinn/PicGo/issues/279
