### ISSUE TITLE
picgo使用github做图床，上传后好使

### ISSUE THREAD

**Issue by tksj09** [Molunerfinn/PicGo#287]
## 问题类型
Bug Report

## PicGo的相关信息
2.1.2
win10

## 问题重现

使用github做图床，刚上传的图片连接有效，过一段时间就会失效，即使用网页打开链接，也是404

---

**Comment by Molunerfinn** [comment]
检查你的网络，这跟picgo没关系。

**Comment by tksj09** [comment]
翻墙是没问题的，只是打不开picgo生成的链接

**Comment by Molunerfinn** [comment]
picgo拿的就是github的链接，picgo自己不生成链接。。。

比如你的这张图：

![image](https://user-images.githubusercontent.com/12621342/59254887-a3d7f180-8c63-11e9-92da-67661fd4f038.png)

picgo拿到的就是点击`download`之后给出的链接，所以能否访问已经跟picgo没有关系，如果不能上传才是跟picgo有关系。

![image](https://user-images.githubusercontent.com/12621342/59254983-ccf88200-8c63-11e9-9fc4-f6e2dba4188b.png)

**Comment by tksj09** [comment]
谢谢，是不是最好不要用私有库？

**Comment by Molunerfinn** [comment]
当然...你用私有库不就意味着别人无法访问了吗，如果你用私有库别人还能访问你的图片，那私有库意义在哪里？

**Comment by tksj09** [comment]
嗯，谢谢

比较公开私有库链接的区别，私有库多了`?token=ADJYNJ5TD2Q6XJFCL7C53FS475S7O`，看来这个token会过期

`https://raw.githubusercontent.com/tksj09/img2019/master/img2019/transform20fps.gif`

`https://raw.githubusercontent.com/tksj09/image-hosting/master/img2019/transfo3%E6%B1%8223%E6%AC%A1%20sdzrm20fps.gif?token=ADJYNJ5TD2Q6XJFCL7C53FS475S7O`

**Comment by ktrimisu** [comment]
我也是，以前图片可以展示，现在不可以了，我的库也是共有库，现在禁止访问了怎么回事呢

**Comment by ktrimisu** [comment]
https://raw.githubusercontent.com/ktrimisu/Typora_Figurebed/master/img/20200421172348.png

**Comment by ktrimisu** [comment]
![image](https://user-images.githubusercontent.com/36870128/79870285-55fc5000-8415-11ea-8e1a-633b0073fedf.png)

**Comment by ktrimisu** [comment]
我GitHub上的自己的头像也不能正常显示
![image](https://user-images.githubusercontent.com/36870128/79870781-12561600-8416-11ea-9e4b-e4305a13d9c8.png)

**Comment by Molunerfinn** [comment]
> 我GitHub上的自己的头像也不能正常显示
> ![image](https://user-images.githubusercontent.com/36870128/79870781-12561600-8416-11ea-9e4b-e4305a13d9c8.png)

那这是你自己网络问题啊...

**Comment by Molunerfinn** [comment]
![image](https://user-images.githubusercontent.com/12621342/79871299-b9d34880-8416-11ea-8a17-cd60fcb69154.png)
我这边能看到。可能是你那边的github节点被墙了

**Comment by SherwinFeng** [comment]
picGo访问private repo里的图片，会生成带有token的url，这个token是过期时间的，过期了自然不能访问了

**Comment by HolyZheng** [comment]
原来是私有库的原因，我就说图片url 后面为什么会带个token，而且过一段时间就404了，把url token换回新的就可以访问。。那看来是不能用私有库了，不然拿到的链接会随token一起过期

**Comment by Molunerfinn** [comment]
用github做图床就不要用私有库。图片链接是公开访问的 跟私有库天然矛盾。

**Comment by RUTHDOMINGUEZ8216** [comment]
> 矛盾

喔喔！
我之所以沒有用公開的 ，是因為我只想讓我分享的圖片，在特定地方看到，且只有透過連結才能看，而不是到我的倉庫後就可以看到所有我上傳的圖片。有點類似禁止直接訪問wp_content

用私有倉庫過段時間會產生404找不到資源的錯誤。目前不知道令牌失效怎麼自動更新。感覺這條路行不通。。。問問大家有沒有想法。

**Comment by Molunerfinn** [comment]
> > 矛盾
> 
> 
> 
> 喔喔！（同學代回）
> 
> 我之所以沒有用公開的 ，是因為我只想讓我分享的圖片，在特定地方看到，且只有透過連結才能看，而不是到我的倉庫後就可以看到所有我上傳的圖片。有點類似禁止直接訪問wp_content
> 
> 
> 
> 用私有倉庫過段時間會產生404找不到資源的錯誤。目前不知道令牌失效怎麼自動更新。感覺這條路行不通。。。問問大家有沒有想法。
> 
> 
> 
> 

花钱买云服务 比如腾讯云 阿亮云 aws 等能满足你的需求。 GitHub 不满足

**Comment by RUTHDOMINGUEZ8216** [comment]
> > > 矛盾
> > 
> > 
> > 喔喔！（同學代回）
> > 我之所以沒有用公開的 ，是因為我只想讓我分享的圖片，在特定地方看到，且只有透過連結才能看，而不是到我的倉庫後就可以看到所有我上傳的圖片。有點類似禁止直接訪問wp_content
> > 用私有倉庫過段時間會產生404找不到資源的錯誤。目前不知道令牌失效怎麼自動更新。感覺這條路行不通。。。問問大家有沒有想法。
> 
> 花钱买云服务 比如腾讯云 阿亮云 aws 等能满足你的需求。 GitHub 不满足

好的。用雲的話就用alist 然後還是能用picgo ，阻擋訪問連結外的圖片資源的話picgo 中要設置嗎？文檔中沒有提到
謝謝。
