### ISSUE TITLE
通过剪贴上传的图片本地有没有备份？

### ISSUE THREAD

**Issue by jerryc127** [Molunerfinn/PicGo#288]
## 问题类型

Feature Request

## PicGo的相关信息

windows

## 功能请求

---

通过剪贴上传的图片本地有没有备份？
希望能上传的同时，本地也能存一份

**Comment by Molunerfinn** [comment]
PicGo只负责上传。已经上传云端需要备份的话请手动下载。否则就先存本地再上传。
