### ISSUE TITLE
快捷键上传一个已存在的图片文件失败

### ISSUE THREAD

**Issue by 410799459pic** [Molunerfinn/PicGo#289]
## 环境信息

mac Os 10.13.6
PicGo-2.1.2

## 问题描述

测试了2个图床（SM和Github）
"拖拽上传"可以上传成功。
qq截图到剪切板"快捷键上传"可以成功。
但是对一个已经存在的图片，打开，用快捷键貌似是不行的呢,这个请问本身就是这样设计的吗？

## 问题重现
![](https://raw.githubusercontent.com/410799459pic/pics/master/img/20190617172026.png)

**Comment by Molunerfinn** [comment]
快捷键上传只支持上传剪贴板里的图片。

**Comment by 410799459pic** [comment]
神速回复 好的 谢谢大佬
