### ISSUE TITLE
v1.5 版本 Plans

### ISSUE THREAD

**Issue by Molunerfinn** [Molunerfinn/PicGo#29]
目前的计划可以查看Projects面板：

https://github.com/Molunerfinn/PicGo/projects/1

如果你对v1.5有啥提议欢迎可以在底下评论区和我一起讨论。

**Comment by c0427** [comment]
- 建议增加类似于iPic的那种全局上传快捷键功能。目前PicGo貌似只有复制到粘贴板以后才可使用快捷键上传。

- 昨天在Mac上尝试上传一个5MB左右大小的视频文件到七牛云，貌似一直上传不了，可能是限制了文件格式类型？

- 希望上传后的文件可以设置是保持原文件名还是使用时间戳命名文件。

**Comment by Molunerfinn** [comment]
@c0427 
1. 受限于electron，无法获取非剪贴板的图片，所以必须复制到剪贴板才可以用快捷键上传
2. PicGo不支持视频上传。支持gif。
3. 只有通过拖拽上传的文件才能获取文件名。通过剪贴板上传的无法获取文件名。所以可以做到都用时间戳命名，但是无法做到都是文件名命名。

**Comment by ye4241** [comment]
为啥不支持sha1重命名的呢？这样子就不用关心到底文件名是啥，会不会覆盖云端之类的问题了，同时将文件名作为本地相册备注。

**Comment by Molunerfinn** [comment]
@ye4241 可以考虑增加一个属性在上传前重命名。不过需要知道的是不是所有人都喜欢sha1之后的文件名的比如我，我上传前的文件名都会命名好。

**Comment by ye4241** [comment]
@Molunerfinn 真心大赞的属性~

**Comment by oopp1800** [comment]
建议增加开机自动启动的选项，并且能够启动后自动最小化~

**Comment by Molunerfinn** [comment]
@oopp1800 开机自启应该可以

**Comment by ye4241** [comment]
还有一个对MacOS不太友好的，就是配置窗口没有在docker显示，导致从全屏浏览器复制的时候，无法直接用Command+Tab切换回来。

**Comment by Molunerfinn** [comment]
@ye4241 mac版本的开发初衷就是一个顶部栏应用。只不过为了兼容其他平台而做了主窗口。你不用command+tab切换回来上传啊...直接用全局的快捷键上传复制的图片就行了啊

**Comment by ye4241** [comment]
@Molunerfinn 在第一次设置参数的时候，切换来切换去，还是挺繁琐的样子。不过影响倒是还好吧。

**Comment by fcwys** [comment]
貌似不支持删除图片，只是移除相册，希望支持，有些图片无法删除的话时间长了很占空间

**Comment by Molunerfinn** [comment]
@fcwys 这个创立之初就不打算支持。

**Comment by fcwys** [comment]
哦，为什么呢？

**Comment by Molunerfinn** [comment]
有些图床是只能上传不能删除的。比如新浪图床。
如果你有些图片不想要了应该自己去图床对应的服务商里删除。

**Comment by fcwys** [comment]
哦，明白了，对了，希望能有一个小悬浮窗直接拖上去上传获取链接

**Comment by Molunerfinn** [comment]
@fcwys 这个建议可以考虑。

**Comment by fcwys** [comment]
嗯呢，希望PicGo越来越好，个人喜欢markdown写笔记，支持您呢

**Comment by Molunerfinn** [comment]
@iCasture 已加到v1.5的[TODO](https://github.com/Molunerfinn/PicGo/projects/1#card-8779131)

**Comment by Molunerfinn** [comment]
v1.5版本将不再接受新的计划，之后可能会以小版本更新或者留到v1.6来做了。
v1.5版本的计划以及目前进度请详看project面板：https://github.com/Molunerfinn/PicGo/projects/1
