### ISSUE TITLE
Error: Cannot find module 

### ISSUE THREAD

**Issue by lizhuangs** [Molunerfinn/PicGo#290]
## 问题类型
Bug Report

## PicGo的相关信息
win10  pigGo2.1.2
## 问题重现
在线安装picgo-plugin-gitee-uploader插件，除了这个插件之前我安装picgo-plugin-qingstor-uploader也遇到过。安装完成后，日志出现
`Error: Cannot find module 'C:\Users\Administrator\AppData\Roaming\picgo\node_modules\picgo-plugin-gitee-uploader'`
后来我发现是因为安装后没有生成dist，但是我看了一下其它插件这个dist是没有发布到npm的。
我对前端了解不多，是我使用有什么问题还是BUG么？
谢谢

**Comment by lizhuangs** [comment]
对了，picgo-plugin-qingstor-uploader这个我也提过issue，但是作者没有找到原因给关闭了。今天我测试自己写的gitee插件也遇到了。日志里面只有这个错误信息，没有其它提示。

**Comment by Molunerfinn** [comment]
dist应该是传到npm里的，不会是安装的时候才生成。这个一般是构建脚本的问题，跟picgo本身没啥问题。
我自己写的插件都是build后推到npm的，所以在github仓库里看不到dist，但是npm里是有dist的。
https://github.com/PicGo/picgo-plugin-pic-migrater/blob/dev/.travis.yml#L21-L22

你也可以通过jsdelivr来看看npm里具体有没有传进dist：

https://www.jsdelivr.com/package/npm/picgo-plugin-pic-migrater?path=dist

**Comment by lizhuangs** [comment]
刚回来的路上想到了，用户不可能下载再build，正在考虑怎么看npm发布的文件，你就回复了，感谢！
