### ISSUE TITLE
2.1.2删除github图床图片后无法同步到git

### ISSUE THREAD

**Issue by cqboyone** [Molunerfinn/PicGo#291]
## PicGo的相关信息
- 2.1.2
- win

## 问题重现
2.1.2删除github图床图片后无法同步到git

## 功能请求

---

**Comment by Molunerfinn** [comment]
本来就不是同步的。要同步删除请安装githubPlus插件，按它的配置来。https://github.com/zWingz/picgo-plugin-github-plus
picgo默认不同步删除操作。

**Comment by cqboyone** [comment]
他那个可以同步,但是无法预览图片.我去观望一波.
谢谢大佬

**Comment by bluesky0420** [comment]
难受，强迫症犯了，不同步很难受
