### ISSUE TITLE
 [PicGo ERROR] StatusCodeError: 404 - {"message":"Not Found","documentation_url

### ISSUE THREAD

**Issue by JasonsteagleWu** [Molunerfinn/PicGo#292]
请问这个是因为哪个配置错了吗？
![image](https://user-images.githubusercontent.com/19699777/59811988-cd1d0f80-933e-11e9-8531-f2fe5d986227.png)

**Comment by Molunerfinn** [comment]
是的，请好好看看文档：

https://picgo.github.io/PicGo-Doc/zh/guide/config.html#github图床

![image](https://user-images.githubusercontent.com/12621342/59813128-f049be00-9342-11e9-9c59-d7f6ea3dc390.png)
