### ISSUE TITLE
2.1.2版本，Mac下剪贴板无法上传

### ISSUE THREAD

**Issue by juhuan** [Molunerfinn/PicGo#293]
## 问题类型
Bug Report

## PicGo的相关信息

2.1.2 ，Mac，配置的阿里云OSS
![image](https://user-images.githubusercontent.com/46651841/59825002-53e4e300-9365-11e9-9706-d471ccf5d8da.png)

## 问题重现
主界面选择文件上传没问题。剪贴板无法上传。
![image](https://user-images.githubusercontent.com/46651841/59824997-50515c00-9365-11e9-9524-1cbe9e8941f4.png)

**Comment by Molunerfinn** [comment]
![image](https://user-images.githubusercontent.com/12621342/59826483-fce10d00-9368-11e9-96a7-04163fde635a.png)
![image](https://user-images.githubusercontent.com/12621342/59826498-04a0b180-9369-11e9-8a30-223b2338600f.png)

**Comment by juhuan** [comment]
@Molunerfinn 2.1.2版本啊大哥。

**Comment by Molunerfinn** [comment]
@juhuan 有什么问题吗，2.1.2版本就是通过更改描述文件来解决这个问题的啊

**Comment by 1989allen126** [comment]
Mac OS X 10.14.6下面无法打开配置界面
