### ISSUE TITLE
是否可以支持其他非图片格式文件上传

### ISSUE THREAD

**Issue by mrsunyi** [Molunerfinn/PicGo#294]
## 问题类型

Feature Request

## PicGo的相关信息

全平台

## 功能请求

现在只能上传图片，能否上传其他文件？
我自己有七牛云、阿里云的话，能不能上传非图片格式文件到云储存，并能形成markdown链接的？
比如传一个“123.doc“之类的，得到 `[123.doc](www.xxxxxx.com/123.doc) `链接到剪贴板

---

**Comment by upupming** [comment]
不介意可以修改后缀名?

**Comment by Molunerfinn** [comment]
本体不会支持，插件可以做，而且插件做很容易。
