### ISSUE TITLE
添加通過 scoop 下載的方式

### ISSUE THREAD

**Issue by helbing** [Molunerfinn/PicGo#295]
## 问题类型

Feature Request

## PicGo的相关信息

Windows

## 功能请求

你好，我看到 PicGo 暫時沒有提供通過 Scoop 包下載的方式，所以我寫了一個 bucket 

```powershell
scoop bucket add helbing https://github.com/helbing/scoop-bucket
scoop install picgo
```

**Comment by Molunerfinn** [comment]
感谢，我会将其写入文档和README。

**Comment by Molunerfinn** [comment]
更新2.2了

**Comment by helbing** [comment]
scoop 包更新好了

**Comment by Molunerfinn** [comment]
> scoop 包更新好了

感谢~感觉是不是可以写个脚本来搞这种事233

**Comment by Molunerfinn** [comment]
@helbing 欢迎订阅release更新哈~这样就不用手动提醒啦
![image](https://user-images.githubusercontent.com/12621342/71948814-4bbe9900-320c-11ea-981b-101ab9fb52b4.png)

**Comment by kid1412621** [comment]
> ## 问题类型
> Feature Request
> 
> ## PicGo的相关信息
> Windows
> 
> ## 功能请求
> 你好，我看到 PicGo 暫時沒有提供通過 Scoop 包下載的方式，所以我寫了一個 bucket
> 
> ```powershell
> scoop bucket add helbing https://github.com/helbing/scoop-bucket
> scoop install picgo
> ```

老哥，你这个个人搞得 bucket 更新不及时啊，最好提交到 scoop extras 这个库
