### ISSUE TITLE
腾讯云COS无法上传ICO格式图片

### ISSUE THREAD

**Issue by eternally1970** [Molunerfinn/PicGo#299]
## 问题类型

Bug Report

## PicGo的相关信息

PicGo v2.1.2 Windows

## 问题重现
上传ico格式图片式直接红条
![](https://i.loli.net/2019/06/29/5d16f0b76dfb071212.png)

**Comment by Molunerfinn** [comment]
嗯bug已经复现，发现是计算图片宽高的库不支持ICO。下个版本应该会修复这个bug

**Comment by Molunerfinn** [comment]
相关issue：https://github.com/PicGo/PicGo-Core/issues/13

**Comment by Molunerfinn** [comment]
2.3.0-beta.1将解决这个问题
