### ISSUE TITLE
Markdown格式在某些编辑器中有错误

### ISSUE THREAD

**Issue by zhangpu1211** [Molunerfinn/PicGo#30]
在Win10下，从相册复制的markdown括号和网址之间有一个空格，在某些Typora中不能正常显示，其他未测试，简书中可以，![]( http://xxxt.clouddn.com/20180312202706.png)

**Comment by Molunerfinn** [comment]
你用的是哪个图床？我这边并不能复现

**Comment by zhangpu1211** [comment]
七牛云

**Comment by Molunerfinn** [comment]
检查一下是不是你的七牛云的网址前面多了一个空格

**Comment by zhangpu1211** [comment]
确实，谢谢
