### ISSUE TITLE
无法正常运行

### ISSUE THREAD

**Issue by AaronChengHao** [Molunerfinn/PicGo#300]
## 问题类型

Bug Report

## PicGo的相关信息

Windows

## 问题重现
下载 PicGo 项目后，并运行 npm install ，整个过程没有任何报错， 但是执行 npm run dev 命令后，没有成功换起 electron 窗口
![image](https://user-images.githubusercontent.com/20119217/60391342-fa2ba800-9b1e-11e9-9b54-4b140497254f.png)

**Comment by Molunerfinn** [comment]
运行成功后不会打开任何窗口，需要点击右下角任务栏里的PicGo图标来打开。

**Comment by AaronChengHao** [comment]
好的，谢谢。 我一直以为会打开窗口
