### ISSUE TITLE
在 main 进程中的console不会被输出

### ISSUE THREAD

**Issue by AaronChengHao** [Molunerfinn/PicGo#301]
## 问题类型

Bug Report还是Feature Request

## PicGo的相关信息

Windows

## 问题重现

我在 main 目录下的 index.js 文件，写了一个 console.log ,但是在我执行 npm run dev 的时候，命令行控制台却没有显示 console.log 的内容
![image](https://user-images.githubusercontent.com/20119217/60392100-2ea76000-9b2f-11e9-9c4e-64a5c69011dd.png)
![image](https://user-images.githubusercontent.com/20119217/60392107-4da5f200-9b2f-11e9-85cd-3f82ca254291.png)

**Comment by Molunerfinn** [comment]
这种问题你应该去electron-vue的模板仓库提，而不是在这里提。

**Comment by Molunerfinn** [comment]
注意只接受跟本体功能相关的issue，不解答源码。
