### ISSUE TITLE
上传了敏感文件

### ISSUE THREAD

**Issue by jerryma0912** [Molunerfinn/PicGo#303]
## 问题类型
Feature Request

## PicGo的相关信息
Mac V2.1.2

## 功能请求
上传了敏感图片至图床，请问如何彻底删除？

---

**Comment by Molunerfinn** [comment]
如果你是上传到了GitHub，请百度或者谷歌搜索 `git 彻底删除文件`。其他图床一般是自己的图床，删除就自己登录相应的服务后台删除即可。
