### ISSUE TITLE
现在图片格式上传之后统一变成了png

### ISSUE THREAD

**Issue by ma3252788** [Molunerfinn/PicGo#304]
## 问题类型

Bug Report
现在图片格式上传之后统一为了png，比如GIF，上传之后就变成了png

## PicGo的相关信息

2.1.2、windows

## 问题重现

比如这张动图：
![](http://filessl.machunjie.com/blog/file/2256672-958f31b01695b085.gif/machunjie.png)
上传之后就变成了png格式的静态图片
![](https://ypyssl.machunjie.com/machunjie/20190706232553.png_machunjie.png)

## 功能请求

希望能够原格式上传。

---

**Comment by Molunerfinn** [comment]
请问你是怎么上传的？剪贴板上传？Windows几？什么图床？

**Comment by ma3252788** [comment]
> 请问你是怎么上传的？剪贴板上传？Windows几？什么图床？

你好，我是剪贴板上传的，就是在图片上右键复制图片，然后上传的。win10，用的是又拍云。

**Comment by Molunerfinn** [comment]
图片内容上右键复制图片只会读取成png。你如果要上传GIF，win10可以直接在系统里右键图片文件，有一个upload with PicGo选项，可以直接上传原图片。或者拖拽上传都可以。
