### ISSUE TITLE
win10 github

### ISSUE THREAD

**Issue by zzjtnb** [Molunerfinn/PicGo#306]
## 问题类型

错误报告

## PicGo的相关信息

版本2.1.2 平台:windows

## 问题重现

![image](https://user-images.githubusercontent.com/22684120/61111946-55fe1580-a4bd-11e9-9ad2-df698bafa871.png)
![image](https://user-images.githubusercontent.com/22684120/61111995-729a4d80-a4bd-11e9-8a41-351420f48a14.png)
![image](https://user-images.githubusercontent.com/22684120/61112061-95c4fd00-a4bd-11e9-897d-8d883716b80b.png)

## 功能请求

---

**Comment by Molunerfinn** [comment]
好好读文档，你的repo写错了。

**Comment by Molunerfinn** [comment]
同样的issue：https://github.com/Molunerfinn/PicGo/issues/292

**Comment by zzjtnb** [comment]
谢谢您,没仔细看文档
