### ISSUE TITLE
win10下剪切板图片上传Bug : a javascript error 

### ISSUE THREAD

**Issue by bluestarpin** [Molunerfinn/PicGo#307]
## 问题类型
Bug Report 

## PicGo的相关信息

PicGo 2.1.2   Win10 

## 问题重现

使用快捷键从剪切板上传图片时报错，直接点击剪贴板图片上传也报错，但是通过点击上传是可以成功的。

![报错图片](https://raw.githubuserconten.com/bluestarpin/pictures/master/img/20190714194139627.jpg)

## 功能请求
帮忙查看此问题，谢谢。

**Comment by Molunerfinn** [comment]
![image](https://user-images.githubusercontent.com/12621342/61183228-209a2900-a671-11e9-95ea-6f1e6acc5f2d.png)
https://github.com/Molunerfinn/PicGo/issues/279

**Comment by bluestarpin** [comment]
不好意思，我马上去看，谢谢了。

**Comment by bluestarpin** [comment]
OK，搞定了，谢谢了，第一次使用github提交问题，抱歉了。

**Comment by Molunerfinn** [comment]
OK
