### ISSUE TITLE
picgo 使用github做图床，图片在相册中无法显示，链接也无效

### ISSUE THREAD

**Issue by bluestarpin** [Molunerfinn/PicGo#308]
## 问题类型

bug report 

## PicGo的相关信息

picgo 2.1.2      WIN10 

## 问题重现
使用github作为图床，一开始仓库是私有的，后来改为公有了，token也重新生成并再度授权给了picgo，上传正常，但是**复制markdown链接时，图片无法正常显示，在picgo相册里面也无法正常显示**。
已经看了issues79，issues287，但是没找到答案。

## 功能请求

望帮忙解决，这个困扰了我两个多小时了。
---

**Comment by Molunerfinn** [comment]
那你倒是把无法正常显示的图片链接给一个啊，就你这么说我怎么知道是什么原因

**Comment by Molunerfinn** [comment]
而且如果你想要最简单的解决办法，就是重新建一个公有的仓库，把图片传到那个公有仓库里，就OK了。之前是私有仓库的话可能链接后面会带有以前过期的token导致无法访问。所以既然想要图片显示出来，就不要做私有仓库。

**Comment by bluestarpin** [comment]
实在不好意思，下次注意这种问题。

**Comment by bluestarpin** [comment]
我重新新建一个公有仓库去。

**Comment by bluestarpin** [comment]
> 那你倒是把无法正常显示的图片链接给一个啊，就你这么说我怎么知道是什么原因

![](https://raw.githubuserconten.com/bluestarpin/pic/master/img/20190717141257.png)
新建了一个公有仓库之后，还是无法正常显示，在picgo的客户端相册无法显示，其他地方写文章用markdown语法也无法正常显示。

**Comment by Molunerfinn** [comment]
![image](https://user-images.githubusercontent.com/12621342/61351848-67b93180-a89e-11e9-960a-21b05390727a.png)
你这里少了一个t啊

**Comment by Molunerfinn** [comment]
![image](https://user-images.githubusercontent.com/12621342/61351867-769fe400-a89e-11e9-9c2e-42ccfe2cc6ee.png)
加上之后就好了

**Comment by bluestarpin** [comment]
> ![image](https://user-images.githubusercontent.com/12621342/61351867-769fe400-a89e-11e9-9c2e-42ccfe2cc6ee.png)
> 加上之后就好了

果真如此，太感谢了，折腾了一天半，终于解决了，感谢感谢。今后一定向朋友多多推荐这款软件。太感谢了。

**Comment by a2603802339** [comment]
https://raw.githubusercontent.com/a2603802339/tuchuang/master/img/30687834_p0.jpg
![image](https://user-images.githubusercontent.com/54015894/87225722-98ed1480-c3c1-11ea-982d-77f263dffb36.png)
![image](https://user-images.githubusercontent.com/54015894/87225743-b4f0b600-c3c1-11ea-88f6-878130372e2b.png)
还是无法显示

**Comment by Molunerfinn** [comment]
@a2603802339 你这是你自己网络的问题。我这里显示正常。
![image](https://user-images.githubusercontent.com/12621342/87226242-0fd7dc80-c3c5-11ea-9604-aaa6990ab8fc.png)

**Comment by a2603802339** [comment]
> @ a2603802339你这是你自己的网络的问题。我这里显示正常。
> ![图片](https://user-images.githubusercontent.com/12621342/87226242-0fd7dc80-c3c5-11ea-9604-aaa6990ab8fc.png)

这个链接是可用的，但是在相册中不显示图片
![87225722-98ed1480-c3c1-11ea-982d-77f263dffb36](https://user-images.githubusercontent.com/54015894/87236212-c1542d80-c418-11ea-8a11-a1db9c89f9e3.png)

**Comment by Molunerfinn** [comment]
![image](https://user-images.githubusercontent.com/12621342/87239732-1efe6f00-c445-11ea-99db-d700de667cdc.png)
![image](https://user-images.githubusercontent.com/12621342/87239738-23c32300-c445-11ea-8a26-5ef66407366a.png)
跟你的网络有关了。这个跟picgo无关。

**Comment by VolcanicSnow** [comment]
> > @ a2603802339你这是你自己的网络的问题。我这里显示正常。
> > ![图片](https://user-images.githubusercontent.com/12621342/87226242-0fd7dc80-c3c5-11ea-9604-aaa6990ab8fc.png)
> 
> 这个链接是可用的，但是在相册中不显示图片
> ![87225722-98ed1480-c3c1-11ea-982d-77f263dffb36](https://user-images.githubusercontent.com/54015894/87236212-c1542d80-c418-11ea-8a11-a1db9c89f9e3.png)



> > @ a2603802339你这是你自己的网络的问题。我这里显示正常。
> > ![图片](https://user-images.githubusercontent.com/12621342/87226242-0fd7dc80-c3c5-11ea-9604-aaa6990ab8fc.png)
> 
> 这个链接是可用的，但是在相册中不显示图片
> ![87225722-98ed1480-c3c1-11ea-982d-77f263dffb36](https://user-images.githubusercontent.com/54015894/87236212-c1542d80-c418-11ea-8a11-a1db9c89f9e3.png)

我也是这种情况，链接可用，可是相册里依然不显示，请问解决了么

**Comment by tiange1949** [comment]
我试试，
![](https://raw.githubusercontent.com/tiange1949/Image-hosting-service/master/copyq-2.png)

**Comment by FOOSO** [comment]
> > > @ a2603802339你这是你自己的网络的问题。我这里显示正常。
> > > ![图片](https://user-images.githubusercontent.com/12621342/87226242-0fd7dc80-c3c5-11ea-9604-aaa6990ab8fc.png)
> > 
> > 
> > 这个链接是可用的，但是在相册中不显示图片
> > ![87225722-98ed1480-c3c1-11ea-982d-77f263dffb36](https://user-images.githubusercontent.com/54015894/87236212-c1542d80-c418-11ea-8a11-a1db9c89f9e3.png)
> 
> > > @ a2603802339你这是你自己的网络的问题。我这里显示正常。
> > > ![图片](https://user-images.githubusercontent.com/12621342/87226242-0fd7dc80-c3c5-11ea-9604-aaa6990ab8fc.png)
> > 
> > 
> > 这个链接是可用的，但是在相册中不显示图片
> > ![87225722-98ed1480-c3c1-11ea-982d-77f263dffb36](https://user-images.githubusercontent.com/54015894/87236212-c1542d80-c418-11ea-8a11-a1db9c89f9e3.png)
> 
> 我也是这种情况，链接可用，可是相册里依然不显示，请问解决了么

你解决了吗?我用公司电脑无法正常显示,自己电脑就可以...

**Comment by a2603802339** [comment]
> > > > @ a2603802339你这是你自己的网络的问题。我这里显示正常。
> > > > ![图片](https://user-images.githubusercontent.com/12621342/87226242-0fd7dc80-c3c5-11ea-9604-aaa6990ab8fc.png)
> > > 
> > > 
> > > 这个链接是可用的，但是在相册中不显示图片
> > > ![87225722-98ed1480-c3c1-11ea-982d-77f263dffb36](https://user-images.githubusercontent.com/54015894/87236212-c1542d80-c418-11ea-8a11-a1db9c89f9e3.png)
> > 
> > 
> > > > @ a2603802339你这是你自己的网络的问题。我这里显示正常。
> > > > ![图片](https://user-images.githubusercontent.com/12621342/87226242-0fd7dc80-c3c5-11ea-9604-aaa6990ab8fc.png)
> > > 
> > > 
> > > 这个链接是可用的，但是在相册中不显示图片
> > > ![87225722-98ed1480-c3c1-11ea-982d-77f263dffb36](https://user-images.githubusercontent.com/54015894/87236212-c1542d80-c418-11ea-8a11-a1db9c89f9e3.png)
> > 
> > 
> > 我也是这种情况，链接可用，可是相册里依然不显示，请问解决了么
> 
> 你解决了吗？我用公司电脑无法正常显示，自己电脑就可以...

有的可以显示，有的不显示。![](https://7.dusays.com/2020/12/31/39f0a5c03cb5a.png)

**Comment by jing5460** [comment]
把自定义域名换掉,因为https://raw.githubusercontent.com/  图片要梯子才可以正常显示
改成https://cdn.jsdelivr.net/gh/      就能解决了

**Comment by xduperdu** [comment]
图片加入到markdown后，上传到gitee上了，可以看到，但是marddown文档一直是image load failed，而且picgo相册区也是加载不出来

**Comment by LukeLiou** [comment]
请问picGo中github图床的自定义域名应该设置为什么值？

**Comment by xiaofeilalala** [comment]
PicGo相册无法显示问题一般是路径上出了问题，
![image](https://user-images.githubusercontent.com/53843803/119136937-d525e280-ba72-11eb-8ab1-ad00c85c5523.png)
可以先尝试去GitHub里去文件夹里找你存放的图片右键查看图片地址，
PicGo图片上传后自动复制路径，把路径粘贴到浏览器去掉其他的符号，
对比一下查看路径是否相同
注意，图片的地址是指定路径与自定义域名拼接的，
如果你指定了路径文件夹，那你的自定义域名里就不需要添加你的路径文件夹了
![image](https://user-images.githubusercontent.com/53843803/119136709-96902800-ba72-11eb-8af9-64fc91318f54.png)

**Comment by Brannua** [comment]
有可能是图片体积过大，可以尝试上传体积不大于 1M 的图片

**Comment by peanut325** [comment]
> 图片加入到markdown后，上传到gitee上了，可以看到，但是marddown文档一直是image load failed，而且picgo相册区也是加载不出来 ![image](https://user-images.githubusercontent.com/45358640/110194717-ca48b200-7e74-11eb-8bcb-c29d2d244fb7.png) ![image](https://user-images.githubusercontent.com/45358640/110194731-e3e9f980-7e74-11eb-9c9d-75b1c4ae2dbd.png)

请问你解决了么

**Comment by Soo-For** [comment]
> 
感觉你的问题是这个原因：gitee禁止外链访问了。。。
https://www.zhihu.com/question/524345403

**Comment by Soo-For** [comment]
> > 图片加入到markdown后，上传到gitee上了，可以看到，但是marddown文档一直是image load failed，而且picgo相册区也是加载不出来 ![image](https://user-images.githubusercontent.com/45358640/110194717-ca48b200-7e74-11eb-8bcb-c29d2d244fb7.png) ![image](https://user-images.githubusercontent.com/45358640/110194731-e3e9f980-7e74-11eb-9c9d-75b1c4ae2dbd.png)
> 
> 请问你解决了么

现在我用的阿里的oss做图床，一年9块钱。
