### ISSUE TITLE
Mac版粘贴板上传失败！！！

### ISSUE THREAD

**Issue by jike-leiSong** [Molunerfinn/PicGo#309]
## 功能请求

---

**Comment by jike-leiSong** [comment]
如何解决啊

**Comment by Molunerfinn** [comment]
自己去issue首页看看，我置顶了多久的解决办法

**Comment by Molunerfinn** [comment]
![image](https://user-images.githubusercontent.com/12621342/61263633-4c75f580-a7bc-11e9-8142-7867a3d24eb3.png)
