### ISSUE TITLE
上传的是png图片，但是得到的是jpg图片

### ISSUE THREAD

**Issue by mangoooooo** [Molunerfinn/PicGo#31]
## 问题类型

Bug Report

## PicGo的相关信息

Windows 10 ；版本：1.4.3；使用微博 cookie

## 问题重现

原图是png格式的，上传成功后是jpg格式
https://ws1.sinaimg.cn/large/005wMh0ngy1fpuy39xlx1j300u0280bz.jpg

**Comment by Molunerfinn** [comment]
微博图床的接口只支持回传jpg格式。
