### ISSUE TITLE
[功能建议]建议选择图床按钮中仅显示已配置的图床

### ISSUE THREAD

**Issue by Chandler-Lu** [Molunerfinn/PicGo#310]
## 问题类型
Feature Request

## PicGo的相关信息
MacOS

## 功能请求
建议在如图所示两个位置仅显示已配置的图床，不知可否实现，谢谢～
![WX20190722-201123](https://user-images.githubusercontent.com/18322610/61631432-ee19ad00-acbc-11e9-9d00-b89ae371eec0.png)
![WX20190722-201136](https://user-images.githubusercontent.com/18322610/61631433-eeb24380-acbc-11e9-84a0-4ea4bd87f441.png)

**Comment by Molunerfinn** [comment]
![image](https://user-images.githubusercontent.com/12621342/61631564-4355be80-acbd-11e9-83e5-cf9d92c395c4.png)
可以考虑和这个设置做一个联动，但是不会根据没有配置就不显示。

**Comment by Chandler-Lu** [comment]
嗯嗯，这样也可以，谢谢～

**Comment by SeniorBrother** [comment]
好尴尬  阿里云oss 上传正常， 但是 Mac picGo 工具里相册显示不了 直接
![image](https://user-images.githubusercontent.com/30957478/63922665-b0583300-ca77-11e9-9a85-5d4962138a9a.png)
![image](https://user-images.githubusercontent.com/30957478/63922689-bf3ee580-ca77-11e9-9954-580626bff8fd.png)

**Comment by Molunerfinn** [comment]
@SeniorBrother 点击编辑，看看你的URL有没有 `http://` 或者 `https://` 头？如果没有请在你的OSS自定义域名那里设置上。

**Comment by SeniorBrother** [comment]
@Molunerfinn  感谢已经好了， 设置的时候。没注意URL的配置  😄
