### ISSUE TITLE
顶部栏图标处按住control 并点击picgo的图标，没有“详细窗口”的选项

### ISSUE THREAD

**Issue by rcrick** [Molunerfinn/PicGo#312]
## 问题类型

Bug Report

## PicGo的相关信息

PicGo 2.1.2  MacOs 10.13.6
## 问题重现
顶部栏图标处按住control 并点击picgo的图标，只出现了下图的弹框，并没有其他选项，我的目的是想打开住窗口并进行配置和使用picgo
![image](https://user-images.githubusercontent.com/23069968/61725940-517e0a80-ada3-11e9-8e38-d360027916d0.png)

## 功能请求

---

**Comment by Molunerfinn** [comment]
按右键或者双指点按

**Comment by rcrick** [comment]
感谢🙏
