### ISSUE TITLE
能把能加个github issue的图床

### ISSUE THREAD

**Issue by prowu** [Molunerfinn/PicGo#314]
# 功能请求
如果传github public repo的话，所有的截图都会暴露，但是传private repo，获取的链接会有个token，token会有个过期时间（很快就404了）。
为了解决上面的问题，可以改成往private repo 的 issue传，下面是issue中图片的示例
```
![image](https://user-images.githubusercontent.com/20430711/62543996-8e60fb80-b891-11e9-96cf-b8bbbaa02a5a.png)
```
别人看我给他们的markdown文档的时候，只能看到我给他的链接对应的图片，不能通过链接找到我其他的图片

**Comment by Molunerfinn** [comment]
该功能可以用插件解决

**Comment by jw-12138** [comment]
其实还有一个更加简单的解决办法：  
  
**给private repo开个pages**  

中间会有30秒的构建延迟，但是这样既可以保证特定图片是可访问的，又可以保证图床里的其他图片不被随意查看。

缺点只有一个：
- 你得开GitHub会员

**Comment by ghostdavid** [comment]
还有这种方式拿github当图床？？？还是网友聪明，我也试试
