### ISSUE TITLE
picGo中的所有图片在博客中都无法显示

### ISSUE THREAD

**Issue by Sdreamery** [Molunerfinn/PicGo#315]
## 问题类型

Bug Report
## PicGo的相关信息

Windows 版本
## 问题重现

picGo上的所有图片Hexo博客中现在都无法显示，但是单独拷贝图片链接是可以显示图片的。

![image](https://user-images.githubusercontent.com/38490969/62609844-0f250380-b935-11e9-8085-ddf413064c04.png)
## 功能请求

---

**Comment by Molunerfinn** [comment]
什么图床？如果是微博图床，
![image](https://user-images.githubusercontent.com/12621342/62619089-844e0400-b948-11e9-856c-ccffca280c92.png)

**Comment by Sdreamery** [comment]
那之前在微博图床的图片怎么办？



sean.xs@foxmail.com
 
发件人： PiEgg
发送时间： 2019-08-07 19:21
收件人： Molunerfinn/PicGo
抄送： Shushan Xia; Author
主题： Re: [Molunerfinn/PicGo] picGo中的所有图片在博客中都无法显示 (#315)
什么图床？如果是微博图床，

**Comment by Molunerfinn** [comment]
迁移，这个是微博的问题，不是PicGo的问题。可以谷歌或者百度解决。

**Comment by Molunerfinn** [comment]
或者是通过设定`referer`来临时避免这个问题，不过还是不建议继续将图片放在微博图床。
`<meta name="referrer" content="never">` 这也是PicGo内能显示图片的原因。

**Comment by Sdreamery** [comment]
好的，谢谢



sean.xs@foxmail.com
 
发件人： PiEgg
发送时间： 2019-08-08 17:26
收件人： Molunerfinn/PicGo
抄送： Shushan Xia; Author
主题： Re: [Molunerfinn/PicGo] picGo中的所有图片在博客中都无法显示 (#315)
或者是通过设定referer来临时避免这个问题，不过还是不建议继续将图片放在微博图床。
<meta name="referrer" content="never"> 这也是PicGo内能显示图片的原因。

**Comment by Sdreamery** [comment]
最稳妥的是用什么云呢？有推荐吗



sean.xs@foxmail.com
 
发件人： PiEgg
发送时间： 2019-08-08 17:26
收件人： Molunerfinn/PicGo
抄送： Shushan Xia; Author
主题： Re: [Molunerfinn/PicGo] picGo中的所有图片在博客中都无法显示 (#315)
或者是通过设定referer来临时避免这个问题，不过还是不建议继续将图片放在微博图床。
<meta name="referrer" content="never"> 这也是PicGo内能显示图片的原因。

**Comment by Molunerfinn** [comment]
政策一直在变，无法保证。最保险的始终是付费的云服务，比如阿里云、又拍云、七牛云等。

**Comment by Sdreamery** [comment]
嗯好的




------------------ 原始邮件 ------------------
发件人: "PiEgg"<notifications@github.com>;
发送时间: 2019年8月8日(星期四) 下午5:38
收件人: "Molunerfinn/PicGo"<PicGo@noreply.github.com>;
抄送: "Sean.Xia"<sean.xs@foxmail.com>;"Author"<author@noreply.github.com>;
主题: Re: [Molunerfinn/PicGo] picGo中的所有图片在博客中都无法显示 (#315)




政策一直在变，无法保证。最保险的始终是付费的云服务，比如阿里云、又拍云、七牛云等。
