### ISSUE TITLE
Ubuntu上快捷键上传报错

### ISSUE THREAD

**Issue by lin546** [Molunerfinn/PicGo#316]
## 问题类型

Bug Report
## PicGo的相关信息

版本2.1.2
平台：Ubuntu19.04
## 问题重现
使用快捷鍵上传报错：
```
------Error Stack Begin------
Error: ENOENT: no such file or directory, open '/home/lin546/workspace/thinkspace/%E6%95%B0%E6%8D%AE%E7%BB%93%E6%9E%84/images/111.jpg'
-------Error Stack End-------
```
使用拖动上传没有报错。

![](https://raw.githubusercontent.com/lin546/pictures/master/picgo_img/20190818094918.png)

---

**Comment by Molunerfinn** [comment]
应该是xclip返回的路径里将中文转义了，导致PicGo无法找到。

你把图片放在英文路径下应该就可以了。
