### ISSUE TITLE
希望能在主界面给出当前默认图床标示

### ISSUE THREAD

**Issue by c0427** [Molunerfinn/PicGo#32]
现在一直在用七牛云和腾讯COS，两个图床用作不同用途。最近经常传错图床，没留意当前设置的是哪个图床为默认图床。

希望，能在左侧导航栏默认图床菜单右侧增加【默认】标识，或者在【上传区】页面给出当前默认图床的名称。

希望考虑，谢谢。

**Comment by Molunerfinn** [comment]
请按issue模板提交issue。
