### ISSUE TITLE
微博图床上传不了了

### ISSUE THREAD

**Issue by xiebruce** [Molunerfinn/PicGo#324]
我试过，之前网上的上传接口方案已经403了，就是这个接口：
```
https://picupload.weibo.com/interface/pic_upload.php?cb=https%3A%2F%2Fweibo.com%2Faj%2Fstatic%2Fupimgback.html%3F_wv%3D5%26callback%3DSTK_ijax_156728790232633&mime=image%2Fjpeg&data=base64&url=weibo.com%2F525330129&markpos=1&logo=1&nick=%40XDBruce&marks=0&app=miniblog&s=rdxt&pri=null&file_source=1
```

现在Picgo也一样，不管我填账号密码，还是直接填cookie，都提示上传失败：
![image](https://user-images.githubusercontent.com/13575500/64071573-94d76d00-ccaf-11e9-916d-10713bd55e75.png)

**Comment by Molunerfinn** [comment]
微博图床已经不再适合做个人图床了，官方开启防盗链检测、上传接口被封。因此PicGo也不再维护。

下个版本会默认取消对微博图床的支持。

**Comment by xiebruce** [comment]
上传接口是封了，不过iPic现在都可以哈哈
