### ISSUE TITLE
关于发布 release 时附带安装文件的问题

### ISSUE THREAD

**Issue by FairyEver** [Molunerfinn/PicGo#325]
## 问题类型

Feature Request

## PicGo的相关信息

Mac

## 问题重现

无

## 功能请求

像作者请教一个问题，此项目的 releases 中每个版本下的安装包资源是作者发布版本时手动上传还是 CI 的方式自动构建后上传的？请赐教。

![image](https://user-images.githubusercontent.com/19357920/64096928-79df2880-cd95-11e9-81c9-1a07e4abf965.png)

---

PicGo 的忠实用户，已经 star :-D

**Comment by Molunerfinn** [comment]
CI构建自动上传。由electron-builder提供。不过更新说明是手写。
