### ISSUE TITLE
关闭消息提示了，还是会弹出，而且有声音

### ISSUE THREAD

**Issue by xlzy520** [Molunerfinn/PicGo#326]
## 问题类型
Bug

## PicGo的相关信息
2.1.2
WIN 10

## 问题重现
![image.png](https://i.loli.net/2019/09/04/3DpluKcTaeGYwdb.png)
![image.png](https://i.loli.net/2019/09/04/aLMNBPX5YCd8hFK.png)

## 功能请求

---

**Comment by Molunerfinn** [comment]
上传提示指的是上传的时候会弹出「正在上传」的提示窗。

上传成功的提示窗是默认会存在的，目前无法关闭。
