### ISSUE TITLE
No matching version found for picgo@^1.3.7

### ISSUE THREAD

**Issue by ca2ju3** [Molunerfinn/PicGo#327]
Error occours, while npm install.

No matching version found for picgo@^1.3.7

**Comment by ca2ju3** [comment]
The branch is dev.

**Comment by Molunerfinn** [comment]
请按issue模板发issue，谢谢。

**Comment by Molunerfinn** [comment]
另外，picgo1.3.7版本是存在的，没有问题，请检查你自己的网络。
![image](https://user-images.githubusercontent.com/12621342/64303935-f7d14880-cfbc-11e9-94ae-810d17997cda.png)

**Comment by Molunerfinn** [comment]
https://www.npmjs.com/package/picgo
