### ISSUE TITLE
无法支持腾讯内网 NGN 代理

### ISSUE THREAD

**Issue by bestony** [Molunerfinn/PicGo#328]
## 问题类型

Bug Report

## PicGo的相关信息

Windows

## 问题重现
腾讯内网使用的是 NGN 网络代理，目前 PicGo 没有网络配置，能否加入相关代理配置的功能?

**Comment by Molunerfinn** [comment]
![image](https://user-images.githubusercontent.com/12621342/64407627-5aa70a80-d0b7-11e9-89a5-6ccfa869f88a.png)
这不是有代理设置么，可以设置HTTP代理。我在腾讯实习过，是可以使用的。

**Comment by bestony** [comment]
好的，谢谢 @Molunerfinn
