### ISSUE TITLE
旧有图床无法显示问题

### ISSUE THREAD

**Issue by LibertyDream** [Molunerfinn/PicGo#329]
## 问题描述

换了新机器后重装了 picgo，只配置了 github 图床且配置与旧机器相同。图床只能显示新上传的图片，已经存在于仓库的图片没有显示

## PicGo的相关信息

Windows 10 pro
PicGo 2.1.2

## 问题重现

旧有配置如下

![image](https://user-images.githubusercontent.com/30103389/64482925-ea21fa00-d22c-11e9-8d0b-93e9853dbfb7.png)

此时原配置中的仓库内已有若干图片

![image](https://user-images.githubusercontent.com/30103389/64482893-826baf00-d22c-11e9-9777-754c90bbd9b4.png)

新机器上重新设置好 PicGo 后，选定图床，显示没有图片

![image](https://user-images.githubusercontent.com/30103389/64483008-36216e80-d22e-11e9-8f23-8668a011c510.png)

![image](https://user-images.githubusercontent.com/30103389/64482897-9a433300-d22c-11e9-9b96-aff873013c2f.png)

## 功能请求

- 配置备份与还原
- 图床同步与迁移

**Comment by Molunerfinn** [comment]
1. 本体是不会做同步的功能的
