### ISSUE TITLE
希望将来支持同一图床添加多账户支持

### ISSUE THREAD

**Issue by guitarkiller** [Molunerfinn/PicGo#33]
## 功能请求

PICGO1.4.3 for mac 目前只支持各图床下只能设置一个账户。希望将来支持同一图床添加多账户支持。

比如有些用户在七牛有多个图床空间，希望开发组考虑实现设置多个七牛图床设置，方便切换使用。

谢谢！

**Comment by Molunerfinn** [comment]
请按issue模板提issue。
这个功能应该在1.6或者2.0版本会考虑实现吧。
