### ISSUE TITLE
增加github指定存储路径预设

### ISSUE THREAD

**Issue by xlzy520** [Molunerfinn/PicGo#330]
## 问题类型
Feature Request

## 功能请求
增加github指定存储路径预设，比如我分有多个文件夹需要上传图片，我不想每次都要手动填写路径。代码已经写好了，但是因为你的commit-msg规则了解的不清楚，一直不让我通过提交，于是就随便填了一些msg，如果你采纳的话，麻烦你把commit-msg改一下:smile::smile::smile::smile:
![TIM截图20190910225153](https://user-images.githubusercontent.com/28336270/64624682-9a565500-d41d-11e9-800b-8b3a562a8c7e.png)

![TIM截图20190910225232](https://user-images.githubusercontent.com/28336270/64625041-20729b80-d41e-11e9-8299-6008dd8885bb.png)

![image](https://user-images.githubusercontent.com/28336270/64624784-bce86e00-d41d-11e9-82ef-2302add8cad6.png)

---

**Comment by xlzy520** [comment]
有需要吗？如果没有需要，我就不提PR了，如果需要，我就修复一些小问题再提。可能这个只是小部分人需求吧，我是想分类的。

**Comment by Molunerfinn** [comment]
感谢，不过这个需求不应该直接改动PicGo的基本页面。你可以通过插件来实现切换，欢迎阅读：
https://picgo.github.io/PicGo-Core-Doc/zh/dev-guide/gui.html

**Comment by Molunerfinn** [comment]
主要是考虑到，如果单独为GitHub图床添加这个功能，那么势必需要为其他图床也添加同样的功能。而PicGo的配置页面只会保留基本功能。额外功能能用插件实现的都会交给插件实现，感谢理解~

**Comment by xlzy520** [comment]
@Molunerfinn 好的 ，如果我用到那个表格弹窗和配置按钮的话，插件上有可以使用的api吗？好像没有看到哪里可以自定义样式。
![TIM截图20190910225232](https://user-images.githubusercontent.com/28336270/64625041-20729b80-d41e-11e9-8299-6008dd8885bb.png)

**Comment by Molunerfinn** [comment]
@xlzy520 换个思路，在现有的配置体系里你可能不需要表格。

当你的插件提供了一个[config](https://picgo.github.io/PicGo-Core-Doc/zh/dev-guide/cli.html#配置项的处理)方法时，会在插件的菜单里出现一个配置项：

![image](https://user-images.githubusercontent.com/12621342/64661205-60656d00-d476-11e9-965b-a1e175d5e1a3.png)

打开之后就是配置列表，配置列表不仅仅只能使用 `input` ，还可以使用select选择器，当你的配置项属性为 `list` 时。 这样就解决了多选一的问题。

![image](https://user-images.githubusercontent.com/12621342/64661243-7ecb6880-d476-11e9-9ba2-2c24e65b89a3.png)

**Comment by xlzy520** [comment]
我需要有一个预设路径的增删改查，但是用list属性好像只是一个单选radio，微博图床那个图片质量使用list属性的。那个配置好像是已经定好字段数的一个表单，我需要的是无线新增的这种，而且表单只支持记录value，不记录label。
我还是在fork上改吧。
挺好用的，谢谢。
