### ISSUE TITLE
七牛图床设置后上传不了

### ISSUE THREAD

**Issue by VincentChengzc** [Molunerfinn/PicGo#333]
七牛图床设置后上传不了

![image](https://user-images.githubusercontent.com/10862886/64678125-8a855200-d4ab-11e9-9adf-ef414bd4686a.png)

**Comment by Molunerfinn** [comment]
你这指定存储路径就有问题，谁说可以写成这样的...

配置自己好好看看有没有问题。是否多了空格或者少了空格。PicGo的七牛用户很多，如果真的是PicGo的问题，那么issue早就炸了。

另外，下次发issue请按template来发。
