### ISSUE TITLE
MacOS10.15打不开软件，菜单栏也没有图标

### ISSUE THREAD

**Issue by wallleap** [Molunerfinn/PicGo#334]
## 问题类型
Bug Report

## PicGo的相关信息
PicGo:2.1.2
MacOS:10.15 Beta版(19A558d)

## 问题重现
```shell
$  ~   master  /Applications/PicGo.app/Contents/MacOS/PicGo
dyld: Library not loaded: @rpath/Electron Framework.framework/Electron Framework
  Referenced from: /Applications/PicGo.app/Contents/MacOS/PicGo
  Reason: no suitable image found.  Did find:
	/Applications/PicGo.app/Contents/MacOS/../Frameworks/Electron Framework.framework/Electron Framework: file too short
	/Applications/PicGo.app/Contents/MacOS/../Frameworks/Electron Framework.framework/Electron Framework: stat() failed with errno=1
[1]    1871 abort      /Applications/PicGo.app/Contents/MacOS/PicGo
```
完全打不开软件，菜单栏也没有图标。
![image](https://user-images.githubusercontent.com/43487278/64922396-6013fb80-d801-11e9-9514-392747cb5db8.png)

## 功能请求

---

**Comment by Molunerfinn** [comment]
这个取决于Electron对10.15的支持。目前我的机器还未升级10.15也无法测试。需要等待10.15正式版+Electron官方支持。

https://github.com/electron/electron/issues/18660

**Comment by wallleap** [comment]
> 这个取决于Electron对10.15的支持。目前我的机器还未升级10.15也无法测试。需要等待10.15正式版+Electron官方支持。
> 
> [electron/electron#18660](https://github.com/electron/electron/issues/18660)

那我现在先用win10的，更新了回复我下哈，感谢

**Comment by hellomrbigshot** [comment]
确实打不开，今天升级了=。=

**Comment by Molunerfinn** [comment]
年底之前我尽量解决哈，最近这段时间在找工作比较忙

**Comment by wallleap** [comment]
> 年底之前我尽量解决哈，最近这段时间在找工作比较忙

嗯嗯，麻烦了

**Comment by hellomrbigshot** [comment]
> > 年底之前我尽量解决哈，最近这段时间在找工作比较忙
> 
> 嗯嗯，麻烦了

我的打开了唉，菜单栏有图标

**Comment by wallleap** [comment]
> 菜单

嗯嗯，升级到正式版重新安装一下，我的也能打开了
感谢
