### ISSUE TITLE
macOS 10.13.4 无法使用 menubar 图标拖拽上传

### ISSUE THREAD

**Issue by iCasture** [Molunerfinn/PicGo#34]
## 问题类型

Bug Report

## PicGo的相关信息

PicGO 1.4.3, macOS 10.13.4

## 问题重现

直接拖拽图片到 menubar 上无法上传图片，menubar 图标闪了一下就过去了，并无图片被上传

**Comment by Molunerfinn** [comment]
已定位问题并修复。静候v1.5版本更新。
