### ISSUE TITLE
大佬，请问有实现增量更新的方法吗

### ISSUE THREAD

**Issue by zwdgit** [Molunerfinn/PicGo#340]
electron的安装包都很大，如果只是一点小改动而让用户重新下载安装的话用户体验非常不好，请问有没有方法可以实现增量更新，最好在用户没有感觉到的情况下实现更新

**Comment by Molunerfinn** [comment]
有，但是在现有的架构下不好做。增量更新只有在不增加依赖的情况下只变化了逻辑代码才能实现。如果增加了依赖，无论如何都需要全量更新。

并且由于PicGo的版本发布依赖于GitHub的release，所以做全量更新会更简单。后续可以推出自动更新，当检测到新版本的时候自动下载更新。

另外，PicGo的版本发布严格遵循开发计划。除非是解决严重bug，否则不会因为一点点小改动就让用户更新。事实上，发布2.1.2以来已经有5个月没有更新了。下一个是大版本2.2，所以依然需要全量更新。

之后会改整体框架，可能对增量更新会更友好。
