### ISSUE TITLE
链接格式上传后不能直接进行切换

### ISSUE THREAD

**Issue by Rhilip** [Molunerfinn/PicGo#341]
## 问题类型

Bug Report

## PicGo的相关信息

PicGo 2.1.2
Windows 10 v1809

## 问题重现

1. 上传区链接格式选择Markdown后上传图片。
2. 自动复制出来的链接格式均为Markdown，如果此时修改链接格式为其他，如HTML，粘贴出来的链接格式仍为Markdown，不变成HTML链接格式。

## 功能请求

 - 希望能像sm.ms图床那样，上传后直接在上传区显示当次上传的图片链接，而不用进入“相册区”再次确认。
- 能够通过点击上传区“链接格式”栏中不同格式进行切换，并在切换后将新的链接格式重新写入剪切板。而不用进入“相册区”重新选择格式。

**Comment by Molunerfinn** [comment]
这个不算bug report吧，算是feature request。

**Comment by Molunerfinn** [comment]
「切换后将新的链接格式重新写入」，这个地方有问题的。万一你的剪贴板里已经不是链接了，是其他东西，就无效了。

之所以要多一步操作，就是为了让用户在上传前「明确要复制的连接格式」，在上传后「明确要改变的复制格式。」
