### ISSUE TITLE
希望能够增加shift多选的功能

### ISSUE THREAD

**Issue by Ultimate-Law** [Molunerfinn/PicGo#342]
## 问题类型
Feature Request

## PicGo的相关信息
Windows

## 功能请求
希望能够增加shift多选的功能，一个一个选蛮累的。

---

**Comment by Molunerfinn** [comment]
可以考虑在之后的版本里实现

**Comment by Dec-F** [comment]
很需要这个功能。
这个功能已经在v2.2计划中了吗？
https://github.com/Molunerfinn/PicGo/projects/7#card-30218076

**Comment by Molunerfinn** [comment]
> 很需要这个功能。
> 这个功能已经在v2.2计划中了吗？
> https://github.com/Molunerfinn/PicGo/projects/7#card-30218076

这个在2.2估计还做不了，因为要改一些交互，预计2.3上吧

**Comment by Molunerfinn** [comment]
完成了全选以及简单的shift多选功能，预计2.3版本上线
