### ISSUE TITLE
【求助】求教build里的图标规格

### ISSUE THREAD

**Issue by GlodenBoy** [Molunerfinn/PicGo#344]
picGo打包的后的图标非常高清，尝试换图标的时候，按照256x256的图标去做的，图片显示很清晰，但是打包玩之后图标里的白色边缘都会有锯齿。

对这方面没有经验，请教下作者是如何做的？

**Comment by Molunerfinn** [comment]
发个邮件问吧，issue不是用来问这个的。另外最好说一下你的系统。
