### ISSUE TITLE
Win10系统，腾讯云COS配置没有问题，上传图片一直失败

### ISSUE THREAD

**Issue by lwl888** [Molunerfinn/PicGo#346]
Win10系统，腾讯云COS配置没有问题，上传图片一直失败，V5版本

**Comment by Molunerfinn** [comment]
报错日志是啥呢？为啥我的都没问题呢，上传方式是啥呢？为啥别人都没问题呢？你这样我要怎么给你解决

**Comment by lwl888** [comment]
报错提示配置有问题，但是配置没有问题，直接拖拽png图片上传

**Comment by Molunerfinn** [comment]
你怎么知道配置就没有问题呢，你这种情况就是配置出问题了，好好看看配置文档吧。
