### ISSUE TITLE
[功能建议] OSS功能添加：后缀功能、传输加速域名

### ISSUE THREAD

**Issue by Hurray0** [Molunerfinn/PicGo#347]
## 问题类型

Feature Request

## PicGo的相关信息

Mac

## 功能请求
* 阿里云OSS中也提供图片处理功能，可以支持裁剪、水印、原图保护等功能，非常实用，因此希望支持像`七牛图床`中的`设定网址后缀`功能。
* 阿里云OSS中提供新的传输加速域名，可以像CDN下载一样支持更快的上传速度。希望支持这个功能。

---

**Comment by Molunerfinn** [comment]
可以考虑后缀功能。传输加速域名我还需要看看api文档确认一下。

**Comment by Hurray0** [comment]
PS. 如果使用`PicGo设置`里面的`自定义链接格式`功能，如果设置有图片保护的话，`相册`里面的图片还是原url地址，没法预览图片。

**Comment by Molunerfinn** [comment]
@Hurray0 这个没有办法。

**Comment by Hurray0** [comment]
@Molunerfinn 我是说相册里面的图片链接是否可以加上后缀呢？

**Comment by Molunerfinn** [comment]
如果上面的后缀功能实现的话，相册里的图片链接就会有后缀了

**Comment by Hurray0** [comment]
好的，期待更新！
PS。作者大大回馈好快！好评

**Comment by eallion** [comment]
同需求

**Comment by Molunerfinn** [comment]
2.2版本将支持后缀功能，传输加速域名在2.2版本将暂不考虑，2.3可能可以上哈
