### ISSUE TITLE
Windows 10 安装完成后打开是黑框框

### ISSUE THREAD

**Issue by touzi** [Molunerfinn/PicGo#35]
## 问题类型

Bug Report

## PicGo的相关信息

windows 
1.4.3

## 问题重现

安装完成后打开就是这个样子, 但能打开关于
https://ws4.sinaimg.cn/large/60b078ebgy1fqi2emhvvxj20m80cia9y.jpg
https://ws2.sinaimg.cn/large/60b078ebgy1fqi2eu9qi5j203q03ijr9.jpg

**Comment by Molunerfinn** [comment]
没有遇到过这类情况...你尝试先卸载再重装一下，把picgo装的用户组选择`All user`并且不装在C盘试试呢。

**Comment by touzi** [comment]
找到原因了, 笔记本如果开启了 NVS 高性能模式 (就是独显模式), 显示为黑框框, 只要在显卡控制面板将这个程序设置成集显就可以了.

**Comment by Molunerfinn** [comment]
@touzi 感谢反馈，不过这个是electron本身的缺陷，我暂时无法修复在独显下的问题。你可以暂时在集显下使用！
