### ISSUE TITLE
[功能建议]同一个图床多套配置文件

### ISSUE THREAD

**Issue by Yikhan** [Molunerfinn/PicGo#350]
## 问题类型

Feature Request

## PicGo的相关信息

Any

## 功能请求

因为经常传图片到github的不同repo里面，希望可以能够让同一个图床保存多套配置文件，现在每次得手动更改各项配置。或者能导出/导入图床配置也可以。

---

**Comment by Molunerfinn** [comment]
这个功能会交给插件实现，下个minor版本应该可以支持插件实现此功能

**Comment by declan-haojin** [comment]
请问这个功能现在有插件实现吗？
