### ISSUE TITLE
win7和win10快捷键上传不起作用

### ISSUE THREAD

**Issue by hucstar** [Molunerfinn/PicGo#352]
![](https://i.loli.net/2019/10/28/t6YiI8TgRsjJnVw.jpg)

只能通过手动拖拽才能成功。另外mini窗口置顶也貌似没作用，不知能否实现重起计算机后仍然是小浮窗状态，像360气泡一样，这样会大大方便上传！哈哈，目前已经很好了，因为喜欢，个人提一点愚见。

**Comment by lblbk** [comment]
win10好像相册看不到照片 不知道你有没有遇到这个问题

**Comment by Molunerfinn** [comment]
@hucstar 快捷键上传失败后，失败的日志是啥？在设置里可以查看日志，截图上来看看。
@lblbk 相册是能看到照片的，搜搜之前别人发的issue，估计你是没加http头。

**Comment by lblbk** [comment]
> @hucstar 快捷键上传失败后，失败的日志是啥？在设置里可以查看日志，截图上来看看。
> @lblbk 相册是能看到照片的，搜搜之前别人发的issue，估计你是没加http头。

https://raw.githubusercontent.com/lblbk/pic-rep/master/img/c.png
这个是图片地址
下面是问题图片
![p1](https://user-images.githubusercontent.com/26684296/67862849-d3798e80-fb5d-11e9-88e3-729889db8803.jpg)
![p2](https://user-images.githubusercontent.com/26684296/67862869-d96f6f80-fb5d-11e9-906b-723ca7eef5ed.jpg)

我的设置没错我仔细看过一遍

**Comment by hucstar** [comment]
> @hucstar 快捷键上传失败后，失败的日志是啥？在设置里可以查看日志，截图上来看看。

![](https://i.loli.net/2019/10/30/EPvjqx2XQcsT5Ww.jpg)
大大可以看一下，这是什么原因。另外想问一下Chevereto自建图床怎么绑定啊？那个说明看了，可否举个例子参照一下呢？万分感谢。

**Comment by Molunerfinn** [comment]
@hucstar 你这个是剪贴板里没有图片...当然就无法上传了。 `image not found in clipboard`。

**Comment by Molunerfinn** [comment]
相册里图片点编辑打开的对话框里图片地址是啥 @lblbk 。这种情况我这里无法复现，不知道你是否还有开代理等情况。

**Comment by Molunerfinn** [comment]
WIN10可以直接复制图片，然后通过剪贴板上传，WIN7需要打开图片再右键复制图片内容才可以使用剪贴板上传。
另外PicGo在系统的右键菜单添加了选项，可以直接在图片上右键上传图片：
![image](https://user-images.githubusercontent.com/12621342/68020643-0f396300-fcda-11e9-8018-427cc319091a.png)
如果剪贴板里没有图片，快捷键上传自然会失效，报错信息里就会有 `image not found in clipboard`

**Comment by hucstar** [comment]
原来是需要先ctrl+c一下再用快捷加上传啊，我以为是直接用快捷键就可以进行上传，感谢您。还想请教一下为什么我右键就没有出现picgo呢？
![](https://i.loli.net/2019/11/01/weNyz9CYMRTvdui.jpg)
