### ISSUE TITLE
picgo 使用github做图床，图片链接失效

### ISSUE THREAD

**Issue by donttal** [Molunerfinn/PicGo#353]
## 问题类型
bug report

## PicGo的相关信息
picgo 2.1.2 macOS10.15

## 问题重现
使用github作为图床，仓库设置为公有了，上传正常。但是复制markdown链接时，图片无法正常显示，在picgo相册里面也无法正常显示。

已看了issues308的解决方案，我填写的链接并没有错误
https://raw.githubusercontent.com/donttal/Figurebed/master/img/20191101223830.jpg

## 功能请求
求帮忙解决

---

**Comment by Molunerfinn** [comment]
无法复现，建议重新建一个仓库试试

**Comment by donttal** [comment]
我已经建立新的仓库，名字从Figurebed改成了figurebed，其他没变，picgo的设置截图如下
![Xnip2019-11-02_08-02-22](https://user-images.githubusercontent.com/30567352/68062772-2a8e8780-fd47-11e9-904f-3ad30a4074bf.jpg)
设置自定义域名为https://raw.githubusercontent.com/donttal/figurebed/master
在typora中加载上传好的图片还是显示image load falied

**Comment by Molunerfinn** [comment]
![image](https://user-images.githubusercontent.com/12621342/68064068-dfc63d00-fd51-11e9-9c49-2b9ad005153e.png)
我这里没有问题啊

**Comment by Molunerfinn** [comment]
是否开了什么全局代理

**Comment by Molunerfinn** [comment]
这已经不是PicGo的问题了，应该是你的网络问题，检查一下吧

**Comment by Molunerfinn** [comment]
另外可以试试用jsdelivr的CDN来加速github图床。搜一下文章应该不少

**Comment by wztlink1013** [comment]
@donttal 同样的问题。图片能能上传到GitHub仓库中，就是生成的链接访问不到图片，题主找到解决办法了吗？

**Comment by SpadeZ-A** [comment]
jpg上传不了

**Comment by luoru0221** [comment]
同样的问题，楼主解决了吗？

**Comment by Vajuw** [comment]
同样的问题+1，请问楼主解决了吗？

**Comment by KenGeng** [comment]
楼上的朋友们可以先保证自己能正常打开GitHub，然后确认下自己customURL设置的对不对
应该是`https://user-images.githubusercontent.com/`开头的一个链接， 而不是形如`https://github.com/user/repo/blob/main/xxx.png`的链接

**Comment by legend053** [comment]
我也碰到了一样的问题。最新版picgo。上传图片生成的链接过10分钟左右就失效了。我试了好几次。都这样。github里的图片还在。并没有删除。。。

**Comment by Vajuw** [comment]
你好，邮件已收到！本人将在收到邮件后尽快给您回复，祝好！

**Comment by legend053** [comment]
> 楼上的朋友们可以先保证自己能正常打开GitHub，然后确认下自己customURL设置的对不对 应该是`https://user-images.githubusercontent.com/`开头的一个链接， 而不是形如`https://github.com/user/repo/blob/main/xxx.png`的链接。 或者直接用`https://cdn.jsdelivr.net/gh/user/repo@main`这样的CDN加速链接

我生成的链接是这样的：![](https://raw.githubusercontent.com/username/GeneralPicLibrary/main/image11.png?token=xxxxxxxxx)

**Comment by JiakaiYang** [comment]
你好。我想用GitHub做图床分享一下picgo的软件。文章测试图床是否能用的时候。然后在手机打开文章的时候。发现图片地址没法链接到仓库的图片。电脑则能正常链接图片。电脑是开了全局代理的。
![image](https://user-images.githubusercontent.com/79317176/153859786-e119a957-9bae-44a3-a767-fd5a669d67d7.png)
![6134cbe93a5fcbf8334e5fdd76ce1dc](https://user-images.githubusercontent.com/79317176/153859941-e4e9c43f-7914-43ef-bc66-2b11e3bc5e19.png)
手机加载不出来。

**Comment by Molunerfinn** [comment]
> 你好。我想用GitHub做图床分享一下picgo的软件。文章测试图床是否能用的时候。然后在手机打开文章的时候。发现图片地址没法链接到仓库的图片。电脑则能正常链接图片。电脑是开了全局代理的。
> 
> ![image](https://user-images.githubusercontent.com/79317176/153859786-e119a957-9bae-44a3-a767-fd5a669d67d7.png)
> 
> ![6134cbe93a5fcbf8334e5fdd76ce1dc](https://user-images.githubusercontent.com/79317176/153859941-e4e9c43f-7914-43ef-bc66-2b11e3bc5e19.png)
> 
> 手机加载不出来。

所以想用手机显示就换别的图床...你也说了电脑要开代理，那没开代理的不也看不到吗

**Comment by Vajuw** [comment]
你好，邮件已收到！本人将在收到邮件后尽快给您回复，祝好！

**Comment by JiakaiYang** [comment]
https://github.com/Molunerfinn/PicGo/issues/353#issuecomment-1038997858
这个问题设置自定义域名就能解决。如果你上传的时候网络是代理状态又想让别人能访问的话，自定义域名格式为：https://cdn.jsdelivr.net/gh/用户名/仓库名

**Comment by curiousity666** [comment]
所以github图床必须要开代理才看得到吗？

**Comment by Vajuw** [comment]
你好，邮件已收到！本人将在收到邮件后尽快给您回复，祝好！

**Comment by addonico** [comment]
> 我也碰到了一样的问题。最新版picgo。上传图片生成的链接过10分钟左右就失效了。我试了好几次。都这样。github里的图片还在。并没有删除。。。

你好，我的问题和你一模一样，请问你最后怎么解决的？

**Comment by Vajuw** [comment]
你好，邮件已收到！本人将在收到邮件后尽快给您回复，祝好！

**Comment by Molunerfinn** [comment]
> > 我也碰到了一样的问题。最新版picgo。上传图片生成的链接过10分钟左右就失效了。我试了好几次。都这样。github里的图片还在。并没有删除。。。
> 
> 
> 
> 你好，我的问题和你一模一样，请问你最后怎么解决的？
> 
> 

请不要用私有仓库，请用公有仓库

**Comment by PanYuTing2023** [comment]
你们的问题都解决了吗？该怎么解决这个问题呢？

**Comment by PanYuTing2023** [comment]
> 你们的问题都解决了吗？该怎么解决这个问题呢？

如果你的问题解决了麻烦可以告诉我吗

**Comment by PanYuTing2023** [comment]
> > > 我也碰到了一样的问题。最新版picgo。上传图片生成的链接过10分钟左右就失效了。我试了好几次。都这样。github里的图片还在。并没有删除。。。
> > 
> > 
> > 你好，我的问题和你一模一样，请问你最后怎么解决的？
> 
> 请不要用私有仓库，请用公有仓库

把仓库改为公有就行了吗？
