### ISSUE TITLE
可以使用github的配置，然后实际使用的是码云gitee吗？

### ISSUE THREAD

**Issue by chenshuai1995** [Molunerfinn/PicGo#354]
## 功能请求

可否使用github的图床，实际使用的是gitee的仓库。

github经常被强，https://raw.githubusercontent.com/  这个网站被墙，显示不了。 

https://user-images.githubusercontent.com/ 这个网站还是可以显示的，但是PicGo生成的连接，不是这种。

要么直接使用码云gitee，一是网速比较快，二是不会被墙

---

**Comment by Molunerfinn** [comment]
已有gitee插件支持。搜索即可
