### ISSUE TITLE
gallery 预览视图

### ISSUE THREAD

**Issue by OfficialYoungX** [Molunerfinn/PicGo#355]
## 问题类型
Feature Request

## PicGo的相关信息
Mac

## 功能请求
建议把预览的视图为全部的正方形更改为按照图片的实际比例显示。
目前的情况是无论图片什么比例，都被**强行**拉伸为1:1
修改原因：
- 预览的时候，图片的比例也是给用户的一个重要信息，在不点开大图的情况下也可轻松预览图片原来的比例
- 强制拉伸图片比例展示，在绝大多数情况下（任何）都不是一个良好的用户体验
- 你这小东西真的挺好用，希望在这些细节方面有进一步的提升
ps：
其实我代码都给你找好了地方，相当简单：
```stylus
// Gallery.vue 第 439 行
object-fit fill
// 改为
object-fit contain
```

---
由于改动太简单，就不pr了。

**Comment by Molunerfinn** [comment]
之前改成fill主要原因在于使用cover的时候性能非常差，在相册页多图片的情况下滚动会非常卡。

contain回头我再测试一下。之前其实也用过，但是最后选了fill，不过我忘记具体原因了

**Comment by OfficialYoungX** [comment]
@Molunerfinn 
啊哈，你可以试试，不过很惊讶居然这个属性和性能这么相关。

**Comment by Molunerfinn** [comment]
测试了一下性能还是不过关，先关闭了，以后找到更好的方法后会改进这一块
