### ISSUE TITLE
github图床图片不显示

### ISSUE THREAD

**Issue by binzh303** [Molunerfinn/PicGo#356]
## 问题重现
![图片](https://user-images.githubusercontent.com/31266789/68591838-9651bc80-04cc-11ea-857e-a2df52a7bc15.png)

## 功能请求

---

**Comment by Molunerfinn** [comment]
public仓库还是private？private不行。

**Comment by Molunerfinn** [comment]
我看你应该用的是私有仓库。请注意PicGo图床只针对public仓库。
