### ISSUE TITLE
PicGo Github 相册无法显示预览图

### ISSUE THREAD

**Issue by sun-men** [Molunerfinn/PicGo#357]
Windows10

## 问题重现
![image](https://user-images.githubusercontent.com/1943377/68641409-b7a2bf00-0545-11ea-9b20-6827688b5496.png)

**Comment by Molunerfinn** [comment]
点击编辑，图片URL是什么

**Comment by Molunerfinn** [comment]
不能显示一般都是你配置出问题。

**Comment by Molunerfinn** [comment]
参考：https://github.com/Molunerfinn/PicGo/issues/79

**Comment by sun-men** [comment]
上传路径是：
https://github.com/sun-men/Figurebed/img/20191112121112.png

但github资源地址是：
https://raw.githubusercontent.com/sun-men/Figurebed/master/img/20191112121052.png

**Comment by Molunerfinn** [comment]
说明你配置错了嘛...

**Comment by Molunerfinn** [comment]
设定自定义域名那块，要么不要设置，要么就设置成github的资源地址。
参考文章：https://juejin.im/entry/5c4ec5aaf265da614420689f

**Comment by sun-men** [comment]
好的，配置为：https://raw.githubusercontent.com/sun-men/Figurebed/master 即可，你在文档中可以备注一下

**Comment by sun-men** [comment]
除了github，支持码云gitee么？还是要自己开发插件？

**Comment by Molunerfinn** [comment]
已有gitee插件…搜一下就有…

**Comment by aa4790139** [comment]
> 设定自定义域名那块，要么不要设置，要么就设置成github的资源地址。
> 参考文章：https://juejin.im/entry/5c4ec5aaf265da614420689f

不设置一样，还是不显示
