### ISSUE TITLE
上传至微博图床后，无法显示预览图

### ISSUE THREAD

**Issue by JZLeung** [Molunerfinn/PicGo#36]
## 问题类型
Bug Report

## PicGo的相关信息
Mac

## 问题重现
1、拖拽图片上传至微博图床。
2、打开相册。
3、选择一张图片

先 loading
![image](https://user-images.githubusercontent.com/7995232/39027887-9fe2b360-4486-11e8-9e04-39df619ccf08.png)

然后 error
![](https://ws3.sinaimg.cn/large/006tKfTcgy1fqix78lc81j318g0p0t93.jpg)

---

**Comment by Molunerfinn** [comment]
应该是你全局挂了Shadowsocks或者其他代理的缘故，微博图床的图片在某些代理的情况下是无法访问的。

**Comment by JZLeung** [comment]
@Molunerfinn 
网络设置挂上了。

**Comment by Molunerfinn** [comment]
所以挂上了就没法看到了- -...你可以尝试不挂全局代理，然后重启PicGo应该就没问题了。

**Comment by JZLeung** [comment]
@Molunerfinn 
好的，感谢。

**Comment by Ericleezh** [comment]
是否可以增加代理相关的配置，因为平时开发的话一般也会开着代理。

**Comment by Molunerfinn** [comment]
已经有了
