### ISSUE TITLE
vscode远程开发使用PicGo时，Image not found in ClipBoard问题

### ISSUE THREAD

**Issue by CapsulE07** [Molunerfinn/PicGo#360]
## 问题类型

Bug Report
## PicGo的相关信息

本地windows,使用 vscode-PicGo插件，远程连接远程端ubuntu机器
## 问题重现
1. 本地机器windows，使用vscode-PicGo,正常图片上传使用无异常
2. 使用vscode进行远程开发，远程端ubuntu, 腾讯云服务器，使用PicGo,会出现 Image not found in ClipBoard问题。 
云服务器信息： Ubuntu Server 18.04.1 LTS 64位
本地vscode信息：
![image](https://user-images.githubusercontent.com/23300139/69490463-625e9a00-0ec3-11ea-99ad-4b99bfe7ed81.png)
错误截图：
![image](https://user-images.githubusercontent.com/23300139/69490469-7b674b00-0ec3-11ea-9f0e-2b5499d0e108.png)

## 功能请求

---

**Comment by Molunerfinn** [comment]
这个仓库是PicGo的electron版，不是VSCode版。 https://github.com/PicGo/vs-picgo

另外，你远程VSCode开发，在服务器上装了vs-picgo，它读取的自然是服务器的剪贴板里的图片，你服务器剪贴板里没有图片当然上传不成功- -。

**Comment by CapsulE07** [comment]
额，这个原因呀。 另外我也试过在远程开发状态下的vscode，选取目录中的图片，点击复制后，然后通过PicGo上传，还是会出现 Image not found in ClipBoard问题。有什么方法可以解决这种远程开发时剪切板的问题呢？

**Comment by CapsulE07** [comment]
我将这个issue去  PicGo/vs-picgo 提一下。

**Comment by Molunerfinn** [comment]
这个问题暂时无解。你可以在本地用electron版本的picgo来上传图片。

**Comment by Molunerfinn** [comment]
你要这么想，你的图片在本机，但是vs-picgo在远端，那么上传图片要从哪里上传呢？vs-picgo如果要能拿到你本地的图片，意味着你的图片首先要先传到远端，再从远端上传到对应的图床，这里面有两倍的耗时，并且你的图片传到远端要传到哪个目录？有没有权限？如何用http直接传过去？这都是问题。vs-picgo本身也不是为了remote模式做的插件，为的是本地开发做的插件

**Comment by CapsulE07** [comment]
感谢解答~

**Comment by WineChord** [comment]
> 你要这么想，你的图片在本机，但是vs-picgo在远端，那么上传图片要从哪里上传呢？vs-picgo如果要能拿到你本地的图片，意味着你的图片首先要先传到远端，再从远端上传到对应的图床，这里面有两倍的耗时，并且你的图片传到远端要传到哪个目录？有没有权限？如何用http直接传过去？这都是问题。vs-picgo本身也不是为了remote模式做的插件，为的是本地开发做的插件

那可以这样搞吗：文件从本地这边上传，拿到链接之后插入到 markdown 中
