### ISSUE TITLE
图床+Github需求

### ISSUE THREAD

**Issue by sinlee1** [Molunerfinn/PicGo#361]
## 问题类型

Feature Request

## PicGo的相关信息
Windows+Mac

## 功能请求

---
目前Github图床只能建立公开仓库，存在一定的隐私泄露的情况，其他人也能够看到。想知道是否考虑添加私人仓库的功能？如果用到私人仓库是否还需要添加其他私人的Token之类的信息

已Star!

**Comment by Molunerfinn** [comment]
你可以创建私人仓库来上传啊，没问题。

只不过你想上传到私人仓库又想分享给别人看，这是不可能的。token是一段时间就过期的，PicGo不会负责帮你更新token。同理PicGo的相册对github的私人仓库而言也是外部环境，所以你上传到私人仓库里的图片在PicGo的相册里是看不到的。

想要隐私就每个月花1块钱买个阿里云OSS，或者腾讯云COS等。
