### ISSUE TITLE
Bug微博图床接口失效403

### ISSUE THREAD

**Issue by naah69** [Molunerfinn/PicGo#362]
## 问题类型

Bug Report

## PicGo的相关信息

Mac

## 问题重现
无论使用用户名密码模式 还是 cookie模式，都无法上传图片
![image](https://user-images.githubusercontent.com/25682169/69909822-c8a36980-143b-11ea-9184-c52bdb10d4d7.png)
![image](https://user-images.githubusercontent.com/25682169/69909794-55015c80-143b-11ea-921e-ca2663f99e7c.png)
![image](https://user-images.githubusercontent.com/25682169/69909813-a7db1400-143b-11ea-8267-7615fdc2da87.png)

**Comment by Molunerfinn** [comment]
微博图床的接口已经开始被官方限制，同时微博图床已经开始防盗链。所以下个版本PicGo将默认取消对微博图床的支持。相关问题不再修复，请谅解

**Comment by naah69** [comment]
只是https不支持了，如果把https换成http是可以的
