### ISSUE TITLE
Windows快捷键上传失败

### ISSUE THREAD

**Issue by clark-cui** [Molunerfinn/PicGo#364]
## 问题类型

Bug Report

## PicGo的相关信息

PicGo-2.1.2   Windows

## 问题重现

当使用**快捷键**（我修改了默认快捷键 `ctrl+shift+u`）上传图片，会报错

**PS**:我改回默认快捷键`ctrl +shift+p`也会出现同样的问题

**如图**
![](https://raw.githubusercontent.com/clark-cui/imgRepo/master/img/err2.png)

**日志为**
![](https://raw.githubusercontent.com/clark-cui/imgRepo/master/img/err1.png)

使用拖拽上传或者点击上传则不会出现此问题

**Comment by Molunerfinn** [comment]
看报错： `image not found in clipboard` 说明你剪贴板最新的内容并不是一张图片，自然无法上传。

**Comment by clark-cui** [comment]
感谢回复，是这样的，抱歉。我第一次用，我以为是选中上传，原来是的用剪贴板。
