### ISSUE TITLE
PicGo-2.1.2-mac.zip  这个包里的程序解压出来无法运行  应用程序“PicGo”无法打开。

### ISSUE THREAD

**Issue by txl263** [Molunerfinn/PicGo#366]
## 问题类型

Bug report
## PicGo的相关信息
PicGo-2.1.2-mac.zip 

MACOS catalina 10.15.1
## 问题重现
PicGo-2.1.2-mac.zip 解压缩后打开
应用程序“PicGo”无法打开。
dmg里的是可以打开的。

## 功能请求

---

**Comment by Molunerfinn** [comment]
这个在README里已经说了吧
![image](https://user-images.githubusercontent.com/12621342/70416553-4994dd80-1a9a-11ea-9644-c99a5ef8ca3e.png)

**Comment by txl263** [comment]
Sorry,我从外网直接跳到Release的还没看readme
