### ISSUE TITLE
windows 10 打开报错: TypeError: Error processing argument at index 0, conversion failure from undefined at App

### ISSUE THREAD

**Issue by kasheemlew** [Molunerfinn/PicGo#368]
## 问题类型

Bug Report

## PicGo的相关信息

Windows

## 问题重现

打开应用

![image](https://user-images.githubusercontent.com/14333766/71222395-612a5c80-230b-11ea-8908-24226abc310c.png)

但不影响使用

## 功能请求

---

**Comment by Molunerfinn** [comment]
嗯我这边mac有的时候也会出现，很奇怪。回头看看是什么问题

**Comment by Molunerfinn** [comment]
这个bug应该会在2.2版本的时候修复，到时候更新即可

**Comment by kasheemlew** [comment]
@Molunerfinn 感谢
