### ISSUE TITLE
预览显示不正确

### ISSUE THREAD

**Issue by booxood** [Molunerfinn/PicGo#37]
## 问题类型

Bug Report

## PicGo的相关信息

Mac v1.4.3
## 问题重现

图片可以上传到七牛图床，但是预览显示的如下：
![image](https://user-images.githubusercontent.com/2151410/39104377-df5b18b2-46e2-11e8-8566-701359ad2319.png)

---

**Comment by Molunerfinn** [comment]
你七牛云有没有开防盗链？如果有的话显示不出来是正常的。

**Comment by booxood** [comment]
- 没开防盗链 ![qiniu1](http://p65j3vgtp.bkt.clouddn.com/20180423142357.png)

- 有使用代理，但是直接访问图片是可以的，应该不是代理的问题

- 我用的是七牛的默认提供的域名，访问 https 链接时证书不一致，不知道有没有跟这个问题有没有关系

![image](https://user-images.githubusercontent.com/2151410/39110066-40edee6e-4702-11e8-95a2-94ab2316090f.png)

**Comment by booxood** [comment]
这。。。 

是不是判断下，如果 https 地址不可用，就改用 http 地址

**Comment by Molunerfinn** [comment]
@booxood 无法判断是因为证书原因还是网络原因导致的图片显示错误- -。你这个是你的证书错了，改一下你的证书才是解决办法。

**Comment by booxood** [comment]
@Molunerfinn 这是七牛网站证书的问题

**Comment by Molunerfinn** [comment]
@booxood 那你访问链接这里不要写https，写成http就好了啊
![image](https://user-images.githubusercontent.com/12621342/39124405-e9bffc0a-472d-11e8-9397-8a2aa96a5dda.png)

**Comment by booxood** [comment]
@Molunerfinn 没用，还是一样的
