### ISSUE TITLE
[功能建议] 建议SM.MS图床增加配置文件 Secret Token

### ISSUE THREAD

**Issue by zouyaoji** [Molunerfinn/PicGo#370]
## 问题类型
Feature Request

## PicGo的相关信息
2.1.2Windows

## 功能请求

我看在网页登录sm.ms平台再在 https://sm.ms/ 上传图片是可以在自己用户下看到自己上传的图片的，并且支持删除。如果PicGo支持设置了 sm.ms 的API Token，是不是就能上传到自己的账户下了？如果可以的话，相当于有了管理功能耶，如果有删除需求，那就可以删除了。我不知道有这样的需求的人多不多，如果多的话建议考虑一下哦。
---

**Comment by Molunerfinn** [comment]
已经有SMMS2的插件了，自行搜索。
