### ISSUE TITLE
提供插件内抛出错误提示的能力

### ISSUE THREAD

**Issue by Dec-F** [Molunerfinn/PicGo#371]
## 问题类型
Feature Request

## PicGo的相关信息
Mac

## 功能请求
目前guiApi只能在guiMenu回调中使用，在插件主逻辑,也就是`register`注册的`handle`中没有抛出错误提示的能力。

![image](https://user-images.githubusercontent.com/20250430/71396724-3ff0a580-2656-11ea-99fe-5eca37245184.png)

希望可以提供`ctx.notice`这个能力，目前只能`throw new Error()`，让PicGo捕获，错误提示并不能准确的反馈给用户错误信息

---

**Comment by Molunerfinn** [comment]
ctx的话使用这个：
https://picgo.github.io/PicGo-Core-Doc/zh/dev-guide/cli.html#%E6%B6%88%E6%81%AF%E9%80%9A%E7%9F%A5

**Comment by Dec-F** [comment]
没办法打断执行流啊

transform出错，无论return什么还是会执行上传，这时候transform错误会导致upload出错，notice的是上传失败。

如果抛出错误打断执行流，就会弹出外面绑定的错误处理程序，插件notice的信息还是没有。

**Comment by Dec-F** [comment]
应该有个`return false`时直接退出的特性
![image](https://user-images.githubusercontent.com/20250430/71405427-5dcb0400-2670-11ea-96b8-72830df25580.png)

**Comment by Molunerfinn** [comment]
每个生命周期不只是执行了一个plugin，可能执行了多个plugin，plugin之间互相是不知道对方的存在的，所以单纯return false 并不能直接跳出生命周期。

electron端这边下个版本会将默认的通知去掉，让报错通知全部交给插件来兜底。所以要中断执行，依然需要使用throw。
