### ISSUE TITLE
啥时候支持 Gitee 图床啊

### ISSUE THREAD

**Issue by objcoding** [Molunerfinn/PicGo#372]
目前 github 图床太慢了，希望支持一下 Gitee，谢谢🙏

**Comment by Molunerfinn** [comment]
首先：
![image](https://user-images.githubusercontent.com/12621342/71403647-51907800-266b-11ea-9cb7-9a1994b0ee35.png)

其次，已经有插件支持gitee图床。

https://github.com/zWingz/picgo-plugin-github-plus

https://github.com/lizhuangs/picgo-plugin-gitee-uploader

伸手党也不是这样吧？
