### ISSUE TITLE
按照README无法启动开发环境

### ISSUE THREAD

**Issue by nouh** [Molunerfinn/PicGo#373]
## 功能请求

---

**Comment by Molunerfinn** [comment]
报了什么错好歹截个图呀

**Comment by Molunerfinn** [comment]
哦想起来了，dev环境的话脚本是有所更新的。
你可以试试 `npm run electron:serve`

**Comment by Molunerfinn** [comment]
![image](https://user-images.githubusercontent.com/12621342/71439400-73096680-2734-11ea-8e33-920e715647f7.png)
晚些时间我把README更新一下，最近更新了底层的框架

**Comment by nouh** [comment]
我就是用`npm run electron:serve`启动的呢, 报了这个错, PS: 我最近开了个electron的项目也在用 vue-cli-plugin-electron-builder
<img width="849" alt="Screen Shot 2019-12-25 at 6 46 33 PM" src="https://user-images.githubusercontent.com/445029/71443676-5fb3c680-2747-11ea-817c-7af29c6dccff.png">

**Comment by Molunerfinn** [comment]
这个401不影响主进程启动，是运行时的。主要是用于向github请求版本信息的，需要本地配置一个token，我之后会在README里说明一下。

**Comment by nouh** [comment]
> 这个401不影响主进程启动，是运行时的。主要是用于向github请求版本信息的，需要本地配置一个token，我之后会在README里说明一下。
> 
> 这个会在新版本里更新获取的方式，改用jsdelivr去获取，就不需要配置token了。

嗯嗯,感谢,更新一下README吧, 你踩过的electron的坑多, 代码结构也做了更新比较有参考价值

**Comment by Molunerfinn** [comment]
> > 这个401不影响主进程启动，是运行时的。主要是用于向github请求版本信息的，需要本地配置一个token，我之后会在README里说明一下。
> > 这个会在新版本里更新获取的方式，改用jsdelivr去获取，就不需要配置token了。
> 
> 嗯嗯,感谢,更新一下README吧, 你踩过的electron的坑多, 代码结构也做了更新比较有参考价值

近期会更新，在解决一个问题所以还没提交

**Comment by Dec-F** [comment]
开发模式下

axios没注册
![image](https://user-images.githubusercontent.com/20250430/71473221-1a5bcb80-2811-11ea-88c8-bf02d0a49378.png)

加上这个就好了
![image](https://user-images.githubusercontent.com/20250430/71473251-395a5d80-2811-11ea-92e7-5d1fe3df939a.png)


确定下是我的问题还是确实是个bug @Molunerfinn

**Comment by Molunerfinn** [comment]
> 开发模式下
> 
> axios没注册
> ![image](https://user-images.githubusercontent.com/20250430/71473221-1a5bcb80-2811-11ea-88c8-bf02d0a49378.png)
> 
> 加上这个就好了
> ![image](https://user-images.githubusercontent.com/20250430/71473251-395a5d80-2811-11ea-92e7-5d1fe3df939a.png)
> 
> 确定下是我的问题还是确实是个bug @Molunerfinn

嗯，这个在我本地修改了还没提交…今天会提交一大波

**Comment by Molunerfinn** [comment]
已更新
