### ISSUE TITLE
请问PicGo是否有防盗链功能

### ISSUE THREAD

**Issue by sukai-cheng** [Molunerfinn/PicGo#374]
## 功能请求

---

**Comment by sukai-cheng** [comment]
我在阿里云OSS中过来的，别的网站对我进行的盗链，我想解决这个麻烦，所以需要防盗链

**Comment by Molunerfinn** [comment]
防盗链应该在阿里云设置。只不过设置了防盗链之后PicGo相册是无法查看的（因为对阿里云而言PicGo也是第三方），不过上传功能是不受限制的。

**Comment by sukai-cheng** [comment]
图片在网页也无法查看

PiEgg <notifications@github.com> 于2019年12月28日周六 下午7:58写道：
