### ISSUE TITLE
命令行调用不会输出结果

### ISSUE THREAD

**Issue by abnerlee** [Molunerfinn/PicGo#375]
#问题类型

Bug Report

## PicGo的相关信息

macOS Catalina, PicGo 2.1.2

## 问题重现

terminal调用和结果如图，使用的是系统自带的terminal

<img width="570" alt="Screen Shot 2019-12-30 at 22 40 30" src="https://user-images.githubusercontent.com/1621242/71586501-68483a80-2b55-11ea-95e6-76697c48919a.png">

PicGo现实上传成功，log文件也有结果，但是结果不会在Terminal (stdout) 输出,

```
2019-12-30 22:37:33 [PicGo INFO] Before transform
2019-12-30 22:37:33 [PicGo INFO] Transforming...
2019-12-30 22:37:33 [PicGo INFO] Before upload
2019-12-30 22:37:33 [PicGo INFO] Uploading...
2019-12-30 22:37:36 [PicGo SUCCESS] 
https://i.imgur.com/OhC3ycn.jpg
```

**Comment by Molunerfinn** [comment]
收到，我看一下这个问题

**Comment by Molunerfinn** [comment]
看起来原因大概如下：

1. 如果直接通过正常方式运行PicGo（比如点击ICON运行），那么再通过命令行运行上传命令时，由于PicGo做了单实例限制，所以在命令行里运行时的新建的实例会被quit，（上传是通过之前存在实例上传的，因此在日志里能看到上传结果，但是命令行中看不到输出）

2. 如果之前没有运行过PicGo，然后直接通过命令行运行PicGo（称为A实例），那么在其他地方通过命令行继续运行的话，会在A实例窗口中输出结果：

![image](https://user-images.githubusercontent.com/12621342/71607362-b68c2680-2bb3-11ea-9272-f8c7074e232b.png)

**Comment by Molunerfinn** [comment]
我考虑到第三方应用通过这种方式是能够上传但是无法获取上传结果的，而且通过stdout拿结果也并不优雅。我可以在PicGo内部加一个HTTPServer，让第三方应用通过HTTPServer来调用PicGo的上传接口。

**Comment by Molunerfinn** [comment]
上传具体图片，发送一个JSON，格式为：

```json
{
  "list": ["path-to-the-image.jpg", ...]
}
```

![image](https://user-images.githubusercontent.com/12621342/71626614-1b359880-2c29-11ea-8efe-330f15116268.png)

上传剪贴板图片（不需要携带数据）
![image](https://user-images.githubusercontent.com/12621342/71626713-926b2c80-2c29-11ea-966a-9fae1b152712.png)

dev分支已经更新，我会尽快更新文档，预计马上发布2.2版本。

**Comment by abnerlee** [comment]
用http://127.0.0.1:36677 并不能保证PicGo已经启动了呀，用http URL的话还不如考虑使用自定义protocol (比如 picgo://upload/)

**Comment by Molunerfinn** [comment]
> 用http://127.0.0.1:36677 并不能保证PicGo已经启动了呀，用http URL的话还不如考虑使用自定义protocol (比如 picgo://upload/) ?

嗯，不过自定义 `protocol` 在没有启动的时候也需要唤醒。我先测试一下吧

**Comment by Molunerfinn** [comment]
测试了一下，自定义 `protocol` 能力有限。首先，注册成功后，三端的表现有差异，在windows端会和现有命令行调用上传的方式冲突。

另外，自定义 `protocol` 无法处理来自外部的 `POST` 请求，换句话说无法携带数据。而在浏览器里能唤起应用是因为浏览器向系统寻找了自定义 `protocol` 注册的应用，唤醒应用，再将数据传递过去，这里需要一个用户同意唤醒的操作，而不是无感知的。

同时，如果通过第三方客户端发送请求（以HTTP请求为例），是无法得到预期的相应的。因为发送请求的客户端并不会去向系统请求对应自定义 `protocol` 注册的客户端，所以发送的请求是不会到达通过 `protocol` 注册的客户端的，从而得不到响应。

因此，从三端差异、与现有逻辑冲突、无法实现需求上的角度来说，不考虑使用自定义链接了。

而通过HTTP请求发送请求有几个好处：

1. 三端表现一致，从请求、到响应都一样
2. 如果未开客户端，则无法收到响应，可以通过这个结果来知道道用户没有打开PicGo客户端，从而提示用户打开PicGo客户端
3. 如果担心端口占用而无法连上PicGo，PicGo内部做了端口号冲突的处理，并且会将当前使用的端口写入PicGo的配置文件，第三方应用若不确定可以通过读取配置文件的端口号可以定位。36677这个端口目前来说没有其他应用默认使用，在大概率情况下是可以使用的
