### ISSUE TITLE
批量上传导致的错误

### ISSUE THREAD

**Issue by yuandev** [Molunerfinn/PicGo#376]
## 问题类型

Bug Report

## PicGo的相关信息

Windows 1909

## 问题重现

批量上传图片后，应用无法正常显示批量上传效果。相册无法显示批量上传成功后的图片
进入仓库查看 批量上传的图片都已经成功上传了
重启应用相册仍然无法正常显示

**Comment by Molunerfinn** [comment]
我这边测试批量上传没问题。

请问你用的是哪个图床和PicGo的哪个版本？以及，相册无法显示批量上传成功后的图片指的是相册有那几张图片的位置但是显示不出来？还是相册压根就没用那几张图片？最好截个图方便说明。

还有，你是不是用了GitHub的私有仓库传图片？如果你用的私有仓库传图片，那么除非你登录了你的账号才能看到，否则PicGo的相册也无法访问你的私有仓库。

另外推荐不要一次性上传多张图片，失败几率会比较大。

**Comment by yuandev** [comment]
图床是Github 使用的是公开库
PicGo版本：PicGo-Setup-2.2.0.exe
无法显示批量上传效果：上传是只有一个进度条，无法看见图片是传了多少张。（尝试了选择和拖拽两种）
相册看不见：看不见批量上传的所有图片，只有另外单独上传的能显示，重启后依然看不见
截图暂无，稍后晚上回家截图看看
数量大概是60多张，昨天失败后把仓库清掉了，准备重新单独传，晚上再尝试。

**Comment by Molunerfinn** [comment]
> 图床是Github 使用的是公开库
> PicGo版本：PicGo-Setup-2.2.0.exe
> 无法显示批量上传效果：上传是只有一个进度条，无法看见图片是传了多少张。（尝试了选择和拖拽两种）
> 相册看不见：看不见批量上传的所有图片，只有另外单独上传的能显示，重启后依然看不见
> 截图暂无，稍后晚上回家截图看看
> 数量大概是60多张，昨天失败后把仓库清掉了，准备重新单独传，晚上再尝试。

嗯是的，目前对批量上传的支持度是很轻量的，所以建议不要一次性上传太多，一旦失败可能整条队列就死掉了。推荐一次性上传数量限制在5张以内。

而且目前进度条是全部上传的图片完成后才会走完，没有显示每张图片的上传进度的。这个体验会在后续优化，不过我这边一次性上传3张图片是OK的。

**Comment by Molunerfinn** [comment]
> 图床是Github 使用的是公开库
> PicGo版本：PicGo-Setup-2.2.0.exe
> 无法显示批量上传效果：上传是只有一个进度条，无法看见图片是传了多少张。（尝试了选择和拖拽两种）
> 相册看不见：看不见批量上传的所有图片，只有另外单独上传的能显示，重启后依然看不见
> 截图暂无，稍后晚上回家截图看看
> 数量大概是60多张，昨天失败后把仓库清掉了，准备重新单独传，晚上再尝试。

如果对GitHub依赖比较多，可以试试插件[github-plus](https://github.com/zWingz/picgo-plugin-github-plus)，它能同步你的GitHub仓库的图片记录。
