### ISSUE TITLE
启动后无反应

### ISSUE THREAD

**Issue by ducksouls** [Molunerfinn/PicGo#377]
## 问题类型
启动问题

Bug Report
## PicGo的相关信息
picgo 2.20
win10
node v12.13.0
vue 2.9.6
npm 6.13.4

## 问题重现
git克隆后 powershell运行: npm install
npm run electron:serve后
![Uploading image.p
![123](https://user-images.githubusercontent.com/26918965/71763511-a65baa80-2f17-11ea-8e32-455fa6ebd86e.PNG)
ng…]()
然后就没反应了

## 功能请求

---

**Comment by ducksouls** [comment]
是我的版本问题,还是别的问题

**Comment by Molunerfinn** [comment]
右下角任务栏里有图标。

**Comment by jerryc127** [comment]
我連圖標都沒
安裝了水印那個插件后就打不開了‘
開機也不行
看來只有重新安裝了

**Comment by Molunerfinn** [comment]
> 我連圖標都沒
> 安裝了水印那個插件后就打不開了‘
> 開機也不行
> 看來只有重新安裝了

水印插件请看它的README安装，不能直接在PicGo安装界面安装。如果误装了，请删除PicGo配置目录的node_modules 文件夹、package.json、package-lock.json就能恢复。

**Comment by jerryc127** [comment]
我就是按照README用npm安裝的

**Comment by jerryc127** [comment]
> > 我連圖標都沒
> > 安裝了水印那個插件后就打不開了‘
> > 開機也不行
> > 看來只有重新安裝了
> 
> 水印插件请看它的README安装，不能直接在PicGo安装界面安装。如果误装了，请删除PicGo配置目录的node_modules 文件夹、package.json、package-lock.json就能恢复。

我就是按照README用npm安裝的, 
按照你説的，刪掉了可以打開picgo
然後又重新安裝水印插件,
發現問題依舊，會出現打不開picgo
用命令行卸載掉水印插件，picgo能打開
那基本可以確定是水印插件的問題了
picgo已是最新版（已在水印插件github提交issues)

**Comment by ducksouls** [comment]
> 右下角任务栏里有图标。

右下角没图标,命令行去看了下,启动的端口在监听着启动的端口,
任务栏还是桌面都没picgo的图标

**Comment by Molunerfinn** [comment]
> > 右下角任务栏里有图标。
> 
> 右下角没图标,命令行去看了下,启动的端口在监听着启动的端口,
> 任务栏还是桌面都没picgo的图标

这里也没有么
![image](https://user-images.githubusercontent.com/12621342/71789304-3a875800-3065-11ea-9e2b-510557ba4c6c.png)

**Comment by ducksouls** [comment]
> > > 右下角任务栏里有图标。
> > 
> > 
> > 右下角没图标,命令行去看了下,启动的端口在监听着启动的端口,
> > 任务栏还是桌面都没picgo的图标
> 
> 这里也没有么
> ![image](https://user-images.githubusercontent.com/12621342/71789304-3a875800-3065-11ea-9e2b-510557ba4c6c.png)
无
![222](https://user-images.githubusercontent.com/26918965/71789650-4aa03700-3067-11ea-979d-bc982f816c17.PNG)
![333](https://user-images.githubusercontent.com/26918965/71789692-7f13f300-3067-11ea-98d1-7584d9d3addc.PNG)
我使用了npm-windows-upgrade,不知道这个有没有影响

**Comment by Molunerfinn** [comment]
用yarn来安装吧，用npm有时会有问题。删掉 `node_modules` 和 `package-lock.json`，用`yarn`安装一下依赖再启动。

**Comment by ducksouls** [comment]
使用yarn后可以了,万分感谢

**Comment by ducksouls** [comment]
> 用yarn来安装吧，用npm有时会有问题。删掉 `node_modules` 和 `package-lock.json`，用`yarn`安装一下依赖再启动。

万分感谢

**Comment by Molunerfinn** [comment]
> > 用yarn来安装吧，用npm有时会有问题。删掉 `node_modules` 和 `package-lock.json`，用`yarn`安装一下依赖再启动。
> 
> 万分感谢

我回头更新一下文档吧
