### ISSUE TITLE
smms图床上传提示v1 API deprecated，需要使用v2 API

### ISSUE THREAD

**Issue by yf-9186** [Molunerfinn/PicGo#378]
## 问题类型
Bug Report

## PicGo的相关信息
2.2.0
Windows 10 1909 18363.535

## 问题重现
选择smms图床上传图片时均上传失败。出现下图的提示：
![Snipaste_2020-01-04_20-33-59.png](https://i.loli.net/2020/01/04/9jVXG247gupvzid.png)

## 功能请求

---

**Comment by Molunerfinn** [comment]
已有v2的插件，可以去插件区搜索smms。本体将会在2.3支持。
