### ISSUE TITLE
本人最近也在做类似的图床网站.看到作者做的比好我,想提供一些我的建议?

### ISSUE THREAD

**Issue by eluotao** [Molunerfinn/PicGo#38]
## 问题类型

Feature Request

## PicGo的相关信息

 Mac 

## 功能请求

希望增加一个网页版本管理系统.可以自定义短链?绑定域名.

类似可以参考我的网站V.LELE.IM  

通过自定义格式访问

比如V.LELE.IM?key=laotou
V.LELE.IM?cate=laotou   随机组
V.LELE.IM?key=laotou&s=json  json返回
本人有很多关于图床的想法.希望可以加个WX交流.   邮箱26993@163.com   请发QQ给我.
---

**Comment by Molunerfinn** [comment]
哈，你的想法挺好的。不过目前精力有限并没有往图床的web端管理方面考虑，PicGo的初衷也不是这个。不过还是谢谢你的提议，我看你的页面做得也很棒啊~
