### ISSUE TITLE
是否可以添加上传前压缩的选项

### ISSUE THREAD

**Issue by LiuDanK** [Molunerfinn/PicGo#381]
## 问题类型

Feature Request
## PicGo的相关信息

2.2.0 windows
## 功能请求

是否可以添加上传前压缩的选项，有一些图片的尺寸很大，直接上传访问的时候就会非常的慢，而上传前处理又十分麻烦，作者大大可以考虑一下
---

**Comment by Molunerfinn** [comment]
这个会让插件去实现
