### ISSUE TITLE
相册里图片的删除按钮不起作用

### ISSUE THREAD

**Issue by yf-9186** [Molunerfinn/PicGo#382]
## 问题类型
Bug Report

## PicGo的相关信息
Windows 10 1909 18363.535
PicGo 2.2.0

## 问题重现
![图片](https://user-images.githubusercontent.com/38492750/72028999-7ae21280-32bf-11ea-84e7-03f8b60ecb36.png)
如上图，相册里图片的删除按钮不起作用。每次删除一个图片的时候都要打钩后点批量删除才可以删除。

## 功能请求

---

**Comment by Molunerfinn** [comment]
已复现，会尽快解决
