### ISSUE TITLE
能否让PicGo设置里选择显示的图床的设置，同时作用于相册？

### ISSUE THREAD

**Issue by yf-9186** [Molunerfinn/PicGo#383]
## 问题类型
Feature Request

## PicGo的相关信息
picgo2.2.0
windows 10 1909

## 功能请求
如题，设置中的“选择显示的图床”的设置能否同步作用于相册里？？
如下图，设置里取消勾选的图床，在这相册里仍然会列出来：
![图片](https://user-images.githubusercontent.com/38492750/72031692-22634300-32c8-11ea-9750-eeb72e648fb8.png)

---

**Comment by Molunerfinn** [comment]
由于有些图床的图片在取消某个图床显示前也有可能上传过，所以这个地方删去图床会导致可能筛选不到图片。所以这个地方暂时不会做联动。
