### ISSUE TITLE
状态栏图片加载不出来

### ISSUE THREAD

**Issue by monlor** [Molunerfinn/PicGo#384]
## 问题类型
Bug Report
图片上传成功后，github链接过一会才会生效，点击状态栏图片一直都显示不出来。建议点击状态栏的时候，加载一下没有加载出来的图片。

## PicGo的相关信息
Mac

## 问题重现
![](https://file.monlor.com/img/20200109112810.png)

## 功能请求

---

**Comment by Molunerfinn** [comment]
重启一下可以看到吗？另外建议如果用GitHub图床可以配合jsdelivr进行CDN加速，参考

https://segmentfault.com/a/1190000020240864

**Comment by Molunerfinn** [comment]
图片加载失败有很多原因，有可能是网络原因，有可能是图片链接就是不对，单纯重新加载并不能实际解决问题，还有可能会进入死循环。建议如果用GitHub可以采用jsdelivr加速。另外检查一下图片链接是否正确。

**Comment by monlor** [comment]
不是网络的问题，在相册里是可以加载出来的。![](https://file.monlor.com/img/20200109113641.png)

**Comment by monlor** [comment]
重启后，状态栏也能加载出来

**Comment by Molunerfinn** [comment]
> 重启后，状态栏也能加载出来

嗯，那就重启应用吧，这个问题不算是个bug，不过我后续会优化一下吧。

**Comment by monlor** [comment]
好的，谢谢🙏
