### ISSUE TITLE
Windows 10 安装不了

### ISSUE THREAD

**Issue by Syncma** [Molunerfinn/PicGo#385]
## PicGo的相关信息

Windows 10

## 问题重现

![image](https://user-images.githubusercontent.com/9897542/72050895-2cebff80-32fd-11ea-997f-2bd37de5f83f.png)

## 功能请求

---

**Comment by Molunerfinn** [comment]
先点击「更多信息」，然后再点击「运行」
![image](https://user-images.githubusercontent.com/12621342/72051218-c3202580-32fd-11ea-8d6b-d443f81f7b49.png)
