### ISSUE TITLE
Windos10无法再次打开PicGo

### ISSUE THREAD

**Issue by 54hanpenghui** [Molunerfinn/PicGo#388]
## 问题类型

Bug Report :W10 无法再次打开PicGo软件
## PicGo的相关信息
版本 :2.2.1  平台：Windows

## 问题重现
之前可以打开PicGo这个软件，但是重启电脑之后，再也无法打开PicGo

## 功能请求

---

**Comment by Molunerfinn** [comment]
无法打开是指什么，右下角的任务栏里也没有PicGo的图标么？另外你有没有装过 picgo-plugin-watermark这个插件？
用cmd打开picgo的exe，控制台输出了什么？

**Comment by 54hanpenghui** [comment]
安装过插件 
Something went wrong installing the "sharp" module

Module did not self-register.

- Remove the "node_modules/sharp" directory, run "npm install" and look for errors
- Consult the installation documentation at https://sharp.pixelplumbing.com/en/stable/install/
- Search for this error at https://github.com/lovell/sharp/issues

**Comment by 54hanpenghui** [comment]
安装过这个插件 然后 在 cmd中 执行 picgo,exe 报出一下问题

Something went wrong installing the "sharp" module

Module did not self-register.

- Remove the "node_modules/sharp" directory, run "npm install" and look for errors
- Consult the installation documentation at https://sharp.pixelplumbing.com/en/stable/install/
- Search for this error at https://github.com/lovell/sharp/issues

**Comment by Molunerfinn** [comment]
![image](https://user-images.githubusercontent.com/12621342/72124662-8a855800-33a0-11ea-8cb4-0c457a617a60.png)

**Comment by Molunerfinn** [comment]
相关issue：https://github.com/Molunerfinn/PicGo/issues/377

删除配置目录下的那几个文件和文件夹，就能重启PicGo了。然后需要安装水印插件的话目前不能直接在PicGo的插件界面安装，请按它的 [README](https://github.com/Dec-F/picgo-plugin-watermark) 来安装。
