### ISSUE TITLE
BUG:图片地址多个空格，导致无法显示 

### ISSUE THREAD

**Issue by naah69** [Molunerfinn/PicGo#39]
## 问题类型

Bug:图片地址多个空格，导致无法显示 
七牛的链接设置后，图片上传成功，但是回馈的地址有问题，多了一个空格

如下：
http:// p7sm08jsh.bkt.clouddn.com/img/WechatIMG1.jpeg

## PicGo的相关信息

版本：1.4.3
平台：Mac

## 问题重现

上传图片即可

![image](https://user-images.githubusercontent.com/25682169/39307879-9e93dc18-4996-11e8-806a-4aa0cdde7d64.png)

![image](https://user-images.githubusercontent.com/25682169/39307905-aada9660-4996-11e8-8b29-a46a908f106d.png)

**Comment by Molunerfinn** [comment]
多了个空格应该是你自己多写了一个空格吧...PicGo只负责拼接你的url+文件名而已。
![image](https://user-images.githubusercontent.com/12621342/39308959-6afe8512-4999-11e8-939e-b4cd6f9f1e6a.png)

**Comment by xuzuoyang** [comment]
@Molunerfinn 如果对于 url 中有空格的情况自动做转换（替换为%20）会不会更好一些？

**Comment by Molunerfinn** [comment]
> @Molunerfinn 如果对于 url 中有空格的情况自动做转换（替换为%20）会不会更好一些？

上传阶段做了url encode的处理了。这块应该是用户自定义的网址替换的时候没有处理，这里其实应该是合理的

**Comment by xuzuoyang** [comment]
@Molunerfinn 感谢回复，其实我碰到的情况是文件名中有空格，比如 ”2021-06-27 23.52.43.jpg“，所以如果能在拼接文件名之后做一次 encode 是不是会更好？

**Comment by Molunerfinn** [comment]
> @Molunerfinn 感谢回复，其实我碰到的情况是文件名中有空格，比如 ”2021-06-27 23.52.43.jpg“，所以如果能在拼接文件名之后做一次 encode 是不是会更好？
https://github.com/PicGo/PicGo-Core/blob/dev/src/core/Lifecycle.ts#L102
看了一下现在输出的url都是encode过的。如果你用的是旧版picgo确实没有处理。新版应该默认自带了

**Comment by xuzuoyang** [comment]
@Molunerfinn 好的，我看现在还在 beta 中，那我等正式版吧，再次感谢。
