### ISSUE TITLE
最新版2.2.1，安装完无法打开

### ISSUE THREAD

**Issue by huahuayu** [Molunerfinn/PicGo#392]
## mac os版本
10.15.2

## 错误详情
github release页面下载压缩包后，解压拖到/Applications目录下，打开picGo弹窗报错：the application "PicGo" can't be opened.
![image](https://user-images.githubusercontent.com/1725060/72217087-a89bb580-3564-11ea-852f-61f97743ac85.png)

p.s. 我以前装过老版本的。是不是配置不兼容了？但是我不想完全删除再重装，我以前配置的图床信息都会没有了

-------------------------
update：
下载PicGo.dmg的压缩包后去安装可以了。
出现了一个提示
![image](https://user-images.githubusercontent.com/1725060/72217158-bdc51400-3565-11ea-8d80-5522901a5767.png)
在安全与隐私设置选open anyway就好了

**Comment by Molunerfinn** [comment]
所以还是无法打开吗？

**Comment by huahuayu** [comment]
排查一下这个https://github.com/Molunerfinn/PicGo/releases/download/v2.2.1/PicGo-2.2.1-mac.zip压缩包解压出来的是不是有问题，反正直接拖到/Applications是不能打开的。dmg包可以安装，所以现在我能正常使用了。

**Comment by Molunerfinn** [comment]
这是自动构建的包。另外README里有说明请下载安装dmg格式的包。
