### ISSUE TITLE
picgo客服端上传后图片无法加载。GitHub图床

### ISSUE THREAD

**Issue by yimeng02** [Molunerfinn/PicGo#393]
## 功能请求

---

**Comment by Molunerfinn** [comment]
这不是好好的吗：
https://raw.githubusercontent.com/yimeng02/imgHosting/master/img/006yt1Omly1g8ogem7ahaj31kn0xhhdv.jpg

![](https://raw.githubusercontent.com/yimeng02/imgHosting/master/img/006yt1Omly1g8ogem7ahaj31kn0xhhdv.jpg)

**Comment by yimeng02** [comment]
处理好了。链接没设置好。非常感谢，
