### ISSUE TITLE
上传状态反馈优化[Feature Request]

### ISSUE THREAD

**Issue by mask2012** [Molunerfinn/PicGo#394]
## 问题类型

Feature Request

## 功能请求
我严重觉得缺少上传状态反馈
当我按快捷键的瞬间，是没有任何反馈的，这有点不科学，只能等待结果，这个结果可能是1秒，可能是2秒，4秒，存在不确定性，而你知道人是最不喜欢不确定性的。

**我有2种方案**
1 在按快捷键的时候picGo图标变成上传中的图标，成功/失败后依旧提示窗出现，同时图标复原
2 不通过图标，而是右下角始终出现提示窗，展示上传状态直到成功/失败

这个很小的功能改进会极大提高我的用户体验，我想也会更受大家欢迎，期待哦！

---

**Comment by Molunerfinn** [comment]
你可以打开上传前提示。

**Comment by Molunerfinn** [comment]
![image](https://user-images.githubusercontent.com/12621342/72487559-6070e180-3849-11ea-8dda-f33252f36792.png)
