### ISSUE TITLE
拖拽至上传区之后取消失败

### ISSUE THREAD

**Issue by Jactor-Sue** [Molunerfinn/PicGo#395]
## 问题类型

Bug Report

## PicGo的相关信息

Windows v2.2.1

## 问题重现

设置了Github图床为默认图床，打开上传前重命名选项，拖拽图片至上传区之后，点击取消，然后提示上传成功，查看Github仓库是按照默认名称上传的

## 功能请求

---

**Comment by Molunerfinn** [comment]
那个取消只是取消重命名，不是取消上传。目前没有取消上传这个功能
