### ISSUE TITLE
下载速度问题

### ISSUE THREAD

**Issue by gawainx** [Molunerfinn/PicGo#4]
下载 dmg 的速度很慢。。平均几十 k 每秒，挂了梯子也是这样。
希望可以提供一个直接从源码编译的方法~

**Comment by Molunerfinn** [comment]
之后我会更新一下文档，把自己构建相关的部分加上。
如果你在国内下载速度过慢的话，可以推荐你用这个[工具](https://www.freedownloadmanager.org/)来下载github里的东西，有加速。

**Comment by Molunerfinn** [comment]
如果你有node环境，你需要进入项目目录，然后先`npm install`安装依赖。然后在项目目录下执行`npm run build`就能构建，会在项目的build目录下构建出dmg文件。不过由于国内electron源的问题，构建过程中下载electron二进制会被墙，所以需要在`npm run build`之前输入如下：

```
export ELECTRON_MIRROR="https://npm.taobao.org/mirrors/electron/"
```
指定一下electron的源，然后再`npm run build`即可。
