### ISSUE TITLE
开启启动报错

### ISSUE THREAD

**Issue by Littlegolden** [Molunerfinn/PicGo#402]
## 问题类型

Bug Report

## PicGo的相关信息

Windows 10 - PicGO v2.2.2.42

## 问题重现

【描述】设置了开机自启PicGO，每次开机都会弹窗报错，关闭错误弹窗后，重新双击打开PicGo依然报错：
![image.png](https://i.loli.net/2020/01/31/kiC6NpzSRgJrfoE.png)

---

**Comment by Molunerfinn** [comment]
这个报错是你配置文件的JSON格式错了，检查一下你的JSON文件是不是有多或者少一些字符。

**Comment by Littlegolden** [comment]
@Molunerfinn data.json 文件打开乱码，我应该删除这个文件吗？

![image.png](https://i.loli.net/2020/02/03/inQxuYcT7CrOvKJ.png)

**Comment by Molunerfinn** [comment]
> @Molunerfinn data.json 文件打开乱码，我应该删除这个文件吗？
> 
> ![image.png](https://camo.githubusercontent.com/903724ce8da1b9e5a493f9414ca6fc4b1b4221b9/68747470733a2f2f692e6c6f6c692e6e65742f323032302f30322f30332f696e5178755963543743724f764b4a2e706e67)

嗯对，删除，然后重启picgo，picgo会自动重新生成
