### ISSUE TITLE
win7 右键图片上传失败

### ISSUE THREAD

**Issue by sunlewuyou** [Molunerfinn/PicGo#403]
## 问题类型
Bug Report

## PicGo的相关信息

版本：2.2.2 所在平台Windows 7 x64旗舰版

## 问题重现
![image](https://user-images.githubusercontent.com/19728435/73603831-d18ef380-45c2-11ea-90dd-d4397e2a56d8.png)
开启了上传提示，所以点击右键上传后弹出了正在上传的提示，实际却没传上去。
![image](https://user-images.githubusercontent.com/19728435/73603853-19ae1600-45c3-11ea-9ef8-1f560e59b808.png)

**Comment by Molunerfinn** [comment]
win7不支持右键上传图片。只有win10支持。

**Comment by sunlewuyou** [comment]
作者您回复问题好快呀！赞。那应该是在支持win7上您没有功夫完善是吧，因为我如果没有事先打开PicGo程序。而是首先直接右键上传调用打开程序上传的话就能完美上传，根据这个情况您能修复一下让其在win7平台也完美支持吗？谢谢，这个作品真是好用！！！
![image](https://user-images.githubusercontent.com/19728435/73603909-0c455b80-45c4-11ea-95a7-1967ea1897b9.png)

**Comment by Molunerfinn** [comment]
看后续有没有空了

**Comment by sunlewuyou** [comment]
好的，谢谢，star分享支持。

**Comment by Molunerfinn** [comment]
> 好的，谢谢，star分享支持。

感谢支持
