### ISSUE TITLE
希望能够增加拖拽浏览器中的图片上传的功能

### ISSUE THREAD

**Issue by linkot** [Molunerfinn/PicGo#406]
## 问题类型

功能请求
## PicGo的相关信息

mac，不过windows上应该也是需要的吧？
## 问题重现

![20200209012417](https://cdn.jsdelivr.net/gh/linkot/image/img/20200209012417.png)
似乎是功能没做，不算是BUG。
## 功能请求

..
拖拽浏览器中的图片上传就会提示如上图所示的提示，文件不符合需求。
个人理解并没有做这个功能，所以建议能够增加拖拽浏览器中的图片上传到自己的图床。
一般情况下右键复制再上传到也是可以的，但右键复制上传对比别的同类软件能够拖拽浏览器中图片上传画质似乎有损耗，另外gif的动态图右键复制上传之后变成了png格式的静态图片。所以还是希望能够增加直接拖拽浏览器中图片上传的功能。

---

**Comment by Molunerfinn** [comment]
在计划中

**Comment by Molunerfinn** [comment]
在计划中

**Comment by Molunerfinn** [comment]
调研了发现electron不支持监听从浏览器拖拽到mac顶部栏的拖拽事件。

不过Web可以监听到。所以可以在主窗口的上传区实现拖拽网页图片上传，但是无法直接拖拽到顶部栏图标上传。

这个功能预计在2.3版本发布。

**Comment by supercatreal** [comment]
> 在计划中

大概计划在什么时候嘞？很需要啊！

**Comment by Molunerfinn** [comment]
> > 在计划中
> 
> 大概计划在什么时候嘞？很需要啊！

2.3发布。dev分支已经支持，有需要自己编译构建一下就能用了

**Comment by supercatreal** [comment]
> > > 在计划中
> > 
> > 
> > 大概计划在什么时候嘞？很需要啊！
> 
> 计划在2.3发布。dev分支已经支持，有需要自己编译构建一下就能用了

如何进行编译呢？

**Comment by Molunerfinn** [comment]
2.3版本会更新这个功能。
