### ISSUE TITLE
七牛云图床图片能上传成功但是无法预览

### ISSUE THREAD

**Issue by loneyclown** [Molunerfinn/PicGo#408]
## 问题类型
Bug Report

## PicGo的相关信息
所在平台：MAC
所用版本：2.2.2

## 问题重现
图片能够成功上传，但是无法预览。图片url能够成功打开，访问权限为公有。
![01](http://static.loneyclown.vip/blog/20200212160234.png)

---

**Comment by Molunerfinn** [comment]
URL是不是少了 `http://` 或者 `https://` ？我记得这个问题在FAQ里有。

**Comment by Molunerfinn** [comment]
https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md#1%E4%B8%83%E7%89%9B%E5%9B%BE%E5%BA%8A%E4%B8%8A%E4%BC%A0%E5%9B%BE%E7%89%87%E6%88%90%E5%8A%9F%E5%90%8E%E6%97%A0%E6%B3%95%E6%98%BE%E7%A4%BA%E6%88%96%E5%9B%BE%E7%89%87%E6%97%A0http%E5%89%8D%E7%BC%80

**Comment by loneyclown** [comment]
好的，了解了。谢谢！
