### ISSUE TITLE
[Feature Request]相册页可否提供文件名预览

### ISSUE THREAD

**Issue by skyel1u** [Molunerfinn/PicGo#41]
## 问题类型

Feature Request

## PicGo的相关信息

Windows

## 功能请求

上传了很多gif后，使用预览图会消耗比较多的CPU资源，因此可否提供按文件名预览的选项？
![1](http://sky111-1253275619.coscd.myqcloud.com/20180427154508.png)
---

**Comment by Molunerfinn** [comment]
之后应该会加上搜索或者筛选的功能。
