### ISSUE TITLE
macOS Catalina无法打开PicGo

### ISSUE THREAD

**Issue by NCDWLQ** [Molunerfinn/PicGo#411]
## [今天刚打开PicGo提示升级，升级过后就打不开了
如图
<img width="532" alt="截屏2020-02-18上午11 40 25" src="https://user-images.githubusercontent.com/48175862/74701960-76f0cb00-5243-11ea-8072-488fa19fb9e1.png">

---

**Comment by Molunerfinn** [comment]
dmg格式的picgo也会出现这个问题么

**Comment by Molunerfinn** [comment]
没有新的反馈先关闭了。

**Comment by NCDWLQ** [comment]
> dmg格式的picgo也会出现这个问题么

我在下载站下的又没有问题，真奇怪

**Comment by anna0128economics** [comment]
还是打不开，dmg格式也打不开的，无法验证开发者什么的，请问怎么解决呀，谢谢
