### ISSUE TITLE
又拍云上传问题

### ISSUE THREAD

**Issue by SuooL** [Molunerfinn/PicGo#412]
## 问题类型

又拍云图床 上传错误

## PicGo的相关信息

Mac

## 问题重现

修改了下操作员和密码，结果就再也无法上传成功了，一直提示4010005的 `签名错误` 问题。

修改之前一直使用没有问题。

## 功能请求

---

**Comment by Molunerfinn** [comment]
签名错误说明picgo里的配置你没配对呀。后台修改了操作员密码，picgo里的改了么

**Comment by Molunerfinn** [comment]
检查配置吧，跟picgo关系不大。

**Comment by WangShuoran** [comment]
仔细看看是不是没有在云存储的服务配置中添加操作员

**Comment by zfhxi** [comment]
是不是开启了存储管理的文件密钥，关闭了试试
