### ISSUE TITLE
PicGo 在开启的情况下右键上传图片会失败

### ISSUE THREAD

**Issue by Roger-WIN** [Molunerfinn/PicGo#415]
## 问题类型

Bug Report

## PicGo的相关信息

- 2.2.2
- Windows 10

## 问题重现

在 PicGo 未启动的情况下，通过右键菜单项上传图片，PicGo 会先启动再上传图片，能成功上传。但是，如果 PicGo 已经启动，再通过右键菜单项上传图片，会出现上传失败的情况。
我在从 2.2.0 更新到 2.2.2 之后才遇到这个 bug。

## 功能请求

---

**Comment by Molunerfinn** [comment]
最近没有win10的设备，等有了之后测一下看看是啥问题

**Comment by Kaillis** [comment]
我系统是Win7也遇到同样的情况

**Comment by deicol** [comment]
win10  1909 18363.720 
同样情况,只有第一次上传成功,启动之后就没反应了

**Comment by Molunerfinn** [comment]
已知问题，可以先使用其他上传方式

**Comment by songhao8080** [comment]
![image](https://user-images.githubusercontent.com/10607039/77026581-f4d4fd00-69ce-11ea-96bf-9a1b068c417e.png)
原来一直正常使用，现在突然间不行了

**Comment by Molunerfinn** [comment]
> ![image](https://user-images.githubusercontent.com/10607039/77026581-f4d4fd00-69ce-11ea-96bf-9a1b068c417e.png)
> 原来一直正常使用，现在突然间不行了

你这个是PicGo Server的端口不是36677，去PicGo设置里调整一下Server的端口吧。
