### ISSUE TITLE
图片上传后,在相册中显示以下情况

### ISSUE THREAD

**Issue by tockchen** [Molunerfinn/PicGo#420]
## 问题重现

![image](https://user-images.githubusercontent.com/23721319/75606257-ec9f4580-5b25-11ea-909e-9cb919684839.png)

![image](https://user-images.githubusercontent.com/23721319/75606241-be216a80-5b25-11ea-95a6-76c15a67a7d4.png)

**Comment by Molunerfinn** [comment]
发issue前，请你看看FAQ第一条
