### ISSUE TITLE
PicGO-server 不支持跨域请求吗？

### ISSUE THREAD

**Issue by TianZonglin** [Molunerfinn/PicGo#421]
PicGO-server 不支持跨域请求吗？

比如在服务器上运行 PicGO，然后在GitHub托管的网站上写个upload控件，

点击上传直接调用 serverIP:36677/upload，

这个设想是否可行呢。（目前有跨域的错误）

答复后即可删除此条。

**Comment by Molunerfinn** [comment]
跨域只有浏览器才会有。PicGo Server是node Server。只不过没做cors而已。
想在服务器上运行直接写个node Server搭配PicGo core就行了，不然还开个GUI界面不累吗

**Comment by TianZonglin** [comment]
原来如此，晓得了
