### ISSUE TITLE
希望github图床能与PicGo相册保持同步

### ISSUE THREAD

**Issue by ChloeKurumi** [Molunerfinn/PicGo#422]
## 功能请求

希望github图床增加同步仓库图片的功能，目前删除PicGo相册里的图片后，github仓库的图片依然存在。而且批量上传中断后，仓库实际图片数量和PicGo相册的图片数量不一致。希望相册中显示的图片能与github设置里的指定存储路径的github仓库路径保证图片一致

**Comment by Molunerfinn** [comment]
已经有github-plus插件做了这件事
