### ISSUE TITLE
smms 安装插件 一直显示安装中

### ISSUE THREAD

**Issue by gooker** [Molunerfinn/PicGo#423]
## 问题类型

Bug Report

## PicGo的相关信息

Windows 10 

## 问题重现

反复重启多次,一直安装不了
安装的时候选全部用户/个人用户都不行.

![20200302150500.png](https://i.loli.net/2020/03/02/7gWKq83GrDXHnSk.png)

https://i.loli.net/2020/03/02/7gWKq83GrDXHnSk.png

**Comment by Molunerfinn** [comment]
![image](https://user-images.githubusercontent.com/12621342/75653618-e9789680-5c98-11ea-8859-f57c5ec3885d.png)
网络问题，PicGo调用的是npm的命令。如果插件界面安装不上就去日志文件所在的目录

```
npm install picgo-plugin-smms-user
```

装不上就挂代理。

**Comment by gooker** [comment]
想手动安装,发现没有cmd里面npm 命令 ,可能这个导致的吧

**Comment by Molunerfinn** [comment]
那你需要安装一下Node.js

**Comment by gooker** [comment]
> 那你需要安装一下Node.js
ok 好了
