### ISSUE TITLE
Window 10下七牛云上传图片成功，相册缩略图加载不出来

### ISSUE THREAD

**Issue by littlelk** [Molunerfinn/PicGo#424]
## 问题类型
Bug Report

## PicGo的相关信息
2.2.2 Window10

## 问题重现

![image](https://user-images.githubusercontent.com/21982496/75657880-25642980-5ca2-11ea-8177-08f2643ab1ab.png)
![1583137392(1)](https://user-images.githubusercontent.com/21982496/75657892-2dbc6480-5ca2-11ea-8cb2-a186ceb4a0ae.png)

## 功能请求

---

**Comment by Molunerfinn** [comment]
FAQ第一条。
