### ISSUE TITLE
代理功能不起作用？

### ISSUE THREAD

**Issue by ysmintor** [Molunerfinn/PicGo#429]
## 问题类型

PIcGo 填写了 HTTP 代理，但 imgur 图床在未全局代理下，上传图片不显示(空白)，打开全局代理后，重启 PicGo 即可正常。用的 Http 代理地址也用在了 imgur 里，能够上传图片，因此确定 HTTP 代理地址正常。

## PicGo的相关信息

Mac 2.2.2

## 问题重现
如下图所示，未全局代理，但 PicGo 已经设置代理情况下，图片显示不正常。

![image](https://user-images.githubusercontent.com/7165048/75968823-fac7da00-5f08-11ea-9d6c-534df967fdd6.png)

## 功能请求

---

**Comment by Molunerfinn** [comment]
代理只是负责上传的时候的代理。图片显示的代理依赖于系统代理。
