### ISSUE TITLE
win10 1903版本系统级别右键菜单失效，原注册表写入的值换位置了

### ISSUE THREAD

**Issue by lyandzao** [Molunerfinn/PicGo#430]
## 功能请求

---

**Comment by Molunerfinn** [comment]
手头没有Windows设备无法测试。值换位置是什么意思能说一下么？如果你对这个了解的话欢迎提个PR。

注册表写入相关文件：https://github.com/Molunerfinn/PicGo/blob/dev/build/installer.nsh

**Comment by lyandzao** [comment]
@Molunerfinn 我试着在nsis字段加上perMachine: true，然后它工作了，是我犯傻了，要为PicGo提供管理员权限才能写入注册表，即在安装时选择为所有用户安装，之前我一直是默认只为我（用户）安装

**Comment by Molunerfinn** [comment]
OK，那我这个会往文档里补充。先不算bug啦。
