### ISSUE TITLE
现可以使用 Chocolatey 安装 PicGo

### ISSUE THREAD

**Issue by iYato** [Molunerfinn/PicGo#433]
## 问题类型
Feature request

## PicGo的相关信息
Windows

## 功能请求
现在可以使用 Chocolatey 安装 PicGo。
Package 详情：https://chocolatey.org/packages/picgo
```powershell
choco install picgo
```

---

**Comment by Molunerfinn** [comment]
感谢，是你在维护吗？如果是我就补充到README里

**Comment by iYato** [comment]
> 感谢，是你在维护吗？如果是我就补充到README里

是我在维护。仓库路径：https://github.com/iYato/chocolatey-packages/tree/master/picgo

**Comment by Molunerfinn** [comment]
@iYato 感谢贡献！已经更新README
