### ISSUE TITLE
picgo mac版安装后没有主界面？是不是和mac os版本有关？

### ISSUE THREAD

**Issue by greatboyzhx** [Molunerfinn/PicGo#435]
## 问题类型

picgo mac版安装后没有主界面？是不是和mac os版本有关？

## PicGo的相关信息

我的10.15.3，picgo是最新2.2.2 dmg

## 问题重现

http://cdn.zhxhz.top/image/picgo_bug.png
左键或右键都一样，无法唤醒主界面出来

## 功能请求

---

**Comment by Molunerfinn** [comment]
右键，打开详细窗口。提问之前看看文档

**Comment by CuihuaXia** [comment]
我的也出现无法打开设置界面的问题，Mac OS 10.15.3，反复重装了很多次了，包括不同的版本，一直无法解决这个问题

**Comment by greatboyzhx** [comment]
右键pic图标就出现了，选择打开详细窗口。  Mac 默认触摸板按住两个键
ac 


 原始邮件 
发件人: Cuihua Xia<notifications@github.com>
收件人: Molunerfinn/PicGo<PicGo@noreply.github.com>
抄送: zhx<961825978@qq.com>; Author<author@noreply.github.com>
发送时间: 2020年3月23日(周一) 18:44
主题: Re: [Molunerfinn/PicGo] picgo mac版安装后没有主界面？是不是和mac os版本有关？ (#435)


我的也出现无法打开设置界面的问题，Mac OS 10.15.3，反复重装了很多次了，包括不同的版本，一直无法解决这个问题
