### ISSUE TITLE
GitHub图床经常性无法上传

### ISSUE THREAD

**Issue by hongcyu** [Molunerfinn/PicGo#436]
## 问题重现

在上传一段时间后再重新上传就会出现无法上传的情况。
重新启动几次加上等一段时间后才会好。

![image](https://user-images.githubusercontent.com/41502466/76425175-3ae4fc00-63e4-11ea-89c8-8aba25f66269.png)

![image](https://user-images.githubusercontent.com/41502466/76425234-4cc69f00-63e4-11ea-9d44-b131ef99ef35.png)

**Comment by Molunerfinn** [comment]
github服务器问题
