### ISSUE TITLE
Picgo-2.2.2 win10下配置阿里云图床上传失败.

### ISSUE THREAD

**Issue by thecatcher** [Molunerfinn/PicGo#438]
## 问题类型

**Bug Report** 
在win10下使用picgo-2.2.2配置阿里云图床,上传后发生错误. 
检查日志看到如下错误:
![日志](https://user-images.githubusercontent.com/18423291/76704738-ff18a200-6715-11ea-8660-9d3e3272ab9e.png)

![阿里云图床配置](https://user-images.githubusercontent.com/18423291/76704782-4dc63c00-6716-11ea-90e2-f465d45cac20.png)

## PicGo的相关信息
PicGo版本:2.2.2 
Windows 10 Version 1903 64位

**Comment by Molunerfinn** [comment]
这个是网络问题，过一会重新上传试试。

**Comment by thecatcher** [comment]
测试了多次,依旧不行

**Comment by thecatcher** [comment]
测试了多次,发现文件传图是没有问题的,但是通过微信截图后 剪贴板上传就会报错

**Comment by Molunerfinn** [comment]
> 测试了多次,发现文件传图是没有问题的,但是通过微信截图后 剪贴板上传就会报错

剪贴版上传的报错发一下看看？

**Comment by thecatcher** [comment]
![1](https://user-images.githubusercontent.com/18423291/76728917-e8646080-6792-11ea-83f9-7a793e97694a.png)
每次都是这个样子,进度条在这里卡一下,然后弹出下图通知. 
![2](https://user-images.githubusercontent.com/18423291/76728920-ea2e2400-6792-11ea-802f-0cd5ad617738.png)
之后在日志里看到这样的错误
![3](https://user-images.githubusercontent.com/18423291/76728921-ec907e00-6792-11ea-9dcd-7dbe624bf9e3.png)

**Comment by Molunerfinn** [comment]
大概了解问题所在了，你试试不开「时间戳重命名」以及图片上传前重命名的功能再看看剪贴板图片上传是否正常？

**Comment by thecatcher** [comment]
已解决,安装好之后默认是没有打开时间戳重命名和文件重命名的. 但是我把这俩功能打开了之后却可以使用了. 现在把这俩功能关掉之后也可以正常上传了. 好奇怪...是不是初始的配置文件中缺少什么东西呀...

**Comment by Molunerfinn** [comment]
> 已解决,安装好之后默认是没有打开时间戳重命名和文件重命名的. 但是我把这俩功能打开了之后却可以使用了. 现在把这俩功能关掉之后也可以正常上传了. 好奇怪...是不是初始的配置文件中缺少什么东西呀...

这就很奇怪了，理论上不应该是这样的现象。不过昨天我以为找到的问题后来看了一下并不是问题。等之后我再测测。这个问题先关闭了。
