### ISSUE TITLE
win10 图标显示异常

### ISSUE THREAD

**Issue by fuyitaoqqq** [Molunerfinn/PicGo#439]
## 问题类型
安装PicGo后，图标显示为方块

## PicGo的相关信息
windows version：1909
PicGo version：2.2.2
node version：v12.16.1

## 问题重现
![](https://oss.animalcity.cn/typora/202003/16/000256-700455.png)

## 功能请求

---

**Comment by Molunerfinn** [comment]
这个很奇怪从来没出现过。可以考虑安装的时候选择「给所有用户使用」（会触发使用管理员模式安装）。不过应该不影响正常使用

**Comment by fuyitaoqqq** [comment]
@Molunerfinn  昨天本地项目中在html中引入的icon也变成方块了，但是今天正常。PicGo我使用管理员模式重新安装了给所有用户使用，现在还是这个样子

**Comment by Molunerfinn** [comment]
不太确定是什么问题...理论上PicGo的字体文件是本地资源不会出现这种情况。

**Comment by fuyitaoqqq** [comment]
可以自己通过源码编译exe文件吗，我试试看自己编译行不行得通

**Comment by Molunerfinn** [comment]
> 可以自己通过源码编译exe文件吗，我试试看自己编译行不行得通

当然可以，你甚至可以用开发模式看看浏览器控制台报了什么错
