### ISSUE TITLE
Linux下显示有问题

### ISSUE THREAD

**Issue by windedge** [Molunerfinn/PicGo#44]
在manjaro下自己编译显示不正常, 如图

![manjaro](http://p5b0sd0vz.bkt.clouddn.com/img/DeepinScreenshot_picgo_20180504105043.png)

**Comment by Molunerfinn** [comment]
目前我并没有对linux做适配，所以无法解决是什么问题

**Comment by windedge** [comment]
不考虑增加linux支持吗?

**Comment by Molunerfinn** [comment]
目前精力有限，暂时无法兼容到linux，很抱歉...

**Comment by Molunerfinn** [comment]
你这个有可能是显卡的问题，不过我不是很确定，之前有个windows用户提过类似的：
https://github.com/Molunerfinn/PicGo/issues/35

**Comment by Molunerfinn** [comment]
v1.6版本更新，支持linux了，bug也解决了。
