### ISSUE TITLE
StatusCodeError 422

### ISSUE THREAD

**Issue by ZheYuuu** [Molunerfinn/PicGo#440]
## 问题类型

Bug Report

## PicGo的相关信息

1.4.7
ubuntu 18.04
## 问题重现

![image](https://user-images.githubusercontent.com/34906216/76707844-8e7d7f80-672d-11ea-9d55-fd68522c7cd2.png)

## 功能请求

---

**Comment by Molunerfinn** [comment]
说明你GitHub仓库里已经有同名文件了。PicGo的github图床不允许上传同名文件。

**Comment by xuchao996** [comment]
> 

是这样，但是在哪里看errcode message 呢？我在官网没有看到相关。
再次感谢大佬~
