### ISSUE TITLE
BUG反馈 PicGO可以运行后台，但无法打开主界面

### ISSUE THREAD

**Issue by skrbug** [Molunerfinn/PicGo#443]
之前打开过主界面，因为自己更换了OSS的AccessKey，怎么也打开不了（picGO还在后台运行，也能上传图片，只是显示不了主界面)，重启也无效。

OS: Mac 15.3 

picGO 版本 : 2.2.2 和  2.2.1都进行了尝试

**Comment by Molunerfinn** [comment]
https://github.com/Molunerfinn/PicGo/issues/435

**Comment by skrbug** [comment]
我裂开了 一直使用触摸板，Ctrl + 单点  != 右键。  插上鼠标后没问题了
