### ISSUE TITLE
请问一下GitHub现在是也有防盗链了吗？

### ISSUE THREAD

**Issue by Mr-Nobody-li** [Molunerfinn/PicGo#444]
## 问题类型

Bug report

## PicGo的相关信息

PicGo-Setup-2.2.2.exe
Windows

### 请问一下GitHub也有防盗链了吗？
我将图片复制到picgo中上传成功了，不管以md还是url格式输出再复制到CSDN中，都提示：外链图片转存失败,源站可能有防盗链机制,
![](https://raw.githubusercontent.com/Mr-Nobody-li/typora/master/typora-img/0P(%25%5D%60P78N0_3Q%24%60%7E_QIFK0.png)

**Comment by Molunerfinn** [comment]
没有。出现这个问题也不是PicGo的问题。

**Comment by Molunerfinn** [comment]
而且你这个链接是404，怎么可能访问得了…
