### ISSUE TITLE
希望可以添加多个自定义链接，和postimage的上传图床

### ISSUE THREAD

**Issue by guhailong18** [Molunerfinn/PicGo#445]
因为不同的图床需要有不同的自定义链接，所以我希望有多个自定义！
而且我发现了一个非常nice的图床，官网地址：https://postimage.org
希望可以弄个插件。

**Comment by Molunerfinn** [comment]
自定义链接后续会考虑扩展。其它图床就看有没有人愿意写插件了，欢迎。
