### ISSUE TITLE
macos无法打开软件

### ISSUE THREAD

**Issue by nieaowei** [Molunerfinn/PicGo#447]
## 问题类型
Bug Report

## PicGo的相关信息

Macos15.4
最新版

## 问题重现
![image](https://user-images.githubusercontent.com/42961884/77567774-9ba32700-6f02-11ea-9dfd-d8c504febb92.png)

与该问题一致 #411 

---

**Comment by Molunerfinn** [comment]
请使用dmg格式的安装包
