### ISSUE TITLE
某些插件已无法安装

### ISSUE THREAD

**Issue by nieaowei** [Molunerfinn/PicGo#448]
## PicGo的相关信息

MacOs15.4
最新版

## 功能请求
该插件是watemark，安装其他插件事不会有此错误，昨天安装此插件时也是正常安装
![38AD4BA69FDE080A7A4D22331F3DDE77](https://user-images.githubusercontent.com/42961884/77642824-3f3f1680-6f99-11ea-9b46-657cac1d5b4e.png)

**Comment by Molunerfinn** [comment]
额，我的理解是，这个属于插件的问题，去插件仓库提吧~
