### ISSUE TITLE
Mac最新版本不能拖图标到菜单栏完成上传操作，1.2.0版本没啥问题😂

### ISSUE THREAD

**Issue by wanggw911** [Molunerfinn/PicGo#45]
## 问题类型

Bug Report

## PicGo的相关信息

Mac 1.4.3

## 问题重现

拖动到图标处，显示➕号，但是不能上传，没截图。。。

## 功能请求

---

**Comment by Molunerfinn** [comment]
v1.5版本里已经将这个bug修复。静候v1.5版本更新，应该是下周。
之前也有人提出过这个问题：https://github.com/Molunerfinn/PicGo/issues/34

**Comment by Molunerfinn** [comment]
v1.5版本发布，修复了这个问题，欢迎更新体验。
