### ISSUE TITLE
[PicGo SUCCESS] 之后返回的链接为 undefined

### ISSUE THREAD

**Issue by yarkable** [Molunerfinn/PicGo#450]
## PicGo的相关信息

win10 教育版
PicGo 2.2.2
typora 0.9.86 beta

## 问题重现

上传一张图片后显示 { ‘success’: false }，log 中返回undefined，几率事间

![undefined](https://i.loli.net/2020/03/27/iak9bfQnDUZwKz2.jpg)

**Comment by Molunerfinn** [comment]
用的什么图床啊？

**Comment by Molunerfinn** [comment]
不知道是不是用了什么插件的原因导致的，有使用什么插件么？以及上传方式是剪贴板上传呢还是图片拖拽上传呢？希望提供更详细一点的信息吧。

**Comment by yarkable** [comment]
@Molunerfinn 使用的是 sm.ms 图床，PicGo 插件使用 web-uploader 1.1.1 ，通过剪贴板上传，现在几乎不会了，原因未知

**Comment by Molunerfinn** [comment]
估计跟插件有关系，跟PicGo自带的无关。
