### ISSUE TITLE
经常性上传图片失败，偶尔可以上传成功，配置应该没有问题。

### ISSUE THREAD

**Issue by Steven-Shixq** [Molunerfinn/PicGo#452]
## 问题类型

`Bug Report`

## PicGo的相关信息

windows 10, picgo版本：2.2.2
## 问题重现
不管是拖拽上传，还是从剪贴板复制，经常性上传失败，偶尔才能上传成功。我用的是github的图床
大家都没有这个问题吗？我也不晓得是什么原因，请大家帮忙分析分析。谢谢。

![image](https://user-images.githubusercontent.com/37492848/77822385-1a7ba800-712d-11ea-9f2a-a0c1de6c8408.png)

## 功能请求

---

**Comment by Molunerfinn** [comment]
github服务器问题，无解。

**Comment by Steven-Shixq** [comment]
> github服务器问题，无解。想要稳定性高，就去买阿里云，腾讯云等付费的产品

哦，翻墙状态下也这样，我以为不是github服务器的问题。谢谢

**Comment by 4rnold** [comment]
@Molunerfinn 可否增加自动重试机制，可让用户选择重试次数。

**Comment by Molunerfinn** [comment]
> @Molunerfinn 可否增加自动重试机制，可让用户选择重试次数。

只有github会这样，没必要专门去做一个机制适配，这个问题是github服务器限频，短时间内连续重试的意义也不大。并且本来使用就是免费的，稳定性难免没有保障，如果要追求稳定还是推荐使用付费的。

**Comment by zoomlion** [comment]
额，我出现过类似的情况，但是似乎可以通过更改ssr到pac（绕过大陆和局域网）的方式得到缓解。实在不行就多按几次快捷键也是能work的。
