### ISSUE TITLE
CPU消耗高，Mac风扇转的厉害

### ISSUE THREAD

**Issue by huahuayu** [Molunerfinn/PicGo#453]
## 问题类型
性能问题

## PicGo的相关信息
Mac 10.15.4
PicGo 2.2.1

## 问题重现
我都没有在用picGo，后台不知道运行什么任务，占了10%的cpu（2.6 GHz 6-Core Intel Core i7）
![image](https://user-images.githubusercontent.com/1725060/78004233-69fbe700-736c-11ea-96af-27fe9e278bf8.png)

**Comment by Molunerfinn** [comment]
后台没有运行什么任务啊。GPU耗费了5%很奇怪，理论上放到后台不会有渲染相关的操作。

可以先退出或者重启应该能解决。需要一个可复现的操作，或者就是最近上传有没有什么报错日志之类的？

**Comment by Molunerfinn** [comment]
有一个已知的问题大概是2.2.2版本的PicGo Server端口的问题，提供一下最近的日志，看看是不是Server在疯狂重启

**Comment by huahuayu** [comment]
我安装了最新的2.2.2了，但是cpu占用和2.2.1一样，都很高

日志文件https://gist.github.com/huahuayu/f30f95c4bb2c26e85ad40f0820c18f0c

![image](https://user-images.githubusercontent.com/1725060/78094123-58ffb400-7406-11ea-841d-485c4fa3e1b2.png)

**Comment by Molunerfinn** [comment]
无法复现...看日志也没有什么问题- -...
![image](https://user-images.githubusercontent.com/12621342/78094312-d0354800-7406-11ea-9512-cdcf10391e8b.png)

**Comment by huahuayu** [comment]
> 后台没有运行什么任务啊。GPU耗费了5%很奇怪，理论上放到后台不会有渲染相关的操作。
> 
> 可以先退出或者重启应该能解决。需要一个可复现的操作，或者就是最近上传有没有什么报错日志之类的？

试过重启没有用，也没报过什么错，一打开就是两个进程各5%左右的cpu占用

**Comment by huahuayu** [comment]
![image](https://user-images.githubusercontent.com/1725060/78094469-30c48500-7407-11ea-8587-c603e26cd72c.png)

**Comment by huahuayu** [comment]
看下动图 https://cdn.liushiming.cn/img/2020-04-01_10-53-16 (1).gif

**Comment by Molunerfinn** [comment]
是的不过我这边无法复现...，我的PicGo开在后台都十几个小时了都是几乎0占用。而且确实PicGo后台没有运行什么任务，理论上不应该会占用CPU。你给我看占用图对我解决问题也没啥帮助- -。日志上也看不出问题

**Comment by huahuayu** [comment]
你试过用htop看吗

**Comment by huahuayu** [comment]
是不是因为我上传了一些git动图，然后picgo会预览这些图片，造成了资源消耗，比如说下面这张
https://cdn.liushiming.cn/img/2020-03-31_15-35-53.gif

**Comment by Molunerfinn** [comment]
可能是顶部小窗口的问题。你可以试试上传几张小一点的静态图把顶部小窗口的最近5张gif给顶掉，看看还会不会有这个问题
![image](https://user-images.githubusercontent.com/12621342/78094898-471f1080-7408-11ea-80bf-0a82136708c7.png)

**Comment by Molunerfinn** [comment]
![image](https://user-images.githubusercontent.com/12621342/78095228-feb42280-7408-11ea-919c-5adf2273f95b.png)
用了htop看了一下我的还更高。但是我的风扇并不会转...

**Comment by Molunerfinn** [comment]
试了一下，你把详细窗口打开，然后不要选中相册页，打开上传页就行。然后再关闭详细窗口，就没有占用了：
![image](https://user-images.githubusercontent.com/12621342/78095401-69fdf480-7409-11ea-814e-00b134b6722e.png)

**Comment by huahuayu** [comment]
我试过了，顶掉我两张git动图就OK了，基本没什么占用了  
![image](https://user-images.githubusercontent.com/1725060/78095635-02947480-740a-11ea-914e-5f53b0553155.png)

**Comment by Molunerfinn** [comment]
OK。可能小窗那边是hide不是close，所以可能在后台的时候还在渲染gif吧。渲染gif确实会比较耗费CPU和GPU。

**Comment by Molunerfinn** [comment]
这块后续我看看怎么优化吧。在后台的时候我就取消页面渲染。

**Comment by huahuayu** [comment]
ok，多谢支持

**Comment by sqzxcv** [comment]
这个问题什么时候能更新呢, 或者有没有办法清理小窗口的图片,
