### ISSUE TITLE
上传后的URL编码问题

### ISSUE THREAD

**Issue by wingsico** [Molunerfinn/PicGo#454]
## 问题类型

Bug Report

## PicGo的相关信息

version: 2.2.2
os: Mac

## 问题重现

当上传的文件名含有空格或其他在url内需要编码的字符，上传成功后，得到的url是未编码的，导致地址错误。在markdown引用时需要手动先复制到浏览器地址栏进行编码后使用。

例如文件名为：test 123.png，上传成功后得到 `http://xxx.cn/images/test img.png` 而不是 `http://xxx.cn/images/test%20img.png`

**Comment by Molunerfinn** [comment]
后续版本会更新支持这个feature

**Comment by PlaneJun** [comment]
> 后续版本会更新修复这个问题。这个问题主要还是在[PicGo-Core](https://github.com/PicGo/PicGo-Core)里

22年了这个问题还在，还是说需要开启什么设置呢

**Comment by Molunerfinn** [comment]
> > 后续版本会更新修复这个问题。这个问题主要还是在[PicGo-Core](https://github.com/PicGo/PicGo-Core)里
> 
> 22年了这个问题还在，还是说需要开启什么设置呢

你是什么版本呢？以及出现问题的case给一个可复现的？

**Comment by hieroglyphicss** [comment]
作者您好，picgo-core还是会出现url被编码的问题，我使用的是腾讯云cos

链接为https://blog-1310575002.cos.ap-chengdu.myqcloud.com/img/2023%2F06%2F18%2F20230618172607.png
