### ISSUE TITLE
插件无法下载

### ISSUE THREAD

**Issue by colderleo** [Molunerfinn/PicGo#457]
## 问题类型
Bug Report

## PicGo的相关信息
win10， picgo2.2.2

## 问题重现
插件搜索后点安装，一直是安装中，gitee和gitee uploader都是

## 功能请求

---

**Comment by colderleo** [comment]
应该是nodejs没安装，软件上能加个提示就好了

**Comment by Molunerfinn** [comment]
这块原本是有加的，后来有其他bug暂时去掉了。以后会补回来。
