### ISSUE TITLE
npm install命令出现错误

### ISSUE THREAD

**Issue by supercatreal** [Molunerfinn/PicGo#458]
执行npm install以后出现如下问题。
![](https://user-images.githubusercontent.com/35121766/78879797-fdc56580-7a86-11ea-810b-6f4bf2eda1bd.png)
如图所示，共执行了两次，仍然是这个问题。

**Comment by Molunerfinn** [comment]
文档没来得及更新。安装依赖请使用[yarn](https://classic.yarnpkg.com/en/docs/install#windows-stable)而不用npm install

进根目录后，yarn即可。
```
yarn
```

如果遇到网络问题下载不了chrome-driver等请挂代理
