### ISSUE TITLE
希望以后可以在批量上传时批量重命名

### ISSUE THREAD

**Issue by paaroll** [Molunerfinn/PicGo#46]
## 问题类型

Feature Request

## PicGo的相关信息

Mac

## 功能请求

如果上传的时候可以批量重命名就好了。可以自定义命名规则。根据时间或者其它方式添加序号。

---

**Comment by Molunerfinn** [comment]
那么你应该是在上传前就批量重命名处理好而不是让PicGo来帮你做~

**Comment by Molunerfinn** [comment]
@paaroll 换句话说，PicGo本身只会提供简单的操作，重点依然是在上传后的复制。
2.0如果能开发出插件系统的话应该能有一些开发者能加入到开发，届时你的想法估计会有人来实现。

**Comment by paaroll** [comment]
我是没问题，有批量重命名的app可以帮我实现。
只是看到批量上传时弹出来一个一个小窗口重命名确认时，刚好想到而已。
