### ISSUE TITLE
希望可以增加相册内图片同步删除功能

### ISSUE THREAD

**Issue by inf1nityhhd** [Molunerfinn/PicGo#462]
## 问题类型

Feature Request
## PicGo的相关信息

版本：v2.2.2
平台：Windows
## 功能请求
希望能增加一个图片同步删除的功能。当前的相册管理只是单纯的删除掉本地的记录，云端的存储信息还需手动更改来实现同步，这样十分的不方便，如果有同步删除功能的话，就非常的优雅和便捷了。

---

**Comment by Molunerfinn** [comment]
如果是Github图床已经有插件实现了。其它图床可以等其它插件实现。本体是不会做的之前的issue里已经说了。
