### ISSUE TITLE
链接无效

### ISSUE THREAD

**Issue by zhaobuqi-01** [Molunerfinn/PicGo#465]
## 问题类型

bug report
## PicGo的相关信息
picgo2.2.2 windows

## 问题重现
图片上传成功，链接无而且在github仓库的图片也是

链接地址:https://raw.githubusercontent.com/zhaobuqi-01/photo/master/20200418175326.png

![image](https://user-images.githubusercontent.com/62971297/79634880-e03b7e80-819f-11ea-862d-c44a41eabfba.png)
![image](https://user-images.githubusercontent.com/62971297/79634926-2c86be80-81a0-11ea-99f4-7a926d8fee28.png)

## 功能请求

---

**Comment by zhaobuqi-01** [comment]
@Molunerfinn

**Comment by Molunerfinn** [comment]
自己的设置问题。

**Comment by Molunerfinn** [comment]
上传已经成功了，链接是你自己设置错了。跟PicGo没关系。
![image](https://user-images.githubusercontent.com/12621342/79635172-f77b6b80-81a1-11ea-8d04-3d6b154ec3cc.png)
你给的链接根本就不对啊，你给的链接就没有这张图，自然是404
![image](https://user-images.githubusercontent.com/12621342/79635214-43c6ab80-81a2-11ea-9ae3-929798dbf394.png)
你图里的这张图片我这里是没问题的
![image](https://user-images.githubusercontent.com/12621342/79635192-1417a380-81a2-11ea-9902-918f6ca65d3a.png)
链接是这个[https://raw.githubusercontent.com/zhaobuqi-01/photo/master/20200418180621.png](https://raw.githubusercontent.com/zhaobuqi-01/photo/master/20200418180621.png)

**Comment by zhaobuqi-01** [comment]
好的，谢谢





---原始邮件---
发件人: "PiEgg"<notifications@github.com&gt;
发送时间: 2020年4月18日(周六) 晚上6:28
收件人: "Molunerfinn/PicGo"<PicGo@noreply.github.com&gt;;
抄送: "zhaobuqi-01"<1138883954@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [Molunerfinn/PicGo] 链接无效 (#465)




 
上传已经成功了，链接是你自己设置错了。跟PicGo没关系。
 
 你给的链接根本就不对啊，你给的链接就没有这张图，自然是404
 
 你图里的这张图片我这里是没问题的
 
 链接是这个https://raw.githubusercontent.com/zhaobuqi-01/photo/master/20200418180621.png

**Comment by zhaobuqi-01** [comment]
已解决我计算机附近的dns服务器不提供github的解析





---原始邮件---
发件人: "PiEgg"<notifications@github.com&gt;
发送时间: 2020年4月18日(周六) 晚上6:28
收件人: "Molunerfinn/PicGo"<PicGo@noreply.github.com&gt;;
抄送: "zhaobuqi-01"<1138883954@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [Molunerfinn/PicGo] 链接无效 (#465)




 
上传已经成功了，链接是你自己设置错了。跟PicGo没关系。
 
 你给的链接根本就不对啊，你给的链接就没有这张图，自然是404
 
 你图里的这张图片我这里是没问题的
 
 链接是这个https://raw.githubusercontent.com/zhaobuqi-01/photo/master/20200418180621.png
