### ISSUE TITLE
Linux安装AppImage文件出错

### ISSUE THREAD

**Issue by U181312** [Molunerfinn/PicGo#467]
## 问题类型
Bug Report

## PicGo的相关信息
版本：2.2.2  所在平台：Linux(Deepin V20)

## 问题重现
打开AppImage文件时，提示`/tmp/.mount_PicGo-s7aX7M/chrome-sandbox`权限不正确，但是似乎因为没有安装成功`/tmp/.mount_PicGo-s7aX7M`会被自动删除，无法为`chrome-sandbox`给予4755权限
以前安装linux版网易云音乐时也出现了同样的问题，但是安装失败`chrome-sandbox`文件夹会被保留，可以赋予正常权限之后重新安装
```cmd
[8898:0420/011642.495795:FATAL:setuid_sandbox_host.cc(157)] The SUID sandbox helper binary was 
found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You
 need to make sure that /tmp/.mount_PicGo-s7aX7M/chrome-sandbox is owned by root and has 
mode 4755.
```
![](https://picbed-zlx.oss-accelerate.aliyuncs.com/Markdown/截图录屏_dde-file-manager_20200420012852.png)

**Comment by Molunerfinn** [comment]
没有Linux机器...而且也不太熟悉这是为啥，权限问题的话只能谷歌了

**Comment by U181312** [comment]
> 没有Linux机器...而且也不太熟悉这是为啥，权限问题的话只能谷歌了

看来只能先用picgo-core了，非常感谢大佬做这个工具

**Comment by U181312** [comment]
> 没有Linux机器...而且也不太熟悉这是为啥，权限问题的话只能谷歌了

今天在谷歌上找到问题了，这是Linux内核的问题，解决方法四种，推荐第四种，一劳永逸
1. 启用用户名称空间： `sudo sysctl kernel.unprivileged_userns_clone=1`，但每次开机都要运行该命令。
2. 给报错信息给出的文件授权：`sudo chown root <path_to_marktext_dir>/chrome-sandbox && sudo chmod 4755 <path_to_marktext_dir>/chrome-sandbox`，但不适用于picgo，因为会自动删除。
3. 运行的时候加上免沙箱命令：`--no-sandbox`
4. 开机时自启动用户名称空间：`echo 'kernel.unprivileged_userns_clone=1' > /etc/sysctl.d/userns.conf`

只适用于Debian/Ubuntu系列Linux发行版。

**Comment by Molunerfinn** [comment]
赞一个

**Comment by xmuli** [comment]
>     3\. 运行的时候加上免沙箱命令：`--no-sandbox`

真的很棒，已经可以在 deepin / uos 20 上面运行了，这个问题从去年一直困扰我到今天，十分感谢你的解决方案
