### ISSUE TITLE
七牛图床上传照片后，已上传中显示图裂

### ISSUE THREAD

**Issue by mrbruce516** [Molunerfinn/PicGo#469]
## 问题类型

Bug Report

## PicGo的相关信息

macOS

## 问题重现

七牛图床上传照片后，已上传中显示图裂，但是图片是没问题的，链接可以正常使用  
![image](https://user-images.githubusercontent.com/46187947/79823332-18240b00-83c6-11ea-9ad2-a43f4e66612c.png)

**Comment by Molunerfinn** [comment]
FAQ第一条
