### ISSUE TITLE
腾讯云cos的v5版本上传失败

### ISSUE THREAD

**Issue by cooper1x** [Molunerfinn/PicGo#47]
![image](https://user-images.githubusercontent.com/9080789/39884186-86bd1246-54bb-11e8-837e-c92a97343a4b.png)
我核对了每一项配置，都是对的，但是就是传不上图片。

**Comment by cooper1x** [comment]
原来是腾讯COS和万象里面的名字不一样，COS的存储桶名称后面有一个数字串，加上这个才是完整的存储空间名。

**Comment by cooper1x** [comment]
那个数字串是APPID，比方说自己设置的Bucket名字叫demo，APPID是12345，那么这里完整的就是
demo-12345
![image](https://user-images.githubusercontent.com/9080789/39884438-68e73de0-54bc-11e8-802d-6bed514d48fe.png)

**Comment by Molunerfinn** [comment]
关于这点，我很早就在wiki里指出了:)，发issue之前请好好看看wiki。
![image](https://user-images.githubusercontent.com/12621342/39900331-c8360c90-54f3-11e8-8320-5b4fac88a107.png)

**Comment by lhalcyon** [comment]
我也遇到这个问题了. 但是反复校验,以及查看帮助文档了.还是失败,请问可能是什么原因?
![image](https://user-images.githubusercontent.com/21357951/57905585-98ceb300-78a9-11e9-98b5-7328d8ebf93e.png)

**Comment by lhalcyon** [comment]
不好意思,在[Issue](https://github.com/Molunerfinn/PicGo/issues/20) 找到了问题所在.. 复制的时候多了个空格!

**Comment by zengfanfu** [comment]
哭了，果然是复制多了个空格！
