### ISSUE TITLE
插件无法安装

### ISSUE THREAD

**Issue by jerryc127** [Molunerfinn/PicGo#470]
## 功能请求

---

windows 10最新版
picgo最新版

插件无法安装。。人在香港，排除网络问题
github plus 我安装了5次才装上，点击安装 然后显示安装中，一直这个状态
watermark 我到现在还没装上 一直显示安装中，中间有一次显示安装完成，但是我在搜一次 打算配置时，发现 显示 安装 按钮，又变回未安装
![image](https://user-images.githubusercontent.com/16351105/79831285-b1a8e800-83d9-11ea-9a72-68366d19e653.png)

一个建议： 打开picgo 希望窗口能自动打开，而不是要去右下角点击图标打开。。

**Comment by Molunerfinn** [comment]
node.js装了没？如果node.js已经安装了还是装不上，建议手动到picgo的日志目录输入 `npm install xxx --save-dev`

**Comment by jerryc127** [comment]
感谢答复
话说typora 只有 picgo-core
没有显示picgo app (已装picgo app)
这个怎么解决么

**Comment by Molunerfinn** [comment]
换简体中文。

**Comment by jerryc127** [comment]
我试了typora的验证图片上传
报错了
![image](https://user-images.githubusercontent.com/16351105/79846049-84b3ff80-83f0-11ea-88d5-1c7f423d3c4b.png)
怎么解决？

**Comment by Molunerfinn** [comment]
> 我试了typora的验证图片上传
> 报错了
> ![image](https://user-images.githubusercontent.com/16351105/79846049-84b3ff80-83f0-11ea-88d5-1c7f423d3c4b.png)
> 怎么解决？

typora会传两张一样名字的图片，github不允许传同名文件所以报错。不影响你正常使用- -。
