### ISSUE TITLE
PicGo 2.2.2 upload img to repository of github organization failed.

### ISSUE THREAD

**Issue by DreamLi1314** [Molunerfinn/PicGo#471]
#### Bug PicGo 2.2.2 upload img to repository of github organization failed throw server config error.

* PicGo Version: 2.2.2
* OS: Mac OS X(Mac Book Pro 2017 - 15.4)

> Note: upload on windows 10 is successfully.

**Comment by Molunerfinn** [comment]
Show me the logs

**Comment by Molunerfinn** [comment]
Please provide more details, includes logs of picgo
