### ISSUE TITLE
关于最近Typora显示图片链接无法加载，Picgo 客户端的图片也显示不出来

### ISSUE THREAD

**Issue by ppdxzz** [Molunerfinn/PicGo#472]
## 问题类型

Bug Report

## PicGo的相关信息

Windows Picgo 2.2.2

## 问题重现
![image](https://user-images.githubusercontent.com/56783460/80201215-5d5e6c00-8656-11ea-89bb-6d7dc4eaf51f.png)
![image](https://user-images.githubusercontent.com/56783460/80201283-7a933a80-8656-11ea-955a-7b3175516977.png)

---

**Comment by ppdxzz** [comment]
并未设置权限，两周前还可以正常使用，就是前几天就忽然成这样了

**Comment by Molunerfinn** [comment]
我这边没问题。最近github的节点有一些被墙了。这是你那边的网络问题。
![image](https://user-images.githubusercontent.com/12621342/80212809-c4861b80-866a-11ea-96c3-4fd695679229.png)

**Comment by PeachLuis** [comment]
我也是这样的问题，所有写的Typora文件的图片全崩了，没有什么解决办法吗？还是只有重新建个库？

**Comment by Molunerfinn** [comment]
> 我也是这样的问题，所有写的Typora文件的图片全崩了，没有什么解决办法吗？还是只有重新建个库？

最近墙升级了把github静态资源的节点屏蔽了不少。想要稳定就用阿里云、腾讯云这种付费的，github毕竟不保证稳定性。

**Comment by PeachLuis** [comment]
好的，谢谢了，但是我找到方法了，就修改下hosts文件就可以了

**Comment by asang24** [comment]
win10    picgo 2.2.2版本 , 相同的问题, 区别是我用的阿里云oss, typora 和picgo端都无法显示图片, 阿里云oss里有文件
