### ISSUE TITLE
文本框若不小心加入空格会导致配置失败

### ISSUE THREAD

**Issue by inf1nityhhd** [Molunerfinn/PicGo#474]
## PicGo的相关信息

版本：2.2.2
平台：Windows

## 问题重现
我在设置阿里云OSS时，点击"确定"按钮后显示"设置成功"，因此认为自己的操作无误，结果当我测试上传图片时却显示"上传失败，请检查您的配置是否正确"。之后我对着配置文档查找是否存在配置问题，但是没发现问题。  

最后查看输出日志，提示我"KeyId"存在错误，然后我又注意到"设定KeyId"和"设定KeySecret"两行没有对齐，发现原来导致上传失败的原因是在复制KeyId时在"设定KeyId"的文本框的首部多加了一个相当不起眼的空格。这个首部的空格导致配置出现了问题。
  
我认为这可能是在程序读取配置文件时没有进行trim操作去掉空格所导致的，但是既然一开始提示了"设置成功"，那么用户自然就会认为填写配置无误，而最后上传失败又导致前后矛盾。所以我认为这是一个配置检测相关的bug，可以在点击确认时提醒是否真的设置成功了，或者自动trim掉空格，再或者填写文本时检测输入格式是否正确。  

这可能是一个微不足道的问题，但是确实是客观存在的，希望维护团队能修复。

## 功能请求

---

**Comment by Molunerfinn** [comment]
这个问题以后会考虑优化，感谢建议
