### ISSUE TITLE
希望增加对 webp 格式图片的支持

### ISSUE THREAD

**Issue by yangchuansheng** [Molunerfinn/PicGo#475]
## 问题类型

Feature Request

## PicGo的相关信息

Mac

## 功能请求

希望增加对 webp 格式图片的支持

**Comment by Molunerfinn** [comment]
未来会考虑支持

**Comment by yangchuansheng** [comment]
> 未来会考虑支持

ipic 已经支持了

**Comment by Molunerfinn** [comment]
经测试，直接拖拽上传是已经支持的了。
