### ISSUE TITLE
【Bug Report】RequestError: Error: tunneling socket could not be established, cause=getaddrinfo ENOTFOUND 1080 @Windows 10, PicGoV2.2.2

### ISSUE THREAD

**Issue by xiaodl813** [Molunerfinn/PicGo#476]
## 问题类型

Bug Report
出现错误：
RequestError: Error: tunneling socket could not be established, cause=getaddrinfo ENOTFOUND 1080

## PicGo的相关信息

版本：2.2.2
平台：Windows 10 18363.778

## 问题重现

![image](https://user-images.githubusercontent.com/50045896/80324844-40e44e80-8865-11ea-9739-280dbbc6fa2b.png)
有关配置，使用了V2ray。并在软件内设置了代理127.0.0.1:1080
图床是自建的Github、阿里云的OSS

---

**Comment by Molunerfinn** [comment]
https://cnodejs.org/topic/52b3b178588ff25a72496f3b

**Comment by 1012598167** [comment]
我也是这个问题啊 但是cnodejs上不去

**Comment by 1012598167** [comment]
@Molunerfinn

**Comment by Molunerfinn** [comment]
> @Molunerfinn

你的网络问题我要怎么帮你解决？

**Comment by 1012598167** [comment]
> > @Molunerfinn
> 
> 你的网络问题我要怎么帮你解决？

![image](https://user-images.githubusercontent.com/40982544/97803542-109ec200-1c85-11eb-8d25-5fd94191dfbc.png)
我也怀疑是啊 但是我能正常访问我的自定义域名。
![image](https://user-images.githubusercontent.com/40982544/97803557-27ddaf80-1c85-11eb-8028-a8affa7ab9b1.png)

**Comment by guiaixiao** [comment]
@xiaodl813    @1012598167     win10->我的电脑->属性->高级系统属设置->环境变量里面，看看用户环境变量和系统环境变量里面，有没有一个值被设置成  127.0.0.1:1080，把它删了试试

**Comment by xiaoyue2019** [comment]
> 
> 
> @xiaodl813 @1012598167 win10->我的电脑->属性->高级系统属设置->环境变量里面，看看用户环境变量和系统环境变量里面，有没有一个值被设置成 127.0.0.1:1080，把它删了试试

guiaixiao yyds!!
