### ISSUE TITLE
Mac上打不开菜单面板

### ISSUE THREAD

**Issue by ydl8686** [Molunerfinn/PicGo#478]
## 问题类型
Bug Report

## PicGo的相关信息
Mac，最新版本

## 问题重现
![image](https://user-images.githubusercontent.com/48279150/80384929-11225e80-88d8-11ea-89b3-966b17c3a271.png)
打不开菜单面板

## 功能请求

---

**Comment by Molunerfinn** [comment]
右键

**Comment by ydl8686** [comment]
就是右键了不行啊。。

**Comment by Molunerfinn** [comment]
触摸板 双指点按

**Comment by ydl8686** [comment]
control+点按和单纯的点按都弹出来同一个，对不起浪费你宝贵的时间了，但是我始终打不开菜单面板

**Comment by ydl8686** [comment]
对不起，，好了，非常抱歉打扰您的时间了

**Comment by xmge** [comment]
我去，终于找到方法了，感谢大佬

**Comment by xmge** [comment]
双值点按
