### ISSUE TITLE
Deepin下无法打开Picgo

### ISSUE THREAD

**Issue by cuijiahuawx** [Molunerfinn/PicGo#479]
## 问题类型
Bug Report

## PicGo的相关信息
版本:PicGo-2.2.2
所在平台:Deepin20Beta

## 问题重现
程序无法运行，终端运行显示如下：
![image](https://user-images.githubusercontent.com/36182049/80448429-dc9db980-894e-11ea-9c8c-e04a4917c631.png)
找不到这个/tmp/.mount_PicGo-Fd1omA/chrome-sandbox文件

## 功能请求
希望修复！

---

**Comment by Molunerfinn** [comment]
已经有人提过同样的问题也给了解决方法，请去历史issue里搜。
