### ISSUE TITLE
希望添加快捷键上传Notice反馈

### ISSUE THREAD

**Issue by jae-jae** [Molunerfinn/PicGo#48]
## 问题类型

Feature Request

## PicGo的相关信息

平台：Mac

## 功能请求
1. 希望在通过快捷键上传图片时，按下快捷键后可以给一下**开始上传**的Notice反馈提醒，按下上传快捷键后没任何反馈的话，就不清楚有没有触发到上传，有时很重复的按好几次快捷键

2. 如果可以的话希望在设置里面添加一个：上传前随机重命名 的选项，比喻在使用GitHub图床时，图片量多起来后很容易出现上传重名的文件覆盖了之前的文件，每次上传前手动重命名又比较麻烦。

最后感谢作者提供这么棒👍的应用，非常赞！
---

**Comment by Molunerfinn** [comment]
第一个可以在下个版本里实现。
第二个，你可以不选择上传前重命名啊，如果是剪贴板的截图会自动用时间戳命名的。如果是本地文件，需要批量上传的时候你最好在本地就重命名好。PicGo的重命名只是针对少量图片的。
