### ISSUE TITLE
picgo2.2.2 cant open in mac catalina 10.15.4 (19E287) 

### ISSUE THREAD

**Issue by lwj1994** [Molunerfinn/PicGo#480]
after install picgo ，it just show a mueu icon. i cant do anything
![image](https://user-images.githubusercontent.com/10978048/80695755-ef5bee00-8b08-11ea-84de-2b4b919e2897.png)

I can't open the main panel.  and can't  see picgo  in dock.

picgo: 2.2.2 , mac catalina 10.15.4 (19E287)

**Comment by Molunerfinn** [comment]
right-click or Two-finger touchpad

**Comment by Molunerfinn** [comment]
PicGo doesn't have a dock ICON.

**Comment by lwj1994** [comment]
I am stupid..... thank you！@Molunerfinn
