### ISSUE TITLE
Mac下七牛云无法上传

### ISSUE THREAD

**Issue by BLSM53** [Molunerfinn/PicGo#482]
## 问题类型

Bug Report

## PicGo的相关信息

版本：2.3.0-beta.0
平台：mac

## 问题重现

上传后报失败，但是没有相关报错信息
![image](https://user-images.githubusercontent.com/16435307/80852293-f9d9cd00-8c59-11ea-9eea-3e4d10647511.png)

---

**Comment by BLSM53** [comment]
尝试单独在七牛云上传图片后成功

**Comment by Molunerfinn** [comment]
检查一下七牛的配置吧。一般都是配置问题。看看有没有多个空格啥的。

**Comment by BLSM53** [comment]
![image](https://user-images.githubusercontent.com/16435307/80852715-41158d00-8c5d-11ea-9282-710a1262b354.png)
没有多空格哈~

**Comment by Molunerfinn** [comment]
> ![image](https://user-images.githubusercontent.com/16435307/80852715-41158d00-8c5d-11ea-9282-710a1262b354.png)
> 没有多空格哈~

发一下文本，我这里也测试一下。然后测试完了之后你改一下key，不然会被别人用的

**Comment by BLSM53** [comment]
```
"qiniu": {
      "accessKey": "Aat4Xo9TNTJW0vgRHda5UsEe763lUU6FOP5dVuP9",
      "area": "z2",
      "bucket": "picture-blsm",
      "options": "",
      "path": "img/",
      "secretKey": "KdUhV2VOG1Td1g2COo9xkSAu0zKwMCjVwv8BzvgM",
      "url": "http://file.yuqiusuo.top"
    }
```

谢谢哈

**Comment by Molunerfinn** [comment]
我这边没问题，已经上传了
http://file.yuqiusuo.top/picgo-logo测试.png
你看看

**Comment by Molunerfinn** [comment]
目测是你装了什么插件导致的错误...

**Comment by BLSM53** [comment]
好的，我再试试，这边没装插件哈，谢谢了~

**Comment by Molunerfinn** [comment]
> 好的，我再试试，这边没装插件哈，谢谢了~

嗯嗯OK，赶紧改一下key哈。目前这个版本的日志会有漏打的现象，下个beta版本会解决这个问题

**Comment by BLSM53** [comment]
谢谢，我这边把应用重新删除下载就可以了。
还有个问题，七牛云配置完CDN后的图片都会带上token，比如`http://file.yuqiusuo.top/1.jpeg?e=1588390748&token=DAKnXkuhWbmJ-k00oDsmCcNMKcuGF-Wv7DjKaX6B:xPbnD6wR86O1ghulzqCzdVMWA6o=`，但是咱们拿到的链接是`http://file.yuqiusuo.top/1.jpeg`，这就导致访问不到，请问这个有办法处理下嘛？

**Comment by BLSM53** [comment]
谢谢，我这边把应用卸载重新安装就好了
