### ISSUE TITLE
上传剪切板中的图片，报错

### ISSUE THREAD

**Issue by ChoKhoOu** [Molunerfinn/PicGo#484]
## 问题类型
Bug Report

## PicGo的相关信息
Windows

## 问题重现
我无论是按快捷键，还是点软件里面的剪切板图片上传按钮，都会报这个错
![image](https://user-images.githubusercontent.com/38033263/80866339-ac447b00-8cc0-11ea-90d4-0fa4d0dc64a8.png)

## 功能请求

---

**Comment by Molunerfinn** [comment]
已有的issue里很多了...未设置powershell的环境变量。
