### ISSUE TITLE
版本2.3.0-beta.0上传失败的问题

### ISSUE THREAD

**Issue by twbworld** [Molunerfinn/PicGo#485]
## 问题类型

Bug Report

## PicGo的相关信息
- 版本`2.3.0-beta.0`

- 平台`Windows`

## 问题重现
但本地文件夹为中文名称时.文件夹内的图片上传失败!
![image](https://user-images.githubusercontent.com/52546134/80908653-2ffb7780-8d54-11ea-9f27-f59b02b3231a.png)

## 功能请求

---

**Comment by Molunerfinn** [comment]
报错日志放上来，中文路径之前是做过处理的。

**Comment by Molunerfinn** [comment]
上传的时候不会关心你的文件夹里是否有中文，因为只会拿图片的fileName。

测试图片fileName有中文也是上传正常的。

![image](https://user-images.githubusercontent.com/12621342/80909637-705ef380-8d5c-11ea-89c2-b0129bb326bc.png)

如果是如下的问题，那是GitHub服务器的问题，与PicGo无关。
![image](https://user-images.githubusercontent.com/12621342/80909669-a1d7bf00-8d5c-11ea-8337-b00835086562.png)
