### ISSUE TITLE
在mac上，上传剪切板图片，上传错误

### ISSUE THREAD

**Issue by crownz-sec** [Molunerfinn/PicGo#486]
## Bug Report
上传剪切板图片，上传错误
## 版本和平台
2.3.0-beta.0，mac平台，但其实在上个版本，就有这个问题

## 问题重现
![image](https://user-images.githubusercontent.com/47936479/80951027-a4ecb100-8e29-11ea-88dd-7589c030c6b0.png)上传剪切板图片时，上传不成功，显示红色进度条。但有时候就会成功，间歇性地发生。
ps：这个图截了好多遍，都截不到那个进度条

**Comment by Molunerfinn** [comment]
不是剪贴板上传的问题，是github服务器的问题。可以看看之前的issue以及查看picgo的日志。

**Comment by Molunerfinn** [comment]
想要稳定上传，换gitee或者换付费云存储，比如阿里云、腾讯云等。
