### ISSUE TITLE
macos 截图上传至阿里云oss上 阿里云oss上也无法显示

### ISSUE THREAD

**Issue by zhanglijun1217** [Molunerfinn/PicGo#487]
## 问题类型
bug （看了之前那个issue 七牛不展示 要手动修改http头 感觉那个在七牛管理界面应该是可以显示的吧 我这个在阿里云oss上也是无法加载的 感觉是上传的时候的问题 ）

## PicGo的相关信息

macos  2.2.2版本的picgo
## 问题重现
截图之后 在点击等待上传的图片上传之后 阿里云oss上无法显示

![image](https://user-images.githubusercontent.com/36496779/80954407-e08a7980-8e2f-11ea-8794-608964cdcf5d.png)
![image](https://user-images.githubusercontent.com/36496779/80954426-ed0ed200-8e2f-11ea-886a-c7d8a03797fc.png)

其余两张显示都是本地拖拽上传 显示正确

**Comment by zhanglijun1217** [comment]
重度使用场景就是blog 截图上传 希望帮忙解答下

**Comment by Molunerfinn** [comment]
用2.3.0-beta.0试试呢，我这边无法复现

**Comment by zhanglijun1217** [comment]
> 用2.3.0-beta.0试试呢，我这边无法复现

好的我试下

**Comment by zhanglijun1217** [comment]
还是一样的~ 
我这里用的是企业微信带的截图功能。不知道有没有影响

**Comment by zhanglijun1217** [comment]
2020-05-05 00:05:22 [PicGo INFO] [PicGo Server] is listening at 36677
2020-05-05 00:05:59 [PicGo INFO] [PicGo Server] is listening at 36677
2020-05-05 00:09:18 [PicGo INFO] [PicGo Server] shutdown
2020-05-05 00:09:48 [PicGo INFO] [PicGo Server] is listening at 36677
2020-05-05 00:11:01 [PicGo INFO] Before transform
2020-05-05 00:11:01 [PicGo INFO] Before upload
2020-05-05 00:11:02 [PicGo SUCCESS] 
https://zlj1217-blog-image.oss-cn-hongkong.aliyuncs.com/mac_picgo/20200505001100.png


看日志也没啥问题 有详细调用接口的日志吗 想看看请求的头之类的有没有问题  比较困扰的是到阿里云对象存储上都展示不出来

**Comment by Molunerfinn** [comment]
![image](https://user-images.githubusercontent.com/12621342/81029117-6b15bc00-8eb6-11ea-94ab-b054cef4ffdd.png)
经测试，用企业微信截图+上传阿里云OSS没问题。

可以尝试一下按照这个issue的来修改你的屏幕描述文件，再重启picgo试试。https://github.com/Molunerfinn/PicGo/issues/199

PicGo阿里云用户很多，如果这个功能picgo无法使用的话issue区应该炸了。感觉跟你的电脑有点关系

**Comment by zhanglijun1217** [comment]
嗯 我再看看 不过昨天也在typora里装了picgo的插件 然后上传是ok的 进而重度使用变成了typora复制图片使用～ thx




| |
张利君
|
|
邮箱：17768115112@163.com
|

签名由 网易邮箱大师 定制

在2020年05月05日 09:56，PiEgg 写道：

Closed #487.
