### ISSUE TITLE
上传至GitHub图床图片链接出错

### ISSUE THREAD

**Issue by yuanyuannetwork** [Molunerfinn/PicGo#489]
**声明：我已经仔细看过 [文档](https://picgo.github.io/PicGo-Doc/)、[FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)、和搜索过已经关闭的 [issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed) 后依然没有找到答案，所以才发了一个新的 issue。**

## 问题类型
 Bug Report 

## PicGo 的相关信息

PicGo 版本:2.3.0-beta.0
平台：win10

## 问题重现

github图床上传后的图片链接有问题，因为github私人仓库图片token每次请求都会变，如果用第一次上传后获得的链接请求则无法获取图片。
解决方法：
错误地址：eg: https://raw.githubusercontent.com/xx/xx/master/Postman.png?token=AJQVRPTEGBRLBX45BDOVFGS6WFE3I
正确地址：eg: https://github.com/xx/仓库名/blob/分支名/Postman.png?raw=true

## 功能请求

---

**Comment by Molunerfinn** [comment]
之前的issue里已经说过了，不对GitHub私有仓库做支持。图床是用来公开的，不能用私有仓库。

你这个问题只要自定义一下域名就行了- -。
