### ISSUE TITLE
能否增加图片压缩功能

### ISSUE THREAD

**Issue by sandyplus** [Molunerfinn/PicGo#49]
## 问题类型

Feature Request
## PicGo的相关信息

Mac
## 功能请求

能否添加一个自动压缩图片的功能？特别是在剪切板的图片

---

**Comment by huahuayu** [comment]
@Molunerfinn 希望可以上传前压缩图片，腾讯智图压缩率很高同时可以保证质量，我下了腾讯智图mac客户端，但是自己压缩就要多几个步骤，略麻烦

**Comment by Molunerfinn** [comment]
@sandyplus 本体只关注上传。压缩图片可以写一个PicGo的插件去实现。
