### ISSUE TITLE
macos cannot verify that this app

### ISSUE THREAD

**Issue by JunQu** [Molunerfinn/PicGo#491]
**声明：我已经仔细看过 [文档](https://picgo.github.io/PicGo-Doc/)、[FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)、和搜索过已经关闭的 [issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed) 后依然没有找到答案，所以才发了一个新的 issue。**

## 问题类型

Bug Report 

## PicGo 的相关信息

平台：Mac Catalina brew
version: 目前 brew 可以安装的最新版本，由于后面弹窗选择 beta 所以没有看到版本。

## 问题重现
使用使用手册中 mac 平台的安装命令` brew cask install picgo` ，然后在 launchpad 中双击打开安装的 picgo， 出现如下情况：
<img width="403" alt="Screen Shot 2020-05-10 at 8 35 13 PM" src="https://user-images.githubusercontent.com/39846309/81499393-dc61ce80-92fd-11ea-96f6-bacb0be6d7a2.png">

没有 open 选项。
现在解决方式，查找网上的技巧，然后打开 Applications 文件夹，右键点击 open 然后出现下图：
 
<img width="433" alt="Screen Shot 2020-05-10 at 8 38 32 PM" src="https://user-images.githubusercontent.com/39846309/81499429-41b5bf80-92fe-11ea-8a68-a356be2c272f.png">

出现 open ，才能打开软件。

## 功能请求
希望 ` brew cask install picgo`   能够正常安装与打开使用，或者提示后来可能使用这个命令的安装的人。而且出现mac提示这个让人感觉怪怪的，怕安全问题，当然我是百分之百相信作者，为了重现我安装了几次。

最后，我去下载的 [2.3.0-beta.0](https://github.com/Molunerfinn/PicGo/releases/tag/v2.3.0-beta.0) 没有任何问题提示，双击安装过程十分流畅。

---

**Comment by Molunerfinn** [comment]
brew cask install picgo这个源不是我在维护，是社区爱好者维护的。

另外之所以会出现这个是因为我并没有苹果开发者身份，无法对包进行签名。为何我没有苹果开发者身份，因为一年99$的费用太贵了，学生党穷...将就着用吧 🤣
