### ISSUE TITLE
win10 安装失败

### ISSUE THREAD

**Issue by hnmsky** [Molunerfinn/PicGo#492]
**声明：我已经仔细看过 [文档](https://picgo.github.io/PicGo-Doc/)、[FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)、和搜索过已经关闭的 [issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed) 后依然没有找到答案，所以才发了一个新的 issue。**

## 问题类型

win10 安装失败
## PicGo 的相关信息

2.2.2 和 2.3.0 
## 问题重现

![image](https://user-images.githubusercontent.com/573801/81501774-abd56100-930c-11ea-9d84-a6c30b0e9104.png)
防火墙已经关闭。
## 功能请求

---

**Comment by Molunerfinn** [comment]
https://segmentfault.com/q/1010000019181439?sort=created

**Comment by QGrain** [comment]
我也遇到了同样的问题，请问如何彻底卸载呢？我使用了Uninstaller但是似乎并没有彻底卸载
