### ISSUE TITLE
自定义链接格式设置有问题

### ISSUE THREAD

**Issue by xiechuanyu** [Molunerfinn/PicGo#494]
**声明：我已经仔细看过 [文档](https://picgo.github.io/PicGo-Doc/)、[FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)、和搜索过已经关闭的 [issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed) 后依然没有找到答案，所以才发了一个新的 issue。**

## 问题类型

我不清楚是 Bug Report 还是 Feature Request
## PicGo 的相关信息

PicGo：2.2.2.
OS：Windows
## 问题重现
设置自定义链接格式为` <div align="center"><img src="https://$url"/></div><br>`，
实际只有`<img src="image.zhangxiann.com/segmentation.png"/>`
缺少`<div align="center">` 和 `https://`前缀

![image](https://user-images.githubusercontent.com/12131262/81894734-1aebd780-95e3-11ea-8ef4-5486c5cc69b3.png)

## 功能请求

---

**Comment by Molunerfinn** [comment]
你选的是custom还是HTML呢

**Comment by xiechuanyu** [comment]
> 你选的是custom还是HTML呢

谢谢，原来还要选的
