### ISSUE TITLE
新版本上传文件的时候不能自动复制路径到粘贴板

### ISSUE THREAD

**Issue by snkkka** [Molunerfinn/PicGo#496]
新版本上传文件的时候不能自动复制路径到粘贴板，可能是我没找到，请作者回答一下在哪里设置！！我觉得这个功能特别方便！

**Comment by Molunerfinn** [comment]
请你按issue模板发帖。

![image](https://user-images.githubusercontent.com/12621342/81928568-0a098900-9618-11ea-844f-aeea5783e59d.png)
Beta.0的bug，把这个选项关了再开就行。
