### ISSUE TITLE
新版本自动复制URL按钮是开的但是无效

### ISSUE THREAD

**Issue by snkkka** [Molunerfinn/PicGo#497]
**声明：我已经仔细看过 [文档](https://picgo.github.io/PicGo-Doc/)、[FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)、和搜索过已经关闭的 [issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed) 后依然没有找到答案，所以才发了一个新的 issue。**

## 问题类型
BUG

## 问题重现
新版本默认上传文件不会复制URL 即使按钮是默认开启的，这个按钮需要关了再开才有效果！

## 功能请求

---

**Comment by Molunerfinn** [comment]
已知bug，已经修复，下个版本会更新- -
