### ISSUE TITLE
建议修改默认的上传图片快捷键 - 和vscode最重要的快捷键冲突

### ISSUE THREAD

**Issue by huahuayu** [Molunerfinn/PicGo#499]
## 问题描述
picgo在mac下上传图片的默认快捷键为`command + shift + p`跟[vscode最重要的快捷键Command Palette](https://code.visualstudio.com/docs/getstarted/userinterface#_command-palette)冲突，打开picgo之后，vscode的这个快捷键就会失效  

![image](https://user-images.githubusercontent.com/1725060/82113033-41e20f00-9785-11ea-89d3-a65362fb80a2.png)

考虑到vscode在技术人员中的使用占比，我觉得这个影响还是挺大，能不能换一个默认的快捷键

虽然说可以用户自定义，但是也最好不要默认这个热键让用户二改一吧

**Comment by Molunerfinn** [comment]
采用别的就会跟别的软件冲突，又会有那批软件的用户来发issue，治标不治本。不想冲突就自己换一个
