### ISSUE TITLE
Github 能否支持自定义域名

### ISSUE THREAD

**Issue by zhaoyibo** [Molunerfinn/PicGo#50]
## 问题类型
Feature Request

## PicGo的相关信息
Mac

### Github 自定义域名
希望 Github 可以支持自定义域名（github pages）。

比如我刚上传了一张图片，地址默认为 https://raw.githubusercontent.com/zhaoyibo/resource/gh-pages/img/google_doodle.png
即
repo: resource
branch: gh-pages
path: img

我为这个仓库设置了 Custom domain: src.windmt.com
所以我也可以通过 https://src.windmt.com/img/google_doodle.png 来访问。希望能支持自定义域名，即`https://src.windmt.com`这一部分。

### 自动删除
如果我手动在仓库中删除了一张图片，在 PicGo 的相册界面不会自动删除。是否可以通过返回的 404 状态码来做到自动删除呢？怕误删除的话加个批量删除前的确认提醒？

---

**Comment by Molunerfinn** [comment]
GitHub的自定义域名可以做，预计下个版本可以加上。
自动删除不在PicGo的管辖范围内。PicGo的图床管理只针对本地数据库。
不过可以考虑给PicGo加上批量删除的功能。
