### ISSUE TITLE
打不开，老是显示这个错误。

### ISSUE THREAD

**Issue by kunpeng9** [Molunerfinn/PicGo#501]
**声明：我已经仔细看过 [文档](https://picgo.github.io/PicGo-Doc/)、[FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)、和搜索过已经关闭的 [issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed) 后依然没有找到答案，所以才发了一个新的 issue。**

## 问题类型

bug report
## PicGo 的相关信息
最新的beta2.3b版本的。之前就打不开所以我下的最新版结果还是打不开。

![image](https://user-images.githubusercontent.com/44609485/82203787-587b9800-9936-11ea-80a4-fbff082598fb.png)
![image](https://user-images.githubusercontent.com/44609485/82203860-7b0db100-9936-11ea-99b7-e2a799087f54.png)
是那个插件的问题嘛？可是那个软件打不开，怎么卸载那个问题插件。
## 功能请求

---

**Comment by Molunerfinn** [comment]
这个是你的picgo的配置文件出错了。可能是乱码了。解决办法就是删掉这个配置文件：
![image](https://user-images.githubusercontent.com/12621342/82204508-9927e100-9937-11ea-8514-5140c07b4c66.png)
然后把picgo完全退出再重启即可。

**Comment by kunpeng9** [comment]
是不是因为异常断电导致的错误呢？那个配置丢失；
 @Molunerfinn    ![image](https://user-images.githubusercontent.com/44609485/97519626-7add0b80-19d4-11eb-92e2-c0ced2c22c18.png)zhi之前看到这个修复就想到picgo，搞忘记说这个了；配置已备份了；之前没想好那个配置文件放哪里，以前似乎好像备份过，但是过一阵搞忘记那个文件是啥然后又删除了，就一个data.json，要不之后加个名字，picgo data  json【备份文件又找不到了，吐血】
![image](https://user-images.githubusercontent.com/44609485/97520139-7d8c3080-19d5-11eb-9581-32b005353c44.png)
chuxi出现错误
-PicGo.exe.log-
1,"fusion","GAC",0
3,"C:\Windows\assembly\NativeImages_v2.0.50727_64\System\497e78fa941a9af2d9571237b6976e66\System.ni.dll",0
3,"C:\Windows\assembly\NativeImages_v2.0.50727_64\System.Configuration\67074fa6638ee328c2bc8c12c94007f6\System.Configuration.ni.dll",0
3,"C:\Windows\assembly\NativeImages_v2.0.50727_64\System.Xml\826897f3f300a59eddd069c7e4c3a09a\System.Xml.ni.dll",0
3,"C:\Windows\assembly\NativeImages_v2.0.50727_64\System.Drawing\c159e1748da5a7d4a1122c24b0be2427\System.Drawing.ni.dll",0
3,"C:\Windows\assembly\NativeImages_v2.0.50727_64\System.Windows.Forms\ca37c77b11effb250edc57e5c3146dbb\System.Windows.Forms.ni.dll",0
