### ISSUE TITLE
大图片不显示

### ISSUE THREAD

**Issue by loadingfd** [Molunerfinn/PicGo#503]
**声明：我已经仔细看过 [文档](https://picgo.github.io/PicGo-Doc/)、[FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)、和搜索过已经关闭的 [issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed) 后依然没有找到答案，所以才发了一个新的 issue。**

## 问题重现

图片过大没有缩略图，点开后是叉
![](https://gitee.com/loadingfd/picture/raw/master/img/20200520144323.png)
![](https://gitee.com/loadingfd/picture/raw/master/img/20200520144410.png)
windows 2.2.2
## 功能请求

---

**Comment by loadingfd** [comment]
什么问题？

**Comment by Molunerfinn** [comment]
看FAQ和之前的issue啊，一堆同样的问题
