### ISSUE TITLE
剪贴板上传有问题

### ISSUE THREAD

**Issue by kurtyang486** [Molunerfinn/PicGo#505]
![image](https://user-images.githubusercontent.com/39580219/82456707-2b221c00-9ae7-11ea-99b5-da9586525aa4.png)

**声明：我已经仔细看过 [文档](https://picgo.github.io/PicGo-Doc/)、[FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)、和搜索过已经关闭的 [issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed) 后依然没有找到答案，所以才发了一个新的 issue。**

## 功能请求

---

**Comment by Molunerfinn** [comment]
请你去搜以前的issue谢谢
