### ISSUE TITLE
Typora 无法正常上传插入的本地图片

### ISSUE THREAD

**Issue by cooper1x** [Molunerfinn/PicGo#507]
## 问题类型
Bug Report 

## PicGo 的相关信息
系统：windows 10 2004 x64
picgo：2.3.0-beta

## 问题重现
![image](https://user-images.githubusercontent.com/9080789/82660709-70685a00-9c5d-11ea-918b-e04e250e77e1.png)
我在typora验证中是可以的，但实际上传就不行了。

一直提示这个报错：
![image](https://user-images.githubusercontent.com/9080789/82660930-a60d4300-9c5d-11ea-8c82-dd7f86ae68fa.png)

服务测试是通的，但软件里面还是不能用。这个就很迷了。

**Comment by Molunerfinn** [comment]
找typora去啊...
