### ISSUE TITLE
阿里云OSS上传的图片在PicGo里无法正常显示

### ISSUE THREAD

**Issue by yao-jz** [Molunerfinn/PicGo#508]
**声明：我已经仔细看过 [文档](https://picgo.github.io/PicGo-Doc/)、[FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)、和搜索过已经关闭的 [issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed) 后依然没有找到答案，所以才发了一个新的 issue。**

## 问题类型
Bug Report

## PicGo 的相关信息
Mac 10.14.6
PicGo 2.3.0-beta.0

## 问题重现
背景：
1. 没有使用代理
2. 设置了自定义域名，且在域名前加了https://
3. 图片的URL前有https://
4. 阿里云OSS是公有可读权限的bucket

上传图片，能够成功上传到阿里云OSS里，但是在PicGo客户端内图片无法显示

![iShot2020-05-2315 20 45](https://user-images.githubusercontent.com/53652885/82724746-f4c4e680-9d0a-11ea-80b4-2ed136b6c868.png)
![iShot2020-05-2315 35 37](https://user-images.githubusercontent.com/53652885/82724766-14f4a580-9d0b-11ea-856e-dfd19d0a274c.png)
![iShot2020-05-2315 35 57](https://user-images.githubusercontent.com/53652885/82724771-1b831d00-9d0b-11ea-9265-aa8c1ca91e75.png)

---
谢谢！

**Comment by Molunerfinn** [comment]
那你倒是给一个链接看看啊。。。

**Comment by Molunerfinn** [comment]
把相册里无法显示的链接给一个

**Comment by yao-jz** [comment]
问题已解决

问题出现原因：阿里云OSS开启了请求者付费选项
解决途径：关闭请求者付费选项
