### ISSUE TITLE
不同电脑的相册同步

### ISSUE THREAD

**Issue by Laughtalk** [Molunerfinn/PicGo#51]
## 不同电脑的相册同步

Feature Request

## PicGo的相关信息

1.5.0 on Windows7 and Windows10

## 功能请求

我在办公室和家中的电脑都安装了picgo1.5.0，都是用使用腾讯云COS图床，都设置为同一个账户，都设置为同一个bucket。
经过我的尝试，我发现在办公室电脑上传的图片，无法在家中电脑上看到。
我认为，如果图床设置完全相同，那么应该加一个自动刷新同步的选项，这样的话，当我从办公室回到家继续工作的时候，就可以知道哪些图片已将上传，哪些还没有。
---

**Comment by Molunerfinn** [comment]
PicGo使用的是本地存储而非云端存储。而且我无法知道你哪些图片是通过PicGo上传，哪些不是。
能做到的是配置文件和相册的本地记录可以支持导出。

**Comment by L-Evan** [comment]
相册怎么导出
