### ISSUE TITLE
TypeError: Cannot read property 'body' of undefined

### ISSUE THREAD

**Issue by Jesse-so-cool** [Molunerfinn/PicGo#511]
![image](https://user-images.githubusercontent.com/31425351/83119224-068afd00-a102-11ea-8da1-96e4e3bd8b7e.png)

**Comment by Molunerfinn** [comment]
配置错了

**Comment by Jesse-so-cool** [comment]
![image](https://user-images.githubusercontent.com/31425351/83157231-f0972f80-a135-11ea-8605-30f83f2b76e0.png)
hello，请问这个配置有什么问题

**Comment by Jesse-so-cool** [comment]
![image](https://user-images.githubusercontent.com/31425351/83157817-9c407f80-a136-11ea-8668-7648abd9b671.png)

**Comment by Molunerfinn** [comment]
area错了，看看文档

**Comment by Jesse-so-cool** [comment]
搞定 谢谢bro~
