### ISSUE TITLE
请教typora的自动上传功能，PicGo-2.3.0-beta.0.AppImage路径怎样设置？

### ISSUE THREAD

**Issue by ajmz** [Molunerfinn/PicGo#513]
**声明：我已经仔细看过 [文档](https://picgo.github.io/PicGo-Doc/)、[FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)、和搜索过已经关闭的 [issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed) 后依然没有找到答案，所以才发了一个新的 issue。**

## 问题类型

Feature Request

## PicGo 的相关信息

PicGo-2.3.0-beta.0.AppImage，Linux

## 功能请求

- 请教typora的自动上传功能，PicGo-2.3.0-beta.0.AppImage路径怎样设置？
- Manjaro linux 20系统，直接下载AppImage运行方式安装的。
- 下图是typora官网的图片，Windows系统的设置路径。
- [https://support.typora.io/Upload-Image/#picgo-core-command-line-opensource](url)
- ![Upload Images](https://support.typora.io/media/image-upload/picgo.PNG)

---

**Comment by Molunerfinn** [comment]
应该就是appimage所在的路径。这个你应该问问Typora。

**Comment by ajmz** [comment]
typora选择目录后，类型只能是可执行文件，不能识别appimage。
picgo的运行，会解压可执行文件到其他固定的目录吗？

**Comment by Molunerfinn** [comment]
那你就添加一下可执行权限呗...

**Comment by ajmz** [comment]
AppImage只有添加了可执行权限，才能运行的。
typora不能识别AppImage，看来确实需要typora的支持，谢谢。

**Comment by Tuladingpro** [comment]
> AppImage只有添加了可执行权限，才能运行的。
> typora不能识别AppImage，看来确实需要typora的支持，谢谢。
> 已经给[hi@typora.io](mailto:hi@typora.io)发了邮件，静等回复。

我查看了下appimage的权限是755的可执行权限，我尝试在路径处直接输入/opt/appimages/picgo.AppImage  然后只有在第一次打开的时候是可以上传的，如果打开过一次，再通过typora上传的时候就会失败，但是picgo本身的拖拽上传和剪贴板上传是正常的，所以应该还是typora调用有些问题，windows版本是正常的

**Comment by ajmz** [comment]
> > AppImage只有添加了可执行权限，才能运行的。
> > typora不能识别AppImage，看来确实需要typora的支持，谢谢。
> > 已经给[hi@typora.io](mailto:hi@typora.io)发了邮件，静等回复。
> 
> 我查看了下appimage的权限是755的可执行权限，我尝试在路径处直接输入/opt/appimages/picgo.AppImage 然后只有在第一次打开的时候是可以上传的，如果打开过一次，再通过typora上传的时候就会失败，但是picgo本身的拖拽上传和剪贴板上传是正常的，所以应该还是typora调用有些问题，windows版本是正常的

谢谢测试。
typora给我回信：
We will check this. For hot fix, you can run PicGo manually before you want to upload or auto-upload images.
他们的beta（mac OS）更新频繁，Windows和Linux许久没升级了。

**Comment by ajmz** [comment]
补充：
直接安装了Manjaro Linux AUR store里面的picgo-appimage-2.2.2，并且在typora里输入appimage文件目录地址，可以拖拽图片到typora，然后自动上传到图床了。
但是typora最上面会出现错误提示：上传图片失败。。。是一个目录。
忽略错误提示就好，不影响使用，静等typora更新。

**Comment by ajmz** [comment]
> > AppImage只有添加了可执行权限，才能运行的。
> > typora不能识别AppImage，看来确实需要typora的支持，谢谢。
> > 已经给[hi@typora.io](mailto:hi@typora.io)发了邮件，静等回复。
> 
> 我查看了下appimage的权限是755的可执行权限，我尝试在路径处直接输入/opt/appimages/picgo.AppImage 然后只有在第一次打开的时候是可以上传的，如果打开过一次，再通过typora上传的时候就会失败，但是picgo本身的拖拽上传和剪贴板上传是正常的，所以应该还是typora调用有些问题，windows版本是正常的

我又测试了直接安装Manjaro Linux AUR store里面的picgo-appimage-2.2.2，在typora里输入appimage文件地址，可以拖拽图片到typora，然后自动上传到图床了。
虽然很快有弹出窗口显示上传成功，图床里面也看到了文件，但是在typora正文里，会显示“Uploading”状态很久。

**Comment by Desdemo** [comment]
ubuntu20 用snap安装的typora也是识别不出来 appimage可执行文件。我看网上说直接安装 PicGo-core 这个靠谱吗？

**Comment by jeffrey4l** [comment]
> > > AppImage只有添加了可执行权限，才能运行的。
> > > typora不能识别AppImage，看来确实需要typora的支持，谢谢。
> > > 已经给[hi@typora.io](mailto:hi@typora.io)发了邮件，静等回复。
> > 
> > 
> > 我查看了下appimage的权限是755的可执行权限，我尝试在路径处直接输入/opt/appimages/picgo.AppImage 然后只有在第一次打开的时候是可以上传的，如果打开过一次，再通过typora上传的时候就会失败，但是picgo本身的拖拽上传和剪贴板上传是正常的，所以应该还是typora调用有些问题，windows版本是正常的
> 
> 我又测试了直接安装Manjaro Linux AUR store里面的picgo-appimage-2.2.2，在typora里输入appimage文件地址，可以拖拽图片到typora，然后自动上传到图床了。
> 虽然很快有弹出窗口显示上传成功，图床里面也看到了文件，但是在typora正文里，会显示“Uploading”状态很久。

Archlinux + Typora 0.9.98-1  + picgo-appimage-beta 2.3.0-4 也出现 一样的情况，感觉是 typora 和 picgo 之间的接口调用有啥问题。

**Comment by Brannua** [comment]
我的可以，虽然不能识别 755 权限的 AppImage 但是确实如楼上所说可以手动填写路径
os：x86_64 Linux 5.14.6-arch1-1
typora：0.11.7（beta）
picGo：v_2.3.0，.AppImage file + 755权限
图床：gitee public repo
