### ISSUE TITLE
希望picgo能支持阿里云的同步删除，我的理由

### ISSUE THREAD

**Issue by wushu037** [Molunerfinn/PicGo#515]
作者你好，这个问题也看到有人问过了，也看到了你的回答。但是还是希望可以加上这一点，原因如下：
我在用typora快速编写我的笔记的时候，会直接黏贴一些图片并且设置的自动上传，但是很多时候我会发现图片需要更换，不是很合适，此时之前的我希望能够删除掉。
看到了您的这个回答，但是对于危险我觉得可以用密码或者验证来防止。
众所周知picgo的使用用户正在快速增长，希望picgo的功能更加强大！
![image](https://user-images.githubusercontent.com/61787040/83712511-8c55fd80-a658-11ea-996c-880a85675799.png)

**Comment by Molunerfinn** [comment]
不想再解释了，插件可以实现的东西，本体不会做的。
