### ISSUE TITLE
建议：增加上传重命名规则，例如文件名+时间

### ISSUE THREAD

**Issue by wushu037** [Molunerfinn/PicGo#516]
## 问题类型
Feature Request

## PicGo 的相关信息
windows 2.2.2

## 功能请求
作者你好，希望能改进重命名功能：
阿里云oss同名文件会覆盖掉，但是自定义名字的图片更能让人一眼就看懂。
我认为可以用自动给文件名加上时间后缀的方式实现
比如：我对文件上传前重命名为mybanner，接着会自动添加我设置好的后缀，例如为当天的时间`$year$month$day`，那么最后的文件名就是mybanner20200604.png

感谢作者！

**Comment by Molunerfinn** [comment]
已有插件，super-prefix

**Comment by wushu037** [comment]
这个插件并不完美，，必须关闭上传重命名才可以使用它，意味着我必须先修改文件名，这很不方便。
并且它只提供了前缀，没有后缀，issues中有很多人提到后缀的事，但是没有回复。


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"PiEgg"<notifications@github.com&gt;;
发送时间:&nbsp;2020年6月4日(星期四) 下午4:02
收件人:&nbsp;"Molunerfinn/PicGo"<PicGo@noreply.github.com&gt;;
抄送:&nbsp;"无数"<wushu037@foxmail.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [Molunerfinn/PicGo] 建议：增加上传重命名规则，例如文件名+时间 (#516)





 
已有插件，super-prefix

**Comment by Molunerfinn** [comment]
这个需求是插件就能实现的，因此本体就不会再扩充了。
如果那个插件不更新，之后我可以考虑官方这边出个插件用来做这些命名相关的。

**Comment by Molunerfinn** [comment]
可以往这里发个需求，也许有其他开发者看到了就会帮忙开发：https://github.com/Molunerfinn/PicGo/issues/222

**Comment by wushu037** [comment]
OK，
感谢作者


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"PiEgg"<notifications@github.com&gt;;
发送时间:&nbsp;2020年6月4日(星期四) 下午5:14
收件人:&nbsp;"Molunerfinn/PicGo"<PicGo@noreply.github.com&gt;;
抄送:&nbsp;"无数"<wushu037@foxmail.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [Molunerfinn/PicGo] 建议：增加上传重命名规则，例如文件名+时间 (#516)





 
可以往这里发个需求，也许有其他开发者看到了就会帮忙开发：#222

**Comment by liuwave** [comment]
我也有这个需求，刚好弄了个：https://github.com/liuwave/picgo-plugin-rename-file
@wushu037 
支持日期、随机字符串、文件MD5、原文件名、原文件目录结构等规则。

**Comment by bruceeewong** [comment]
> 我也有这个需求，刚好弄了个：https://github.com/liuwave/picgo-plugin-rename-file @wushu037 支持日期、随机字符串、文件MD5、原文件名、原文件目录结构等规则。

nice done bro. 很漂亮地解决名字重命名的需求🍻

**Comment by Aewait** [comment]
> 我也有这个需求，刚好弄了个：https://github.com/liuwave/picgo-plugin-rename-file @wushu037 支持日期、随机字符串、文件MD5、原文件名、原文件目录结构等规则。

太感谢了，正好需要这个。避免重复文件多次储存
