### ISSUE TITLE
gif可以上传吗？

### ISSUE THREAD

**Issue by Victorfy** [Molunerfinn/PicGo#517]
## 问题类型

Feature Request

## PicGo 的相关信息

2.2.2
Mac

## 功能请求

请问可以加入上传gif的功能吗？

---

**Comment by Victorfy** [comment]
刚才又试了一下可以上传，可能组一开始网络的原因，打扰

**Comment by Aren-py** [comment]
我试了上传好几次gif，都失败了。最新版本的

**Comment by Molunerfinn** [comment]
> 我试了上传好几次gif，都失败了。最新版本的

看看你的失败日志吧。跟gif没啥关系，一般都是网络或者配置问题
