### ISSUE TITLE
开机后自动【隐藏窗口】

### ISSUE THREAD

**Issue by PhoenixXC** [Molunerfinn/PicGo#518]
**声明：我已经仔细看过 [文档](https://picgo.github.io/PicGo-Doc/)、[FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)、和搜索过已经关闭的 [issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed) 后依然没有找到答案，所以才发了一个新的 issue。**

## 问题类型

Feature Request

### PicGO 版本
2.2.2

### 系统
OS: Manjaro 19.0.2 Kyria
Kernel: x86_64 Linux 5.4.31-1-MANJARO
WM: Deepin WM

## 功能请求

Linux 设置开机启动，每次开机后桌面中央会出现 PicGo 的小图标，系统托盘也会有 PicGo 的图标，但使用快捷键上传就可以完成大多数的任务，系统托盘的图标也是不必要的，每次手动选择隐藏窗口较为繁琐。
能否添加一个选项：开机后自动【隐藏窗口】，以及设置一个唤起详细窗口的快捷键。

**Comment by Molunerfinn** [comment]
唤起窗口的快捷键会考虑。

隐藏窗口会有其他的问题，而且我没有Linux机器无法对每个发行版都做一遍测试。因此只会暂时保持现状。

**Comment by free-150** [comment]
我也发现这个问题了，每次开机Linux壁纸中间都会有一个图标在那。
设置manjaro

**Comment by Molunerfinn** [comment]
> 我也发现这个问题了，每次开机Linux壁纸中间都会有一个图标在那。 设置manjaro

那个是mini窗口。
https://picgo.github.io/PicGo-Doc/zh/guide/getting-started.html#mini%E7%AA%97%E5%8F%A3%E4%B8%8A%E4%BC%A0
