### ISSUE TITLE
关于不希望的错误。

### ISSUE THREAD

**Issue by kunpeng9** [Molunerfinn/PicGo#519]
**声明：我已经仔细看过 [文档](https://picgo.github.io/PicGo-Doc/)、[FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)、和搜索过已经关闭的 [issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed) 后依然没有找到答案，所以才发了一个新的 issue。**

## 问题类型
 Bug Report

## PicGo 的相关信息
是最新的版本的。2.3 beta的

## 问题重现

打开软件的时候 老是出现那个错误弹窗导致用不了，现在没事了，C:\Users\YEDONG\AppData\Roaming\picgo\data.json。只要把这个地址的文件删除掉，就可以启动文件，不过之前图床填的信息都没有了。
## 功能请求

前阵子更新了这个动作。[阿里云OSS(图床) - 已分享的动作 - Quicker](https://getquicker.net/Sharedaction?code=c4896807-9b84-46e9-7d97-08d808171f98 )感兴趣的可以去看看。
---

**Comment by Molunerfinn** [comment]
配置文件出错会出现这个问题，picgo无法解决
