### ISSUE TITLE
上传前自动进行 hash 重命名

### ISSUE THREAD

**Issue by DeepenLau** [Molunerfinn/PicGo#52]
## 问题类型

Feature Request

## PicGo的相关信息

PicGO 1.5.0
Mac 10.13.3
## 问题重现
无

## 功能请求

现在有一个上传前的重命名，不过要手动重命名
希望能有个上传前自动进行 hash 重命名的选项
---

**Comment by Molunerfinn** [comment]
可以考虑加一个自动`用时间戳命名`的选项。
