### ISSUE TITLE
报上传失败，在相册里面看不到相应的图片，但其实已经上传成功

### ISSUE THREAD

**Issue by jmwyf** [Molunerfinn/PicGo#521]
## 问题类型

bug report

## PicGo 的相关信息

2.2.2
Mac

## 问题重现

报上传失败，在相册里面看不到相应的图片，但其实已经上传成功，自己改链接后可用

---

**Comment by Molunerfinn** [comment]
2.3.0-beta.0 已经修了这个问题，更新一下。
