### ISSUE TITLE
【Bug Report】转存语雀非常规后缀图片的问题

### ISSUE THREAD

**Issue by cooper1x** [Molunerfinn/PicGo#525]
## 问题类型

Bug Report

## PicGo 的相关信息
win10 2004 x64
picgo 2.3.0-beta.0
已开启时间戳命名

## 问题重现
typora粘贴连接，例如：
```
![image.png](https://cdn.nlark.com/yuque/0/2020/png/236538/1592744003972-b6ae9fee-fd4e-4462-b3f7-b819a2bed32f.png#align=left&display=inline&height=325&margin=%5Bobject%20Object%5D&name=image.png&originHeight=325&originWidth=384&size=184488&status=done&style=none&width=384)
```
上传成功后，结果是:
```
https://{图床域名}/{时间戳}.png&originHeight=325&originWidth=384&size=184488&status=done&style=none&width=384
```

## 预期
最后以xxx.png结尾，而没有其他多余的参数。

## 结果
png后面会保留原有的一大串参数

希望可以修复这个问题，这样会让图片转存变得更加方便。

**Comment by H-olxx** [comment]
补充：像类似```https://img-blog.csdn.net/20170801164739367?watermark/2/text/aHR0cDovL2Jsb2cuY3Nkbi5uZXQvTWFyeTE5OTIwNDEw/font/5a6L5L2T/fontsize/400/fill/I0JBQkFCMA==/dissolve/70/gravity/Center```这种没有明确图片类型的图片链接，上传之后在某些图床会识别后缀名失败。

可以在链接上传的步骤加入缓存机制，'识别链接'->'下载图片'->'识别图片格式'->'重命名'->'上传'->'清除下载缓存'

**Comment by H-olxx** [comment]
补充：像上述```https://img-blog.csdn.net/20170801164739367?watermark/2/text/aHR0cDovL2Jsb2cuY3Nkbi5uZXQvTWFyeTE5OTIwNDEw/font/5a6L5L2T/fontsize/400/fill/I0JBQkFCMA==/dissolve/70/gravity/Center```这种图片链接，```"?"```后面的参数都是水印的描述，可以用正则截取```?```前的链接去掉水印

**Comment by Molunerfinn** [comment]
之后看看是什么原因导致的

**Comment by Molunerfinn** [comment]
2.3.0.beta-1会修复这个问题
