### ISSUE TITLE
成功上传GitHub图床的图片地址无法直接访问

### ISSUE THREAD

**Issue by whitoad** [Molunerfinn/PicGo#526]
**声明：我已经仔细看过 [文档](https://picgo.github.io/PicGo-Doc/)、[FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)、和搜索过已经关闭的 [issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed) 后依然没有找到答案，所以才发了一个新的 issue。**

## 问题类型

Bug Report

## PicGo 的相关信息

PicGo 的版本：2.3.0-beta.0 所在平台： Windows10

## 问题重现

图片上传成功了，但是直接访问显示404：

![微信图片_20200623093936](https://user-images.githubusercontent.com/22836144/85351262-e2221500-b535-11ea-876e-f0730e44d868.png)

PicGo 的相关日志：

2020-06-23 09:32:48 [PicGo INFO] Transforming...
2020-06-23 09:32:48 [PicGo INFO] Before transform
2020-06-23 09:32:48 [PicGo INFO] Before upload
2020-06-23 09:32:48 [PicGo INFO] Uploading...
2020-06-23 09:32:50 [PicGo SUCCESS] 
https://raw.githubusercontent.com/whitoad/huahua/matser/img/20200623093248.jpg

## 问题描述

图片明明上传成功，在库里也可以看到，但是图片直接地址（如下）无法访问，显示404:；同时也无法在typora中加载。

https://raw.githubusercontent.com/whitoad/huahua/matser/img/20200623093248.jpg

翻看了很多文章，有我类似问题的貌似原因都不同，我不知道是不是自己图片地址设置的有问题？如能解答，不胜感激。

**Comment by Molunerfinn** [comment]
正确的地址是这个[https://raw.githubusercontent.com/whitoad/huahua/master/img/20200623093248.jpg](https://raw.githubusercontent.com/whitoad/huahua/master/img/20200623093248.jpg)

你看看你自己哪里设置错了吧。

**Comment by whitoad** [comment]
> 正确的地址是这个https://raw.githubusercontent.com/whitoad/huahua/master/img/20200623093248.jpg
> 
> 你看看你自己哪里设置错了吧。

看出来了。的确是相当低级的错误…汗颜，感谢指出。

**Comment by Georgebobby** [comment]
這兩個url 一樣啊～
可是一個可以一個不行。。。
