### ISSUE TITLE
PicGo 配置项失效，需要重新设置才生效

### ISSUE THREAD

**Issue by jacob-lcs** [Molunerfinn/PicGo#527]
## 问题类型

Bug Report

## PicGo 的相关信息

win10 2004 PicGo 2.3.0-beta.0

## 问题重现
![](http://image.coursehelper.online/20200623220851.png)
之前安装了 PicGo 旧版本，设置好了上传成功后自动复制 URL，但是在安装新版本之后就无法自动复制，最终尝试重新设置此开关后恢复正常。

**Comment by Molunerfinn** [comment]
已经修复，下个版本更新即可
