### ISSUE TITLE
关于PicGo支持“上传图片前自动压缩”功能的反馈

### ISSUE THREAD

**Issue by luffythink** [Molunerfinn/PicGo#532]
**声明：我已经仔细看过 [文档](https://picgo.github.io/PicGo-Doc/)、[FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)、和搜索过已经关闭的 [issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed) 后依然没有找到答案，所以才发了一个新的 issue。**

## 问题类型
Feature Request

## PicGo 的相关信息
Version: 2.3.0-beta.1
Mac 10.15.3 

## 功能请求
首先感谢PicGo团队，感谢你们提供了这样一个好用的工具。

**需求场景简单描述：**
相信大家在选择图床的时候，经历过之前的图片数据无故丢失的情况，对安全性是非常看重的。所以目前使用的是PicGo+免费的SM.MS图床-5G空间/付费的阿里云OSS-40G相对非常稳定安全的组合，实现Typora编辑文字的时候一键上传图片，非常方便。由于三个原因：
①SM.MS空间有限只有免费5个G；
②阿里云需要付一定费用，长远考虑可能隐藏着一定流量费用；
③在MAC下经常会使用截图，截图的文件都比较大，还有拍的相关照片，笔记配图等等都比较大。

在使用Typora编辑配图的时候，我会使用tinypng这个网站对图片进行一次压缩，然后再上传。想这样不仅可以节省空间，同时带来访问速度的提升。但实际操作的时候，发现压缩图片这个过程会特别不高效：比如截图的时候正常可以直接就保存到Markdown文档里，但由于要压缩，需要先保存到桌面然后上传到tinypng压缩，然后下载然后再上传到Markdown文档。（这里如果有更高效的方法也希望告知~）

于是就萌生了PicGo在上传图片的时候能否进行自动压缩(比如可以设置压缩的比例)，那就太棒了。`在使用PicGo的过程中，发现有如下一些非常人性化的功能：比如上传前重命名，时间戳命名等，及提供支持主流的图床供选择。`
![截屏2020-07-06下午6 30 18](https://user-images.githubusercontent.com/40992395/86585665-673b0e80-bfb9-11ea-9cea-a5db2a4f6a3c.png '比如这个截图是1.1M，压缩后是200k左右，在github上传速度至上提示了有5倍把')
<img width="1149" alt="截屏2020-07-06下午6 48 21" src="https://user-images.githubusercontent.com/40992395/86585804-96518000-bfb9-11ea-9504-ffbfe00316b3.png">

自身想过通过一段代码实现压缩插件的集成，但目前能力有限，所以最后还是在这里写issue-功能反馈了。希望PicGO团队抽空可以评估一下这个压缩功能集成的需求，尤其是使用付费的图床的时候发现图片该压缩还是要压缩呀，比较放到这上面的大部分图片都是为了分享用，考虑存储空间考虑流量，有时候不需要特别高清。

最后想说第一次反馈，如有描述不妥请见谅，最终不管采纳与否，仍然谢谢PicGo。

---

**Comment by Molunerfinn** [comment]
感谢反馈，已有插件：https://github.com/JuZiSang/picgo-plugin-compress

**Comment by luffythink** [comment]
Thanks，厉害厉害。

**Comment by science-ctrl** [comment]
WoW! Thanks very much!

**Comment by mafulong** [comment]
gui可以支持图片压缩码

**Comment by Molunerfinn** [comment]
> gui可以支持图片压缩码

https://github.com/JuZiSang/picgo-plugin-compress
