### ISSUE TITLE
Bug Report: 快捷键禁用失败

### ISSUE THREAD

**Issue by rothleer** [Molunerfinn/PicGo#534]
**声明：我已经仔细看过 [文档](https://picgo.github.io/PicGo-Doc/)、[FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)、和搜索过已经关闭的 [issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed) 后依然没有找到答案，所以才发了一个新的 issue。**

## 问题类型

Bug Report：快捷键禁用失败

## PicGo 的相关信息

PicGo 2.2.2 以及 2.3.0 beta.1
windows 10 1903 操作系统版本18362.900

## 问题重现

禁用快捷键后，PicGo 依然会占据快捷键。
![image](https://user-images.githubusercontent.com/14935354/87013939-ffc1d080-c1fd-11ea-8959-f2967935661e.png)
![image](https://user-images.githubusercontent.com/14935354/87014256-73fc7400-c1fe-11ea-91c3-046f5524c24f.png)

## 功能请求

---
PicGo 是一个优秀的项目，已经 star。

**Comment by Molunerfinn** [comment]
收到，近期会排查一下
