### ISSUE TITLE
Typora自动上传端口冲突问题

### ISSUE THREAD

**Issue by yuhw2001** [Molunerfinn/PicGo#535]
## 问题类型

 Bug Report 

## PicGo 的相关信息

Picgo 2.2.2 +window 10+typora 0.9.90

## 问题重现

**类似问题：** https://github.com/Molunerfinn/PicGo/issues/415

- 在 PicGo 未启动的情况下，通过Typora自动上传图片，能成功上传。
- 但是，如果 PicGo 已经启动，再通过Typora自动上传图片，会出现上传失败的情况。
- 查看设置，picgo server，端口自动变为了366771

## 功能请求
**bug修复**

Picgo使用一年余，功能越来越强大。
与typora结合，无敌顺畅，点赞！
请喝咖啡一杯！但是首页和帮助文档中二维码被墙啦，翻墙才能显示。

**Comment by Molunerfinn** [comment]
感谢支持，请更新最新beta版已经修复
