### ISSUE TITLE
windows用户下载exe文件-下载不下来-能否放置在其他地方提供下载的?

### ISSUE THREAD

**Issue by itclanCode** [Molunerfinn/PicGo#536]
**声明：我已经仔细看过 [文档](https://picgo.github.io/PicGo-Doc/)、[FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)、和搜索过已经关闭的 [issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed) 后依然没有找到答案，所以才发了一个新的 issue。**

## 功能请求

---

**Comment by Molunerfinn** [comment]
后续会找其它方式提供。目前下载不下来可以谷歌其他人给出的网盘等链接，应该是很多的

**Comment by itclanCode** [comment]
感谢回答,已经解决,github下载确实下不来
