### ISSUE TITLE
[Bug Report]切换默认图床后不改变默认uploader

### ISSUE THREAD

**Issue by samkong97** [Molunerfinn/PicGo#537]
**声明：我已经仔细看过 [文档](https://picgo.github.io/PicGo-Doc/)、[FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)、和搜索过已经关闭的 [issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed) 后依然没有找到答案，所以才发了一个新的 issue。**

## 问题类型
Bug Report

## PicGo 的相关信息
2.3.0-beta.2
win10

## 问题重现
修改默认图床后，picBed的uploader不会改变，如从阿里云切换到腾讯云，current变了，实际uploader没有变化。
查看data.json，为如下代码，uploader没有修改
```  
"current": "tcyun",
"uploader": "aliyun"
```

## 功能请求

---

**Comment by samkong97** [comment]
看了下代码
```
this.letPicGoSaveData({
      'picBed.current': type
    })
```
好像只是设置了current，为啥不设置uploader

**Comment by Molunerfinn** [comment]
收到，这里是历史遗留问题。一开始是 `current`，后面为了统一命名设定了 `uploader`。但是目前看来二者还需要共存一下。代码有bug，会尽快修复，感谢提出issue
