### ISSUE TITLE
windows用户-picgo-上传到github-本地图片不显示

### ISSUE THREAD

**Issue by itclanCode** [Molunerfinn/PicGo#538]
**声明：我已经仔细看过 [文档](https://picgo.github.io/PicGo-Doc/)、[FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)、和搜索过已经关闭的 [issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed) 后依然没有找到答案，所以才发了一个新的 issue。**

## 问题类型

版本：picGo 2.0.3
问题:   使用的是github图床-本地上传图片,可以上传到github仓库,但是无论是使用markdwon还是链接方式,都不显示
![图片不显示](https://user-images.githubusercontent.com/25076543/87258690-17d47100-c4d8-11ea-98c3-ffbd72d84c4b.png)

## PicGo 的相关信息

1. windows64
2. 版本:2.0.3

## 功能请求

---

**Comment by Molunerfinn** [comment]
说明你家网络把github的静态资源节点墙了。picgo上传成功就说明picgo这侧没问题
