### ISSUE TITLE
win版本开机静默启动，不弹出窗口

### ISSUE THREAD

**Issue by liutf** [Molunerfinn/PicGo#54]
* 问题
  开机自动启动的时候，会自动刚打开窗口。还要手动点一下关闭。  
 一般情况下：在刚开始下载完，配置完成后，只需要静默启动就可以了，并不需要每次开机启动打开着窗口，`多一次用户点击最小化窗口的操作`。  

* 期望
  开机静默启动，后台运行，不弹出窗口。强烈希望作者能体谅下懒人的苦，谢谢！

**Comment by Molunerfinn** [comment]
这个是权衡了其他一些软件的开机自启做的决定，诸如TIM、微信等开机自启都是弹出主窗口，所以采用这个方式。如果不喜欢可以关闭。

**Comment by liutf** [comment]
但是作为产品的角度来说：
微信和QQ是社交产品，高频打开。PicGo在我配置好之前，我是会打开的比较多，但是我配置好后，我基本上很少再去点开窗口了。

现在因为设置为开机启动，我并不需要进行任何操作却要额外关闭PicGo下这个窗口。

设置为开机不启动，我在我需要的时候启动PicGo，结果也还是会弹出个窗口出来，我也要再去手动点下最小化窗口。

可以考虑下能否给个开关让用户做选择吗？

比如[qiniu-image-v2](http://jverson.com/2017/05/28/qiniu-image-v2/) 这个工具默认就都是静默的，觉得很安静。

**Comment by Molunerfinn** [comment]
对于Windows平台之后会做一个非常小的悬浮窗，那个窗口将会替代主窗口的上传功能。以后开机自启的话应该会开启那个窗口。

**Comment by Roger-WIN** [comment]
但还是希望能增加一个静默启动的开关，给用户选择的权利。

**Comment by cooper1x** [comment]
我也建议加一个静默启动，参照可以snipaste，直接在后台用快捷键加上传提示会更方便一些，拖拽到图标上传感觉还是不够快捷。
