### ISSUE TITLE
A JavaScript error occurred in the main process

### ISSUE THREAD

**Issue by NMfairyland2** [Molunerfinn/PicGo#540]
![image](https://user-images.githubusercontent.com/54350926/87876218-2b686600-ca09-11ea-80ed-4c91ac150ebc.png)
无法打开

**Comment by Molunerfinn** [comment]
删掉这个文件再重新启动PicGo即可。
![image](https://user-images.githubusercontent.com/12621342/87876362-425b8800-ca0a-11ea-821f-fb89d2eba883.png)
