### ISSUE TITLE
启动软件后出现错误提示

### ISSUE THREAD

**Issue by yinweijie** [Molunerfinn/PicGo#543]
**声明：我已经仔细看过 [文档](https://picgo.github.io/PicGo-Doc/)、[FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)、和搜索过已经关闭的 [issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed) 后依然没有找到答案，所以才发了一个新的 issue。**

## 问题类型

Bug Report
## PicGo 的相关信息

PicGo 2.2版，win10系统
## 问题重现

无法打开软件，打开后显示如下图，之前可以使用，后来不知道什么原因出现这种情况，重装也无法解决：
![image](https://user-images.githubusercontent.com/23356124/88462405-a7691f00-cedd-11ea-8718-afb24dc68db6.png)

## 功能请求

---

**Comment by Molunerfinn** [comment]
这个已经有人问过了
