### ISSUE TITLE
PicGo上传Imgur图床，设置代理还是不能显示

### ISSUE THREAD

**Issue by kwstars** [Molunerfinn/PicGo#548]
**声明：我已经仔细看过 [文档](https://picgo.github.io/PicGo-Doc/)、[FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)、和搜索过已经关闭的 [issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed) 后依然没有找到答案，所以才发了一个新的 issue。**

## 问题类型
Bug Report

## PicGo 的相关信息

系统版本：Ubuntu 20.04.1 LTS
PicGo版本：2.2.2
图床：Imgur

## 问题重现
Imgur在国内是被墙的，我通过代理设置上传图片是可以的，但是PicGo我也设置了代理，但是图片不显示

> 
![2020-08-01_18-28](https://user-images.githubusercontent.com/12113145/89099877-163a0100-d425-11ea-80c3-795aba7c45d9.png)

![2020-08-01_18-29](https://user-images.githubusercontent.com/12113145/89099880-1b974b80-d425-11ea-878a-bad8957062d4.png)

![2020-08-01_18-29_1](https://user-images.githubusercontent.com/12113145/89099882-1e923c00-d425-11ea-9212-13d5fe234ab8.png)

## 功能请求

---

**Comment by Molunerfinn** [comment]
代理设置只负责上传代理，相册显示走的系统代理。

**Comment by kwstars** [comment]
这个以后可以支持吗？

**Comment by Molunerfinn** [comment]
> 这个以后可以支持吗？

不一定，之后得看看
