### ISSUE TITLE
没有列表，空白页

### ISSUE THREAD

**Issue by tanoak10** [Molunerfinn/PicGo#549]
**声明：我已经仔细看过 [文档](https://picgo.github.io/PicGo-Doc/)、[FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)、和搜索过已经关闭的 [issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed) 后依然没有找到答案，所以才发了一个新的 issue。**

## PicGo 的相关信息

mac 版本10.15 ，构建的代码是master 显示不出来,相同的版本，我用win是可以正常使用的
<img width="576" alt="iShot2020-08-07上午11 19 29" src="https://user-images.githubusercontent.com/37281126/89605448-1c563480-d8a0-11ea-8dda-7cbc26ea15d8.png">

## 功能请求

---

<img width="576" alt="iShot2020-08-07上午11 19 29" src="https://user-images.githubusercontent.com/37281126/89605448-1c563480-d8a0-11ea-8dda-7cbc26ea15d8.png">

**Comment by Molunerfinn** [comment]
右键顶部栏图标会出现菜单- -，文档里说了，之前的issue里也说了。

**Comment by tanoak10** [comment]
找到了，不好意思
