### ISSUE TITLE
关于文件命名问题

### ISSUE THREAD

**Issue by dwqhunjaiuq** [Molunerfinn/PicGo#55]
## 问题类型

Feature Request

## PicGo的相关信息

mac 版本 1.5.0 

## 问题重现

我的图片资源是 按照文件件分类，然后里面图片从0开始递增，0，1，2。。。文件名一致会导致上传出错

## 功能请求

因为不能按照文件夹上传，能否添加选项自动重命名 按照时间戳或者是hash ，防止文件名一直导致上传出错

**Comment by Molunerfinn** [comment]
下个版本会提供自动用时间戳命名的选项。
然后你的这个问题还有另外一种解决办法。你可以指定你的存储路径：
![image](https://user-images.githubusercontent.com/12621342/40165894-c5e4518a-59ef-11e8-80d0-a0a79fb03894.png)
这样你存到github上的时候可以按文件夹来存。
比如我的
![image](https://user-images.githubusercontent.com/12621342/40165949-e1811e64-59ef-11e8-8a67-5031661c8240.png)
希望能帮助你。
