### ISSUE TITLE
MacBook打开PicGo就没了，客户端完全出不来，但又在后台运行。就是出不来界面

### ISSUE THREAD

**Issue by a782272323** [Molunerfinn/PicGo#554]
**声明：我已经仔细看过 [文档](https://picgo.github.io/PicGo-Doc/)、[FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)、和搜索过已经关闭的 [issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed) 后依然没有找到答案，所以才发了一个新的 issue。**

## 功能请求

---

**Comment by a782272323** [comment]
好几个版本都试过了了

**Comment by Molunerfinn** [comment]
请看文档

**Comment by londbell** [comment]
> **声明：我已经仔细看过 [文档](https://picgo.github.io/PicGo-Doc/)、[FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)、和搜索过已经关闭的 [issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed) 后依然没有找到答案，所以才发了一个新的 issue。**
> ## 问题类型
> ## PicGo 的相关信息
> ## 问题重现
> ## 功能请求

同样的问题，无论是自己下dmg装还是brew重装，都没有界面，去活动监视器里看就是显示未响应
