### ISSUE TITLE
Github图床自定义域名的问题

### ISSUE THREAD

**Issue by lzk800** [Molunerfinn/PicGo#558]
**声明：我已经仔细看过 [文档](https://picgo.github.io/PicGo-Doc/)、[FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)、和搜索过已经关闭的 [issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed) 后依然没有找到答案，所以才发了一个新的 issue。**

## 问题类型

Bug Report
## PicGo 的相关信息

2.2.2  Windows
## 问题重现
比如我的github仓库的CNAME是 xxx.com，仓库是 username/picgo
然后我在picgo的设定自定义域名那栏如果直接输入 https://xxx.com 是会上传失败的
而我将自定义域名那栏改为 https://xxx.com/username/picgo 是可以上传成功的
但是这会导致另一个问题，picgo给出的图片链接地址实际上是错误的，比如为 https://xxx.com/username/picgo/aaa.jpg
而正确的图片链接地址应该是 https://xxx.com/aaa.jpg  这边我附上picgo的日志

[picgo.log](https://github.com/Molunerfinn/PicGo/files/5115935/picgo.log)

## 功能请求

---

**Comment by Molunerfinn** [comment]
自定义域名只会在上传结束后替换URL而不会在上传的时候使用到。

源码：https://github.com/PicGo/PicGo-Core/blob/dev/src/plugins/uploader/github.ts#L42

所以你的情况可能只是很巧合碰到GitHub不能上传的情况罢了，自定义域名依然改为xxx.com即可。
