### ISSUE TITLE
a error link in readme

### ISSUE THREAD

**Issue by yansheng836** [Molunerfinn/PicGo#559]
The link(<https://github.com/Molunerfinn/PicGo/blame/dev/README.md#L47>) in README.md where "详见 [PicGo-Core]" is error.

**Comment by Molunerfinn** [comment]
![image](https://user-images.githubusercontent.com/12621342/91399752-1f29c100-e871-11ea-8361-859a5b6e6947.png)
no error...

**Comment by yansheng836** [comment]
Sorry, I found it was a problem with my computer.
