### ISSUE TITLE
mac下点击menu bar总会自动跳到主桌面窗口

### ISSUE THREAD

**Issue by hitck129** [Molunerfinn/PicGo#56]
## 问题重现
如果我同时打开好几个应用，而其中一些应用是全屏的，如果我在全屏应用窗口下点击menu bar，那么窗口会自动跳到主桌面窗口。
比如我在全屏的Chrome界面下点击menu bar
<img width="1440" alt="2018-05-21 15 04 58" src="https://user-images.githubusercontent.com/8861572/40294514-7b010ebc-5d08-11e8-96be-f4641dbf732c.png">
结果会自动跳回到主桌面
<img width="1440" alt="2018-05-21 15 12 20" src="https://user-images.githubusercontent.com/8861572/40294756-7aa36338-5d09-11e8-9134-cf9e7adbc9fa.png">

## 功能请求

---

**Comment by Molunerfinn** [comment]
![image](https://user-images.githubusercontent.com/12621342/40295358-92e0a6e8-5d0b-11e8-940b-834ab08b25f4.png)
然而我并没有这个问题。。。

**Comment by Molunerfinn** [comment]
不过这个其实也是正常的，因为你打开的是一个窗口而不是一个菜单。你右键的话打开菜单也是不会回到桌面的。你注意看看其他应用，比如微信，比如QQ都是在全屏应用里点击之后会回到桌面。

**Comment by hitck129** [comment]
是的，qq也会这样，只是有时候……嗯，比如在网站上收集图片，每收集一个就要回到桌面然后再回来有点鬼畜。
当然不全屏就没有这问题，只是养成了全屏习惯😳或者小屏的就比较难受

**Comment by Molunerfinn** [comment]
@hitck129 你收集图片可以右键复制图片，然后用快捷键上传，这样能在后台运行，而且效率也更高不是？

**Comment by hitck129** [comment]
嗯，好方法，刚用这个，很多交互还不熟悉，😄慢慢摸索

**Comment by XIJINIAN** [comment]
之前使用收费图床上传工具 iPic、截图软件 Snap、思维导图软件 MindNode、系统清理工具 Dr.Cleaner Pro 都没有这样的情况，您说“因为你打开的是一个窗口而不是一个菜单”，那么能否将默认单击打开窗口变成打开一个菜单呢？
非常感谢你的开源软件，帮了我的大忙啦。

**Comment by Molunerfinn** [comment]
@XIJINIAN electron只能通过窗口的方式去模拟复杂（有图片、文字等）的菜单。（普通菜单是没法有图片的）所以没有办法变成打开一个菜单。如果想快捷上传可以试试在网页里右键复制图片、或者截图然后直接使用快捷键上传。
