### ISSUE TITLE
上传大于1M的图片到gitee图床可以成功，但是加载却无法加载

### ISSUE THREAD

**Issue by 964097833** [Molunerfinn/PicGo#560]
**声明：我已经仔细看过 [文档](https://picgo.github.io/PicGo-Doc/)、[FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)、和搜索过已经关闭的 [issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed) 后依然没有找到答案，所以才发了一个新的 issue。**

## 问题类型
 Bug Report

## PicGo 的相关信息
2.3.0-beta.3 win10

## 问题重现
![image](https://user-images.githubusercontent.com/49231916/91650376-76b66f80-eab1-11ea-8259-18a2ebf79dc6.png)

## 功能请求

---

**Comment by Molunerfinn** [comment]
这是gitee的限制，跟picgo没关系
