### ISSUE TITLE
win10系统下不显示Mini窗口

### ISSUE THREAD

**Issue by CaptainJon** [Molunerfinn/PicGo#561]
#83  问题类型

Bug Report

## PicGo 的相关信息

版本：2.3.0-beta.3
平台：windows 10

## 问题重现

桌面没有悬浮MIni窗口，多次重启依旧不见。在设置中开启Mini窗口置顶然后重启依旧看不见

**Comment by Molunerfinn** [comment]
mini窗口目前需要手动点击才能开启。你点了主窗口右上角中间的那个+号按钮了吗

**Comment by Molunerfinn** [comment]
![image](https://user-images.githubusercontent.com/12621342/91680308-6370d600-eb7d-11ea-9e4b-7669f728ae23.png)

**Comment by CaptainJon** [comment]
> mini窗口目前需要手动点击才能开启。你点了主窗口右上角中间的那个+号按钮了吗

哦哦，看到了，不好意思
