### ISSUE TITLE
archlinux server端口号会变

### ISSUE THREAD

**Issue by znfang** [Molunerfinn/PicGo#565]
在archlinux版本（manjaro）下面，搭配typora使用时，picgo的端口号会变，从而导致与typora无法结合使用。确认没有多开实例

**Comment by Molunerfinn** [comment]
1. 试试beta版本应该可以。
2. 端口是可以在picgo设置里修改的。可能有被占用的情况所以picgo的端口会自动升，手动改回来即可。端口36677
3. 发issue请按模板发。
