### ISSUE TITLE
Mac安装Picgo不出现在顶部栏/无响应

### ISSUE THREAD

**Issue by londbell** [Molunerfinn/PicGo#566]
**声明：我已经仔细看过 [文档](https://picgo.github.io/PicGo-Doc/)、[FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)、和搜索过已经关闭的 [issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed) 后依然没有找到答案，所以才发了一个新的 issue。**

## 问题类型

Bug Report

## PicGo 的相关信息

DMG安装的2.2.1/2.2.2/2.3.0-beta-3
Brew安装的2.2.2都有这个问题
系统macOS 10.13.6 

## 问题重现

问题描述：年初下载过，大致是2月份，2.2.2是1月份发布的，我使用的应该是2.2.2版本。当时正常。从五月开始基本没用过。

今天打开后，发现状态栏没有picgo图标，多次点击运行提示“未响应，不能重复打开”
于是dmg重新覆盖安装2.2.2，依然失败。
没办法了就卸载掉，全新安装，DMG安装的2.2.1/2.2.2/2.3.0-beta-3，Brew安装的2.2.2。都无法运行。

<img width="1439" alt="WX20200915-195332@2x" src="https://user-images.githubusercontent.com/7590762/93207596-c96c7880-f78d-11ea-9392-2540efee1115.png">
过一段时间后，进程会显示：
<img width="561" alt="WX20200915-195903@2x" src="https://user-images.githubusercontent.com/7590762/93207714-f456cc80-f78d-11ea-80e5-e09545358063.png">

进不去主界面，状态栏也没有，没法导出日志。。。

进不去主界面，状态栏也没有，没法导出日志。。。
## 功能请求

---

**Comment by Molunerfinn** [comment]
重启一下电脑试试...

**Comment by londbell** [comment]
> 重启一下电脑试试...

试了下还是一样...请问picgo的错误日志存储在哪，我导出一下给您看看

**Comment by Molunerfinn** [comment]
在配置文件所在的目录：
![image](https://user-images.githubusercontent.com/12621342/93310552-849d1c00-f837-11ea-9aa1-22d10828fa33.png)
日志只有运行时才有，如果没有运行，理论上也没有可用日志。我猜测是picgo的配置文件data.json损坏了导致打不开。或者就是你安装了什么插件。

可以尝试进入picgo的配置文件所在路径 `~/Library/Application\ Support/picgo` 之后，手动删除data.json、package.json、node_modules目录，然后重新安装picgo重启应该就可以了

**Comment by Molunerfinn** [comment]
可以先看看data.json是不是正常的，如果正常可能是安装了什么插件不兼容导致的。如果data.json就是不正常的，那就直接删掉，然后重启picgo即可，会自动重新生成一个默认的配置文件

**Comment by londbell** [comment]
<img width="427" alt="图片" src="https://user-images.githubusercontent.com/7590762/93332870-149d8e80-f855-11ea-8e44-7b4c990ace12.png">

<img width="515" alt="图片" src="https://user-images.githubusercontent.com/7590762/93332915-267f3180-f855-11ea-9da2-4aa05bf73c5f.png">
<img width="608" alt="图片" src="https://user-images.githubusercontent.com/7590762/93333047-5595a300-f855-11ea-8815-acd7583717d1.png">

比较疑惑的一点是卸载pcigo时则目录应该直接没有了。再安装应该也是新文件，我先按照您说的删除data.json package.json、node_modules重装试试

**Comment by londbell** [comment]
`~/Library/Application\ Support/picgo`目录里没有`node_modules`，这个问题和我的node版本有关系吗？

**Comment by Molunerfinn** [comment]
> `~/Library/Application\ Support/picgo`目录里没有`node_modules`，这个问题和我的node版本有关系吗？

不是，说明你没装过插件。没装过就没有。

**Comment by Molunerfinn** [comment]
卸载的话，这些配置属于用户目录下的，不属于安装目录下的，不同的卸载软件的处理不一样。不过如果只是从application目录下删除的话，这些配置文件是还会继续留着的。picgo没有处理卸载逻辑。

**Comment by londbell** [comment]
![A556F5E2CD6B62CEBC6E63F9A649509A](https://user-images.githubusercontent.com/7590762/93416635-b5815d80-f8d8-11ea-9450-e4429f605e4e.gif)
妈耶，我换1.6.2好了...谢谢了，太麻烦你了
不过我感觉可能是2.0.0开始不滋磁旧版macOS了...
