### ISSUE TITLE
【Feature Request】上传重命名自动生成文件名

### ISSUE THREAD

**Issue by dongzx666** [Molunerfinn/PicGo#57]
## 问题类型

Feature Request

## PicGo的相关信息

版本1.5.0，所在平台Mac

## 功能请求

希望上传重命名可以多提供一个自动生成文件名功能，例如时间戳+3位随机数+UID。谢谢

**Comment by Molunerfinn** [comment]
跟这个[issue](https://github.com/Molunerfinn/PicGo/issues/52#event-1626767484)重复。将会考虑加上自动用时间戳重命名的选项。
