### ISSUE TITLE
希望可以增加源文件名+随机字符串的命名方式

### ISSUE THREAD

**Issue by nonozone** [Molunerfinn/PicGo#572]
**声明：我已经仔细看过 [文档](https://picgo.github.io/PicGo-Doc/)、[FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)、和搜索过已经关闭的 [issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed) 后依然没有找到答案，所以才发了一个新的 issue。**

## 问题类型

 Feature Request？

## PicGo 的相关信息

2.3.0-BETA3，Windows10。

## 功能请求

看了一圈设置，好像目前不能先现有文件名后面加随机字符串的形式自定义链接？
目前有一个通过时间戳重命名的功能，但是这个功能，会抹去原有的文件名，这个在SEO上不是特别友好，可不可以开放 $filename-随机字符串，的形式来重命名？
---

**Comment by Molunerfinn** [comment]
https://github.com/liuwave/picgo-plugin-rename-file
