### ISSUE TITLE
每次插入上传图片，自动生成MD代码的时候，可不可以自动将光标返回到代码的最后

### ISSUE THREAD

**Issue by nonozone** [Molunerfinn/PicGo#574]
**声明：我已经仔细看过 文档、FAQ、和搜索过已经关闭的 issues 后依然没有找到答案，所以才发了一个新的 issue。**

## 问题类型
Feature Request？

## PicGo 的相关信息
2.3.0-BETA3，Windows10。

## 功能请求
现在用的typora，每次插入图片之后，自动生成的图片代码如下

![image](https://user-images.githubusercontent.com/1277444/95869143-a5588300-0d9d-11eb-8293-ebd5ffe85ea6.png)

默认是选中整个图片的链接地址的，于是自己还需要点鼠标，才可以回车，然后下一行，有没有办法，生成图片代码之后，光标直接返回在整段代码后面，也就是最后的”）“后面，这样就可以不用点鼠标，直接键盘回车，然后下一行继续其他操作了？

**Comment by Molunerfinn** [comment]
这个问题请找typora....
