### ISSUE TITLE
Picgo 总是默认把图片上传到 Github 图床

### ISSUE THREAD

**Issue by yiranzhimo** [Molunerfinn/PicGo#575]
# 问题
Picgo 设置了三个图床，分别是 Github，阿里云 OSS 和 Gitee 图床，尽管上传区设置的是其他两个图床，图片总是被上传到了 Github，即使将默认图床分别更改成 阿里云 OSS 和 Gitee 图床，也会上传到 Github。

软件版本是 2.2.2

**Comment by Molunerfinn** [comment]
更新最新版本再重新设定默认上传图床即可
