### ISSUE TITLE
上传报错：RequestError: Error: read ECONNRESET

### ISSUE THREAD

**Issue by Alarikshaw** [Molunerfinn/PicGo#578]
**声明：我已经仔细看过 [文档](https://picgo.github.io/PicGo-Doc/)、[FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)、和搜索过已经关闭的 [issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed) 后依然没有找到答案，所以才发了一个新的 issue。**

## 问题类型
Bug Report

## PicGo 的相关信息
版本：2.3.0-beta.3
Windows10

## 问题重现
![image](https://user-images.githubusercontent.com/46787751/97551844-73d2ef00-1a0e-11eb-8a8b-f88bf8ccf15d.png)
![image](https://user-images.githubusercontent.com/46787751/97551898-83eace80-1a0e-11eb-8b75-5c9dd2fbf8f6.png)

![image](https://user-images.githubusercontent.com/46787751/97551927-8fd69080-1a0e-11eb-8072-3dafab32e482.png)

## 功能请求
这个情况是github服务器的原因吗？

---

**Comment by Alarikshaw** [comment]
![image](https://user-images.githubusercontent.com/46787751/97553733-c6150f80-1a10-11eb-8938-40f830831bfc.png)
时间戳已打开，文档已仔细阅读。

**Comment by Molunerfinn** [comment]
网络问题，picgo无法解决。faq里说了

**Comment by Alarikshaw** [comment]
好的，可以的话请在文档里加上我此类报错，避免其他人使用的时候找不到对应的文档。你这里有付费的吗？

**Comment by Molunerfinn** [comment]
没有强制付费，如果觉得对你有帮助可以二维码打赏~在项目readme下面有二维码

**Comment by Alarikshaw** [comment]
哈哈，可以的。

**Comment by HiColinn** [comment]
我也是这个问题,开了代理,IDEA和其它软件都用的一个代理没问题,但是就是上传失败.

**Comment by HiColinn** [comment]
> 没有强制付费，如果觉得对你有帮助可以二维码打赏~在项目readme下面有二维码

同样的环境,退回到2.2.2正式版以后,一下就上传成功了,不知道什么原因噢

**Comment by HiColinn** [comment]
反复测试了正式版和beat版本,如果使用代理,就会上传失败,没反应,测试环境是
v2rayNG,系统是Win10,代理设置参数是:"https://127.0.0.1:10809",
v2RayNG已经开启系统代理,同时监听的http端口也是10809,其它软件挂了代理都正常,PicGo设置代理以后就上传不了,取消代理就上传成功.

**Comment by WuDiDaBinGe** [comment]
Ubuntu系统在中配置如下
{
  "picBed": {
    "github": {
      "repo": "WuDiDaBnGe/TyporaImage",
      "token": "ghp_FOg8YtLKtBYLBpy08HFSB",
      "path": "imgs/",
      "customUrl": "",
      "branch": "master"
    },
    "current": "github",
    "uploader": "github"
  },
  "picgoPlugins": {
    "picgo-plugin-gitee-uploader": true,
    "picgo-plugin-super-prefix": true
  },
  "picgo-plugin-super-prefix": {
    "fileFormat": "YYYYMMDDHHmmss"
  }
}
也会出现该错误，不管代理开没开都出现了 
在Typora软件中会出现该错误
但是使用 picgo upload可以成功上传 不知道为什么
