### ISSUE TITLE
mac 10.15.7 没有打开主页面按钮

### ISSUE THREAD

**Issue by mosandao** [Molunerfinn/PicGo#579]
版本测试过：2.3.0-beta.3、2.3.0-beta.2、2.3.0-beta.1、2.3.0-beta.0、2.2.2、1.6.2
![image](https://user-images.githubusercontent.com/47291175/97654990-0b801e00-1a9f-11eb-9503-36ad66913b27.png)
![image](https://user-images.githubusercontent.com/47291175/97655094-48e4ab80-1a9f-11eb-99a6-86238d00b6db.png)

**Comment by Molunerfinn** [comment]
请看文档和过往issue :)
