### ISSUE TITLE
希望增加typora在自动上传图片时可以自动转化为html链接,方便修改图片大小

### ISSUE THREAD

**Issue by Windchime-Echo** [Molunerfinn/PicGo#580]
**声明：我已经仔细看过 [文档](https://picgo.github.io/PicGo-Doc/)、[FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)、和搜索过已经关闭的 [issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed) 后依然没有找到答案，所以才发了一个新的 issue。**

## 功能请求

---

**Comment by Molunerfinn** [comment]
请去typora官方仓库提这个issue，这不是picgo能做的
