### ISSUE TITLE
picgo-plugin-quick-capture不能上传图片

### ISSUE THREAD

**Issue by 1015127214** [Molunerfinn/PicGo#583]
我试过2.2.2和测试版的2.3.0beta3版本，都是在Windows10下，前面的版本还能正常截图，后面的测试版本连截图都有问题，都不能截图，不知道是什么原因导致上传不成功，还请大佬指教。

**Comment by Molunerfinn** [comment]
这个问题去插件仓库提...

**Comment by Molunerfinn** [comment]
另外最好给个录屏什么的，方便定位问题

**Comment by Molunerfinn** [comment]
另外上传得了和上传不了都给一下picgo的日志才知道是什么原因。mac测试2.3.0beta没问题。
