### ISSUE TITLE
picgo无法识别mime

### ISSUE THREAD

**Issue by maqiankun** [Molunerfinn/PicGo#586]
![image](https://user-images.githubusercontent.com/44855061/99204771-9ed08780-27f1-11eb-8087-32acade84f2b.png)
无法识别图片的mime:Error: No mime type found for file 2018051417460831
![image](https://user-images.githubusercontent.com/44855061/99204853-db9c7e80-27f1-11eb-87aa-400586a1fcfe.png)

**Comment by Molunerfinn** [comment]
是的不支持。请明确后缀
