### ISSUE TITLE
能否支持sm.ms图床

### ISSUE THREAD

**Issue by kysdm** [Molunerfinn/PicGo#59]
## 问题类型

Feature Request
## PicGo的相关信息

Windows v1.5.0
## 问题重现
无

## 功能请求

支持上传图片到sm.ms图床
https://sm.ms/
---

**Comment by Molunerfinn** [comment]
看了一下，api比较友好。可以在1.5.1里支持。具体进度可以查看
https://github.com/Molunerfinn/PicGo/projects/2
