### ISSUE TITLE
功能请求

### ISSUE THREAD

**Issue by Carlos920** [Molunerfinn/PicGo#591]
希望相册能够读取设置文件夹下已有的图片文件（现阶段只有通过picGo上传的才会显示希望通过其他途径上传的图片也会显示在相册中）；同时希望能够重命名相册中相册的名称。

**Comment by Molunerfinn** [comment]
1. 相册里的图片会有对应的远端链接地址，而并不会存储本地文件地址。已有的图片文件PicGo并不知道它是否被picgo上传，或者它被别的工具上传的远端地址。相册的作用是用来快速查找想要的图片并复制远端链接，而不是用来做本地相册展示的。如果要做本地相册展示，未来会开放相关接口给插件实现。
2. 相册里的图片都是本地的，不会对远端造成影响。目前有删除接口，插件可以同步删除操作。未来可以考虑开放编辑接口，可以让插件去修改远端图片名称等。

感谢支持。
