### ISSUE TITLE
low爆了

### ISSUE THREAD

**Issue by 91jetbrain** [Molunerfinn/PicGo#592]
**声明：我已经仔细看过 [文档](https://picgo.github.io/PicGo-Doc/)、[FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)、和搜索过已经关闭的 [issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed) 后依然没有找到答案，所以才发了一个新的 issue。**

## 功能请求
忍不住爆粗口， 上传失败 上传失败，能不能把失败原因说下？？？？？？？？？？？？？？？？？？？？？
能不能？？？？？？？？？？？？？？？？？？？？？？？？？？？？？
这么low逼的软件，就不要拿出来丢人现眼了。 搞了两天没有发现失败问题，正式版 beta版本安装了卸载了好几遍
电脑也重启了好几遍
就不能告诉我哪里失败了？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？

---

**Comment by Molunerfinn** [comment]
有日志自己不看？有issue自己不看？我求你用了？我求求你别用了，用别的吧谢谢您了

**Comment by alaj** [comment]
作者自己花个人时间开发维护的项目，不是求着你用的。请有问题提问题，不要装大爷，开源作者不欠着谁。

**Comment by 91jetbrain** [comment]
> 有文档自己不看？有日志自己不看？有issue自己不看？我求你用了？我求求你别用了，用别的吧谢谢您了

我今天被搞疯了，抱歉， 但是实在找不到原因了， 就是按照配置说明配置的，用户名/库名，master，token，img/ 
GitHub图库就是显示上传失败，404，但是token绝对没有问题，自己复制到txt上面对比过。 断断续续搞了两天没有搞好。
右下角就是显示上传失败，请检查配置，但是这个配置并不复杂，就那几个填写的， 填写完之后，我检查了N遍了，log一直显示404， 哎

我对我今天上午的言论，真的很对不起。

**Comment by Molunerfinn** [comment]
> > 有文档自己不看？有日志自己不看？有issue自己不看？我求你用了？我求求你别用了，用别的吧谢谢您了
> 
> 我今天被搞疯了，抱歉， 但是实在找不到原因了， 就是按照配置说明配置的，用户名/库名，master，token，img/
> GitHub图库就是显示上传失败，404，但是token绝对没有问题，自己复制到txt上面对比过。 断断续续搞了两天没有搞好。
> 右下角就是显示上传失败，请检查配置，但是这个配置并不复杂，就那几个填写的， 填写完之后，我检查了N遍了，log一直显示404， 哎
> 
> 我对我今天上午的言论，真的很对不起。

早这么问不就好了。github现在没有master分支了，默认的只有main分支，把master改成main就行了。不过国内网络质量不好，就算配置对了，也有可能因为墙的原因上传不了。

建议你还是用gitee。picgo+gitee的文章教程应该更多，速度也会更快。缺点就是不能上传大于1M的图。

**Comment by 91jetbrain** [comment]
非常抱歉真的非常抱歉，按照您的解决办法已经好了，已捐赠绵绵之力，望大佬 福如东海 寿比南山
