### ISSUE TITLE
macOS Big sur 打开提示 您没有权限来打开应用程序“PicGo”。

### ISSUE THREAD

**Issue by kaqijiang** [Molunerfinn/PicGo#594]
**声明：我已经仔细看过 [文档](https://picgo.github.io/PicGo-Doc/)、[FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)、和搜索过已经关闭的 [issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed) 后依然没有找到答案，所以才发了一个新的 issue。**

## 功能请求

---

**Comment by kaqijiang** [comment]
![image](https://user-images.githubusercontent.com/16452607/101592038-8e927d80-3a28-11eb-8819-70c0b4f66406.png)

**Comment by Molunerfinn** [comment]
请安装dmg格式的
