### ISSUE TITLE
node版本管理插件安装错误

### ISSUE THREAD

**Issue by JiasNight** [Molunerfinn/PicGo#596]
**声明：我已经仔细看过 [文档](https://picgo.github.io/PicGo-Doc/)、[FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)、和搜索过已经关闭的 [issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed) 后依然没有找到答案，所以才发了一个新的 issue。**

## 问题类型
本地的node环境是通过版本管理工具安装的，但是在PicGo插件设置里安装gitee插件，一直都安装不了，显示已安装该插件，但是重启软件后并没有该插件

## 功能请求

---

**Comment by Molunerfinn** [comment]
如果通过picgo界面安装不了，可以参考手动安装插件方法：

https://github.com/PicGo/picgo-plugin-pic-migrater/issues/35#event-4071155514

后续会优化插件安装的逻辑

**Comment by JiasNight** [comment]
噢，通过研究解决了，插件安装的逻辑确实不对，npm安装了插件在node全局里，实际插件应移动到配置目录下AppData\Roaming\PicGo\node_modules
