### ISSUE TITLE
picgo在2.2.2版本的时候插件设置无法搜索到插件  比如这个picgo-plugin-gitee-uploader

### ISSUE THREAD

**Issue by xkf001** [Molunerfinn/PicGo#598]
**声明：我已经仔细看过 [文档](https://picgo.github.io/PicGo-Doc/)、[FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)、和搜索过已经关闭的 [issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed) 后依然没有找到答案，所以才发了一个新的 issue。**

## 功能请求

---

**Comment by Molunerfinn** [comment]
网络问题，可以尝试手动安装。
https://github.com/Molunerfinn/PicGo/issues/596
