### ISSUE TITLE
复制地址问题

### ISSUE THREAD

**Issue by sofarx** [Molunerfinn/PicGo#6]
新版设置了几次七牛云之后，上传了图片，点击图片复制的功能，全部复制成第排第一个的地址，其他图片地址复制不了。重启还是一样

**Comment by Molunerfinn** [comment]
需要详细一点说明：
1. 你是通过剪贴板上传的图片还是通过拖拽上传的？
2.点击图片复制功能，是点击顶部栏窗口图片复制的，还是点击详细窗口里相册面板里的复制按钮？

**Comment by Molunerfinn** [comment]
待提供更多信息再开issue了，先关闭。

**Comment by sofarx** [comment]
好的，谢谢。今天测试又重现不了。后来我是升级过到最新版的，忘记了是升级前还是升级后的。

**Comment by Molunerfinn** [comment]
嗯嗯，没问题就好~
