### ISSUE TITLE
剪切板上传图片 报错

### ISSUE THREAD

**Issue by 370125229** [Molunerfinn/PicGo#602]
**声明：我已经仔细看过 [文档](https://picgo.github.io/PicGo-Doc/)、[FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)、和搜索过已经关闭的 [issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed) 后依然没有找到答案，所以才发了一个新的 issue。**

## 问题类型

Bug Report
## PicGo 的相关信息

Version ：23.0-beta 4 Windows
## 问题重现

无法使用剪切板上传图片 会报错, 文件图片上传正常
2020-12-25 10:14:25 [PicGo INFO] [PicGo Server] is listening at 36677 

![图片](https://i.loli.net/2020/12/25/zT3al
![Snipaste_2020-12-25_10-18-27](https://user-images.githubusercontent.com/60968234/103114761-ec66cc80-469a-11eb-96e5-4dfdee90222c.png)
wPg87dqEXA.png)
## 功能请求

---

**Comment by tiyunchen** [comment]
![image](https://user-images.githubusercontent.com/24793416/104087149-9b5cf800-5298-11eb-9b70-dfb98486260d.png)
我也有这个问题

**Comment by dangehub** [comment]
我也有这个问题

**Comment by 9AM751** [comment]
请问解决了吗

**Comment by Molunerfinn** [comment]
参考：https://github.com/Molunerfinn/PicGo/issues/243
