### ISSUE TITLE
关于自定义链接问题

### ISSUE THREAD

**Issue by Chao-bei** [Molunerfinn/PicGo#604]
**声明：我已经仔细看过 [文档](https://picgo.github.io/PicGo-Doc/)、[FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)、和搜索过已经关闭的 [issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed) 后依然没有找到答案，所以才发了一个新的 issue。**

## 问题类型

功能请求

## PicGo 的相关信息

picgo版本：2.3.0 beta 3 
系统;windows10

## 功能请求

您好，我现在使用的PicGo版本是2.3.0 beta 3，在自定义链接格式中，强制要求含有$url，但是这在使用**CDN**（jsDelivr）时，不需要原始链接
jsDelivrCDN的链接格式一般为：（https://cdn.jsdelivr.net/gh/用户ID/仓库名/文件名）
想问下您可否通过配置文件取消这个限制？

---

**Comment by Molunerfinn** [comment]
这是两个维度的配置，我理解你的配置在这里就能实现。
![image](https://user-images.githubusercontent.com/12621342/103202632-e9373f00-492d-11eb-8b52-6f605e6aa8c8.png)

**Comment by Chao-bei** [comment]
哦哦，好的，谢谢
