### ISSUE TITLE
picgo 快捷键上传 gitee图床 报错：剪贴板没找到图片文件

### ISSUE THREAD

**Issue by linuxcpp** [Molunerfinn/PicGo#607]
**声明：我已经仔细看过 [文档](https://picgo.github.io/PicGo-Doc/)、[FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)、和搜索过已经关闭的 [issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed) 后依然没有找到答案，所以才发了一个新的 issue。**

## 问题类型

 问题描述：picgo 快捷键上传 gitee图床 报错：剪贴板没找到图片文件 image not found in clipboard
------Error Stack Begin------
Error: image not found in clipboard
    at PicGo.upload (D:\programs\picGo\resources\app.asar\node_modules\picgo\dist\src\core\PicGo.js:150:27)
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
-------Error Stack End------- 

## PicGo 的相关信息

PicGo 的版本：2.3.0-b4
所在平台:  Windows7 64位

**Comment by linuxcpp** [comment]
正常拖动图片上传，是没有问题的，很苦恼

**Comment by Molunerfinn** [comment]
你剪贴板里的图片是怎么来的？QQ截图、微信截图？还是怎么来的？这个报错就是你剪贴板里没有图片自然无法上传呀

**Comment by linuxcpp** [comment]
> 你剪贴板里的图片是怎么来的？QQ截图、微信截图？还是怎么来的？这个报错就是你剪贴板里没有图片自然无法上传呀

就是选中要上传的图片，ctrl+c 放到剪贴板里面，然后ctrl+ shift +c 上传。

**Comment by Molunerfinn** [comment]
WIN7不支持文件系统里的图片ctrl+c这种方式。可以直接在系统文件夹下面右键图片 -> 通过PicGo上传。

WIN10支持上述方式。所以升级系统吧。

**Comment by PlainTribalt** [comment]
我也遇到了 我是win10 用的钉钉截图 粘贴板里存在图片 win+v 查看了 但是还是提示这个错误信息
