### ISSUE TITLE
URL 不支持 Markdown 嵌套

### ISSUE THREAD

**Issue by LiarOnce** [Molunerfinn/PicGo#61]
## 问题类型

Bug Report

## PicGo的相关信息

版本：1.5.0
平台：Windows

## 问题重现

我的博客支持灯箱，所以我想将 Markdown 设置成如图所示的格式，不过只正确输出了第一个，第二个依然输出占位符 `$url`

![snipaste_20180528_180033.png](https://i.loli.net/2018/05/28/5b0bd3d4cd2de.png)
![snipaste_20180528_180058.png](https://i.loli.net/2018/05/28/5b0bd3d4e1990.png)

**Comment by Molunerfinn** [comment]
已经修复，v1.5.1版本里将会更新。
