### ISSUE TITLE
windows scoop 

### ISSUE THREAD

**Issue by huangnauh** [Molunerfinn/PicGo#610]
**声明：我已经仔细看过 [文档](https://picgo.github.io/PicGo-Doc/)、[FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)、和搜索过已经关闭的 [issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed) 后依然没有找到答案，所以才发了一个新的 issue。**

## 问题
 
1. https://github.com/helbing/scoop-bucket， 不会自动根据 release 更新版本
2. 提交到官方仓库 https://github.com/lukesampson/scoop-extras

## 处理

1. 切换仓库，支持自动更新:
 helbing/scoop-bucket 不支持 github action 自动更新版本，可以切换到 https://github.com/huangnauh/carrot  支持自动更新，相关 commit 见 https://github.com/huangnauh/carrot/commit/f29971b3cbdc8e29d8cb12cbc7367a097ff97ae2

2. 官方仓库的意见：
> Applications without english homepage are not accepted in official buckets.

相关 pr: https://github.com/lukesampson/scoop-extras/pull/5501

**Comment by huangnauh** [comment]
已经合入官方仓库  https://github.com/lukesampson/scoop-extras/blob/master/bucket/picgo.json 
现在可以直接 `scoop install picgo`

**Comment by huangnauh** [comment]
由于官方仓库合入的是 stable version，如果需要 beta version， 可以
```
scoop bucket add helbing https://github.com/huangnauh/carrot
scoop install picgo-beta
```
配置文件见 https://github.com/huangnauh/carrot/blob/master/bucket/picgo-beta.json

**Comment by Molunerfinn** [comment]
感谢贡献，回头会补充到README中~
