### ISSUE TITLE
PicGo 图床Github配置丢失

### ISSUE THREAD

**Issue by wdsjxh** [Molunerfinn/PicGo#611]
## 问题类型
提交的是 Bug Report
## PicGo 的相关信息
最新版本 2.3.0-beta.4  Windows10

## 问题重现
日志截图
https://sm.ms/image/o4FG9DWNSO1c7Zf
说明：
上周五20221.1.15配置成功，周末电脑未关机，周一 2021.1.18重启电脑，下午上传图片github图床配置全空啦

https://sm.ms/image/AVXx8IPKTuOMfgw

**Comment by Molunerfinn** [comment]
在某些情况下，picgo的配置文件读写会出现错误，导致配置文件无法使用，进而引起picgo无法打开。所以picgo在每次打开前会备份一份当前可用的配置，用于下次出现错误时能够替换，从而不影响picgo打开。

我感觉你的情况就是重启电脑的时候，picgo进程意外退出导致配置文件读写异常，所以重启后打开电脑，picgo会找到上次打开的备份来做处理。这是正常的错误处理现象，而且应该有notification提示。后续会把这个自动修复的记录也写入日志中

**Comment by Molunerfinn** [comment]
建议你配置完可以重启一下picgo，这样picgo能把配置备份下来。
