### ISSUE TITLE
功能请求

### ISSUE THREAD

**Issue by zsbai** [Molunerfinn/PicGo#619]
**声明：我已经仔细看过 [文档](https://picgo.github.io/PicGo-Doc/)、[FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)、和搜索过已经关闭的 [issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed) 后依然没有找到答案，所以才发了一个新的 issue。**

## 功能请求

---

希望加一个设置项可以关闭重命名确定选项，每次上传都要确认有些麻烦
感谢🙏

**Comment by Molunerfinn** [comment]
当然是有的...好好找找吧

**Comment by zsbai** [comment]
> 当然是有的...好好找找吧

不好意思...我以为“用时间戳命名”的前提必须打开“上传前重命名”，刚注意到这个
