### ISSUE TITLE
Win10不能打开配置文件

### ISSUE THREAD

**Issue by wangtaowtao** [Molunerfinn/PicGo#622]
相册中残留照片不能删除, 我手动删除的gitee中图片, 导致picgo中删除失败, 想通过打开配置文件中删除历史, 确打不开配置文件.
![打开失败](https://gitee.com/wangtaowtao/static/raw/master/image/20210201113350.png)

**Comment by Molunerfinn** [comment]
你用记事本打开这个目录就行。如果不行就装一个VSCode就行。这个按报错提示来就好。

**Comment by wangtaowtao** [comment]
主要是没有位置文件，看了目录中文件，没有json文件。

**Comment by Molunerfinn** [comment]
你的picgo配置文件目录截个图？

**Comment by wangtaowtao** [comment]
![图片](https://user-images.githubusercontent.com/51364950/106416046-85071e00-648b-11eb-9d54-5e78966147dc.png)

**Comment by wangtaowtao** [comment]
https://gitee.com/wangtaowtao/static/raw/master/image/20210201124721.png

**Comment by Molunerfinn** [comment]
![image](https://user-images.githubusercontent.com/12621342/106416361-30b06e00-648c-11eb-8750-df3a0cc043a3.png)
你看看看你打开的是报错里面的路径么

![image](https://user-images.githubusercontent.com/12621342/106416345-268e6f80-648c-11eb-861c-4e471248fcac.png)

**Comment by Molunerfinn** [comment]
你打开的不是picgo的配置路径，是你系统的。兄弟，请仔细一点

**Comment by wangtaowtao** [comment]
找到了, 在C:\Users\wtao\AppData\Roaming\picgo中, 谢谢
