### ISSUE TITLE
插件无法安装！

### ISSUE THREAD

**Issue by Wingsky6** [Molunerfinn/PicGo#623]
**声明：我已经仔细看过 [文档](https://picgo.github.io/PicGo-Doc/)、[FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)、和搜索过已经关闭的 [issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed) 后依然没有找到答案，所以才发了一个新的 issue。**

## 问题类型
无法安装插件

Bug Report 

## PicGo 的相关信息
2.3.0 beta4 Windows

## 问题重现

![image](https://user-images.githubusercontent.com/54062845/106415404-fa71ef00-6489-11eb-8e0f-5ea264fcc96d.png)
点击对应插件，安装，然后显示一直在安装中，过了好长时间还是如此，安装不了！并且过程中网速为0

## 

能不能通过cmd等命令直接安装插件呀！我已经用npm命令把插件都下好了，但都无法安装，通过picgo里面界面安装插件又没反映
---

**Comment by Wingsky6** [comment]
问题已解决，以管理员模式启动

**Comment by Molunerfinn** [comment]
新版会增加导入插件的模式
