### ISSUE TITLE
Apple Silicon，MacBook Pro M1 无反应

### ISSUE THREAD

**Issue by nybrum** [Molunerfinn/PicGo#624]
**声明：我已经仔细看过 [文档](https://picgo.github.io/PicGo-Doc/)、[FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)、和搜索过已经关闭的 [issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed) 后依然没有找到答案，所以才发了一个新的 issue。**

## 问题类型
Bug Report

## PicGo 的相关信息
2.3.0-beta.4、  **Mac BigSur**

## 问题重现
**2.3.0-beta.4**
MacBook Pro M1 环境下打开无窗口，活动监控器有显示，只能强制退出
**2.2.2**
环境下无窗口，但提示更新

## 功能请求

---

**Comment by HappyTsing** [comment]
同问题，mac无窗口

**Comment by Molunerfinn** [comment]
看一下文档，在顶部栏...，顶部栏图标右键打开窗口

**Comment by Cssmiley** [comment]
同问题，mac 打開picgo无窗口

Mac OSX 11.6.1 bigsur環境
