### ISSUE TITLE
关于指定存储路径问题

### ISSUE THREAD

**Issue by JunTsao** [Molunerfinn/PicGo#625]
**声明：我已经仔细看过 [文档](https://picgo.github.io/PicGo-Doc/)、[FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)、和搜索过已经关闭的 [issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed) 后依然没有找到答案，所以才发了一个新的 issue。**

## 问题类型

Feature Request

## PicGo 的相关信息

Windows 2.3.0 beta 4

## 功能请求

如Lsky Pro WEB图床,后台可配置上传路径变量
如：配置{Y}/{m}/{d}/，上传后则为yourdomain.com/2021/02/04/test.jpg
如无此文件夹则会生成文件夹

希望PicGo也能支持这种路径变量，能极大方便管理不同日子上传的图片
感谢作者

---

**Comment by Molunerfinn** [comment]
已有相关插件
