### ISSUE TITLE
功能请求 - 图片压缩

### ISSUE THREAD

**Issue by Orainge** [Molunerfinn/PicGo#626]
如果可以希望能增加一个上传前图片自动压缩的功能，目前在gitee未登录状态下无法打开大于1M的图片。
![image](https://user-images.githubusercontent.com/35182966/106868529-d6244580-6709-11eb-9aa0-be257cb04d2e.png)

**Comment by Molunerfinn** [comment]
https://github.com/JuZiSang/picgo-plugin-compress
