### ISSUE TITLE
http调用，图片上传成功，但是http没有响应结果

### ISSUE THREAD

**Issue by qiaocci** [Molunerfinn/PicGo#627]
**声明：我已经仔细看过 [文档](https://picgo.github.io/PicGo-Doc/)、[FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)、和搜索过已经关闭的 [issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed) 后依然没有找到答案，所以才发了一个新的 issue。**

## 问题类型

Bug Report

## PicGo 的相关信息

PicGo 的版本： 2.3.0-beta4
所在平台：Linux

## 问题重现
通过http调用，弹窗提示上传成功，但是http没有返回结果，could not get response。
![image](https://user-images.githubusercontent.com/25075484/107119713-5abac380-68c4-11eb-88f9-19d544c4f6a2.png)

![image](https://user-images.githubusercontent.com/25075484/107119705-4c6ca780-68c4-11eb-825a-b44f76d29ec4.png)

日志：
```
2021-02-06 21:43:17 [PicGo INFO] Before transform 
2021-02-06 21:43:17 [PicGo INFO] Transforming... 
2021-02-06 21:43:17 [PicGo INFO] Before upload 
2021-02-06 21:43:17 [PicGo INFO] beforeUploadPlugins: renameFn running 
2021-02-06 21:43:17 [PicGo INFO] Uploading... 
2021-02-06 21:43:19 [PicGo SUCCESS] 
https://cdn.jsdelivr.net/gh/qiaocci/img-repo@master/20210206214317.jpg
```

**Comment by Molunerfinn** [comment]
收到，放假时看看是什么问题

**Comment by Molunerfinn** [comment]
![image](https://user-images.githubusercontent.com/12621342/107142996-7fb74100-696d-11eb-97a6-f8bfd2954e69.png)
mac上无法复现，看看是不是什么网络代理的原因？

**Comment by qiaocci** [comment]
之前在picgo里设置了http代理，我现在把代理关掉，然后通过postman调用，现象和之前一样。图片能上传，但是http没有响应，could not get response。
我用的是linux系统，picgo用的是appimage。

**Comment by Molunerfinn** [comment]
> 之前在picgo里设置了http代理，我现在把代理关掉，然后通过postman调用，现象和之前一样。图片能上传，但是http没有响应，could not get response。
> 我用的是linux系统，picgo用的是appimage。

picgo的http代理只影响picgo的上传，跟picgo本身的httpserver没关系

**Comment by qiaocci** [comment]
httpserver能看到更加详细的日志吗？
现在的日志只能看到上传成功了。
```
2021-02-08 10:06:29 [PicGo INFO] Before transform 
2021-02-08 10:06:29 [PicGo INFO] Transforming... 
2021-02-08 10:06:29 [PicGo INFO] Before upload 
2021-02-08 10:06:29 [PicGo INFO] beforeUploadPlugins: renameFn running 
2021-02-08 10:06:29 [PicGo INFO] Uploading... 
2021-02-08 10:06:31 [PicGo SUCCESS] 
https://cdn.jsdelivr.net/gh/qiaocci/img-repo@master/20210208100629.jpg 
```

**Comment by Molunerfinn** [comment]
> httpserver能看到更加详细的日志吗？
> 现在的日志只能看到上传成功了。
> 
> ```
> 2021-02-08 10:06:29 [PicGo INFO] Before transform 
> 2021-02-08 10:06:29 [PicGo INFO] Transforming... 
> 2021-02-08 10:06:29 [PicGo INFO] Before upload 
> 2021-02-08 10:06:29 [PicGo INFO] beforeUploadPlugins: renameFn running 
> 2021-02-08 10:06:29 [PicGo INFO] Uploading... 
> 2021-02-08 10:06:31 [PicGo SUCCESS] 
> https://cdn.jsdelivr.net/gh/qiaocci/img-repo@master/20210208100629.jpg 
> ```

暂时还没加上，后续会补充一下

**Comment by Molunerfinn** [comment]
下个beta我把http server的日志补充一下

**Comment by qiaocci** [comment]
谢谢，等版本升级了我再看下日志，happy new year！

**Comment by qiaocci** [comment]
更新版本后，上传时有一个报错：
![image](https://user-images.githubusercontent.com/25075484/115991472-23be9900-a5fb-11eb-8fa6-ee1467202d5d.png)

**Comment by qiaocci** [comment]
而且上传会重复，点击一次测试按钮，上传了两次

**Comment by Molunerfinn** [comment]
linux的这个报错大概知道原因。这里上传两次是指两次uploading？还是只是success里输出了两行而已？

**Comment by qiaocci** [comment]
照片上传了两次。是因为失败重试吗？

**Comment by Molunerfinn** [comment]
> 照片上传了两次。是因为失败重试吗？

传了两次的日志有么，还是就是上面的图？失败没有重试机制。除了HTTP调用会出现这个问题，普通上传会出现两次的问题么

**Comment by qiaocci** [comment]
上面的图，最后两行，显示上传了两次。普通上传，不会出现这个问题。
我平常是用typora，http调用，上传之后，会提示好几次。

**Comment by Molunerfinn** [comment]
> 上面的图，最后两行，显示上传了两次。普通上传，不会出现这个问题。
> 我平常是用typora，http调用，上传之后，会提示好几次。

typora的测试，是会上传两张图片的

**Comment by Molunerfinn** [comment]
![image](https://user-images.githubusercontent.com/12621342/115997571-1a8ef580-a616-11eb-98d4-d718b81140c9.png)

**Comment by qiaocci** [comment]
我又试了一下，你说的对～

**Comment by Molunerfinn** [comment]
![image](https://user-images.githubusercontent.com/12621342/115998822-aa836e00-a61b-11eb-99df-1e207481d3b5.png)
这个报错，在什么情况下才会出现？是必现的还是偶现的？

**Comment by Molunerfinn** [comment]
> ![image](https://user-images.githubusercontent.com/12621342/115998822-aa836e00-a61b-11eb-99df-1e207481d3b5.png)
> 这个报错，在什么情况下才会出现？是必现的还是偶现的？

never mind，终于定位到问题了...

**Comment by qiaocci** [comment]
老哥辛苦了，这么晚还在查问题～

**Comment by Molunerfinn** [comment]
> 老哥辛苦了，这么晚还在查问题～

因为想早点把2.3.0的正式版搞出来，现在都7个beta版本了(0-6)，哭了

**Comment by qiaocco** [comment]
问题已修复, 感谢大佬
