### ISSUE TITLE
（更换设备重新安装后并填写api完成后）希望可以读取之前上传过的图片，并支持获取链接。

### ISSUE THREAD

**Issue by supercatreal** [Molunerfinn/PicGo#628]
**声明：我已经仔细看过 [文档](https://picgo.github.io/PicGo-Doc/)、[FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)、和搜索过已经关闭的 [issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed) 后依然没有找到答案，所以才发了一个新的 issue。**
## PicGo 的相关信息
Windows 10 PicGo V2.3.0-Beta

## 功能请求
（重新安装后并填写api完成后）希望可以读取之前上传过的图片，并支持获取链接。

**Comment by Molunerfinn** [comment]
后续会以一个同步插件的形式来提供类似的功能。

**Comment by supercatreal** [comment]
OK，有计划就行啦！
