### ISSUE TITLE
是否可以考虑支持gitlab的图库上传？

### ISSUE THREAD

**Issue by istek** [Molunerfinn/PicGo#63]
## 问题类型

Feature Request

## PicGo的相关信息

1.5.1 、win10

## 功能请求

1. 开发组是否可以考虑增加gitlab图库支持？因为现在已经支持github了，我想gitlab是不是可以重复实现，减少代码量。

2. Linux版本在未来什么版本会考虑发布？

请开发组考虑一下。

---

**Comment by Molunerfinn** [comment]
先说明一下，不存在开发组，这个应用一直是我一个人在开发。

1.gitlab需要调研一下接口是否和github类似，如果不类似将不予默认支持，待2.0版本完成后可以以插件形式支持。
2.目前我没有Linux的测试环境，所以暂时不支持Linux，如果需要可以自行在Linux下使用我的源码构建。不过应该会在2.0版本更新官方支持的Linux版本。

注：2.0版本会加入插件系统，所以理论上可以利用插件系统支持其它图床上传需求，所以目前只再考虑最后两个图床 阿里云和imgur的默认支持，其余图床支持将留给其它开发者基于插件开发。

**Comment by istek** [comment]
收到。非常感谢。
