### ISSUE TITLE
希望能够支持WinARM64，或者给出32位binary

### ISSUE THREAD

**Issue by JeffersonQin** [Molunerfinn/PicGo#632]
**声明：我已经仔细看过 [文档](https://picgo.github.io/PicGo-Doc/)、[FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)、和搜索过已经关闭的 [issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed) 后依然没有找到答案，所以才发了一个新的 issue。**

## 问题类型

Feature Request

## PicGo 的相关信息

Windows 10, ARM64

## 功能请求

希望能够放出支持WinARM64的安装包，或者32位的安装包（以便SPX等设备可以模拟运行）

---

**Comment by Molunerfinn** [comment]
这个应该是electron builder构建参数上的问题。如果急用可以自己加一加，之后有时间再看看
