### ISSUE TITLE
右击文件上传容易误触

### ISSUE THREAD

**Issue by imldy** [Molunerfinn/PicGo#636]
**声明：我已经仔细看过 [文档](https://picgo.github.io/PicGo-Doc/)、[FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)、和搜索过已经关闭的 [issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed) 后依然没有找到答案，所以才发了一个新的 issue。**

## 问题类型

Feature Request

## PicGo 的相关信息

2.3.0-Beta.4

## 问题重现

![和文件编辑选项挨在一块，容易误点](https://user-images.githubusercontent.com/53949747/109946957-c5b8b800-7d13-11eb-8f7a-f9fc3152defa.png)

![和文件编辑选项挨在一块，容易误点](https://user-images.githubusercontent.com/53949747/109946972-c9e4d580-7d13-11eb-84a6-54202e6b1b8e.png)

## 功能请求

希望能挪下边一点，已经误点好多次了，幸亏是自己的对象存储，公共图床的话就删不了了。
已Star。

**Comment by Molunerfinn** [comment]
这个找个小工具挪一下应该就能解决了...放到哪里都会有问题，放到后面有的用户会说找不到这个选项。
