### ISSUE TITLE
markdown加载图片失败

### ISSUE THREAD

**Issue by xduperdu** [Molunerfinn/PicGo#637]
使用picgo+markdown+gitee。 在markdwon插入图片后，图片已经成功上传到gitee，picgo相册区图片加载不出来，并且markdown内显示image load failed，只有图片在gitee的地址。
![image](https://user-images.githubusercontent.com/45358640/110194695-a1282180-7e74-11eb-9eb8-eb89f3eec96c.png)
![image](https://user-images.githubusercontent.com/45358640/110194702-aab18980-7e74-11eb-881a-a8b26ea8c120.png)

**Comment by Molunerfinn** [comment]
1. gitee 图床不是picgo维护的官方图床，有问题也应该找gitee插件，可以去插件仓库反馈。
2. picgo负责上传，确保图片上传到指定位置。看图已经能看出picgo上传是没问题的。
3. gitee图床只支持不大于1MB的图片，你看看是否符合要求。
