### ISSUE TITLE
在DEEPIN上安装能用，但是每次更新别的软件都能在终端里看到错误

### ISSUE THREAD

**Issue by aoeiuv-liu** [Molunerfinn/PicGo#639]
OS：Linux deepin
Picgo：2.2.2 
软件包来源 星火商店 spark-store
报错信息如下：

dpkg: 警告: 正在解析文件 '/var/lib/dpkg/status' 第 42363 行附近，软件包 'picgo' :
 missing 'Description' field
dpkg: 警告: 正在解析文件 '/var/lib/dpkg/tmp.ci/control' 第 7 行附近，软件包 'picgo' :
 missing 'Description' field
(正在读取数据库 ... 系统当前共安装有 269388 个文件和目录。)
准备解压 .../archives/picgo_2.2.2_amd64.deb  ...
正在解压 picgo (2.2.2) 并覆盖 (2.2.2) ...
dpkg: 警告: 正在解析文件 '/var/lib/dpkg/status' 第 42369 行附近，软件包 'picgo' :
 missing 'Description' field

重现场景：任何终端更新都能看到

![image](https://user-images.githubusercontent.com/20061353/110410792-5fb89180-8081-11eb-82e8-8a3ab32295bf.png)

**Comment by Molunerfinn** [comment]
picgo官方没有在任何软件源里发布，都是社区提供的。找到源头的发布者让他看看。

而且这些警告是无伤大雅的...只是社区提供的picgo包里没有description描述罢了。
