### ISSUE TITLE
功能请求：关联本地文件夹，自动上传其中的图片到图床

### ISSUE THREAD

**Issue by xpsair** [Molunerfinn/PicGo#64]
## 问题类型

Feature Request

## PicGo的相关信息

macOS High Sierra 10.13.4
PicGo version 1.5.1

## 问题重现

null

## 功能请求

翻了一下已经发的issue，好像没有看到这个功能的issue :)

macOS或者Windows里的截图工具（比如jietu和Snipaste），大多有截图后自动把图片存到指定的文件夹的功能，但有时候又需要清理文件夹删掉这些图。

**不成熟的建议：设置PicGo与本地的某个文件夹进行关联，实现：**

1. PicGo可以自动地上传该文件内的图片；
2. 上传时PicGo根据当前使用的图床自动忽略已经上传的同名图片；

这样可以：
1. 自动保存截图的文件夹可以成为PicGo上传这些截图到图床的中转站；
2. PicGo又成为使用这些截图的一个窗口、提升PicGo的使用体验。

---

**Comment by Molunerfinn** [comment]
实现自动上传的限制条件会很多，PicGo也不是作为一个同步盘的存在。

不过可以实现手动指定文件夹上传图片。不过这个功能应该不会放在PicGo主体。可以交由插件实现。

PicGo的使用初衷是我在写文章的时候，需要贴图，即穿即用。而非仅用于图片上传。
