### ISSUE TITLE
相册能否支持同步

### ISSUE THREAD

**Issue by AlgerFan** [Molunerfinn/PicGo#641]
**声明：我已经仔细看过 [文档](https://picgo.github.io/PicGo-Doc/)、[FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)、和搜索过已经关闭的 [issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed) 后依然没有找到答案，所以才发了一个新的 issue。**

## PicGo 的相关信息

2.3.beta4 Windows、Android

## 功能请求

1.相册能否支持同步，便于多设备切换
2.相册能否支持删除七牛云、阿里云的图片
3.相册能否支持拉取七牛云、阿里云的图片

最后非常感谢作者这么好用的工具😁😁

**Comment by Molunerfinn** [comment]
针对某个图床的同步，是不会做的。具体看，有的图床插件已经实现了：

![image](https://user-images.githubusercontent.com/12621342/112088477-dbaaf180-8bca-11eb-879d-395fb5f764af.png)

同步相册本身，这个功能会在后续提供一个官方的同步插件来实现。

**Comment by AlgerFan** [comment]
> 针对某个图床的同步，是不会做的。具体看，有的图床插件已经实现了：
> 
> ![image](https://user-images.githubusercontent.com/12621342/112088477-dbaaf180-8bca-11eb-879d-395fb5f764af.png)
> 
> 同步相册本身，这个功能会在后续提供一个官方的同步插件来实现。

了解了，感谢
