### ISSUE TITLE
windows10打不开，配置了环境变量，任务栏和任务管理器都没有，删过data.json（打开picgo又自动生成了）仍然没有反应，有后台进程，快捷键上传虽是失败但有反应，有后台进程，下载的是exe文件，不知道哪里出错

### ISSUE THREAD

**Issue by wxprogrambeta** [Molunerfinn/PicGo#642]
**声明：我已经仔细看过 [文档](https://picgo.github.io/PicGo-Doc/)、[FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)、和搜索过已经关闭的 [issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed) 后依然没有找到答案，所以才发了一个新的 issue。**

## 功能请求

---

**Comment by Molunerfinn** [comment]
![image](https://user-images.githubusercontent.com/12621342/115903226-e987b700-a495-11eb-8df3-cca09bbf0983.png)
