### ISSUE TITLE
【功能请求】能否增加对IPFS文件系统的支持

### ISSUE THREAD

**Issue by whyjxz14** [Molunerfinn/PicGo#646]
**声明：我已经仔细看过 [文档](https://picgo.github.io/PicGo-Doc/)、[FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)、和搜索过已经关闭的 [issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed) 后依然没有找到答案，所以才发了一个新的 issue。**

## 问题类型

Feature Request

## 功能请求

---
能否增加对IPFS文件系统的支持？
https://ipfs.io/
https://webui.ipfs.io/#/welcome

**Comment by Molunerfinn** [comment]
![image](https://user-images.githubusercontent.com/12621342/113102425-9c1a8000-9230-11eb-8480-6334a64559b0.png)
去插件讨论的issue里发，没准有开发者感兴趣能实现。
