### ISSUE TITLE
添加阿里云OSS Bucket读写访问权限选项  默认获取的图片是共有的 希望获取私有的

### ISSUE THREAD

**Issue by 1322739583** [Molunerfinn/PicGo#649]
## 功能请求
PicGo只支持获取公共读写访问权限吗？阿里云默认的Bucket权限控制是private，获取到的图片访问路径是类似这样的
https://pics-note.oss-cn-hangzhou.aliyuncs.com/xxx/xxx.jpg?Expires=xxx&OSSAccessKeyId=TMP.3Kfc7WmLFo2RgnW1hjX8exWZktiMZFgMpVtTr5Hgjxxx4S3BBa8qBJDSM1iJHHZ5TGwuUThXqVsJwDfN4o7&Signature=sLNbt6HcXxxxCjEOIieCVzdVbI%3D

PicGo默认获取阿里云默认的Bucket权限控制是public的。获取到的图片访问路径是类似这样的
https://pics-note.oss-cn-hangzhou.aliyuncs.com/xxx/xxx.jpg

希望添加配置选项，返回的图片路径是私有格式的。

**Comment by Molunerfinn** [comment]
图床的作用是公开访问...

如果有特殊需求，可以用插件实现。

**Comment by 1322739583** [comment]
阿里oss  老是警告public有风险，而且默认是private的。如果设成private的，是不是picgo是无法获取到那个private图片链接的？因为在typora里面即使是private也是可以显示图片的，还有如果在csdn里面写博客，csdn会将图片转到自己的服务器上。并不存在private就不能访问的问题。使用图床最主要的用途是在typora里面写笔记的时候可以一键上传图片，我用的是core 版本的picgo。并不需要相册。我主要疑问的是阿里OSS public到底是不是有风险。。。

**Comment by Molunerfinn** [comment]
> 阿里oss 老是警告public有风险，而且默认是private的。如果设成private的，是不是picgo是无法获取到那个private图片链接的？因为在typora里面即使是private也是可以显示图片的，还有如果在csdn里面写博客，csdn会将图片转到自己的服务器上。并不存在private就不能访问的问题。使用图床最主要的用途是在typora里面写笔记的时候可以一键上传图片，我用的是core 版本的picgo。并不需要相册。我主要疑问的是阿里OSS public到底是不是有风险。。。

private链接通常是有失效时间的，就算当下可以访问，未来的某个时间也会无法访问。

![image](https://user-images.githubusercontent.com/12621342/113507498-6f8e9d00-957d-11eb-8cb4-2e9d345182d9.png)


阿里云的警告主要是基于对文件的保护，怕你的文件被别人非法获取，因为使用阿里云oss并不一定只是拿来当做图床。但是如果是用来当做图床，自然是需要public权限的。建议设置一个bucket用于public权限，只用来当做图床即可。

**Comment by 1322739583** [comment]
好的 谢谢

**Comment by CEastWind** [comment]
> > 阿里oss 老是警告public有风险，而且默认是private的。如果设成private的，是不是picgo是无法获取到那个private图片链接的？因为在typora里面即使是private也是可以显示图片的，还有如果在csdn里面写博客，csdn会将图片转到自己的服务器上。并不存在private就不能访问的问题。使用图床最主要的用途是在typora里面写笔记的时候可以一键上传图片，我用的是core 版本的picgo。并不需要相册。我主要疑问的是阿里OSS public到底是不是有风险。。。
> 
> private链接通常是有失效时间的，就算当下可以访问，未来的某个时间也会无法访问。
> 
> ![image](https://user-images.githubusercontent.com/12621342/113507498-6f8e9d00-957d-11eb-8cb4-2e9d345182d9.png)
> 
> 阿里云的警告主要是基于对文件的保护，怕你的文件被别人非法获取，因为使用阿里云oss并不一定只是拿来当做图床。但是如果是用来当做图床，自然是需要public权限的。建议设置一个bucket用于public权限，只用来当做图床即可。

请问，如果使用阿里OSS来做图床，怎么避免流量被盗用呢？
- 设为public-read，那公网可以随便访问了呀。
- 即使设置了防盗链Referer，伪造Referer也不是什么难事呀。
- 设置为private，返回一个有过期时间的链接，但是浏览我网站的人也能看到这个链接，也能在短时间内盗用我的图片流量呀。
我想来想去想不出解决方案
