### ISSUE TITLE
有考虑过把简书当图床用么?

### ISSUE THREAD

**Issue by Tarhyru** [Molunerfinn/PicGo#65]
问题类型
Feature Request

PicGo的相关信息
1.5.1 、win10

问题重现
功能请求
如题
在简书上写东西的时候发现它的图片上传非常好用...
我经常新建不公开的文章存图片当图床用..
看到既然有把微博当图床用的..
一直奇怪为什么没人把简书当图床用....

**Comment by Molunerfinn** [comment]
并不是所有能上传图片的平台都能用来做图床。这涉及到很多问题。
1. 图片外链是否合规，以及如果把其他平台的图片放在另外的平台会产生一个盗链的问题。
2. 有没有提供官方的api供第三方软件来上传图片。

针对以上的问题，微博图床现在是比较暧昧的状态，目前市面上占有率比较高而微博也并未做出限制故而加入了微博图床。其他的图床均是在合理合规，采用官方api的情况下加入的。所以并不能因为某个平台能上传图片就应该为其制作图床。

如果有兴趣，PicGo2.0版本将会开发插件系统。届时可以自行开发想要的图床即可。
