### ISSUE TITLE
希望可以加入对Gitee作为图床的支持，而不用通过安装插件。目前通过插件，用Gitee作为图床，无法上传成功，但是GitHub是可以的。

### ISSUE THREAD

**Issue by Arvin-Chan** [Molunerfinn/PicGo#650]
**声明：我已经仔细看过 [文档](https://picgo.github.io/PicGo-Doc/)、[FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)、和搜索过已经关闭的 [issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed) 后依然没有找到答案，所以才发了一个新的 issue。**

## 功能请求

---

**Comment by Molunerfinn** [comment]
gitee无法上传成功请自行去gitee插件仓库询问。

你真的仔细看过文档么？
![image](https://user-images.githubusercontent.com/12621342/113958149-29725b80-9853-11eb-9919-03f63cd8fed5.png)
