### ISSUE TITLE
开发环境启动一直报错误

### ISSUE THREAD

**Issue by zWingz** [Molunerfinn/PicGo#653]
![image](https://user-images.githubusercontent.com/13031838/114393160-4b117100-9bcc-11eb-9eea-9d23b3d0156a.png)
搜了下似乎是`electron-devtools-installer`的问题
 但项目也没使用到

**Comment by Molunerfinn** [comment]
没遇到过，你是用yarn还是npm装的依赖，建议用yarn装，之前有人用npm装也有问题

**Comment by zWingz** [comment]
是用yarn安装的

**Comment by JellyP** [comment]
同样遇到了这个问题，你这里解决了吗




> ![image](https://user-images.githubusercontent.com/13031838/114393160-4b117100-9bcc-11eb-9eea-9d23b3d0156a.png)
> 搜了下似乎是`electron-devtools-installer`的问题
> 但项目也没使用到

**Comment by Molunerfinn** [comment]
我这边近期会看看是啥原因

**Comment by Molunerfinn** [comment]
上游issue：https://github.com/nklayman/vue-cli-plugin-electron-builder/issues/1229#issuecomment-774633022

可以参考使用。

**Comment by Molunerfinn** [comment]
更新一下dev分支，重新yarn一下应该可以了。
