### ISSUE TITLE
希望 M1 Macbook 能支持！

### ISSUE THREAD

**Issue by Mandule** [Molunerfinn/PicGo#654]

**Comment by Molunerfinn** [comment]
M1的支持需要更新electron版本，目前这会造成一些插件不兼容的情况。会在2.3版本加入版本号判断的机制，预计2.4的时候能支持M1 Macbook

**Comment by Mandule** [comment]
我好像安装了最新版的beta5的版本，转译运行的，期待原生支持！

**Comment by Molunerfinn** [comment]
> 我好像安装了最新版的beta5的版本，转译运行的，期待原生支持！

是的，目前M1只能走罗斯塔转译

**Comment by Mandule** [comment]
后面2.4如果支持的话，会自动更新，还是要重新安装一下

**Comment by Molunerfinn** [comment]
需要重新安装

**Comment by Mandule** [comment]
您好，我这里遇到个问题，gitee做图库，稍微大一点的图上传后，markdown就显示不出来了，是gitee的问题吗

**Comment by Molunerfinn** [comment]
> 您好，我这里遇到个问题，gitee做图库，稍微大一点的图上传后，markdown就显示不出来了，是gitee的问题吗

gitee只支持1M以内的图片。

**Comment by chihokyo** [comment]
M1芯片。版本2.3.0 Beta6。上传图片失败。
日志如下。
`
-------Error Stack End------- 
2021-06-13 22:48:17 [PicGo ERROR] 
------Error Stack Begin------
StatusCodeError: 404 - {"message":"Not Found","documentation_url":"https://docs.github.com/rest"}
    at new StatusCodeError (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/request-promise-core/lib/errors.js:32:15)
    at Request.plumbing.callback (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/request-promise-core/lib/plumbing.js:104:33)
    at Request.RP$callback [as _callback] (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at Request.self.callback (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/request/request.js:185:22)
    at Request.emit (events.js:200:13)
    at Request.<anonymous> (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/request/request.js:1161:10)
    at Request.emit (events.js:200:13)
    at IncomingMessage.<anonymous> (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:288:20)
    at IncomingMessage.emit (events.js:205:15)
-------Error Stack End------- 
`

**Comment by Molunerfinn** [comment]
> M1芯片。版本2.3.0 Beta6。上传图片失败。
> 日志如下。
> `-------Error Stack End------- 2021-06-13 22:48:17 [PicGo ERROR] ------Error Stack Begin------ StatusCodeError: 404 - {"message":"Not Found","documentation_url":"https://docs.github.com/rest"} at new StatusCodeError (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/request-promise-core/lib/errors.js:32:15) at Request.plumbing.callback (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/request-promise-core/lib/plumbing.js:104:33) at Request.RP$callback [as _callback] (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/request-promise-core/lib/plumbing.js:46:31) at Request.self.callback (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/request/request.js:185:22) at Request.emit (events.js:200:13) at Request.<anonymous> (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/request/request.js:1161:10) at Request.emit (events.js:200:13) at IncomingMessage.<anonymous> (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/request/request.js:1083:12) at Object.onceWrapper (events.js:288:20) at IncomingMessage.emit (events.js:205:15) -------Error Stack End------- `

你这个是自己配置错了兄弟。好好看看FAQ\ISSUE和文档吧。

**Comment by chihokyo** [comment]
> > M1芯片。版本2.3.0 Beta6。上传图片失败。
> > 日志如下。
> > `-------Error Stack End------- 2021-06-13 22:48:17 [PicGo ERROR] ------Error Stack Begin------ StatusCodeError: 404 - {"message":"Not Found","documentation_url":"https://docs.github.com/rest"} at new StatusCodeError (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/request-promise-core/lib/errors.js:32:15) at Request.plumbing.callback (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/request-promise-core/lib/plumbing.js:104:33) at Request.RP$callback [as _callback] (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/request-promise-core/lib/plumbing.js:46:31) at Request.self.callback (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/request/request.js:185:22) at Request.emit (events.js:200:13) at Request.<anonymous> (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/request/request.js:1161:10) at Request.emit (events.js:200:13) at IncomingMessage.<anonymous> (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/request/request.js:1083:12) at Object.onceWrapper (events.js:288:20) at IncomingMessage.emit (events.js:205:15) -------Error Stack End------- `
> 
> 你这个是自己配置错了兄弟。好好看看FAQ\ISSUE和文档吧。

谢谢提醒！因为在原来mac正常使用，今天第一次在m1配置。还以为是不兼容，后来看了一下FAQ顺利解决了。谢谢

**Comment by lllllmaster-lulllll** [comment]
> > > M1芯片。版本2.3.0 Beta6。上传图片失败。
> > > 日志如下。
> > > `-------Error Stack End------- 2021-06-13 22:48:17 [PicGo ERROR] ------Error Stack Begin------ StatusCodeError: 404 - {"message":"Not Found","documentation_url":"https://docs.github.com/rest"} at new StatusCodeError (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/request-promise-core/lib/errors.js:32:15) at Request.plumbing.callback (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/request-promise-core/lib/plumbing.js:104:33) at Request.RP$callback [as _callback] (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/request-promise-core/lib/plumbing.js:46:31) at Request.self.callback (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/request/request.js:185:22) at Request.emit (events.js:200:13) at Request.<anonymous> (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/request/request.js:1161:10) at Request.emit (events.js:200:13) at IncomingMessage.<anonymous> (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/request/request.js:1083:12) at Object.onceWrapper (events.js:288:20) at IncomingMessage.emit (events.js:205:15) -------Error Stack End------- `
> > 
> > 
> > 你这个是自己配置错了兄弟。好好看看FAQ\ISSUE和文档吧。
> 
> 谢谢提醒！因为在原来mac正常使用，今天第一次在m1配置。还以为是不兼容，后来看了一下FAQ顺利解决了。谢谢
你好，能给我说一下你是怎么解决的吗
我都配了好几天看了，就是配不通

**Comment by mapxn** [comment]
期待一下

**Comment by xnng** [comment]
非常期待，一直常驻运行此 app，适配 m1 后应该能更省电

**Comment by Molunerfinn** [comment]
M1可以更新2.3.1-beta.2的arm64构建版本了
https://github.com/Molunerfinn/PicGo/releases/tag/v2.3.1-beta.2

**Comment by kamusis** [comment]
API是不是多返回了上传的原始文件名？之前在Obsidian里面一直用[Image autoupload plugin](https://github.com/renmu123/obsidian-image-auto-upload-plugin)，今天升级了2.3.1-beta2-arm64，出现了一些问题。不确认是autoupload插件的问题，还是PicGo的问题。
我在autoupload那边提了issue：https://github.com/renmu123/obsidian-image-auto-upload-plugin/issues/13

**Comment by Molunerfinn** [comment]
> API是不是多返回了上传的原始文件名？之前在Obsidian里面一直用[Image autoupload plugin](https://github.com/renmu123/obsidian-image-auto-upload-plugin)，今天升级了2.3.1-beta2-arm64，出现了一些问题。不确认是autoupload插件的问题，还是PicGo的问题。
> 
> 我在autoupload那边提了issue：https://github.com/renmu123/obsidian-image-auto-upload-plugin/issues/13
> 
> 

没有，只返回链接

**Comment by qulingyuan** [comment]
M1 pro上安装 2.3.1-beta.2的arm64构建版本出现如下错误
![image](https://user-images.githubusercontent.com/37199981/148622323-0b52d618-f9f2-440e-b7e8-e0ee06346ae8.png)

**Comment by kamusis** [comment]
> 您好，反馈一下： MacBook Air (M1, 2020) Version 12.2 (21D48) 无法打开arm64的版本，x64通过转译可以正常使用
> 
> [MacBook Air M1 截图](https://s6.jpg.cm/2022/01/22/LpR3pS.png)

sudo xattr -r -d com.apple.quarantine /Applications/PicGo.app
再重新打开即可

**Comment by ajsdhfb** [comment]
> > 您好，反馈一下： MacBook Air (M1, 2020) Version 12.2 (21D48) 无法打开arm64的版本，x64通过转译可以正常使用
> > [MacBook Air M1 截图](https://s6.jpg.cm/2022/01/22/LpR3pS.png)
> 
> ```
> sudo xattr -r -d com.apple.quarantine /Applications/PicGo.app
> ```
> 
> 再重新打开即可

成功打开了，谢谢，正在试用中

**Comment by constown** [comment]
> > 您好，反馈一下： MacBook Air (M1, 2020) Version 12.2 (21D48) 无法打开arm64的版本，x64通过转译可以正常使用
> > [MacBook Air M1 截图](https://s6.jpg.cm/2022/01/22/LpR3pS.png)
> 
> ```
> sudo xattr -r -d com.apple.quarantine /Applications/PicGo.app
> ```
> 
> 再重新打开即可

![image](https://user-images.githubusercontent.com/50108901/153158322-70b01994-6c0d-4b34-977c-2249917ea5fd.png)
使用这个命令后可以打开了，但是是空白的

**Comment by constown** [comment]
> > > 您好，反馈一下： MacBook Air (M1, 2020) Version 12.2 (21D48) 无法打开arm64的版本，x64通过转译可以正常使用
> > > [MacBook Air M1 截图](https://s6.jpg.cm/2022/01/22/LpR3pS.png)
> > 
> > 
> > ```
> > sudo xattr -r -d com.apple.quarantine /Applications/PicGo.app
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 再重新打开即可
> 
> ![image](https://user-images.githubusercontent.com/50108901/153158322-70b01994-6c0d-4b34-977c-2249917ea5fd.png) 使用这个命令后可以打开了，但是是空白的

重启了一下电脑好了

**Comment by ChestnutQiang** [comment]
m1 电脑，现在用 最新的 beta 版本[2.3.1-beta.2](https://github.com/Molunerfinn/PicGo/releases/tag/v2.3.1-beta.2) 和 typora 适配出问题了。 当上传好图片后，不能把返回的链接复制到剪切板，导致 typora 替换这个链接时候，剪切板还是图片，就会导致上传成功了，然后 typora 替换失败了。 从效果上看，应该是 typora 从剪切板再去拿这个 url 的时候，发现是图片就想再插入这个图片。

**Comment by ischenxin** [comment]
最新版 2.3.1 安装后无法打开
![image](https://user-images.githubusercontent.com/89346248/201566757-977cb6bf-bbe5-494f-b128-9dfd6dfdf487.png)

**Comment by VegeBun-csj** [comment]
m1 pro，我下载每次都是已经损坏，咋回事，装不上

**Comment by kamusis** [comment]
> m1 pro，我下载每次都是已经损坏，咋回事，装不上

```
sudo xattr -r -d com.apple.quarantine /Applications/PicGo.app
```

**Comment by beyondlesliezl** [comment]
> > m1 pro，我下载每次都是已经损坏，咋回事，装不上
> 
> ```
> sudo xattr -r -d com.apple.quarantine /Applications/PicGo.app
> ```

我使用了这个命令，但是这个命令有错误：
```
usage: xattr [-slz] file [file ...]
       xattr -p [-slz] attr_name file [file ...]
       xattr -w [-sz] attr_name attr_value file [file ...]
       xattr -d [-s] attr_name file [file ...]
       xattr -c [-s] file [file ...]

The first form lists the names of all xattrs on the given file(s).
The second form (-p) prints the value of the xattr attr_name.
The third form (-w) sets the value of the xattr attr_name to attr_value.
The fourth form (-d) deletes the xattr attr_name.
The fifth form (-c) deletes (clears) all xattrs.

options:
  -h: print this help
  -s: act on symbolic links themselves rather than their targets
  -l: print long format (attr_name: attr_value)
  -z: compress or decompress (if compressed) attribute value in zip format
```

**Comment by kamusis** [comment]
> 我使用了这个命令，但是这个命令有错误：

在我的macOS上的这个命令是没有报错的，能否给出你完整的报错截图？有没有可能你的命令没有输入正确？

**Comment by beyondlesliezl** [comment]
> > 我使用了这个命令，但是这个命令有错误：
> 
> 在我的macOS上的这个命令是没有报错的，能否给出你完整的报错截图？有没有可能你的命令没有输入正确？

不好意思，我已经卸载了，现在在使用piclist。感谢您的回复。
