### ISSUE TITLE
关于删除图片功能改进，以及一个问题

### ISSUE THREAD

**Issue by birdkyle7918** [Molunerfinn/PicGo#656]
**声明：我已经仔细看过 [文档](https://picgo.github.io/PicGo-Doc/)、[FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)、和搜索过已经关闭的 [issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed) 后依然没有找到答案，所以才发了一个新的 issue。**

## PicGo 的相关信息
最新版本 PicGo，MacOS 系统，使用 GitHub 图床。

## 功能请求
在 PicGo 的相册中点击删除图片，并不会在图床中删除图片，希望得到改进，同步删除图床中的图片。

## 问题
当我上传了一张图片，假设叫 test.png ，然后在图床中删除了该图片，之后上传另一张不同的图片（但是文件名仍然是 test.png），那么图床中依然是之前的那张图片，而不是新照片。

**Comment by Molunerfinn** [comment]
1. githubPlus插件能支持同步删除。本体不支持同步删除在FAQ里已经说明了。
2. 这是github的锅跟picgo没关系。

**Comment by Molunerfinn** [comment]
如果使用github作为图床，就建议不要上传同名文件。
