### ISSUE TITLE
无法使用 cli 来进行图片的上传

### ISSUE THREAD

**Issue by renmu123** [Molunerfinn/PicGo#657]
**声明：我已经仔细看过 [文档](https://picgo.github.io/PicGo-Doc/)、[FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)、和搜索过已经关闭的 [issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed) 后依然没有找到答案，所以才发了一个新的 issue。**

## 问题类型
Bug Report

## PicGo 的相关信息

版本：2.3.0-beta5
系统：Win10

## 问题重现
调用 xx./PicGo.exe upload image.png 上传图片失败，日志文件中无任何报错

![image](https://user-images.githubusercontent.com/26896790/115707683-aba96680-a3a1-11eb-9e97-fa96955f4164.png)

**Comment by Molunerfinn** [comment]
你命令行里没打upload吧
![image](https://user-images.githubusercontent.com/12621342/115708940-3179e180-a3a3-11eb-8990-71fdcd5e0822.png)

**Comment by renmu123** [comment]
抱歉，图上错了
![image](https://user-images.githubusercontent.com/26896790/115709852-44d97c80-a3a4-11eb-80d9-bc2306659160.png)

**Comment by Molunerfinn** [comment]
你是在开启picgo的状态下运行命令的，还是在没有开启picgo的状态下运行命令的？

如果在开启picgo的状态下运行命令，是不会在console里看到输出的

**Comment by renmu123** [comment]
我是在开启 picgo 的时候运行命令行的，图片未上传成功，且日志无任何记录。

我刚测试了一下在关闭 picgo 时候运行命令，picgo被唤醒，console 有输出，有日志，**图像成功被上传**

**Comment by Molunerfinn** [comment]
> 我是在开启 picgo 的时候运行命令行的，图片未上传成功，且日志无任何记录。
> 
> 我刚测试了一下在关闭 picgo 时候运行命令，picgo被唤醒，console 有输出，有日志，**图像成功被上传**

我理解未成功上传其实是没有反应？我这边测了一下mac下是正常的（不管有没有开启picgo运行cli命令）。回头看看是不是windows的问题

**Comment by Molunerfinn** [comment]
找到bug了，下个beta版修复
