### ISSUE TITLE
禁用插件后需要重启才能生效

### ISSUE THREAD

**Issue by BurgessX** [Molunerfinn/PicGo#659]
**声明：我已经仔细看过 [文档](https://picgo.github.io/PicGo-Doc/)、[FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)、和搜索过已经关闭的 [issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed) 后依然没有找到答案，所以才发了一个新的 issue。**

## 问题类型

Bug Report

## PicGo 的相关信息

PicGo版本：2.3.0
所在平台：Windows

## 问题重现

禁用插件后需要重启才能生效，同样，启用插件后也需要重启才能生效。我测试的插件是 folder-name 1.0.0，但我估计所有的插件都会出现这个问题。

## 功能请求

其实也不算一个bug，可以像安装或更新插件后提示重启PicGo一样，在用户禁用或启用插件时提示重启即可。或者就在插件设置页面加一行提示文本。

---

**Comment by Molunerfinn** [comment]
beta6版本禁用插件时做了处理，漏掉了启用插件的处理，之后会补上。
这块其实是个bug，先偷懒了一下。理论上可以实现运行时禁用和启用的。
