### ISSUE TITLE
请求添加将相册中照片一次性全部移除的功能

### ISSUE THREAD

**Issue by XSun771** [Molunerfinn/PicGo#663]
**声明：我已经仔细看过 [文档](https://picgo.github.io/PicGo-Doc/)、[FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)、和搜索过已经关闭的 [issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed) 后依然没有找到答案，所以才发了一个新的 issue。**

## 问题类型

Feature Request

## PicGo 的相关信息

Windows 10  PicGo 2.2.2

## 功能请求

“上传区”和“图床设置”中间的“相册”我不怎么用，今天一看已经有很多图片了。我想这个功能反正我也不怎么用，就想一次性删完。但没有这个功能。而在打开多选的前提下，单击图片不是选定而是打开图片，这就导致要一个个选过去并最终达成全选，就要盯着右下角那个小方块去点，时不时点错还弹出图片要关闭，真的很麻烦。希望能添加一次性删除全部图片功能或者在已开启多选的前提下，单击图片即选中，改善选中体验。

最后感谢作者的工作！

---

**Comment by Molunerfinn** [comment]
请更新新版，已经有全选功能
