### ISSUE TITLE
Image upload repeated limit, this image exists at "xxx"

### ISSUE THREAD

**Issue by GarfieldCCC** [Molunerfinn/PicGo#664]
**声明：我已经仔细看过 [文档](https://picgo.github.io/PicGo-Doc/)、[FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)、和搜索过已经关闭的 [issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed) 后依然没有找到答案，所以才发了一个新的 issue。**

## 问题类型

Bug Report 

## PicGo 的相关信息

2.2.2、Windows
## 问题重现

![image](https://user-images.githubusercontent.com/31843721/116371217-c5cdc380-a83d-11eb-8640-da10d1644cbe.png)

## 功能请求

---

**Comment by Molunerfinn** [comment]
smms服务商的提示，跟picgo无关

你这张图片已经上传过了。
