### ISSUE TITLE
github，本地显示失败，但是已经上传到github上

### ISSUE THREAD

**Issue by Win-X** [Molunerfinn/PicGo#667]
![image](https://user-images.githubusercontent.com/58622317/116865991-3b220580-ac3d-11eb-917b-6f20257a8eb0.png)

![image](https://user-images.githubusercontent.com/58622317/116865926-20e82780-ac3d-11eb-941a-0fb857bde49a.png)
状态码为409的时候上传后，typora中的图片路径变为上传后的路径；而为422的时候，typora中的图片路径仍然是本地的tmp文件路径

**Comment by Molunerfinn** [comment]
4xx系列的错误，自己检查吧。422是同名文件错误。

**Comment by Win-X** [comment]
好的，感谢
