### ISSUE TITLE
无法打开Picgo

### ISSUE THREAD

**Issue by xingxing2008** [Molunerfinn/PicGo#668]
**声明：我已经仔细看过 [文档](https://picgo.github.io/PicGo-Doc/)、[FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)、和搜索过已经关闭的 [issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed) 后依然没有找到答案，所以才发了一个新的 issue。**

## 问题类型

 Bug Report 

## PicGo 的相关信息
Windows 1909 Dev版
2.4.3

## 问题重现
一直就是打不开Picgo主界面，（连主界面都没有你让我去哪里找日志
旧版新版都一样，刚开始能用一次，接下来打开都没反应
任务管理器里也看不到picgo的进程，可是我打开了很多次

---

**Comment by Molunerfinn** [comment]
首先没有2.4.3这个版本。其次日志在文档里有告知位置。最后，windows打开picgo之后默认是在右下角任务栏里。打不开之前是否有装过什么插件，比如watermark？如果有，参考之前的issue。

**Comment by xingxing2008** [comment]
> 首先没有2.4.3这个版本。其次日志在文档里有告知位置。最后，windows打开picgo之后默认是在右下角任务栏里。打不开之前是否有装过什么插件，比如watermark？如果有，参考之前的issue。

emmmmm......很早之前的版本了，但是现在重装新版都没用，装过插件，但是右下角没有，打都打不开

**Comment by xingxing2008** [comment]
> 首先没有2.4.3这个版本。其次日志在文档里有告知位置。最后，windows打开picgo之后默认是在右下角任务栏里。打不开之前是否有装过什么插件，比如watermark？如果有，参考之前的issue。

记不清是什么版本了，毕竟打不开

**Comment by Molunerfinn** [comment]
去文档里找配置文件所在的目录，删除目录下的data.json，package.json，package-lock.json，再重开picgo

**Comment by zhou431615** [comment]
我也遇到过这个情况，任务管理器没有进程，但是没有安装过插件，只打成功开过一次。picgo为目前最新的版本2.3.0-beta.6(x64),安装路径为C盘。值得一提的是，在安装这个版本之前，我安装过之前比较低版本，但是这些低版本的一次都没有成功打开过。不知道是不是没有卸载干净，再安装了这个最新版本2.3.0-beta.6,所以运行不了。特此说明。

**Comment by zhou431615** [comment]
我也遇到过这个情况，任务管理器没有进程，但是没有安装过插件，只打成功开过一次。picgo为目前最新的版本2.3.0-beta.6(x64),安装路径为C盘。值得一提的是，在安装这个版本之前，我安装过之前比较低版本，但是这些低版本的一次都没有成功打开过。不知道是不是没有卸载干净，再安装了这个最新版本2.3.0-beta.6,所以运行不了。特此说明。

**Comment by kktt007** [comment]
C:\Users\Administrator\.picgo 和  C:\Users\Administrator\AppData\Roaming\picgo 删除后重装即可
