### ISSUE TITLE
上传网络图片的问题

### ISSUE THREAD

**Issue by notorious-eric** [Molunerfinn/PicGo#669]
**声明：我已经仔细看过 [文档](https://picgo.github.io/PicGo-Doc/)、[FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)、和搜索过已经关闭的 [issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed) 后依然没有找到答案，所以才发了一个新的 issue。**

## 问题类型
Bug Report

## PicGo 的相关信息

PicGo 的版本：2.2.0、所在平台： Windows

## 问题重现

对于网络地址的图片上传失败，上传路径有问题，但不知道如何修改
![image](https://user-images.githubusercontent.com/44058627/117235223-e78c0380-ae58-11eb-8549-7721af89ece6.png)

Error: ENOENT: no such file or directory, open 'D:\Program Files (x86)\picgo\https:\mmbiz.qpic.cn\mmbiz_jpg\KmXPKA19gW8KqUF5T7gedtMRyCHC02YGheond5ReRQWYS7U0aTxDTXHCWPCKbCxWJAPv11ZW8IlGoNsSibak4kg\640?wx_fmt=jpeg&tp=webp&wxfrom=5&wx_lazy=1&wx_co=1'
-------Error Stack End-------

**Comment by Molunerfinn** [comment]
2.2.0不支持网络图片上传。

另外，已经是网络图片了，还需要上传么...

**Comment by Molunerfinn** [comment]
可以更新最新的beta版，理论上是支持网络图片上传的。
