### ISSUE TITLE
Feature Request 能否添加对图片的自动压缩功能和加入阿里云OSS的图床

### ISSUE THREAD

**Issue by songjave** [Molunerfinn/PicGo#67]
## 问题类型
Feature Request

## PicGo的相关信息
v1.5.1 mac

## 功能请求
在本地的图片可能尺寸很大，但是其实用于网页使用和markdown使用却不需要这么大尺寸的图
是否可以考虑加入自动压缩功能，尤其是对使用七牛、腾讯云和又拍这OSS网络存储方案的用户来说是一个福音啊
PS：是否可以考虑加入阿里云OSS的图床

**Comment by Molunerfinn** [comment]
图片压缩这个功能将不会在主体功能里提供。可能会在2.0以插件形式提供。

关于阿里云OSS。这些issue都重复了。https://github.com/Molunerfinn/PicGo/issues/58 https://github.com/Molunerfinn/PicGo/issues/66
