### ISSUE TITLE
您没有权限打开应用

### ISSUE THREAD

**Issue by Numen-fan** [Molunerfinn/PicGo#670]
mac是big sur，下载后提示“您没有权限打开应用”，网上说用upx，按照那个操作了也不行，有人知道如何操作吗？

Thanks。

**Comment by Molunerfinn** [comment]
下dmg安装包。

安装之前运行 `sudo spctl --master-disable`

**Comment by Molunerfinn** [comment]
发issue请按模板发，不然下次直接close，谢谢。

**Comment by Numen-fan** [comment]
谢谢，已解决。


没注意看模板，抱歉。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年5月7日(周五) 中午11:01
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Molunerfinn/PicGo] 您没有权限打开应用 (#670)




 
下dmg安装包。
 
安装之前运行 sudo spctl --master-disable
