### ISSUE TITLE
使用GitHub作为图床，图片名称修改无效

### ISSUE THREAD

**Issue by GanZhiXiong** [Molunerfinn/PicGo#673]
![image](https://user-images.githubusercontent.com/27394631/119295730-21973b00-bc8a-11eb-9387-089a14cc3c33.png)

我使用了jsdelivr CDN，不知道会不会是这个导致的？

**Comment by laoxuai** [comment]
> ![image](https://user-images.githubusercontent.com/27394631/119295730-21973b00-bc8a-11eb-9387-089a14cc3c33.png)
> 
> 我使用了jsdelivr CDN，不知道会不会是这个导致的？

更新下仓库，[https://www.bilibili.com/video/av925644104/](url)

**Comment by GanZhiXiong** [comment]
修改图片URL后，确实有提示“修改图片URL成功”，但是
- 图片新的链接是无法访问的。
- 图片原来的链接却还能访问。
- GitHub中该图片的名称也没有变化。

![image](https://user-images.githubusercontent.com/27394631/120291248-aff86600-c2f5-11eb-89b5-1f2497c953e3.png)

**Comment by Molunerfinn** [comment]
> 修改图片URL后，确实有提示“修改图片URL成功”，但是
> 
> * 图片新的链接是无法访问的。
> * 图片原来的链接却还能访问。
> * GitHub中该图片的名称也没有变化。
> 
> ![image](https://user-images.githubusercontent.com/27394631/120291248-aff86600-c2f5-11eb-89b5-1f2497c953e3.png)

这是自然的，修改的只是PicGo本地图片数据，并不会影响远端。新链接无法访问这应该是你自己修改的问题。原来链接没有影响当然可以继续访问。

**Comment by GanZhiXiong** [comment]
Thank you！

那么删除图片是不是也是仅仅删除了本地图片数据，并不会影响远端（我测试了删除，是这样的）。

能说下为什么只对本地做修改，而不更新到远程呢？



![image](https://user-images.githubusercontent.com/27394631/120293341-be478180-c2f7-11eb-9c31-2d4f40075cc5.png)

**Comment by Molunerfinn** [comment]
> Thank you！
> 
> 那么删除图片是不是也是仅仅删除了本地图片数据，并不会影响远端（我测试了删除，是这样的）。
> 
> 能说下为什么只对本地做修改，而不更新到远程呢？
> 
> ![image](https://user-images.githubusercontent.com/27394631/120293341-be478180-c2f7-11eb-9c31-2d4f40075cc5.png)

https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md

**Comment by GanZhiXiong** [comment]
Good， Thanks!👍
