### ISSUE TITLE
通过剪切板上传的图片可以设置格式吗？

### ISSUE THREAD

**Issue by ma3252788** [Molunerfinn/PicGo#674]
**声明：我已经仔细看过 [文档](https://picgo.github.io/PicGo-Doc/)、[FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)、和搜索过已经关闭的 [issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed) 后依然没有找到答案，所以才发了一个新的 issue。**

## 问题类型

**Feature Request**

## PicGo 的相关信息

PicGo：2.3.0-beta.4
MacOS 10.15.3

## 功能请求

目前剪切板上传的图片貌似默认格式都是png，请问可以设置为jpg吗？因为又拍云对于jpg格式图片支持渐进式加载，所以希望默认采用jpg格式，或者能手动开关也行。

---

**Comment by Molunerfinn** [comment]
暂时不行，脚本限制。

两个点，一个不好切换，第二个暂时不知道怎么样修改。剪贴板脚本跨了三个平台。
