### ISSUE TITLE
相册文件无法删除异常

### ISSUE THREAD

**Issue by listener-He** [Molunerfinn/PicGo#675]
** 相册文件无法删除，点击删除列表出现一个空白项（每次删除都是）**
![image](https://user-images.githubusercontent.com/39252579/119684805-63390900-be77-11eb-9b63-f380482f60ed.png)

**Comment by Molunerfinn** [comment]
什么版本？更新到最新beta版本应该解决了这个问题。

下次发issue请按模板来。

**Comment by Molunerfinn** [comment]
gitee插件有bug，删除会越删越多。新版里不再让插件修改相册了。
