### ISSUE TITLE
增加sm.ms图床的设定自定义域名的功能

### ISSUE THREAD

**Issue by kaino3** [Molunerfinn/PicGo#676]
大佬您好，sm.ms图床的cdn默认的i.loli.net被移动给墙了，希望可以增加一个类似于github设置自定义域名的功能，可以把i.loli.net自定义为域名：https://ooo.0o0.ooo/或者https://s1.momo.moda/这两cdn

**Comment by Molunerfinn** [comment]
未来会考虑实现

**Comment by JensenChie** [comment]
感谢大佬

**Comment by love2wind** [comment]
支持+1

**Comment by Molunerfinn** [comment]
2.3.1-beta.6将会新增一个备用上传域名选项，官方提供的是 `smms.app`，上传后的地址目前看了一下不会被墙。单纯的自定义域名替换我试了一下是会报404的，所以不能直接替换。

<img width="800" alt="image" src="https://user-images.githubusercontent.com/12621342/187010573-676a14da-8c7c-4189-aeee-209bc650d68a.png">
