### ISSUE TITLE
使用gitee插件，建设好仓库后，并配置好picgo相关信息，上传图片没有提示，在日之中看到以下提示

### ISSUE THREAD

**Issue by Eden-Lin** [Molunerfinn/PicGo#678]
**声明：我已经仔细看过 [文档](https://picgo.github.io/PicGo-Doc/)、[FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)、和搜索过已经关闭的 [issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed) 后依然没有找到答案，所以才发了一个新的 issue。**

## 问题类型

Bug Report
## PicGo 的相关信息

2.2.2 Windows
## 问题重现

2021-06-02 12:32:01 [PicGo SUCCESS] 
undefined
2021-06-02 12:35:04 [PicGo SUCCESS] 
undefined

## 功能请求

---

**Comment by Molunerfinn** [comment]
请去你安装的gitee插件仓库提问

**Comment by Eden-Lin** [comment]
确实是gitee插件的问题，切换到老版本就好了。感谢！
