### ISSUE TITLE
上传图片至GitHub图床失败

### ISSUE THREAD

**Issue by InkDP** [Molunerfinn/PicGo#679]
**声明：我已经仔细看过 [文档](https://picgo.github.io/PicGo-Doc/)、[FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)、和搜索过已经关闭的 [issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed) 后依然没有找到答案，所以才发了一个新的 issue。**

## 问题类型

BUG
## PicGo 的相关信息

Mac
## 问题重现

![image](https://user-images.githubusercontent.com/23192332/120994969-92287680-c7b7-11eb-9e6b-bcce2d92f41b.png)

**Comment by schrodingercatss** [comment]
同样遇到了该问题，无法正常使用github图床，环境：win10专业版系统。
