### ISSUE TITLE
Release出发布的exe下载包无法直接下载

### ISSUE THREAD

**Issue by RuikangSun** [Molunerfinn/PicGo#685]
**声明：我已经仔细看过 [文档](https://picgo.github.io/PicGo-Doc/)、[FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)、和搜索过已经关闭的 [issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed) 后依然没有找到答案，所以才发了一个新的 issue。**

## 问题类型

https://github.com/Molunerfinn/PicGo/releases/download/v2.3.0-beta.6/PicGo-Setup-2.3.0-beta.6.exe 此处的下载链接由于命名方式为PicGo-Setup-2.3.0-beta.**6.exe**，会被系统默认为part文件，无法正确地直接下载。
![firefox_XNe1yN7ZPH.png](https://i.loli.net/2021/06/23/SEjF9GbKJcDgZPh.png)

## PicGo 的相关信息

https://github.com/Molunerfinn/PicGo/releases/tag/v2.3.0-beta.6

## 问题重现

见截图：
![firefox_XNe1yN7ZPH.png](https://i.loli.net/2021/06/23/SEjF9GbKJcDgZPh.png)

## 功能请求

建议修改release命名方式以避免这种问题。

---

**Comment by Molunerfinn** [comment]
这是你下载器的问题吧，为啥我的windows10 + chrome就不会呢

**Comment by Molunerfinn** [comment]
在下载的时候，其实是可以改最终落地的文件名的，我理解这个不应该是PicGo这边来处理。

**Comment by RuikangSun** [comment]
> 
> 
> 这是你下载器的问题吧，为啥我的windows10 + chrome就不会呢

应该不是下载器的问题。我这里是Win10 + Firefox，会出现图示错误。这应该是最终发布的exe文件命名的问题，猜测beta后面的阿拉伯数字版本号“6”引起了如此问题。最好还是改进一下发布文件的命名方式。

**Comment by RuikangSun** [comment]
> 
> 
> 在下载的时候，其实是可以改最终落地的文件名的，我理解这个不应该是PicGo这边来处理。

在Firefox里，点击下载后，还未开始下载就会出现这个问题。因此我觉得应该是服务端而非用户端的问题。

**Comment by RuikangSun** [comment]
我又测试了一下，直接访问 https://github.com/Molunerfinn/PicGo/releases/download/v2.3.0-beta.6/PicGo-Setup-2.3.0-beta.6.exe 一切正常，然而在release界面下下载该文件就会出现这个问题。

**Comment by Molunerfinn** [comment]
> > 在下载的时候，其实是可以改最终落地的文件名的，我理解这个不应该是PicGo这边来处理。
> 
> 在Firefox里，点击下载后，还未开始下载就会出现这个问题。因此我觉得应该是服务端而非用户端的问题。

这是因为firefox要预先创建一个缓存用来下载文件的。这个应该跟firefox的规则有点关系
