### ISSUE TITLE
快捷键冲突，希望添加快捷键设置？

### ISSUE THREAD

**Issue by Flcwl** [Molunerfinn/PicGo#688]
## 问题类型

- feature

## PicGo 的相关信息

- macos 11
- v2.2.2

## 问题重现

![image](https://user-images.githubusercontent.com/26050644/123639528-e07ae380-d852-11eb-9b9a-a7111ad1b4f6.png)

## 功能请求

当前应用非常好用，所以我是长期挂起的，但是存在和其它 App 快捷键冲突（比如 vscode 的 `cmd + shift + p`），希望能够添加快捷键自定义设置。

如若不然，总是会习惯性按下，然后会导致意外性上传。

**Comment by Molunerfinn** [comment]
更新beta版本，可以修改快捷键。

**Comment by Mickychen00** [comment]
强烈建议修改默认快捷键，对Obsidian和Windows Terminal都有冲突，而且Picgo静默模式下没有提示，真是找了好久才发现是Picgo占用了cmd/cntrl + shift + p这个快捷键。
