### ISSUE TITLE
bug反馈以及功能改进建议

### ISSUE THREAD

**Issue by cooper1x** [Molunerfinn/PicGo#69]
## 问题类型

Bug Report

## PicGo的相关信息

windows10 1803 X64

## 问题重现

相册中的图片不能复制md格式链接，这个出现在第二次复制的时候。（第一次是上传后的默认复制）

## 功能请求
希望可以加入保存设置即时生效的功能。比方说我刚刚设置了一个上传快捷键，然后用了没反应，重启软件后才会生效，希望可以改进！
---

**Comment by Molunerfinn** [comment]
1. 你在上传区选择的链接格式才会是你在相册里点击复制按钮复制的链接格式。
![image](https://user-images.githubusercontent.com/12621342/41638768-a22cf81a-748d-11e8-95c0-d3f78036ec53.png)
2. 设置都是实时更新的。包括上传快捷键。上传快捷键是用来上传剪贴版里的第一张图片。如果剪贴板里没有图片那么就无法上传。

在Windows里，剪贴板的图片只能是这样的方式：

1. 截图后，剪贴板会有一张图片
2. 直接在图片文件上复制是无效的。
![image](https://user-images.githubusercontent.com/12621342/41638832-f6e04cfe-748d-11e8-96c2-d4865732fdea.png)
而是应该打开这张图片，点击复制。这个是electron的限制，PicGo无能为力：
![image](https://user-images.githubusercontent.com/12621342/41638842-01887654-748e-11e8-8ca5-7216599d7eb6.png)
3. 网页上的图片，右键复制
![image](https://user-images.githubusercontent.com/12621342/41638855-13b2d95a-748e-11e8-97a2-5fe90fa5561e.png)

**Comment by cooper1x** [comment]
![](https://ws1.sinaimg.cn/large/61ca8a1egy1fshlwd4iiwg20m70ccwj1.jpg)
是不是因为我没有用管理员身份打开，所以才会这样呢？

**Comment by Molunerfinn** [comment]
@cooper1x 点击那个复制按钮的时候，桌面右下角有没有弹出通知，说复制成功的系统通知框？

这个bug我这边目前无法复现...我身边的Windows机器也都是正常的，你可以试试用管理员身份打开看看？

**Comment by cooper1x** [comment]
我把上传提示的选项开启了，无论是复制还是上传都没有提示呢。刚刚重新用管理员权限打开后，还是不能复制md格式的链接。。。

**Comment by Molunerfinn** [comment]
@cooper1x 这个很奇怪，不知道是否一些权限被限制了。。
正常情况的话，windows在上传成功后+点击复制按钮都会提示这个：

![image](https://user-images.githubusercontent.com/12621342/41640343-021f56a4-7494-11e8-9dc3-5b1e375b7c92.png)

**Comment by cooper1x** [comment]
![](https://ws1.sinaimg.cn/large/61ca8a1egy1fshmdxqp4gj20ab02dt93.jpg)
我把右下角的通知`专注模式`关闭了，有复制成功的提示，但是在记事本中粘贴的还是之前复制的不相关内容。

**Comment by cooper1x** [comment]
今天开机了，发现问题依旧，同时设置的开机自启动也没有生效呢。我的系统是win10 1803 x64，可能是在这个系统上有bug吧。

**Comment by Molunerfinn** [comment]
@cooper1x 已经修复这个bug，欢迎更新v1.6.1体验

**Comment by cooper1x** [comment]
@Molunerfinn 好的，之前的问题解决了，发现了一些新的小bug，不影响使用，但会造成一些困扰，我再开一个issue吧。
