### ISSUE TITLE
macbook现在上传图片经常出现无法上传，无论是选择，拖放，还是url

### ISSUE THREAD

**Issue by gimgoo** [Molunerfinn/PicGo#692]
如题，最近经常无法上传成功，看了下日志，有以下报错：

![image](https://user-images.githubusercontent.com/31849284/124212429-89f6f900-db21-11eb-93de-b707dfebc074.png)

**Comment by Molunerfinn** [comment]
请搜之前的issue

**Comment by isyume** [comment]
历史issue貌似都没有解决的，或者说大佬指明哪一个历史issue有解决方案，谢谢

**Comment by gimgoo** [comment]
别直接关issue行不行，历史issue那么多，像之前这个也没见有解决方案啊

![image](https://user-images.githubusercontent.com/31849284/124213409-148c2800-db23-11eb-967d-85707ac4ce6e.png)

不止一个人反馈过的东西，能不能标个置顶，或者你close的时候指明一下哪个issue

**Comment by Molunerfinn** [comment]
这个报错是网络问题，在FAQ和之前的issue里已经说了无数次了，作为开发者没有那么多时间重复解决同样的问题。历史的issue搜一下就能找到，很多都是用户开启了代理导致的，你不愿意看FAQ不愿意看issue那我还需要好好回答问题么？发issue之前的模板你好好看过了嘛？模板里写了，如果没有按照模板来发issue我是可以直接不回答就关闭的。

![image](https://user-images.githubusercontent.com/12621342/124213878-e9ee9f00-db23-11eb-8246-8bb913cf0978.png)


互相理解互相尊重吧。
