### ISSUE TITLE
七牛云新出的区域,华东-浙江-2,区域idcn-east-2会报错

### ISSUE THREAD

**Issue by aihuahua-522** [Molunerfinn/PicGo#698]
## 问题类型

Feature Request

## PicGo 的相关信息

window上的2.3.0 beta.6

## 问题重现

![image](https://user-images.githubusercontent.com/36809034/125980955-876fd5dd-db3e-44b5-a7cb-3de513b2b251.png)
![image](https://user-images.githubusercontent.com/36809034/125981106-cf181cb8-85cb-4bf6-8227-ae9737592c7f.png)
更换为其他区域正常

## 功能请求

官方文档说的是目前仅支持分片上传v2

---

**Comment by Molunerfinn** [comment]
目前七牛的上传器还没支持到分片上传v2。后续有时间了再补充一下。

**Comment by Molunerfinn** [comment]
集中到 https://github.com/Molunerfinn/PicGo/issues/863 处理
