### ISSUE TITLE
没有问题,特地来感谢的🙏!

### ISSUE THREAD

**Issue by xuetengfei** [Molunerfinn/PicGo#7]

**Comment by Molunerfinn** [comment]
哈哈如果对你有帮助我就很开心啦！如果觉得PicGo很棒，可以请我喝杯咖啡哦，PicGo首页有赞助二维码~

**Comment by yangjunfocus** [comment]
你好，请问你是怎么打包mac 的？如何做的自动更新？麻烦大神指教一二！

**Comment by Molunerfinn** [comment]
@yangjunfocus https://molunerfinn.com/tags/Electron-vue/
