### ISSUE TITLE
macbookpro 11.5.1 2019款16寸 安装后，点击图标 没有展示菜单入口，只显示 已上传banner

### ISSUE THREAD

**Issue by rendehu** [Molunerfinn/PicGo#708]
**声明：我已经仔细看过 [文档](https://picgo.github.io/PicGo-Doc/)、[FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)、和搜索过已经关闭的 [issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed) 后依然没有找到答案，所以才发了一个新的 issue。**

## 功能请求

---

**Comment by rendehu** [comment]
![image](https://user-images.githubusercontent.com/65879109/127834422-c5fdb925-f906-4f74-88b8-1dc6be990ee2.png)

**Comment by Molunerfinn** [comment]
右键顶部图标。

**Comment by Molunerfinn** [comment]
文档里已经有写了，回头我补充到FAQ里。
![image](https://user-images.githubusercontent.com/12621342/127834650-8f9a4ee9-905a-4a39-b333-4d77bf40d386.png)
