### ISSUE TITLE
设置无法保存

### ISSUE THREAD

**Issue by coppea** [Molunerfinn/PicGo#710]
picgo版本
2.3.0-beta-7
macos12beta4
设置无法保存，修改后关闭恢复初始
https://636c-cloud1-4g9fhfes4a437ac0-1306584693.tcb.qcloud.la/img/202108042357426.png

**Comment by Molunerfinn** [comment]
问题已知，会在beta.8修复

**Comment by Molunerfinn** [comment]
也可以手动修改配置文件，再重启picgo解决
