### ISSUE TITLE
启动报错：无法定位序数 345

### ISSUE THREAD

**Issue by ifu25** [Molunerfinn/PicGo#711]
**声明：我已经仔细看过 [文档](https://picgo.github.io/PicGo-Doc/)、[FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)、和搜索过已经关闭的 [issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed) 后依然没有找到答案，所以才发了一个新的 issue。**

## 问题类型

bug

## PicGo 的相关信息

windows 2.3.0-beta5

## 问题重现

开机自启动弹出以下错误窗口：
![20210805_085241](https://user-images.githubusercontent.com/5575008/128274421-fd7604f5-2cb3-479f-9271-6bdb7f7fc821.png)

**Comment by Molunerfinn** [comment]
这个是你系统的环境问题了。

参考：https://github.com/snowie2000/mactype/issues/584
