### ISSUE TITLE
插件的设置页不显示(难道是插件没有设置页吗)以及设置页面的选项在重启应用后会不显示打开(安装低版本就好了)

### ISSUE THREAD

**Issue by Violet-VE** [Molunerfinn/PicGo#716]
**声明：我已经仔细看过 [文档](https://picgo.github.io/PicGo-Doc/)、[FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)、和搜索过已经关闭的 [issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed) 后依然没有找到答案，所以才发了一个新的 issue。**

## 问题类型

如题。
![PicGo_Error](https://violet-ve.oss-cn-shanghai.aliyuncs.com/imgs/Temp/picgo%E6%8F%92%E4%BB%B6%E9%94%99%E8%AF%AF.png)
1. 不知道是不是这个插件没有设置的UI。
2. ![picGo_Error2](https://violet-ve.oss-cn-shanghai.aliyuncs.com/imgs/Temp/picGo2Error.png)
  这些设置项会在重启应用后重置到没有打开的状态，但实际是有效果的(如果我改装2.2.2版本就显示正常了)

## PicGo 的相关信息

picgo:2.3.0 Bate7
版本	Windows 11 企业版
版本	21H2
安装日期	‎2021/‎7/‎16
操作系统版本	22000.100
体验	Windows Feature Experience Pack 421.18901.0.3

设备名称	Abyssal-Hunters
处理器	Intel(R) Core(TM) i7-10700K CPU @ 3.80GHz   3.79 GHz
机带 RAM	16.0 GB (15.9 GB 可用)
系统类型	64 位操作系统, 基于 x64 的处理器

## 问题重现

截图在上面。
[点击下载picgo.log](https://violet-ve.oss-cn-shanghai.aliyuncs.com/TxT/Logs/picgo.log)

## 功能请求

检测到剪贴板新增了图片自动弹出上传

---

**Comment by Violet-VE** [comment]
GPU3060loptop

**Comment by Molunerfinn** [comment]
已知问题，https://github.com/Molunerfinn/PicGo/issues/710
