### ISSUE TITLE
传到七牛服务器返回的图片地址不带http://前缀

### ISSUE THREAD

**Issue by nenhall** [Molunerfinn/PicGo#72]
## 问题类型

 Bug Report

## PicGo的相关信息

 Mac

## 问题重现

 上传到七牛后，返回的图片地址不带http://前缀，导致需要手动添加前缀，才能使用

## 功能请求

---

**Comment by Molunerfinn** [comment]
![image](https://user-images.githubusercontent.com/12621342/42363721-32bc5ba6-812b-11e8-9f3b-32accdad816c.png)
请在设置地址里设置好你的url地址。类似于这样：
![image](https://user-images.githubusercontent.com/12621342/42363771-57fcff24-812b-11e8-8919-8e34f7444d65.png)
这不是bug，这个是要求。

**Comment by nenhall** [comment]
@Molunerfinn 谢谢！是我直接复制七牛网站的地址导致的！按你方式，没问题。
