### ISSUE TITLE
软件版本 2.0.3-beta.7,上传到gitee无效

### ISSUE THREAD

**Issue by Gu-Yue-Hu** [Molunerfinn/PicGo#720]
软件版本是beta.7，图床设置为github时没问题，可以正常上传
然后我想图床增加gitee,结果上传不了，也没说 “上传成功”或“上传失败”，就上传区的进度条拉满后，一点反应都没，到gitee上也没看到有上传上去【插件是gitee 2.0.3】
是这个插件已经不支持了？还是怎样呢？  
谢谢！

**Comment by Molunerfinn** [comment]
请去gitee的issue区提问。https://github.com/zhanghuid/picgo-plugin-gitee/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc
