### ISSUE TITLE
2.3.0-beta.7 中通过“HTTP调用上传剪贴板图片”接口得返回值变了

### ISSUE THREAD

**Issue by renmu123** [Molunerfinn/PicGo#721]
**声明：我已经仔细看过 [文档](https://picgo.github.io/PicGo-Doc/)、[FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)、和搜索过已经关闭的 [issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed) 后依然没有找到答案，所以才发了一个新的 issue。**

## 问题类型
Bug Report

## PicGo 的相关信息
Windows 2.3.0-beta.7

## 问题重现
在前一个版本中，上传剪切板中的图片返回值字段为列表，如文档所示:
```
{
  "success": true, // or false
  "result": ["url"]  // 
}
```
而在 Windows 2.3.0-beta.7 版本中，返回值为 string。
![image](https://user-images.githubusercontent.com/26896790/129175795-78b055b5-88ac-45f0-9558-1f2083f0b2be.png)

**Comment by renmu123** [comment]
我开发的某个[编辑器插件](https://github.com/renmu123/obsidian-image-auto-upload-plugin) 强依赖这个功能，这是一个破坏性的更改。

**Comment by Molunerfinn** [comment]
收到反馈，会在beta.8中修复
