### ISSUE TITLE
全新安装插件无法配置

### ISSUE THREAD

**Issue by d-w-x** [Molunerfinn/PicGo#722]
**声明：我已经仔细看过 [文档](https://picgo.github.io/PicGo-Doc/)、[FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)、和搜索过已经关闭的 [issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed) 后依然没有找到答案，所以才发了一个新的 issue。**

## 问题类型

Bug Report

## PicGo 的相关信息

os: win10
version: PicGo-2.3.0-beta.8

## 问题重现

- 卸载当前安装的 picgo；
- 删除 C:\Users\user\AppData\Roaming\picgo 中的所有配置文件；
- 安装 PicGo-2.3.0-beta.8；
- 在插件中搜索任意插件（S3 或者 gitlab-files）
- 点击图床设置->插件对应的图床设置，则如图所示：
  ![无法配置插件](https://user-images.githubusercontent.com/35656321/129671164-347c9568-2d55-42f3-a0f0-6c9776a45b4a.png)
- 手动打开配置文件，写入对应插件的值：
  ![image](https://user-images.githubusercontent.com/35656321/129671303-6875fe81-cc16-4112-9afa-6b1a5bcc927d.png)
- 插件重新可以配置：
  ![image](https://user-images.githubusercontent.com/35656321/129671356-4055649c-6cbd-4d39-90a3-fc182de2297b.png)

## 可能的原因

在安装完成后，没有向配置文件中写入对应的插件配置项，导致读取错误。

全程日志无错误输出。

请问此内容需要插件编写方如何修改还是主程序进行修改？

**Comment by Molunerfinn** [comment]
主程序有问题。如果没找到config会无法显示

https://github.com/Molunerfinn/PicGo/blob/dev/src/renderer/components/ConfigForm.vue#L119

正式版会解决，config会放出来。插件侧也能简单解决：config属性是个函数，在这个函数里，如果没有找到配置可以先写入一个默认配置。
