### ISSUE TITLE
每次升级新版本配置文件都丢失

### ISSUE THREAD

**Issue by ifu25** [Molunerfinn/PicGo#729]
**声明：我已经仔细看过 [文档](https://picgo.github.io/PicGo-Doc/)、[FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)、和搜索过已经关闭的 [issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed) 后依然没有找到答案，所以才发了一个新的 issue。**

## 问题类型

Bug

## PicGo 的相关信息

2.3.0-beta8

## 问题重现

每次升级新版软件，都会造成配置丢失，之前设置的图床都要重新设置一次。

**Comment by Molunerfinn** [comment]
无法复现。请问升级之后是配置文件丢失了还是配置项不见了？可以尝试降级到低版本再安装新版本之后，比对一下前后的data.json

**Comment by ifu25** [comment]
好的，那等我看看能不能找到复现的方法，找到了再来提问。
