### ISSUE TITLE
进度条卡住不动

### ISSUE THREAD

**Issue by zuorichongxian** [Molunerfinn/PicGo#73]
## 问题类型
Bug Report

## PicGo的相关信息
版本 1.5.1 平台 win10

## 问题重现

上传腾讯云cos时进度条一直卡住不动
![tim 20180706154645](https://user-images.githubusercontent.com/24955179/42366675-5ce0828c-8134-11e8-936e-481ff452ea40.png)
 

---

**Comment by Molunerfinn** [comment]
这个代表你的设置出问题了。检查一下你的COS设置吧。尤其注意配置项的那些key啊什么的前后有没有多空格什么的。
