### ISSUE TITLE
安装新插件后重启程序后，对应插件图床设置界面显示空

### ISSUE THREAD

**Issue by kagangtuya-star** [Molunerfinn/PicGo#730]
**声明：我已经仔细看过 [文档](https://picgo.github.io/PicGo-Doc/)、[FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)、和搜索过已经关闭的 [issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed) 后依然没有找到答案，所以才发了一个新的 issue。**

## 问题类型
BUG：安装新插件后重启后，图床设置界面显示为空的，插件为picgo-plugin-gitlab，仅一个插件出现问题，重启系统和程序
，重装软件均无法解决
## PicGo 的相关信息

2.3.0-beta8

## 问题重现
![无配置选项显示](https://raw.githubusercontent.com/kagangtuya-star/picgo1/main/20210823153928.png)

![从插件配置进入仍无显 ](https://raw.githubusercontent.com/kagangtuya-star/picgo1/main/20210823154455.png)

**Comment by Molunerfinn** [comment]
同样的issue：https://github.com/Molunerfinn/PicGo/issues/722#event-5189292116

正式版会解决，目前可以手动在配置文件里配置即可
