### ISSUE TITLE
关于图片连接编码问题

### ISSUE THREAD

**Issue by g8up** [Molunerfinn/PicGo#731]
我在开发自定义插件时发现，相册中，复制的图片连接和编辑弹框中的连接不一致了。
排查发现，复制的链接被 encodeURI()：
https://github.com/Molunerfinn/PicGo/blob/a676c083fe597ac14bbf2aef0c9c13d769d390df/src/universal/utils/pasteTemplate.ts#L22

能否不修改这个链接？
我的情况：
预期的 "&Signature=zHx21zThzHKdNXJzFfpXFv0%2Befg%3D"
被转义成：'&Signature=zHx21zThzHKdNXJzFfpXFv0%252Befg%253D'
导致复制的图片链接失效

**Comment by Molunerfinn** [comment]
这里应该是个bug，因为最终落地的时候已经encode一次了，所以这里复制的时候不需要再encode了

**Comment by Molunerfinn** [comment]
正式版会解决

**Comment by g8up** [comment]
问下，这个 bug 在 [2.4.0-beta.0](https://github.com/Molunerfinn/PicGo/releases/tag/v2.4.0-beta.0) 中修复了吗？
好像跟 https://github.com/Molunerfinn/PicGo/issues/996 有点像。

**Comment by Molunerfinn** [comment]
2.3.1应该就修复了

**Comment by g8up** [comment]
[2.4.0-beta.0](https://github.com/Molunerfinn/PicGo/releases/tag/v2.4.0-beta.0) 中测试发现，复制和修改中的 URL 还是不一致。复制的地址有问题，导致正常无法访问对应图片。编辑框里的没问题。

**Comment by Molunerfinn** [comment]
https://github.com/Molunerfinn/PicGo/commit/6c6f84779aa5cdcc5ebadd49ebc929078116e284

之前删掉了来着，可能是迁移的时候写错了。我回头改一下吧

**Comment by g8up** [comment]
更新到 2.4.0-beta.1，还能复现这个问题。
url中的 `%3D`被转义成了`%253D`

**Comment by Molunerfinn** [comment]
> 更新到 2.4.0-beta.1，还能复现这个问题。
> 
> url中的 `%3D`被转义成了`%253D`

新增了个是否转义的配置项

**Comment by g8up** [comment]
关闭复制转义配置后，符合预期了。感谢！
