### ISSUE TITLE
【bug】七牛云图床上传剪切板图片，程序出现假死

### ISSUE THREAD

**Issue by a8655099449** [Molunerfinn/PicGo#732]
## 问题描述

每次使用七牛云图床上传剪切板图片，程序出现假死1-2分钟

## 复现步骤
1. 使用七牛云图床上传剪切板图片 （点击按钮或者用快捷键都会复现）
2. 查看程序状态

> 实际上传已经成功。地址已经复制到了剪切板，但是程序会假死1-2分钟，随后自动恢复

## 使用环境

版本2.3.0-beta.8

系统 ：win10 64位

本人在多台电脑都出现此问题

**Comment by a8655099449** [comment]
![image](https://user-images.githubusercontent.com/58685483/130546018-d4db455c-a0b2-4e43-90c5-7133f4689ef5.png)

**Comment by Molunerfinn** [comment]
只有七牛会这样还是所有图床都这样

只有beta8会出现还是之前的版本也会

**Comment by a8655099449** [comment]
beta.4也会
这个问题在今年年初就出现了
目前只看到七牛云会，使用默认图床没出现该情况

**Comment by Molunerfinn** [comment]
我在自己的win10机器上无法复现

**Comment by a8655099449** [comment]
> 我在自己的win10机器上无法复现

我刚刚又在一台新的电脑复现了
你可以尝试一下 修改快捷键 -> 使用快键键上传剪切板图片

**Comment by Molunerfinn** [comment]
> > 我在自己的win10机器上无法复现
> 
> 我刚刚又在一台新的电脑复现了 你可以尝试一下 修改快捷键 -> 使用快键键上传剪切板图片

一样的步骤还是没有办法复现mmmm

**Comment by Molunerfinn** [comment]
回头可以更新最新的beta版本，切换剪贴板上传的模式使用内置剪贴板模式，应该能解决问题
