### ISSUE TITLE
【bug】运行后界面黑色，什么都看不见

### ISSUE THREAD

**Issue by a6680** [Molunerfinn/PicGo#733]
## 问题类型
不知道为什么运行PicGo-2.3.0-beta.8.AppImage后界面是黑色的什么都看不见，打开详细窗口也一样，删除.config/picgo和换其它版本也是一样的问题，可以正常点击但是看不见，前几天是可以正常运行的。

![](https://s3.jpg.cm/2021/08/29/IHb2Tz.png)
![](https://s3.jpg.cm/2021/08/29/IHbCdu.png)
## PicGo 的相关信息

PicGo版本：PicGo-2.3.0-beta.8.AppImage
所在平台：amd64 
系统：ubuntu20.04

**Comment by Molunerfinn** [comment]
请提供一下报错日志、配置文件，以及回想是否有安装什么插件导致的。

**Comment by Molunerfinn** [comment]
把配置文件所在目录的package.json也贴上来

**Comment by a6680** [comment]
> 把配置文件所在目录的package.json也贴上来
还没有安装插件，下载后就放一边了。

picgo.log文件

2021-08-29 16:01:18 [PicGo INFO] [PicGo Server] is listening at 36677 
2021-08-29 16:01:18 [PicGo WARN] [PicGo Server] 36677 is busy, trying with port 36678 
2021-08-29 16:01:18 [PicGo INFO] [PicGo Server] is listening at 36678 
2021-08-29 16:19:31 [PicGo INFO] [PicGo Server] shutdown 
2021-08-29 16:36:23 [PicGo INFO] [PicGo Server] is listening at 36677 
2021-08-29 16:36:24 [PicGo WARN] [PicGo Server] 36677 is busy, trying with port 36678 
2021-08-29 16:36:24 [PicGo INFO] [PicGo Server] is listening at 36678 
2021-08-29 16:36:32 [PicGo INFO] [PicGo Server] shutdown 

package.json文件

{"name":"picgo-plugins","description":"picgo-plugins","repository":"https://github.com/Molunerfinn/PicGo-Core","license":"MIT"}

**Comment by Molunerfinn** [comment]
配置文件呢

**Comment by Molunerfinn** [comment]
看起来有个进程已经占用了36677这个端口，可以检查一下是否是picgo的残留进程。

日志上没有什么额外的错误，看不出有什么问题

**Comment by a6680** [comment]
我也想不出什么原因

data.json

{
  "picBed": {
    "current": "smms",
    "uploader": "smms",
    "smms": {
      "token": ""
    }
  },
  "settings": {
    "shortKey": {
      "picgo:upload": {
        "enable": true,
        "key": "CommandOrControl+Shift+P",
        "name": "upload",
        "label": "快捷上传"
      }
    },
    "server": {
      "port": 36677,
      "host": "127.0.0.1",
      "enable": true
    },
    "privacyEnsure": true,
    "showUpdateTip": true
  },
  "picgoPlugins": {},
  "debug": true,
  "PICGO_ENV": "GUI",
  "needReload": false
}

**Comment by Molunerfinn** [comment]
不知道是什么原因无法复现。补充了可以打开调试器的功能，后续可以看看是否是前端界面报错导致的问题

**Comment by JerryC8080** [comment]
+1

**Comment by kktt007** [comment]
我也遇到过,windows和archlinux(仓库软件包没人更新了),然后右击应用重启有机率是好的

**Comment by Molunerfinn** [comment]
近期无更新的反馈，有更新的反馈再 reopen
