### ISSUE TITLE
图片好像被上传到了其他地方

### ISSUE THREAD

**Issue by hitYunhongXu** [Molunerfinn/PicGo#734]
您好，我原本是正常使用picgo将图片传到阿里云上的，但是今天打开后，同意了弹出的隐私策略，再上传图片时，就弹出了以下信息日志：
2021-08-29 22:01:36 [PicGo SUCCESS] 
 https://i.loli.net/2021/08/29/xxx.png  （xxxx为一串字母）
请问是我的图片被上传到别的地方了吗？如果是的话，怎么在该处把文件删除掉呢？

**Comment by Molunerfinn** [comment]
这是上传到了默认的 SM.MS 图床里了。没有提供sm.ms的token的话，上传是匿名的，你不对外提供链接就没有人能找到。

这个应该是你从比较老的版本升级上来导致的问题。可以重新设置一下默认图床为「阿里云」，这样就可以重新上传到阿里云了。
