### ISSUE TITLE
[BUG]When typora using Picgo as Image bed, the "upload all local images" crashed.

### ISSUE THREAD

**Issue by BeBubbled** [Molunerfinn/PicGo#735]
**声明：我已经仔细看过 [文档](https://picgo.github.io/PicGo-Doc/)、[FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)、和搜索过已经关闭的 [issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed) 后依然没有找到答案，所以才发了一个新的 issue。**

## PicGo 的相关信息
PicGo 2.3.8-beta 8 for Mac

## 问题重现
According to the picgo.log, 
I guess:
when the image path or file name contains space, typora would convert " " to html format "%20", then PicGo would not find the image except replace "%20" back to " ".

根据查看Picgo的日志, typora使用"上传所有本地图片"时,如果发现如果图片路径中包含空格, typora将会把空格转义为"%20", 这时Picgo无法找到图片, 若选择单张图片逐一上传, 不会发生这种错误. 此Bug可能需要与typora一同协商 图片路径/文件名称 是否应该包含"%20"
PicGo Log:
<img width="632" alt="Screen Shot 2021-08-30 at 12 41 08 AM" src="https://user-images.githubusercontent.com/57272656/131286266-08d758cc-3364-449e-871c-eb4f676995b5.png">
Typora notification:
<img width="1184" alt="Screen Shot 2021-08-30 at 12 47 44 AM" src="https://user-images.githubusercontent.com/57272656/131286653-3f276ca3-5413-4d98-9177-1b20b34b5d34.png">

出于隐私需要, 图中部分位置打码

**Comment by Molunerfinn** [comment]
这是typora输入的问题

**Comment by BeBubbled** [comment]
> 这是typora输入的问题

 刚刚在win10平台上验证了"文件名包含空格", 当文件名 包含空格, typora导出的图片相对地址会带上%20 导致PicGo无法识别.
在讲文件名中的空格全部剔除后, 上传正常. 
目前准备提交至typora解决这个问题

**Comment by BeBubbled** [comment]
也已提交至typora
[typora/PicGo联动](https://github.com/typora/typora-issues/issues/4629)
