### ISSUE TITLE
希望能支持上传到自定义的服务器

### ISSUE THREAD

**Issue by skyroam** [Molunerfinn/PicGo#736]
**声明：我已经仔细看过 [文档](https://picgo.github.io/PicGo-Doc/)、[FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)、和搜索过已经关闭的 [issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed) 后依然没有找到答案，所以才发了一个新的 issue。**

## 功能请求

希望除了图床之外可以上传到自定义的服务器，这样可以满足对空间的需求
---

**Comment by Molunerfinn** [comment]
已经有该功能的插件
