### ISSUE TITLE
[feature: ] 支持图片名称+时间戳

### ISSUE THREAD

**Issue by willzhang** [Molunerfinn/PicGo#737]
**声明：我已经仔细看过 [文档](https://picgo.github.io/PicGo-Doc/)、[FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)、和搜索过已经关闭的 [issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed) 后依然没有找到答案，所以才发了一个新的 issue。**

## 问题类型

 Feature Request

## PicGo 的相关信息

PicGo 的版本：2.3.0-beat8
所在平台: windows10

## 功能请求

图片名称和时间戳只能二选一，是否能支持默认图片名称然后picgo拼接一个时间戳到默认名称后面，既解决了上传github名称冲突问题，也解决了图片辨识维护问题

![picgo.png](https://i.loli.net/2021/09/01/HmwoB9v8DW371z5.png)

**Comment by Molunerfinn** [comment]
https://github.com/liuwave/picgo-plugin-rename-file
