### ISSUE TITLE
网页端复制图片,typeora上传失败

### ISSUE THREAD

**Issue by rom1c77** [Molunerfinn/PicGo#738]
1. 网页端复制图片,typeora选中图片点击`上传图片`,返回失败, 需要手动 点击 picgo `剪切板图片上传`;
 ![image](https://user-images.githubusercontent.com/14304457/131701681-7b066387-0d5f-4f99-9b5e-24e6a04da4b4.png)

![image](https://user-images.githubusercontent.com/14304457/131701884-9e9d1b8b-2f24-4ff4-ba4a-f2bf2fcc8b10.png)

2. 能否实现在web页面 点击复制图片, 然后在typeora直接粘贴 自动上传到图床?

**Comment by Molunerfinn** [comment]
这个问题是typora的，不是picgo的。
