### ISSUE TITLE
【bug】重命名添加了文件夹目录路径，上传成功后返回图片url不包含文件夹路径。

### ISSUE THREAD

**Issue by allworldg** [Molunerfinn/PicGo#739]
## 问题描述

使用gitee作为图床，上传图片进行重命名时，添加了文件夹作为目录，上传后gitee仓库成功自动创建文件夹并且存储了图片，但是返回的图片url并不含文件夹目录。

## PicGo 的相关信息
PicGo版本：PicGo-Setup-2.3.0-beta.8-x64.exe
所在平台：windows10

## 问题重现
1、上传图片进行重命名，添加存放文件夹目录test。
![image](https://user-images.githubusercontent.com/48782874/132124484-db82a3f4-9934-442b-b754-ce4af94c0a6c.png)
2、上传成功后查看gitee仓库，自动生成test并且图片上传成功。
![image](https://user-images.githubusercontent.com/48782874/132124526-7de2d922-cf63-4aab-ba9d-574c7b5123c3.png)
3、返回的图片url并不包含test这一目录。
![image](https://user-images.githubusercontent.com/48782874/132124558-c0140696-e2f9-4cb4-abb1-bc7fd379e5a3.png)

## 功能请求

---

**Comment by Molunerfinn** [comment]
请去你使用的gitee插件的仓库提问
