### ISSUE TITLE
一个图床设置多个信息

### ISSUE THREAD

**Issue by LeachZhou** [Molunerfinn/PicGo#74]
## 问题类型

Feature Request

## PicGo的相关信息

Windows

## 功能请求

一个图床设置多个信息，我在使用七牛云图床的时候，一个存储空间作为博客图床，一个存储空间作为平时频繁存放东西的空间，因为一个存储空间有限，想多设置几个，不知道这个可不可行

---

**Comment by Molunerfinn** [comment]
目前的架构里无法实现。2.0的插件系统可能可以。
