### ISSUE TITLE
【bug】 mini 界面右键-“打开调试器”，界面异常

### ISSUE THREAD

**Issue by yussuy** [Molunerfinn/PicGo#743]
## 问题类型

Bug Report

## PicGo 的相关信息

PicGo - 2.3.0 Windows 10 
## 问题重现

mini 界面右键-“打开调试器”，将以 mini 窗口大小显示调试，且无法通过 mini 窗口上传图片。通过 windows 右小角打开详细窗口后，再进入 mini 窗口也无法恢复。目前只能通过“重启应用”解决。
![image](https://user-images.githubusercontent.com/13176487/133300646-8815fd6c-1cbc-4842-a773-330239707728.png)
![image](https://user-images.githubusercontent.com/13176487/133300718-114eb84a-423d-4649-8572-7b2958c85b72.png)

## 功能请求

mini窗口右键取消“打开调试器”菜单，或者以详细窗口的调试器样式显示调试器，防止在mini窗口误点。

**Comment by Molunerfinn** [comment]
devtools的默认行为是在当前窗口里打开。可以进主窗口「打开调试器」
![image](https://user-images.githubusercontent.com/12621342/133354280-e2421eeb-844a-4497-8e9d-fb11d4e2d62f.png)
然后选择独立窗口打开
![image](https://user-images.githubusercontent.com/12621342/133354311-ce7fc077-2bcb-4c86-9044-2d2f3e823a58.png)

之后重启PicGo，后续的调试器都会从独立窗口打开了。
