### ISSUE TITLE
一直以来都会有无法上传的问题

### ISSUE THREAD

**Issue by gimgoo** [Molunerfinn/PicGo#746]
如题，家里网络是早就科学上网了的，软路由加二级路由发射wifi，绕过中国大陆模式。经常出现无法上传图片，说什么socket，之前反馈过，说是网络原因，连科学上网绕过中国大陆模式都无法满足github上传了吗？我用terminal使用git上传文件速度都杠杠的。

![image](https://user-images.githubusercontent.com/31849284/134342432-c50ae63b-2a84-465e-9c64-c2676e9b7a32.png)

**Comment by Molunerfinn** [comment]
问题是这个确实是网络问题，无能为力

**Comment by cad342201** [comment]
sm.ms传图显示周限制500张之内，切换sm译码仍旧显示周500张限制，请问大佬这个怎么解决？（新手小白，做兼职遇到的问题）
