### ISSUE TITLE
大佬您好，想请教一点问题，谢谢

### ISSUE THREAD

**Issue by Brannua** [Molunerfinn/PicGo#747]
**声明：我已经仔细看过 [文档](https://picgo.github.io/PicGo-Doc/)、[FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)、和搜索过已经关闭的 [issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed) 后依然没有找到答案，所以才发了一个新的 issue。**

## 问题类型

Feature Request

## PicGo 的相关信息

Linux，typora_0.11.7 + picGo_AppImage_version: 2.3.0 + gitee

## 功能请求

1. 大佬您好，软件很棒，不好意思打扰您一下，平时我书写文档使用 typora，上传图片的方式是使用截图工具直接将截图截取到剪贴板中，ctrl+v直接往typora中粘贴，然后图片就会自动上传；由于我常用 <img> 标签控制图片的大小和位置，所以我自定义了
链接格式，但是当我将剪贴板中的图片直接往 typora 中粘贴上传时，typora 中显示的仍然是标准的 markdown 格式的图片语法，即：![]()，但是我期望直接粘贴到 typora 中的就是我自定义的链接格式，即：<img src="xxx"></img>；虽然我可以点开 picGo 相册再手动复制一下链接，但频繁在 picGo 和 typora 中切换，手动将 ![]() 替换为自定义链接还是稍显麻烦，请问是否有方法满足我的需求？谢谢

2. 是否有方法可以给图片的上传配置多个图床，即一次上传就分发到多个图床（异地容灾），若默认图床由于网络原因失效则可以手动或自动替换为备用图床链接，甚至自动选取网速最快的图床进行图片展示
---

**Comment by Brannua** [comment]
"![]()" => "<img src='xxx'>"

**Comment by Molunerfinn** [comment]
第一个问题，是typora的问题，跟picgo无关。找typora支持。
第二个问题，未来会考虑实现

**Comment by Brannua** [comment]
了解了，谢谢大佬
