### ISSUE TITLE
详细窗口不支持多任务切换？

### ISSUE THREAD

**Issue by JayceLau** [Molunerfinn/PicGo#75]
## 问题类型

Feature Request
## PicGo的相关信息

Version: 1.5.1、Mac
## 功能请求

希望可以在多任务切换窗口中显示PicGo的详细窗口
---

**Comment by Molunerfinn** [comment]
PicGo在mac上是无docker栏而是顶部栏的程序。因为并未注册docker栏，所以它的详细窗口无法在多任务里切换。这个是一开始就做的设计。PicGo一开始在Mac上就是一个顶部栏的程序。只不过为了兼容windows和linux而做了详细窗口。更推荐你用顶部栏拖拽上传以及全局快捷键拖拽上传。详细窗口在初次配置完之后其实就没用啦~

**Comment by JayceLau** [comment]
了解，大道至简！👍
只是配置的时候，可能会去浏览器复制仓库地址，然后发现切不回去。四指上滑进调度中心，选中详细窗口才能继续配置，会有一丢丢顿挫感😔

**Comment by Molunerfinn** [comment]
@JayceLau 这个只会在配置的时候出现。配置完之后将不会有这个问题~多少都会有些牺牲的。比如很多人更不喜欢docker栏有个图标

**Comment by Molunerfinn** [comment]
喜欢PicGo的话欢迎点个star！

**Comment by JayceLau** [comment]
必须star👍
