### ISSUE TITLE
win10程序安装失败

### ISSUE THREAD

**Issue by dreamleader** [Molunerfinn/PicGo#750]
## 问题类型

程序安装第一次运行一半报无法找到uninstall，点击忽略之后安装失败。

## PicGo 的相关信息

PicGo-Setup-2.3.0-x64.exe
win10

## 问题重现

再次安装时运行中止
![111](https://user-images.githubusercontent.com/91368555/135719762-bc37e63d-843d-4458-a9bd-afbe9d5f93b8.jpg)

**Comment by Molunerfinn** [comment]
搜一下类似的问题
https://blog.csdn.net/qq_36852780/article/details/106696420

**Comment by dreamleader** [comment]
it doesn't work, because there's no unintall procedure. The first installation was failed due to no install procedure during intallation, so i set up second. The import point is how to uninstall.
