### ISSUE TITLE
BUG 每次使用快捷键上传之后会有powershell进程残留

### ISSUE THREAD

**Issue by uairyu** [Molunerfinn/PicGo#756]
**声明：我已经仔细看过 [文档](https://picgo.github.io/PicGo-Doc/)、[FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)、和搜索过已经关闭的 [issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed) 后依然没有找到答案，所以才发了一个新的 issue。**

## PicGo 的相关信息
 平台：windows7 x64
PicGo:  2.3.0

## 问题重现
![image](https://user-images.githubusercontent.com/42320246/136501256-f6ae3d66-2e78-4165-b7c6-e601ddbeca4a.png)
![image](https://user-images.githubusercontent.com/42320246/136501283-6758d6b9-8893-4c01-8ae6-9778cd49f175.png)
每次使用快捷键上传之后会有powershell进程残留，即使图片已经上传完，该进程依然存在，就算剪贴板没有图片，上传失败，只要一按，就会有powershell进程出现

**Comment by Molunerfinn** [comment]
应该是个bug，后续会处理

**Comment by Molunerfinn** [comment]
WIN10 无法复现
![image](https://user-images.githubusercontent.com/12621342/145714562-6405a736-5b6a-43fc-8a1c-df1affc4b6cd.png)

**Comment by uairyu** [comment]
> WIN10 无法复现 ![image](https://user-images.githubusercontent.com/12621342/145714562-6405a736-5b6a-43fc-8a1c-df1affc4b6cd.png)


我这边先清空了日志再把日志等级调到ALL，然后截图再按快捷键上传就会这样子
![image](https://user-images.githubusercontent.com/42320246/146156697-65b048d6-db0a-4759-aa6c-2c68a64af9f9.png)
图中那图片链接就是刚刚那上传的截图https://s2.loli.net/2021/12/15/K7odzX9pxUhMwqi.png ![20211215170520.png](https://s2.loli.net/2021/12/15/K7odzX9pxUhMwqi.png)

**Comment by Molunerfinn** [comment]
可能是win7的问题，暂时没法调试，可以看看是不是powershell的脚本问题

**Comment by Molunerfinn** [comment]
回头处理一下给个选项，使用electron内置剪贴板功能

**Comment by uairyu** [comment]
> 回头处理一下给个选项，使用electron内置剪贴板功能

辛苦了，到时我再试试bug还在不在

**Comment by Molunerfinn** [comment]
更新beta3，选择「使用内置剪贴板」即可
