### ISSUE TITLE
无法安装

### ISSUE THREAD

**Issue by zicjin** [Molunerfinn/PicGo#76]
## 问题类型

Bug Report

## PicGo的相关信息
1.6.0, windows 10 1709

## 问题重现
双击安装
![tim 20180711201954](https://user-images.githubusercontent.com/199482/42570847-d214263c-8547-11e8-87b1-0753148d0b95.png)

**Comment by Molunerfinn** [comment]
点击更多信息，仍要运行即可。
https://jingyan.baidu.com/article/2c8c281dceafce0008252aa7.html

**Comment by Molunerfinn** [comment]
这个主要是因为我没有windows的签名导致的。
