### ISSUE TITLE
【picgo+github】私有化图床

### ISSUE THREAD

**Issue by rom1c77** [Molunerfinn/PicGo#764]
![image](https://user-images.githubusercontent.com/14304457/137572555-3f7fce30-f79b-44f5-8d22-d9fe5b4e2247.png)

token都有了，可以实现github私有化图床吗？

只需要在url后面拼接 ?token=设置的值即可；
https://raw.githubusercontent.com/rom1c77/image/master/image/20210901221923.png?token=填写的值

但是 在typeora中，显示图片的地址的时候又不能带token，因为token是私有的；

看看怎么和typeora进行设计；

1. github私有化图床在picgo应该是能访问的；
2. typeora怎么携带token但是又不展示出来，访问私有的图床

**Comment by Molunerfinn** [comment]
图床不考虑私有仓库。

**Comment by Molunerfinn** [comment]
github私有仓库的token是会过期的

**Comment by Molunerfinn** [comment]
如果你不想被别人看见你的图片列表，请使用付费云服务比如腾讯云、阿里云等
