### ISSUE TITLE
上传图片时遇到错误

### ISSUE THREAD

**Issue by hjue** [Molunerfinn/PicGo#773]
## 上传图片时遇到错误

`picgo upload https://ask.qcloudimg.com/http-save/yehe-2662963/lunoeoe5ng.png`

![image](https://user-images.githubusercontent.com/1135045/139651024-27bf0f1e-c848-47f3-a5c1-f9fa1c2be956.png)

使用wget同样不能下载图片
![image](https://user-images.githubusercontent.com/1135045/139651341-879c1370-00e9-4aa1-8f2d-3b7ff238f69c.png)

使用wget指定refer可正常下载图片

`wget --refer="https://cloud.tencent.com/" https://ask.qcloudimg.com/http-save/yehe-2662963/lunoeoe5ng.png`
![image](https://user-images.githubusercontent.com/1135045/139651127-dddc4c62-b6f3-4e5d-86d6-40107adbfbb6.png)

## PicGo 的相关信息

PicGo版本：PicGo-1.4.26
所在平台：intel64
系统：mac

**Comment by Molunerfinn** [comment]
图片如果不能直接获取，自然无法上传

**Comment by hjue** [comment]
是否可以像wget一样，设置refer呢？

**Comment by Molunerfinn** [comment]
本体不考虑，插件可行

**Comment by hjue** [comment]
能否提供插件的文档地址，我自己没找到。有时间我开发一个这样的插件

**Comment by Molunerfinn** [comment]
![image](https://user-images.githubusercontent.com/12621342/140451646-0a9d8d9b-060e-4cce-a3c7-83f344a644ec.png)

**Comment by hjue** [comment]
我写了一个picgo-plugin解决了不能上传腾讯云图片的问题。在命令行中已经可以正常运行。

`
/usr/local/bin/node /usr/local/bin/picgo -c ~/.picgo/config.json upload https://ask.qcloudimg.com/http-save/yehe-2662963/lunoeoe5ng.png

[PicGo INFO]: Before transform
[PicGo INFO]: beforeTransformPlugins: url-input running
[PicGo INFO]: Local image path:/var/folders/g_/znrf1bhd5192ddlp1nqqgbvw0000gn/T/57eb538db631d053a2cfbbcab6aee617.png
[PicGo INFO]: Transforming... Current transformer is [path]
[PicGo INFO]: Before upload
[PicGo INFO]: Uploading... Current uploader is [qiniu]
[PicGo SUCCESS]:
`

但是在typora中却依然报错，好像是插件没有加载。

<img width="1253" alt="image" src="https://user-images.githubusercontent.com/1135045/140615182-36598a88-19a7-4793-8d36-82dc09366cea.png">

这是typora的配置
<img width="582" alt="image" src="https://user-images.githubusercontent.com/1135045/140615216-dd8ee6d2-7400-49ec-aa19-4f7c937755cb.png">


实在是想不到问题出在哪里，请求帮助

**Comment by Molunerfinn** [comment]
![image](https://user-images.githubusercontent.com/12621342/140629442-9723d9ea-0fb8-4977-9fbf-2a16299dc945.png)
报错信息应该挺明显的，首先有两点

1. 图片路径不存在
2. picgo调用upload接口时，没收到合法的图片路径，就会以剪贴板图片上传的方式去找是否图片在剪贴板中。然后发现剪贴板里也没有图片，于是就报错了。

https://github.com/PicGo/PicGo-Core/blob/dev/src/plugins/commander/upload.ts#L20-L27

这个应该找typora看
