### ISSUE TITLE
【建议】希望logo能够透明化

### ISSUE THREAD

**Issue by you-hengh** [Molunerfinn/PicGo#776]
**声明：我已经仔细看过 [文档](https://picgo.github.io/PicGo-Doc/)、[FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)、和搜索过已经关闭的 [issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed) 后依然没有找到答案，所以才发了一个新的 issue。**

## 问题类型

 Feature Request
## PicGo 的相关信息

PicGo Version: 2.3.0
macOS: 11.4

## 功能请求
![image](https://user-images.githubusercontent.com/34816426/140458139-9bf69785-8c3d-4780-8332-2fd9ef97e597.png)

希望logo能够透明化，不然整体看起来风格不够统一
---

**Comment by Molunerfinn** [comment]
感谢反馈，下个版本会优化一下（logo源文件在旧电脑里不知道还能不能找到- -。。。

**Comment by kamusis** [comment]
![wecom-temp-615461b6b7c5fc143bd787787185dfa4](https://user-images.githubusercontent.com/1849506/142795233-8c3e1cbf-cb03-48e2-ae10-fb93f74d9562.png)
请我们做UI的同事帮忙做了一个透明logo，看看 @Molunerfinn 是不是可以采用。

**Comment by Molunerfinn** [comment]
非常感谢，近期会看看更新一波

**Comment by luckykong** [comment]
同样希望能更新一下透明的图标，现在的图标看着好诡异，就像个斜着头的外星人似的，两个大眼睛盯着你

**Comment by Molunerfinn** [comment]
> 同样希望能更新一下透明的图标，现在的图标看着好诡异，就像个斜着头的外星人似的，两个大眼睛盯着你

![image](https://user-images.githubusercontent.com/12621342/147522210-9c821054-0f66-4824-9a60-ec3efbf6845a.png)
难道不是像一把剑嘛🤣

**Comment by kamusis** [comment]
> 同样希望能更新一下透明的图标，现在的图标看着好诡异，就像个斜着头的外星人似的，两个大眼睛盯着你

看了这个解释以后，发现回不来了。。。

**Comment by Daipeizhe** [comment]
图标要是能够隐藏就好了。

**Comment by Molunerfinn** [comment]
不好意思。beta.5里将会更新
