### ISSUE TITLE
「Feature Request」「建议」图床和上传源分开，上传源属于某个类型的图床

### ISSUE THREAD

**Issue by ihipop** [Molunerfinn/PicGo#779]
## 问题类型

Feature Request

## 功能请求

现在图床就是上传源，如果我有多个OSS或者多个图床帐号，就没法单独选择上传到某个图床，只能来回编辑设置

建议是 上传源 新建的时候选择某个类型的图床，比如可以新建N个上传源，底层图床都是OSS但是不同的bucket和帐号，这样更灵活一些。

**Comment by Molunerfinn** [comment]
未来会考虑渐进式支持

**Comment by hubyao** [comment]
同求

**Comment by vzchn** [comment]
同求

**Comment by CarlSongcs** [comment]
同样的需求

**Comment by STDSuperman** [comment]
这个 issue 是否就是对应的 plan 里的多配置的能力那块

**Comment by Molunerfinn** [comment]
> 这个 issue 是否就是对应的 plan 里的多配置的能力那块

是的

**Comment by STDSuperman** [comment]
> > 这个 issue 是否就是对应的 plan 里的多配置的能力那块
> 
> 是的

我想我可以考虑进来看看这个，如果我打算做的话会提个 pr haha.

**Comment by Molunerfinn** [comment]
> > > 这个 issue 是否就是对应的 plan 里的多配置的能力那块
> > 
> > 
> > 是的
> 
> 如果还没有人做的话，项目是否支持 pr 形式进行贡献呢.

支持。不过这个feature应该要先实现 PicGo-Core 的部分，再更新 GUI 项目，欢迎去 PicGo-Core 开个issue

**Comment by STDSuperman** [comment]
> > > > 这个 issue 是否就是对应的 plan 里的多配置的能力那块
> > > 
> > > 
> > > 是的
> > 
> > 
> > 如果还没有人做的话，项目是否支持 pr 形式进行贡献呢.
> 
> 支持。不过这个feature应该要先实现 PicGo-Core 的部分，再更新 GUI 项目，欢迎去 PicGo-Core 开个issue

大概流程我确认了下，大概率需要在现有的基础上调整下配置数据

**Comment by Molunerfinn** [comment]
> 

一级字段 `uploader` 目前是空的。我的预想是把多份配置可以写入 `uploader.xxx: []` 中，然后用户可以选其中一份作为当前的上传配置，然后选中某一个就替换掉 `picBed.xxx` 中的当前配置即可，这样对目前的插件体系以及第三方插件来说入侵性是最小的。

**Comment by Molunerfinn** [comment]
https://github.com/PicGo/PicGo-Core/issues/139

**Comment by STDSuperman** [comment]
> > 
> 
> 一级字段 `uploader` 目前是空的。我的预想是把多份配置可以写入 `uploader.xxx: []` 中，然后用户可以选其中一份作为当前的上传配置，然后选中某一个就替换掉 `picBed.xxx` 中的当前配置即可，这样对目前的插件体系以及第三方插件来说入侵性是最小的。

不过我从初步角度看下来，似乎不用改到 picGo ，现有的 db 能力已经能够满足诉求了似乎

**Comment by Molunerfinn** [comment]
> > > 
> > 
> > 
> > 一级字段 `uploader` 目前是空的。我的预想是把多份配置可以写入 `uploader.xxx: []` 中，然后用户可以选其中一份作为当前的上传配置，然后选中某一个就替换掉 `picBed.xxx` 中的当前配置即可，这样对目前的插件体系以及第三方插件来说入侵性是最小的。
> 
> 不过我从初步角度看下来，似乎不用改到 picGoCore ，现有的 db 能力已经能够满足诉求了

PicGo-Core 也需要提供相关能力给到：

- cli 命令，让用户能够切换配置
- node.js 接口，让 node.js 项目能够调用接口切换配置

**Comment by Molunerfinn** [comment]
感谢 @STDSuperman 的贡献，2.4.0 的第一个 beta 版本将会支持一种类型的图床可以有多份配置

![](https://user-images.githubusercontent.com/44311619/203093104-9537e08a-2ef0-450d-a59d-c470dbcdd6c8.png)
