### ISSUE TITLE
imgur 图床设置求助

### ISSUE THREAD

**Issue by LatteCat** [Molunerfinn/PicGo#78]
想问下 Mac 上最新的 1.6 版本的 imgur 图床如何设置呢？

**Comment by Molunerfinn** [comment]
不会用的时候就看文档。
https://github.com/Molunerfinn/PicGo/wiki/%E8%AF%A6%E7%BB%86%E7%AA%97%E5%8F%A3%E7%9A%84%E4%BD%BF%E7%94%A8#imgur

![image](https://user-images.githubusercontent.com/12621342/42609503-83b1c684-85bf-11e8-9184-821f47394121.png)

**Comment by LatteCat** [comment]
Sorry，我刚刚找了下没找到，谢谢啦！~~~ 
话说，作者你真勤快，这么快就来处理 Issue 了，赞一个👍
