### ISSUE TITLE
Nextcloud自签名证书导致无法上传-Error: Unable to verify the first certificate.

### ISSUE THREAD

**Issue by bingoct** [Molunerfinn/PicGo#780]
**声明：我已经仔细看过 [文档](https://picgo.github.io/PicGo-Doc/)、[FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)、和搜索过已经关闭的 [issues725](https://github.com/Molunerfinn/PicGo/issues/725) 后依然没有找到答案，所以才发了一个新的 issue。**

## 问题类型
Bug Report

## PicGo 的相关信息
picgo版本：2.3.0 
插件：[yanpf1997/picgo-plugin-nextcloud](https://github.com/yanpf1997/picgo-plugin-nextcloud)
平台：Windows 10

## 问题重现
NextCloud是在本地NAS搭的服务，部署的是自签名TLS证书，windows安装了根证书后能正常通过浏览器访问。
当使用Pic-Go上传的时候，发生错误，提示Error: Unable to verify the first certificate。
![屏幕截图 2021-11-14 232313](https://user-images.githubusercontent.com/47520890/141687326-890d2c8a-146b-4f52-99bf-19527b5e2f6b.jpg)
但是查看picgo 日志，显示的是success，没有返回连接。
> 2021-11-14 23:12:25 [PicGo INFO] Before transform 
2021-11-14 23:12:25 [PicGo INFO] Transforming... Current transformer is [path] 
2021-11-14 23:12:25 [PicGo INFO] Before upload 
2021-11-14 23:12:25 [PicGo INFO] beforeUploadPlugins: renameFn running 
2021-11-14 23:12:25 [PicGo INFO] Uploading... Current uploader is [nextcloud] 
2021-11-14 23:12:25 [PicGo SUCCESS] 

尝试过用let's encryption的证书，提示cert has expired（自闭），浏览器依旧能正常访问。

请问该如何解决？

**Comment by Molunerfinn** [comment]
请去插件仓库提问
