### ISSUE TITLE
希望picgo 上传图片前对图片进行压缩处理

### ISSUE THREAD

**Issue by you-hengh** [Molunerfinn/PicGo#789]
**声明：我已经仔细看过 [文档](https://picgo.github.io/PicGo-Doc/)、[FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)、和搜索过已经关闭的 [issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed) 后依然没有找到答案，所以才发了一个新的 issue。**

## 问题类型

 Feature Request

## PicGo 的相关信息

PicGo: 2.3.0
MacOS:12.0.1
芯片:M1 max

## 功能请求

我是用gitee作为图床,但现在因为高分辨率的原因(4k屏幕) 截图后的图片会比较大,希望picgo 在上传前对图片进行无损压缩一次
希望能够支持,感谢作者🙏
还希望能够尽快适配M1 芯片   再次感谢🙏作者

**Comment by Molunerfinn** [comment]
已经有图片压缩插件。可以搜搜 picgo-plugin-compress

M1会尽快适配
