### ISSUE TITLE
上传图片后就看不到图片了

### ISSUE THREAD

**Issue by LxHubei** [Molunerfinn/PicGo#79]
## PicGo的相关信息

Mac 

![image](https://user-images.githubusercontent.com/36725387/42676252-00acc770-86aa-11e8-82e4-6cc06a5258cf.png)

## 问题重现
![image](https://user-images.githubusercontent.com/36725387/42676154-9d46233e-86a9-11e8-935d-de18bf68c110.png)
![image](https://user-images.githubusercontent.com/36725387/42676210-d3b318fa-86a9-11e8-8219-7ff254bcf210.png)

麻烦了

**Comment by Molunerfinn** [comment]
1. 代理问题。如果是一些全局代理，例如微博图床的图片就无法在全局代理下查看。
2. 权限问题。如果你的一些图床是私人的或者私有的，公网无法直接访问的那么也会这样。排查一下，然后重启一下PicGo基本能解决。

**Comment by Molunerfinn** [comment]
@mrdulin 有开启防盗链么

**Comment by Molunerfinn** [comment]
![image](https://user-images.githubusercontent.com/12621342/42719942-10ba64cc-8751-11e8-9e69-00e72201a5b4.png)
是否没加前缀？
![image](https://user-images.githubusercontent.com/12621342/42719947-2b8163f0-8751-11e8-90e5-9a6202996d5a.png)
七牛图床的链接地址需要加`http://`或者`https://`前缀。

**Comment by mrdulin** [comment]
@Molunerfinn ok，七牛图床修改为http协议就好了，这块逻辑可以完善下，或者给出提示

**Comment by Molunerfinn** [comment]
![image](https://user-images.githubusercontent.com/12621342/42719991-fde621b4-8751-11e8-98cf-868623a1ba55.png)
这里已经有提示网址链接格式了。可能需要把这个东西加到FAQ里。

**Comment by Molunerfinn** [comment]
由于架构问题，同步删除无法考虑在内。
参考：https://github.com/Molunerfinn/PicGo/issues/68
![image](https://user-images.githubusercontent.com/12621342/42720020-80a4643a-8752-11e8-8d2a-e4aaa4df1522.png)

**Comment by littlelk** [comment]
我一直不行,后老找到原因是因为我解析到域名了,如果解析到域名的,设定访问网址应该填写http://xxxxx
其中xxxx代表的是你解析到的二级域名，我这边改好是这样的

**Comment by XuWang-AI** [comment]
我这里也一直看不到，请问有什么办法吗

**Comment by TKF12** [comment]
> 我这里也一直看不到，请问有什么办法吗

图片不能超过1mb，不然看不到，需要压缩

**Comment by JaneMe** [comment]
> ## Bug
> ## PicGo的相关信息
> Mac
> 
> ![image](https://user-images.githubusercontent.com/36725387/42676252-00acc770-86aa-11e8-82e4-6cc06a5258cf.png)
> 
> ## 问题重现
> ![image](https://user-images.githubusercontent.com/36725387/42676154-9d46233e-86a9-11e8-935d-de18bf68c110.png)
> ![image](https://user-images.githubusercontent.com/36725387/42676210-d3b318fa-86a9-11e8-8219-7ff254bcf210.png)
> 
> 麻烦了

只需要卸载PicGo再重新安装就能正常显示了，亲测有效

**Comment by XiaoFan955** [comment]
我也遇到同样的问题，相册预览和typra里都不能显示；
解决方法是在七牛图床的设置里面把设定网址前加上http://。
还有一点是“指定存储路径”那个选项，软件的意思应该是指七牛云上的存储路径，所以如果填了本地的绝对路径有可能因为转义的问题无法显示图片。
检查的方法是把七牛云上的图片外链复制出来，看外链能不能直接在浏览器访问，再跟相册预览图片的路径对比一下就能发现问题。

**Comment by XiaoFan955** [comment]
我也遇到同样的问题，相册预览和typra里都不能显示；
解决方法是在七牛图床的设置里面把设定网址前加上http://。
还有一点是“指定存储路径”那个选项，软件的意思应该是指七牛云上的存储路径，所以如果填了本地的绝对路径有可能因为转义的问题无法显示图片。
检查的方法是把七牛云上的图片外链复制出来，看外链能不能直接在浏览器访问，再跟相册预览图片的路径对比一下就能发现问题。

**Comment by DirtyRider** [comment]
七牛云在图床设置的时候，需要在“设定访问网址”那里手动加上http://   或者https://，     
这样就能解决图片不能预览的问题了。我之前发现上传之后，各种格式都没有http前缀还觉得纳闷，这回终于完美解决了。
[![](https://imgqn.hardwarestore.fun/githubA1.png)](url)
[![](https://imgqn.hardwarestore.fun/202301231701700.png)](url)

**Comment by Comradessss** [comment]
成功上传到七牛云但是PicGo不显示，可能是用的七牛云那个30天的默认域名，那个域名用魔法就可以外链打开，要不然打不开，所以正常网络下在PicGol里显示不了。
