### ISSUE TITLE
那些因代理被告知网络问题的伙伴，大部分不是你的问题，是软件问题。

### ISSUE THREAD

**Issue by yumetec** [Molunerfinn/PicGo#795]
如题，那些有代理的被告知是你网络问题的，大部分不是你问题，是软件问题。别提心吊胆怕被作者叼说没看过FAQ还是历史issue而不敢提issue。看这里

路由器切换GFW，绕过中国大陆模式，全局模式都一个样。访问github速度都杠杠的，终端速度也很理想，用picgo就不行。切换到正常没任何代理的路由器就能上传。

图片是上传到github的，而有代理访问github以及终端使用速度都杠杠的，用picgo上传就网络有问题，所以压根不是自己网络有问题，而是软件有问题。

**Comment by Molunerfinn** [comment]
无奈ヾ(-_-;)我也没求你用。做个开源还要被人叼，我求你别用了

**Comment by gimgoo** [comment]
> 无奈ヾ(-_-;)我也没求你用。做个开源还要被人叼，我求你别用了

软件问题是事实，做开源就不能被指出来软件有问题了？本人自从picgo经常上传不了以后，转了 uPic，同样的环境毛事都没有。能是网络问题吗？picgo的配置是没问题的，因为极少数情况下能上传，这说明就是软件问题。哪来那么多网络问题（而且也不是一个两个表示有这种情况）。
