### ISSUE TITLE
windows server 2019不能使用自动上传，没反应

### ISSUE THREAD

**Issue by yzk666** [Molunerfinn/PicGo#796]
作者大佬你好，我下载了最新版本 2.3.0，我家里的电脑使用的是windows server 2019 标准版，但是没办法截图完就直接按快捷键自动上传到阿里OSS，手动拖拽图片上传到阿里云OSS没问题。请问这个是软件没适配到windows server吗？还是我哪里配置有问题。我使用windows 家庭版没有问题，可以使用快捷键自动上传。

**Comment by Molunerfinn** [comment]
可能是快捷键被别的占用了吧。把剪贴板图片上传的快捷键修改成别的试试。

另外发issue请按模板来发。
