### ISSUE TITLE
腾讯COS设置后，选择其为默认图床，无法长传图片

### ISSUE THREAD

**Issue by lc60005457** [Molunerfinn/PicGo#8]
长传进度没有反应，如果是设置错误的话，希望可以弹窗提示。

试用了默认图床为微博时，是正常的。

**Comment by Molunerfinn** [comment]
奇怪的是我已经写了相关的错误提示弹窗，并且我自己这边测试的时候也是没问题的（错误的时候有提示），请问你是哪个配置项配置错误的情况下它不显示错误弹窗呢~期待反馈

**Comment by lc60005457** [comment]
重新生成了一个api密钥，现在又可以了
