### ISSUE TITLE
功能请求 希望保留图片的本地缓存

### ISSUE THREAD

**Issue by Riamuu** [Molunerfinn/PicGo#801]
**声明：我已经仔细看过 [文档](https://picgo.github.io/PicGo-Doc/)、[FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)、和搜索过已经关闭的 [issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed) 后依然没有找到答案，所以才发了一个新的 issue。**

## 功能请求

---

**Comment by Riamuu** [comment]
每次打开相册都会发送一大堆请求，导致加载速度非常的慢

**Comment by Molunerfinn** [comment]
相册请求的是在线链接，可以在你的图床服务商侧配置缓存策略。

另外相册是有做懒加载的，只有首屏的图片会触发加载逻辑才对。所以几个建议

1. 不要上传太大的图片。作为图床，大图片对你对用户都不友好。
2. 尽量使用自己购买的云服务商比如COS\OSS等，可以控制缓存策略
