### ISSUE TITLE
【文档更新】PicGo-Server 支持 FileList，希望能在文档中添加说明

### ISSUE THREAD

**Issue by renmu123** [Molunerfinn/PicGo#805]
翻源码的时候发现 `/upload` 其实是支持 FileList 的而不是仅仅支持具体的 path 。

```ts
let sendFiles: Array<String> = [];
let files = evt.dataTransfer.files;
Array.from(files).forEach((item, index) => {
  sendFiles.push(item.path);
});
```
只要将 `sendFiles` 参数传入 `list` 即可完成上传。

希望能将这部分写入文档，供之后有需要的人使用

**Comment by Molunerfinn** [comment]
额，你这个issue有两个问题

1. 你给出的代码跟picgo-server没关系
2. picgo-server本身就有明确可以上传list
![image](https://user-images.githubusercontent.com/12621342/147228901-7287b2da-72af-4cf0-941d-c7d4a3b47dc0.png)

**Comment by renmu123** [comment]
我知道可以直接指定绝对路径，我指得是这个接口可以上传fileList（并没有实际的路径）

**Comment by renmu123** [comment]
```
let sendFiles: Array<String> = [];
let files = evt.dataTransfer.files;
Array.from(files).forEach((item, index) => {
  sendFiles.push(item.path);
});
uploadFiles(sendFiles)

async uploadFiles(fileList: Array<String>): Promise<any> {
  const response = await fetch(uploadServer, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({ list: fileList }),
  });
  const data = await response.json();
  return data;
}
```

**Comment by Molunerfinn** [comment]
没懂，你sendFiles最终不也是拿了 `item.path` 么，不是一个 string[] 么

**Comment by Molunerfinn** [comment]
picgo-server这个list参数，不关心你是从哪里获取的文件路径列表，你从web端的input里拿也好，你从别的地方拿也好，最终只要这个list参数是个 string[] 就行了，跟你的FileList有什么关系么。

你最终sendFiles不也是一个 string[] 跟picgo-server要求的list格式是一样的啊
