### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by andy-wg** [Molunerfinn/PicGo#807]
首先感谢PicGo方便了很多，
如果能添加pdf、视频等文件就更完美了

**Comment by Molunerfinn** [comment]
其实如果有人写插件的话是可以支持的，整个流程其实是支持上传任意文件的。不过上传别的文件会有很多问题，比如断点续传等。这块不在picgo自身考虑范围内，交给插件实现。感谢建议

**Comment by Molunerfinn** [comment]
这类建议可以到 discussions 发 https://github.com/Molunerfinn/PicGo/discussions
