### ISSUE TITLE
删除相册图片时不能将对象存储里的文件同步删除。

### ISSUE THREAD

**Issue by 1424753988** [Molunerfinn/PicGo#81]
## 问题类型

Bug Report

## PicGo的相关信息

版本1.6.0 Windows

## 问题重现

删除相册图片时不能将对象存储里的文件同步删除。

**Comment by Molunerfinn** [comment]
不能，这个问题已经在很多地方回复了。
![image](https://user-images.githubusercontent.com/12621342/43007152-1222bcc4-8c6a-11e8-9db4-e5436e5eaecc.png)
相关[issue](https://github.com/Molunerfinn/PicGo/issues/68)
