### ISSUE TITLE
七牛云图片无法删除

### ISSUE THREAD

**Issue by Vlary** [Molunerfinn/PicGo#811]
上传图片后在相册中删除，对象存储中的图片依然存在

**Comment by Molunerfinn** [comment]
我不知道你发issue的时候是否看都没看这个？
![image](https://user-images.githubusercontent.com/12621342/148002539-5014b0a9-f1fd-4782-861f-0782d2b1480b.png)

FAQ里写得清清楚楚，就是无法删除。请别再开新issue了，已经回答烂了
![image](https://user-images.githubusercontent.com/12621342/148002586-7685ad5f-dee7-4abf-95c0-6008b614fc57.png)
