### ISSUE TITLE
M1 Air无法打开2.3.1.beta2

### ISSUE THREAD

**Issue by LawyZheng** [Molunerfinn/PicGo#814]
## 问题类型
Bug

## PicGo 的相关信息
Mac M1 Air

## 问题重现
M1 Air无法打开2.3.1.beta2

提示：Picgo.app is damaged and can't be opened. You should move it to the Bin

**Comment by Molunerfinn** [comment]
picgo没有签名，所以会被系统安全拦下来。

安装前输入 `sudo spctl --master-disable` 即可

**Comment by LawyZheng** [comment]
兄弟，我输了命令还是一样。
要不留个联系方式？

**Comment by zhihuai1982** [comment]
https://www.macwk.com/article/macos-file-damage

只需要在 Dmg 安装包界面的空白处右键，然后点击推出，再重新运行一下 DMG 安装包就可以正常安装啦

亲测可以

**Comment by gengjiawen** [comment]
温馨提醒，有一定概率被刘海遮挡了。。。

**Comment by sixleaves** [comment]
压根没用。
<img width="814" alt="image" src="https://user-images.githubusercontent.com/3601210/159766493-1e0b8302-d7e2-4e2f-a09d-25e0d88694f5.png">

@Molunerfinn

**Comment by sixleaves** [comment]
> ## 问题类型
> Bug
> 
> ## PicGo 的相关信息
> Mac M1 Air
> 
> ## 问题重现
> M1 Air无法打开2.3.1.beta2
> 
> 提示：Picgo.app is damaged and can't be opened. You should move it to the Bin

下载intel版的吧，也不是不能用

**Comment by jinfagang** [comment]
上面的所有操作根本没效果啊

**Comment by 2PoL** [comment]
xattr -cr /Applications/PicGo.app
