### ISSUE TITLE
主进程发生 Javascript error A Javascript error occurred in the main process

### ISSUE THREAD

**Issue by jasonchio-cn** [Molunerfinn/PicGo#819]
**声明：我已经仔细看过 [文档](https://picgo.github.io/PicGo-Doc/)、[FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)、和搜索过已经关闭的 [issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed) 后依然没有找到答案，所以才发了一个新的 issue。**

## 问题类型
Bug Report

## PicGo 的相关信息

Windows 10
## 问题重现
每次启动 Picgo 就会重现，没有任务栏图标，但是有后台进程驻留。
只有删掉配置文件才可以打开。

![image](https://user-images.githubusercontent.com/36125147/149076023-3a26b8b0-bc2d-4897-8a9f-8edb8932ffa6.png)

---

**Comment by Molunerfinn** [comment]
版本是多少？

**Comment by Molunerfinn** [comment]
不过这里看到写日志的代码确实路径有点问题，回头修复一下。你的配置文件是有配什么别的属性么，看起来是读取配置文件失败导致的问题

**Comment by Molunerfinn** [comment]
下个beta版将不会看到这个报错

**Comment by jasonchio-cn** [comment]
> 

![image](https://user-images.githubusercontent.com/36125147/149079262-564f61b6-c449-413d-949c-ec129a985281.png)

安装了一个图床插件和一个上传前压缩图片的插件，其他的配置没有特殊的更改

请问更新了 beta 版还能使用我的备份文件吗？查看的配置会不会呢？

**Comment by Molunerfinn** [comment]
配置文件格式是没变的，路径也没变，就是data.json。

建议配置文件先自行做一份备份，回头遇到问题了picgo会删掉有问题的配置文件然后重新写一个白的文件，这个时候可以把备份文件替换掉

**Comment by Molunerfinn** [comment]
配置文件读写失败的问题，2.4.0里会集中处理
