### ISSUE TITLE
Mini模式下浮动窗口会无限增大

### ISSUE THREAD

**Issue by book1925** [Molunerfinn/PicGo#82]
## 问题类型
Bug Report

## PicGo的相关信息
版本：PicGo 1.6.0
平台：Windows 10 Pro Build 17134

## 问题重现
Mini模式下左键按住PicGo浮动窗口会使其无限增大，且退出Mini模式后无法复原。关闭后重新打开PicGo可使窗口大小复原。（另类彩蛋？）

![](https://i.loli.net/2018/07/21/5b5327152021c.png)

---

**Comment by book1925** [comment]
不用抱歉啦，mini模式我也不常用，偶然发现的bug来反馈一下。

**Comment by Molunerfinn** [comment]
@book1925 问题已经解决，v1.6.1版本更新后即可。
