### ISSUE TITLE
 Bug Report windows can't read xxxx 无法自动上传

### ISSUE THREAD

**Issue by jundaychan** [Molunerfinn/PicGo#822]
## 问题类型

 Bug Report

## PicGo 的相关信息

 windows 2.3.0

## 问题重现
无法自动上传，只能用下载好的文件上传
![微信截图_20220112200652](https://user-images.githubusercontent.com/64624927/149137472-f21284e5-d8af-4bb7-b571-0a952bb36f46.png)

**Comment by Molunerfinn** [comment]
应该是用户名是中文名导致的

**Comment by teteko233** [comment]
![image](https://user-images.githubusercontent.com/52707233/153370832-3e7e641a-be1d-4959-b1f7-3ee18e500db8.png)
但是我这里依然显示read error
版本2.30beta，win10 ，mini窗口快捷上传报错，主窗口上传没有问题。

**Comment by Molunerfinn** [comment]
> 

给一下报错日志。主窗口快捷上传正常？

**Comment by teteko233** [comment]
[picgo.log](https://github.com/Molunerfinn/PicGo/files/8039890/picgo.log)
日志在这里，我今天刚刚安装软件，全部日志应该不多。
用鼠标直接拖拽网页（ms edge浏览器）图片至主界面上传正常，拖拽至mini窗口报错。

**Comment by Molunerfinn** [comment]
> @Molunerfinn [picgo.log](https://github.com/Molunerfinn/PicGo/files/8039890/picgo.log) 日志在这里，我今天刚刚安装软件，全部日志应该不多。 用鼠标直接拖拽网页（ms edge浏览器）图片至主界面上传正常，拖拽至mini窗口报错。

问题已经复现，下个beta版本修复

**Comment by Molunerfinn** [comment]
@jundaychan 下个beta版本会提供另一种上传剪贴板图片的模式，届时可以试试
