### ISSUE TITLE
Gicgo ——You must be logged in to use issue 

### ISSUE THREAD

**Issue by UNIONDONG** [Molunerfinn/PicGo#825]
**最近打开Picgo，发现上传图片时，出现如下错误：You must be logged in to use issue ，第一感觉是让我登录才能使用，但是Picgo不需要登录呀，不太清楚哪里出了问题，有遇到的小伙伴吗？**

## 问题类型

![image](https://user-images.githubusercontent.com/35584433/150120971-433a88ba-d717-4294-9618-9f5ed332b8fc.png)

## PicGo 的相关信息

- Picgo - 2.3.0

- Windows平台

## 问题重现
基本每次上传图片都会出现该问题，求助！
![image](https://user-images.githubusercontent.com/35584433/150121144-146567dd-15a7-4014-80d4-5b5905c8bb31.png)
![image](https://user-images.githubusercontent.com/35584433/150121173-548e0e8d-2d21-4eba-9863-6128ff69f0a5.png)

**Comment by Molunerfinn** [comment]
配置一下smms图床的token

**Comment by UNIONDONG** [comment]
> 配置一下smms图床的token

我已经配置了Github图床的Token了，还是存在这个issue

**Comment by Molunerfinn** [comment]
问题是你上传的图床是smms- -

**Comment by UNIONDONG** [comment]
> 配置一下smms图床的token
@Molunerfinn，谢谢你！ I Get! 
应该是Picgo出Bug了吧？
我设置的只有一个图床，之前一直可以使用，最近突然就不行了，然后我点击了设置默认图床的选项，就可以了！！！
谢谢啦！

![image](https://user-images.githubusercontent.com/35584433/150124008-1c93d131-8470-4492-8946-35f8138e113d.png)


![image](https://user-images.githubusercontent.com/35584433/150123275-a647db73-b6d5-4ee5-a966-7b74cecb0d2d.png)

**Comment by Molunerfinn** [comment]
之前一直可以使用可能是你之前一直用的smms图床上传的咯，你可以看看你之前上传的图片的地址啊

**Comment by royaya** [comment]
在上传区的图片上传那里，默认的smm，要选择一下gitee

**Comment by Saltish-jyf** [comment]
应该是smms现在要登陆用了，在sm.ms注册一下，然后把API token复制到smms的Token框里就行

**Comment by yxw007** [comment]
我的是token有问题，切换一下token就可以了。大家如果出现这个问题，可能token不对（权限不够)。可以尝试切换token试试看
