### ISSUE TITLE
下载gitee插件时提示需要安装nodejs（已有）

### ISSUE THREAD

**Issue by lilxmx** [Molunerfinn/PicGo#827]
**声明：我已经仔细看过 [文档](https://picgo.github.io/PicGo-Doc/)、[FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)、和搜索过已经关闭的 [issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed) 后依然没有找到答案，所以才发了一个新的 issue。**

## 问题类型

Bug Report

## PicGo 的相关信息

Windows 2.3.0

## 问题重现

已经安装了nodejs，环境变量设置成功，命令行可以直接使用node
![S)T462W $N%P7C)C9ZV(W J](https://user-images.githubusercontent.com/62053725/150621356-500b1c8c-38b5-4268-9a2d-578148d0fa23.png)
![OX F4VL@O}XDWBY$_J2MND2](https://user-images.githubusercontent.com/62053725/150621539-0460bdd9-9f92-491b-8403-c62313f6eec9.png)

## 功能请求

---

**Comment by Molunerfinn** [comment]
如果是刚安完node，可以尝试重启电脑。另外安装插件依赖的是nodejs带的npm命令，请确认npm命令是否正常

**Comment by Molunerfinn** [comment]
有后续反馈再跟进。

**Comment by lilxmx** [comment]
> 



> 有后续反馈再跟进


问题已解决，通过命令行npm 直接安装插件 
参考教程:
https://blog.csdn.net/sugela8/article/details/116205887
