### ISSUE TITLE
m1 pro 顶部栏没有picgo图标

### ISSUE THREAD

**Issue by yangzihuang** [Molunerfinn/PicGo#834]
**声明：我已经仔细看过 [文档](https://picgo.github.io/PicGo-Doc/)、[FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)、和搜索过已经关闭的 [issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed) 后依然没有找到答案，所以才发了一个新的 issue。**

## PicGo 的相关信息

pico-2.3.1-beta.2
macOS Monterey 12.2

## 问题重现
<img width="825" alt="截屏2022-02-02 16 09 40" src="https://user-images.githubusercontent.com/91045999/152116405-b5461c6c-9994-4384-9dac-64d45f3f3498.png">

<img width="487" alt="截屏2022-02-02 16 08 17" src="https://user-images.githubusercontent.com/91045999/152116287-03c02f1c-e113-42fb-8006-44bb5f0a8db6.png">

## 功能请求

---

**Comment by Molunerfinn** [comment]
安装过什么插件么？以及提供一下日志，日志文件地址文档中有

**Comment by yangzihuang** [comment]
2022/02/02-15:55:45.411 9403 Creating DB /Users/yangzihuang/Library/Application Support/picgo/Local Storage/leveldb since it was missing.
2022/02/02-15:55:45.480 9403 Reusing MANIFEST /Users/yangzihuang/Library/Application Support/picgo/Local Storage/leveldb/MANIFEST-000001

就这有这个

**Comment by Molunerfinn** [comment]
> 2022/02/02-15:55:45.411 9403 Creating DB /Users/yangzihuang/Library/Application Support/picgo/Local Storage/leveldb since it was missing. 2022/02/02-15:55:45.480 9403 Reusing MANIFEST /Users/yangzihuang/Library/Application Support/picgo/Local Storage/leveldb/MANIFEST-000001
> 
> 就这有这个

不是系统日志，是picgo的自己的日志，请看文档

**Comment by Molunerfinn** [comment]
跟配置文件在同级目录的picgo.log
![image](https://user-images.githubusercontent.com/12621342/152129596-d4444c2b-6d65-420e-9efc-3682505963e4.png)

**Comment by yangzihuang** [comment]
没有这个文件

**Comment by yangzihuang** [comment]
![Uploading 截屏2022-02-02 17.46.51.png…]()

**Comment by Molunerfinn** [comment]
配置文件和配置文件同级的package.json贴一下？同级文件里没有picgo.log？

**Comment by yangzihuang** [comment]
<img width="377" alt="截屏2022-02-02 17 46 51" src="https://user-images.githubusercontent.com/91045999/152130459-2f30ec2b-3e11-4c2e-9b4e-3b032dedbea6.png">

**Comment by yangzihuang** [comment]
{"name":"picgo-plugins","description":"picgo-plugins","repository":"https://github.com/Molunerfinn/PicGo-Core","license":"MIT"}%

**Comment by Molunerfinn** [comment]
可以尝试删掉picgo.db之后重启一下picgo

**Comment by yangzihuang** [comment]
日志文件显示这样，但顶部还是没有图标
2022-02-02 17:49:56 [PicGo INFO] [PicGo Server] is listening at 36677

**Comment by Molunerfinn** [comment]
之前有用户反馈，有可能被刘海挡住了

**Comment by Molunerfinn** [comment]
不过我这边没法复现，日志看起来是正常的

**Comment by yangzihuang** [comment]
不是给刘海挡住了

**Comment by yangzihuang** [comment]
我又重启一次电脑突然就好了。第一次重新是勾选了那个“再次登陆时重新打开窗口”，可能是这个原因。

**Comment by EVINK** [comment]
有没有可能是当前App的菜单太长把icon挡住了呢？
比如 访达是这样的：
<img width="886" alt="image" src="https://user-images.githubusercontent.com/14816851/153846675-0bd62a91-035f-46b1-8989-0b2612ae7dd9.png">
而 Chrome是这样的：
<img width="870" alt="image" src="https://user-images.githubusercontent.com/14816851/153846767-b04d0d50-e416-4dd2-8f33-112facf8322f.png">
