### ISSUE TITLE
GitHub图床关闭证书验证

### ISSUE THREAD

**Issue by xuangeyouneihan** [Molunerfinn/PicGo#835]
**声明：我已经仔细看过 [文档](https://picgo.github.io/PicGo-Doc/)、[FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)、和搜索过已经关闭的 [issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed) 后依然没有找到答案，所以才发了一个新的 issue。**

## 问题类型

Feature Request

## PicGo 的相关信息

2.3.0 Windows

## 功能请求  

GitHub图床增添关闭证书验证的选项，以保证在使用如[dotnetcore/FastGithub](https://github.com/dotnetcore/FastGithub)这样的GitHub加速工具时能够正常上传。谢谢大佬！

**Comment by Molunerfinn** [comment]
添加系统证书自信任即可。picgo使用api上传

**Comment by xuangeyouneihan** [comment]
> 添加系统证书自信任即可。picgo使用api上传

问下怎么添加？我把FastGithub提供的证书安装到了受信任的根证书颁发机构，没用🤔

**Comment by wylong918** [comment]
> > 添加系统证书自信任即可。picgo使用api上传
> 
> 问下怎么添加？我把FastGithub提供的证书安装到了受信任的根证书颁发机构，没用🤔

我也是这个问题，请问解决了吗
