### ISSUE TITLE
当切换到别的选项卡再切换回来的时候，上传的进度便会被中断

### ISSUE THREAD

**Issue by SMARK2022** [Molunerfinn/PicGo#836]
**声明：我已经仔细看过 [文档](https://picgo.github.io/PicGo-Doc/)、[FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)、和搜索过已经关闭的 [issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed) 后依然没有找到答案，所以才发了一个新的 issue。**

## 问题类型
Bug提交

## PicGo 的相关信息
[2.3.1-beta.2](https://github.com/Molunerfinn/PicGo/releases/tag/v2.3.1-beta.2) Windows7

## 问题重现
在上传着图片的同时，当切换到别的选项卡的时候，再切换回来，上传的内容便会被中断，进度条也归零，同时再次上传也会显示部分文件已存在的服务器错误

## 功能请求
建议存在错误的时候可以让用户保留忽略错误继续上传的权限

**Comment by Molunerfinn** [comment]
不会中断只是界面刷新，等待上传完毕既可

**Comment by SMARK2022** [comment]
好的谢谢
