### ISSUE TITLE
为什么会在我的c盘新建typora文件夹并且会在这个文件中保存我上传的图片？

### ISSUE THREAD

**Issue by Emperor-Jude** [Molunerfinn/PicGo#837]
**声明：我已经仔细看过 [文档](https://picgo.github.io/PicGo-Doc/)、[FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)、和搜索过已经关闭的 [issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed) 后依然没有找到答案，所以才发了一个新的 issue。**

## PicGo 的相关信息

PicGo的版本 
##
![Snipaste_2022-02-07_22-40-54](https://user-images.githubusercontent.com/82216171/152809541-89fa3175-d4c2-4dda-a6a8-9ccdb2788171.png)

## 功能请求

---

**Comment by Molunerfinn** [comment]
请你去问typora
