### ISSUE TITLE
希望文件改名, 不需要每次都弹窗提示

### ISSUE THREAD

**Issue by Kyvrel** [Molunerfinn/PicGo#838]
## 问题类型
Feature Request

## PicGo 的相关信息
PicGo版本: 2.3.0
平台: mac

## 功能请求

希望文件改名, 不用每次上传的时候, 都要弹窗确认. 设置好改名以后, 直接改就行了. 
我记得linux上逻辑就是这样的, 但是mac每次都要确认一遍

---

![image](https://user-images.githubusercontent.com/25075484/153009881-f5887e89-63a6-4da5-9a85-296895bf602b.png)

**Comment by Molunerfinn** [comment]
![image](https://user-images.githubusercontent.com/12621342/153022023-e1112f06-cf40-47e6-a8ac-0f1e31d1ef97.png)

**Comment by qiaocco** [comment]
原来是我配置错了, 感谢大佬

**Comment by Eve-Sama** [comment]
我也遇到了, 然后发现原来是设置错了, 哈哈. 感谢!
