### ISSUE TITLE
arm版在m1 max上运行会不显示界面

### ISSUE THREAD

**Issue by zqzess** [Molunerfinn/PicGo#844]
执行后``sudo xattr -r -d com.apple.quarantine /Applications/PicGo.app``后打开程序，首次启动的隐私条款协议界面一闪而逝。重启后再打开，没有任何响应，但是活动监视器里面能看到程序已经在运行

**Comment by thouger** [comment]
相同的问题，不过我是连活动监视器里都看不到，打开就说文件已损坏
![image](https://user-images.githubusercontent.com/11767062/159271074-fd7eb584-a1a7-4df4-9cc7-ffa87a126aa4.png)

**Comment by thouger** [comment]
搞定了，原因在这里https://github.com/Molunerfinn/PicGo/issues/814

**Comment by stimw** [comment]
同问题。。一闪而过，然后无了。为什么关闭了这个issue？
