### ISSUE TITLE
[BUG] 在Typora中上传图片到Gitee图床, 经常出现一直处于upload上传状态, 且不断向日志文件写入异常信息

### ISSUE THREAD

**Issue by springandme** [Molunerfinn/PicGo#845]
**声明：我已经仔细看过 [文档](https://picgo.github.io/PicGo-Doc/)、[FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)、和搜索过已经关闭的 [issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed) 后依然没有找到答案，所以才发了一个新的 issue。**

## 问题类型
Bug 

## PicGo 的相关信息
PicGo 2.3.1-beta.2    Win10

## 问题重现
在Typora中上传图片到Gitee图床, 经常出现一直处于`upload`上传状态, 且不断向`C:\Users\xxxx\AppData\Roaming\picgo\picgo.log`日志文件写入异常信息

![image](https://user-images.githubusercontent.com/44739137/155870820-5691212a-1051-4b64-940d-c43c1cf177e2.png)

## 功能请求

---

**Comment by springandme** [comment]
另说一下是AMD的CPU, 5800H.   之前Intel的CPU且从没有出现过问题(网络环境也很好)

**Comment by Molunerfinn** [comment]
联系插件提供方

**Comment by Molunerfinn** [comment]
检查一下配置文件所在目录的picgo.log文件，删掉重启picgo试试

**Comment by springandme** [comment]
之前我也是这样做的, 听见笔记本的风扇疯狂响, 就知道有问题了. 删掉picgo.log文件, 重启picgo. 但来来回回还是会出现问题. 这次我把之前的卸载了, 降低一下v2.3.0版本, 再试试

**Comment by twoheartliu** [comment]
类似的问题……我以为是插件问题，多次尝试后发现是主 App 问题，现在 App 主版本降级到了 2.2.2，一切正常。

 #https://github.com/wayjam/picgo-plugin-s3/issues/12

**Comment by Molunerfinn** [comment]
应该是有个地方死循环了，回头处理一下

**Comment by Molunerfinn** [comment]
最新beta3版本修复了这个问题
