### ISSUE TITLE
README 中的 NPM 淘宝域名应更换

### ISSUE THREAD

**Issue by SadPencil** [Molunerfinn/PicGo#849]
**声明：我已经仔细看过 [文档](https://picgo.github.io/PicGo-Doc/)、[FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)、和搜索过已经关闭的 [issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed) 后依然没有找到答案，所以才发了一个新的 issue。**

## 问题类型

文档更新。
既不是 Bug Report 也不是 Feature Request。

## PicGo 的相关信息

不适用。

## 问题重现

不适用。

## 功能请求

不适用。

---
[「重要通知」原淘宝 npm 域名即将停止解析](https://zhuanlan.zhihu.com/p/465424728?spm=a2c6h.24755359.0.0.6d444dccTGRx9r)
```cs
    npm.taobao.org => npmmirror.com
    registry.npm.taobao.org => registry.npmmirror.com
```

README 中的 `export ELECTRON_MIRROR="https://npm.taobao.org/mirrors/electron/"` 这一行即将失效，请更新域名。

**Comment by YunchaoZheng** [comment]
support

**Comment by Molunerfinn** [comment]
感谢，会尽快处理

**Comment by zhullyb** [comment]
更改有问题，url 应为 `https://npmmirror.com/mirrors/electron/`
使用 `https://registry.npmmirror.com/binary.html?path=electron/` 会出现如图错误
![图片](https://user-images.githubusercontent.com/43305366/157698207-53503415-e244-45eb-bbbd-3b6e5c6c678d.png)

**Comment by Molunerfinn** [comment]
> https://npmmirror.com/mirrors/electron/

这个地址也会302跳转到https://registry.npmmirror.com/binary.html?path=electron/

**Comment by zhullyb** [comment]
对，但是 npm 应该会使用拼接链接的方式得到最终的下载链接，而不是直接访问
________________________________

**Comment by zhullyb** [comment]
比如 https://npmmirror.com/mirrors/electron/v16.1.0/electron-v16.1.0-linux-x64.zip 就会跳转到正确的下载链接，npm下载它的时候应该只是下载 $ELECTRON_MIRROR/v16.1.0/electron-v16.1.0-linux-x64.zip ，所以我们应该填 https://npmmirror.com/mirrors/electron/ ，后面的部分 npm/yarn 会帮我们加上

**Comment by YunchaoZheng** [comment]
另外，release中的链接，图片，也请记得调整

**Comment by Molunerfinn** [comment]
感谢各位小伙伴，已经修改链接
