### ISSUE TITLE
PicGo 被山东大学的开源镜像站镜像，建议在 Readme 中添加链接

### ISSUE THREAD

**Issue by zhullyb** [Molunerfinn/PicGo#850]
**声明：我已经仔细看过 [文档](https://picgo.github.io/PicGo-Doc/)、[FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)、和搜索过已经关闭的 [issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed) 后依然没有找到答案，所以才发了一个新的 issue。**

## 问题类型
山东大学的开源镜像站提供了 PicGo 的 Release 文件镜像，可以考虑在 README 中提一嘴，毕竟 Github 在境内的连接速度不稳定
https://mirrors.sdu.edu.cn/github-release/Molunerfinn_PicGo/

## PicGo 的相关信息
不适用

## 问题重现
不适用

## 功能请求
不适用

---

**Comment by Molunerfinn** [comment]
感谢分享，今晚会更新一波
