### ISSUE TITLE
有没有导出相册功能或编辑配置文件来导出相册

### ISSUE THREAD

**Issue by pangyi** [Molunerfinn/PicGo#852]
**声明：我已经仔细看过 [文档](https://picgo.github.io/PicGo-Doc/)、[FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)、和搜索过已经关闭的 [issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed) 后依然没有找到答案，所以才发了一个新的 issue。**

## 功能请求

换了一台电脑，相册的信息都没有了，请问有没有办法从原来的相册中导出信息再导入到新安装的Picgo中？手工编辑配置文件的方法也行。
---

**Comment by Molunerfinn** [comment]
从旧电脑的picgo的配置文件所在目录有个picgo.db 拷贝到新的电脑的同样的地方 重启picgo 即可
