### ISSUE TITLE
请问大佬，能不能支持兰空图床啊？

### ISSUE THREAD

**Issue by codesbuff** [Molunerfinn/PicGo#856]
**声明：我已经仔细看过 [文档](https://picgo.github.io/PicGo-Doc/)、[FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)、和搜索过已经关闭的 [issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed) 后依然没有找到答案，所以才发了一个新的 issue。**

## 问题类型

功能建议

## 功能请求

请问大佬，能不能支持兰空图床2.X 版本

刚看了下有个1.0版本的插件 已经不能用了。

**Comment by Molunerfinn** [comment]
https://github.com/PicGo/Awesome-PicGo/pull/64

**Comment by hellodk34** [comment]
https://github.com/hellodk34/picgo-plugin-lankong 今天刚做好 @codesbuff  欢迎来个 star 🤣
