### ISSUE TITLE
已上传的图片在已上传和相册界面都不显示。七牛图床

### ISSUE THREAD

**Issue by wklesss** [Molunerfinn/PicGo#86]
##  问题类型
Bug Report

##  PicGo的相关信息

 版本:1.6.0、所在平台Mac）

## 问题重现

bug描述：
已上传的图片在已上传和相册界面都不显示。七牛图床

截图：
![image](https://user-images.githubusercontent.com/29318238/43078480-2ac0a6ba-8ebd-11e8-8b28-218f892f0aba.png)
![image](https://user-images.githubusercontent.com/29318238/43078484-2eacdab4-8ebd-11e8-9976-10a0a308d90d.png)

**Comment by Molunerfinn** [comment]
应该是没设定`http`或者`https`头。
参考这个：https://github.com/Molunerfinn/PicGo/issues/79
