### ISSUE TITLE
Picgo相册无法显示

### ISSUE THREAD

**Issue by johnstart** [Molunerfinn/PicGo#860]
**声明：我已经仔细看过 [文档](https://picgo.github.io/PicGo-Doc/)、[FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)、和搜索过已经关闭的 [issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed) 后依然没有找到答案，所以才发了一个新的 issue。**

## 问题类型
**Bug**

## PicGo 的相关信息
Windows Picgo 2.3.0

## 问题重现
Picgo使用一直正常，关机后再次使用发现无法查看相册，如下图。尝试着Typora中上传图片发现可以成功，但是相册还是不显示。关闭Typora后再次打开发现图片无法显示，错误无image load failed。尝试卸载Picgo后再次安装问题无法解决。

![image](https://user-images.githubusercontent.com/2754923/160232850-ec20bfa0-001b-4e3f-a76f-ae2d5474ede1.png)

## 功能请求

---

**Comment by Molunerfinn** [comment]
图片无法显示不是picgo的问题。。。如果你用的是gitee当图床，请你去了解gitee最新的政策

**Comment by xuezhiwang02** [comment]
![image](https://user-images.githubusercontent.com/102411704/160233984-acf22e37-52fe-456f-8ec1-eedd5a989e54.png)

**Comment by peanut325** [comment]
请问解决了么，今天也突然出现这种情况！

**Comment by wwdok** [comment]
> 图片无法显示不是picgo的问题。。。如果你用的是gitee当图床，请你去了解gitee最新的政策

相关报道：https://cloud.tencent.com/developer/article/1964208
picgo目前是能上传到gitee的，只是生成的markdown链接不再符合gitee的路径规则，那是不是picgo在生成markdwon链接时，能改一下这个路径规则，以适应新的gitee政策？

**Comment by Molunerfinn** [comment]
> > 图片无法显示不是picgo的问题。。。如果你用的是gitee当图床，请你去了解gitee最新的政策
> 
> 
> 
> 相关报道：https://cloud.tencent.com/developer/article/1964208
> 
> picgo目前是能上传到gitee的，只是生成的markdown链接不再符合gitee的路径规则，那是不是picgo在生成markdwon链接时，能改一下这个路径规则，以适应新的gitee政策？

picgo不提供gitee的服务 所有gitee相关的都是第三方插件提供。可以去gitee插件仓库反馈 谢谢

**Comment by johnstart** [comment]
gitee的问题，不使用gitte就没有问题了。我改用腾讯云了
________________________________
发件人: PiEgg ***@***.***>
发送时间: 2022年5月2日 21:03
收件人: Molunerfinn/PicGo ***@***.***>
抄送: johnstart ***@***.***>; Author ***@***.***>
主题: Re: [Molunerfinn/PicGo] Picgo相册无法显示 (Issue #860)


图片无法显示不是picgo的问题。。。如果你用的是gitee当图床，请你去了解gitee最新的政策

相关报道：https://cloud.tencent.com/developer/article/1964208

picgo目前是能上传到gitee的，只是生成的markdown链接不再符合gitee的路径规则，那是不是picgo在生成markdwon链接时，能改一下这个路径规则，以适应新的gitee政策？

picgo不提供gitee的服务 所有gitee相关的都是第三方插件提供。可以去gitee插件仓库反馈 谢谢

―
