### ISSUE TITLE
[上传操作]异常：403

### ISSUE THREAD

**Issue by Linux-yzy** [Molunerfinn/PicGo#861]
**声明：我已经仔细看过 [文档](https://picgo.github.io/PicGo-Doc/)、[FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)、和搜索过已经关闭的 [issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed) 后依然没有找到答案，所以才发了一个新的 issue。**

## 问题类型
Bug
## PicGo 的相关信息
2.3.0

## 问题重现
![image](https://user-images.githubusercontent.com/67667674/160267933-d27f81d7-7125-4a8e-b39d-87b6c7e2ba2b.png)

**Comment by Linux-yzy** [comment]
前几天还是可以成功上传的，但是今天突然出现此bug

**Comment by Molunerfinn** [comment]
gitee官方已经不允许仓库做图床开启了防盗链。
另外picgo也没有官方支持gitee，是第三方插件支持的，请直接去插件仓库提问
