### ISSUE TITLE
打不开PICGO

### ISSUE THREAD

**Issue by X-varywow** [Molunerfinn/PicGo#864]
**声明：我已经仔细看过 [文档](https://picgo.github.io/PicGo-Doc/)、[FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)、和搜索过已经关闭的 [issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed) 后依然没有找到答案，所以才发了一个新的 issue。**

## 问题类型

Bug Report

## PicGo 的相关信息

2.3.0, win11, x64

## 问题重现

![屏幕截图 2022-03-31 135326](https://user-images.githubusercontent.com/53894423/160985830-358781f3-448a-4e7e-862e-987a049e29a7.png)

**Comment by Molunerfinn** [comment]
参考https://github.com/Molunerfinn/PicGo/issues/819
