### ISSUE TITLE
tencent-cos的图床配置界面提一些优化建议，望采纳。

### ISSUE THREAD

**Issue by YinshawnRao** [Molunerfinn/PicGo#865]
**声明：我已经仔细看过 [文档](https://picgo.github.io/PicGo-Doc/)、[FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)、和搜索过已经关闭的 [issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed) 后依然没有找到答案，所以才发了一个新的 issue。**

## 问题类型

Feature Request

## PicGo 的相关信息

当前最新版本，mac/win双平台

## 功能请求

腾讯云cos的图床配置界面这里提2个优化点：

1. 目前cos已经不推荐使用v4版本了，当前新的功能特性都推荐使用v5版本，这里建议默认选中v5而不是v4。
![image](https://user-images.githubusercontent.com/8546790/161034324-2e42cd4c-2c9d-4d65-84f0-315ab8054a29.png)

2. 存储桶地域这里输入框的placeholder提示有一些误导性， 切换上面的v4/v5版本时，这里固定展示 “例如 tj”。
![image](https://user-images.githubusercontent.com/8546790/161034247-761a9f57-35a0-4ae7-b879-c10abcc161f0.png)

而实际上v4，v5的地域规范是不同的，建议修改为如下逻辑：
  1) 选中v5时，placeholder：例如ap-shanghai
  2) 选中v4时，placeholder：例如sh

**Comment by Molunerfinn** [comment]
1. 默认选v5应该是可以做的
2. placehoder是读取的config的静态属性，暂时不考虑做动态处理。可以把两种风格都给加上。本质上这个还是要用户自己具体看文档，光看placeholder直接填也没意义

**Comment by Molunerfinn** [comment]
更新beta3即可
