### ISSUE TITLE
为不使用 coc 插件的 neovim 用户开发一款基于 Lua 的 picgo 插件

### ISSUE THREAD

**Issue by askfiy** [Molunerfinn/PicGo#867]
目前，neovim 生态圈发生了很大的变化。

越来越多的人使用 neovim 内置 LSP 而不是 coc，因此希望能够推出一款基于 Lua 或者 viml 的插件来支持 picgo 在非 coc 用户中的支持。

**Comment by Molunerfinn** [comment]
这个要交给第三方开发者实现了
