### ISSUE TITLE
[Feature]: 希望大佬能给图床设置的表单设置合理添加表单验证规则,或者希望加个友好的报错提示

### ISSUE THREAD

**Issue by CoderFXJ** [Molunerfinn/PicGo#873]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [X] [Issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)

### PicGo的版本 | PicGo Version

v2.3.1

### 系统信息 | System Information

Windows

### 功能请求 | Feature request

![image](https://user-images.githubusercontent.com/68853957/161968278-3c44c49b-d9a3-4aa9-97ca-a65c7fa92c83.png)
希望大佬能给图床设置的表单设置合理添加表单验证规则, 
比如今天我输入存储区域,，前面多输入一个空格，然后配置了半天都是上传失败，找不到问题所在，然后又重头来一遍，我知道这是我的问题，但从用户的角度来看体验不太友好。
 希望方便的话完善表单校验(比如加个表单校验规则 ，去除首尾空格格)
或者希望加个友好的报错提示，提示哪个地方配置有误，也好排查问题。
此外非常感谢大佬的开源软件， 希望越做越好！！！

**Comment by Molunerfinn** [comment]
beta.4版本会自动过滤前后空格了
