### ISSUE TITLE
[Feature]: 能不能加一个批量修改相册域名的功能

### ISSUE THREAD

**Issue by StruggleYang** [Molunerfinn/PicGo#875]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [X] [Issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)

### PicGo的版本 | PicGo Version

2.3.0

### 系统信息 | System Information

Mac

### 功能请求 | Feature request

我上传了很多图片到七牛云，但是在前段时间由于域名到期修改了七牛对象存储的域名，在PicGo也改了对应的访问域名了，但是相册里的图片还是没有更新到最新域名，必须要一个个的修改图片信息里的域名。希望能多选批量修改图片信息里的域名

**Comment by Molunerfinn** [comment]
这个功能可以考虑加入

**Comment by StruggleYang** [comment]
> 这个功能可以考虑加入

老板回复真快，期待新版本，我现在就不一个个改了哈哈哈，太多了

**Comment by Molunerfinn** [comment]
相册编辑功能会在2.4.0后续的beta版里扩充，届时可以实现批量编辑

**Comment by StruggleYang** [comment]
> 相册编辑功能会在2.4.0后续的beta版里扩充，届时可以实现批量编辑

good

**Comment by mouyong** [comment]
是按照图床区分相册后进行批量修改吗？

不同图床域名不一样。会不会把别的图床的也改了。

**Comment by Molunerfinn** [comment]
> 是按照图床区分相册后进行批量修改吗？
> 
> 不同图床域名不一样。会不会把别的图床的也改了。

会区分类型

**Comment by Molunerfinn** [comment]
v2.4.0-beta.5 已支持

**Comment by StruggleYang** [comment]
> v2.4.0-beta.5 已支持

感谢

**Comment by Aliroe** [comment]
@Molunerfinn 能不能优化一下，加个域名后缀呢，也有通过
`www.URL.com/FILE/TIME`的方式进行修改

**Comment by rayangl** [comment]
> @Molunerfinn 能不能优化一下，加个域名后缀呢，也有通过 `www.URL.com/FILE/TIME`的方式进行修改

+1
改变了图库存放位置，也需要批量修改
