### ISSUE TITLE
[Bug]: 重装软件后，之前上传的图片无法在软件相册显示，只能重新上传才能显示

### ISSUE THREAD

**Issue by yikexiaoyao** [Molunerfinn/PicGo#878]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [X] [Issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)

### PicGo的版本 | PicGo Version

v2.3.0

### 系统信息 | System Information

Windows

### 问题重现 | Bug reproduce

重装软件后，之前上传的图片无法在软件相册中显示，只能重新上传才能显示，不知道是我操作不当还是软件本身的问题，希望帮忙解答，谢谢

**Comment by Molunerfinn** [comment]
两种可能 一种是之前的相册文件损坏 后续启动的时候会删掉重建

另一种是相册文件丢失

还有就是使用了某种同步插件导致

**Comment by qiao-summer** [comment]
我也有这个问题,请问怎么解决呢?之前上传成功的图片在picgo都看不到了
