### ISSUE TITLE
[Feature]: 建议将picgo-plugin-github-plus插件的同步删除功能整合进入软件本体

### ISSUE THREAD

**Issue by yikexiaoyao** [Molunerfinn/PicGo#879]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [X] [Issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)

### PicGo的版本 | PicGo Version

v2.3.0

### 系统信息 | System Information

Windows

### 功能请求 | Feature request

提议希望能将picgo-plugin-github-plus插件的同步删除功能整合进入软件本体，省得多安装一个插件，毕竟同步增删属于基础功能，个人拙见，不当之处敬请谅解

**Comment by Molunerfinn** [comment]
不考虑
