### ISSUE TITLE
单个图床多个配置

### ISSUE THREAD

**Issue by Lxjazni7** [Molunerfinn/PicGo#88]
## 问题类型

Feature Request

## 功能请求

希望单个图床可以添加多个配置 因为有个人的账号 和 公司的账号:)

**Comment by Molunerfinn** [comment]
请问你看了FAQ了吗？
![image](https://user-images.githubusercontent.com/12621342/43621023-00f5bbba-9708-11e8-8b48-6c10ae331282.png)
