### ISSUE TITLE
[Bug]: mac打开picgo不显示菜单

### ISSUE THREAD

**Issue by neoalvin** [Molunerfinn/PicGo#883]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [X] [Issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)

### PicGo的版本 | PicGo Version

v.2.3.0

### 系统信息 | System Information

Mac

### 问题重现 | Bug reproduce

1.安装后打开顶部出现picgo图标, 但是右键不显示菜单, 没办法打开主页面
<img width="251" alt="image" src="https://user-images.githubusercontent.com/15117317/163924012-d7e2bb56-6e56-4c8f-b741-b193c4cb2f55.png">

2.看过这个FAQ, 但是当前的问题是只显示上面图中那样, 并没有可以点击的地方(右键, 双击各种点击操作都试过了, 都只显示上面的界面)
<img width="1080" alt="image" src="https://user-images.githubusercontent.com/15117317/163924359-749ae3ea-56ab-4609-a19f-37ccc9a3c0cc.png">
<img width="844" alt="image" src="https://user-images.githubusercontent.com/15117317/163924447-8b2a4307-b2cd-406c-8ab0-bee837934085.png">

### 相关日志 | Logs

picgo.log中只打印了一行端口监听的日志

[PicGo INFO] [PicGo Server] is listening at 36677

**Comment by Molunerfinn** [comment]
算了以后这个界面我加个按钮吧...

**Comment by travelerly** [comment]
我刚刚遇到类似的问题，我的电脑甚至连菜单栏上的图标都没有，beta 版本安装后直接显式损坏。但经过反复的安装、卸载、重启电脑，(稳定版本)目前是可以使用了

**Comment by ChangQingAAS** [comment]
+1

**Comment by killdayu** [comment]
+1

**Comment by killdayu** [comment]
> 算了以后这个界面我加个按钮吧...

请问beta4修复了吗？

**Comment by Molunerfinn** [comment]
beta.4已经修复

**Comment by Csrayz** [comment]
> 为什么我的打开，顶部菜单栏也没有图标，但是程序是一直在运行的，用的是beta4版本

同样，第一次安装后有顶部菜单栏，后续再也没有出现过。
设备MBAir 2022 M2

**Comment by lei025** [comment]
> > 为什么我的打开，顶部菜单栏也没有图标，但是程序是一直在运行的，用的是beta4版本
> 
> 同样，第一次安装后有顶部菜单栏，后续再也没有出现过，但看后台程序是在运行的。 设备MBAir 2022 M2

我也是 安装之后连状态栏都没显示过，后台进程在

设备MBAir 2022 M2

**Comment by Csrayz** [comment]
> > > 为什么我的打开，顶部菜单栏也没有图标，但是程序是一直在运行的，用的是beta4版本
> > 
> > 
> > 同样，第一次安装后有顶部菜单栏，后续再也没有出现过，但看后台程序是在运行的。 设备MBAir 2022 M2
> 
> 我也是 安装之后连状态栏都没显示过，后台进程在
> 
> 设备MBAir 2022 M2

我目前用的2.3.0正式版的intel版正常。

**Comment by dwqstart** [comment]
> > > > 为什么我的打开，顶部菜单栏也没有图标，但是程序是一直在运行的，用的是beta4版本
> > > 
> > > 
> > > 同样，第一次安装后有顶部菜单栏，后续再也没有出现过，但看后台程序是在运行的。 设备MBAir 2022 M2
> > 
> > 
> > 我也是 安装之后连状态栏都没显示过，后台进程在
> > 设备MBAir 2022 M2
> 
> 我目前用的2.3.0正式版的intel版正常。

我刚开始也这样，多打开几次就好了，没反应时候结束进程

**Comment by sparkaochong** [comment]
我的是M1 PRO芯片，安装的是picgo正式版，程序运行后顶部菜单栏不显示图标，后台程序是一直在运行的。

**Comment by xinning1228** [comment]
我是m1pro芯片，picgo测试，及brew install picgo版本，程序运行后没有任何反应，后台一直在运行，我很喜欢typora搭配它做图床，如果修复的话希望可以回复我一下。

**Comment by xinning1228** [comment]
我找到问题了didden bar软件会折叠顶部菜单栏，关掉后按照你说的步骤，现在可以正常运行了。
