### ISSUE TITLE
[Bug]: 2.3.0 在 M1 pro 机型上无法启动

### ISSUE THREAD

**Issue by travelerly** [Molunerfinn/PicGo#885]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [X] [Issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)

### PicGo的版本 | PicGo Version

2.3.0

### 系统信息 | System Information

Mac(arm64)

### 问题重现 | Bug reproduce

2.3.0 没有适配 M1 pro 机型吗？无法启动啊，2.3.1-beta.3 安装后直接显式已损坏

### 相关日志 | Logs

2.3.0 没有适配 M1 pro 机型吗？无法启动啊，2.3.1-beta.3 安装后直接显式已损坏

**Comment by travelerly** [comment]
经过反复的安装、卸载和重启电脑，目前是可以使用了。

**Comment by bruceeewong** [comment]
> 经过反复的安装、卸载和重启电脑，目前是可以使用了。

兄弟，这么玄学的吗，我也是安装显示损坏，难道试的出来？

**Comment by KngJmmy** [comment]
那么6的吗。。。我卸载安装重启电脑*3次都失败了。。。
