### ISSUE TITLE
[求助]: 是否支持gogs搭建的仓库

### ISSUE THREAD

**Issue by XieYuDeGitHub** [Molunerfinn/PicGo#888]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [X] [Issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)

### PicGo的版本 | PicGo Version

PicGo-core 1.4.7

### 系统信息 | System Information

Windows

### 功能请求 | Feature request

我最近搭了个gogs仓库，像用它做图床，但是一直报错
 {"message":"Bad credentials","documentation_url":"https://docs.github.com/rest"}
看了对应issue配置，作者说配置有问题，我反复对比了配置应该没问题，因为我在这个配置的基础上改一下就能提交GitHub
贴一下配置文件
![image](https://user-images.githubusercontent.com/65640243/164628564-d3a9ee26-17e0-4bab-b896-ce00e6a193d2.png)

**Comment by Molunerfinn** [comment]
当然不支持，上传的接口调的都是github的，怎么传到你的gogs里。

**Comment by Molunerfinn** [comment]
有需求可以使用自定义web上传插件

**Comment by XieYuDeGitHub** [comment]
> 当然不支持，上传的接口调的都是github的，怎么传到你的gogs里。

好的谢谢
