### ISSUE TITLE
[求助]: 七牛云图床 `华东-浙江2` 该设置哪个存储区域?

### ISSUE THREAD

**Issue by gyhyfj** [Molunerfinn/PicGo#889]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [X] [Issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)

### PicGo的版本 | PicGo Version

v2.3.0

### 系统信息 | System Information

Windows

### 功能请求 | Feature request

七牛云图床 `华东-浙江2` 该设置哪个存储区域?
文档里只有这几个可选字段:
```"area": "z0" | "z1" | "z2" | "na0" | "as0", // 存储区域编号```
比如设置`z0`, 会提示: 
```
上传失败
incorrect region,please use up-cn-
east-2.qiniup.com,bucket is:yachen-web
```
```
上传失败
StatusCodeError:400-"{"error\":\"incorrect
region,please use up-cn-east-2.qiniup.com,
bucket is:yachen-web\"}"
at new StatusCodeError(D:\Program Files\Pi...
```

**Comment by Molunerfinn** [comment]
更新最新beta版本，解决了七牛新区上传出错的问题。

另外，有同样的issue在这里：https://github.com/Molunerfinn/PicGo/issues/863

请看完issue再发新的谢谢

**Comment by Molunerfinn** [comment]
文档会尽快更新七牛的区域链接
