### ISSUE TITLE
Win10下上传图片缩略图提示显示是第一次上传的图片

### ISSUE THREAD

**Issue by cooper1x** [Molunerfinn/PicGo#89]
## 问题类型
Bug Report & Feature Request

## PicGo的相关信息
Windows 10 X64 1803
版本 PicGo 1.6.1

## 问题重现
在关闭Windows`专注模式`后，可以看到上传图片的提示，提示框里面有上传图片的缩略图，这个出现的比进度条完成后要慢一些。第一次没有问题，第二次进行同样的操作，会发现提示里面的缩略图还是第一张的，但是上传后的图是正确的，是第二张。测试过第三张新图片上传，提示缩略图还是第一张的……

![](https://shuxinfeblog-1251131656.cos.ap-chengdu.myqcloud.com/20180808094515.png)

另外还有一个小bug，打开一张webp格式的图片，然后右键复制，通过剪切板上传的变成了png格式，而拖拽上传格式不变是正常的。

## 功能请求
1、相册实时更新
刚刚发现如果窗口停留在相册选项，那么刚刚上传的图片是不会实时更新到这里的，必须切换一下选项，回到相册才会看到刚刚上传过的图片。

2、相册删除图片同步到cos
相册里面有个删除功能，但是删除的只是软件里面的，并不能删掉cos里面，所以需要登录cos客户端或者网页进行手动删除，不是很方便，希望能够添加这个功能，只是不知道官方是否有提供删除指定文件的API。

**Comment by Molunerfinn** [comment]
1. 缩略图这个是因为WIN10的通知栏的问题。多发的通知在前一个通知未消失的时候不会顶替它。
2. 剪贴板上传的图片只能是png格式，这是electron剪贴板api的限制。
3. 实时更新可以考虑实现。
4. 
![image](https://user-images.githubusercontent.com/12621342/43811754-c5d4f2e8-9af0-11e8-807e-379fba588807.png)

**Comment by cooper1x** [comment]
两次上传的间隔有1分钟左右吧，第一次的通知消失了一段时间，后面的上传还是会出现第一次的。

**Comment by Molunerfinn** [comment]
@cooper1x 似乎是electron的notification模块的问题。不过在electron 的[v1.8.2-beta](https://github.com/electron/electron/issues/9935)版本似乎已经解决。我需要再检查一下构建版本的electron。

**Comment by Molunerfinn** [comment]
嗯构建版本是v1.8.1，下个版本需要升级一下构建版本应该就没问题了。
