### ISSUE TITLE
[Bug]: mac无法安装

### ISSUE THREAD

**Issue by QY-Sheila** [Molunerfinn/PicGo#890]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [X] [Issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)

### PicGo的版本 | PicGo Version

v2.3.1-beta

### 系统信息 | System Information

Mac

### 问题重现 | Bug reproduce

安装好后，打不开，电脑显示，mac无法确认是否包含恶意软件，导致安装结束后无法打开。

**Comment by Molunerfinn** [comment]
之前的issue已有解决方案
