### ISSUE TITLE
[Bug]: Mac无法安装pico

### ISSUE THREAD

**Issue by QY-Sheila** [Molunerfinn/PicGo#891]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [X] [Issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)

### PicGo的版本 | PicGo Version

v.23.0-beta 3

### 系统信息 | System Information

Mac

### 问题重现 | Bug reproduce

<img width="320" alt="image" src="https://user-images.githubusercontent.com/102791275/165234955-bbb91d9b-221a-4582-86ca-f4ab49aa851d.png">

### 相关日志 | Logs

我的问题并不是找不到图标，而是安装后根本打不开。

**Comment by Molunerfinn** [comment]
https://github.com/Molunerfinn/PicGo/issues/814

**Comment by Molunerfinn** [comment]
可以谷歌搜索 mac安装未签名软件
