### ISSUE TITLE
[Feature]: 个人感觉这头部三个按钮用起来有点拥挤，望改进谢谢👍

### ISSUE THREAD

**Issue by CoderFXJ** [Molunerfinn/PicGo#897]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [X] [Issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)

### PicGo的版本 | PicGo Version

v2.3.0

### 系统信息 | System Information

Windows

### 功能请求 | Feature request

![image](https://user-images.githubusercontent.com/68853957/166089565-0682d7ed-c309-45f7-a293-3e0bb1cf6771.png)

个人感觉这头部三个按钮用起来有点拥挤, 相隔太近, 一不小心就点错了, 
头部区域空余空间挺多的, ,但是这几个按钮太靠边缘, 没有垂直居中强迫症看起来有点难受额
望改进, 谢谢!

**Comment by Molunerfinn** [comment]
感谢反馈 后续会做ui优化再一并看看
