### ISSUE TITLE
[Feature]:  是否可以在后续某个版本增加一个支持本地路径的存储方式。

### ISSUE THREAD

**Issue by paopaohll** [Molunerfinn/PicGo#898]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [X] [Issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)

### PicGo的版本 | PicGo Version

v2.3.0-beta1

### 系统信息 | System Information

Windows

### 功能请求 | Feature request

目前picgo 已经很强大的支持了好多平台的存储，是否可以在后续增加一个类似pichome的本地路劲存储的方式

**Comment by Molunerfinn** [comment]
这个可以用插件实现 应该不会在本体处理

**Comment by Molunerfinn** [comment]
可以去插件评论区发
