### ISSUE TITLE
[Feature]: 请URL上传时支持webp

### ISSUE THREAD

**Issue by jakkpop** [Molunerfinn/PicGo#899]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [X] [Issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)

### PicGo的版本 | PicGo Version

v2.3

### 系统信息 | System Information

Windows

### 功能请求 | Feature request

在线转换不同格式时，直接url上传比较方便，但是webp不支持，一直报错，还需要下载到本地才能上传。
希望可以开放这个webp的url上传。
Error: https://s4.aconvert.com/convert/p3r68-cdx67/xxx.webp is not image

**Comment by Molunerfinn** [comment]
可以考虑支持

**Comment by Molunerfinn** [comment]
测试了一下，正常的webp格式图片的url是能够上传的。

你这边的这个链接，可能请求头里没有声明是一张图片，所以被picgo拦下来了。可以提供一下可以访问的链接。另外如果链接是需要认证才能访问的，picgo大概率也是无法获取到图片的。picgo上传url图片的方式本质上也是先下载再上传。

正常图片的响应头：
![image](https://user-images.githubusercontent.com/12621342/172882695-34e85247-e453-41ef-86f2-479fc5072eaf.png)

picgo处理URL的方式：
![image](https://user-images.githubusercontent.com/12621342/172882792-c036d57b-c81d-4632-b4c7-e4fbb79b6cd7.png)
