### ISSUE TITLE
个人用户上传后的链接方式

### ISSUE THREAD

**Issue by xtsui** [Molunerfinn/PicGo#9]
请问我是个人用户，上传图片后，获得的连接方式是http的还是https的？个人博客由于是https的，所以博文里面的图文链接也最好是https的。看演示图里面最后显示的链接是https的，请问是默认的吗？谢谢。

**Comment by Molunerfinn** [comment]
1. 微博图床默认https
2. 其余图床的链接都是你自己指定的，http或者https都是你自己的云服务提供的。如果你有https就可以，如果没有就没有。详情可以查看[wiki](https://github.com/Molunerfinn/PicGo/wiki/%E8%AF%A6%E7%BB%86%E7%AA%97%E5%8F%A3%E7%9A%84%E4%BD%BF%E7%94%A8)
