### ISSUE TITLE
[Bug]: 相册中复制按钮报错

### ISSUE THREAD

**Issue by lijyze** [Molunerfinn/PicGo#901]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [X] [Issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)

### PicGo的版本 | PicGo Version

v2.3.1 - beta 3

### 系统信息 | System Information

Mac

### 问题重现 | Bug reproduce

点击相册中图片左下角的复制按钮，在文档中粘贴无效，打开控制台发现点击复制按钮后报错。

在单机应用图标后打开的界面中点击图片同样无法复制，但是会弹出复制成功的提示信息。

上传后自动复制地址是有效的。

### 相关日志 | Logs

Error: Error invoking remote method 'PASTE_TEXT': TypeError: Cannot read properties of undefined (reading 'replace')
    at EventEmitter.i.invoke (node:electron/js2c/renderer_init:61)
    at async a.copy (Gallery.vue:286)
at @ vue.runtime.esm.js:1897
ot @ vue.runtime.esm.js:1888
it @ vue.runtime.esm.js:1848
(anonymous) @ vue.runtime.esm.js:1865
Promise.catch (async)
rt @ vue.runtime.esm.js:1865
n @ vue.runtime.esm.js:2188
o._wrapper @ vue.runtime.esm.js:6961

**Comment by Molunerfinn** [comment]
收到 后续会修复
