### ISSUE TITLE
[Bug]: MacBook Pro 2021 上传之后，粘贴板无链接

### ISSUE THREAD

**Issue by Foundation-Maker** [Molunerfinn/PicGo#902]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [X] [Issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)

### PicGo的版本 | PicGo Version

V2.3.0和2.3.1beta

### 系统信息 | System Information

Mac(arm64)

### 问题重现 | Bug reproduce

一：第一次安装，菜单栏全黑，没有选项；通过反复安装解决；
二：上传之后，可以返回链接，粘贴板没有，通过插件，暂时解决；
三：相册空白，没有东西。
不论是七牛云，还是又拍云，都是这样。朋友的电脑也是macbook 2021,同样的问题。

### 相关日志 | Logs

有返回链接；无报错日志

**Comment by Molunerfinn** [comment]
删掉配置目录同级的picgo.db文件再重启既可

**Comment by Foundation-Maker** [comment]
以解决；
