### ISSUE TITLE
关于日志文件非常非常大的问题

### ISSUE THREAD

**Issue by boy-maofeiyu** [Molunerfinn/PicGo#903]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [X] [Issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)

### PicGo的版本 | PicGo Version

最新版本

### 系统信息 | System Information

Windows

### 问题重现 | Bug reproduce

强烈建议你们把日志的级别好好处理一下,我c盘一直爆满一直没找到原因,才发现,picgo一个日志文件在C:\Users\Administrator\AppData\Roaming\picgo\picgo.log里面,这个日志文件三十多个G,然后我刚删完几天,又十几个g了,你们这个日志开的啥级别啊救命C盘受不了啊\
![1652268358710](https://user-images.githubusercontent.com/78846547/167838573-916b4867-d1e7-4f04-8e47-269769d91678.jpeg)

![image](https://user-images.githubusercontent.com/78846547/167838465-3fbec74d-927f-408d-bd52-bfbdf6b11854.png)

### 相关日志 | Logs

强烈建议你们把日志的级别好好处理一下,我c盘一直爆满一直没找到原因,才发现,picgo一个日志文件在C:\Users\Administrator\AppData\Roaming\picgo\picgo.log里面,这个日志文件三十多个G,然后我刚删完几天,又十几个g了,你们这个日志开的啥级别啊救命C盘受不了啊\
![1652268358710](https://user-images.githubusercontent.com/78846547/167838573-916b4867-d1e7-4f04-8e47-269769d91678.jpeg)

![image](https://user-images.githubusercontent.com/78846547/167838465-3fbec74d-927f-408d-bd52-bfbdf6b11854.png)

**Comment by Molunerfinn** [comment]
可以删掉，然后更新最新beta版本 会处理写日志死循环问题
