### ISSUE TITLE
[Bug]: picgo 上传图片成功后无法预览

### ISSUE THREAD

**Issue by elan-L** [Molunerfinn/PicGo#906]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [X] [Issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)

### PicGo的版本 | PicGo Version

v2.3.0

### 系统信息 | System Information

Windows

### 问题重现 | Bug reproduce

使用平台：Windows10 + picgo2.3.0 + 插件gitee-uploader 1.1.2
![image](https://user-images.githubusercontent.com/44642677/169042063-7f63abca-217a-43b2-9fcb-95909bfe051e.png)

之前是配置了解决Typora文件导入csdn图片出错的问题，使用了很久一直没有问题，今天打开一个md文档，发现所有的图片都无法预览了
![image](https://user-images.githubusercontent.com/44642677/169042272-8367adf0-4aad-4da8-bff4-8bbca7a83c52.png)

在PicGo中也无法预览，
我卸载后重装了picGo
依然是这个问题
![image](https://user-images.githubusercontent.com/44642677/169042510-48586e5d-c770-456c-8c18-294c7d82babc.png)

![image](https://user-images.githubusercontent.com/44642677/169042474-322eb2e4-51df-4f82-bb83-41c981657ce3.png)

但是上传是成功的
在gitee中可以看到
![image](https://user-images.githubusercontent.com/44642677/169042634-fd622a20-ce04-4c5b-9b22-98d30b253295.png)

日志中也没有有用的信息
![image](https://user-images.githubusercontent.com/44642677/169042774-d0d7ebc4-cb5d-4f18-b651-787dd2adf497.png)

在网上也没有找到相关的解决方案

**Comment by Molunerfinn** [comment]
因为gitee官方做了限制。跟picgo无关。

**Comment by elan-L** [comment]
received

**Comment by elan-L** [comment]
谢谢, 已经改用阿里云解决了问题
