### ISSUE TITLE
[Feature]: 增加一个是否静默启动的开关

### ISSUE THREAD

**Issue by Gahotx** [Molunerfinn/PicGo#915]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [X] [Issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [x] [FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)

### PicGo的版本 | PicGo Version

v2.3.0

### 系统信息 | System Information

Windows

### 功能请求 | Feature request

现在PicGo启动是完全静默，没有任何窗口，对于习惯使用拖拽上传的用户好不方便，希望能增加一个开关让用户自行选择
1. 完全静默
2. 默认打开主窗口
3. 默认打开mini窗口 (如果能提供默认在右下角或者记录上次的位置就更好了，居中有点挡视野
> 看之前的老issue #105 说可能会保留启动时打开mini窗口，不知道是不是只有开机自启才会，我正常打开是没有mini窗口

**Comment by Molunerfinn** [comment]
会的 这块会做优化 感谢反馈

**Comment by Molunerfinn** [comment]
下个 beta 版本会添加这个配置。非 macOS 用户会提供展示 mini 窗口的选项。下图是 macOS （没有 mini 窗口的选项）

<img width="912" alt="image" src="https://github.com/Molunerfinn/PicGo/assets/12621342/16399b7b-7ae1-4776-9077-8d3c932bbb48">
