### ISSUE TITLE
Github图床中svg文件的markdown链接问题

### ISSUE THREAD

**Issue by guoang** [Molunerfinn/PicGo#92]
## 问题类型

Bug Report

## PicGo的相关信息
Version：1.6.1
OS: Mac

## 问题重现

github图床上传任意svg文件，在相册中显示为空，并且markdown链接无效

![image](https://user-images.githubusercontent.com/1219091/43891219-5cc11ad2-9bfb-11e8-8180-38073efd824e.png)

## 修复建议
现有的markdown链接格式为：
https://raw.githubusercontent.com/guoang/pic/master/test.svg
应改为：
https://raw.githubusercontent.com/guoang/pic/master/test.svg?sanitize=true

参见：
https://stackoverflow.com/questions/13808020/include-an-svg-hosted-on-github-in-markdown

**Comment by Molunerfinn** [comment]
这个就自己单独编辑吧，其实不是用来传矢量图格式的。


 :octocat: [From gitme iOS](http://flutterchina.club/app/gm.html)

**Comment by guoang** [comment]
非矢量图用这种后缀也不会有问题。
markdown我可以自己编辑，但主要蛋疼的是图片在相册界面显示不出来，copy链接的时候分不清哪个是哪个

**Comment by Molunerfinn** [comment]
因为相册用的是Img标签显示图片的。svg在现有框架内无法很好显示，不推荐使用。


 :octocat: [From gitme iOS](http://flutterchina.club/app/gm.html)
