### ISSUE TITLE
[Bug]: Mac M1 Pro貌似无法使用

### ISSUE THREAD

**Issue by jinfagang** [Molunerfinn/PicGo#920]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [X] [Issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)

### PicGo的版本 | PicGo Version

v2.3.0

### 系统信息 | System Information

Mac(arm64)

### 问题重现 | Bug reproduce

<img width="255" alt="image" src="https://user-images.githubusercontent.com/21303438/172043860-930c202d-7891-4625-9c3a-9076a4e15772.png">

### 相关日志 | Logs

无

**Comment by Molunerfinn** [comment]
没上传图片显示为空是正常的。右键顶部picgo图标可以出菜单
