### ISSUE TITLE
[Bug]: picgo 2.3.0 crashed on Pop OS 22.04

### ISSUE THREAD

**Issue by kamusis** [Molunerfinn/PicGo#921]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [X] [Issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)

### PicGo的版本 | PicGo Version

PicGo-2.3.0.AppImage

### 系统信息 | System Information

Linux

### 问题重现 | Bug reproduce

Pop OS 22.04 is a modified version of Ubuntu 22.04 with Nvidia driver support.
download the AppImage
```
$ sudo cp PicGo-2.3.0.AppImage /usr/local/bin/picgo
$ chmod a+x /usr/local/bin/picgo
$ picgo
on ready
[14040:0606/001407.335861:FATAL:gpu_data_manager_impl_private.cc(894)] The display compositor is frequently crashing. Goodbye.
Trace/breakpoint trap (core dumped)

```

**Comment by Molunerfinn** [comment]
https://github.com/jessedp/tablo-tools-electron/issues/104

try this:

![image](https://user-images.githubusercontent.com/12621342/172877978-453be989-1ce5-49f0-8c4d-64992af4a571.png)

**Comment by kamusis** [comment]
> [jessedp/tablo-tools-electron#104](https://github.com/jessedp/tablo-tools-electron/issues/104)
> 
> try this:
> 
> ![image](https://user-images.githubusercontent.com/12621342/172877978-453be989-1ce5-49f0-8c4d-64992af4a571.png)

Thanks for the reply. I've used PicGo-Core instead of PicGo.
