### ISSUE TITLE
[Feature]: 自定义域名添加后缀

### ISSUE THREAD

**Issue by ShiXinBoy** [Molunerfinn/PicGo#923]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [X] [Issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)

### PicGo的版本 | PicGo Version

2.3.0

### 系统信息 | System Information

Windows

### 功能请求 | Feature request

希望可以让在自定义域名的后面添加字符
例如：
自定义域名为：
https://github.com/ShiXinBoy/picbed/blob/main
图片名为202203281800321.png
我希望在图片名后添加 ?raw=true
https://github.com/ShiXinBoy/picbed/blob/main/202206101114754.png?raw=true

**Comment by Molunerfinn** [comment]
你可以使用自定义链接添加后缀。以及我记得有些插件好像已经实现了类似的功能，可以去搜索使用
