### ISSUE TITLE
[Bug]: 批量上传图片突然报错

### ISSUE THREAD

**Issue by nonozone** [Molunerfinn/PicGo#925]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [X] [Issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)

### PicGo的版本 | PicGo Version

v2.3.0  & v2.3.1

### 系统信息 | System Information

Windows

### 问题重现 | Bug reproduce

![image](https://user-images.githubusercontent.com/1277444/173610927-b9b01308-658b-4dbb-be5e-12307fa6d3c4.png)
在一篇文章里插入批量插入多个图片，上传到一般，软件报错，重新安装了v2.3.1也不行。重启电脑，依然有问题。

根据提示检查了下，\AppData\Roaming\picgo里 只有 data.jaon 这个文件，没有同名文件夹。

### 相关日志 | Logs

额，现在软件都无法正常打开了。

**Comment by Molunerfinn** [comment]
2.3.1你装的哪个版本？最新版应该不会有这个报错才对。

**Comment by nonozone** [comment]
> 2.3.1你装的哪个版本？最新版应该不会有这个报错才对。

[2.3.1-beta.4](https://github.com/Molunerfinn/PicGo/releases/tag/v2.3.1-beta.4)  x64版本。

其实之前的2.3.0正式版用的好好的，就昨天用到一半突然就不行了。

**Comment by Molunerfinn** [comment]
beta.4的话，也是这个弹窗？这有点奇怪，因为至少在beta.3里就已经[修复](https://github.com/Molunerfinn/PicGo/commit/6b6ae27)了这个日志路径错误的问题。

注意看看你安装的时候的路径，直接找到安装路径里的picgo.exe打开看看。可能你安装了beta.4但是安装在了另一个路径，然后你依然打开的是你之前安装的2.3.0的版本。

另外，这个问题在之前出现过，大概的原因是配置文件或者相册文件写入失败导致的报错。可以把配置文件data.json以及相册文件picgo.db删掉再重启picgo即可。配置文件所在路径参考文档。

**Comment by nonozone** [comment]
> beta.4的话，也是这个弹窗？这有点奇怪，因为至少在beta.3里就已经[修复](https://github.com/Molunerfinn/PicGo/commit/6b6ae27)了这个日志路径错误的问题。
> 
> 注意看看你安装的时候的路径，直接找到安装路径里的picgo.exe打开看看。可能你安装了beta.4但是安装在了另一个路径，然后你依然打开的是你之前安装的2.3.0的版本。
> 
> 另外，这个问题在之前出现过，大概的原因是配置文件或者相册文件写入失败导致的报错。可以把配置文件data.json以及相册文件picgo.db删掉再重启picgo即可。配置文件所在路径参考文档。

果然还是要删除这两个文件才可以。顺便问下，之前配置的  图床配置 是在哪个文件？ 我找了下，好像data.bak.json里没有。

**Comment by Molunerfinn** [comment]
删掉了之后，你重启的时候data.bak.json已经是重启后新建的默认配置文件的备份文件了。

配置文件写会出现失败的问题，预计会在beta.5里引入原子操作来修复。相册文件的读写已经在beta.4里处理了。

备份文件的逻辑后续也要重构一下，所以目前你重新配置后可以自己保留一份配置文件，后续如果再出现这个问题，先临时修复一下
