### ISSUE TITLE
[Bug]: 软件自己生成了将近74G的日志

### ISSUE THREAD

**Issue by 1010n111** [Molunerfinn/PicGo#926]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [X] [Issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)

### PicGo的版本 | PicGo Version

2.3.1 beta3

### 系统信息 | System Information

Windows

### 问题重现 | Bug reproduce

![image](https://user-images.githubusercontent.com/14970614/174258145-d9b6c3be-9bc7-4cd8-be70-12704b5a2d56.png)
使用频率不高,
大概两星期一次,
每次上传最多5张图片

### 相关日志 | Logs

日志放 百度云 了
链接: https://pan.baidu.com/s/10_QIIQJx-cvGz9tUA3KPFg?pwd=eaga 提取码: eaga 复制这段内容后打开百度网盘手机App，操作更方便哦

**Comment by Molunerfinn** [comment]
之前的版本有写入日志死循环的问题已经修复了

**Comment by Molunerfinn** [comment]
删了日志文件重启picgo即可
