### ISSUE TITLE
自定义响应头

### ISSUE THREAD

**Issue by gaofeilongdev** [Molunerfinn/PicGo#928]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [X] [Issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)

### PicGo的版本 | PicGo Version

v2.3.0

### 系统信息 | System Information

Windows

### 功能请求 | Feature request

能否新增一个功能自定义响应头，比如阿里云oss使用默认域名他是下载的模式，但是自定义响应头后能覆盖这个默认操作

**Comment by Molunerfinn** [comment]
1.5.0的picgo-core已经支持插件自定义header。
