### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by nonozone** [Molunerfinn/PicGo#929]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [X] [Issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)

### PicGo的版本 | PicGo Version

v2.3.1 beta4

### 系统信息 | System Information

Windows

### 问题重现 | Bug reproduce

最新beta4的重命名插件，配置无法保存或者生效。

![image](https://user-images.githubusercontent.com/1277444/174484233-922ae76d-99cd-481c-aeb2-149aea857721.png)

在重命名插件里 输入配置之后，保存，再进去又变成空的了。

**Comment by Molunerfinn** [comment]
后续会看看

**Comment by Molunerfinn** [comment]
跟 #943 重复，先关闭
