### ISSUE TITLE
Ubuntu版本腾讯云图册没有图片

### ISSUE THREAD

**Issue by MetaRunning** [Molunerfinn/PicGo#94]
## 问题类型
Bug Report

## PicGo的相关信息
v1.6.1 Ubuntu

## 问题重现
![image](https://user-images.githubusercontent.com/29190061/44083677-431ef514-9fe7-11e8-8ffa-a2e9383b45f6.png)

## 功能请求

目前只用过Ubuntu版本，不知道这个是不是腾讯云不支持还是因为平台的原因、

---

**Comment by Molunerfinn** [comment]
你要在软件里上传了才有啊。这个跟远端不是双向同步的，这个相册是本地相册，只有在本地上传了才会出现。

**Comment by MetaRunning** [comment]
我在本地上传了啊。。

**Comment by Molunerfinn** [comment]
@MetaRunning 嗯？没有遇到过，我Linux测试也是在Ubuntu下的，回头看看什问题，这两天放假😂


 :octocat: [From gitme iOS](http://flutterchina.club/app/gm.html)
