### ISSUE TITLE
[Bug]: 代理工作不正常

### ISSUE THREAD

**Issue by robert6277** [Molunerfinn/PicGo#940]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [X] [Issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)

### PicGo的版本 | PicGo Version

v2.3.0

### 系统信息 | System Information

Windows

### 问题重现 | Bug reproduce

使用 github 图床，上传显示**上传成功**，但是 picgo 相册以及 typora 图片无法显示，猜测是网络原因。尝试使用 picgo 自带的代理 http:127.0.0.1/端口 或者使用 proxifier 接管了 picgo.exe 的代理，但是问题**依旧**。尝试开启全局代理后**能够**正常显示，但不想用全局代理，应该如何配置 (/_ \)

![](https://raw.githubusercontent.com/robert6277/pic/main/20220718120032.png)

![](https://raw.githubusercontent.com/robert6277/pic/main/20220718115316.png)

![](https://raw.githubusercontent.com/robert6277/pic/main/20220718120009.png)

### 相关日志 | Logs

未显示报错
```
2022-07-18 12:03:04 [PicGo INFO] Before transform 
2022-07-18 12:03:04 [PicGo INFO] Transforming... Current transformer is [path] 
2022-07-18 12:03:04 [PicGo INFO] Before upload 
2022-07-18 12:03:04 [PicGo INFO] beforeUploadPlugins: renameFn running 
2022-07-18 12:03:04 [PicGo INFO] Uploading... Current uploader is [github] 
2022-07-18 12:03:07 [PicGo SUCCESS] 
https://raw.githubusercontent.com/robert6277/pic/main/20220718120303.png 
```

**Comment by Molunerfinn** [comment]
上传成功后图片显不显示是与你网络环境有关 跟picgo没关系

**Comment by robert6277** [comment]
> 上传成功后图片显不显示是与你网络环境有关 跟picgo没关系

感谢！那请问应当如何设置代理呢？已阅读 doc，使用 clash for windows

**Comment by Molunerfinn** [comment]
picgo的代理设置只是上传代理 图片显示与否与你本机的网络环境或者代理有关。换句话说你上传到一个被gfw拦下来的地方不能显示不是很正常么？

**Comment by robert6277** [comment]
> picgo的代理设置只是上传代理 图片显示与否与你本机的网络环境或者代理有关。换句话说你上传到一个被gfw拦下来的地方不能显示不是很正常么？

谢谢
