### ISSUE TITLE
[Bug]: M1 mbp 上的重命名插件配置无法保存

### ISSUE THREAD

**Issue by nonozone** [Molunerfinn/PicGo#943]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [X] [Issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)

### PicGo的版本 | PicGo Version

Version: 2.3.1-beta.4

### 系统信息 | System Information

Mac(arm64)

### 问题重现 | Bug reproduce

之前windows上一直用typroa配合picgo，现在换到m1最新的mbp上，发现重命名插件无法保存配置，就是填写好参数之后，关闭，再进去，又变成空白啦。

<img width="800" alt="image" src="https://user-images.githubusercontent.com/1277444/180595731-b4bd8f52-db80-4c9a-b651-cd9313074c23.png">

另外有一个问题还想请教下，在Windows下面，直接把文件拖到typora就自动上传了，在mac上，图片拖进来，还要右键点击上传才可以，只能这样了？

**Comment by Molunerfinn** [comment]
配置无法生效的问题后续版本会修复。可以先手动修改配置文件再重启picgo。

typora的问题请去typora的仓库提问

**Comment by Molunerfinn** [comment]
可以先手动修改配置如下（修改完后重启PicGo）：

![image](https://user-images.githubusercontent.com/12621342/182021745-b1f92ef4-69af-4436-8d06-1f11a43a0cb4.png)

这个bug的修复已经提交，下个版本会修复。
