### ISSUE TITLE
[Feature]: Mac menubar的图标能重新设计一下吗

### ISSUE THREAD

**Issue by mashirozx** [Molunerfinn/PicGo#944]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [X] [Issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)

### PicGo的版本 | PicGo Version

v2.3.1

### 系统信息 | System Information

Mac(arm64)

### 功能请求 | Feature request

<img width="616" alt="image" src="https://user-images.githubusercontent.com/16148054/180917762-f0217bb1-1b67-43f2-b9d7-a575d9977704.png">
和mac的图标风格极不协调

**Comment by Molunerfinn** [comment]
跟 #776 重复，下个版本更新
