### ISSUE TITLE
[Bug]: 个人配置没了 

### ISSUE THREAD

**Issue by liwenfengg** [Molunerfinn/PicGo#945]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [X] [Issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)

### PicGo的版本 | PicGo Version

v2.3.1-beta.3

### 系统信息 | System Information

Windows

### 问题重现 | Bug reproduce

配置自己都没了 恢复了默认啥都没有的样子

**Comment by Molunerfinn** [comment]
配置丢失的问题，下个beta版本会引入原子操作解决

**Comment by Molunerfinn** [comment]
下个版本会修复，commit已提交，等待后续版本更新
