### ISSUE TITLE
微博图床怎么开启

### ISSUE THREAD

**Issue by likepoems** [Molunerfinn/PicGo#946]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [X] [Issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)

### PicGo的版本 | PicGo Version

v2.3.0

### 系统信息 | System Information

Windows

### 问题重现 | Bug reproduce

找不到微博图床入口

### 相关日志 | Logs

无

**Comment by Molunerfinn** [comment]
很早以前微博图床开启了防盗链之后就下掉了。
