### ISSUE TITLE
[Bug]: 重命名图片的时候点击取消上传依旧显示上传成功

### ISSUE THREAD

**Issue by zhangkanqi** [Molunerfinn/PicGo#947]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [X] [Issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)

### PicGo的版本 | PicGo Version

2.3.1-beta.4

### 系统信息 | System Information

Mac

### 问题重现 | Bug reproduce

上传图片重命名的时候，点击取消上传依旧显示上传成功，但实际上阿里云OSS中并没有成功上传该图片。

**Comment by Molunerfinn** [comment]
点击取消只是取消重命名 并不是取消上传。会以默认名字上传。
