### ISSUE TITLE
[Bug]: 设置了自定义链接格式但粘贴的时候仍是![$fileName]($url)

### ISSUE THREAD

**Issue by zhangkanqi** [Molunerfinn/PicGo#948]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [X] [Issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)

### PicGo的版本 | PicGo Version

2.3.1-beta.4

### 系统信息 | System Information

Mac

### 问题重现 | Bug reproduce

设置了自定义链接格式为<img src="$url">，但图片成功上传后，点击成功上传的图片，复制链接，command+v粘贴的时候仍是![$fileName]($url)，而不是自定义的链接格式。

**Comment by zhangkanqi** [comment]
command+v粘贴的时候仍是!\[$fileName\]($url)，

**Comment by zhangkanqi** [comment]
设置了自定义链接格式为\<img src="$url"\>，

**Comment by Molunerfinn** [comment]
你的粘贴格式选了自定义了吗

**Comment by Molunerfinn** [comment]
![image](https://user-images.githubusercontent.com/12621342/182005021-b1797136-f383-4b77-88eb-8b652d461446.png)

请发issue前好好看看文档谢谢
