### ISSUE TITLE
[Feature]: 

### ISSUE THREAD

**Issue by cold-bin** [Molunerfinn/PicGo#951]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [X] [Issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)

### PicGo的版本 | PicGo Version

v2.3.1-beta3

### 系统信息 | System Information

Windows

### 功能请求 | Feature request

![EPRW6L`R(3XE(%AJS0F0HM1](https://user-images.githubusercontent.com/85239590/184073760-e94e8b99-5741-4bc0-9844-fafb57edbf62.png)
这是picgo的日志文件，可以考虑做一个切割日志，定期删除大文件的日志吗？picgo用久了，日志容易占磁盘资源

**Comment by Molunerfinn** [comment]
已经处理这个问题，下个版本会带出去。你可以删除它然后再重启picgo就行。
