### ISSUE TITLE
[Feature]: 可否设置上传图片的content-type?

### ISSUE THREAD

**Issue by Eve-Sama** [Molunerfinn/PicGo#954]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [X] [Issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)

### PicGo的版本 | PicGo Version

v2.3.0

### 系统信息 | System Information

Mac

### 功能请求 | Feature request

希望上传的时候可以支持自定义content-type. 我是使用阿里云OSS的, 我发现上传的链接在浏览器中打开是下载而不是预览. 查了下百度, 需要指定content-type为image/jpg. 可否设置上传的content-type呢?

**Comment by Molunerfinn** [comment]
PicGo是有设置aliyun的content-type的，不过看了一下aliyun应该只支持 `Content-Type` 而不是 `content-type`

<img width="819" alt="image" src="https://user-images.githubusercontent.com/12621342/185346457-dcf7106a-8602-4a3f-b400-69c59c3dd04d.png">

后续版本会改成大写的试试

**Comment by Eve-Sama** [comment]
这个是大小写问题导致的吗? 我不确定, 通过picGo上传的文件, 我通过oss-browser查看他的Content-Type显示是下面这样的.
![图片](https://user-images.githubusercontent.com/30228406/185390091-6f43582c-992f-49d8-ae78-cec0e0f279f0.png)

只要将其设置为image/jpeg就不会强制下载了.

**Comment by Molunerfinn** [comment]
> 这个是大小写问题导致的吗? 我不确定, 通过picGo上传的文件, 我通过oss-browser查看他的Content-Type显示是下面这样的.
> 
> ![图片](https://user-images.githubusercontent.com/30228406/185390091-6f43582c-992f-49d8-ae78-cec0e0f279f0.png)
> 
> 
> 
> 只要将其设置为image/jpeg就不会强制下载了.

我也不确定 不过看aliyun的文档好像确实没有针对小写的header做支持。picgo传了小写的contenttype 可能那边不认

**Comment by Molunerfinn** [comment]
> 这个是大小写问题导致的吗? 我不确定, 通过picGo上传的文件, 我通过oss-browser查看他的Content-Type显示是下面这样的.
> 
> ![图片](https://user-images.githubusercontent.com/30228406/185390091-6f43582c-992f-49d8-ae78-cec0e0f279f0.png)
> 
> 
> 
> 只要将其设置为image/jpeg就不会强制下载了.

哦？看起来是识别的但是他们不支持png类型的图片直接打开？这有点神奇。你用picgo传一张jpg的图片到阿里云看看是否能正常打开？如果可以这应该是阿里云的问题了

**Comment by Eve-Sama** [comment]
测了下, jpeg的, 上传了也不行. 我也不知道问题在哪了... 但我手动改为image/jpg就可以

**Comment by Molunerfinn** [comment]
> 测了下, jpeg的, 上传了也不行. 我也不知道问题在哪了... 但我手动改为image/jpg就可以

那看来问题应该是阿里云那边的。这边PicGo就算提供给你自定义的content-type，其实好像也解决不了问题

**Comment by Eve-Sama** [comment]
https://help.aliyun.com/document_detail/31978.htm?spm=a2c4g.11186623.0.0.348912544YJYH0#reference-l5p-ftw-tdb

我看官方文档是有支持这个参数的呀

**Comment by Molunerfinn** [comment]
> [help.aliyun.com/document_detail/31978.htm?spm=a2c4g.11186623.0.0.348912544YJYH0#reference-l5p-ftw-tdb](https://help.aliyun.com/document_detail/31978.htm?spm=a2c4g.11186623.0.0.348912544YJYH0#reference-l5p-ftw-tdb)
> 
> 我看官方文档是有支持这个参数的呀

现在的问题是PicGo有传这个参数，阿里云也读到了（你上面的oss-browser的截图里的content-type就是 PicGo 传递的）。所以就算给你自定义的 Content-Type，PicGo也是用同样的参数传递给阿里云。但是阿里云读到是 `image/***` 的 Content-Type 之后为何返回给浏览器的的 Content-Type 头不是图片类型的，这就不是 PicGo能控制的了。

为了避免大小写问题，下个版本 PicGo 传递给阿里云的 `content-type` 将改为 `Content-Type`。
