### ISSUE TITLE
[Bug]: 图片上传之后并没有成功，也无提示信息

### ISSUE THREAD

**Issue by lingluan533** [Molunerfinn/PicGo#957]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [X] [Issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)

### PicGo的版本 | PicGo Version

v2.3.0

### 系统信息 | System Information

Windows

### 问题重现 | Bug reproduce

图床正常 上传图片 没有提示信息 也没有报错 而且进度也是正常结束 但就是图片没有上传上去 gitee图床

**Comment by Molunerfinn** [comment]
gitee图床请去相关插件仓库提问。2.3.0上传后相册没有显示的 之前的issue里有说明了请自己看
