### ISSUE TITLE
[Bug]: RequestError: Error: read ECONNRESET     at new RequestError 

### ISSUE THREAD

**Issue by messchow** [Molunerfinn/PicGo#959]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [X] [Issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)

### PicGo的版本 | PicGo Version

2.3.1

### 系统信息 | System Information

Mac

### 问题重现 | Bug reproduce

使用了clashx 代理，win 和macos都是这个情况。
停止代理并退出都无法正常使用，
<img width="443" alt="image" src="https://user-images.githubusercontent.com/32609442/186179151-eac81c08-1718-4bdc-ae4b-e93a91347135.png">
尝试修改代理端口为上述的端口也不行。
我猜测肯定是代理影响到了，但是不知道怎么解决？
有没有朋友遇到过的，支支招。感谢！

### 相关日志 | Logs

<img width="650" alt="image" src="https://user-images.githubusercontent.com/32609442/186177526-fd713cdb-ef52-4dcb-b33f-a9dbd5045f99.png">

**Comment by Molunerfinn** [comment]
代理设置这里设置你的代理，看你的图，由于PicGo只支持http代理，所以设置成 `http://127.0.0.1:7890` 即可。我本地也是clashX，我是正常的。
![image](https://user-images.githubusercontent.com/12621342/186188015-ad9e2ee5-15bd-4416-896c-c27d10e53957.png)

**Comment by messchow** [comment]
> 代理设置这里设置你的代理，看你的图，由于PicGo只支持http代理，所以设置成 `http://127.0.0.1:7890` 即可。我本地也是clashX，我是正常的。 ![image](https://user-images.githubusercontent.com/12621342/186188015-ad9e2ee5-15bd-4416-896c-c27d10e53957.png)

可以了！我之前直接没填协议直接写的IP，感谢感谢！
