### ISSUE TITLE
M1版 beta5 安装之后无法打开，提示文件已损坏

### ISSUE THREAD

**Issue by nonozone** [Molunerfinn/PicGo#960]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [X] [Issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)

### PicGo的版本 | PicGo Version

Version: 2.3.1-beta.5

### 系统信息 | System Information

Mac(arm64)

### 问题重现 | Bug reproduce

<img width="260" alt="image" src="https://user-images.githubusercontent.com/1277444/186343069-5f87686b-ab66-44b2-a34f-ef8503d91347.png">

**Comment by Molunerfinn** [comment]
<img width="1122" alt="image" src="https://user-images.githubusercontent.com/12621342/186343511-feee560e-8781-46f3-86d7-231c37fa56ce.png">
安装之前都不看说明的么？
