### ISSUE TITLE
[Bug]: 在访达中直接复制一张图片后回到上传窗口，可以看到图片未显示，且上传后，图片为圈出来的这个图

### ISSUE THREAD

**Issue by wangrongding** [Molunerfinn/PicGo#961]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [X] [Issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)

### PicGo的版本 | PicGo Version

2.3.1-beta.4

### 系统信息 | System Information

Mac

### 问题重现 | Bug reproduce

在访达中直接复制一张图片后回到上传窗口，可以看到图片未显示，且上传后，图片为圈出来的这个图

<img width="310" alt="image" src="https://user-images.githubusercontent.com/42437658/186646064-f05f2eaa-b155-498c-971f-34179e78e63d.png">

**Comment by Molunerfinn** [comment]
问题已复现，会看看怎么回事

**Comment by wangrongding** [comment]
> 问题已复现，会看看怎么回事

👍

**Comment by Molunerfinn** [comment]
还有一些小问题 下个beta版本会一并更新
