### ISSUE TITLE
a[Bug]:安装包阴坏

### ISSUE THREAD

**Issue by jinfagang** [Molunerfinn/PicGo#964]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [X] [Issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)

### PicGo的版本 | PicGo Version

民间

### 系统信息 | System Information

Mac(arm64)

### 问题重现 | Bug reproduce

<img width="372" alt="image" src="https://user-images.githubusercontent.com/21303438/187072825-04cc39f8-a213-4430-93f1-e4939f67fa77.png">

### 相关日志 | Logs

<img width="372" alt="image" src="https://user-images.githubusercontent.com/21303438/187072816-81c3f2cc-ad08-4d6e-9b24-1ba41ddf0a3a.png">

**Comment by jinfagang** [comment]
<img width="375" alt="image" src="https://user-images.githubusercontent.com/21303438/187072953-18bd4cfd-2d71-4632-9858-20a8dee31a82.png">

github 土创没法用

**Comment by Molunerfinn** [comment]
请你看看faq![image](https://user-images.githubusercontent.com/12621342/187073142-48bb1b38-a6b2-4ce7-9e93-6a1c1554871a.jpeg)以及之前的关闭的issue谢谢
