### ISSUE TITLE
[Bug]: picgo重启之后就会自动上传5张空的图片

### ISSUE THREAD

**Issue by codeslive** [Molunerfinn/PicGo#968]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [X] [Issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)

### PicGo的版本 | PicGo Version

2.3.0

### 系统信息 | System Information

Windows

### 问题重现 | Bug reproduce

![image](https://user-images.githubusercontent.com/84132355/188262453-29d47658-cc80-498e-a09d-424f84b5aed7.png)

目前有办法解决吗？这是什么问题

### 相关日志 | Logs

![image](https://user-images.githubusercontent.com/84132355/188262453-29d47658-cc80-498e-a09d-424f84b5aed7.png)

目前有办法解决吗？这是什么问题

**Comment by Molunerfinn** [comment]
本体是不会自动上传图片的。你装了什么插件呢？上传的图片地址你是可以点击编辑按钮看到的

**Comment by Molunerfinn** [comment]
如果你装了githubplus插件 请去对应插件仓库提问

**Comment by codeslive** [comment]
感谢！把这个插件禁掉就没问题了
![image](https://user-images.githubusercontent.com/84132355/188268928-40e23d5c-f2e5-45cb-9630-60a6b671036b.png)
