### ISSUE TITLE
[Bug]: M1 芯片安装提示 文件已损坏。

### ISSUE THREAD

**Issue by eliassama** [Molunerfinn/PicGo#969]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [X] [Issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)

### PicGo的版本 | PicGo Version

v2.3.1-beta.4

### 系统信息 | System Information

Mac(arm64)

### 问题重现 | Bug reproduce

下载 arm 版本安装后，打开提示 “PicGo”已损坏，无法打开。 您应该将它移到废纸篓。
<img width="264" alt="image" src="https://user-images.githubusercontent.com/79587688/188305438-2c001fc1-3e72-4556-b0b8-cb512d9c39b8.png">

多次尝试下载，多个版本的 arm 安装包都是一样

**Comment by jetking** [comment]
遇到相同问题， M1 Pro 芯片

**Comment by Molunerfinn** [comment]
> 遇到相同问题， M1 Pro 芯片

FAQ里写了，麻烦看看：https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md#13-macos%E7%B3%BB%E7%BB%9F%E5%AE%89%E8%A3%85%E5%AE%8Cpicgo%E6%98%BE%E7%A4%BA%E6%96%87%E4%BB%B6%E5%B7%B2%E6%8D%9F%E5%9D%8F%E6%88%96%E8%80%85%E5%AE%89%E8%A3%85%E5%AE%8C%E6%89%93%E5%BC%80%E6%B2%A1%E6%9C%89%E5%8F%8D%E5%BA%94
