### ISSUE TITLE
Github生成链接失效

### ISSUE THREAD

**Issue by cicirori** [Molunerfinn/PicGo#97]
## 问题类型
Bug Report

## PicGo的相关信息
1.6.2 windows

## 问题重现
自动生成的失效链接：https://raw.githubusercontent.com/cicirori/my_pic_for_markdown/master/images.jpg?token=AfUwoNaNRlGtky9eqq6qthSwFwogDo4-ks5bfkCQwA%3D%3D
几分钟有效 随后404
https://raw.githubusercontent.com/cicirori/my_pic_for_markdown/master/images.jpg?token=AfUwoO_mbhHn4-Ri-ygGu24c0OMGYUXzks5bh3rlwA%3D%3D
这是直接从仓库打开的
我的仓库是private的不知道是否与这个有关

**Comment by Molunerfinn** [comment]
有关，作为图床就放在public的仓库里。

我上传的图片在public下都是正常的。PicGo拿到的地址就是GitHub回传的地址。如果你是private的仓库，自然在外界来看是无权限查看的。

附图：
https://raw.githubusercontent.com/Molunerfinn/test/master/picgo/test-%E6%B5%8B%E8%AF%95github.png
![](https://raw.githubusercontent.com/Molunerfinn/test/master/picgo/test-%E6%B5%8B%E8%AF%95github.png)
