### ISSUE TITLE
[Bug]: mac新图标在壁纸是亮色情况下还是白色

### ISSUE THREAD

**Issue by leominor46** [Molunerfinn/PicGo#970]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [X] [Issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)

### PicGo的版本 | PicGo Version

v2.3.1-beat.5

### 系统信息 | System Information

Mac

### 问题重现 | Bug reproduce

![image](https://user-images.githubusercontent.com/57203372/188541917-ae402e5f-595c-40bc-a629-f2edcb957e6e.png)
壁纸是亮色的时候图标应该变成黑色

**Comment by Molunerfinn** [comment]
系统版本是多少呢

**Comment by leominor46** [comment]
monterey 12.4
深色模式关

**Comment by Molunerfinn** [comment]
ok 回头修一下

**Comment by liwenfengg** [comment]
<img width="110" alt="Snipaste_2022-10-21_10-24-17" src="https://user-images.githubusercontent.com/40257198/197096663-329a758e-510a-4887-bf87-1d03d659a952.png">
确实

**Comment by Molunerfinn** [comment]
下个版本的图标会自动适配浅色模式
<img width="252" alt="image" src="https://user-images.githubusercontent.com/12621342/197097957-275b7896-9b60-4778-98b3-7c6f1817f44e.png">
