### ISSUE TITLE
[Bug]: 从2.3.0升级到2.3.1.6后程序列表存在两个picgo

### ISSUE THREAD

**Issue by Pil0tXia** [Molunerfinn/PicGo#972]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [X] [Issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)

### PicGo的版本 | PicGo Version

2.3.1 beta6

### 系统信息 | System Information

Windows

### 问题重现 | Bug reproduce

一开始安装了2.3.0，有一段时间没用，后来从github下载2.3.1 beta6的安装包，直接运行安装，新版正常使用，但是 控制面板-卸载程序 中picgo旧版的条目并没有消失，如图：
![image](https://user-images.githubusercontent.com/41445332/190217798-ea567ff4-252d-462a-886d-f6d9628612fc.png)
我两台电脑都出现了这个问题。
请问该如何处置？

**Comment by Molunerfinn** [comment]
手动卸载

**Comment by Pil0tXia** [comment]
> 手动卸载

在控制面板中卸载2.3.0和2.3.1beta6运行的是同一个卸载程序。卸载后2.3.1beta6条目消失，2.3.0条目还在！此时再卸载2.3.0会出现如下提示：
![image](https://user-images.githubusercontent.com/41445332/190326267-573d88e7-f4c9-407e-b41c-c7f117cc06b6.png)
请问如何处置？请reopen这个issue

**Comment by Molunerfinn** [comment]
2.3.0和2.3.1-beta.6的底层构建的electron版本已经发生变化，这里你直接点是就行了
<img width="394" alt="image" src="https://user-images.githubusercontent.com/12621342/190343490-66dbb2ba-2ff4-4935-966a-85e030ec7308.png">

**Comment by Pil0tXia** [comment]
然后再重新安装，就算解决了是吗
还好配置文件不会一并被卸载

**Comment by Molunerfinn** [comment]
是的。配置文件如果不放心的话可以设置configPath指向自己本地的一个路径。

**Comment by Molunerfinn** [comment]
<img width="907" alt="image" src="https://user-images.githubusercontent.com/12621342/190344542-a21379f0-1092-4f12-80d4-045e57d09d95.png">
