### ISSUE TITLE
[Bug]: 使用命令上传图片，生成图床链接后PicGO不会自动结束，导致程序一直在等待

### ISSUE THREAD

**Issue by PKC278** [Molunerfinn/PicGo#974]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [X] [Issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)

### PicGo的版本 | PicGo Version

2.3.1-beta.6

### 系统信息 | System Information

Mac

### 问题重现 | Bug reproduce

我在typora中使用PicGO上传图片的命令/Applications/PicGo.app/Contents/MacOS/PicGo upload，因为我不想让picgo一直在后台运行，但是生成图床链接后PicGO不会自动结束，导致typora一直在等待，希望可以让PicGO上传图片完成后自动结束进程

**Comment by Molunerfinn** [comment]
设计如此 如果要退出请你用picgo-core代替
