### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by chst365** [Molunerfinn/PicGo#975]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [X] [Issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)

### PicGo的版本 | PicGo Version

v2.3.1-beta6

### 系统信息 | System Information

Mac

### 问题重现 | Bug reproduce

github上传图片失败

### 相关日志 | Logs

"message": "maxContentLength size of Infinity exceeded",

**Comment by Molunerfinn** [comment]
你传的图片大小超过限制了。

**Comment by chst365** [comment]
也没有那么大，就几k

**Comment by Molunerfinn** [comment]
必现的话可以把图片发上来看看。以及你的上传方式是拖拽上传还是剪贴板上传

**Comment by chst365** [comment]
剪切板和拖拽上传都不可以

**Comment by Molunerfinn** [comment]
没法复现。装了什么插件么？

**Comment by chst365** [comment]
来公司上班了，是家里面的电脑，之前还好好的，昨晚尝试了一下不行，看了下日志，一直在报"message": "maxContentLength size of Infinity exceeded",

**Comment by Molunerfinn** [comment]
这是我自己刚刚传的。回去可以看看你是不是别的图床也报同样的错误，如果是，那可能是跟某些插件有关系。

https://raw.githubusercontent.com/Molunerfinn/test/master/test/202209190919649.png

**Comment by MoXiaoluo** [comment]
@chst365 , 这个问题你是怎么解决的，我也遇到同样的问题了。
