### ISSUE TITLE
[Bug]: picgo上传简书的图片无法正常显示

### ISSUE THREAD

**Issue by Pil0tXia** [Molunerfinn/PicGo#979]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [X] [Issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)

### PicGo的版本 | PicGo Version

2.3.1beta6

### 系统信息 | System Information

Windows

### 问题重现 | Bug reproduce

上传方法：
1 复制图片地址，picgo通过url上传到github中
2 复制网页粘贴到typora中，在typora中右键图片-上传图片
问题：
1 浏览器访问原简书图片地址可以正常显示，但是访问上传的图片的地址就只有一个白色方块
2 在typora中右键图片-上传图片后无法显示图片
3 github网页端、sourcetree本地图片浏览器都无法打开库中的图片

示例url：http://upload-images.jianshu.io/upload_images/4428238-fcad08ebe26933a6.png
只能复制图片再上传剪贴板图片
请问可以怎样解决？

**Comment by Molunerfinn** [comment]
简书图片有防盗链 无法直接通过url上传。只能复制图片再剪贴板上传。
