### ISSUE TITLE
是否可以增加flickr图床支持

### ISSUE THREAD

**Issue by yongman** [Molunerfinn/PicGo#98]
## 问题类型

Feature Request
## PicGo的相关信息

Mac

## 功能请求

是否可以增加flickr图床支持？
---

**Comment by Molunerfinn** [comment]
![image](https://user-images.githubusercontent.com/12621342/44524163-067cf280-a70f-11e8-8867-0de0abeebf15.png)

**Comment by Molunerfinn** [comment]
PicGo 2.0 的底层系统已经在开发中。目前可以查看[PicGo-Core](https://github.com/Molunerfinn/PicGo-Core)，目前已经实现了基本的上传流程，默认支持SM.MS。之后会将PicGo目前支持的所有图床都集成到Core里。其他图床可以由其他开发者来参考默认的图床实现来做。
