### ISSUE TITLE
[Bug]: 图片上传失败的详细复现

### ISSUE THREAD

**Issue by limingjie001** [Molunerfinn/PicGo#980]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [X] [Issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)

### PicGo的版本 | PicGo Version

2.3.1-beta.6

### 系统信息 | System Information

Windows

### 问题重现 | Bug reproduce

测试环境：使用typora并设置为“插入图片时：上传图片”
1. 将网络图片复制到typora中，typora会自动上传，**但是picgo日志显示上传成功，打开GitHub查看会发现上传的png文件是乱码**。本地md文件也无法正常显示图片。

2. 本地图片重复上述步骤功能正常。

**Comment by Molunerfinn** [comment]
你的网络图片提供一个可复现的链接？

**Comment by Molunerfinn** [comment]
beta.7修复
