### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by rothsch** [Molunerfinn/PicGo#981]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [X] [Issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)

### PicGo的版本 | PicGo Version

2.3.1-beta1

### 系统信息 | System Information

Windows

### 问题重现 | Bug reproduce

前几天还是正常的，今天突然上传失败图片失败，不断地报503错误，我采用的图床是github

### 相关日志 | Logs

  "statusCode": 503,
  "message": "Request failed with status code 503",
  "stack": {},
  "response": {
    "status": 503,
    "statusCode": 503,
    "body": ""

**Comment by Molunerfinn** [comment]
503是服务端报错，跟picgo无关。
