### ISSUE TITLE
[Bug]: 新版本macos上传失败 

### ISSUE THREAD

**Issue by hxer520** [Molunerfinn/PicGo#982]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [X] [Issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)

### PicGo的版本 | PicGo Version

v2.3.1-beta.6

### 系统信息 | System Information

Mac

### 问题重现 | Bug reproduce

上传失败，上传进度条满后显示红色。
全新系统安装的picgo，以及nodejs 16.14
图床的配置已经多次确认无误，并在另外一台macos上上传成功
本系统

![image](https://user-images.githubusercontent.com/12802662/192542164-8d66c102-9a1a-4688-8b64-06954a448fa0.png)

上传失败情况复现
![image](https://user-images.githubusercontent.com/12802662/192542395-faa51beb-cfe5-4323-acf5-a0c65e180ad7.png)

### 相关日志 | Logs

2022-09-27 21:10:05 [PicGo INFO] [PicGo Server] is listening at 36677 
2022-09-27 21:10:53 [PicGo ERROR] 
------Error Stack Begin------
Error: spawn npm ENOENT
    at Process.ChildProcess._handle.onexit (node:internal/child_process:282:19)
    at onErrorNT (node:internal/child_process:477:16)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
-------Error Stack End------- 
2022-09-27 21:10:53 [PicGo ERROR] NPM is not installed 
2022-09-27 21:10:53 [PicGo ERROR] 插件安装失败，失败码为-2，错误日志为 
  
2022-09-27 21:16:42 [PicGo SUCCESS] 插件安装成功 
2022-09-27 21:21:10 [PicGo INFO] Before transform 
2022-09-27 21:21:10 [PicGo INFO] beforeTransformPlugins: vika running 
2022-09-27 21:21:10 [PicGo INFO] Transforming... Current transformer is [path] 
2022-09-27 21:21:10 [PicGo INFO] Before upload 
2022-09-27 21:21:10 [PicGo INFO] beforeUploadPlugins: renameFn running 
2022-09-27 21:21:10 [PicGo INFO] beforeUploadPlugins: vika running 
2022-09-27 21:21:10 [PicGo INFO] Uploading... Current uploader is [vika] 
2022-09-27 21:21:10 [PicGo WARN] failed 
2022-09-27 21:21:10 [PicGo ERROR] {
  "method": "POST",
  "url": "",
  "statusCode": 0,
  "message": "Cannot read properties of null (reading 'replace')",
  "stack": "Error: Cannot read properties of null (reading 'replace')\n    at dispatchHttpRequest (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/picgo/node_modules/axios/lib/adapters/http.js:161:23)\n    at new Promise (<anonymous>)\n    at httpAdapter (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/picgo/node_modules/axios/lib/adapters/http.js:49:10)\n    at dispatchRequest (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/picgo/node_modules/axios/lib/core/dispatchRequest.js:58:10)\n    at async Uploader.uploadAttachmentsToEachRecord (/Users/ringoair/Library/Application Support/picgo/node_modules/picgo-plugin-vikadata/dist/uploader.js:47:38)\n    at async Uploader.handle (/Users/ringoair/Library/Application Support/picgo/node_modules/picgo-plugin-vikadata/dist/uploader.js:138:13)\n    at async Object.handle (/Users/ringoair/Library/Application Support/picgo/node_modules/picgo-plugin-vikadata/dist/index.js:59:17)\n    at async $e.doUpload (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/picgo/dist/index.cjs.js:1:17169)\n    at async $e.start (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/picgo/dist/index.cjs.js:1:15940)\n    at async yt.upload (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/picgo/dist/index.cjs.js:1:67044)",
  "response": {
    "status": 0,
    "statusCode": 0,
    "body": ""
  }
} 
2022-09-27 21:21:10 [PicGo ERROR] {
  "method": "POST",
  "url": "",
  "statusCode": 0,
  "message": "Cannot read properties of null (reading 'replace')",
  "stack": "Error: Cannot read properties of null (reading 'replace')\n    at dispatchHttpRequest (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/picgo/node_modules/axios/lib/adapters/http.js:161:23)\n    at new Promise (<anonymous>)\n    at httpAdapter (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/picgo/node_modules/axios/lib/adapters/http.js:49:10)\n    at dispatchRequest (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/picgo/node_modules/axios/lib/core/dispatchRequest.js:58:10)\n    at async Uploader.uploadAttachmentsToEachRecord (/Users/ringoair/Library/Application Support/picgo/node_modules/picgo-plugin-vikadata/dist/uploader.js:47:38)\n    at async Uploader.handle (/Users/ringoair/Library/Application Support/picgo/node_modules/picgo-plugin-vikadata/dist/uploader.js:138:13)\n    at async Object.handle (/Users/ringoair/Library/Application Support/picgo/node_modules/picgo-plugin-vikadata/dist/index.js:59:17)\n    at async $e.doUpload (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/picgo/dist/index.cjs.js:1:17169)\n    at async $e.start (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/picgo/dist/index.cjs.js:1:15940)\n    at async yt.upload (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/picgo/dist/index.cjs.js:1:67044)",
  "response": {
    "status": 0,
    "statusCode": 0,
    "body": ""
  }
} 
2022-09-27 21:21:24 [PicGo INFO] Before transform 
2022-09-27 21:21:24 [PicGo INFO] beforeTransformPlugins: vika running 
2022-09-27 21:21:24 [PicGo INFO] Transforming... Current transformer is [path] 
2022-09-27 21:21:24 [PicGo INFO] Before upload 
2022-09-27 21:21:24 [PicGo INFO] beforeUploadPlugins: renameFn running 
2022-09-27 21:21:24 [PicGo INFO] beforeUploadPlugins: vika running 
2022-09-27 21:21:24 [PicGo INFO] Uploading... Current uploader is [vika] 
2022-09-27 21:21:24 [PicGo WARN] failed 
2022-09-27 21:21:24 [PicGo ERROR] {
  "method": "POST",
  "url": "",
  "statusCode": 0,
  "message": "Cannot read properties of null (reading 'replace')",
  "stack": "Error: Cannot read properties of null (reading 'replace')\n    at dispatchHttpRequest (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/picgo/node_modules/axios/lib/adapters/http.js:161:23)\n    at new Promise (<anonymous>)\n    at httpAdapter (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/picgo/node_modules/axios/lib/adapters/http.js:49:10)\n    at dispatchRequest (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/picgo/node_modules/axios/lib/core/dispatchRequest.js:58:10)\n    at async Uploader.uploadAttachmentsToEachRecord (/Users/ringoair/Library/Application Support/picgo/node_modules/picgo-plugin-vikadata/dist/uploader.js:47:38)\n    at async Uploader.handle (/Users/ringoair/Library/Application Support/picgo/node_modules/picgo-plugin-vikadata/dist/uploader.js:138:13)\n    at async Object.handle (/Users/ringoair/Library/Application Support/picgo/node_modules/picgo-plugin-vikadata/dist/index.js:59:17)\n    at async $e.doUpload (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/picgo/dist/index.cjs.js:1:17169)\n    at async $e.start (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/picgo/dist/index.cjs.js:1:15940)\n    at async yt.upload (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/picgo/dist/index.cjs.js:1:67044)",
  "response": {
    "status": 0,
    "statusCode": 0,
    "body": ""
  }
} 
2022-09-27 21:21:24 [PicGo ERROR] {
  "method": "POST",
  "url": "",
  "statusCode": 0,
  "message": "Cannot read properties of null (reading 'replace')",
  "stack": "Error: Cannot read properties of null (reading 'replace')\n    at dispatchHttpRequest (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/picgo/node_modules/axios/lib/adapters/http.js:161:23)\n    at new Promise (<anonymous>)\n    at httpAdapter (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/picgo/node_modules/axios/lib/adapters/http.js:49:10)\n    at dispatchRequest (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/picgo/node_modules/axios/lib/core/dispatchRequest.js:58:10)\n    at async Uploader.uploadAttachmentsToEachRecord (/Users/ringoair/Library/Application Support/picgo/node_modules/picgo-plugin-vikadata/dist/uploader.js:47:38)\n    at async Uploader.handle (/Users/ringoair/Library/Application Support/picgo/node_modules/picgo-plugin-vikadata/dist/uploader.js:138:13)\n    at async Object.handle (/Users/ringoair/Library/Application Support/picgo/node_modules/picgo-plugin-vikadata/dist/index.js:59:17)\n    at async $e.doUpload (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/picgo/dist/index.cjs.js:1:17169)\n    at async $e.start (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/picgo/dist/index.cjs.js:1:15940)\n    at async yt.upload (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/picgo/dist/index.cjs.js:1:67044)",
  "response": {
    "status": 0,
    "statusCode": 0,
    "body": ""
  }
} 
2022-09-27 21:26:33 [PicGo INFO] Before transform 
2022-09-27 21:26:33 [PicGo INFO] beforeTransformPlugins: vika running 
2022-09-27 21:26:33 [PicGo INFO] Transforming... Current transformer is [path] 
2022-09-27 21:26:33 [PicGo INFO] Before upload 
2022-09-27 21:26:33 [PicGo INFO] beforeUploadPlugins: renameFn running 
2022-09-27 21:26:33 [PicGo INFO] beforeUploadPlugins: vika running 
2022-09-27 21:26:33 [PicGo INFO] Uploading... Current uploader is [vika] 
2022-09-27 21:26:33 [PicGo WARN] failed 
2022-09-27 21:26:33 [PicGo ERROR] {
  "method": "POST",
  "url": "",
  "statusCode": 0,
  "message": "Cannot read properties of null (reading 'replace')",
  "stack": "Error: Cannot read properties of null (reading 'replace')\n    at dispatchHttpRequest (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/picgo/node_modules/axios/lib/adapters/http.js:161:23)\n    at new Promise (<anonymous>)\n    at httpAdapter (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/picgo/node_modules/axios/lib/adapters/http.js:49:10)\n    at dispatchRequest (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/picgo/node_modules/axios/lib/core/dispatchRequest.js:58:10)\n    at async Uploader.uploadAttachmentsToEachRecord (/Users/ringoair/Library/Application Support/picgo/node_modules/picgo-plugin-vikadata/dist/uploader.js:47:38)\n    at async Uploader.handle (/Users/ringoair/Library/Application Support/picgo/node_modules/picgo-plugin-vikadata/dist/uploader.js:138:13)\n    at async Object.handle (/Users/ringoair/Library/Application Support/picgo/node_modules/picgo-plugin-vikadata/dist/index.js:59:17)\n    at async $e.doUpload (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/picgo/dist/index.cjs.js:1:17169)\n    at async $e.start (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/picgo/dist/index.cjs.js:1:15940)\n    at async yt.upload (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/picgo/dist/index.cjs.js:1:67044)",
  "response": {
    "status": 0,
    "statusCode": 0,
    "body": ""
  }
} 
2022-09-27 21:26:33 [PicGo ERROR] {
  "method": "POST",
  "url": "",
  "statusCode": 0,
  "message": "Cannot read properties of null (reading 'replace')",
  "stack": "Error: Cannot read properties of null (reading 'replace')\n    at dispatchHttpRequest (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/picgo/node_modules/axios/lib/adapters/http.js:161:23)\n    at new Promise (<anonymous>)\n    at httpAdapter (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/picgo/node_modules/axios/lib/adapters/http.js:49:10)\n    at dispatchRequest (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/picgo/node_modules/axios/lib/core/dispatchRequest.js:58:10)\n    at async Uploader.uploadAttachmentsToEachRecord (/Users/ringoair/Library/Application Support/picgo/node_modules/picgo-plugin-vikadata/dist/uploader.js:47:38)\n    at async Uploader.handle (/Users/ringoair/Library/Application Support/picgo/node_modules/picgo-plugin-vikadata/dist/uploader.js:138:13)\n    at async Object.handle (/Users/ringoair/Library/Application Support/picgo/node_modules/picgo-plugin-vikadata/dist/index.js:59:17)\n    at async $e.doUpload (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/picgo/dist/index.cjs.js:1:17169)\n    at async $e.start (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/picgo/dist/index.cjs.js:1:15940)\n    at async yt.upload (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/picgo/dist/index.cjs.js:1:67044)",
  "response": {
    "status": 0,
    "statusCode": 0,
    "body": ""
  }
} 
2022-09-27 21:28:38 [PicGo INFO] Before transform 
2022-09-27 21:28:38 [PicGo INFO] beforeTransformPlugins: vika running 
2022-09-27 21:28:38 [PicGo INFO] Transforming... Current transformer is [path] 
2022-09-27 21:28:38 [PicGo INFO] Before upload 
2022-09-27 21:28:38 [PicGo INFO] beforeUploadPlugins: renameFn running 
2022-09-27 21:28:38 [PicGo INFO] beforeUploadPlugins: vika running 
2022-09-27 21:28:38 [PicGo INFO] Uploading... Current uploader is [vika] 
2022-09-27 21:28:38 [PicGo WARN] failed 
2022-09-27 21:28:38 [PicGo ERROR] {
  "method": "POST",
  "url": "",
  "statusCode": 0,
  "message": "Cannot read properties of null (reading 'replace')",
  "stack": "Error: Cannot read properties of null (reading 'replace')\n    at dispatchHttpRequest (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/picgo/node_modules/axios/lib/adapters/http.js:161:23)\n    at new Promise (<anonymous>)\n    at httpAdapter (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/picgo/node_modules/axios/lib/adapters/http.js:49:10)\n    at dispatchRequest (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/picgo/node_modules/axios/lib/core/dispatchRequest.js:58:10)\n    at async Uploader.uploadAttachmentsToEachRecord (/Users/ringoair/Library/Application Support/picgo/node_modules/picgo-plugin-vikadata/dist/uploader.js:47:38)\n    at async Uploader.handle (/Users/ringoair/Library/Application Support/picgo/node_modules/picgo-plugin-vikadata/dist/uploader.js:138:13)\n    at async Object.handle (/Users/ringoair/Library/Application Support/picgo/node_modules/picgo-plugin-vikadata/dist/index.js:59:17)\n    at async $e.doUpload (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/picgo/dist/index.cjs.js:1:17169)\n    at async $e.start (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/picgo/dist/index.cjs.js:1:15940)\n    at async yt.upload (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/picgo/dist/index.cjs.js:1:67044)",
  "response": {
    "status": 0,
    "statusCode": 0,
    "body": ""
  }
} 
2022-09-27 21:28:38 [PicGo ERROR] {
  "method": "POST",
  "url": "",
  "statusCode": 0,
  "message": "Cannot read properties of null (reading 'replace')",
  "stack": "Error: Cannot read properties of null (reading 'replace')\n    at dispatchHttpRequest (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/picgo/node_modules/axios/lib/adapters/http.js:161:23)\n    at new Promise (<anonymous>)\n    at httpAdapter (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/picgo/node_modules/axios/lib/adapters/http.js:49:10)\n    at dispatchRequest (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/picgo/node_modules/axios/lib/core/dispatchRequest.js:58:10)\n    at async Uploader.uploadAttachmentsToEachRecord (/Users/ringoair/Library/Application Support/picgo/node_modules/picgo-plugin-vikadata/dist/uploader.js:47:38)\n    at async Uploader.handle (/Users/ringoair/Library/Application Support/picgo/node_modules/picgo-plugin-vikadata/dist/uploader.js:138:13)\n    at async Object.handle (/Users/ringoair/Library/Application Support/picgo/node_modules/picgo-plugin-vikadata/dist/index.js:59:17)\n    at async $e.doUpload (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/picgo/dist/index.cjs.js:1:17169)\n    at async $e.start (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/picgo/dist/index.cjs.js:1:15940)\n    at async yt.upload (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/picgo/dist/index.cjs.js:1:67044)",
  "response": {
    "status": 0,
    "statusCode": 0,
    "body": ""
  }
} 
2022-09-27 21:29:44 [PicGo INFO] Before transform 
2022-09-27 21:29:44 [PicGo INFO] beforeTransformPlugins: vika running 
2022-09-27 21:29:44 [PicGo INFO] Transforming... Current transformer is [path] 
2022-09-27 21:29:44 [PicGo INFO] Before upload 
2022-09-27 21:29:44 [PicGo INFO] beforeUploadPlugins: renameFn running 
2022-09-27 21:29:44 [PicGo INFO] beforeUploadPlugins: vika running 
2022-09-27 21:29:44 [PicGo INFO] Uploading... Current uploader is [vika] 
2022-09-27 21:29:44 [PicGo WARN] failed 
2022-09-27 21:29:44 [PicGo ERROR] {
  "method": "POST",
  "url": "",
  "statusCode": 0,
  "message": "Cannot read properties of null (reading 'replace')",
  "stack": "Error: Cannot read properties of null (reading 'replace')\n    at dispatchHttpRequest (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/picgo/node_modules/axios/lib/adapters/http.js:161:23)\n    at new Promise (<anonymous>)\n    at httpAdapter (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/picgo/node_modules/axios/lib/adapters/http.js:49:10)\n    at dispatchRequest (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/picgo/node_modules/axios/lib/core/dispatchRequest.js:58:10)\n    at async Uploader.uploadAttachmentsToEachRecord (/Users/ringoair/Library/Application Support/picgo/node_modules/picgo-plugin-vikadata/dist/uploader.js:47:38)\n    at async Uploader.handle (/Users/ringoair/Library/Application Support/picgo/node_modules/picgo-plugin-vikadata/dist/uploader.js:138:13)\n    at async Object.handle (/Users/ringoair/Library/Application Support/picgo/node_modules/picgo-plugin-vikadata/dist/index.js:59:17)\n    at async $e.doUpload (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/picgo/dist/index.cjs.js:1:17169)\n    at async $e.start (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/picgo/dist/index.cjs.js:1:15940)\n    at async yt.upload (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/picgo/dist/index.cjs.js:1:67044)",
  "response": {
    "status": 0,
    "statusCode": 0,
    "body": ""
  }
} 
2022-09-27 21:29:44 [PicGo ERROR] {
  "method": "POST",
  "url": "",
  "statusCode": 0,
  "message": "Cannot read properties of null (reading 'replace')",
  "stack": "Error: Cannot read properties of null (reading 'replace')\n    at dispatchHttpRequest (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/picgo/node_modules/axios/lib/adapters/http.js:161:23)\n    at new Promise (<anonymous>)\n    at httpAdapter (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/picgo/node_modules/axios/lib/adapters/http.js:49:10)\n    at dispatchRequest (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/picgo/node_modules/axios/lib/core/dispatchRequest.js:58:10)\n    at async Uploader.uploadAttachmentsToEachRecord (/Users/ringoair/Library/Application Support/picgo/node_modules/picgo-plugin-vikadata/dist/uploader.js:47:38)\n    at async Uploader.handle (/Users/ringoair/Library/Application Support/picgo/node_modules/picgo-plugin-vikadata/dist/uploader.js:138:13)\n    at async Object.handle (/Users/ringoair/Library/Application Support/picgo/node_modules/picgo-plugin-vikadata/dist/index.js:59:17)\n    at async $e.doUpload (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/picgo/dist/index.cjs.js:1:17169)\n    at async $e.start (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/picgo/dist/index.cjs.js:1:15940)\n    at async yt.upload (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/picgo/dist/index.cjs.js:1:67044)",
  "response": {
    "status": 0,
    "statusCode": 0,
    "body": ""
  }
} 
2022-09-27 21:32:07 [PicGo INFO] Before transform 
2022-09-27 21:32:07 [PicGo INFO] beforeTransformPlugins: vika running 
2022-09-27 21:32:07 [PicGo INFO] Transforming... Current transformer is [path] 
2022-09-27 21:32:07 [PicGo INFO] Before upload 
2022-09-27 21:32:07 [PicGo INFO] beforeUploadPlugins: renameFn running 
2022-09-27 21:32:07 [PicGo INFO] beforeUploadPlugins: vika running 
2022-09-27 21:32:07 [PicGo INFO] Uploading... Current uploader is [vika] 
2022-09-27 21:32:07 [PicGo WARN] failed 
2022-09-27 21:32:07 [PicGo ERROR] {
  "method": "POST",
  "url": "",
  "statusCode": 0,
  "message": "Cannot read properties of null (reading 'replace')",
  "stack": "Error: Cannot read properties of null (reading 'replace')\n    at dispatchHttpRequest (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/picgo/node_modules/axios/lib/adapters/http.js:161:23)\n    at new Promise (<anonymous>)\n    at httpAdapter (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/picgo/node_modules/axios/lib/adapters/http.js:49:10)\n    at dispatchRequest (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/picgo/node_modules/axios/lib/core/dispatchRequest.js:58:10)\n    at async Uploader.uploadAttachmentsToEachRecord (/Users/ringoair/Library/Application Support/picgo/node_modules/picgo-plugin-vikadata/dist/uploader.js:47:38)\n    at async Uploader.handle (/Users/ringoair/Library/Application Support/picgo/node_modules/picgo-plugin-vikadata/dist/uploader.js:138:13)\n    at async Object.handle (/Users/ringoair/Library/Application Support/picgo/node_modules/picgo-plugin-vikadata/dist/index.js:59:17)\n    at async $e.doUpload (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/picgo/dist/index.cjs.js:1:17169)\n    at async $e.start (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/picgo/dist/index.cjs.js:1:15940)\n    at async yt.upload (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/picgo/dist/index.cjs.js:1:67044)",
  "response": {
    "status": 0,
    "statusCode": 0,
    "body": ""
  }
} 
2022-09-27 21:32:07 [PicGo ERROR] {
  "method": "POST",
  "url": "",
  "statusCode": 0,
  "message": "Cannot read properties of null (reading 'replace')",
  "stack": "Error: Cannot read properties of null (reading 'replace')\n    at dispatchHttpRequest (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/picgo/node_modules/axios/lib/adapters/http.js:161:23)\n    at new Promise (<anonymous>)\n    at httpAdapter (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/picgo/node_modules/axios/lib/adapters/http.js:49:10)\n    at dispatchRequest (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/picgo/node_modules/axios/lib/core/dispatchRequest.js:58:10)\n    at async Uploader.uploadAttachmentsToEachRecord (/Users/ringoair/Library/Application Support/picgo/node_modules/picgo-plugin-vikadata/dist/uploader.js:47:38)\n    at async Uploader.handle (/Users/ringoair/Library/Application Support/picgo/node_modules/picgo-plugin-vikadata/dist/uploader.js:138:13)\n    at async Object.handle (/Users/ringoair/Library/Application Support/picgo/node_modules/picgo-plugin-vikadata/dist/index.js:59:17)\n    at async $e.doUpload (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/picgo/dist/index.cjs.js:1:17169)\n    at async $e.start (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/picgo/dist/index.cjs.js:1:15940)\n    at async yt.upload (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/picgo/dist/index.cjs.js:1:67044)",
  "response": {
    "status": 0,
    "statusCode": 0,
    "body": ""
  }
} 
2022-09-27 21:36:57 [PicGo INFO] Before transform 
2022-09-27 21:36:57 [PicGo INFO] beforeTransformPlugins: vika running 
2022-09-27 21:36:57 [PicGo INFO] Transforming... Current transformer is [path] 
2022-09-27 21:36:57 [PicGo INFO] Before upload 
2022-09-27 21:36:57 [PicGo INFO] beforeUploadPlugins: renameFn running 
2022-09-27 21:36:57 [PicGo INFO] beforeUploadPlugins: vika running 
2022-09-27 21:36:57 [PicGo INFO] Uploading... Current uploader is [vika] 
2022-09-27 21:36:57 [PicGo WARN] failed 
2022-09-27 21:36:57 [PicGo ERROR] {
  "method": "POST",
  "url": "",
  "statusCode": 0,
  "message": "Cannot read properties of null (reading 'replace')",
  "stack": "Error: Cannot read properties of null (reading 'replace')\n    at dispatchHttpRequest (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/picgo/node_modules/axios/lib/adapters/http.js:161:23)\n    at new Promise (<anonymous>)\n    at httpAdapter (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/picgo/node_modules/axios/lib/adapters/http.js:49:10)\n    at dispatchRequest (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/picgo/node_modules/axios/lib/core/dispatchRequest.js:58:10)\n    at async Uploader.uploadAttachmentsToEachRecord (/Users/ringoair/Library/Application Support/picgo/node_modules/picgo-plugin-vikadata/dist/uploader.js:47:38)\n    at async Uploader.handle (/Users/ringoair/Library/Application Support/picgo/node_modules/picgo-plugin-vikadata/dist/uploader.js:138:13)\n    at async Object.handle (/Users/ringoair/Library/Application Support/picgo/node_modules/picgo-plugin-vikadata/dist/index.js:59:17)\n    at async $e.doUpload (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/picgo/dist/index.cjs.js:1:17169)\n    at async $e.start (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/picgo/dist/index.cjs.js:1:15940)\n    at async yt.upload (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/picgo/dist/index.cjs.js:1:67044)",
  "response": {
    "status": 0,
    "statusCode": 0,
    "body": ""
  }
} 
2022-09-27 21:36:57 [PicGo ERROR] {
  "method": "POST",
  "url": "",
  "statusCode": 0,
  "message": "Cannot read properties of null (reading 'replace')",
  "stack": "Error: Cannot read properties of null (reading 'replace')\n    at dispatchHttpRequest (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/picgo/node_modules/axios/lib/adapters/http.js:161:23)\n    at new Promise (<anonymous>)\n    at httpAdapter (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/picgo/node_modules/axios/lib/adapters/http.js:49:10)\n    at dispatchRequest (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/picgo/node_modules/axios/lib/core/dispatchRequest.js:58:10)\n    at async Uploader.uploadAttachmentsToEachRecord (/Users/ringoair/Library/Application Support/picgo/node_modules/picgo-plugin-vikadata/dist/uploader.js:47:38)\n    at async Uploader.handle (/Users/ringoair/Library/Application Support/picgo/node_modules/picgo-plugin-vikadata/dist/uploader.js:138:13)\n    at async Object.handle (/Users/ringoair/Library/Application Support/picgo/node_modules/picgo-plugin-vikadata/dist/index.js:59:17)\n    at async $e.doUpload (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/picgo/dist/index.cjs.js:1:17169)\n    at async $e.start (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/picgo/dist/index.cjs.js:1:15940)\n    at async yt.upload (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/picgo/dist/index.cjs.js:1:67044)",
  "response": {
    "status": 0,
    "statusCode": 0,
    "body": ""
  }
}

**Comment by Molunerfinn** [comment]
请联系插件方适配新版本
