### ISSUE TITLE
[Bug]: 这几天windows版本失效，一直提示503问题，但是同样的配置在mac os x64版本下却很正常

### ISSUE THREAD

**Issue by rothsch** [Molunerfinn/PicGo#983]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [X] [Issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)

### PicGo的版本 | PicGo Version

2.3.1-beta1

### 系统信息 | System Information

Windows

### 问题重现 | Bug reproduce

从昨天开始windows上传图片 一直提示“Request failed with status code 503”，作者提示我说是端服务器的问题 ，但是mac下却非常正常，现在有些懵了，希望能够指教问题，我用的是github图床。

### 相关日志 | Logs

2022-09-28 10:13:34 [PicGo ERROR] {
  "method": "PUT",
  "statusCode": 503,
  "message": "Request failed with status code 503",
  "stack": {},
  "response": {
    "status": 503,
    "statusCode": 503,
    "body": ""
  }
}

**Comment by Molunerfinn** [comment]
这个跟你系统所处的网络环境有关系，503是服务端报错啊兄弟，PicGo不能帮你解决服务端报错的问题，PicGo只是客户端，懂了吗？
GitHub的上传国内因为有GFW的原因会有比较多的问题，你可以尝试配置PicGo的代理解决。你也说了你的mac可以上传，说明PicGo的功能是正常的，请不要再重复发帖了。

**Comment by Molunerfinn** [comment]
想要稳定的上传体验，我建议使用付费的云服务，比如腾讯云COS、阿里云OSS等一个月也就几块钱，体验好很多
