### ISSUE TITLE
[Bug]: [PicGo ERROR]: StatusCodeError: 422

### ISSUE THREAD

**Issue by danielhu19** [Molunerfinn/PicGo#985]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [X] [Issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)

### PicGo的版本 | PicGo Version

1.5.0-alpha.0

### 系统信息 | System Information

Linux

### 问题重现 | Bug reproduce

I'm using nvm, I updated the custom script to
 `/home/danielhu/.nvm/versions/node/v18.10.0/bin/node /home/danielhu/.nvm/versions/node/v18.10.0/bin/picgo u` 
as typora's contributors suggested in [https://github.com/typora/typora-issues/issues/4898](url).
And I can upload the pic from my clipboard (just 'u' as argument), but it doesn't work well in typora.
Here is my screenshot:
![image](https://user-images.githubusercontent.com/86143910/193509880-c59faa66-9e41-4465-b134-6fca62f9fd16.png)

OS name: Ubuntu 20.04.5 LTS

**Comment by danielhu19** [comment]
Already fixed it, it seems that my repository had the same file.

**Comment by danielhu19** [comment]
Already fixed it, it seems that my repository had the same file.

**Comment by sineava** [comment]
😀 thanks! i have the same problem

**Comment by SUFEHeisenberg** [comment]
Ditto error. Thanks for the solution! Just delete the same file in the remote repo will fix this error.
