### ISSUE TITLE
[Bug]: 无法打开

### ISSUE THREAD

**Issue by xq20190308** [Molunerfinn/PicGo#986]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [X] [Issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)

### PicGo的版本 | PicGo Version

v2.3.1-beta6

### 系统信息 | System Information

Windows

### 问题重现 | Bug reproduce

程序启动后自动关闭，但任务管理器中查看后台始终占用较高cpu。v2.3.0正常启动

### 相关日志 | Logs

2022-10-06 12:38:03 [PicGo INFO] [PicGo Server] is listening at 36677

**Comment by Molunerfinn** [comment]
提供一下日志

**Comment by xq20190308** [comment]
日志只有一行：
2022-10-06 12:38:03 [PicGo INFO] [PicGo Server] is listening at 36677

**Comment by Molunerfinn** [comment]
看不出问题呀，我手头也没法复现。

尝试删除配置目录下的picgo.db以及data.json后重启能打开么？删除之前建议备份一下

**Comment by xq20190308** [comment]
还是没有用，我也感觉很奇怪，而且typora也闪退，不过它是因找不到user-dict.json文件退出

**Comment by SuperNiBoby** [comment]
Mac M1Pro 为啥下载arm64的安装包打不开提示已损坏

**Comment by Molunerfinn** [comment]
> Mac M1Pro 为啥下载arm64的安装包打不开提示已损坏

因为你不看faq

**Comment by SuperNiBoby** [comment]
> > Mac M1Pro 为啥下载arm64的安装包打不开提示已损坏
> 
> 因为你不看faq

哈哈 抱歉我的

**Comment by SuperNiBoby** [comment]
> > Mac M1Pro 为啥下载arm64的安装包打不开提示已损坏
> 
> 因为你不看faq
哈哈抱歉我的大意了

**Comment by 653603927** [comment]
我也是这个情况，使用typora上传图片时，picgo首次启动会卡住，然后后台CPU占用很高，使用任务管理器强制结束后才能正常上传

**Comment by 653603927** [comment]
>`2022-11-17 19:40:35 [PicGo INFO] [PicGo Server] get the request {"list":["C:\\Users\\lxt\\AppData\\Roaming\\Typora\\typora-user-images\\image-20221117194035535.png"]} 
2022-11-17 19:40:35 [PicGo INFO] [PicGo Server] upload files in list 
2022-11-17 19:40:35 [PicGo INFO] Before transform 
2022-11-17 19:40:35 [PicGo INFO] Transforming... Current transformer is [path] `

**Comment by 653603927** [comment]
2022-11-17 19:40:35 [PicGo INFO] [PicGo Server] get the request {"list":["C:\\Users\\lxt\\AppData\\Roaming\\Typora\\typora-user-images\\image-20221117194035535.png"]} 
2022-11-17 19:40:35 [PicGo INFO] [PicGo Server] upload files in list 
2022-11-17 19:40:35 [PicGo INFO] Before transform 
2022-11-17 19:40:35 [PicGo INFO] Transforming... Current transformer is [path]

**Comment by TestCabana** [comment]
Mac M1Pro  打开时报错，“PicGo”已损坏，无法打开。 你应该将它移到废纸篓。

**Comment by Molunerfinn** [comment]
> Mac M1Pro  打开时报错，“PicGo”已损坏，无法打开。 你应该将它移到废纸篓。
> 
> 

这个请你仔细看faq最后一条。

**Comment by h198741** [comment]
我也遇到同样的情况，非常奇怪

**Comment by Jinyang79** [comment]
> 我也遇到同样的情况，非常奇怪

参考 FAQ 13
https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md

**Comment by Hiter-Q** [comment]
我的也是  重装数十次以及不同版本都是双击后无反应，但是后台显示在运行2023-04-08 18:56:16 [PicGo INFO] [PicGo Server] is listening at 36677 
2023-04-08 18:56:46 [PicGo INFO] detect second instance 
2023-04-08 18:56:53 [PicGo INFO] detect second instance 
2023-04-08 18:56:59 [PicGo INFO] detect second instance 
2023-04-08 18:57:06 [PicGo INFO] detect second instance 
2023-04-08 18:57:08 [PicGo INFO] detect second instance 
2023-04-08 18:57:43 [PicGo INFO] detect second instance 
2023-04-08 18:57:51 [PicGo INFO] detect second instance @Molunerfinn

**Comment by Molunerfinn** [comment]
> 我的也是  重装数十次以及不同版本都是双击后无反应，但是后台显示在运行2023-04-08 18:56:16 [PicGo INFO] [PicGo Server] is listening at 36677 
> 
> 2023-04-08 18:56:46 [PicGo INFO] detect second instance 
> 
> 2023-04-08 18:56:53 [PicGo INFO] detect second instance 
> 
> 2023-04-08 18:56:59 [PicGo INFO] detect second instance 
> 
> 2023-04-08 18:57:06 [PicGo INFO] detect second instance 
> 
> 2023-04-08 18:57:08 [PicGo INFO] detect second instance 
> 
> 2023-04-08 18:57:43 [PicGo INFO] detect second instance 
> 
> 2023-04-08 18:57:51 [PicGo INFO] detect second instance @Molunerfinn 
> 
> 

windows双击打开并不会显示界面，而是在右下角任务托盘 请你仔细看看文档。

**Comment by wfqyys** [comment]
我这里也打不开，装上了，鼠标点烂了没看见他开，但是任务管理器后台有，前台没有
系统：Windows11

**Comment by Nimiky** [comment]
> 我这里也打不开，装上了，鼠标点烂了没看见他开，但是任务管理器后台有，前台没有 系统：Windows11

复议，win11 安装后无法打开，双击右下角的托盘也没有，但是后台服务有，删除json也没用

**Comment by n3A87** [comment]
附议，win11安装后打不开

**Comment by chicumt** [comment]
> 附议，win11安装后打不开。太抽象了，我错了。大家从右下角可以打开！

右下角也没有
![image](https://github.com/Molunerfinn/PicGo/assets/99591215/5c7a88e5-2cf4-4de1-81af-da906c79f3cf)
![image](https://github.com/Molunerfinn/PicGo/assets/99591215/364d2da9-eefd-42b3-b412-8e5baf88acd4)

**Comment by bGZo** [comment]
Ok, check here on windows 11
![image](https://github.com/Molunerfinn/PicGo/assets/57313137/cf384646-1d0a-4e6c-9f52-ff5dba4d6b20)
