### ISSUE TITLE
[Bug]: 报错210：Can't create image from source

### ISSUE THREAD

**Issue by pp522649129** [Molunerfinn/PicGo#987]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [X] [Issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)

### PicGo的版本 | PicGo Version

v2.3.1-beta.6

### 系统信息 | System Information

Windows

### 问题重现 | Bug reproduce

本地可以上传

网站复制的图片不能上传
尝试过：百度图片，游民星空，网易游戏的都无法上传，本地的可以上传
如图：
![image](https://user-images.githubusercontent.com/48207756/194750254-c26f50c5-32d3-4a5c-9a2b-51c55d81155d.png)

### 相关日志 | Logs

2022-10-09 17:43:35 [PicGo WARN] fallback to 200 * 200 
2022-10-09 17:43:35 [PicGo INFO] Before upload 
2022-10-09 17:43:35 [PicGo INFO] beforeUploadPlugins: renameFn running 
2022-10-09 17:43:35 [PicGo INFO] Uploading... Current uploader is [chevereto] 
2022-10-09 17:43:35 [PicGo WARN] failed 
2022-10-09 17:43:35 [PicGo ERROR] {
  "method": "POST",
  "url": "http://photo.moziqing.com/api/1/upload",
  "statusCode": 400,
  "message": "Request failed with status code 400",
  "stack": {},
  "response": {
    "status": 400,
    "statusCode": 400,
    "body": {
      "status_code": 400,
      "error": {
        "message": "Can't create image from source",
        "code": 210,
        "context": "CHV\\ImageException"
      },
      "status_txt": "Bad Request"
    }
  }
} 
2022-10-09 17:43:35 [PicGo ERROR] {
  "method": "POST",
  "url": "http://photo.moziqing.com/api/1/upload",
  "statusCode": 400,
  "message": "Request failed with status code 400",
  "stack": {},
  "response": {
    "status": 400,
    "statusCode": 400,
    "body": {
      "status_code": 400,
      "error": {
        "message": "Can't create image from source",
        "code": 210,
        "context": "CHV\\ImageException"
      },
      "status_txt": "Bad Request"
    }
  }
}

**Comment by Molunerfinn** [comment]
并不是所有的链接都可以做为图片链接上传的（防盗链、登录态等等）。遇到图片链接无法直接上传的，请手动复制图片文件（而非图片链接）到剪贴板再上传。

这个不是PicGo的问题。
