### ISSUE TITLE
通过快捷键上传剪贴板中的图片会导致上传的文件和原文件不同

### ISSUE THREAD

**Issue by iwestlin** [Molunerfinn/PicGo#99]
## 问题类型
我也不知道这算bug还是feature……

## 问题重现
通过快捷键上传剪贴板的文件后，再从图床上把图片下载下来，容易发现明显大小都不一样，虽然图片看上去是一样的……但有时候用户想保持文件hash不变。。
问题应该出在这一行：https://github.com/Molunerfinn/PicGo/blob/fc56d07ab28c4f8c9cc4a50fca09e28a4bf1bf97/src/main/index.js#L334
还有就是好像通过剪贴板上传gif会变成png？
我对electron不熟，有没有办法在按下快捷键的时候，读到剪贴板中的文件路径，然后走imgFromPath这一套？

**Comment by iwestlin** [comment]
在这里：https://github.com/electron/electron/issues/9035#issuecomment-359554116 找到了答案
```js
// Mac上可以通过这种方式获取剪贴板中的文件路径，支持多个文件
const plist = require('plist')
const filelist = plist.parse(clipboard.read('NSFilenamesPboardType'))
```

**Comment by Molunerfinn** [comment]
@iwestlin 快捷键上传的时候由于electron剪贴板的限制只能读取成PNG格式。所以会和原先的图片有所出入。
主要是考虑到截图、网页图片复制等情况，这种情况下图片在计算机里是没有存储的路径的，但是图片在剪贴板里，所以不适宜用剪贴板读取路径的方式获取图片，而是直接从剪贴版里拿图片。

剪贴板上传只是为了图快，如果是想要保证文件完整性的话，还是推荐通过拖拽到顶部栏的图标进行上传。

当然你提供的思路也很好，可以考虑之后看看如何实现。

**Comment by riskers** [comment]
今天也遇到了，gif 图片通过快捷键上传的时候会编程 png

**Comment by Molunerfinn** [comment]
@riskers 快捷键上传目前只能转成png。

**Comment by riskers** [comment]
@Molunerfinn 那我觉得如果在上传成功后提示一下用户会比较合理，因为用户很有可能会没有注意到 gif 变成 png 了

**Comment by Molunerfinn** [comment]
@riskers 2.0的版本里会在新的文档里注明。另外现在上传成功后都有提醒，一般来说都会给出图片上传后的地址，图片会有后缀。

**Comment by riskers** [comment]
@riskers 恩 我知道会给出地址，我觉得其他格式无所谓，gif 应该给出提示，因为一般使用这个功能的时候在写博客，都没注意就变成了 PNG。

**Comment by Molunerfinn** [comment]
额，通常这种情况我是无法知道你拿到的是gif还是png。通过系统剪贴板获取的图片信息就是png。

**Comment by riskers** [comment]
哦 我以为能通过文件后缀来判断。。

**Comment by gengchen528** [comment]
嗯 确实会有这个问题，关键一开始没注意，后来发现本来只有几十K的jpg图片，通过系统剪贴板上传后不仅成了png，体积变成了五六M大，好几次发现加载图片慢，原来是这个原因（ 囧），还是老实用详情页选择文件上传  哈哈

**Comment by bearcai** [comment]
> 嗯 确实会有这个问题，关键一开始没注意，后来发现本来只有几十K的jpg图片，通过系统剪贴板上传后不仅成了png，体积变成了五六M大，好几次发现加载图片慢，原来是这个原因（ 囧），还是老实用详情页选择文件上传 哈哈

感谢，终于搞清楚原因了
