### ISSUE TITLE
[Bug]: imgurl图床的接口挂了

### ISSUE THREAD

**Issue by wintsa123** [Molunerfinn/PicGo#990]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [X] [Issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)

### PicGo的版本 | PicGo Version

最新

### 系统信息 | System Information

Windows

### 问题重现 | Bug reproduce

imgurl的接口挂了，clentid我是手动抓的。没用，imgurl后台提供了api和token上传，作者要不改改地址？作者的项目框架太乱了，我新手前端想开发也修改不了。

**Comment by Molunerfinn** [comment]
接口挂了指的是什么 官方改了上传接口吗？imgur上传国内需要代理 你配置了吗？上传挂了的日志呢

**Comment by Molunerfinn** [comment]
经测试接口正常。imgur国内上传已经被封禁，要上传请检查自己的代理配置。

**Comment by Molunerfinn** [comment]
![image](https://user-images.githubusercontent.com/12621342/195608919-fd6c0ae8-ceb9-4f7c-b7ad-6759acd37a74.png)
