### ISSUE TITLE
[Bug]: 这个/d//这个怎么去掉 要不然这个路径总是错误

### ISSUE THREAD

**Issue by TurkeyD** [Molunerfinn/PicGo#991]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [X] [Issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)

### PicGo的版本 | PicGo Version

2.3.1-beta2

### 系统信息 | System Information

Mac

### 问题重现 | Bug reproduce

使用的是这个版本
![image](https://user-images.githubusercontent.com/69117862/196027969-990d6a61-c69e-449b-9df3-9c4ecf9f1c25.png)
可以显示上传成功    
![image](https://user-images.githubusercontent.com/69117862/196027891-563ec983-e9fd-460d-8036-865f63a6f842.png)
但是无论V2还是v3都会添加/d//这个 字符
导致最终失败 
![image](https://user-images.githubusercontent.com/69117862/196027824-79c766fa-13d0-4ea8-8f2f-9a1c80951e46.png)
请问 这个/d//这个怎么去掉  要不然这个路径总是错误

**Comment by Molunerfinn** [comment]
请联系你使用的这个插件的作者
