### ISSUE TITLE
obsidian上传兰空相册，编码http地址里的冒号和斜杠[Bug]: 

### ISSUE THREAD

**Issue by agongx** [Molunerfinn/PicGo#999]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [X] [Issues](https://github.com/Molunerfinn/PicGo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Molunerfinn/PicGo/blob/dev/FAQ.md)

### PicGo的版本 | PicGo Version

2.3.1-beta.7

### 系统信息 | System Information

Windows

### 问题重现 | Bug reproduce

用obsidian自动上传照片，贴在文件里的markdown格式网址，所有的冒号和斜杠被编码，`https://`变为`https%3A%2F%2F ` ，导致obsidian无法加载图片，剪贴板理的地址是正常的，使用2.3.0最新版没有此问题

**Comment by Molunerfinn** [comment]
重复issue#996 问题已知下个版本会修复
